Repository bcgov/PSP, pull requests merged in 2021-07, with the labels that each got.

#96 Psp 1421 add reverse geocoder lookup api and frontend POC with unit tests.
  backend/api/Areas/Tools/Controllers/GeocoderController.cs
  backend/geocoder/Extensions/ParameterExtensions.cs
  backend/geocoder/GeocoderService.cs
  backend/geocoder/IGeocoderService.cs
  backend/geocoder/Parameters/AddressesParameters.cs
  backend/geocoder/Parameters/BaseParameters.cs
  backend/geocoder/Parameters/NearParameters.cs
  backend/geocoder/Parameters/NearestParameters.cs
  backend/tests/unit/api/Controllers/Tools/GeocoderControllerTest.cs
  backend/tests/unit/dal/Libraries/Geocoder/GeocoderServiceTest.cs
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.test.tsx
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.tsx
  frontend/src/hooks/useApi.ts
Labels: enhancement

#103 Help desk tests
  backend/tests/unit/dal/Services/Admin/BuildingServiceTest.cs
  frontend/package-lock.json
  frontend/src/components/common/ErrorModal.test.tsx
  frontend/src/components/common/__snapshots__/ErrorModal.test.tsx.snap
  frontend/src/features/help/components/HelpBox.test.tsx
  frontend/src/features/help/components/HelpSubmitBox.test.tsx
  frontend/src/features/help/components/__snapshots__/HelpBox.test.tsx.snap
  frontend/src/features/help/components/__snapshots__/HelpSubmitBox.test.tsx.snap
  frontend/src/features/help/containers/HelpContainer.test.tsx
  frontend/src/features/help/containers/HelpModalContentContainer.test.tsx
  frontend/src/features/help/containers/__snapshots__/HelpContainer.test.tsx.snap
  frontend/src/features/help/containers/__snapshots__/HelpModalContentContainer.test.tsx.snap
  frontend/src/utils/TestCommonWrapper.tsx
Labels: unit-tests

#102 Correct 404 errors when zooming too far into the new map.
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/constants/strings.tsx
Labels: bug

#105 Ensure that updated jwt token used for all requests.
  frontend/src/customAxios.ts
Labels: bug

#107 PSP-1280 Center Logo and Title.
  frontend/src/features/account/LoginStyled.tsx
  frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
Labels: bug

#101 PIMS LOGGING
  openshift/4.0/templates/Logging/Dockerfile
  openshift/4.0/templates/Logging/README.md
  openshift/4.0/templates/Logging/docker-compose.yml
  openshift/4.0/templates/Logging/logging_dc.yaml
  openshift/4.0/templates/Logging/oclogbc.yaml
  openshift/4.0/templates/Logging/role-binding.yaml
  openshift/4.0/templates/Logging/sidecar-logging.sh
Labels: logging

#109 psp-1004 dropdown does not scale.
  frontend/src/components/layout/Header/UserProfile.tsx
Labels: bug

#108 PSP-1444 Fix Agency Administration - Concurrency
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.test.tsx
  frontend/src/constants/index.ts
  frontend/src/features/admin/agencies/EditAgencyPage.tsx
  frontend/src/interfaces/IAccessRequest.ts
  frontend/src/mocks/filterDataMock.ts
  frontend/src/store/slices/agencies/agencyActionCreator.test.tsx
  frontend/src/store/slices/agencies/useAgencies.ts
  frontend/src/store/slices/lookupCodes/interfaces/ILookupCode.ts
  frontend/src/store/slices/properties/useProperties.test.tsx
Labels: bug

#111 Test tsc corrections.
  frontend/package.json
  frontend/src/components/Table/PageSizeSelector.test.tsx
  frontend/src/components/Table/Table.tsx
  frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  frontend/src/components/layout/Header/Header.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.test.tsx
  frontend/src/features/admin/access/ManageAccessRequests.test.tsx
  frontend/src/features/admin/access/components/Details.test.tsx
  frontend/src/features/admin/agencies/EditAgencyPage.test.tsx
  frontend/src/features/admin/agencies/ManageAgencies.test.tsx
  frontend/src/layouts/Header.test.tsx
  frontend/src/store/slices/agencies/agencyActionCreator.test.tsx
  frontend/src/store/slices/users/usersReducer.test.tsx
Labels: enhancement

#110 PSP-911 Update Keycloak Sync Config
  backend/api/Areas/Admin/Mapping/User/RoleMap.cs
  openshift/3.11/MULTIPLE_INSTANCES.md
  openshift/3.11/templates/pims-api/deploy.yaml
  openshift/3.11/templates/pims-app/deploy.yaml
  openshift/3.11/templates/resources/api-sso-configMap.yaml
  openshift/3.11/templates/resources/app-sso-configMap.yaml
  openshift/4.0/templates/app/deploy.yaml
  test/Postman/pims-api-collection.json
  tools/import/appsettings.Development.json
  tools/import/appsettings.Production.json
  tools/import/appsettings.Test.json
  tools/import/appsettings.json
  tools/keycloak/sync/SyncFactory.cs
  tools/keycloak/sync/appsettings.development.json
  tools/keycloak/sync/appsettings.test.json
  tools/keycloak/sync/realm.development.json
  tools/keycloak/sync/realm.test.json
Labels: bug

#113 Correct concurrency error when updating users.
  backend/api/Areas/Admin/Mapping/User/AgencyMap.cs
  backend/api/Areas/Admin/Mapping/User/UserMap.cs
  backend/api/Areas/Keycloak/Mapping/User/AgencyMap.cs
  backend/api/Areas/Keycloak/Mapping/User/UserMap.cs
  backend/dal/Services/Admin/Concrete/UserService.cs
  frontend/src/features/admin/edit-user/EditUserPage.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  frontend/src/interfaces/userDetails.ts
  frontend/src/store/slices/users/useUsers.ts
  frontend/src/store/slices/users/usersReducer.test.tsx
  frontend/src/store/slices/users/usersSlice.ts
Labels: bug

#112 Fix Keycloak test configuration
  tools/keycloak/sync/realm.test.json
Labels: enhancement

#114 configuration updates
  openshift/4.0/templates/api/deploy.yaml
  openshift/4.0/templates/app/deploy.yaml
  tools/keycloak/sync/realm.development.json
Labels: bug, enhancement

#104 PSP-1481 Update frontend to React 17
  Makefile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SearchBar/FilterBar.test.tsx
  frontend/src/components/Table/PageSizeSelector.test.tsx
  frontend/src/components/common/form/FastCurrencyInput.test.tsx
  frontend/src/components/common/form/LimitedSelect.test.tsx
  frontend/src/components/common/form/ParentSelect.test.tsx
  frontend/src/components/common/form/__snapshots__/FastCurrencyInput.test.tsx.snap
  frontend/src/components/layout/AppNavBar/AppNavBar.test.tsx
  frontend/src/components/maps/BasemapToggle.test.tsx
  frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.test.tsx
  frontend/src/components/maps/leaflet/LayersControl/LayersControl.test.tsx
  frontend/src/components/maps/leaflet/MapProperties.test.tsx
  frontend/src/features/account/Logout.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.test.tsx
  frontend/src/features/admin/access/ManageAccessRequests.test.tsx
  frontend/src/features/admin/access/components/Details.test.tsx
  frontend/src/features/admin/access/components/RowActions.test.tsx
  frontend/src/features/admin/agencies/EditAgencyPage.test.tsx
  frontend/src/features/admin/users/ManageUsers.test.tsx
  frontend/src/features/admin/users/components/RowActions.test.tsx
  frontend/src/features/help/components/HelpBox.test.tsx
  frontend/src/features/mapSideBar/containers/MotiInventoryContainer.test.tsx
  frontend/src/features/mapSideBar/containers/__snapshots__/MotiInventoryContainer.test.tsx.snap
  frontend/src/features/mapSideBar/forms/PropertyForm.test.tsx
  frontend/src/features/properties/filter/PropertyFilter.test.tsx
  frontend/src/features/properties/list/PropertyListView.test.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/hooks/pims-api/useApi.test.ts
  frontend/src/hooks/useMyAgencies.test.tsx
  frontend/src/router.test.tsx
  frontend/src/setupTests.ts
  frontend/src/store/slices/tenants/useTenants.test.tsx
  frontend/src/utils/testUtils.ts
Labels: dependencies, frontend

#115 Psp 1051 add electoral district.
  frontend/src/components/maps/leaflet/LayersControl/data.ts
Labels: enhancement, gis

#119 update manifest, further address lighthouse report.
  frontend/config-overrides.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/manifest.json
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: enhancement

#121 psp-862
  frontend/package-lock.json
  frontend/package.json
Labels: tech-debt

#116 psp-1478 initial ETL proof of concept migrations.
  .gitignore
  etl/PAIMS_PIMS/PAIMS_PIMS.sln
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.database
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj.user
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_AREA_UNIT_Load.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_PROPERTY_Load.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_PROPERTY_TENURE_TYPE_Load.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/Project.params
  etl/PAIMS_PIMS/PAIMS_PIMS/lizzard.th.gov.bc.ca.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/sqldevtst.th.gov.bc.ca.conmgr
Labels: etl

#117 Node 14 updates.
  .github/workflows/app-react.yml
  frontend/Dockerfile
  openshift/4.0/templates/app/README.md
  openshift/4.0/templates/app/build.yaml
  openshift/4.0/templates/base-images/nodejs-14-ubi8.yaml
  openshift/4.0/templates/jenkins-slaves/README.md
  openshift/4.0/templates/jenkins-slaves/dotnet-jenkins-slave.yaml
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-dotnet/Dockerfile
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-dotnet/README.md
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-npm/Dockerfile
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-npm/README.md
  openshift/4.0/templates/jenkins-slaves/node10-jenkins-slave.yaml
Labels: devops, enhancement

#125 PSP-1488 create a storage that accept binary upload via http or https
  openshift/4.0/templates/Logging/.dockerignore
  openshift/4.0/templates/Logging/Dockerfile
  openshift/4.0/templates/Logging/README.md
  openshift/4.0/templates/Logging/bin/s3-get
  openshift/4.0/templates/Logging/bin/s3-put
  openshift/4.0/templates/Logging/docker-compose.yml
  openshift/4.0/templates/Logging/lib/s3-common.sh
  openshift/4.0/templates/Logging/logging_dc.yaml
  openshift/4.0/templates/Logging/oclogbc.yaml
  openshift/4.0/templates/Logging/sidecar-logging.sh
Labels: logging

#126 correct unicode conversion.
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_AREA_UNIT_Load.dtsx
Labels: etl

#127 Frontend Unit Tests
  frontend/src/components/common/GenericModal.test.tsx
  frontend/src/components/common/TooltipIcon.tsx
  frontend/src/components/common/__snapshots__/GenericModal.test.tsx.snap
  frontend/src/components/common/form/ParentSelect.test.tsx
  frontend/src/components/common/form/__snapshots__/FastCurrencyInput.test.tsx.snap
  frontend/src/components/menu/Menu.test.tsx
  frontend/src/components/menu/__snapshots__/Menu.test.tsx.snap
  frontend/src/features/admin/agencies/AgencyFilterBar.test.tsx
  frontend/src/features/admin/agencies/__snapshots__/AgencyFilterBar.test.tsx.snap
  frontend/src/features/admin/users/components/RowActions.tsx
  frontend/src/features/mapSideBar/components/InventoryFormButtons.test.tsx
  frontend/src/features/mapSideBar/components/MapSideBarLayout.test.tsx
  frontend/src/features/mapSideBar/components/__snapshots__/InventoryFormButtons.test.tsx.snap
  frontend/src/features/mapSideBar/components/__snapshots__/MapSideBarLayout.test.tsx.snap
  frontend/src/features/properties/components/GeocoderAutoComplete.test.tsx
  frontend/src/features/properties/components/__snapshots__/GeocoderAutoComplete.test.tsx.snap
  frontend/src/features/properties/filter/PropertyFilterAgencyOptions.test.tsx
  frontend/src/features/properties/filter/PropertyFilterOptions.test.tsx
  frontend/src/features/properties/filter/__snapshots__/PropertyFilterAgencyOptions.test.tsx.snap
  frontend/src/features/properties/filter/__snapshots__/PropertyFilterOptions.test.tsx.snap
Labels: unit-tests
