Repository bcgov/PSP, pull requests merged in 2021-05, with the labels that each got.

#4 Correct projectConverter test failures.
  frontend/src/features/projects/common/projectConverter.test.tsx
  frontend/src/features/projects/dispose/testUtils.ts
  frontend/src/mocks/filterDataMock.ts
Labels: bug

#10 psp-698 Tenant Configuration
  .vscode/launch.json
  .vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/layout/Header/ErrorModal.tsx
  frontend/src/components/layout/Header/Header.test.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
  frontend/src/tenants/CITZ/config.ts
  frontend/src/tenants/ITenantConfig.ts
  frontend/src/tenants/MOTI/config.ts
  frontend/src/tenants/index.ts
  frontend/src/tenants/tenant.test.ts
  frontend/src/tenants/tenant.ts
Labels: enhancement, unit-tests

#6 Remove dead code uncovered by test coverage.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/form/DisplayCurrency.scss
  frontend/src/components/common/form/DisplayCurrency.tsx
  frontend/src/components/common/form/Field.tsx
  frontend/src/components/common/form/index.ts
  frontend/src/components/maps/leaflet/LeafletDraw/LeafletDraw.md
  frontend/src/components/maps/leaflet/LeafletDraw/LeafletDraw.scss
  frontend/src/components/maps/leaflet/LeafletDraw/LeafletDraw.tsx
  frontend/src/components/maps/leaflet/LeafletDraw/index.ts
  frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedBuildingListForm.scss
  frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedBuildingListForm.tsx
  frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedLandListForm.tsx
  frontend/src/features/mapSideBar/SidebarContents/subforms/LeasedLandOwned.tsx
  frontend/src/features/projects/common/hooks/useAgencyResponseTable.tsx
  frontend/src/features/projects/common/index.ts
Labels: tech-debt

#5 test updates related to mapsidebar functionality
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
  frontend/src/features/mapSideBar/SidebarContents/BuildingForm.test.tsx
  frontend/src/features/mapSideBar/SidebarContents/BuildingForm.tsx
  frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
  frontend/src/features/mapSideBar/SidebarContents/__snapshots__/LandForm.test.tsx.snap
  frontend/src/features/mapSideBar/SidebarContents/subforms/LandSearchForm.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.test.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarGeocoder.test.tsx
  frontend/src/features/properties/hooks/useGeocoder.tsx
Labels: unit-tests

#11 Update keycloak, react-keycloak. Includes fixes for breaking changes.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.test.tsx
  frontend/src/features/admin/access/ManageAccessRequests.test.tsx
  frontend/src/features/admin/agencies/EditAgencyPage.test.tsx
  frontend/src/features/admin/agencies/ManageAgencies.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.test.tsx
  frontend/src/features/admin/users/ManageUsers.test.tsx
  frontend/src/features/mapSideBar/SidebarContents/subforms/AddParentParcelsForm.test.tsx
  frontend/src/features/projects/common/forms/UpdateInfoForm.test.tsx
  frontend/src/features/projects/dispose/ProjectDisposeLayout.test.tsx
  frontend/src/features/projects/dispose/ProjectDisposeView.test.tsx
  frontend/src/features/projects/dispose/steps/DocumentationStep.test.tsx
  frontend/src/features/projects/dispose/steps/ProjectDraftStep.test.tsx
  frontend/src/features/projects/dispose/steps/ReviewProjectStep.test.tsx
  frontend/src/features/projects/erp/tabs/EnhancedReferralTab.test.tsx
  frontend/src/features/projects/list/ProjectApprovalRequest.test.tsx
  frontend/src/index.tsx
  frontend/src/utils/KeycloakEventHandler.test.ts
  frontend/src/utils/KeycloakEventHandler.ts
  frontend/src/utils/YupSchema.ts
Labels: enhancement

#14 PSP-676 Add Tenant Logos and text
  frontend/public/tenants/CITZ/favicon-16x16.ico
  frontend/public/tenants/CITZ/logo_only.png
  frontend/public/tenants/CITZ/logo_with_text.png
  frontend/public/tenants/MOTI/PIMS-logo-with-text.png
  frontend/public/tenants/MOTI/PIMS-logo.png
  frontend/public/tenants/MOTI/favicon.ico
  frontend/src/App.tsx
  frontend/src/components/common/BCGovLogo.tsx
  frontend/src/components/layout/Header/EmptyHeader.tsx
  frontend/src/components/layout/Header/Header.test.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/__snapshots__/EmptyHeader.test.tsx.snap
  frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
  frontend/src/features/account/IENotSupportedPage.tsx
  frontend/src/features/account/Login.test.tsx
  frontend/src/features/account/Login.tsx
  frontend/src/features/account/LoginLoading.tsx
  frontend/src/features/account/__snapshots__/IENotSupportedPage.test.tsx.snap
  frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  frontend/src/features/admin/access/ManageAccessRequests.tsx
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
  frontend/src/layouts/__snapshots__/EmptyLayout.test.tsx.snap
  frontend/src/tenants/CITZ/config.ts
  frontend/src/tenants/ITenantConfig.ts
  frontend/src/tenants/Logo.tsx
  frontend/src/tenants/MOTI/config.ts
  frontend/src/tenants/index.ts
  frontend/src/tenants/tenant.test.ts
  frontend/src/tenants/tenant.ts
Labels: enhancement

#12 PSP-614 Remove old app name
  maintenance/maintenance.html
Labels: enhancement

#13 update dependencies, correct breaking changes.
  frontend/.vscode/launch.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/manifest.json
  frontend/src/components/SearchBar/__snapshots__/FilterBar.test.tsx.snap
  frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  frontend/src/components/common/ErrorTabs.tsx
  frontend/src/components/common/Stepper.tsx
  frontend/src/components/common/TooltipWrapper.tsx
  frontend/src/components/common/form/Button.tsx
  frontend/src/components/common/form/Check.tsx
  frontend/src/components/common/form/ParentSelect.tsx
  frontend/src/components/common/form/StepForm/SteppedForm.tsx
  frontend/src/components/common/form/StepForm/__snapshots__/SteppedForm.test.tsx.snap
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.test.tsx.snap
  frontend/src/components/maps/hooks/useSupercluster.ts
  frontend/src/components/maps/leaflet/MapProperties.test.tsx
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
  frontend/src/features/admin/access/components/__snapshots__/AccessRequestActions.test.tsx.snap
  frontend/src/features/admin/agencies/__snapshots__/EditAgencyPage.test.tsx.snap
  frontend/src/features/admin/agencies/__snapshots__/ManageAgencies.test.tsx.snap
  frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
  frontend/src/features/mapSideBar/SidebarContents/AssociatedLandForm.tsx
  frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
  frontend/src/features/mapSideBar/SidebarContents/__snapshots__/LandForm.test.tsx.snap
  frontend/src/features/mapSideBar/SidebarContents/__snapshots__/SubmitPropertySelector.test.tsx.snap
  frontend/src/features/mapSideBar/SidebarContents/subforms/AddParentParcelsForm.tsx
  frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingReviewPage.test.tsx.snap
  frontend/src/features/mapSideBar/hooks/useQueryParamSideBar.tsx
  frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
  frontend/src/features/projects/common/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
  frontend/src/features/projects/dispose/__snapshots__/ProjectDisposeLayout.test.tsx.snap
  frontend/src/features/projects/dispose/forms/__snapshots__/PropertyListViewSelect.test.tsx.snap
  frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
  frontend/src/features/projects/erp/forms/AgencyInterest.tsx
  frontend/src/features/projects/erp/forms/EnhancedReferralCompleteForm.tsx
  frontend/src/features/projects/erp/forms/ExemptionEnhancedReferralCompleteForm.tsx
  frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
  frontend/src/features/projects/erp/steps/__snapshots__/GreTransferStep.test.tsx.snap
  frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequest.test.tsx.snap
  frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
  frontend/src/features/projects/spl/forms/SurplusPropertyListForm.tsx
  frontend/src/features/projects/spl/steps/SplStep.test.tsx
  frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
  frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/features/splReports/components/ReportControls.tsx
  frontend/src/hooks/useDeepCompareMemoize.ts
  frontend/src/layouts/PublicLayout.tsx
  frontend/src/setupProxy.js
  frontend/src/setupTests.ts
  frontend/src/utils/YupSchema.ts
  frontend/tsconfig.json
Labels: enhancement, tech-debt

#20 Fixes for test failures in dev.
  frontend/.husky/.gitignore
  frontend/.husky/_/husky.sh
  frontend/.husky/pre-commit
  frontend/.husky/pre-push
  frontend/.vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/maps/leaflet/MapProperties.test.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.test.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarGeocoder.test.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/setupTests.ts
  frontend/tsconfig.json
Labels: bug

#18 PSP_659 replace access request redux components with slice. (#2)
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/actionCreators/accessRequestActionCreator.spec.ts
  frontend/src/actionCreators/accessRequestActionCreator.ts
  frontend/src/actions/accessRequestActions.ts
  frontend/src/constants/reducerTypes.ts
  frontend/src/customAxios.ts
  frontend/src/features/admin/access-request/AccessRequestPage.tsx
  frontend/src/features/admin/access/ManageAccessRequests.tsx
  frontend/src/features/admin/access/components/AccessRequestActions.tsx
  frontend/src/features/admin/access/components/Filter.tsx
  frontend/src/features/admin/access/components/RowActions.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/hooks/useApi.ts
  frontend/src/index.tsx
  frontend/src/mocks/filterDataMock.ts
  frontend/src/reducers/accessRequestReducer.ts
  frontend/src/reducers/rootReducer.ts
  frontend/src/store/hooks.ts
  frontend/src/store/slices/accessRequests/accessRequestsActionCreator.spec.tsx
  frontend/src/store/slices/accessRequests/accessRequestsReducer.test.tsx
  frontend/src/store/slices/accessRequests/accessRequestsSlice.ts
  frontend/src/store/slices/accessRequests/index.ts
  frontend/src/store/slices/accessRequests/interfaces/IAccessRequestsFilterData.ts
  frontend/src/store/slices/accessRequests/interfaces/IAccessRequestsSort.ts
  frontend/src/store/slices/accessRequests/interfaces/IAccessRequestsState.ts
  frontend/src/store/slices/accessRequests/interfaces/index.ts
  frontend/src/store/slices/accessRequests/useAccessRequests.ts
  frontend/src/store/store.ts
  frontend/src/utils/KeycloakEventHandler.test.ts
  frontend/src/utils/KeycloakEventHandler.ts
Labels: tech-debt

#19 Tenant Configuration
  frontend/package-lock.json
  frontend/public/tenants/tenant.json
  frontend/src/App.tsx
  frontend/src/components/layout/Header/EmptyHeader.test.tsx
  frontend/src/components/layout/Header/EmptyHeader.tsx
  frontend/src/components/layout/Header/Header.test.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/__snapshots__/EmptyHeader.test.tsx.snap
  frontend/src/features/account/IENotSupportedPage.test.tsx
  frontend/src/features/account/IENotSupportedPage.tsx
  frontend/src/features/account/Login.test.tsx
  frontend/src/features/account/Login.tsx
  frontend/src/features/account/LoginLoading.test.tsx
  frontend/src/features/account/__snapshots__/IENotSupportedPage.test.tsx.snap
  frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  frontend/src/features/admin/access/ManageAccessRequests.test.tsx
  frontend/src/features/admin/access/ManageAccessRequests.tsx
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.test.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarGeocoder.test.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/index.tsx
  frontend/src/layouts/EmptyLayout.test.tsx
  frontend/src/layouts/__snapshots__/EmptyLayout.test.tsx.snap
  frontend/src/tenants/Logo.tsx
  frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  frontend/src/tenants/config/CITZ.ts
  frontend/src/tenants/config/MOTI.ts
  frontend/src/tenants/config/default.ts
  frontend/src/tenants/config/index.ts
  frontend/src/tenants/index.ts
  frontend/src/tenants/tenant.test.ts
  frontend/src/tenants/tenant.test.tsx
  frontend/src/tenants/tenant.ts
  frontend/src/tenants/tenant.tsx
  frontend/src/tenants/useTenant.test.tsx
  frontend/src/tenants/useTenant.ts
  openshift/4.0/templates/app/deploy - Copy.yaml
  openshift/4.0/templates/app/deploy.yaml
  openshift/s2i/nginx-runtime/nginx-runtime.yaml
Labels: enhancement

#21 PSP-665 Update Nuget Packages
  backend/api/Pims.Api.csproj
  backend/ches/Pims.Ches.csproj
  backend/core/Pims.Core.csproj
  backend/dal.keycloak/Pims.Dal.Keycloak.csproj
  backend/dal/Pims.Dal.csproj
  backend/entities/Pims.Dal.Entities.csproj
  backend/geocoder/Pims.Geocoder.csproj
  backend/keycloak/Pims.Keycloak.csproj
  backend/notifications/Pims.Notifications.csproj
  backend/tests/core/Pims.Core.Test.csproj
  backend/tests/unit/api/Controllers/Reports/ProjectControllerTest.cs
  backend/tests/unit/api/Controllers/Reports/UserControllerTest.cs
  backend/tests/unit/api/Pims.Api.Test.csproj
  backend/tests/unit/dal/Pims.Dal.Test.csproj
Labels: enhancement, tech-debt

#23 PSP-665 Fix EF Versions
  backend/api/Pims.Api.csproj
  backend/dal.keycloak/Pims.Dal.Keycloak.csproj
  backend/dal/Pims.Dal.csproj
  backend/entities/Pims.Dal.Entities.csproj
  backend/tests/core/Pims.Core.Test.csproj
  backend/tests/unit/api/Pims.Api.Test.csproj
  backend/tests/unit/dal/Pims.Dal.Test.csproj
Labels: bug, tech-debt

#22 update lookup code reducer to slice.
  frontend/src/App.tsx
  frontend/src/actionCreators/lookupCodeActionCreator.spec.ts
  frontend/src/actionCreators/lookupCodeActionCreator.ts
  frontend/src/actions/lookupActions.ts
  frontend/src/components/layout/Header/UserProfile.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/features/admin/access/ManageAccessRequests.test.tsx
  frontend/src/features/admin/access/components/Filter.tsx
  frontend/src/features/admin/agencies/EditAgencyPage.tsx
  frontend/src/features/admin/agencies/ManageAgencies.test.tsx
  frontend/src/features/admin/agencies/ManageAgencies.tsx
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/admin/users/components/UsersFilterBar.tsx
  frontend/src/features/projects/common/forms/GreTransferForm.tsx
  frontend/src/features/projects/erp/forms/AgencyInterest.tsx
  frontend/src/features/properties/components/forms/subforms/AddressForm.tsx
  frontend/src/features/properties/filter/PropertyFilter.tsx
  frontend/src/features/properties/hooks/useParcelLayerData.tsx
  frontend/src/features/properties/list/columns.tsx
  frontend/src/hooks/useLookupCodes.tsx
  frontend/src/mocks/filterDataMock.ts
  frontend/src/reducers/lookupCodeReducer.ts
  frontend/src/reducers/rootReducer.ts
  frontend/src/store/slices/lookupCodes/index.ts
  frontend/src/store/slices/lookupCodes/interfaces/ILookupCode.ts
  frontend/src/store/slices/lookupCodes/interfaces/ILookupCodesState.ts
  frontend/src/store/slices/lookupCodes/interfaces/index.ts
  frontend/src/store/slices/lookupCodes/lookupCodeActionCreator.spec.tsx
  frontend/src/store/slices/lookupCodes/lookupCodesReducer.test.tsx
  frontend/src/store/slices/lookupCodes/lookupCodesSlice.ts
  frontend/src/store/slices/lookupCodes/useLookupCodes.ts
  frontend/src/utils/mapLookupCode.ts
  frontend/src/utils/utils.ts
Labels: tech-debt

#25 Fix Favicon
  frontend/public/favicon-32x32.ico
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/tenants/CITZ/favicon.ico
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/hooks/useFavicon.test.ts
  frontend/src/hooks/useFavicon.ts
  frontend/src/tenants/config/CITZ.ts
Labels: enhancement

#24 PSP-687 Add API version component
  backend/api/Controllers/HealthController.cs
  backend/api/Pims.Api.csproj
  backend/ches/Pims.Ches.csproj
  backend/core/Pims.Core.csproj
  backend/dal.keycloak/Pims.Dal.Keycloak.csproj
  backend/dal/Pims.Dal.csproj
  backend/entities/Pims.Dal.Entities.csproj
  backend/geocoder/Pims.Geocoder.csproj
  backend/keycloak/Pims.Keycloak.csproj
  backend/notifications/Pims.Notifications.csproj
  backend/tests/core/Pims.Core.Test.csproj
  frontend/src/components/common/ApiVersionInfo.test.tsx
  frontend/src/components/common/ApiVersionInfo.tsx
  frontend/src/components/common/__snapshots__/ApiVersionInfo.test.tsx.snap
  frontend/src/components/layout/Footer/Footer.scss
  frontend/src/components/layout/Footer/Footer.tsx
  frontend/src/components/layout/Footer/__snapshots__/Footer.test.tsx.snap
  frontend/src/customAxios.ts
  frontend/src/hooks/pims-api/index.ts
  frontend/src/hooks/pims-api/interfaces/IApiHealth.ts
  frontend/src/hooks/pims-api/interfaces/IApiVersion.ts
  frontend/src/hooks/pims-api/interfaces/IHealthLive.ts
  frontend/src/hooks/pims-api/interfaces/IHealthReady.ts
  frontend/src/hooks/pims-api/interfaces/index.ts
  frontend/src/hooks/pims-api/useApi.test.ts
  frontend/src/hooks/pims-api/useApi.ts
  frontend/src/hooks/pims-api/useApiHealth.test.ts
  frontend/src/hooks/pims-api/useApiHealth.ts
  frontend/src/layouts/EmptyLayout.test.tsx
  frontend/src/layouts/__snapshots__/EmptyLayout.test.tsx.snap
Labels: enhancement

#26 Psp 659 agencies
  frontend/src/actionCreators/agencyActionCreator.test.tsx
  frontend/src/actionCreators/agencyActionCreator.ts
  frontend/src/actions/adminActions.ts
  frontend/src/features/admin/agencies/EditAgencyPage.test.tsx
  frontend/src/features/admin/agencies/EditAgencyPage.tsx
  frontend/src/features/admin/agencies/ManageAgencies.tsx
  frontend/src/reducers/agencyDetailReducer.tsx
  frontend/src/reducers/agencyReducer.tsx
  frontend/src/reducers/rootReducer.ts
  frontend/src/store/slices/agencies/agenciesReducer.test.tsx
  frontend/src/store/slices/agencies/agenciesSlice.ts
  frontend/src/store/slices/agencies/agencyActionCreator.test.tsx
  frontend/src/store/slices/agencies/index.ts
  frontend/src/store/slices/agencies/interfaces/IAgenciesState.ts
  frontend/src/store/slices/agencies/interfaces/index.ts
  frontend/src/store/slices/agencies/useAgencies.ts
Labels: enhancement, tech-debt

#28 replace users reducer with slice. remove unused code.
  frontend/src/App.tsx
  frontend/src/actionCreators/usersActionCreator.spec.ts
  frontend/src/actionCreators/usersActionCreator.ts
  frontend/src/actions/adminActions.ts
  frontend/src/features/account/Login.tsx
  frontend/src/features/admin/edit-user/EditUserPage.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/admin/users/ManageUsers.tsx
  frontend/src/features/admin/users/components/RowActions.tsx
  frontend/src/interfaces/userDetails.ts
  frontend/src/reducers/rootReducer.ts
  frontend/src/reducers/userDetailReducer.ts
  frontend/src/reducers/usersReducer.ts
  frontend/src/store/slices/users/index.ts
  frontend/src/store/slices/users/interfaces/IUsersState.ts
  frontend/src/store/slices/users/interfaces/index.ts
  frontend/src/store/slices/users/useUsers.ts
  frontend/src/store/slices/users/userActionCreator.test.tsx
  frontend/src/store/slices/users/usersReducer.test.tsx
  frontend/src/store/slices/users/usersSlice.ts
Labels: tech-debt

#27 PSP-690 API Response Logging
  backend/api/Helpers/Middleware/LogRequestMiddleware.cs
  backend/api/Helpers/Middleware/LogResponseMiddleware.cs
  backend/api/Pims.Api.csproj
  backend/api/Startup.cs
Labels: enhancement

#30 PSP-684 Add tenant environment colour
  frontend/src/components/common/VerticalBar.tsx
  frontend/src/components/layout/Header/EmptyHeader.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/HeaderStyled.tsx
  frontend/src/components/layout/Header/__snapshots__/EmptyHeader.test.tsx.snap
  frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
  frontend/src/features/account/__snapshots__/IENotSupportedPage.test.tsx.snap
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
  frontend/src/layouts/EmptyLayout.tsx
  frontend/src/layouts/Footer.tsx
  frontend/src/layouts/Header.test.tsx
  frontend/src/layouts/Header.tsx
  frontend/src/layouts/PublicLayout.scss
  frontend/src/layouts/PublicLayout.tsx
  frontend/src/layouts/__snapshots__/EmptyLayout.test.tsx.snap
  frontend/src/layouts/__snapshots__/Header.test.tsx.snap
  frontend/src/tenants/ITenantConfig.ts
  frontend/src/tenants/config/CITZ.ts
  frontend/src/tenants/config/MOTI.ts
  frontend/src/tenants/config/default.ts
  frontend/src/tenants/tenant.tsx
  frontend/src/tenants/useTenant.test.tsx
  openshift/4.0/templates/app/deploy.yaml
  openshift/4.0/templates/app/tenant-configMap.yaml
Labels: enhancement

#33 PSP-675 Add Tenant login background image
  frontend/package-lock.json
  frontend/package.json
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/tenants/CITZ/background-image.png
  frontend/public/tenants/MOTI/background-image.jpg
  frontend/src/_variables.scss
  frontend/src/features/account/Login.test.tsx
  frontend/src/features/account/Login.tsx
  frontend/src/features/account/LoginLoading.test.tsx
  frontend/src/features/account/LoginLoading.tsx
  frontend/src/features/account/LoginStyled.tsx
  frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  frontend/src/index.tsx
  frontend/src/layouts/EmptyLayout.test.tsx
  frontend/src/layouts/Footer.tsx
  frontend/src/layouts/Header.test.tsx
  frontend/src/layouts/Header.tsx
  frontend/src/layouts/__snapshots__/EmptyLayout.test.tsx.snap
  frontend/src/layouts/__snapshots__/Header.test.tsx.snap
  frontend/src/tenants/ITenantConfig.ts
  frontend/src/tenants/config/CITZ.ts
  frontend/src/tenants/config/MOTI.ts
  openshift/4.0/templates/app/deploy.yaml
  openshift/4.0/templates/app/tenant-configMap.yaml
Labels: enhancement

#35 1) Remove label on images causes the agent templates in the configmap…
  openshift/4.0/scripts/oc-sonar-dotnet.sh
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-generic-template.yaml
Labels: devops

#36 PSP-694 Improve code coverage
  .vscode/settings.json
  backend/tests/unit/dal/Libraries/Geocoder/GeocoderServiceTest.cs
  backend/tests/unit/dal/Libraries/Geocoder/ParameterExtensionsTest.cs
  backend/tests/unit/dal/Libraries/Geocoder/ServiceCollectionExtensionsTest.cs
  backend/tests/unit/dal/Libraries/Keycloak/ServiceCollectionExtensionsTest.cs
  backend/tests/unit/dal/Libraries/Notifications/ServiceCollectionExtensionsTest.cs
Labels: unit-tests

#38 PSP-665 Upgrade tool packages
  backend/core/Pims.Core.csproj
  backend/geocoder/Pims.Geocoder.csproj
  tools/converters/excel/Converters/GeoLocationConverter.cs
  tools/converters/excel/Pims.Tools.Converters.ExcelConverter.csproj
  tools/core/Pims.Tools.Core.csproj
  tools/import/Pims.Tools.Import.csproj
  tools/keycloak/sync/Pims.Tools.Keycloak.Sync.csproj
Labels: tech-debt

#41 PSP-675 Update tenant logo and pic
  frontend/public/tenants/MOTI/PIMS-logo-with-text.png
  frontend/public/tenants/MOTI/PIMS-logo.png
  frontend/public/tenants/MOTI/background-image.jpg
Labels: enhancement

#42 PSP-684 Fix footer
  frontend/src/layouts/Footer.tsx
  openshift/4.0/templates/app/deploy.yaml
Labels: bug, devops

#40 PSP-660 update access request action creator, split out api. correspo…
  frontend/package.json
  frontend/src/constants/API.ts
  frontend/src/features/admin/access/components/RowActions.test.tsx
  frontend/src/hooks/pims-api/index.ts
  frontend/src/hooks/pims-api/useApiAccessRequests.test.ts
  frontend/src/hooks/pims-api/useApiAccessRequests.ts
  frontend/src/store/slices/accessRequests/accessRequestsActionCreator.spec.tsx
  frontend/src/store/slices/accessRequests/useAccessRequests.ts
Labels: tech-debt

#46 PSP-723 Disable "Submit Property" feature from the ribbon
  frontend/src/components/layout/AppNavBar/AppNavBar.CITZ.test.tsx
  frontend/src/components/layout/AppNavBar/AppNavBar.MOTI.test.tsx
  frontend/src/components/layout/AppNavBar/AppNavBar.tsx
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.CITZ.test.tsx.snap
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.MOTI.test.tsx.snap
  frontend/src/tenants/FeatureToggle/FeatureToggle.test.tsx
  frontend/src/tenants/FeatureToggle/FeatureToggle.tsx
  frontend/src/tenants/FeatureToggle/index.ts
Labels: alignment

#44 Psp 660 agencies
  frontend/package.json
  frontend/src/customAxios.ts
  frontend/src/features/admin/agencies/EditAgencyPage.tsx
  frontend/src/hooks/pims-api/useApi.ts
  frontend/src/hooks/pims-api/useApiAgencies.test.ts
  frontend/src/hooks/pims-api/useApiAgencies.ts
  frontend/src/interfaces/agency.ts
  frontend/src/mocks/dataMocks.js
  frontend/src/mocks/filterDataMock.ts
  frontend/src/store/slices/agencies/agencyActionCreator.test.tsx
  frontend/src/store/slices/agencies/useAgencies.ts
Labels: tech-debt

#47 include zap html report in sonar.
  openshift/4.0/pipelines/Jenkinsfile.cicd
  openshift/4.0/scripts/oc-sonar-scan.sh
Labels: bug

#48 Psp 660 lookup codes
  frontend/package.json
  frontend/src/hooks/pims-api/useApiLookupCodes.test.ts
  frontend/src/hooks/pims-api/useApiLookupCodes.ts
  frontend/src/store/slices/agencies/useAgencies.ts
  frontend/src/store/slices/lookupCodes/lookupCodeActionCreator.spec.tsx
  frontend/src/store/slices/lookupCodes/useLookupCodes.ts
  frontend/src/store/slices/tenants/useTenants.ts
Labels: enhancement, tech-debt

#45 PSP-694 Add unit tests
  backend/dal/Configuration/Generators/IntIdentityGenerator.cs
  backend/dal/Helpers/Extensions/BuildingExtensions.cs
  backend/dal/Helpers/Extensions/IdentityExtensions.cs
  backend/dal/Helpers/Extensions/RowVersionExtensions.cs
  backend/dal/Migrations/20210517195530_v01.10.03.cs
  backend/dal/Migrations/PimsContextModelSnapshot.cs
  backend/entities/Address.cs
  backend/entities/Helpers/Extensions/ProjectExtensions.cs
  backend/entities/Models/AgencyFilter.cs
  backend/entities/Models/ProjectProperty.cs
  backend/entities/Property.cs
  backend/tests/core/DatabaseHelper.cs
  backend/tests/core/Entities/AgencyHelper.cs
  backend/tests/core/Entities/BuildingHelper.cs
  backend/tests/core/Extensions/IEnumerableExtensions.cs
  backend/tests/unit/dal/Entities/AccessRequestAgencyTest.cs
  backend/tests/unit/dal/Entities/AccessRequestRoleTest.cs
  backend/tests/unit/dal/Entities/AccessRequestTest.cs
  backend/tests/unit/dal/Entities/AddressTest.cs
  backend/tests/unit/dal/Entities/AdministrativeAreaTest.cs
  backend/tests/unit/dal/Entities/AgencyFilterTest.cs
  backend/tests/unit/dal/Entities/AllPropertyFilterTest.cs
  backend/tests/unit/dal/Entities/BuildingFilterTest.cs
  backend/tests/unit/dal/Entities/ClaimTest.cs
  backend/tests/unit/dal/Entities/CodeEntityTest`.cs
  backend/tests/unit/dal/Entities/Comparers/AccessRequestAgencyAgencyIdComparerTest.cs
  backend/tests/unit/dal/Entities/Comparers/AccessRequestRoleRoleIdComparerTest.cs
  backend/tests/unit/dal/Entities/Comparers/AgencyIdComparerTest.cs
  backend/tests/unit/dal/Entities/Comparers/RoleIdComparerTests.cs
  backend/tests/unit/dal/Entities/Extensions/BuildingExtensionsTest.cs
  backend/tests/unit/dal/Entities/Extensions/ParcelExtensionsTest.cs
  backend/tests/unit/dal/Entities/Extensions/ProjectExtensionsTest.cs
  backend/tests/unit/dal/Entities/LookupEntityTest`.cs
  backend/tests/unit/dal/Entities/NotificationQueueTest.cs
  backend/tests/unit/dal/Entities/NotificationTemplateTest.cs
  backend/tests/unit/dal/Entities/PageFilterTest.cs
  backend/tests/unit/dal/Entities/PagedTest`.cs
  backend/tests/unit/dal/Entities/ParcelParcelTest.cs
  backend/tests/unit/dal/Entities/ProjectNotificationFilterTest.cs
  backend/tests/unit/dal/Entities/ProjectNumberTest.cs
  backend/tests/unit/dal/Entities/PropertyTypeTest.cs
  backend/tests/unit/dal/Entities/RoleClaimTest.cs
  backend/tests/unit/dal/Exceptions/ConfigurationExceptionTest.cs
  backend/tests/unit/dal/Exceptions/NotAuthorizedExceptionTest.cs
  backend/tests/unit/dal/Exceptions/RowVersionMissingExceptionTest.cs
  backend/tests/unit/dal/Helpers/Extensions/AddressExtensionsTest.cs
  backend/tests/unit/dal/Helpers/Extensions/BuildingExtensionsTest.cs
  backend/tests/unit/dal/Helpers/Extensions/EntityExtensionsTest.cs
  backend/tests/unit/dal/Helpers/Extensions/PropertyExtensionsTest.cs
Labels: bug, unit-tests

#49 Psp 660 users
  frontend/src/constants/API.ts
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/admin/users/components/RowActions.test.tsx
  frontend/src/features/admin/users/components/RowActions.tsx
  frontend/src/hooks/pims-api/useApiUsers.test.ts
  frontend/src/hooks/pims-api/useApiUsers.ts
  frontend/src/mocks/filterDataMock.ts
  frontend/src/store/slices/lookupCodes/lookupCodeActionCreator.spec.tsx
  frontend/src/store/slices/properties/parcelsActionCreator.spec.tsx
  frontend/src/store/slices/properties/useProperties.test.tsx
  frontend/src/store/slices/tenants/useTenants.test.tsx
  frontend/src/store/slices/users/useUsers.ts
  frontend/src/store/slices/users/userActionCreator.test.tsx
  frontend/src/tenants/useTenant.test.tsx
Labels: tech-debt

#50 Psp 660 properties
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/hooks/useSideBarBuildingLoader.tsx
  frontend/src/features/mapSideBar/hooks/useSideBarParcelLoader.tsx
  frontend/src/hooks/pims-api/__snapshots__/useApiProperties.test.tsx.snap
  frontend/src/hooks/pims-api/useApiProperties.test.tsx
  frontend/src/hooks/pims-api/useApiProperties.ts
  frontend/src/store/slices/accessRequests/useAccessRequests.ts
  frontend/src/store/slices/agencies/agencyActionCreator.test.tsx
  frontend/src/store/slices/properties/parcelsActionCreator.spec.tsx
  frontend/src/store/slices/properties/useProperties.test.tsx
  frontend/src/store/slices/properties/useProperties.ts
Labels: tech-debt

#51 only prompt for version if the flag is enabled.
  openshift/4.0/pipelines/Jenkinsfile.cicd
Labels: devops

#52 Alignment stories
  Makefile
  frontend/src/components/layout/AppNavBar/AppNavBar.CITZ.test.tsx
  frontend/src/components/layout/AppNavBar/AppNavBar.MOTI.test.tsx
  frontend/src/components/layout/AppNavBar/AppNavBar.tsx
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.CITZ.test.tsx.snap
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.MOTI.test.tsx.snap
  frontend/src/components/maps/leaflet/MapProperties.test.tsx
  frontend/src/features/properties/filter/PropertyFilter.CITZ.test.tsx
  frontend/src/features/properties/filter/PropertyFilter.MOTI.test.tsx
  frontend/src/features/properties/filter/PropertyFilter.tsx
  frontend/src/features/properties/filter/__snapshots__/PropertyFilter.CITZ.test.tsx.snap
  frontend/src/features/properties/filter/__snapshots__/PropertyFilter.MOTI.test.tsx.snap
  frontend/src/features/properties/list/PropertyListView.test.tsx
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/mocks/filterDataMock.ts
Labels: alignment

#54 PSP-997 Remove Home Button from Access Request Page
  frontend/src/components/layout/AppNavBar/AppNavBar.CITZ.test.tsx
  frontend/src/components/layout/AppNavBar/AppNavBar.MOTI.test.tsx
  frontend/src/components/layout/AppNavBar/AppNavBar.tsx
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.CITZ.test.tsx.snap
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.MOTI.test.tsx.snap
Labels: enhancement

#53 Merging bug fixes made to CITZ PIMS
  backend/api/Startup.cs
  backend/ches/ChesService.cs
  backend/core/Http/HttpRequestClient.cs
  backend/dal/Helpers/Extensions/ProjectExtensions.cs
  backend/dal/Migrations/20210422222731_v01.10.01.Designer.cs
  backend/dal/Migrations/20210422222731_v01.10.01.cs
  backend/dal/Migrations/20210505204819_v01.10.02.Designer.cs
  backend/dal/Migrations/20210505204819_v01.10.02.cs
  backend/dal/Migrations/Initial/Up/PostUp/01-NotificationTemplates.sql
  backend/dal/Migrations/v01.09.02/Up/PostUp/01-NotificationTemplates.sql
  backend/dal/Migrations/v01.10.01/Up/PostUp/01-NotificationTemplates.sql
  backend/dal/Migrations/v01.10.02/Up/PostUp/01-ProjectStatusNotifications.sql
  backend/dal/Services/Concrete/NotificationQueueService.cs
  backend/dal/Services/Concrete/ProjectService.cs
  backend/entities/Models/ProjectFilter.cs
  backend/entities/NotificationResponses.cs
  backend/notifications/Configuration/NotificationOptions.cs
  backend/notifications/NotificationService.cs
  backend/tests/core/ProjectAgencyResponseHelper.cs
  backend/tests/unit/api/Controllers/Reports/ProjectControllerTest.cs
  backend/tests/unit/api/Controllers/Tools/ImportControllerTest.cs
  backend/tests/unit/dal/Libraries/Ches/ChesServiceCollectionTest.cs
  backend/tests/unit/dal/Libraries/Ches/ChesServiceTest.cs
  backend/tests/unit/dal/Libraries/Notifications/NotificationServiceTest.cs
  backend/tests/unit/dal/Services/ProjectServiceTest.cs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/form/ParentSelect.tsx
  frontend/src/features/projects/common/components/columns.tsx
  frontend/src/features/projects/common/interfaces.ts
  frontend/src/features/projects/common/projectConverter.ts
  frontend/src/features/projects/dispose/testUtils.ts
  frontend/src/features/projects/erp/steps/ErpStep.test.tsx
  frontend/src/features/projects/list/ProjectApprovalRequestListView.test.tsx
  frontend/src/features/projects/list/ProjectApprovalRequestListView.tsx
  frontend/src/features/projects/list/ProjectListView.tsx
  frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequestListView.test.tsx.snap
  frontend/src/features/projects/list/index.ts
  frontend/src/features/projects/spl/steps/SplStep.test.tsx
  frontend/src/router.tsx
  openshift/4.0/templates/jenkins/config.yaml
Labels: bug, db-migration
