Repository bcgov/PSP, pull requests merged in 2021-11, with the labels that each got.

#432 PSP-2204: Access request auto populate fields
  frontend/src/features/admin/access-request/AccessRequestPage.tsx
  frontend/src/interfaces/IAccessRequestUserInfo.ts
  frontend/src/interfaces/index.ts
  testing/Profiles/default.glbl
Labels: bug

#455 Lease Surplus Declaration view - Psp 1949
  backend/api/Areas/Leases/Mapping/Lease/PropertyMap.cs
  backend/api/Areas/Leases/Mapping/Lease/PropertySurplusMap.cs
  backend/api/Areas/Leases/Models/Lease/PropertyModel.cs
  backend/api/Areas/Leases/Models/Lease/SurplusDeclarationModel.cs
  frontend/package-lock.json
  frontend/public/manifest.json
  frontend/src/features/leases/detail/LeaseContainer.test.tsx
  frontend/src/features/leases/detail/LeaseContainer.tsx
  frontend/src/features/leases/detail/LeasePages/LeasePageForm.tsx
  frontend/src/features/leases/detail/LeasePages/details/Details.tsx
  frontend/src/features/leases/detail/LeasePages/surplus/Surplus.test.tsx
  frontend/src/features/leases/detail/LeasePages/surplus/Surplus.tsx
  frontend/src/features/leases/detail/LeasePages/surplus/__snapshots__/Surplus.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/interfaces/IProperty.ts
  frontend/src/interfaces/IPropertySurplus.ts
Labels: enhancement

#463 PSP-2221: Property Filter - Reset button not clearing properties on map view
  frontend/src/components/maps/leaflet/Map.tsx
Labels: bug

#468 PSP-2261 Correct NPE on L&L list view
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Migrations/20211108185659_v0.2.13.3.Designer.cs
  backend/dal/Migrations/20211108185659_v0.2.13.3.cs
  backend/dal/Migrations/v0.2.13.3/Up/PostUp/01-History.sql
Labels: bug

#465 Lease Insurance view - Psp 1696
  backend/api/Areas/Leases/Mapping/Lease/InsuranceMap.cs
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Mapping/Lease/TypeMap.cs
  backend/api/Areas/Leases/Models/Lease/AddressModel.cs
  backend/api/Areas/Leases/Models/Lease/InsuranceModel.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  backend/api/Areas/Leases/Models/Lease/OrganizationModel.cs
  backend/api/Areas/Leases/Models/Lease/PersonModel.cs
  backend/api/Areas/Leases/Models/Lease/TypeModel.cs
  backend/api/Pims.Api.csproj
  frontend/src/features/leases/detail/LeaseContainer.tsx
  frontend/src/features/leases/detail/LeasePages/LeasePageForm.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/Insurance.test.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/Insurance.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/Insurer.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/MinistryContacts.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/Policy.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/__snapshots__/Insurance.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/insurance/styles.ts
  frontend/src/features/leases/detail/LeasePages/surplus/Surplus.tsx
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/interfaces/IInsurance.ts
  frontend/src/interfaces/ILease.ts
  frontend/src/interfaces/IOrganization.ts
  frontend/src/interfaces/IPerson.ts
  frontend/src/interfaces/ITypeCode.ts
  frontend/src/interfaces/index.ts
Labels: enhancement

#471 backmerge test to dev
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Migrations/20211108185659_v0.2.13.3.Designer.cs
  backend/dal/Migrations/20211108185659_v0.2.13.3.cs
  backend/dal/Migrations/v0.2.13.3/Up/PostUp/01-History.sql
Labels: bug

#475 PSP-2250 Lease Improvements
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Mapping/Lease/PropertyImprovementMap.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  backend/api/Areas/Leases/Models/Lease/PropertyImprovementModel.cs
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Services/LeaseService.cs
  frontend/src/components/common/Scrollable/Scrollable.tsx
  frontend/src/components/common/form/TextArea.tsx
  frontend/src/constants/propertyImprovementTypes.ts
  frontend/src/features/leases/detail/LeaseBreadCrumb.tsx
  frontend/src/features/leases/detail/LeaseContainer.tsx
  frontend/src/features/leases/detail/LeasePages/LeasePageForm.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/Improvements.tsx
  frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
  frontend/src/features/leases/detail/LeasePages/improvements/components/Summary/Summary.tsx
  frontend/src/features/leases/detail/LeasePages/improvements/styles.ts
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseBreadCrumb.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/styles.ts
  frontend/src/interfaces/ILease.ts
  frontend/src/interfaces/ILeaseImprovement.ts
Labels: enhancement, frontend

#480 psp-2167 prevent leading zeros from being stripped from pid search.
  backend/dal/Migrations/20211110022507_v1.0.14.2.Designer.cs
  backend/dal/Migrations/20211110022507_v1.0.14.2.cs
  backend/dal/Migrations/v1.0.14.2/Down/PostDown/02_PIMS_PROPERTY_BOUNDARY_VW.sql
  backend/dal/Migrations/v1.0.14.2/Down/PostDown/02_PIMS_PROPERTY_LOCATION_VW.sql
  backend/dal/Migrations/v1.0.14.2/Up/PostUp/01-GEOSPATIAL_VW.sql
  frontend/src/components/maps/leaflet/Map.test.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/constants/API.ts
  frontend/src/hooks/useApi.ts
Labels: bug

#481 psp-2309
  backend/dal/Services/LeaseService.cs
Labels: bug

#484 force refresh local geoserver layer.
  geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_VW/featuretype.xml
  geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_VW/layer.xml
Labels: bug

#487 More FT scripts
  testing/Object Repository/AccessRequest/Email.rs
  testing/Object Repository/AccessRequest/FirstName.rs
  testing/Object Repository/AccessRequest/Idir.rs
  testing/Object Repository/AccessRequest/LastName.rs
  testing/Object Repository/Navigation/ListViewButton.rs
  testing/Profiles/default.glbl
  testing/Scripts/AccessRequest/accessRequest/Script1636525625011.groovy
  testing/Scripts/AccessRequest/autoPopulateFields/Script1636525625020.groovy
  testing/Scripts/Administartive/manageUser/Script1635187115583.groovy
  testing/Scripts/General/signIn/signIn.groovy
  testing/Scripts/LeaseLicense/leaseAndLicensesNavigation/Script1635188616410.groovy
  testing/Scripts/LeaseLicense/persistantLeaseHeader/Script1636504973681.groovy
  testing/Scripts/MapView/filterByPid/Script1634156014300.groovy
  testing/Scripts/MapView/filterByPid/propertyData.txt
  testing/Scripts/PropertyListView/propertiesDisplayed/Script1636525802581.groovy
  testing/Test Cases/AccessRequest/.meta
  testing/Test Cases/AccessRequest/accessRequest.tc
  testing/Test Cases/AccessRequest/autoPopulateFields.tc
  testing/Test Cases/Administartive/manageUser.tc
  testing/Test Cases/General/signIn.tc
  testing/Test Cases/LeaseLicense/leaseAndLicensesNavigation.tc
  testing/Test Cases/LeaseLicense/persistantLeaseHeader.tc
  testing/Test Cases/MapView/filterByPid.tc
  testing/Test Cases/PropertyListView/.meta
  testing/Test Cases/PropertyListView/propertiesDisplayed.tc
  testing/settings/internal/com.kms.katalon.composer.testcase.properties
Labels: test-scripts

#493 reverse merge test -> dev
  backend/dal/Services/LeaseService.cs
Labels: release-management

#501 Increment DEV version to IS15
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#509 Added complete includes from DB mapping for contacts
  backend/dal/Services/LeaseService.cs
Labels: bug

#510 Backmerge test changes
  backend/dal/Services/LeaseService.cs
Labels: bug

#511 PSP-2306 Lease Deposits
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Mapping/Lease/SecurityDepositMap.cs
  backend/api/Areas/Leases/Mapping/Lease/SecurityDepositReturnMap.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  backend/api/Areas/Leases/Models/Lease/SecurityDepositModel.cs
  backend/api/Areas/Leases/Models/Lease/SecurityDepositReturnModel.cs
  backend/dal/Services/LeaseService.cs
  backend/entities/SecurityDeposit.cs
  frontend/src/components/Table/helpers.ts
  frontend/src/components/Table/index.ts
  frontend/src/features/leases/detail/LeaseContainer.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/Deposits.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/Deposits.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/Deposits.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/__snapshots__/DepositNotes.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/DepositsReceivedTable.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/DepositsReceivedTable.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/__snapshots__/DepositsReceivedTable.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/columns.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedTable/DepositsReturnedTable.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedTable/DepositsReturnedTable.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedTable/__snapshots__/DepositsReturnedTable.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedTable/columns.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/styles.ts
  frontend/src/features/leases/detail/LeasePages/improvements/Improvements.tsx
  frontend/src/features/leases/detail/styles.ts
  frontend/src/interfaces/ILease.ts
  frontend/src/interfaces/ILeaseImprovement.ts
  frontend/src/interfaces/ILeaseSecurityDeposit.ts
  frontend/src/interfaces/ILeaseSecurityDepositReturn.ts
  frontend/src/interfaces/index.ts
  frontend/src/utils/numberFormatUtils.ts
Labels: enhancement

#516 Fixed insurance in place date calculation
  backend/api/Areas/Leases/Mapping/Lease/InsuranceMap.cs
Labels: bug

#518 Lease search and list updates psp-2224
  backend/.editorconfig
  backend/api/Areas/Leases/Controllers/SearchController.cs
  backend/api/Areas/Leases/Mapping/Search/LeaseMap.cs
  backend/api/Areas/Leases/Mapping/Search/PropertyMap.cs
  backend/api/Areas/Leases/Models/Lease/PropertyImprovementModel.cs
  backend/api/Areas/Leases/Models/Search/LeaseFilterModel.cs
  backend/api/Areas/Leases/Models/Search/LeaseModel.cs
  backend/api/Areas/Leases/Models/Search/PropertyModel.cs
  backend/api/Controllers/LookupController.cs
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Services/Interfaces/ILookupService.cs
  backend/dal/Services/LeaseService.cs
  backend/dal/Services/LookupService.cs
  backend/entities/Models/LeaseFilter.cs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Table/Table.tsx
  frontend/src/constants/API.ts
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
  frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
  frontend/src/features/contact/list/ContactSearchResults/__snapshots__/ContactSearchResults.test.tsx.snap
  frontend/src/features/contact/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/Deposits.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/__snapshots__/DepositsReceivedTable.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedTable/__snapshots__/DepositsReturnedTable.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/surplus/__snapshots__/Surplus.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/interfaces.ts
  frontend/src/features/leases/list/LeaseFilter/LeaseFilter.test.tsx
  frontend/src/features/leases/list/LeaseFilter/LeaseFilter.tsx
  frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  frontend/src/features/leases/list/LeaseListView.test.tsx
  frontend/src/features/leases/list/LeaseListView.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseProperties.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.test.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseTenants.tsx
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  frontend/src/features/leases/list/LeaseSearchResults/columns.tsx
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/leases/list/styles.ts
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/interfaces/ILeaseSearchResult.ts
Labels: enhancement

#524 Correction to PSP-2361
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/styles.ts
Labels: bug

#528 correct missing css on react multiselect dropdown.
  frontend/package.json
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: bug

#531 Improvement description text fix
  frontend/src/components/common/form/TextArea.tsx
  frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
Labels: bug

#523 PSP-2308: Align tenant notes with rest of page
  frontend/src/features/leases/detail/LeasePages/tenant/TenantNotes.tsx
  frontend/src/features/leases/detail/styles.ts
Labels: bug

#527 add convenience script for deployment.
  Makefile
  database/mssql/scripts/clear-objects.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S15_01/Alter Up/02_PSP_PIMS_S15_00_Alter.sql
  database/mssql/scripts/dbscripts/deploy.sh
Labels: enhancement, db-migration

#538 fix date display on details page.
  frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
Labels: bug

#541 allow user to control target folder of database deployment scripts.
  Makefile
Labels: enhancement, devops

#533 PSP-1825 release automation
  .github/release.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  Makefile
  build/bump-version.js
  build/bump.sh
  build/version-next.sh
  build/version.sh
Labels: enhancement, devops

#546 Backmerge Test -> Dev
  backend/api/Areas/Leases/Mapping/Lease/InsuranceMap.cs
  frontend/src/components/common/form/TextArea.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/styles.ts
Labels: devops

#550 Fix auto-versioning action
  .github/workflows/version.yml
Labels: bug

#555 Increment DEV version to IS16
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#560 Psp 2371
  backend/api/Areas/Contacts/Mapping/Search/ContactMap.cs
  frontend/src/AppRouter.tsx
  frontend/src/_variables.module.scss
  frontend/src/components/common/styles.ts
  frontend/src/constants/claims.ts
  frontend/src/features/contact/index.ts
  frontend/src/features/contacts/contact/ContactBreadcrumb/ContactBreadcrumb.test.tsx
  frontend/src/features/contacts/contact/ContactBreadcrumb/ContactBreadcrumb.tsx
  frontend/src/features/contacts/contact/ContactBreadcrumb/__snapshots__/ContactBreadcrumb.test.tsx.snap
  frontend/src/features/contacts/contact/ContactContainer/ContactContainer.test.tsx
  frontend/src/features/contacts/contact/ContactContainer/ContactContainer.tsx
  frontend/src/features/contacts/contact/ContactContainer/__snapshots__/ContactContainer.test.tsx.snap
  frontend/src/features/contacts/contact/ContactTypeSelector/ContactTypeSelector.test.tsx
  frontend/src/features/contacts/contact/ContactTypeSelector/ContactTypeSelector.tsx
  frontend/src/features/contacts/contact/ContactTypeSelector/__snapshots__/ContactTypeSelector.test.tsx.snap
  frontend/src/features/contacts/index.ts
  frontend/src/features/contacts/interfaces.ts
  frontend/src/features/contacts/list/ContactListView.test.tsx
  frontend/src/features/contacts/list/ContactListView.tsx
  frontend/src/features/contacts/list/ContactSearchResults/ContactSearchResults.test.tsx
  frontend/src/features/contacts/list/ContactSearchResults/ContactSearchResults.tsx
  frontend/src/features/contacts/list/ContactSearchResults/__snapshots__/ContactSearchResults.test.tsx.snap
  frontend/src/features/contacts/list/ContactSearchResults/columns.tsx
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/contacts/list/filter/ActiveFilterCheck.tsx
  frontend/src/features/contacts/list/filter/ContactFilter.test.tsx
  frontend/src/features/contacts/list/filter/ContactFilter.tsx
  frontend/src/features/contacts/list/filter/__snapshots__/ContactFilter.test.tsx.snap
  frontend/src/features/contacts/list/styles.ts
  frontend/src/features/contacts/styles.ts
  frontend/src/features/leases/detail/LeaseBreadCrumb.tsx
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/styles.ts
  frontend/src/hooks/pims-api/useApiContacts.ts
Labels: enhancement

#564 [PSP-2423] Makefile enhancements
  .github/notifications/release_template.json
  .github/workflows/release.yml
  .github/workflows/tag.yml
  Makefile
Labels: enhancement
