Repository bcgov/PSP, pull requests merged in 2021-12, with the labels that each got.

#573 Re-applied filter and cleaned up legacy filter options for property.
  backend/api/Areas/Leases/Models/Search/LeaseFilterModel.cs
  backend/api/Areas/Property/Models/Search/PropertyFilterModel.cs
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Helpers/Extensions/PropertyExtensions.cs
  backend/dal/Services/LeaseService.cs
  backend/entities/Models/LeaseFilter.cs
  backend/entities/Models/PropertyFilter.cs
  backend/tests/core/Entities/LeaseHelper.cs
  backend/tests/unit/api/Controllers/Leases/SearchControllerTest.cs
  backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
  backend/tests/unit/api/Controllers/Reports/PropertyControllerTest.cs
  backend/tests/unit/dal/Entities/PropertyFilterTest.cs
  backend/tests/unit/dal/Services/LeaseServiceTest.cs
  backend/tests/unit/dal/Services/PropertyServiceTest.cs
  frontend/src/components/maps/leaflet/Map.test.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/Deposits.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/__snapshots__/DepositsReceivedTable.test.tsx.snap
  frontend/src/features/leases/interfaces.ts
  frontend/src/features/leases/list/LeaseFilter/LeaseFilter.test.tsx
  frontend/src/features/leases/list/LeaseFilter/LeaseFilter.tsx
  frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  frontend/src/features/leases/list/LeaseListView.test.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/properties/filter/IPropertyFilter.ts
  frontend/src/features/properties/filter/PropertyFilter.test.tsx
  frontend/src/features/properties/filter/PropertyFilterOptions.tsx
  frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  frontend/src/features/properties/filter/__snapshots__/PropertyFilterOptions.test.tsx.snap
  frontend/src/features/properties/list/PropertyListView.tsx
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: bug

#574 Test backmerge
  backend/api/Areas/Leases/Models/Search/LeaseFilterModel.cs
  backend/api/Areas/Property/Models/Search/PropertyFilterModel.cs
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Helpers/Extensions/PropertyExtensions.cs
  backend/dal/Services/LeaseService.cs
  backend/entities/Models/LeaseFilter.cs
  backend/entities/Models/PropertyFilter.cs
  backend/tests/core/Entities/LeaseHelper.cs
  backend/tests/unit/api/Controllers/Leases/SearchControllerTest.cs
  backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
  backend/tests/unit/api/Controllers/Reports/PropertyControllerTest.cs
  backend/tests/unit/dal/Entities/PropertyFilterTest.cs
  backend/tests/unit/dal/Services/LeaseServiceTest.cs
  backend/tests/unit/dal/Services/PropertyServiceTest.cs
  frontend/src/components/maps/leaflet/Map.test.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/Deposits.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/__snapshots__/DepositsReceivedTable.test.tsx.snap
  frontend/src/features/leases/interfaces.ts
  frontend/src/features/leases/list/LeaseFilter/LeaseFilter.test.tsx
  frontend/src/features/leases/list/LeaseFilter/LeaseFilter.tsx
  frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  frontend/src/features/leases/list/LeaseListView.test.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/properties/filter/IPropertyFilter.ts
  frontend/src/features/properties/filter/PropertyFilter.test.tsx
  frontend/src/features/properties/filter/PropertyFilterOptions.tsx
  frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  frontend/src/features/properties/filter/__snapshots__/PropertyFilterOptions.test.tsx.snap
  frontend/src/features/properties/list/PropertyListView.tsx
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: alignment

#565 psp-1760 fix issue with lease amounts.
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_Load.dtsx
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_PIMS.dtproj
Labels: etl

#572 Psp 2331
  Makefile
  backend/api/Areas/Leases/Controllers/LeaseController.cs
  backend/api/Areas/Leases/Controllers/SearchController.cs
  backend/dal/Security/Permissions.cs
  backend/dal/Services/LeaseService.cs
  backend/tests/unit/dal/Services/LeaseServiceTest.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_S16_00/Alter Up/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S16_00/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S16_00/Build/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S16_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
  frontend/src/AppRouter.tsx
  frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  frontend/src/constants/claims.ts
  frontend/src/features/leases/add/AddLeaseLayout.tsx
  frontend/src/features/leases/add/DetailContainer.tsx
  frontend/src/features/leases/detail/LeaseBreadCrumb.test.tsx
  frontend/src/features/leases/detail/LeaseBreadCrumb.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/Deposits.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/Deposits.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/DepositsReceivedTable.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/__snapshots__/DepositsReceivedTable.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedTable/DepositsReturnedTable.test.tsx
  frontend/src/features/leases/detail/__snapshots__/LeaseBreadCrumb.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/index.ts
  frontend/src/features/leases/list/LeaseListView.test.tsx
  frontend/src/features/leases/list/LeaseListView.tsx
Labels: enhancement

#577 Psp 2114
  database/mssql/scripts/dbscripts/PSP_PIMS_S15_01/Alter Up/02_PSP_PIMS_S15_00_Alter.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S15_01/Alter Up/49_DML_PIMS_PROPERTY_DATA_SOURCE_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S16_00/Alter Up/01_PSP_PIMS_S15_01_Alter_Up.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S16_00/Alter Up/73_DML_PIMS_LEASE_STATUS_TYPE.sql
Labels: db-migration

#585 Contact view of individual - Psp-2278
  backend/api/Areas/Contacts/Controllers/ContactController.cs
  backend/api/Areas/Contacts/Controllers/SearchController.cs
  backend/api/Areas/Contacts/Mapping/Contact/AddressMap.cs
  backend/api/Areas/Contacts/Mapping/Contact/ContactMap.cs
  backend/api/Areas/Contacts/Mapping/Contact/ContactMethod.Map.cs
  backend/api/Areas/Contacts/Mapping/Contact/OrganizationMap.cs
  backend/api/Areas/Contacts/Mapping/Contact/PersonMap.cs
  backend/api/Areas/Contacts/Mapping/Search/ContactSummaryMap.cs
  backend/api/Areas/Contacts/Models/Contact/AddressModel.cs
  backend/api/Areas/Contacts/Models/Contact/ContactMethodModel.cs
  backend/api/Areas/Contacts/Models/Contact/ContactModel.cs
  backend/api/Areas/Contacts/Models/Contact/OrganizationModel.cs
  backend/api/Areas/Contacts/Models/Contact/PersonModel.cs
  backend/api/Areas/Contacts/Models/Search/ContactSummaryModel.cs
  backend/api/Areas/Leases/Models/Lease/InsuranceModel.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  backend/api/Areas/Leases/Models/Lease/SurplusDeclarationModel.cs
  backend/api/Areas/Leases/Models/Lease/Term.cs
  backend/api/Mapping/TypeMap.cs
  backend/api/Models/TypeModel.cs
  backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  backend/dal/IPimsService.cs
  backend/dal/PIMSContext.cs
  backend/dal/PimsService.cs
  backend/dal/Services/ContactService.cs
  backend/dal/Services/Interfaces/IContactService.cs
  backend/dal/Services/Interfaces/IPersonService.cs
  backend/dal/Services/PersonService.cs
  backend/dal/Services/UserService.cs
  backend/entities/IDisableBaseAppEntity.cs
  backend/entities/Person.cs
  backend/tests/unit/api/Controllers/Contacts/SearchControllerTest.cs
  backend/tests/unit/dal/Services/ContactServiceTest.cs
  frontend/package-lock.json
  frontend/src/AppRouter.tsx
  frontend/src/constants/contactMethodType.ts
  frontend/src/features/contacts/contact/breadcrumb/ContactBreadcrumb.test.tsx
  frontend/src/features/contacts/contact/breadcrumb/ContactBreadcrumb.tsx
  frontend/src/features/contacts/contact/breadcrumb/__snapshots__/ContactBreadcrumb.test.tsx.snap
  frontend/src/features/contacts/contact/create/Container.test.tsx
  frontend/src/features/contacts/contact/create/Container.tsx
  frontend/src/features/contacts/contact/create/__snapshots__/Container.test.tsx.snap
  frontend/src/features/contacts/contact/detail/Container.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
  frontend/src/features/contacts/contact/edit/Container.tsx
  frontend/src/features/contacts/contact/typeSelector/ContactTypeSelector.test.tsx
  frontend/src/features/contacts/contact/typeSelector/ContactTypeSelector.tsx
  frontend/src/features/contacts/contact/typeSelector/__snapshots__/ContactTypeSelector.test.tsx.snap
  frontend/src/features/contacts/hooks/useContactDetail.ts
  frontend/src/features/contacts/index.ts
  frontend/src/features/contacts/interfaces.ts
  frontend/src/features/contacts/styles.ts
  frontend/src/features/leases/add/DetailContainer.tsx
  frontend/src/hooks/pims-api/useApiContacts.ts
  frontend/src/interfaces/Dictionary.ts
  frontend/src/interfaces/IContact.ts
Labels: enhancement

#591 PSP_PIMS_S16_02 updates. Support address usage type changes.
  backend/entities/AddressType.cs
  backend/entities/Helpers/OrganizationExtensions.cs
  backend/entities/Helpers/PersonExtensions.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_S16_01/Alter Up/01_PSP_PIMS_S16_00_Alter_Up.sql
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
  frontend/src/components/maps/leaflet/PointClusterer.tsx
  frontend/src/components/maps/leaflet/mapUtils.test.tsx
  frontend/src/constants/addressTypes.ts
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/mocks/filterDataMock.ts
Labels: db-migration

#584 psp-2315 export leases.
  backend/api/Areas/Reports/Controllers/LeaseController.cs
  backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Reports/Models/Lease/LeaseModel.cs
  backend/api/Helpers/Reporting/ReportHelper.cs
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/PIMSContext.cs
  backend/dal/Services/PersonService.cs
  backend/dal/Services/UserService.cs
  backend/entities/Helpers/PersonExtensions.cs
  backend/entities/LeaseStatusType.cs
  backend/tests/core/Entities/LeaseHelper.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_S16_02/Alter Up/77_DML_PIMS_TENANT.sql
  frontend/src/customAxios.ts
  frontend/src/features/leases/hooks/useLeaseExport.ts
  frontend/src/features/leases/list/LeaseListView.tsx
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/hooks/pims-api/useApiLeases.ts
  frontend/src/store/slices/properties/useProperties.ts
Labels: enhancement

#600 Fixed searches to work with leading zero
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Helpers/Extensions/PropertyExtensions.cs
Labels: bug

#596 PSP-2308: Adjust for scaling
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/TenantNotes.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/styles.ts
Labels: bug

#605 Fixed link between Orgs and Persons
  frontend/src/features/contacts/contact/detail/Organization.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
Labels: enhancement

#603 Test back merge
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Helpers/Extensions/PropertyExtensions.cs
Labels: alignment

#612 Correct issue with IS16 Alter up.
  database/mssql/scripts/dbscripts/PSP_PIMS_S16_00/Alter Up/74_DML_PIMS_CLAIM.sql
Labels: bug, db-migration

#625 Lease & License Deposits not appearing | psp-2473
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
Labels: bug

#627 Increment DEV version to IS17
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#626 Align - test backmerge
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
Labels: alignment

#632 Added missing field from the returned lease model | PSP-2540
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
Labels: bug

#380 Add the ability to manually specify release versions.
  openshift/4.0/pipelines/Jenkinsfile.cicd.prod
Labels: devops

#637 Updated entitites and insurance view - PSP-2545
  backend/api/Areas/Leases/Mapping/Lease/InsuranceMap.cs
  backend/api/Areas/Leases/Mapping/Lease/PropertyImprovementMap.cs
  backend/api/Areas/Leases/Models/Lease/InsuranceModel.cs
  backend/dal/PIMSContext.cs
  backend/dal/Services/LeaseService.cs
  backend/entities/InsurancePayeeType.cs
  backend/entities/ef/PimsInsurance.cs
  backend/entities/ef/PimsInsuranceHist.cs
  backend/entities/ef/PimsInsurancePayeeType.cs
  backend/entities/ef/PimsLease.cs
  backend/entities/ef/PimsLeaseHist.cs
  backend/entities/ef/PimsLeasePayment.cs
  backend/entities/ef/PimsLeasePaymentForecast.cs
  backend/entities/ef/PimsLeasePaymentForecastHist.cs
  backend/entities/ef/PimsLeasePaymentHist.cs
  backend/entities/ef/PimsOrganization.cs
  backend/entities/ef/PimsPerson.cs
  backend/entities/ef/PimsPersonHist.cs
  backend/entities/ef/PimsProperty.cs
  backend/entities/ef/PimsPropertyBoundaryVw.cs
  backend/entities/ef/PimsPropertyHist.cs
  backend/entities/ef/PimsPropertyImprovement.cs
  backend/entities/ef/PimsPropertyImprovementHist.cs
  backend/entities/ef/PimsPropertyLocationVw.cs
  database/mssql/scripts/dbscripts/setup.sh
  frontend/src/features/leases/detail/LeasePages/insurance/Insurance.test.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/Insurance.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/Insurer.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/MinistryContacts.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/Policy.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/__snapshots__/Insurance.test.tsx.snap
  frontend/src/interfaces/IInsurance.ts
Labels: alignment

#640 psp-2564 psp-2557
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  backend/dal/PIMSContext.cs
  backend/entities/ef/PimsLease.cs
  backend/entities/ef/PimsLeaseHist.cs
Labels: bug

#648 PSP-2582: Contact names on new line
  frontend/src/features/contacts/contact/detail/Organization.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
Labels: bug

#647 PSP-2543: Excel button downloading CSV
  frontend/src/features/leases/list/LeaseListView.tsx
Labels: bug

#646 PSP-2497: Fix IDIR not displaying
  frontend/src/features/admin/edit-user/EditUserPage.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/admin/users/ManageUsers.test.tsx
  frontend/src/features/admin/users/ManageUsers.tsx
  frontend/src/interfaces/IUser.ts
Labels: bug

#642 add claim/associate with roles for PIMS_ROLE_R to prevent it from bei…
  database/mssql/scripts/dbscripts/PSP_PIMS_S17_01/Alter Down/74_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S17_01/Alter Down/75_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S17_01/Alter Up/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S17_01/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
Labels: db-migration

#645 Do not attempt to return the person name if tenant is not a person.
  backend/api/Areas/Leases/Mapping/Search/LeaseMap.cs
  backend/entities/Helpers/PersonExtensions.cs
  frontend/src/features/leases/detail/LeasePages/deposits/Deposits.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/Deposits.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/DepositsReceivedTable.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/__snapshots__/DepositsReceivedTable.test.tsx.snap
Labels: bug

#633 Lisos etl fix
  etl/LISOS_PIMS/02_PSP_PIMS_ETL_OPERATIONAL_SS_LOAD_Build.sql
  etl/LISOS_PIMS/02_PSP_PIMS_ETL_OPERATIONAL_SS_PLACEHOLDER_ADDRESS.sql
  etl/LISOS_PIMS/02_PSP_PIMS_ETL_OPERATIONAL_SS_PLACEHOLDER_PERSON.sql
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_Load.dtsx
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_PIMS.dtproj
Labels: etl

#650 PSP-2587: Fix for work phone appearing as home
  frontend/src/features/contacts/contact/detail/Person.tsx
Labels: bug

#658 Refactor test data scripts to be compatible with PSP_PIMS_SPRINT_17_00
  testing/data-scripts/sprint-14/LEASE_TEST_DATA.sql
  testing/data-scripts/sprint-14/TENANT_TEST_DATA.sql
  testing/data-scripts/sprint-15/INSURANCE_TEST_DATA.sql
Labels: test-data

#659 add Rafael to codeowners.
  .github/CODEOWNERS
Labels: help wanted

#666 Manually increment versions
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: devops

#679 Backmerge branch 'master' into 'test'
  backend/api/Areas/Leases/Mapping/Search/LeaseMap.cs
  backend/api/Pims.Api.csproj
  etl/PAIMS_PIMS/PAIMS_PIMS.sln
  etl/PAIMS_PIMS/PAIMS_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/PAIMS 1.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/PAIMS.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_AREA_UNIT_Load.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_LOAD_PAIMS_TO_PIMS_DATASET_2.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_PROPERTY_Load.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_PROPERTY_TENURE_TYPE_Load.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PIMS.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/Project.params
  etl/PAIMS_PIMS/PAIMS_PIMS/lizzard.th.gov.bc.ca.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/sqldevtst.th.gov.bc.ca.conmgr
  frontend/package.json
  frontend/src/features/account/LoginStyled.tsx
  frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  openshift/4.0/pipelines/Jenkinsfile.cicd.prod
Labels: alignment, release-management

#670 Fix tenant test data
  database/mssql/scripts/dbscripts/PSP_PIMS_S17_00/Test Data/TENANT_TEST_DATA.sql
Labels: test-data
