Repository bcgov/PSP, pull requests merged in 2021-08, with the labels that each got.

#130 PSP-1488 logging update
  .github/workflows/app-logging.yml
  openshift/4.0/templates/Logging/README.md
  openshift/4.0/templates/Logging/docker-compose.yml
  openshift/4.0/templates/Logging/logging_dc.yaml
  openshift/4.0/templates/Logging/sidecar-logging.sh
Labels: bug, devops, logging

#131 PSP-1374 Upgrade mapping library React-Leaftlet to v3
  Makefile
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  frontend/src/components/maps/leaflet/Control/Control.test.tsx
  frontend/src/components/maps/leaflet/Control/Control.tsx
  frontend/src/components/maps/leaflet/Control/__snapshots__/Control.test.tsx.snap
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/InfoSlideOut.test.tsx.snap
  frontend/src/components/maps/leaflet/InventoryLayer.tsx
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopUpContent.test.tsx
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContent.tsx
  frontend/src/components/maps/leaflet/LayerPopup/__snapshots__/LayerPopUpContent.test.tsx.snap
  frontend/src/components/maps/leaflet/LayersControl/LayersControl.test.tsx
  frontend/src/components/maps/leaflet/LayersControl/LayersControl.tsx
  frontend/src/components/maps/leaflet/LayersControl/LayersTree.tsx
  frontend/src/components/maps/leaflet/LayersControl/__snapshots__/LayersControl.test.tsx.snap
  frontend/src/components/maps/leaflet/Legend/Legend.test.tsx
  frontend/src/components/maps/leaflet/Legend/Legend.tsx
  frontend/src/components/maps/leaflet/Legend/LegendControl.tsx
  frontend/src/components/maps/leaflet/Legend/__snapshots__/Legend.test.tsx.snap
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/leaflet/MapEvents/MapEvents.tsx
  frontend/src/components/maps/leaflet/MapProperties.test.tsx
  frontend/src/components/maps/leaflet/PointClusterer.tsx
  frontend/src/components/maps/leaflet/SelectedPropertyMarker/SelectedPropertyMarker.tsx
  frontend/src/components/maps/leaflet/ZoomOut/ZoomOutButton.tsx
  frontend/src/components/maps/leaflet/__snapshots__/MapProperties.test.tsx.snap
  frontend/src/features/admin/access-request/AccessRequestPage.test.tsx
  frontend/src/features/admin/agencies/EditAgencyPage.test.tsx
  frontend/src/features/admin/users/ManageUsers.test.tsx
  frontend/src/features/mapSideBar/containers/MotiInventoryContainer.test.tsx
  frontend/src/features/mapSideBar/forms/PropertyForm.test.tsx
  frontend/src/features/properties/filter/PropertyFilter.test.tsx
  frontend/src/features/properties/list/PropertyListView.test.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/router.test.tsx
  frontend/src/utils/TestCommonWrapper.tsx
  frontend/src/utils/test-utils.tsx
  frontend/src/utils/testUtils.ts
Labels: unit-tests, gis, frontend

#132 PSP-1721 Integrate GeoServer
  backend/api/Pims.Api.csproj
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/maps/leaflet/LayersControl/__snapshots__/LayersControl.test.tsx.snap
  frontend/src/components/maps/leaflet/LayersControl/data.ts
  frontend/src/components/maps/leaflet/__snapshots__/MapProperties.test.tsx.snap
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: gis, frontend

#133 Release v0.2.0.7.2
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/maps/leaflet/LayersControl/data.ts
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: gis

#136 modify csp based on conversation with Jeremy, Alejandro. (#87)
  frontend/public/index.html
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: release-management

#137 Deploy v0.2.0.7.3 to TST
  frontend/public/index.html
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: release-management

#140 Clean up test warnings
  frontend/src/features/admin/agencies/EditAgencyPage.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/help/components/HelpSubmitBox.test.tsx
  frontend/src/features/help/components/__snapshots__/HelpSubmitBox.test.tsx.snap
  frontend/src/features/help/containers/HelpModalContentContainer.test.tsx
  frontend/src/features/help/containers/__snapshots__/HelpModalContentContainer.test.tsx.snap
  frontend/src/features/properties/filter/PropertyFilter.test.tsx
Labels: tech-debt

#123 Psp 1652
  .github/workflows/zap-scan.yml
Labels: bug, enhancement, tech-debt

#142 Psp 1635 navbar updates
  frontend/src/components/layout/AppNavBar/AppNavBar.test.tsx
  frontend/src/components/layout/AppNavBar/AppNavBar.tsx
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.test.tsx.snap
Labels: enhancement

#141 Psp 1322 help updates
  frontend/src/features/help/components/HelpModal.tsx
  frontend/src/features/help/components/HelpSubmitBox.scss
  frontend/src/features/help/components/text/LandingFilterHelpText.tsx
  frontend/src/features/help/components/text/LandingMapHelpText.tsx
  frontend/src/features/help/components/text/LandingNavigationHelpText.tsx
Labels: enhancement

#145 Treat keycloak as the source of truth for usernames. Ignore any usern…
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
Labels: bug

#148 PSP-1663: Background image 'scaling'
  frontend/src/features/account/LoginStyled.tsx
  frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
Labels: bug

#143 Devops Pipeline to use Release version from Git
  openshift/4.0/pipelines/Jenkinsfile.cicd
  openshift/4.0/pipelines/Jenkinsfile.cicd.prod
  tools/keycloak/sync/realm.json
Labels: devops

#157 PSP-1784 Replace Initial DB Migration
  backend/dal/Configuration/AccessRequestConfiguration.cs
  backend/dal/Configuration/AddressConfiguration.cs
  backend/dal/Configuration/PersonConfiguration.cs
  backend/dal/Configuration/PropertyConfiguration.cs
  backend/dal/Configuration/UserConfiguration.cs
  backend/dal/Migrations/20210820154301_Initial.Designer.cs
  backend/dal/Migrations/20210820154301_Initial.cs
  backend/dal/Migrations/Initial/Up/PostUp/03-SpatialIndex.sql
  backend/dal/Migrations/Initial/Up/PostUp/99-Triggers.sql
  backend/dal/Migrations/Initial/Up/PreUp/01-History.sql
  backend/dal/Migrations/PimsContextModelSnapshot.cs
  backend/entities/AccessRequest.cs
  backend/entities/User.cs
Labels: enhancement, db-migration

#158 Replacing Initial DB Migration
  backend/core/Extensions/ObjectExtensions.cs
  backend/dal/Migrations/20210820183209_Initial.Designer.cs
  backend/dal/Migrations/20210820183209_Initial.cs
  backend/dal/Migrations/Initial/Up/PostUp/01-OrganizationIdentifierType.sql
  backend/dal/Migrations/Initial/Up/PostUp/01-OrganizationType.sql
  backend/dal/Migrations/Initial/Up/PostUp/03-Address.sql
  backend/dal/Migrations/Initial/Up/PostUp/03-Organization.sql
  backend/dal/Migrations/PimsContextModelSnapshot.cs
  backend/entities/Address.cs
  backend/entities/Property.cs
  backend/tests/unit/dal/Core/Extensions/ObjectExtensionsTest.cs
Labels: enhancement, db-migration

#156 fix keycloak sync tool, as well as some issues with the user api.
  backend/api/Areas/Admin/Mapping/User/OrganizationMap.cs
  backend/api/Areas/Admin/Mapping/User/UserMap.cs
  backend/api/Areas/Admin/Models/User/UserModel.cs
  backend/dal/Migrations/20210820235547_Initial.Designer.cs
  backend/dal/Migrations/20210820235547_Initial.cs
  backend/dal/Migrations/Initial/Up/PostUp/01-Roles.sql
  backend/dal/Migrations/Initial/Up/PostUp/99-Triggers.sql
  backend/dal/Migrations/Initial/Up/PreUp/01-History.sql
  backend/dal/Services/UserService.cs
  backend/entities/ContactMethod.cs
  backend/entities/ContactMethodType.cs
  backend/entities/Helpers/PersonExtensions.cs
  backend/entities/UserOrganization.cs
  tools/keycloak/sync/Models/Pims/UserModel.cs
  tools/keycloak/sync/SyncFactory.cs
Labels: enhancement

#160 PSP-1711 automatic versioning
  .editorconfig
  .github/workflows/version.yml
  backend/api/Pims.Api.csproj
  build/.prettierrc.js
  build/README.md
  build/bump-version.js
  frontend/package.json
Labels: devops, release-management

#163 Add property status type seed
  backend/dal/Migrations/Initial/Up/PostUp/01-PropertyStatusType.sql
Labels: enhancement, db-migration

#172 psp-1390 revert workaround in preparation for firewall change.
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: alignment
