Repository bcgov/PSP, pull requests merged in 2021-10, with the labels that each got.

#323 1rem -> 10px corrections.
  frontend/src/App.scss
  frontend/src/buttons.scss
  frontend/src/components/common/form/Form.scss
  frontend/src/index.scss
Labels: frontend

#330 PSP-2018 Property List View pagination bugfix
  Makefile
  docker-compose.yml
  frontend/src/App.scss
  frontend/src/components/Table/Table.tsx
  frontend/src/components/common/Snackbar.tsx
  frontend/src/components/maps/leaflet/__snapshots__/Map.test.tsx.snap
  frontend/src/components/maps/leaflet/styles.ts
  frontend/src/features/admin/access-request/AccessRequestPage.scss
  frontend/src/features/admin/access-request/AccessRequestPage.tsx
  frontend/src/features/admin/access/ManageAccessRequests.scss
  frontend/src/features/admin/edit-user/EditUserPage.scss
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  frontend/src/features/admin/users/ManageUsers.tsx
  frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
  frontend/src/features/admin/users/styles.ts
  frontend/src/features/properties/list/PropertyListView.scss
  frontend/src/features/properties/list/PropertyListView.tsx
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/layouts/AuthLayout.tsx
  frontend/src/layouts/styles.ts
Labels: bug

#344 Release IS12 to DEV
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#260 correct renderhook tests such that failures are reported properly.
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/hooks/pims-api/useApi.test.ts
  frontend/src/hooks/pims-api/useApiAccessRequests.test.ts
  frontend/src/hooks/pims-api/useApiHealth.test.ts
  frontend/src/hooks/pims-api/useApiLookupCodes.test.ts
  frontend/src/hooks/pims-api/useApiLtsa.test.tsx
  frontend/src/hooks/pims-api/useApiProperties.test.tsx
  frontend/src/hooks/pims-api/useApiTenant.test.ts
  frontend/src/hooks/pims-api/useApiUsers.test.ts
  frontend/src/store/slices/accessRequests/accessRequestsActionCreator.spec.tsx
  frontend/src/store/slices/lookupCodes/lookupCodeActionCreator.spec.tsx
  frontend/src/store/slices/properties/parcelsActionCreator.spec.tsx
  frontend/src/store/slices/users/userActionCreator.test.tsx
Labels: unit-tests

#353 psp-1686 add common lease header.
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Mapping/Lease/OrganizationMap.cs
  backend/api/Areas/Leases/Mapping/Lease/PersonMap.cs
  backend/api/Areas/Leases/Mapping/Lease/PropertyMap.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  backend/api/Areas/Leases/Models/Lease/OrganizationModel.cs
  backend/api/Areas/Leases/Models/Lease/PersonModel.cs
  backend/api/Areas/Leases/Models/Lease/PropertyModel.cs
  backend/api/Areas/Property/Mapping/Property/LeaseMap.cs
  backend/api/Controllers/LookupController.cs
  backend/api/Mapping/Lookup/LookupMap.cs
  backend/dal/Configuration/LeaseConfiguration.cs
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Helpers/Extensions/PropertyExtensions.cs
  backend/dal/PIMSContext.cs
  backend/dal/Services/Interfaces/ILookupService.cs
  backend/dal/Services/LookupService.cs
  backend/entities/Helpers/PersonExtensions.cs
  backend/entities/Lease.cs
  backend/tests/unit/dal/Core/Extensions/LeaseExtensionsTest.cs
  frontend/src/App.tsx
  frontend/src/AppRouter.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/LeaseAttributes.tsx
  frontend/src/components/maps/leaflet/LoadingBackdrop/LoadingBackdrop.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/constants/API.ts
  frontend/src/features/account/LoginLoading.tsx
  frontend/src/features/leases/detail/LeaseContainer.test.tsx
  frontend/src/features/leases/detail/LeaseContainer.tsx
  frontend/src/features/leases/detail/LeaseHeader.tsx
  frontend/src/features/leases/detail/LeaseLayout.tsx
  frontend/src/features/leases/detail/LeaseStatusSummary.test.tsx
  frontend/src/features/leases/detail/LeaseStatusSummary.tsx
  frontend/src/features/leases/detail/StackedPidTenantFields.test.tsx
  frontend/src/features/leases/detail/StackedPidTenantFields.tsx
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseStatusSummary.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/StackedPidTenantFields.test.tsx.snap
  frontend/src/features/leases/hooks/useLeaseDetail.ts
  frontend/src/features/leases/index.ts
  frontend/src/features/leases/leaseUtils.ts
  frontend/src/hooks/useLookupCodeHelpers.tsx
  frontend/src/interfaces/ILease.ts
  frontend/src/interfaces/IOrganization.ts
  frontend/src/interfaces/IPerson.ts
  frontend/src/mocks/filterDataMock.ts
Labels: enhancement

#442 Bump version to 1.0.0-12.13
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#443 Added missing COPY file
  backend/Dockerfile
  backend/Dockerfile.3.1
  backend/Dockerfile.ocp
Labels: bug, devops

#447 Release IS14 to DEV
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management
