Repository bcgov/PSP, pull requests merged in 2021-06, with the labels that each got.

#56 PSP-926 Assorted frontend errors.
  backend/api/Areas/Property/Mapping/Building/BuildingMap.cs
  frontend/src/components/common/ApiVersionInfo.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/leaflet/MapProperties.test.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/hooks/pims-api/useApiHealth.test.ts
  frontend/src/hooks/pims-api/useApiLookupCodes.test.ts
  frontend/src/hooks/pims-api/useApiTenant.test.ts
  frontend/src/hooks/useFavicon.test.ts
  frontend/src/tenants/tenant.test.tsx
Labels: bug

#57 resolve some zap security warnings.
  frontend/package.json
  frontend/public/index.html
  openshift/4.0/pipelines/Jenkinsfile.cicd
  openshift/4.0/scripts/oc-sonar-scan.sh
  openshift/s2i/nginx-runtime/Dockerfile
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: enhancement

#59 PSP-722 Disable Agency dropdown for MOTI tenant
  frontend/src/components/common/ApiVersionInfo.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.CITZ.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.MOTI.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.tsx
  frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.CITZ.test.tsx.snap
  frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.MOTI.test.tsx.snap
  frontend/src/utils/YupSchema.ts
Labels: alignment, enhancement

#61 PSP-1008 Update version v01.10.5
  backend/api/Pims.Api.csproj
Labels: enhancement

#60 Refactor UI feature toggles
  frontend/src/components/layout/AppNavBar/AppNavBar.tsx
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.CITZ.test.tsx.snap
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.MOTI.test.tsx.snap
  frontend/src/features/admin/access-request/AccessRequestPage.tsx
  frontend/src/features/properties/filter/PropertyFilter.tsx
  frontend/src/store/slices/tenants/useTenants.test.tsx
  frontend/src/tenants/FeatureHidden/FeatureHidden.test.tsx
  frontend/src/tenants/FeatureHidden/FeatureHidden.tsx
  frontend/src/tenants/FeatureHidden/index.ts
  frontend/src/tenants/FeatureToggle/FeatureToggle.test.tsx
  frontend/src/tenants/FeatureToggle/FeatureToggle.tsx
  frontend/src/tenants/FeatureToggle/index.ts
  frontend/src/tenants/FeatureVisible/FeatureVisible.test.tsx
  frontend/src/tenants/FeatureVisible/FeatureVisible.tsx
  frontend/src/tenants/FeatureVisible/index.ts
  frontend/src/tenants/index.ts
Labels: enhancement

#65 Disable Jenkins Pipeline Testing and SonarQube
  openshift/4.0/pipelines/Jenkinsfile.cicd
Labels: devops

#62 PSP-985 SonarQube cleanup
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
  .vscode/settings.json
  backend/api/Areas/Admin/Controllers/AgencyController.cs
  backend/api/Areas/Admin/Controllers/UserController.cs
  backend/api/Areas/Project/Controllers/DisposeController.cs
  backend/api/Areas/Project/Controllers/ReportController.cs
  backend/api/Areas/Project/Mapping/Dispose/BuildingMap.cs
  backend/api/Areas/Project/Mapping/Dispose/ParcelMap.cs
  backend/api/Areas/Project/Models/Dispose/ProjectNoteModel.cs
  backend/api/Areas/Project/Models/Dispose/SubdivisionParcelModel.cs
  backend/api/Areas/Property/Controllers/ParcelController.cs
  backend/api/Areas/Property/Mapping/Parcel/ParcelParcelMap.cs
  backend/api/Areas/Property/Mapping/Search/PropertyMap.cs
  backend/api/Areas/Property/Models/Parcel/ParcelSubdivisionModel.cs
  backend/api/Areas/Property/Models/Parcel/SubdivisionParcelModel.cs
  backend/api/Areas/Reports/Mapping/Project/ProjectMap.cs
  backend/api/Areas/Reports/Mapping/Project/ProjectPropertyMap.cs
  backend/api/Areas/Reports/Models/User/UserModel.cs
  backend/api/Areas/Tools/Helpers/ImportProjectsHelper.cs
  backend/api/Areas/Tools/Helpers/ImportPropertiesHelper.cs
  backend/api/Areas/Tools/Models/Import/ProjectModel.cs
  backend/api/Configuration/ProgramOptions.cs
  backend/api/Controllers/HealthController.cs
  backend/api/Controllers/TenantController.cs
  backend/api/Helpers/Authorization/KeyCloakClaimTransformer.cs
  backend/api/Helpers/Extensions/MapperExtensions.cs
  backend/api/Helpers/Logging/LoggerExtension.cs
  backend/api/Helpers/Routes/Constraints/PidConstraint.cs
  backend/api/Mapping/Parcel/AddressMap.cs
  backend/api/Models/Parcel/BuildingParcelModel.cs
  backend/api/Pims.Api.csproj
  backend/api/Program.cs
  backend/dal/Configuration/Views/PropertyConfiguration.cs
  backend/entities/Views/Property.cs
  backend/tests/unit/api/Configuration/ProgramOptionsTest.cs
  backend/tests/unit/api/Controllers/Admin/AgencyControllerTest.cs
  backend/tests/unit/api/Controllers/Project/Mapping/BuildingModelTest.cs
  backend/tests/unit/api/Controllers/Property/ParcelControllerTest.cs
  backend/tests/unit/api/Exceptions/ApiHttpRequestExceptionTest.cs
Labels: enhancement, tech-debt

#64 DotNet 5.0 BuildConfig for API
  backend/Dockerfile.ocp
  openshift/4.0/templates/api/build.yaml
  openshift/4.0/templates/api/quota
  openshift/4.0/templates/base-images/dotnet50/Dockerfile
  openshift/4.0/templates/base-images/dotnet50/Dockerfile.ocp3
  openshift/4.0/templates/base-images/dotnet50/README.md
  openshift/4.0/templates/base-images/dotnet50/build.ocp3.yaml
  openshift/4.0/templates/base-images/dotnet50/build.yaml
Labels: devops, enhancement

#66 Fix docker build
  backend/Dockerfile
Labels: bug

#72 Make codecov patch status informational
  codecov.yml
Labels: devops, enhancement

#68 PSP-1256 Add new sidebar logic with Add a Property button
  backend/ltsa/Extensions/ServiceCollectionExtensions.cs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/layout/AppNavBar/AppNavBar.MOTI.test.tsx
  frontend/src/components/layout/AppNavBar/AppNavBar.tsx
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.CITZ.test.tsx.snap
  frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.MOTI.test.tsx.snap
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.CITZ.test.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.MOTI.test.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/containers/PimsInventoryContainer.test.tsx
  frontend/src/features/mapSideBar/containers/PimsInventoryContainer.tsx
  frontend/src/features/mapSideBar/containers/PimsInventoryGeocoder.test.tsx
  frontend/src/features/mapSideBar/containers/__snapshots__/MapSideBarContainer.test.tsx.snap
  frontend/src/features/mapSideBar/containers/__snapshots__/PimsInventoryContainer.test.tsx.snap
  frontend/src/features/moti/mapSideBar/SubmitPropertySelector.test.tsx
  frontend/src/features/moti/mapSideBar/SubmitPropertySelector.tsx
  frontend/src/features/moti/mapSideBar/__snapshots__/SubmitPropertySelector.test.tsx.snap
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.test.tsx
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.tsx
  frontend/src/features/moti/mapSideBar/containers/__snapshots__/MotiInventoryContainer.test.tsx.snap
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/utils/TestCommonWrapper.tsx
  frontend/src/utils/TestProviderWrapper.tsx
  frontend/src/utils/TestRouterWrapper.tsx
Labels: enhancement

#70 PSP-1252 Fix background image style
  frontend/src/features/account/LoginStyled.tsx
  frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
Labels: bug

#71 PSP-1146 Add SonarQube GitHub Action
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
Labels: devops, enhancement

#73 Unit tests backend
  backend/tests/unit/dal/Services/Admin/AddressServiceTest.cs
  backend/tests/unit/dal/Services/Admin/AdministrativeAreaServiceTest.cs
  backend/tests/unit/dal/Services/Admin/AgencyServiceTest.cs
  backend/tests/unit/dal/Services/Admin/ProjectServiceTest.cs
  backend/tests/unit/dal/Services/Admin/PropertyClassificationTest.cs
  backend/tests/unit/dal/Services/Admin/ProvinceServiceTest.cs
  backend/tests/unit/dal/Services/Admin/RoleServiceTest.cs
  backend/tests/unit/dal/Services/Admin/UserServiceTest.cs
  backend/tests/unit/dal/Services/Admin/WorkflowServiceTest.cs
Labels: unit-tests

#76 Update Docker compose configuration
  docker-compose.yml
Labels: enhancement

#77 PSP-1246 DevOps pipeline 'test' to TEST
  frontend/.prettierignore
  openshift/4.0/pipelines/Jenkinsfile.cicd
  openshift/4.0/scripts/oc-build.sh
  openshift/4.0/scripts/oc-deploy.sh
  openshift/4.0/templates/api/README.md
  openshift/4.0/templates/api/build.yaml
  openshift/4.0/templates/api/deploy-alt-routes.yaml
  openshift/4.0/templates/api/deploy-routes.yaml
  openshift/4.0/templates/api/deploy-swagger.yaml
  openshift/4.0/templates/api/deploy.yaml
  openshift/4.0/templates/app/README.md
  openshift/4.0/templates/app/deploy-alt-routes.yaml
  openshift/4.0/templates/app/deploy-routes.yaml
  openshift/4.0/templates/app/deploy.yaml
Labels: devops

#80 Merge test branch into master in preparation for UAT deployment
  backend/tests/unit/dal/Services/Admin/AddressServiceTest.cs
  backend/tests/unit/dal/Services/Admin/AdministrativeAreaServiceTest.cs
  backend/tests/unit/dal/Services/Admin/AgencyServiceTest.cs
  backend/tests/unit/dal/Services/Admin/ProjectServiceTest.cs
  backend/tests/unit/dal/Services/Admin/PropertyClassificationTest.cs
  backend/tests/unit/dal/Services/Admin/ProvinceServiceTest.cs
  backend/tests/unit/dal/Services/Admin/RoleServiceTest.cs
  backend/tests/unit/dal/Services/Admin/UserServiceTest.cs
  backend/tests/unit/dal/Services/Admin/WorkflowServiceTest.cs
  docker-compose.yml
  frontend/.prettierignore
  openshift/4.0/pipelines/Jenkinsfile.cicd
  openshift/4.0/scripts/oc-build.sh
  openshift/4.0/scripts/oc-deploy.sh
  openshift/4.0/templates/api/README.md
  openshift/4.0/templates/api/build.yaml
  openshift/4.0/templates/api/deploy-alt-routes.yaml
  openshift/4.0/templates/api/deploy-routes.yaml
  openshift/4.0/templates/api/deploy-swagger.yaml
  openshift/4.0/templates/api/deploy.yaml
  openshift/4.0/templates/app/README.md
  openshift/4.0/templates/app/deploy-alt-routes.yaml
  openshift/4.0/templates/app/deploy-routes.yaml
  openshift/4.0/templates/app/deploy.yaml
Labels: devops

#79 DAL Unit Tests
  backend/tests/unit/dal/Services/Admin/BuildingContructionTypeServiceTest.cs
  backend/tests/unit/dal/Services/Admin/ProjectRiskServiceTest.cs
  backend/tests/unit/dal/Services/Admin/TierLevelServiceTest.cs
Labels: unit-tests

#75 PSP-1140 Property Information Form
  backend/api/Areas/Tools/Controllers/LtsaController.cs
  backend/api/Mapping/Converters/ParcelConverter.cs
  backend/tests/unit/api/Controllers/Tools/LtsaControllerTest.cs
  frontend/public/index.html
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
  frontend/src/components/maps/leaflet/MapProperties.test.tsx
  frontend/src/features/mapSideBar/components/MapSideBarLayout.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.CITZ.test.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.MOTI.test.tsx
  frontend/src/features/mapSideBar/containers/PimsInventoryContainer.test.tsx
  frontend/src/features/mapSideBar/containers/PimsInventoryContainer.tsx
  frontend/src/features/mapSideBar/containers/PimsInventoryGeocoder.test.tsx
  frontend/src/features/moti/mapSideBar/InventoryTabs.tsx
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.test.tsx
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.tsx
  frontend/src/features/moti/mapSideBar/forms/PropertyForm.tsx
  frontend/src/features/moti/mapSideBar/forms/PropertySearchForm.tsx
  frontend/src/features/moti/mapSideBar/hooks/useMarkerSearch.tsx
  frontend/src/features/properties/hooks/useParcelLayerData.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/hooks/pims-api/useApiLtsa.test.tsx
  frontend/src/hooks/pims-api/useApiLtsa.tsx
  frontend/src/interfaces/ltsaModels.ts
  frontend/src/store/slices/leafletMouse/LeafletMouseSlice.ts
  frontend/src/utils/TestCommonWrapper.tsx
  frontend/src/utils/TestProviderWrapper.tsx
  frontend/src/utils/utils.ts
Labels: enhancement

#82 Revert "PSP-1140 Property Information Form (#75)"
  backend/api/Areas/Tools/Controllers/LtsaController.cs
  backend/api/Mapping/Converters/ParcelConverter.cs
  backend/tests/unit/api/Controllers/Tools/LtsaControllerTest.cs
  codecov.yml
  frontend/public/index.html
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
  frontend/src/components/maps/leaflet/MapProperties.test.tsx
  frontend/src/features/mapSideBar/components/MapSideBarLayout.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.CITZ.test.tsx
  frontend/src/features/mapSideBar/containers/MapSideBarContainer.MOTI.test.tsx
  frontend/src/features/mapSideBar/containers/PimsInventoryContainer.test.tsx
  frontend/src/features/mapSideBar/containers/PimsInventoryContainer.tsx
  frontend/src/features/mapSideBar/containers/PimsInventoryGeocoder.test.tsx
  frontend/src/features/moti/mapSideBar/InventoryTabs.tsx
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.test.tsx
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.tsx
  frontend/src/features/moti/mapSideBar/forms/PropertyForm.tsx
  frontend/src/features/moti/mapSideBar/forms/PropertySearchForm.tsx
  frontend/src/features/moti/mapSideBar/hooks/useMarkerSearch.tsx
  frontend/src/features/properties/hooks/useParcelLayerData.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/hooks/pims-api/useApiLtsa.test.tsx
  frontend/src/hooks/pims-api/useApiLtsa.tsx
  frontend/src/interfaces/ltsaModels.ts
  frontend/src/store/slices/leafletMouse/LeafletMouseSlice.ts
  frontend/src/utils/TestCommonWrapper.tsx
  frontend/src/utils/TestProviderWrapper.tsx
  frontend/src/utils/utils.ts
Labels: bug

#83 PSP-1187 Change Base Map to BC Data Warehouse
  frontend/public/basemaps.json
  frontend/public/index.html
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: gis

#84 PIMS-1248 Update API version to v01.11.00
  backend/api/Pims.Api.csproj
Labels: enhancement

#85 uat-prod pipeline
  codecov.yml
  openshift/4.0/pipelines/Jenkinsfile.cicd.prod
Labels: devops

#87 update csp to include a wider match for gov.bc.ca whitelist
  frontend/public/index.html
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: devops, enhancement

#90 PSP_1144 duplicate pid and populate by layer functionality.
  frontend/src/App.scss
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/features/moti/mapSideBar/InventoryTabs.tsx
  frontend/src/features/moti/mapSideBar/components/MapSideBarLayout.tsx
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.test.tsx
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.tsx
  frontend/src/features/moti/mapSideBar/forms/PropertyForm.tsx
  frontend/src/features/moti/mapSideBar/forms/PropertySearchForm.tsx
  frontend/src/features/moti/mapSideBar/hooks/useDuplicatePidModal.tsx
  frontend/src/features/properties/components/GeocoderAutoComplete.tsx
  frontend/src/hooks/useApi.ts
  frontend/src/hooks/useCallbackAppSelector.ts
  openshift/4.0/templates/api/deploy.yaml
Labels: bug, enhancement

#92 prevent vertical overflow of search form.
  frontend/src/features/moti/mapSideBar/forms/PropertySearchForm.tsx
Labels: bug

#93 PSP-1392 DevOps improvements
  openshift/4.0/pipelines/Jenkinsfile.cicd
  openshift/4.0/templates/app/README.md
  openshift/4.0/templates/app/build.yaml
  openshift/s2i/README.md
  openshift/s2i/nginx-build.png
  openshift/s2i/nginx-runtime/nginx-runtime.yaml
Labels: devops

#94 Updates from UI/UX review from Bobbi PSP-1366
  frontend/src/components/SearchBar/FilterBar.tsx
  frontend/src/components/common/form/Form.tsx
  frontend/src/features/moti/mapSideBar/InventoryTabs.tsx
  frontend/src/features/moti/mapSideBar/components/FormHeader.tsx
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.test.tsx
  frontend/src/features/moti/mapSideBar/containers/MotiInventoryContainer.tsx
  frontend/src/features/moti/mapSideBar/forms/PropertyForm.test.tsx
  frontend/src/features/moti/mapSideBar/forms/PropertySearchForm.tsx
  frontend/src/features/moti/mapSideBar/strings.ts
Labels: enhancement

#95 PSP-1433 Agency error appears when submitting access request
  Makefile
  backend/api/Areas/Admin/Controllers/AccessRequestController.cs
  backend/api/Controllers/UserController.cs
  frontend/src/features/admin/access-request/AccessRequestPage.CITZ.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.MOTI.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.tsx
  frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.CITZ.test.tsx.snap
  frontend/src/features/admin/access/ManageAccessRequests.test.tsx
  frontend/src/features/admin/access/ManageAccessRequests.tsx
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
  frontend/src/features/admin/access/constants/constants.tsx
  frontend/src/features/admin/edit-user/EditUserPage.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  frontend/src/interfaces/accessRequests.ts
  frontend/src/mocks/filterDataMock.ts
  frontend/src/store/slices/accessRequests/accessRequestsSlice.ts
  frontend/src/utils/YupSchema.ts
Labels: bug

#97 PSP-1404 DevOps: Send pipeline notifications to MS Teams
  openshift/4.0/pipelines/Jenkinsfile.cicd
  openshift/4.0/pipelines/scripts/notify-teams.groovy
  openshift/4.0/templates/jenkins/README.md
  openshift/4.0/templates/jenkins/teams_webhook_url.png
Labels: devops
