Repository bcgov/PSP, pull requests merged in 2021-09, with the labels that each got.

#177 Release IS8 to DEV
  Makefile
  backend/api/Pims.Api.csproj
  build/bump-version.js
  frontend/package.json
Labels: release-management

#180 Disable auto-versioning action until it can be fixed
  .github/workflows/version.yml
Labels: release-management

#170 Fix for user position filter on user management page.
  backend/api/Controllers/AccessRequestController.cs
  backend/api/Mapping/AccessRequest/AccessRequestMap.cs
  backend/api/Models/AccessRequest/AccessRequestModel.cs
  backend/api/Pims.Api.csproj
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Services/UserService.cs
  backend/entities/Models/UserFilter.cs
  backend/tests/unit/api/Controllers/AccessControllerTest.cs
  backend/tests/unit/api/Controllers/Admin/UserControllerTest.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  backend/tests/unit/dal/Services/UserServiceTest.cs
  frontend/src/features/admin/access-request/AccessRequestPage.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.tsx
  frontend/src/store/slices/accessRequests/accessRequestsSlice.ts
  tools/keycloak/sync/appsettings.development.json
Labels: enhancement

#176 psp-1370 display filterable properties on the map using geoserver.
  backend/dal/Migrations/Initial/Up/PostUp/02_PIMS_PROPERTY_LOCATION_VW.sql
  frontend/src/App.scss
  frontend/src/_variables.scss
  frontend/src/components/common/form/SearchButton.tsx
  frontend/src/components/maps/leaflet/InventoryLayer.tsx
  frontend/src/components/maps/leaflet/Map.test.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/leaflet/mapUtils.test.tsx
  frontend/src/components/maps/leaflet/mapUtils.tsx
  frontend/src/constants/API.ts
  frontend/src/features/properties/common/slices/usePropertyNames.ts
  frontend/src/features/properties/filter/IPropertyFilter.ts
  frontend/src/features/properties/filter/PropertyFilter.scss
  frontend/src/features/properties/filter/PropertyFilter.test.tsx
  frontend/src/features/properties/filter/PropertyFilter.tsx
  frontend/src/features/properties/filter/PropertyFilterOptions.tsx
  frontend/src/features/properties/filter/PropertyFilterOrganizationOptions.test.tsx
  frontend/src/features/properties/filter/PropertyFilterOrganizationOptions.tsx
  frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  frontend/src/features/properties/filter/__snapshots__/PropertyFilterOptions.test.tsx.snap
  frontend/src/features/properties/filter/__snapshots__/PropertyFilterOrganizationOptions.test.tsx.snap
  frontend/src/features/properties/list/PropertyListView.test.tsx
  frontend/src/features/properties/list/PropertyListView.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/features/properties/service.ts
  frontend/src/hooks/useApi.ts
  frontend/src/hooks/useRouterFilter.ts
  frontend/src/store/slices/accessRequests/accessRequestsActionCreator.spec.tsx
  frontend/src/store/slices/properties/useProperties.ts
Labels: enhancement, gis

#186 Release IS8 to DEV - version 0.2.0-8.2
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/src/components/common/ApiVersionInfo.test.tsx
  frontend/src/components/common/ApiVersionInfo.tsx
Labels: release-management

#187 Corrections from dev testing of psp-1370
  backend/dal/Migrations/Initial/Up/PostUp/02_PIMS_PROPERTY_LOCATION_VW.sql
  frontend/src/App.scss
  frontend/src/components/maps/leaflet/PointClusterer.tsx
Labels: bug

#205 DEPLOY IS10 to DEV Environment
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#210 Added lease data
  database/mssql/scripts/dbscripts/PSP_PIMS_S10_00/Build/82_DML_LEASE_TESTING.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S10_00/Build/83_DML_LEASE_LOAD.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S10_00/Build/84_DML_LEASE_PROPERTY.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S10_00/Build/85_DML_PROPERTY_LEASE.sql
Labels: db-migration

#203 Add migration so views are added without requiring db refresh
  backend/dal/Migrations/20210908232309_v0.2.0.9.1.Designer.cs
  backend/dal/Migrations/20210908232309_v0.2.0.9.1.cs
  backend/dal/Migrations/v0.2.0.9.1/Up/PostUp/02_PIMS_PROPERTY_BOUNDARY_VW.sql
  backend/dal/Migrations/v0.2.0.9.1/Up/PostUp/02_PIMS_PROPERTY_LOCATION_VW.sql
Labels: db-migration

#202 Psp 1843 side tray for side bar.
  frontend/src/App.scss
  frontend/src/assets/images/airline-stops.svg
  frontend/src/assets/images/dynamic-form.svg
  frontend/src/assets/images/insights.svg
  frontend/src/assets/images/inventory.svg
  frontend/src/assets/images/real-estate-agent.svg
  frontend/src/assets/images/source.svg
  frontend/src/components/SearchBar/FilterBar.scss
  frontend/src/components/common/LabelledIcon.tsx
  frontend/src/components/layout/SideNavBar/AdminTools.tsx
  frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  frontend/src/components/layout/SideNavBar/NavIcon.tsx
  frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  frontend/src/components/layout/SideNavBar/SideTray.tsx
  frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  frontend/src/components/layout/SideNavBar/styles.ts
  frontend/src/components/layout/index.ts
  frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/InfoSlideOut.test.tsx.snap
  frontend/src/components/maps/leaflet/InventoryLayer.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/leaflet/__snapshots__/Map.test.tsx.snap
  frontend/src/components/maps/leaflet/styles.ts
  frontend/src/features/properties/filter/PropertyFilter.scss
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/layouts/AuthLayout.tsx
  frontend/src/layouts/SideNavbar.test.tsx
  frontend/src/layouts/SideNavbar.tsx
  frontend/src/layouts/__snapshots__/SideNavbar.test.tsx.snap
  frontend/src/layouts/styles.ts
  frontend/src/utils/TestCommonWrapper.tsx
  frontend/src/utils/test-utils.tsx
Labels: enhancement, tech-debt, frontend

#218 PSP-1848 Update Property Search Bar
  frontend/src/assets/images/icon-map.svg
  frontend/src/assets/images/icon-table.svg
  frontend/src/components/SearchBar/FilterBar.tsx
  frontend/src/components/common/form/PlusButton.tsx
  frontend/src/components/common/form/ResetButton.tsx
  frontend/src/components/common/form/SearchButton.tsx
  frontend/src/components/common/form/SearchToggle.tsx
  frontend/src/components/common/form/index.ts
  frontend/src/components/maps/leaflet/InventoryLayer.tsx
  frontend/src/features/properties/filter/PropertyFilter.tsx
  frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  frontend/src/features/properties/list/PropertyListView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: enhancement

#212 Psp 1772 lease search form
  backend/api/Areas/Leases/Controllers/SearchController.cs
  backend/api/Areas/Leases/Mapping/Search/LeaseMap.cs
  backend/api/Areas/Leases/Models/Search/LeaseFilterModel.cs
  backend/api/Areas/Leases/Models/Search/LeaseModel.cs
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Helpers/Extensions/PropertyExtensions.cs
  backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  backend/dal/IPimsService.cs
  backend/dal/PIMSContext.cs
  backend/dal/PimsService.cs
  backend/dal/Services/Interfaces/ILeaseService.cs
  backend/dal/Services/LeaseService.cs
  backend/entities/Models/LeaseFilter.cs
  backend/tests/core/Entities/LeaseHelper.cs
  backend/tests/unit/api/Controllers/Leases/SearchControllerTest.cs
  backend/tests/unit/dal/Services/PropertyServiceTest.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_S10_00/Build/82_DML_LEASE_TESTING.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S10_00/Build/83_DML_LEASE_LOAD.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S10_00/Build/85_DML_PROPERTY_LEASE.sql
  frontend/src/App.scss
  frontend/src/buttons.scss
  frontend/src/components/SearchBar/__snapshots__/FilterBar.test.tsx.snap
  frontend/src/components/common/form/Input.tsx
  frontend/src/components/common/form/InputGroup.scss
  frontend/src/components/common/form/SearchButton.tsx
  frontend/src/components/common/form/styles.ts
  frontend/src/components/common/styles.ts
  frontend/src/components/layout/SideNavBar/AdminTools.tsx
  frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  frontend/src/components/layout/SideNavBar/SideTray.tsx
  frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
  frontend/src/features/leases/components/LeaseAndLicenseFilter.tsx
  frontend/src/features/leases/components/LeaseAndLicenseListView.test.tsx
  frontend/src/features/leases/components/LeaseAndLicenseListView.tsx
  frontend/src/features/leases/interfaces.ts
  frontend/src/features/properties/filter/PropertyFilterOptions.tsx
  frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/headers.scss
  frontend/src/hooks/pims-api/useApiLeases.ts
  frontend/src/interfaces/ILease.ts
  frontend/src/interfaces/index.ts
  frontend/src/router.tsx
  frontend/src/styles.scss
Labels: enhancement

#223 psp-1767
  frontend/src/buttons.scss
  frontend/src/components/layout/Header/Header.test.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/HeaderStyled.tsx
  frontend/src/components/layout/Header/__snapshots__/EmptyHeader.test.tsx.snap
  frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
  frontend/src/features/help/components/HelpModal.tsx
  frontend/src/features/help/containers/HelpContainer.tsx
  frontend/src/features/help/containers/__snapshots__/HelpContainer.test.tsx.snap
  frontend/src/layouts/Header.tsx
  frontend/src/layouts/__snapshots__/EmptyLayout.test.tsx.snap
  frontend/src/layouts/__snapshots__/Header.test.tsx.snap
Labels: bug

#226 support searching by pid/pin with leading 0's.
  frontend/src/components/layout/Header/Header.test.tsx
  frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  frontend/src/components/maps/leaflet/Map.test.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/constants/API.ts
  frontend/src/features/account/LoginStyled.tsx
  frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  frontend/src/hooks/pims-api/useApi.test.ts
  frontend/src/hooks/pims-api/useApi.ts
  frontend/src/hooks/pims-api/useApiAccessRequests.ts
  frontend/src/hooks/pims-api/useApiHealth.ts
  frontend/src/hooks/pims-api/useApiLeases.ts
  frontend/src/hooks/pims-api/useApiLookupCodes.ts
  frontend/src/hooks/pims-api/useApiLtsa.tsx
  frontend/src/hooks/pims-api/useApiProperties.ts
  frontend/src/hooks/pims-api/useApiTenants.ts
  frontend/src/hooks/pims-api/useApiUsers.ts
Labels: bug, gis, frontend

#213 Psp 1839 add property lease details to slideout
  backend/api/Areas/Property/Mapping/Property/LeaseMap.cs
  backend/api/Areas/Property/Mapping/Property/PropertyMap.cs
  backend/api/Areas/Property/Models/Property/LeaseModel.cs
  backend/api/Areas/Property/Models/Property/PropertyModel.cs
  backend/dal/Helpers/Extensions/PropertyExtensions.cs
  backend/dal/Services/PropertyService.cs
  backend/tests/core/Entities/PropertyHelper.cs
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/LeaseAttributes.tsx
  frontend/src/features/leases/components/LeaseAndLicenseListView.test.tsx
  frontend/src/interfaces/ILease.ts
  frontend/src/interfaces/IProperty.ts
  frontend/src/interfaces/index.ts
Labels: enhancement

#221 PSP-1906 DEVSECOPS Credentials scan
  .github/.trufflehog3.yml
  .github/workflows/credentials-comment-pr.yml
  .github/workflows/credentials-scan.yml
  .gitignore
  Makefile
  build/secops_report.sh
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/Project.params
  etl/PAIMS_PIMS/PAIMS_PIMS/lizzard.th.gov.bc.ca.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/sqldevtst.th.gov.bc.ca.conmgr
  openshift/4.0/README.md
  openshift/4.0/scripts/oc-sonar-scan.sh
  openshift/4.0/templates/maintenance/README.md
  openshift/s2i/README.md
Labels: devops

#222 Layers
  backend/dal/Services/PropertyService.cs
  frontend/public/tenants/tenant.json
  frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  frontend/src/tenants/config/CITZ.ts
  frontend/src/tenants/config/MOTI.ts
  frontend/src/tenants/useTenant.test.tsx
Labels: enhancement, devops, frontend

#232 support customizable layer urls in TEST.
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/public/tenants/tenant.json
  frontend/src/components/maps/leaflet/LayersControl/LayersTree.tsx
  frontend/src/hooks/useApi.ts
  frontend/src/tenants/ITenantConfig.ts
  frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  frontend/src/tenants/config/default.ts
  frontend/src/tenants/useTenant.test.tsx
Labels: gis

#230 Discuss exceptions to security scans
  .github/.trufflehog3.yml
  .github/workflows/credentials-comment-pr.yml
  .github/workflows/credentials-scan.yml
  auth/keycloak/config/realm-export.json
  build/README.md
  build/secops_report.sh
  frontend/public/tenants/tenant.json
Labels: devops

#243 psp-1742 remove zap scan, references as is no longer used.
  openshift/4.0/pipelines/Jenkinsfile.cicd
  openshift/4.0/pipelines/README.md
  openshift/4.0/templates/jenkins-slaves/README.md
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-config-map.yaml
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-generic-template.yaml
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/.dockerignore
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/.xinitrc
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/Dockerfile
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/Jenkinsfile.test
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/README.md
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/configuration/nexus-settings.xml
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/configuration/passwd.template
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/configuration/run-jnlp-client
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/configuration/settings.xml
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/API-Minimal.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/Default Policy.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-High-Th-High.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-High-Th-Low.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-High-Th-Med.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-Ins-Th-High.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-Ins-Th-Low.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-Ins-Th-Med.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-Low-Th-High.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-Low-Th-Low.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-Low-Th-Med.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-Med-Th-High.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/policies/St-Med-Th-Low.policy
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/webswing.config
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/zap/zap-api-scan.py
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/zap/zap-baseline.py
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/zap/zap-full-scan.py
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/zap/zap-webswing.sh
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/zap/zap-x.sh
  openshift/4.0/templates/jenkins-slaves/jenkins-slave-zap/zap/zap_common.py
  openshift/4.0/templates/jenkins-slaves/zap-jenkins-slave.yaml
Labels: devops

#242 PSP-1381 Property List View
  backend/api/Areas/Property/Controllers/SearchController.cs
  backend/api/Areas/Property/Mapping/Search/AddressMap.cs
  backend/api/Areas/Property/Mapping/Search/PropertyMap.cs
  backend/api/Areas/Property/Models/Search/AddressModel.cs
  backend/api/Areas/Property/Models/Search/PropertyFilterModel.cs
  backend/api/Areas/Property/Models/Search/PropertyModel.cs
  backend/api/Areas/Reports/Controllers/PropertyController.cs
  backend/api/Areas/Reports/Mapping/Property/AllFieldsPropertyMap.cs
  backend/dal/Helpers/Extensions/PropertyExtensions.cs
  backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
  backend/tests/unit/api/Controllers/Reports/PropertyControllerTest.cs
  frontend/.vscode/launch.json
  frontend/src/components/Table/Table.tsx
  frontend/src/components/maps/leaflet/Map.test.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/constants/API.ts
  frontend/src/features/properties/filter/PropertyFilter.test.tsx
  frontend/src/features/properties/filter/PropertyFilter.tsx
  frontend/src/features/properties/filter/PropertyFilterOptions.tsx
  frontend/src/features/properties/list/PropertyListView.styled.ts
  frontend/src/features/properties/list/PropertyListView.test.tsx
  frontend/src/features/properties/list/PropertyListView.tsx
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/features/properties/list/columns.tsx
  frontend/src/features/properties/list/index.ts
  frontend/src/features/properties/list/interfaces/IFlatProperty.ts
  frontend/src/features/properties/list/interfaces/IParentParcel.ts
  frontend/src/features/properties/list/interfaces/IPropertyQueryParams.ts
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/service.ts
  frontend/src/hooks/pims-api/useApiProperties.test.tsx
  frontend/src/hooks/pims-api/useApiProperties.ts
  frontend/src/hooks/useRouterFilter.test.tsx
  frontend/src/hooks/useRouterFilter.ts
  frontend/src/router.test.tsx
  frontend/src/store/slices/properties/useProperties.ts
  frontend/src/utils/download.ts
  frontend/src/utils/propertyUtils.ts
  frontend/src/utils/test-utils.tsx
  tools/keycloak/sync/realm.json
Labels: frontend

#246 remove unused reference to sonar token.
  openshift/4.0/pipelines/Jenkinsfile.cicd
Labels: bug, devops

#239 psp-1936 ensure region displays properly, correct map property popup.
  backend/api/Areas/Property/Mapping/Property/PropertyMap.cs
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
  frontend/src/components/maps/leaflet/LayerPopup/PidLink.tsx
  frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
Labels: bug

#249 Bump IS10 version number in preparation for release
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#250 Merge test to dev
  backend/dal/Migrations/20210908232309_v0.2.0.9.1.Designer.cs
  backend/dal/Migrations/20210908232309_v0.2.0.9.1.cs
  backend/dal/Migrations/v0.2.0.9.1/Up/PostUp/02_PIMS_PROPERTY_BOUNDARY_VW.sql
  backend/dal/Migrations/v0.2.0.9.1/Up/PostUp/02_PIMS_PROPERTY_LOCATION_VW.sql
  frontend/public/tenants/tenant.json
  frontend/src/components/maps/leaflet/LayersControl/LayersTree.tsx
  frontend/src/hooks/useApi.ts
  frontend/src/tenants/ITenantConfig.ts
  frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  frontend/src/tenants/config/default.ts
Labels: release-management

#252 remove unused pipeline script.
  openshift/4.0/pipelines/Jenkinsfile.push-to-uat
Labels: devops

#254 Sonar fixes
  frontend/src/App.tsx
  frontend/src/AppRouter.tsx
  frontend/src/components/Table/ColumnFilter.tsx
  frontend/src/components/Table/Table.tsx
  frontend/src/components/common/form/FastSelect.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/UserProfile.tsx
  frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
  frontend/src/components/maps/leaflet/InventoryLayer.tsx
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContent.tsx
  frontend/src/components/maps/leaflet/LayersControl/LayersControl.tsx
  frontend/src/components/maps/leaflet/LayersControl/LayersMenu.tsx
  frontend/src/components/maps/leaflet/Legend/LegendControl.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/leaflet/PointClusterer.tsx
  frontend/src/features/account/Login.tsx
  frontend/src/features/admin/access/ManageAccessRequests.tsx
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/admin/users/ManageUsers.tsx
  frontend/src/features/leases/components/LeaseAndLicenseListView.tsx
  frontend/src/features/properties/common/slices/propertyNameSlice.ts
  frontend/src/features/properties/hooks/useDraftMarkerSynchronizer.tsx
  frontend/src/features/properties/list/PropertyListView.scss
  frontend/src/hooks/useLookupCodeHelpers.tsx
  frontend/src/hooks/useRouterFilter.ts
  frontend/src/index.tsx
  frontend/src/layouts/EmptyLayout.tsx
  frontend/src/router.test.tsx
  frontend/src/tenants/tenant.tsx
  frontend/src/utils/PrivateRoute.tsx
  frontend/src/utils/getKeycloakEventHandler.test.ts
  frontend/src/utils/getKeycloakEventHandler.ts
  frontend/src/utils/test-utils.tsx
Labels: enhancement, tech-debt

#258 PSP-1381 Fix unit tests for `useProperties` hook
  frontend/src/store/slices/properties/useProperties.test.tsx
Labels: unit-tests

#263 Release IS9 v0.2.0-9.2 to TST
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#266 allow pidformatter to handle number or string types.
  frontend/src/utils/propertyUtils.ts
Labels: bug

#267 psp-1978 Correct double clicks on map markers clearing some slide out…
  frontend/src/components/maps/leaflet/PointClusterer.tsx
Labels: bug

#268 psp-1984 support simultaneous pid/pin search.
  frontend/src/components/maps/leaflet/mapUtils.tsx
Labels: bug

#269 psp-1983 force reset the filter.
  frontend/src/features/properties/filter/PropertyFilter.tsx
Labels: bug

#270 fix viewing spiderfied properties.
  frontend/src/components/maps/leaflet/PointClusterer.tsx
Labels: bug

#274 psp-1985 disable slide out zoom.
  frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/HeaderActions.test.tsx.snap
Labels: bug

#271 PSP-1261 Add geoserver docker container
  .github/.trufflehog3.yml
  .gitignore
  Makefile
  docker-compose.yml
  frontend/src/setupProxy.js
  geoserver/README.md
  geoserver/geoserver_data/default.xml
  geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_VW/featuretype.xml
  geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_VW/layer.xml
  geoserver/geoserver_data/psp/namespace.xml
  geoserver/geoserver_data/psp/settings.xml
  geoserver/geoserver_data/psp/wfs.xml
  geoserver/geoserver_data/psp/workspace.xml
  scripts/gen-env-files.sh
Labels: enhancement, gis, frontend

#296 PSP-1700 Fix automatic versioning action
  .github/workflows/version.yml
Labels: release-management

#313 Update image scan github action.
  .github/workflows/image-scan-analysis.yml
Labels: release-management

#310 psp-2016 correct display of user management page
  frontend/src/features/admin/users/ManageUsers.tsx
  frontend/src/layouts/AuthLayout.tsx
Labels: bug

#314 Backmerge test to dev. resolve conflicts.
  .github/workflows/image-scan-analysis.yml
  frontend/src/features/account/LoginStyled.tsx
  frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  frontend/src/features/admin/users/ManageUsers.tsx
  frontend/src/layouts/AuthLayout.tsx
Labels: release-management

#317 CI: bump version to v0.2.0-10.2
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#318 Release IS11 to DEV
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management
