Repository bcgov/PSP, pull requests merged in 2022-01, with the labels that each got.

#688 Dev backmerge
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Mapping/Search/LeaseMap.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  backend/dal/PIMSContext.cs
  backend/entities/ef/PimsLease.cs
  backend/entities/ef/PimsLeaseHist.cs
  etl/PAIMS_PIMS/PAIMS_PIMS.sln
  etl/PAIMS_PIMS/PAIMS_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/PAIMS 1.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/PAIMS.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_AREA_UNIT_Load.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_LOAD_PAIMS_TO_PIMS_DATASET_2.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_PROPERTY_Load.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_PROPERTY_TENURE_TYPE_Load.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PIMS.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/Project.params
  etl/PAIMS_PIMS/PAIMS_PIMS/lizzard.th.gov.bc.ca.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/sqldevtst.th.gov.bc.ca.conmgr
  frontend/src/features/account/LoginStyled.tsx
  frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  frontend/src/features/admin/edit-user/EditUserPage.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/admin/users/ManageUsers.test.tsx
  frontend/src/features/admin/users/ManageUsers.tsx
  frontend/src/features/contacts/contact/detail/Organization.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
  frontend/src/features/leases/list/LeaseListView.tsx
  frontend/src/interfaces/IUser.ts
  openshift/4.0/pipelines/Jenkinsfile.cicd.prod
Labels: devops

#684 psp-2528 update improvements field names.
  backend/api/Areas/Leases/Mapping/Lease/PropertyImprovementMap.cs
  backend/api/Areas/Leases/Models/Lease/PropertyImprovementModel.cs
  frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
  frontend/src/interfaces/ILeaseImprovement.ts
Labels: enhancement

#685 update sonarqube configuration for newer version.
  openshift/4.0/templates/sonarqube/sonarqube-postgresql-template.yaml
Labels: devops

#708 Increment DEV version to IS18
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#712 Increment DEV version to IS19
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#702 Psp 2396
  etl/PAIMS_PIMS/PAIMS_PIMS/IS15.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/PAIMS 1.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_LOAD_PAIMS_TO_PIMS_DATASET_2.dtsx
Labels: etl

#716 Psp 2658 removing roles from users fails in UAT
  backend/api/Pims.Api.csproj
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Services/Interfaces/IUserService.cs
  backend/dal/Services/UserService.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  frontend/package.json
Labels: bug

#715 PSP 2527 - Update oc builds to use unique tags
  Makefile
  openshift/4.0/pipelines/Jenkinsfile.cicd
  openshift/4.0/scripts/oc-deploy.sh
  openshift/4.0/templates/api/build.yaml
  openshift/4.0/templates/app/build.yaml
Labels: devops

#717 psp-2660 add simple retry to lazy load promise.
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/src/AppRouter.tsx
  frontend/src/utils/utils.ts
Labels: bug

#727 Updated phone list | PSP-2649
  frontend/src/features/contacts/contact/detail/Person.test.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
Labels: bug

#733 PSP-2678: Correct draft color
  frontend/src/colors.scss
Labels: bug

#735 System Constants | psp-2178
  backend/api/Controllers/SystemConstantController.cs
  backend/api/Mapping/SystemConstantMap.cs
  backend/api/Models/SystemConstantModel.cs
  backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  backend/dal/IPimsService.cs
  backend/dal/PimsService.cs
  backend/dal/Services/Interfaces/ISystemConstantService.cs
  backend/dal/Services/SystemConstantService.cs
  frontend/src/App.tsx
  frontend/src/constants/actionTypes.ts
  frontend/src/hooks/pims-api/useApiSystemConstants.ts
  frontend/src/store/slices/systemConstants/index.ts
  frontend/src/store/slices/systemConstants/interfaces/ISystemConstant.ts
  frontend/src/store/slices/systemConstants/interfaces/ISystemConstantsState.ts
  frontend/src/store/slices/systemConstants/interfaces/index.ts
  frontend/src/store/slices/systemConstants/systemConstantsActionCreator.spec.tsx
  frontend/src/store/slices/systemConstants/systemConstantsReducer.test.tsx
  frontend/src/store/slices/systemConstants/systemConstantsSlice.ts
  frontend/src/store/slices/systemConstants/useSystemConstants.ts
Labels: enhancement

#738 rebuild image instead of container to ensure dbscripts folder up to d…
  Makefile
Labels: bug

#734 Adjust test data for S19 schema
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/03_DML_LEASE_TESTING.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/04_DML_LEASE_LOAD.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/05_DML_LEASE_PROPERTY.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/06_DML_PROPERTY_LEASE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/07_CONTACTS_ORGANIZATION_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/08_CONTACTS_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/09_INSURANCE_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/10_LEASE_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/11_SECURITY_DEPOSIT_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/12_SECURITY_DEPOSIT_RETURN_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/13_SURPLUS_DECLERATION_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/14_TENANT_TEST_DATA.sql
Labels: test-data

#748 Backport 2396 to test
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Services/Interfaces/IUserService.cs
  backend/dal/Services/UserService.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_S17_00/Test Data/CONTACTS_ORGANIZATION_TEST_DATA.sql
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/PAIMS 1.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_LOAD_PAIMS_TO_PIMS_DATASET_2.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PIMS.conmgr
  frontend/src/utils/utils.ts
Labels: etl

#749 Backport 2396 to dev
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Services/Interfaces/IUserService.cs
  backend/dal/Services/UserService.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/PAIMS 1.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_LOAD_PAIMS_TO_PIMS_DATASET_2.dtsx
  etl/PAIMS_PIMS/PAIMS_PIMS/PIMS.conmgr
  frontend/src/utils/utils.ts
Labels: etl

#755 Lease Region with code - psp-2605
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Mapping/Lease/RegionMap.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  backend/api/Areas/Leases/Models/Lease/RegionModel.cs
  backend/api/Mapping/Lookup/LookupMap.cs
  backend/dal/Services/LeaseService.cs
  frontend/.vscode/launch.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/API.ts
  frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  frontend/src/features/leases/add/AddLeaseYupSchema.ts
  frontend/src/features/leases/add/AdministrationSubForm.tsx
  frontend/src/features/leases/add/PropertyRows.tsx
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  frontend/src/features/leases/leaseUtils.ts
  frontend/src/interfaces/ILease.ts
  frontend/src/interfaces/IRegion.ts
  frontend/src/mocks/mockLookups.ts
Labels: enhancement

#763 PSP-2675: Mapping issue with 'other' types
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
Labels: bug

#764 PSP-2516 -- adjusted LEASE_STATUS_TYPE_CODE
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj
Labels: etl

#747 Psp 2505
  backend/api/Areas/Leases/Mapping/Lease/PaymentMap.cs
  backend/api/Areas/Leases/Mapping/Lease/TermMap.cs
  backend/api/Areas/Leases/Models/Lease/PaymentModel.cs
  backend/api/Areas/Leases/Models/Lease/TermModel.cs
  backend/api/Controllers/LookupController.cs
  backend/dal/Services/Interfaces/ILookupService.cs
  backend/dal/Services/LeaseService.cs
  backend/dal/Services/LookupService.cs
  backend/entities/LeasePayment.cs
  backend/entities/LeaseTerm.cs
  frontend/src/components/Table/helpers.ts
  frontend/src/components/common/TooltipIcon.tsx
  frontend/src/components/common/form/__snapshots__/FastCurrencyInput.test.tsx.snap
  frontend/src/constants/API.ts
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  frontend/src/features/leases/detail/LeaseContainer.tsx
  frontend/src/features/leases/detail/LeasePages/details/DetailTerms.test.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/PaymentsContainer.tsx
  frontend/src/features/leases/detail/LeasePages/payment/styles.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/PaymentsForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/PaymentsForm.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/__snapshots__/PaymentsForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/table/columns.tsx
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/styles.ts
  frontend/src/interfaces/ILease.ts
  frontend/src/interfaces/ILeasePayment.ts
  frontend/src/interfaces/ILeaseTerm.ts
  frontend/src/interfaces/index.ts
  frontend/src/store/rootReducer.ts
  frontend/src/store/slices/systemConstants/interfaces/ISystemConstant.ts
  frontend/src/store/slices/systemConstants/useSystemConstants.ts
Labels: enhancement

#746 IS-19 Redux
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Down/01_PSP_PIMS_S19_00_Alter Down.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Down/30_DML_PIMS_ADDRESS_USAGE_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Down/73_DML_PIMS_LEASE_STATUS_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Down/77_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Down/Schema Compare.zip
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Up/01_PSP_PIMS_S17_00_Alter_Up.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Up/30_DML_PIMS_ADDRESS_USAGE_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Up/62_DML_PIMS_PROPERTY_IMPROVEMENT_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Up/72_DML_PIMS_INSURANCE_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Up/73_DML_PIMS_LEASE_STATUS_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Up/Schema Compare.zip
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Build/02_PSP_PIMS_S19_00_Build.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Build/30_DML_PIMS_ADDRESS_USAGE_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Build/62_DML_PIMS_PROPERTY_IMPROVEMENT_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Build/72_DML_PIMS_INSURANCE_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Build/73_DML_PIMS_LEASE_STATUS_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Drop/01_PSP_PIMS_S19_00_Drop.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/03_DML_LEASE_TESTING.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/04_DML_LEASE_LOAD.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/05_DML_LEASE_PROPERTY.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/06_DML_PROPERTY_LEASE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/07_CONTACTS_ORGANIZATION_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/08_CONTACTS_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/09_INSURANCE_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/10_LEASE_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/11_SECURITY_DEPOSIT_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/12_SECURITY_DEPOSIT_RETURN_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/13_SURPLUS_DECLERATION_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Test Data/14_TENANT_TEST_DATA.sql
Labels: db-migration

#761 PSP-2515 -- updated lease status in LIS ETL
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_Load.dtsx
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_PIMS.dtproj
  etl/LISOS_PIMS/LISOS_PIMS/PIMS.conmgr
Labels: etl

#780 PSP-2721: Handle keycloak undefined middle name
  frontend/src/features/leases/leaseUtils.ts
Labels: bug

#787 merge master into test
  etl/PAIMS_PIMS/PAIMS_PIMS/IS15.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_LOAD_PAIMS_TO_PIMS_DATASET_2.dtsx
  frontend/src/AppRouter.tsx
Labels: devops

#781 PSP-673 Replace Jenkins with Github actions
  .github/workflows/ci-cd-pims-dev.yml
Labels: devops

#792 Correct squash merge from dev to test, backmerge test into dev.
  Makefile
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Models/Lease/TermModel.cs
  backend/dal/PIMSContext.cs
  backend/dal/PimsService.cs
  backend/entities/IdentityBaseAppEntity.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_S17_01/Alter Down/74_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S17_01/Alter Down/75_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S17_01/Alter Up/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S17_01/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  etl/PAIMS_PIMS/PAIMS_PIMS/IS15.conmgr
  frontend/src/AppRouter.tsx
  frontend/src/colors.scss
  frontend/src/features/contacts/contact/detail/Person.test.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/PropertyInformationSubForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap
  frontend/src/features/leases/detail/styles.ts
  frontend/src/features/leases/leaseUtils.ts
Labels: devops

#796 Fix version in TEST
  Makefile
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: devops, release-management

#797 Dev fix version and backmerge
  Makefile
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: devops

#800 Fix the version in master
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: devops

#801 db schema fix.
  backend/api/Pims.Api.csproj
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Up/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  frontend/package.json
Labels: db-migration

#804 Backmerge from test to dev
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Up/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S19_00/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
Labels: devops

#791 Psp 2618
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_Load.dtsx
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_PIMS.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_LOAD_PAIMS_TO_PIMS_DATASET_2.dtsx
Labels: etl

#771 PSP-2116, PSP-2382, PSP-2415
  testing/katalon/Object Repository/LeaseLicenses/editStatus/licenseStatusLabel.rs
  testing/katalon/Object Repository/LeaseLicenses/editStatus/statusSelect.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/commecialAddressInput.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/commecialSizeInput.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/commercialDescriptionTextarea.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/editImprovementsButton.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/h3_Administration.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/improvementsLink.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/improvementsTitleLabel.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/otherImprovementDescriptionTextarea.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/otherImprovementsAddressInput.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/otherImprovementsSizeInput.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/residentialAddressInput.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/residentialDescriptionTextarea.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/residentialSizeInput.rs
  testing/katalon/Object Repository/LeaseLicenses/leaseImprovements/saveButton.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/LFileLink.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/categorySelect.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/descriptionTextarea.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/div_Start DateExpiry Date (if known)Status _c86543.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/editButton.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/expiryDateInput.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/initiatorSelect.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/locationOfDocumentsTextarea.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/motiContactInput.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/notesTextarea.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/programTypeSelect.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/purposeSelect.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/saveButton.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/searchByLFileNoInput.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/searchLeaseButton.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/searchLeaseLink.rs
  testing/katalon/Object Repository/LeaseLicenses/updateLeaseDetails/typeSelect.rs
  testing/katalon/Scripts/LeaseLicense/createLease/Script1640559998071.groovy
  testing/katalon/Scripts/LeaseLicense/createLeaseImprovements/Script1642539848540.groovy
  testing/katalon/Scripts/LeaseLicense/editStatus/Script1642559178746.groovy
  testing/katalon/Scripts/LeaseLicense/updateLeaseDetails/Script1642479367087.groovy
  testing/katalon/Test Cases/LeaseLicense/createLease.tc
  testing/katalon/Test Cases/LeaseLicense/createLeaseImprovements.tc
  testing/katalon/Test Cases/LeaseLicense/editStatus.tc
  testing/katalon/Test Cases/LeaseLicense/updateLeaseDetails.tc
Labels: test-scripts

#807 psp-2665 read only view of payment actuals.
  backend/api/Areas/Leases/Mapping/Lease/PaymentMap.cs
  backend/dal/Repositories/LeaseService.cs
  backend/dal/Repositories/LeaseTermRepository.cs
  backend/entities/LeasePaymentMethodType.cs
  backend/entities/LeasePaymentStatusType.cs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/_variables.module.scss
  frontend/src/colors.scss
  frontend/src/components/Table/Table.scss
  frontend/src/components/Table/Table.tsx
  frontend/src/components/Table/types.ts
  frontend/src/components/common/form/NotesModal.test.tsx
  frontend/src/components/common/form/NotesModal.tsx
  frontend/src/components/common/form/__snapshots__/NotesModal.test.tsx.snap
  frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
  frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
  frontend/src/features/contacts/list/ContactSearchResults/__snapshots__/ContactSearchResults.test.tsx.snap
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/PropertyInformationSubForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/Deposits.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedTable/__snapshots__/DepositsReceivedTable.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedTable/__snapshots__/DepositsReturnedTable.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/PaymentsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/hooks/useTerms.tsx
  frontend/src/features/leases/detail/LeasePages/payment/styles.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/ActualsForm.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/PaymentsForm.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/__snapshots__/PaymentsForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/table/actualsColumns.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/columns.tsx
  frontend/src/features/leases/detail/LeasePages/surplus/__snapshots__/Surplus.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/columns.tsx
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/interfaces/ILeasePayment.ts
  frontend/src/interfaces/ILeaseTerm.ts
  frontend/src/store/slices/systemConstants/systemConstantsActionCreator.spec.tsx
Labels: enhancement
