Repository bcgov/PSP, pull requests merged in 2022-06, with the labels that each got.

#1484 PSP-3011 unit tests
  backend/api/Areas/Property/Controllers/PropertyController.cs
  backend/dal/Repositories/PropertyRepository.cs
  backend/entities/Property.cs
  backend/tests/core/DatabaseHelper.cs
  backend/tests/core/Entities/PropertyHelper.cs
  backend/tests/core/Entities/PropertyStatusTypeHelper.cs
  backend/tests/core/Entities/PropertyTenureTypeHelper.cs
  backend/tests/unit/api/Controllers/Property/PropertyControllerTest.cs
  backend/tests/unit/api/Routes/Property/PropertyControllerTest.cs
  backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  backend/tests/unit/dal/Repositories/PropertyServiceTest.cs
  backend/tests/unit/dal/Services/PropertyServiceTest.cs
  frontend/src/components/common/form/Multiselect.test.tsx
  frontend/src/components/common/form/__snapshots__/Multiselect.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/hooks/useGetProperty.ts
  frontend/src/features/mapSideBar/tabs/propertyDetails/hooks/useUpdateProperty.ts
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/LandMeasurementTable.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/LandMeasurementTable.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/VolumetricMeasurementTable.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/VolumetricMeasurementTable.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/__snapshots__/LandMeasurementTable.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/__snapshots__/VolumetricMeasurementTable.test.tsx.snap
  frontend/src/models/api/AuditFields.ts
Labels: unit-tests

#1494 Updated property update to have selects for region and districtg
  backend/api/Areas/Property/Mapping/Property/PropertyMap.cs
  backend/api/Areas/Property/Models/Property/PropertyModel.cs
  backend/api/Mapping/Lookup/LookupMap.cs
  frontend/src/constants/API.ts
  frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.helpers.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  frontend/src/interfaces/IPropertyApiModel.ts
Labels: enhancement

#1497 PSP-3522: Fixing the sort criteria for lease
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Repositories/LeaseRepository.cs
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
Labels: bug

#1502 Bugs/psp 3513
  frontend/src/features/mapSideBar/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
  frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
Labels: bug

#1513 PSP-3619 Fix capitalization, PSP-3616 Fix spinner
  frontend/src/components/common/TabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/selector/__snapshots__/MapSelectorContainer.test.tsx.snap
Labels: bug

#1480 Psp 3404 add region to manage users page, update styling
  backend/api/Controllers/AccessRequestController.cs
  backend/api/Mapping/AccessRequest/AccessRequestMap.cs
  backend/api/Mapping/AccessRequest/AccessRequestOrganizationMap.cs
  backend/api/Mapping/AccessRequest/RoleMap.cs
  backend/api/Mapping/AccessRequest/UserMap.cs
  backend/api/Models/AccessRequest/AccessRequestModel.cs
  backend/api/Models/AccessRequest/AccessRequestNotificationModel.cs
  backend/api/Models/AccessRequest/AccessRequestOrganizationModel.cs
  backend/api/Models/AccessRequest/RoleModel.cs
  backend/api/Models/AccessRequest/UserModel.cs
  backend/api/Models/Concepts/AccessRequest/AccessRequestMap.cs
  backend/api/Models/Concepts/AccessRequest/AccessRequestModel.cs
  backend/api/Models/Concepts/Role/RoleMap.cs
  backend/api/Models/Concepts/Role/RoleModel.cs
  backend/api/Models/Concepts/User/UserMap.cs
  backend/api/Models/Concepts/User/UserModel.cs
  backend/api/Models/Concepts/User/UserRoleMap.cs
  backend/api/Models/Concepts/User/UserRoleModel.cs
  backend/dal/Repositories/AccessRequest.cs
  backend/tests/core/Entities/AccessRequestHelper.cs
  backend/tests/unit/api/Controllers/AccessControllerTest.cs
  backend/tests/unit/api/Routes/AccessRequestControllerTest.cs
  frontend/src/components/common/Snackbar.tsx
  frontend/src/components/common/TooltipIcon.scss
  frontend/src/components/common/TooltipWrapper.tsx
  frontend/src/features/admin/access-request/AccessRequestContainer.tsx
  frontend/src/features/admin/access-request/AccessRequestForm.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.scss
  frontend/src/features/admin/access-request/AccessRequestPage.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.tsx
  frontend/src/features/admin/access-request/RolesToolTip.tsx
  frontend/src/features/admin/access-request/models.ts
  frontend/src/features/mapSideBar/tabs/SectionField.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaDuplicateTitleSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLandSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaOwnershipInformationForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTransferSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyResearch/__snapshots__/PropertyResearchTabView.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/research/detail/__snapshots__/ResearchSummaryView.test.tsx.snap
  frontend/src/features/properties/map/research/update/property/__snapshots__/UpdatePropertyForm.test.tsx.snap
  frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  frontend/src/features/properties/selector/__snapshots__/MapSelectorContainer.test.tsx.snap
  frontend/src/features/properties/selector/map/__snapshots__/PropertyMapSelectorSubForm.test.tsx.snap
  frontend/src/hooks/pims-api/useApiAccessRequests.test.ts
  frontend/src/hooks/pims-api/useApiAccessRequests.ts
  frontend/src/mocks/filterDataMock.ts
  frontend/src/models/api/AccessRequest.ts
  frontend/src/models/api/Role.ts
  frontend/src/models/api/User.ts
  frontend/src/store/slices/accessRequests/accessRequestsActionCreator.spec.tsx
  frontend/src/store/slices/accessRequests/useAccessRequests.ts
  frontend/src/utils/YupSchema.ts
Labels: enhancement

#1488 Add/Update Properties to Research File | psp-3132
  backend/api/Areas/Research/Controllers/ResearchFileController.cs
  backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  backend/dal/PimsRepository.cs
  backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  backend/dal/Repositories/Interfaces/IResearchFilePropertyRepository.cs
  backend/dal/Repositories/Interfaces/IResearchFileRepository.cs
  backend/dal/Repositories/PropertyRepository.cs
  backend/dal/Repositories/ResearchFilePropertyRepository.cs
  backend/dal/Repositories/ResearchFileRepository.cs
  backend/dal/Services/Interfaces/IResearchFileService.cs
  backend/dal/Services/ResearchFileService.cs
  frontend/package-lock.json
  frontend/src/components/common/UserNameTooltip.tsx
  frontend/src/components/common/__snapshots__/UserNameTooltip.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  frontend/src/features/mapSideBar/__snapshots__/MotiInventoryHeader.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/HeaderField.tsx
  frontend/src/features/properties/map/research/ResearchContainer.tsx
  frontend/src/features/properties/map/research/ViewSelector.tsx
  frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
  frontend/src/features/properties/map/research/add/ResearchProperties.test.tsx
  frontend/src/features/properties/map/research/add/ResearchProperties.tsx
  frontend/src/features/properties/map/research/add/models.ts
  frontend/src/features/properties/map/research/common/ResearchFooter.tsx
  frontend/src/features/properties/map/research/common/ResearchHeader.tsx
  frontend/src/features/properties/map/research/common/__snapshots__/ResearchHeader.test.tsx.snap
  frontend/src/features/properties/map/research/hooks/useUpdateResearchProperties.ts
  frontend/src/features/properties/map/research/update/properties/UpdateProperties.tsx
  frontend/src/features/properties/map/research/update/property/UpdatePropertyView.tsx
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryView.tsx
  frontend/src/features/properties/selector/components/MapClickMonitor.tsx
  frontend/src/hooks/pims-api/useApiResearchFile.ts
Labels: enhancement

#1536 Merge from Test
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
  frontend/package.json
  frontend/src/features/mapSideBar/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
  frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
Labels: devops, alignment

#1539 Added checks to prevent tab to show if property is not in the DB
  frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
Labels: enhancement

#1543 Set DEV version to IS29
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: alignment

#1547 Increment DEV version to IS30
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: devops, release-management

#1554 Scaffold for s30
  backend/dal/PIMSContext.cs
  backend/entities/ef/PimsProperty.cs
  backend/entities/ef/PimsPropertyHist.cs
Labels: db-scaffold

#1551 correct access request approval issue in TEST.
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Repositories/Interfaces/IUserService.cs
  backend/dal/Repositories/UserService.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_00/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Build/75_DML_PIMS_ROLE_CLAIM.sql
  frontend/src/features/admin/access-request/AccessRequestContainer.tsx
Labels: bug

#1519 PSP-3134 : LISDB Insurance data loaded into PIMS_Insurance
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj
Labels: etl

#1550 PSP-3248:ACQ - Navigation to Acquisition File from main menu
  frontend/src/components/layout/SideNavBar/AcquisitionTray.test.tsx
  frontend/src/components/layout/SideNavBar/AcquisitionTray.tsx
  frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  frontend/src/components/layout/SideNavBar/SideTray.tsx
  frontend/src/components/layout/SideNavBar/__snapshots__/AcquisitionTray.test.tsx.snap
  frontend/src/constants/claims.ts
Labels: enhancement

#1542 build the uat pipeline via an action
  .github/workflows/ci-cd-pims-master.yml
Labels: devops

#1563 backmerge master to test
  .github/workflows/ci-cd-pims-master.yml
Labels: devops

#1568 Updating alter up scripts to acquisition file in IS30
  database/mssql/scripts/dbscripts/PSP_PIMS_S30_00/Alter Up/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S30_00/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
Labels: enhancement

#1574 feature(PSP-3520): Changes to fix the label width
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/add/styles.ts
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
Labels: bug

#1581 feature(PSP-3659): Changes to fix the issue related to pagination
  backend/dal/Repositories/ContactRepository.cs
Labels: bug

#1572 Added logic to change sorting column when R-file sort is selected
  backend/api/Areas/Research/Controllers/SearchController.cs
  backend/dal/Helpers/Extensions/ResearchExtensions.cs
Labels: bug

#1583 PSP-3648 bug fix - When adding a pin based on Plan# search, 400 error is thrown
  frontend/src/features/properties/selector/MapSelectorContainer.test.tsx
  frontend/src/features/properties/selector/search/LayerFilter.test.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.test.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.tsx
  frontend/src/hooks/pims-api/useApiGeocoder.test.ts
  frontend/src/hooks/pims-api/useApiGeocoder.ts
  frontend/src/mocks/index.ts
  frontend/src/mocks/mockDistrictLayerResponse.ts
  frontend/src/mocks/mockGeocoderResponses.ts
  frontend/src/mocks/mockMotiRegionLayerResponse.ts
Labels: bug

#1567 remove duplicated role/claims scripts from IS29
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_00/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Down/01_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Down/51_DML_PIMS_ROLE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Down/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Up/11_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Up/51_DML_PIMS_ROLE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Build/75_DML_PIMS_ROLE_CLAIM.sql
Labels: bug, db-migration

#1579 ensure that pid search occurs simultaneously with pin search. psp-3639
  frontend/src/components/maps/leaflet/mapUtils.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.test.tsx
Labels: bug

#1573 Psp 3679, psp-3683 list view sorting
  backend/dal/Repositories/ContactRepository.cs
  backend/dal/Repositories/UserService.cs
  backend/tests/unit/mockdal/Repositories/ContactRepositoryTest.cs
  frontend/src/components/Table/ColumnSort.tsx
  frontend/src/components/Table/Table.tsx
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/ContactResultComponent.tsx
  frontend/src/features/admin/users/ManageUsersPage.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  frontend/src/features/properties/list/PropertyListView.tsx
  frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.tsx
  frontend/src/hooks/useSearch.ts
Labels: bug

#1571 ensure research file list view searches for active files by default.
  frontend/src/features/research/list/ResearchFilter/ResearchFilter.test.tsx
  frontend/src/features/research/list/ResearchFilter/ResearchFilter.tsx
  frontend/src/features/research/list/ResearchFilter/__snapshots__/ResearchFilter.test.tsx.snap
  frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
Labels: bug

#1582 Psp 3519 add yup schema max size validations to lease forms.
  frontend/src/constants/API.ts
  frontend/src/features/leases/add/AddLeaseYupSchema.ts
  frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositYupSchema.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositYupSchema.tsx
  frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsForm.tsx
  frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsYupSchema.ts
  frontend/src/features/leases/detail/LeasePages/insurance/edit/InsuranceYupSchema.ts
  frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentsYupSchema.tsx
  frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermsYupSchema.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantYupSchema.ts
  frontend/src/features/leases/leaseUtils.ts
  frontend/src/utils/formUtils.ts
Labels: enhancement

#1587 Fixed property update for research files
  backend/dal/Repositories/ResearchFilePropertyRepository.cs
  backend/dal/Repositories/ResearchFileRepository.cs
Labels: bug, test-branch

#1565 Property Detail - Enhancement
  backend/api/Areas/Property/Controllers/PropertyController.cs
  backend/api/Areas/Property/Mapping/Property/PropertyMap.cs
  backend/api/Areas/Property/Models/Property/PropertyModel.cs
  backend/api/Controllers/LookupController.cs
  backend/api/Models/Concepts/Property/PropertyMap.cs
  backend/api/Models/Concepts/Property/PropertyModel.cs
  backend/dal/Repositories/Interfaces/ILookupService.cs
  backend/dal/Repositories/LookupService.cs
  backend/dal/Repositories/PropertyRepository.cs
  backend/entities/PphStatusType.cs
  backend/entities/ef/PimsProperty.cs
  backend/entities/ef/PimsPropertyHist.cs
  frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  frontend/src/constants/API.ts
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
  frontend/src/interfaces/IPropertyApiModel.ts
  frontend/src/mocks/mockLookups.ts
  frontend/src/models/api/Property.ts
Labels: enhancement

#1595 Backmerge test to dev
  .github/workflows/ci-cd-pims-master.yml
  backend/api/Areas/Research/Controllers/SearchController.cs
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Helpers/Extensions/ResearchExtensions.cs
  backend/dal/Repositories/Interfaces/IUserService.cs
  backend/dal/Repositories/ResearchFilePropertyRepository.cs
  backend/dal/Repositories/ResearchFileRepository.cs
  backend/dal/Repositories/UserService.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_00/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Down/01_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Down/51_DML_PIMS_ROLE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Down/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Up/11_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Up/51_DML_PIMS_ROLE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S29_01/Build/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S30_00/Alter Down/01_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S30_00/Alter Down/51_DML_PIMS_ROLE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S30_00/Alter Down/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S30_00/Alter Up/11_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S30_00/Alter Up/51_DML_PIMS_ROLE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S30_00/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S30_00/Build/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S30_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
  frontend/src/features/admin/access-request/AccessRequestContainer.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.test.tsx
  frontend/src/features/properties/selector/MapSelectorContainer.test.tsx
  frontend/src/features/properties/selector/search/LayerFilter.test.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.test.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.tsx
  frontend/src/features/research/list/ResearchFilter/ResearchFilter.test.tsx
  frontend/src/features/research/list/ResearchFilter/ResearchFilter.tsx
  frontend/src/features/research/list/ResearchFilter/__snapshots__/ResearchFilter.test.tsx.snap
  frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.test.tsx
  frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  frontend/src/hooks/pims-api/useApiGeocoder.test.ts
  frontend/src/hooks/pims-api/useApiGeocoder.ts
  frontend/src/mocks/index.ts
  frontend/src/mocks/mockDistrictLayerResponse.ts
  frontend/src/mocks/mockGeocoderResponses.ts
  frontend/src/mocks/mockMotiRegionLayerResponse.ts
Labels: devops

#1580 Psp 3646 warn user when navigating away from property details.
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
Labels: bug

#1586 Fixed electoral district nor eturning from layer
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.helpers.tsx
  frontend/src/hooks/useQueryMapLayersByLocation.ts
Labels: bug

#1590 Fixed pid not showing
  frontend/src/features/admin/users/components/UsersFilterBar.tsx
  frontend/src/features/properties/map/research/ResearchContainer.tsx
Labels: bug

#1612 Psp 3656 unit tests for keycloak, access request, user management.
  backend/api/Areas/Admin/Controllers/AccessRequestController.cs
  backend/api/Areas/Admin/Controllers/ClaimController.cs
  backend/api/Areas/Admin/Controllers/RoleController.cs
  backend/api/Areas/Keycloak/Controllers/RoleController.cs
  backend/api/Areas/Keycloak/Controllers/UserController.cs
  backend/api/Areas/Keycloak/Mapping/User/UserMap.cs
  backend/api/Controllers/UserController.cs
  backend/dal.keycloak/IPimsKeycloakService.cs
  backend/dal.keycloak/Partials/PimsKeycloakRoleService.cs
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  backend/dal/IPimsRepository.cs
  backend/dal/PimsRepository.cs
  backend/dal/Repositories/AccessRequestRepository.cs
  backend/dal/Repositories/Interfaces/IAccessRequestRepository.cs
  backend/dal/Repositories/Interfaces/IUserOrganizationService.cs
  backend/dal/Repositories/Interfaces/IUserRepository.cs
  backend/dal/Repositories/UserOrganizationService.cs
  backend/dal/Repositories/UserRepository.cs
  backend/entities/Models/AccessRequestFilter.cs
  backend/tests/core/Entities/AccessRequestHelper.cs
  backend/tests/core/Entities/ClaimHelper.cs
  backend/tests/core/Entities/UserHelper.cs
  backend/tests/unit/api/Controllers/Admin/AccessRequestControllerTest.cs
  backend/tests/unit/api/Controllers/Admin/ClaimControllerTest.cs
  backend/tests/unit/api/Controllers/Admin/RoleControllerTest.cs
  backend/tests/unit/api/Controllers/Admin/UserControllerTest.cs
  backend/tests/unit/api/Controllers/Keycloak/RoleControllerTest.cs
  backend/tests/unit/api/Controllers/Keycloak/UserControllerTest.cs
  backend/tests/unit/api/Controllers/UserControllerTest.cs
  backend/tests/unit/api/Routes/Admin/RoleControllerTest.cs
  backend/tests/unit/api/Routes/Keycloak/RoleControllerTest.cs
  backend/tests/unit/api/Routes/Keycloak/UserControllerTest.cs
  backend/tests/unit/api/Routes/UserControllerTest.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  backend/tests/unit/dal/Repositories/AccessRequestRepositoryTest.cs
  backend/tests/unit/dal/Repositories/LeaseReportsServiceTest.cs
  backend/tests/unit/dal/Repositories/PaymentServiceTest.cs
  backend/tests/unit/dal/Repositories/UserOrganizationServiceTest.cs
  backend/tests/unit/dal/Repositories/UserRepositoryTest.cs
  backend/tests/unit/dal/Repositories/UserServiceTest.cs
  backend/tests/unit/dal/Services/LeaseTermServiceTest.cs
  backend/tests/unit/dal/Services/PropertyServiceTest.cs
  backend/tests/unit/dal/Services/ResearchServiceTest.cs
  frontend/src/features/admin/access-request/AccessRequestContainer.tsx
Labels: unit-tests

#1614 Psp-3759 access request corrections
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Repositories/Interfaces/IUserService.cs
  backend/dal/Repositories/UserService.cs
  frontend/src/features/admin/access-request/AccessRequestContainer.tsx
  frontend/src/features/admin/edit-user/EditUserContainer.tsx
  frontend/src/features/admin/edit-user/EditUserForm.tsx
  frontend/src/features/admin/users/components/UsersFilterBar.tsx
Labels: bug

#1606 feature(PSP-3423): Help text to provide guidance - name a research file
  frontend/src/features/properties/map/research/add/AddResearchContainer.test.tsx
  frontend/src/features/properties/map/research/add/AddResearchForm.tsx
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/common/ResearchFileNameGuide.test.tsx
  frontend/src/features/properties/map/research/common/ResearchFileNameGuide.tsx
  frontend/src/features/properties/map/research/common/__snapshots__/ResearchFileNameGuide.test.tsx.snap
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.test.tsx
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.tsx
  frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
Labels: enhancement

#1618 Backmerge test to dev
  backend/api/Models/Concepts/Property/PropertyModel.cs
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Repositories/Interfaces/IUserRepository.cs
  backend/dal/Repositories/UserRepository.cs
  frontend/src/components/common/form/Multiselect.tsx
  frontend/src/components/common/form/__snapshots__/Multiselect.test.tsx.snap
  frontend/src/features/admin/edit-user/EditUserContainer.tsx
  frontend/src/features/admin/edit-user/EditUserForm.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/validation.ts
Labels: devops

#1629 PSP-3662: Enforce character limits on FE - Properties
  frontend/src/features/properties/map/research/add/AddResearchFileYupSchema.ts
  frontend/src/features/properties/map/research/update/UpdateResearchFileYupSchema.ts
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryView.tsx
Labels: frontend

#1613 Psp 2958 replace pids in lease header with expandable collapsed list of addresses
  frontend/src/components/common/ExpandableTextList.test.tsx
  frontend/src/components/common/ExpandableTextList.tsx
  frontend/src/components/common/OverflowTip.tsx
  frontend/src/components/common/buttons/LinkButton.tsx
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeaseHeader.tsx
  frontend/src/features/leases/detail/LeaseHeaderAddresses.test.tsx
  frontend/src/features/leases/detail/LeaseHeaderAddresses.tsx
  frontend/src/features/leases/detail/LeaseLayout.tsx
  frontend/src/features/leases/detail/LeaseStatusSummary.tsx
  frontend/src/features/leases/detail/StackedTenantFields.test.tsx
  frontend/src/features/leases/detail/StackedTenantFields.tsx
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseStatusSummary.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/StackedTenantFields.test.tsx.snap
  frontend/src/features/leases/detail/styles.ts
  frontend/src/features/leases/index.ts
  frontend/src/mocks/filterDataMock.ts
  frontend/src/mocks/mockProperties.ts
Labels: enhancement

#1645 version bumps requested by dependabot.
  backend/api/Pims.Api.csproj
  frontend/package-lock.json
  frontend/package.json
Labels: tech-debt

#1646 Increment DEV version to IS31
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: devops, release-management

#1659 Scaffold for s31
  backend/dal/PIMSContext.cs
  backend/entities/ef/PimsDocument.cs
  backend/entities/ef/PimsDocumentHist.cs
  backend/entities/ef/PimsDocumentStatusType.cs
  backend/entities/ef/PimsDocumentTyp.cs
  backend/entities/ef/PimsDocumentTypHist.cs
  backend/entities/ef/PimsNote.cs
  backend/entities/ef/PimsNoteHist.cs
  backend/entities/ef/PimsProperty.cs
  backend/entities/ef/PimsPropertyHist.cs
Labels: db-scaffold

#1666 cherry pick system admin fix into master branch
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/src/features/admin/edit-user/EditUserForm.tsx
Labels: bug

#1670 Re-run scaffold and clean old files
  backend/entities/Partials/ProjectRiskType.cs
  backend/entities/Partials/ProjectStatusType.cs
  backend/entities/Partials/ProjectTierType.cs
  backend/entities/Partials/ProjectType.cs
  backend/entities/Partials/Workflow.cs
  backend/entities/Partials/WorkflowType.cs
  backend/entities/PimsBaseContext.cs
  backend/entities/ef/PimsActivity.cs
  backend/entities/ef/PimsActivityInstance.cs
  backend/entities/ef/PimsActivityInstanceDocument.cs
  backend/entities/ef/PimsActivityInstanceDocumentHist.cs
  backend/entities/ef/PimsActivityInstanceHist.cs
  backend/entities/ef/PimsActivityInstanceNote.cs
  backend/entities/ef/PimsActivityInstanceNoteHist.cs
  backend/entities/ef/PimsActivityModel.cs
  backend/entities/ef/PimsActivityModelHist.cs
  backend/entities/ef/PimsDocument.cs
  backend/entities/ef/PimsNote.cs
  backend/entities/ef/PimsProject.cs
  backend/entities/ef/PimsProjectNote.cs
  backend/entities/ef/PimsProjectProperty.cs
  backend/entities/ef/PimsProjectPropertyHist.cs
  backend/entities/ef/PimsProjectRiskType.cs
  backend/entities/ef/PimsProjectStatusType.cs
  backend/entities/ef/PimsProjectTierType.cs
  backend/entities/ef/PimsProjectType.cs
  backend/entities/ef/PimsProjectWorkflowModel.cs
  backend/entities/ef/PimsProjectWorkflowModelHist.cs
  backend/entities/ef/PimsProperty.cs
  backend/entities/ef/PimsPropertyActivity.cs
  backend/entities/ef/PimsPropertyActivityHist.cs
  backend/entities/ef/PimsTask.cs
  backend/entities/ef/PimsTaskHist.cs
  backend/entities/ef/PimsTaskTemplateActivityModelHist.cs
  backend/entities/ef/PimsTaskTemplateHist.cs
  backend/entities/ef/PimsTaskTemplateType.cs
  backend/entities/ef/PimsUser.cs
  backend/entities/ef/PimsWorkflowModel.cs
  backend/entities/ef/PimsWorkflowModelType.cs
Labels: db-scaffold
