Repository bcgov/PSP, pull requests merged in 2022-03, with the labels that each got.

#1036 Csp
  openshift/4.0/templates/app/deploy.yaml
  openshift/s2i/nginx-runtime/nginx.conf.template
  openshift/s2i/nginx-runtime/s2i/bin/run
Labels: bug

#1039 PSP-2626 Fix release github action
  .github/workflows/release.yml
Labels: bug, devops

#1029 Do not duplicate person contacts if a single person has multiple orga…
  database/mssql/scripts/dbscripts/PSP_PIMS_S21_00/Alter Down/01_PIMS_CONTACT_MGR_VIEW.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S21_00/Alter Up/01_PIMS_CONTACT_MGR_VIEW.sql
Labels: bug

#1043 Weak Signature in JWT
  backend/api/Startup.cs
Labels: tech-debt

#1041 Added a multi select to the lease search
  backend/api/Areas/Leases/Models/Search/LeaseFilterModel.cs
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/entities/Models/LeaseFilter.cs
  frontend/src/features/leases/interfaces.ts
  frontend/src/features/leases/list/LeaseFilter/LeaseFilter.test.tsx
  frontend/src/features/leases/list/LeaseFilter/LeaseFilter.tsx
  frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  frontend/src/features/leases/list/LeaseListView.test.tsx
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
Labels: bug

#1047 Update view person to support PERSPHONE.
  frontend/src/features/contacts/contact/detail/Person.test.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
Labels: enhancement

#1048 psp-2821 terms must not have the same start date as the end date of a…
  backend/dal/Services/LeaseTermService.cs
  backend/tests/unit/dal/Services/LeaseTermServiceTest.cs
Labels: bug

#1052 psp-2821 terms must not have the same start date as the end date of a…
  backend/dal/Services/LeaseTermService.cs
  backend/tests/unit/dal/Services/LeaseTermServiceTest.cs
Labels: bug

#1053 Test to dev backmerge
  frontend/src/features/contacts/contact/detail/Person.test.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
Labels: devops

#1049 PSP-2532 Update backend to .NET 6
  .github/workflows/api-dotnetcore.yml
  backend/.s2i/environment
  backend/Directory.Build.props
  backend/Dockerfile.3.1
  backend/Dockerfile.migrations
  backend/Dockerfile.ocp
  backend/dal.keycloak/Pims.Dal.Keycloak.csproj
  backend/tests/Directory.Build.props
  openshift/4.0/templates/api/README.md
  openshift/4.0/templates/api/build.yaml
  openshift/4.0/templates/base-images/dotnet60/README.md
  openshift/4.0/templates/base-images/dotnet60/dotnet-60.yaml
Labels: tech-debt, devops

#1064 Fix dotnet-sonar
  .github/workflows/api-dotnetcore.yml
Labels: bug, devops

#1067 Increment DEV to IS23
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#1072 update property test data, add geo information.
  database/mssql/scripts/dbscripts/PSP_PIMS_S21_00/Test Data/05_DML_LEASE_PROPERTY.sql
Labels: test-data

#1078 Common styles - PSP-3016
  frontend/src/features/mapSideBar/tabs/InventoryTabs.tsx
  frontend/src/features/mapSideBar/tabs/SectionField.tsx
  frontend/src/features/mapSideBar/tabs/SectionStyles.tsx
Labels: enhancement

#1088 Psp 3051
  backend/api/Pims.Api.csproj
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  frontend/package.json
Labels: bug

#1093 Switched the order of modal buttons [cancel] [ok]
  frontend/src/components/common/GenericModal.tsx
Labels: bug

#1085 Psp 2377
  backend/ltsa/Models/TitleIdentifier.cs
  backend/tests/unit/dal/Libraries/Ltsa/TitleIdentifierTest.cs
  frontend/src/assets/scss/App.scss
  frontend/src/components/common/TabView.tsx
  frontend/src/components/common/form/Form.scss
  frontend/src/components/common/form/TextArea.tsx
  frontend/src/components/maps/leaflet/LoadingBackdrop/LoadingBackdrop.tsx
  frontend/src/features/mapSideBar/MapSideBarContainer.test.tsx
  frontend/src/features/mapSideBar/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.ts
  frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  frontend/src/features/mapSideBar/tabs/InventoryTabs.tsx
  frontend/src/features/mapSideBar/tabs/SectionFieldWrapper.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeOwnerSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeOwnerSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaDuplicateTitleSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaDuplicateTitleSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaLandSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaLandSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaLegalNotationsSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaLegalNotationsSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTransferSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTransferSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeOwnerSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaDuplicateTitleSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLandSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLegalNotationsSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTransferSubForm.test.tsx.snap
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/hooks/pims-api/useApiLtsa.tsx
  frontend/src/hooks/useLtsa.ts
  frontend/src/interfaces/ltsaModels.ts
Labels: enhancement

#1090 Psp 3042
  backend/api/Areas/Leases/Controllers/SecurityDepositController.cs
  backend/api/Areas/Leases/Models/Lease/DepositNoteModel.cs
  backend/api/Models/ParentConcurrencyGuardModel.cs
  backend/api/Pims.Api.csproj
  backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  backend/dal/Repositories/LeaseRepository.cs
  backend/dal/Services/Interfaces/ISecurityDepositService.cs
  backend/dal/Services/SecurityDepositService.cs
  backend/entities/Lease.cs
  backend/tests/unit/api/Controllers/Leases/LeaseControllerTest.cs
  backend/tests/unit/dal/Services/LeaseTermServiceTest.cs
  frontend/package.json
  frontend/src/features/leases/SaveCancelButtons.tsx
  frontend/src/features/leases/add/AddLeaseForm.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/__snapshots__/DepositNotes.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/hooks/useDeposits.tsx
  frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsForm.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  frontend/src/hooks/pims-api/useApiLeaseDeposits.ts
Labels: bug, enhancement

#1103 Correct IS21 test data
  database/mssql/scripts/dbscripts/PSP_PIMS_S23_00/Test Data/05_DML_LEASE_PROPERTY.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S23_00/Test Data/12_SECURITY_DEPOSIT_RETURN_TEST_DATA.sql
Labels: db-migration

#1106 add bc assessment schema via scaffold of IS23.
  backend/dal/PIMSContext.cs
  backend/entities/ef/BcaAreaAmendment.cs
  backend/entities/ef/BcaAreaBctransitValue.cs
  backend/entities/ef/BcaAreaDelete.cs
  backend/entities/ef/BcaAreaGeneralValue.cs
  backend/entities/ef/BcaAreaSchoolValue.cs
  backend/entities/ef/BcaAssessmentArea.cs
  backend/entities/ef/BcaDataAdvice.cs
  backend/entities/ef/BcaDataAdviceAmendment.cs
  backend/entities/ef/BcaDataAdviceBctransitValue.cs
  backend/entities/ef/BcaDataAdviceDelete.cs
  backend/entities/ef/BcaDataAdviceGeneralValue.cs
  backend/entities/ef/BcaDataAdviceSchoolValue.cs
  backend/entities/ef/BcaDefined.cs
  backend/entities/ef/BcaElectoralArea.cs
  backend/entities/ef/BcaFolioAddress.cs
  backend/entities/ef/BcaFolioAmendment.cs
  backend/entities/ef/BcaFolioBctransitValue.cs
  backend/entities/ef/BcaFolioDescription.cs
  backend/entities/ef/BcaFolioFarm.cs
  backend/entities/ef/BcaFolioGeneralValue.cs
  backend/entities/ef/BcaFolioLandCharacteristic.cs
  backend/entities/ef/BcaFolioLegalDescription.cs
  backend/entities/ef/BcaFolioManagedForest.cs
  backend/entities/ef/BcaFolioManufacturedHome.cs
  backend/entities/ef/BcaFolioOilAndGa.cs
  backend/entities/ef/BcaFolioRecord.cs
  backend/entities/ef/BcaFolioSale.cs
  backend/entities/ef/BcaFolioSchoolValue.cs
  backend/entities/ef/BcaFolioValuation.cs
  backend/entities/ef/BcaGeneralService.cs
  backend/entities/ef/BcaImprovementDistrict.cs
  backend/entities/ef/BcaIslandsTrust.cs
  backend/entities/ef/BcaJurisdiction.cs
  backend/entities/ef/BcaJurisdictionAmendment.cs
  backend/entities/ef/BcaJurisdictionBctransitValue.cs
  backend/entities/ef/BcaJurisdictionDelete.cs
  backend/entities/ef/BcaJurisdictionGeneralValue.cs
  backend/entities/ef/BcaJurisdictionSchoolValue.cs
  backend/entities/ef/BcaLocalArea.cs
  backend/entities/ef/BcaMinorTaxing.cs
  backend/entities/ef/BcaOwner.cs
  backend/entities/ef/BcaOwnershipGroup.cs
  backend/entities/ef/BcaServiceArea.cs
  backend/entities/ef/BcaSpecifiedMunicipal.cs
  backend/entities/ef/BcaSpecifiedRegional.cs
Labels: db-migration

#1109 psp-3064 lease and license list view/export hotfix.
  backend/api/Areas/Leases/Mapping/Search/LeaseMap.cs
  backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/src/features/leases/list/LeaseListView.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/hooks/useSearch.ts
Labels: bug

#1110 Psp 3042
  backend/api/Pims.Api.csproj
  backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  backend/dal/Repositories/LeaseRepository.cs
  backend/dal/Services/SecurityDepositService.cs
  backend/tests/unit/api/Controllers/Leases/LeaseControllerTest.cs
  backend/tests/unit/dal/Services/LeaseTermServiceTest.cs
  frontend/package.json
Labels: bug

#1111 psp-3042 correct issue with lease max page size.
  backend/api/Pims.Api.csproj
  backend/dal/Repositories/LeaseRepository.cs
  frontend/package.json
Labels: bug

#1112 Master to test
  backend/api/Areas/Leases/Controllers/SecurityDepositController.cs
  backend/api/Areas/Leases/Mapping/Search/LeaseMap.cs
  backend/api/Areas/Leases/Models/Lease/DepositNoteModel.cs
  backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  backend/api/Models/ParentConcurrencyGuardModel.cs
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Repositories/LeaseRepository.cs
  backend/dal/Services/Interfaces/ISecurityDepositService.cs
  backend/dal/Services/SecurityDepositService.cs
  backend/entities/Lease.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  frontend/src/features/leases/SaveCancelButtons.tsx
  frontend/src/features/leases/add/AddLeaseForm.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/__snapshots__/DepositNotes.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/hooks/useDeposits.tsx
  frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsForm.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  frontend/src/features/leases/list/LeaseListView.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/hooks/pims-api/useApiLeaseDeposits.ts
  frontend/src/hooks/useSearch.ts
Labels: devops

#1114 TEST to DEV backmerge
  backend/api/Areas/Leases/Controllers/SecurityDepositController.cs
  backend/api/Areas/Leases/Mapping/Search/LeaseMap.cs
  backend/api/Areas/Leases/Models/Lease/DepositNoteModel.cs
  backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  backend/api/Models/ParentConcurrencyGuardModel.cs
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Repositories/LeaseRepository.cs
  backend/dal/Services/Interfaces/ISecurityDepositService.cs
  backend/dal/Services/SecurityDepositService.cs
  backend/entities/Lease.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  frontend/src/components/common/GenericModal.tsx
  frontend/src/features/leases/SaveCancelButtons.tsx
  frontend/src/features/leases/add/AddLeaseForm.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/__snapshots__/DepositNotes.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/hooks/useDeposits.tsx
  frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsForm.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  frontend/src/features/leases/list/LeaseListView.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/hooks/pims-api/useApiLeaseDeposits.ts
  frontend/src/hooks/useSearch.ts
Labels: release-management

#1120 Increment DEV version to IS24
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#1089 Terms, Payments, Aggregated Lease Scripts
  testing/katalon/Object Repository/LeaseLicenses/payments/AddTermButton.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/CalendarValue.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/ConfirmDeletePayment.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/DeleteActual.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/DeleteTerm.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/EditTerm.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/EndDate.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/EndDateTermModal.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/ExercisedOption.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/Expander.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/NotExercisedOption.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/PaymentAmount.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/PaymentFrequency.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/PaymentFrequencyValue.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/PaymentLease.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/PaymentSave.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/PaymentsDue.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/PaymentsHyperlink.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/ReceivedDate.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/RecordAPaymentButton.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/SaveTermButton.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/StartDate.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/StartDateTermModal.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/TermDeletedModal.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/TermModalCancelButton.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/TermStatus.rs
  testing/katalon/Object Repository/LeaseLicenses/payments/TotalReceived.rs
  testing/katalon/Profiles/default.glbl
  testing/katalon/Scripts/LeaseLicense/AggregatedLease/Script1646957325212.groovy
  testing/katalon/Scripts/LeaseLicense/payments/Script1646419732871.groovy
  testing/katalon/Test Cases/LeaseLicense/AggregatedLease.tc
  testing/katalon/Test Cases/LeaseLicense/payments.tc
  testing/katalon/settings/internal/com.kms.katalon.composer.testcase.properties
  testing/katalon/settings/internal/com.kms.katalon.integration.testcloud.properties
Labels: test-scripts

#1132 Fixed label on return deposits payee
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
Labels: bug

#1123 fix lis db etl to stop crashing due to invalid lease status type.
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj
Labels: etl

#1145 Corrected Primary Key Constraint Names
  database/mssql/scripts/dbscripts/PSP_PIMS_S23_01/Alter Down/01_PSP_PIMS_S23_01_Alter Down.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S23_01/Alter Up/01_PSP_PIMS_S23_00_Alter_Up.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S23_01/Build/02_PSP_PIMS_S23_01_Build.sql
Labels: bug

#1131 Added research side tray
  frontend/package-lock.json
  frontend/src/components/layout/SideNavBar/ResearchTray.tsx
  frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  frontend/src/components/layout/SideNavBar/SideTray.tsx
  frontend/src/components/layout/index.ts
Labels: enhancement

#1143 PSP-2376 Property Information slideout
  backend/.vscode/launch.json
  backend/api/Areas/Property/Mapping/Property/AddressMap.cs
  backend/api/Areas/Property/Mapping/Property/PropertyMap.cs
  backend/api/Areas/Property/Models/Property/AddressModel.cs
  backend/api/Areas/Property/Models/Property/PropertyModel.cs
  backend/dal/Repositories/PropertyService.cs
  backend/entities/AreaUnitType.cs
  backend/entities/PropertyAdjacentLandType.cs
  backend/entities/PropertyAnomalyType.cs
  backend/entities/PropertyRoadType.cs
  backend/entities/VolumetricType.cs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/scss/_variables.module.scss
  frontend/src/assets/scss/colors.scss
  frontend/src/components/common/form/Text.tsx
  frontend/src/components/common/form/TextArea.tsx
  frontend/src/components/common/form/index.ts
  frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
  frontend/src/constants/areaUnitTypes.ts
  frontend/src/constants/volumeUnitTypes.ts
  frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/mapSideBar/MapSideBarContainer.test.tsx
  frontend/src/features/mapSideBar/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/tabs/InventoryTabs.tsx
  frontend/src/features/mapSideBar/tabs/Section.tsx
  frontend/src/features/mapSideBar/tabs/SectionField.tsx
  frontend/src/features/mapSideBar/tabs/SectionStyles.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.helpers.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/components/LandMeasurementTable.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/components/VolumetricMeasurementTable.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/usePropertyDetails.ts
  frontend/src/hooks/pims-api/useApiProperties.ts
  frontend/src/hooks/pims-api/useGeoServer.ts
  frontend/src/hooks/useProperties.ts
  frontend/src/models/api/Property.ts
  frontend/src/utils/convertUtils.ts
  frontend/src/utils/formUtils.ts
  frontend/src/utils/propertyUtils.ts
Labels: enhancement

#1154 PSP-2872 map popup redesign
  frontend/package-lock.json
  frontend/src/assets/scss/_variables.module.scss
  frontend/src/assets/scss/buttons.scss
  frontend/src/assets/scss/colors.scss
  frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopUpContent.test.tsx
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopup.tsx
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContent.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupContent.test.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupContent.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.test.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/__snapshots__/LayerPopupContent.test.tsx.snap
  frontend/src/components/maps/leaflet/LayerPopup/components/__snapshots__/LayerPopupLinks.test.tsx.snap
  frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
  frontend/src/components/maps/leaflet/LayerPopup/index.ts
  frontend/src/components/maps/leaflet/LayerPopup/styles.ts
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/leaflet/__snapshots__/Map.test.tsx.snap
  frontend/src/components/maps/leaflet/styles.ts
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: enhancement

#1162 Master to test
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj
Labels: devops

#1157 PSP-2184 Integrate StyleCop for .NET projects
  backend/Directory.Build.props
Labels: enhancement, tech-debt
