Repository bcgov/PSP, pull requests merged in 2022-07, with the labels that each got.

#1686 Bug Fixes - PSP-3869, PSP-3895
  frontend/src/features/properties/map/research/add/AddResearchFileYupSchema.ts
  frontend/src/features/properties/map/research/add/AddResearchForm.test.tsx
  frontend/src/features/properties/map/research/add/AddResearchForm.tsx
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  frontend/src/features/properties/map/research/update/UpdateResearchFileYupSchema.ts
  frontend/src/features/properties/map/research/update/properties/UpdateProperties.tsx
  frontend/src/features/properties/map/research/update/properties/UpdatePropertiesYupSchema.ts
  frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.tsx
  frontend/src/features/properties/map/research/update/property/UpdatePropertyView.tsx
  frontend/src/features/properties/map/research/update/property/UpdatePropertyYupSchema.ts
  frontend/src/features/properties/map/research/update/property/__snapshots__/UpdatePropertyForm.test.tsx.snap
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.test.tsx
  frontend/src/utils/test-utils.tsx
Labels: bug

#1692 Bug Fixes - PSP-3863, PSP-3865, PSP-3866, PSP-3868
  frontend/src/features/admin/edit-user/EditUserForm.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.test.tsx
  frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  frontend/src/features/leases/add/AddLeaseYupSchema.ts
  frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositYupSchema.tsx
  frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsYupSchema.ts
  frontend/src/features/leases/detail/LeasePages/insurance/edit/EditContainer.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/edit/InsuranceForm.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/edit/InsuranceYupSchema.ts
  frontend/src/utils/YupSchema.ts
Labels: bug

#1691 PSP-3840:Property Details - When a property has Provincial Public Hwy…
  backend/dal/Repositories/PropertyRepository.cs
Labels: bug

#1673 Updated Description for PIMS_PPH_STATUS_TYPE
  database/mssql/scripts/dbscripts/PSP_PIMS_S31_01/Alter Down/79_DML_PIMS_PROPERTY_ROAD_TYPE_Edit.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S31_01/Alter Down/87_DML_PIMS_PPH_STATUS_TYPE_Edit.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S31_01/Alter Up/79_DML_PIMS_PROPERTY_ROAD_TYPE_Edit.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S31_01/Alter Up/87_DML_PIMS_PPH_STATUS_TYPE_Edit.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S31_01/Build/79_DML_PIMS_PROPERTY_ROAD_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S31_01/Build/87_DML_PIMS_PPH_STATUS_TYPE.sql
Labels: db-migration

#1690 PSP-3841: Property Information Details - PPH status option by default…
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
Labels: bug

#1688 psp-3854 show text as well as pid when address not available.
  frontend/src/features/leases/detail/LeaseHeaderAddresses.test.tsx
  frontend/src/features/leases/detail/LeaseHeaderAddresses.tsx
Labels: bug

#1687 Psp 3890
  frontend/src/components/common/GenericModal.tsx
  frontend/src/components/maps/hooks/useMapSearch.tsx
  frontend/src/components/maps/leaflet/InventoryLayer.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/providers/PropertyContext.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/features/properties/map/hooks/useMapProperties.tsx
  frontend/src/features/properties/map/research/ResearchContainer.tsx
  frontend/src/features/properties/map/research/add/models.ts
  frontend/src/features/properties/selector/MapSelectorContainer.test.tsx
  frontend/src/features/properties/selector/MapSelectorContainer.tsx
  frontend/src/hooks/useApi.test.tsx
  frontend/src/hooks/useApi.ts
Labels: bug

#1677 psp-3777 and psp-3784
  frontend/src/AppRouter.tsx
  frontend/src/features/properties/map/research/detail/ResearchSummaryView.test.tsx
  frontend/src/features/properties/map/research/detail/ResearchSummaryView.tsx
  frontend/src/features/properties/map/research/detail/__snapshots__/ResearchSummaryView.test.tsx.snap
Labels: bug

#1681 Psp 3842
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/dal/Repositories/UserRepository.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  backend/tests/unit/dal/Repositories/UserRepositoryTest.cs
  frontend/src/features/admin/edit-user/EditUserPage.test.tsx
  frontend/src/mocks/userMock.ts
  frontend/src/utils/YupSchema.ts
Labels: bug

#1674 Psp 3819 - add tooltips to deposit/terms screens when delete icon is hidden.
  frontend/src/components/common/TooltipIcon.tsx
  frontend/src/components/common/__snapshots__/UserNameTooltip.test.tsx.snap
  frontend/src/components/common/form/__snapshots__/FastCurrencyInput.test.tsx.snap
  frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/DepositsReceivedContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/__snapshots__/DepositsReceivedContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/modal/payment/__snapshots__/PaymentForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/modal/term/__snapshots__/TermForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/__snapshots__/TermsForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
  frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/research/common/__snapshots__/ResearchHeader.test.tsx.snap
  frontend/src/features/properties/selector/__snapshots__/MapSelectorContainer.test.tsx.snap
Labels: enhancement

#1693 Mayan and database syncronization | psp-3803 & psp-3621
  backend/api/Controllers/DocumentController.cs
  backend/api/Helpers/Extensions/ExceptionExtensions.cs
  backend/api/Helpers/Middleware/LogResponseMiddleware.cs
  backend/api/Models/ExternalResult.cs
  backend/api/Models/Mayan/Document/DocumentTypeMetadataType.cs
  backend/api/Models/Mayan/Metadata/MetadataType.cs
  backend/api/Models/Mayan/PimsSync/DocumentMetadataTypeModel.cs
  backend/api/Models/Mayan/PimsSync/DocumentTypeModel.cs
  backend/api/Models/Mayan/PimsSync/ExternalBatchResult.cs
  backend/api/Models/Mayan/PimsSync/SyncModel.cs
  backend/api/Repositories/IDocumentRepository.cs
  backend/api/Repositories/Mayan/IEdmsAuthRepository.cs
  backend/api/Repositories/Mayan/IEdmsDocumentRepository.cs
  backend/api/Repositories/Mayan/IEdmsMetadataRepository.cs
  backend/api/Repositories/Mayan/MayanAuthRepository.cs
  backend/api/Repositories/Mayan/MayanBaseRepository.cs
  backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  backend/api/Repositories/Mayan/MayanMetadataRepository.cs
  backend/api/Repositories/MayanDocumentRepository.cs
  backend/api/Services/DocumentService.cs
  backend/api/Services/DocumentSyncService.cs
  backend/api/Services/IDocumentSyncService.cs
  backend/api/Startup.cs
  backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  backend/dal/Repositories/DocumentTypeRepository.cs
  backend/dal/Repositories/Interfaces/IDocumentTypeRepository.cs
  frontend/package-lock.json
Labels: enhancement

#1696 Bug fix | Name of property on research file cannot be zero
  frontend/src/features/properties/map/research/ResearchContainer.tsx
Labels: bug

#1702 PSP-3693 Add Notes
  backend/api/Areas/Notes/Controllers/NoteController.cs
  backend/api/Constants/NoteType.cs
  backend/api/Models/Concepts/Note/ActivityNoteMap.cs
  backend/api/Models/Concepts/Note/EntityNoteModel.cs
  backend/api/Models/Concepts/Note/NoteMap.cs
  backend/api/Models/Concepts/Note/NoteModel.cs
  backend/api/Models/Concepts/Note/NoteParentModel.cs
  backend/api/Services/BaseService.cs
  backend/api/Services/INoteService.cs
  backend/api/Services/NoteService.cs
  backend/api/Startup.cs
  backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  backend/dal/IPimsRepository.cs
  backend/dal/PimsRepository.cs
  backend/dal/Repositories/EntityNoteRepository.cs
  backend/dal/Repositories/Interfaces/IEntityNoteRepository.cs
  backend/dal/Repositories/Interfaces/INoteRepository.cs
  backend/dal/Repositories/NoteRepository.cs
  backend/dal/Security/Permissions.cs
  backend/entities/Partials/ActivityInstanceNote.cs
  backend/entities/Partials/Note.cs
  frontend/src/AppRouter.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/noteTypes.ts
  frontend/src/features/notes/add/AddNotesContainer.tsx
  frontend/src/features/notes/add/AddNotesForm.tsx
  frontend/src/features/notes/add/models.ts
  frontend/src/features/notes/hooks/useAddNote.ts
  frontend/src/hooks/pims-api/useApiNotes.ts
  frontend/src/models/api/Activity.ts
  frontend/src/models/api/Note.ts
  frontend/src/pages/TestNotes.tsx
  frontend/src/utils/axiosUtils.ts
  frontend/src/utils/index.ts
Labels: enhancement

#1689 feature(PSP-3694): Changes to create reusable Note component
  backend/api/Areas/Notes/Controllers/NoteController.cs
  backend/api/Areas/Notes/Mapping/NoteMap.cs
  backend/api/Constants/NoteType.cs
  backend/api/Models/Concepts/Note/NoteMap.cs
  backend/api/Models/Concepts/Note/NoteModel.cs
  backend/api/Services/INoteService.cs
  backend/api/Services/NoteService.cs
  backend/dal/Repositories/Interfaces/INoteRepository.cs
  backend/dal/Repositories/NoteRepository.cs
  backend/tests/unit/api/Controllers/Note/NoteControllerTest.cs
  frontend/src/constants/noteTypes.ts
  frontend/src/features/notes/list/NoteListView.test.tsx
  frontend/src/features/notes/list/NoteListView.tsx
  frontend/src/features/notes/list/NoteResults/NoteResults.test.tsx
  frontend/src/features/notes/list/NoteResults/NoteResults.tsx
  frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  frontend/src/features/notes/list/styles.ts
  frontend/src/hooks/pims-api/useApiNotes.test.ts
  frontend/src/hooks/pims-api/useApiNotes.ts
  frontend/src/mocks/mockNoteResponses.ts
  frontend/src/models/api/Note.ts
  frontend/src/pages/TestNotes.tsx
Labels: enhancement

#1722 Increment DEV version to IS32
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: devops, release-management

#1730 Changes to fix the CR Comments
  backend/api/Areas/Notes/Controllers/NoteController.cs
  backend/api/Areas/Notes/Mapping/NoteMap.cs
  backend/api/Models/Concepts/Note/NoteModel.cs
  backend/api/Services/INoteService.cs
  backend/api/Services/NoteService.cs
  backend/dal/Repositories/Interfaces/INoteRepository.cs
  backend/dal/Repositories/NoteRepository.cs
  backend/tests/unit/api/Controllers/Note/NoteControllerTest.cs
  frontend/src/constants/claims.ts
  frontend/src/features/notes/list/NoteListView.test.tsx
  frontend/src/features/notes/list/NoteListView.tsx
  frontend/src/features/notes/list/NoteResults/NoteResults.test.tsx
  frontend/src/features/notes/list/NoteResults/NoteResults.tsx
  frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  frontend/src/hooks/pims-api/useApiNotes.test.ts
  frontend/src/hooks/pims-api/useApiNotes.ts
  frontend/src/mocks/mockNoteResponses.ts
  frontend/src/models/api/Note.ts
  frontend/src/pages/TestNotes.tsx
Labels: enhancement

#1731 psp-3832 psp-3833 remove researchfile-add claim from restricted user.…
  auth/keycloak/Dockerfile
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Alter Down/11_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Alter Up/97_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Build/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
  frontend/src/features/properties/map/research/ResearchContainer.tsx
Labels: bug

#1736 Update codeowners
  .github/CODEOWNERS
Labels: devops

#1733 Backmerge test into dev
  backend/api/Areas/Notes/Controllers/NoteController.cs
  backend/api/Areas/Notes/Mapping/NoteMap.cs
  backend/api/Models/Concepts/Note/NoteModel.cs
  backend/api/Services/INoteService.cs
  backend/api/Services/NoteService.cs
  backend/dal/Repositories/Interfaces/INoteRepository.cs
  backend/dal/Repositories/NoteRepository.cs
  backend/tests/unit/api/Controllers/Note/NoteControllerTest.cs
  frontend/src/constants/claims.ts
  frontend/src/features/notes/list/NoteListView.test.tsx
  frontend/src/features/notes/list/NoteListView.tsx
  frontend/src/features/notes/list/NoteResults/NoteResults.test.tsx
  frontend/src/features/notes/list/NoteResults/NoteResults.tsx
  frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  frontend/src/hooks/pims-api/useApiNotes.test.ts
  frontend/src/hooks/pims-api/useApiNotes.ts
  frontend/src/mocks/mockNoteResponses.ts
  frontend/src/models/api/Note.ts
  frontend/src/pages/TestNotes.tsx
Labels: alignment

#1744 Psp 3821 - add support for local clamav scanning
  backend/Pims.sln
  backend/api/Controllers/DocumentController.cs
  backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
  backend/api/Pims.Api.csproj
  backend/api/Program.cs
  backend/api/Services/DocumentService.cs
  backend/api/Services/IDocumentService.cs
  backend/api/Startup.cs
  backend/api/av.Local.json
  backend/api/av.json
  backend/clamav/ClamAvService.cs
  backend/clamav/Configuration/ClamAvOptions.cs
  backend/clamav/Exceptions/AvException.cs
  backend/clamav/Extensions/ServiceCollectionExtensions.cs
  backend/clamav/IAvService.cs
  backend/clamav/Pims.Av.csproj
  backend/tests/core/TestHelper.cs
  backend/tests/unit/dal/Libraries/Av/AvServiceCollectionTest.cs
  backend/tests/unit/dal/Libraries/Av/ClamAvServiceTest.cs
  backend/tests/unit/dal/Services/DocumentServiceTest.cs
  docker-compose.yml
  openshift/4.0/templates/api/deploy.yaml
Labels: enhancement

#1752 Bug Fixes - PSP-3867, PSP-3863
  frontend/.vscode/launch.json
  frontend/src/features/admin/access-request/AccessRequestForm.test.tsx
  frontend/src/features/admin/access-request/AccessRequestForm.tsx
  frontend/src/features/admin/access-request/__snapshots__/AccessRequestContainer.test.tsx.snap
  frontend/src/features/admin/access-request/__snapshots__/AccessRequestForm.test.tsx.snap
  frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/insurance/edit/InsuranceYupSchema.ts
  frontend/src/utils/YupSchema.ts
Labels: bug

#1749 Property Edit Update | Features/psp 3524
  frontend/package-lock.json
  frontend/src/features/mapSideBar/MotiInventoryContainer.test.tsx
  frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  frontend/src/features/mapSideBar/MotiInventoryHeader.test.tsx
  frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  frontend/src/features/mapSideBar/__snapshots__/MotiInventoryHeader.test.tsx.snap
  frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/propertyInformation/ComposedProperty.ts
  frontend/src/features/properties/map/propertyInformation/PropertyContainer.tsx
  frontend/src/features/properties/map/propertyInformation/PropertyViewSelector.tsx
  frontend/src/features/properties/map/research/ResearchContainer.tsx
  frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
  frontend/src/features/properties/map/research/update/properties/UpdateProperties.tsx
  frontend/src/features/properties/map/shared/SidebarFooter.tsx
Labels: enhancement

#1761 Bugs/psp 3850
  backend/api/Areas/Tools/Controllers/GeocoderController.cs
  backend/geocoder/Parameters/NearestParameters.cs
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
  frontend/src/components/maps/leaflet/mapUtils.tsx
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/research/common/ResearchFileNameGuide.tsx
  frontend/src/features/properties/map/research/common/__snapshots__/ResearchFileNameGuide.test.tsx.snap
  frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  frontend/src/features/properties/selector/MapSelectorContainer.test.tsx
  frontend/src/features/properties/selector/__snapshots__/MapSelectorContainer.test.tsx.snap
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.test.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.tsx
  frontend/src/features/properties/selector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap
  frontend/src/features/properties/selector/search/mapPropertyColumns.ts
  frontend/src/hooks/pims-api/useApiGeocoder.ts
  frontend/src/hooks/pims-api/useFullyAttributedParcelMapLayer.test.tsx
  frontend/src/hooks/pims-api/useFullyAttributedParcelMapLayer.ts
  frontend/src/hooks/pims-api/useWfsLayer.ts
Labels: bug

#1746 psp-3800 Add additional error handling/logging to JSON parsing.
  backend/ltsa/LtsaService.cs
Labels: bug

#1756 fix missing modal label change from psp-3072
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
Labels: bug

#1759 psp-3930 remove lease edit from finance role.
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Alter Down/11_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Alter Up/97_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
Labels: db-migration

#1760 PSP-3617: Reusable component - List of uploaded documents
  backend/api/Controllers/DocumentController.cs
  backend/api/Controllers/LookupController.cs
  backend/api/Models/Concepts/Document/DocumentMap.cs
  backend/api/Models/Concepts/Document/DocumentModel.cs
  backend/api/Models/Concepts/Document/DocumentTypeMap.cs
  backend/api/Models/Concepts/Document/DocumentTypeModel.cs
  backend/api/Services/DocumentService.cs
  backend/api/Services/IDocumentService.cs
  backend/dal/Repositories/Interfaces/ILookupService.cs
  backend/dal/Repositories/LookupService.cs
  backend/dal/Security/Permissions.cs
  backend/entities/Partials/DocumentType.cs
  backend/entities/Partials/PimsDocumentStatusType.cs
  frontend/src/constants/API.ts
  frontend/src/constants/documentTypes.ts
  frontend/src/features/documents/list/DocumentFilter/DocumentFilterForm.test.tsx
  frontend/src/features/documents/list/DocumentFilter/DocumentFilterForm.tsx
  frontend/src/features/documents/list/DocumentFilter/__snapshots__/DocumentFilterForm.test.tsx.snap
  frontend/src/features/documents/list/DocumentListView.test.tsx
  frontend/src/features/documents/list/DocumentListView.tsx
  frontend/src/features/documents/list/DocumentResults/DocumentResults.test.tsx
  frontend/src/features/documents/list/DocumentResults/DocumentResults.tsx
  frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  frontend/src/features/documents/list/styles.ts
  frontend/src/hooks/pims-api/useApiDocuments.ts
  frontend/src/interfaces/IDocumentResults.ts
  frontend/src/mocks/mockDocuments.ts
  frontend/src/mocks/mockLookups.ts
  frontend/src/models/api/Document.ts
  frontend/src/pages/TestFileManagement.tsx
Labels: enhancement

#1764 PSP-3726 View and update notes
  Makefile
  backend/api/Areas/Notes/Controllers/NoteController.cs
  backend/api/Models/Concepts/Note/NoteMap.cs
  backend/api/Services/INoteService.cs
  backend/api/Services/NoteService.cs
  backend/dal/Repositories/Interfaces/INoteRepository.cs
  backend/dal/Repositories/NoteRepository.cs
  backend/tests/unit/api/Routes/Notes/NoteControllerTest.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Alter Down/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Alter Down/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Alter Up/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Alter Up/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Build/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S32_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
  frontend/Makefile
  frontend/src/components/common/CancelConfirmationModal.tsx
  frontend/src/components/common/styles.ts
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  frontend/src/features/notes/NoteContainer.tsx
  frontend/src/features/notes/add/AddNotesContainer.test.tsx
  frontend/src/features/notes/add/AddNotesContainer.tsx
  frontend/src/features/notes/add/AddNotesYupSchema.ts
  frontend/src/features/notes/add/models.ts
  frontend/src/features/notes/detail/NoteDetailsFormModal.tsx
  frontend/src/features/notes/hooks/useAddNote.test.tsx
  frontend/src/features/notes/hooks/useAddNote.ts
  frontend/src/features/notes/hooks/useAddNotesFormManagement.test.tsx
  frontend/src/features/notes/hooks/useAddNotesFormManagement.ts
  frontend/src/features/notes/hooks/useNoteRepository.ts
  frontend/src/features/notes/hooks/useUpdateNotesFormManagement.ts
  frontend/src/features/notes/list/NoteListHeader/NoteListHeader.tsx
  frontend/src/features/notes/list/NoteListView.test.tsx
  frontend/src/features/notes/list/NoteListView.tsx
  frontend/src/features/notes/list/NoteResults/NoteResults.tsx
  frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  frontend/src/features/notes/list/NoteResults/columns.tsx
  frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  frontend/src/features/notes/list/styles.ts
  frontend/src/features/notes/models.ts
  frontend/src/features/notes/update/UpdateNoteContainer.tsx
  frontend/src/features/notes/update/UpdateNoteFormModal.tsx
  frontend/src/features/notes/update/UpdateNoteYupSchema.ts
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/hooks/pims-api/useApiNotes.test.ts
  frontend/src/hooks/pims-api/useApiNotes.ts
  frontend/src/hooks/useModalManagement.ts
  frontend/src/pages/TestNotes.tsx
  frontend/src/utils/axiosUtils.ts
Labels: enhancement

#1775 Backmerge test into dev
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
Labels: alignment

#1748 update properties screens to use id instead of pid where appropriate.
  backend/api/Areas/Property/Controllers/PropertyController.cs
  backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  backend/dal/Repositories/PropertyRepository.cs
  backend/geocoder/Extensions/ServiceCollectionExtensions.cs
  backend/tests/unit/api/Controllers/Property/PropertyControllerTest.cs
  backend/tests/unit/api/Routes/Property/PropertyControllerTest.cs
  frontend/src/components/maps/leaflet/PointClusterer.tsx
  frontend/src/features/mapSideBar/MotiInventoryContainer.test.tsx
  frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/hooks/useGetProperty.ts
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/propertyInformation/PropertyViewSelector.tsx
  frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
  frontend/src/hooks/pims-api/useApiProperties.ts
  frontend/src/hooks/useProperties.ts
  frontend/src/hooks/usePropertyAssociations.ts
Labels: bug

#1786 Add doc for clamav configuration.
  openshift/4.0/templates/clamav/README.md
  openshift/4.0/templates/clamav/clamav-bc.conf
  openshift/4.0/templates/clamav/clamav-dc.conf
Labels: documentation

#1792 Bump version on TEST
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#1790 Increment DEV version to IS33
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: devops, release-management

#1795 PSP-3726 tests
  backend/api/Services/NoteService.cs
  backend/dal/Repositories/NoteRepository.cs
  backend/tests/core/Entities/ActivityHelper.cs
  backend/tests/core/Entities/NoteHelper.cs
  backend/tests/unit/api/Controllers/Note/NoteControllerTest.cs
  backend/tests/unit/api/Routes/Notes/NoteControllerTest.cs
  backend/tests/unit/dal/Repositories/NoteRepositoryTest.cs
  backend/tests/unit/dal/Services/NoteServiceTest.cs
  frontend/src/features/notes/NoteContainer.test.tsx
  frontend/src/features/notes/NoteContainer.tsx
  frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  frontend/src/features/notes/detail/NoteDetailsFormModal.test.tsx
  frontend/src/features/notes/detail/NoteDetailsFormModal.tsx
  frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap
  frontend/src/features/notes/hooks/useAddNote.test.tsx
  frontend/src/features/notes/hooks/useNoteRepository.test.tsx
  frontend/src/features/notes/hooks/useNoteRepository.ts
  frontend/src/features/notes/hooks/useUpdateNotesFormManagement.test.tsx
  frontend/src/features/notes/list/NoteResults/NoteResults.test.tsx
  frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  frontend/src/features/notes/update/UpdateNoteContainer.test.tsx
  frontend/src/features/notes/update/UpdateNoteFormModal.test.tsx
  frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap
  frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap
  frontend/src/mocks/mockNoteResponses.ts
Labels: unit-tests

#1807 Generated scaffold for schema changes S33
  backend/entities/PimsBaseContext.cs
  backend/entities/ef/PimsAcquisitionFile.cs
  backend/entities/ef/PimsAcquisitionFileHist.cs
  backend/entities/ef/PimsRegion.cs
Labels: db-scaffold
