Repository bcgov/PSP, pull requests merged in 2022-10, with the labels that each got.

#2216 correct sonarqube error, ensure numeric sort applied (not lexical app…
  frontend/src/features/properties/map/activity/list/ActivityResults/columns.tsx
Labels: bug

#2215 npm version bumps to quieten down dependabot
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2225 Add 24_DML_PIMS_ACTIVITY_TEMPLATE_Insert.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S36_02/HotFix/00_DML_PIMS_ACTIVITY_TEMPLATE_Insert.sql
Labels: db-hotfix

#2224 PSP-4413 Acquisition file number create and update
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/ISequenceRepository.cs
  source/backend/dal/Repositories/SequenceRepository.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionRepositoryTest.cs
Labels: enhancement

#2235 Scaffold for S38_01
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcquisitionFile.cs
  source/backend/entities/ef/PimsAcquisitionFileHist.cs
Labels: db-scaffold

#2241 Bug Fixes: PSP-4496, PSP-4605
  backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  frontend/src/components/common/GenericModal.tsx
  frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.test.tsx
  frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.tsx
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityPropertyModal.test.tsx.snap
Labels: bug

#2242 PSP-4100 Fix GitHub action for releases
  .github/workflows/release.yml
  Makefile
Labels: devops

#2238 Psp 4617
  frontend/src/features/acquisition/list/AcquisitionListView.tsx
  frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.test.tsx
  frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.tsx
  frontend/src/features/acquisition/list/AcquisitionSearchResults/__snapshots__/AcquisitionSearchResults.test.tsx.snap
  frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  frontend/src/features/acquisition/list/AcquisitionSearchResults/models.ts
  frontend/src/features/research/list/ResearchListView.tsx
  frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.tsx
  frontend/src/features/research/list/ResearchSearchResults/__snapshots__/ResearchSearchResults.test.tsx.snap
  frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  frontend/src/interfaces/IResearchSearchResult.ts
Labels: bug

#2237 psp-4495 add fallback for address display.
  frontend/src/components/common/OverflowTip.tsx
  frontend/src/features/leases/detail/StackedTenantFields.tsx
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionProperties.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityPropertyModal.test.tsx.snap
  frontend/src/features/properties/map/activity/properties/PropertyActivityTable.tsx
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  frontend/src/features/properties/selector/components/SelectedPropertyRow.test.tsx
  frontend/src/features/properties/selector/components/SelectedPropertyRow.tsx
  frontend/src/features/properties/selector/components/__snapshots__/SelectedPropertyRow.test.tsx.snap
  frontend/src/features/properties/selector/utils.ts
Labels: bug

#2232 correct test api/keycloak settings.
  tools/keycloak/sync/appsettings.test.json
  tools/keycloak/sync/realm.test.json
Labels: devops

#2214 psp-4505 add claims for document generation.
  source/backend/dal/Security/Permissions.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S38_00/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S38_00/Alter Down/77_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S38_00/Alter Up/76_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S38_00/Alter Up/77_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S38_00/Build/74_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S38_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S38_01/Build/75_DML_PIMS_ROLE_CLAIM.sql
  source/frontend/src/constants/claims.ts
Labels: enhancement

#2228 Psp-3984 cleanup frontend to use Api_Property. Remove references to old IApiPropertyModel. Introduce a hook to facilitate loading composed properties.
  source/backend/api/Areas/Property/Controllers/PropertyController.cs
  source/backend/api/Areas/Property/Mapping/Property/LeaseMap.cs
  source/backend/api/Areas/Property/Mapping/Property/PropertyMap.cs
  source/backend/api/Areas/Property/Models/Property/LeaseModel.cs
  source/backend/api/Areas/Property/Models/Property/PropertyModel.cs
  source/backend/tests/unit/api/Routes/Property/PropertyControllerTest.cs
  source/frontend/src/components/maps/leaflet/PointClusterer.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.helpers.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/hooks/useGetProperty.ts
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  source/frontend/src/features/properties/map/MapRouter.tsx
  source/frontend/src/features/properties/map/MapSideBar.tsx
  source/frontend/src/features/properties/map/MapView.test.tsx
  source/frontend/src/features/properties/map/MapView.tsx
  source/frontend/src/features/properties/map/propertyInformation/ComposedProperty.ts
  source/frontend/src/features/properties/map/propertyInformation/PropertyContainer.tsx
  source/frontend/src/features/properties/map/propertyInformation/PropertyViewSelector.tsx
  source/frontend/src/features/properties/map/shared/detail/PropertyFileContainer.test.tsx
  source/frontend/src/features/properties/map/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/hooks/pims-api/useApiContacts.ts
  source/frontend/src/hooks/pims-api/useApiProperties.test.tsx
  source/frontend/src/hooks/pims-api/useApiProperties.ts
  source/frontend/src/hooks/pims-api/useApiRequestWrapper.ts
  source/frontend/src/hooks/pims-api/useFullyAttributedParcelMapLayer.ts
  source/frontend/src/hooks/pims-api/useGeoServer.ts
  source/frontend/src/hooks/pims-api/useWfsLayer.test.tsx
  source/frontend/src/hooks/pims-api/useWfsLayer.ts
  source/frontend/src/hooks/useComposedProperties.ts
  source/frontend/src/hooks/useLtsa.ts
  source/frontend/src/hooks/useProperties.ts
  source/frontend/src/hooks/usePropertyAssociations.ts
  source/frontend/src/interfaces/IPropertyApiModel.ts
  source/frontend/src/models/api/Property.ts
Labels: enhancement

#2247 PSP-4072 Remove random string generator
  source/backend/core/Helpers/StringHelper.cs
  source/backend/tests/core/DatabaseHelper.cs
  source/backend/tests/core/ServiceHelper.cs
  source/backend/tests/unit/dal/Core/Helpers/StringHelperTest.cs
Labels: tech-debt

#2223 PSP-4131: Auto capture Activity Status Change as a Note
  source/backend/api/Models/Concepts/ActivityInstance/ActivityInstanceMap.cs
  source/backend/api/Services/ActivityService.cs
  source/backend/dal/Repositories/ActivityRepository.cs
  source/backend/dal/Repositories/Interfaces/IActivityRepository.cs
  source/backend/tests/unit/api/Services/ActivityServiceTest.cs
  source/frontend/src/features/notes/detail/NoteDetailsFormModal.tsx
  source/frontend/src/features/notes/list/NoteResults/columns.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityControlsBar.tsx
Labels: enhancement

#2227 PSP-4297:Display acquisition files on the PIMS files tab
  source/backend/api/Areas/Property/Mapping/Property/AssociationMap.cs
  source/backend/api/Areas/Property/Models/Property/AssociationModel.cs
  source/backend/api/Areas/Property/Models/Property/PropertyAssociationModel.cs
  source/backend/dal/Helpers/Extensions/AcquisitionExtensions.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/src/features/mapSideBar/tabs/propertyAssociations/AssociationContent.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyAssociations/PropertyAssociationTabView.test.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
  source/frontend/src/models/api/Property.ts
Labels: enhancement

#2260 Backmerge master to test
  .github/workflows/release.yml
  Makefile
Labels: devops, alignment

#2264 Backmerge test to dev
  .github/workflows/release.yml
  Makefile
  database/mssql/scripts/dbscripts/PSP_PIMS_S36_02/HotFix/00_DML_PIMS_ACTIVITY_TEMPLATE_Insert.sql
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/frontend/src/components/common/GenericModal.tsx
  source/frontend/src/components/common/OverflowTip.tsx
  source/frontend/src/components/maps/leaflet/Map.tsx
  source/frontend/src/features/acquisition/list/AcquisitionListView.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.test.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/__snapshots__/AcquisitionSearchResults.test.tsx.snap
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/models.ts
  source/frontend/src/features/leases/detail/StackedTenantFields.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionProperties.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.tsx
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityPropertyModal.test.tsx.snap
  source/frontend/src/features/properties/map/activity/list/ActivityResults/columns.tsx
  source/frontend/src/features/properties/map/activity/properties/PropertyActivityTable.tsx
  source/frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/properties/selector/components/SelectedPropertyRow.test.tsx
  source/frontend/src/features/properties/selector/components/SelectedPropertyRow.tsx
  source/frontend/src/features/properties/selector/components/__snapshots__/SelectedPropertyRow.test.tsx.snap
  source/frontend/src/features/properties/selector/utils.ts
  source/frontend/src/features/research/list/ResearchListView.tsx
  source/frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.tsx
  source/frontend/src/features/research/list/ResearchSearchResults/__snapshots__/ResearchSearchResults.test.tsx.snap
  source/frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  source/frontend/src/interfaces/IResearchSearchResult.ts
  tools/keycloak/sync/appsettings.test.json
  tools/keycloak/sync/realm.test.json
Labels: alignment

#2263 Fixed initial setting of measurements. Fixed layout
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/LandMeasurementEditTable.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/LandMeasurementTable.test.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/VolumetricMeasurementTable.test.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/VolumetricMeasurementTable.tsx
Labels: bug

#2271 Fix conditional build in GH Actions
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
Labels: devops

#2275 Acquisition File, Research File and refactoring
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseLicense.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFile.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/PageObjects/Tenants.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#2278 Increment DEV version to IS39
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops, release-management

#2285 Scaffold s39_00
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAccessRequest.cs
  source/backend/entities/ef/PimsAcquisitionOwner.cs
  source/backend/entities/ef/PimsAcquisitionOwnerHist.cs
  source/backend/entities/ef/PimsAddress.cs
  source/backend/entities/ef/PimsLease.cs
  source/backend/entities/ef/PimsLeaseHist.cs
  source/backend/entities/ef/PimsLeaseTenant.cs
  source/backend/entities/ef/PimsPropPropTenureType.cs
  source/backend/entities/ef/PimsPropertyLease.cs
  source/backend/entities/ef/PimsResearchFilePurpose.cs
Labels: db-scaffold

#2281 PSP-4609 Remove thicker outline on select, input fields on contact add/edit forms
  source/frontend/src/components/common/form/styles.ts
  source/frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/styles.ts
  source/frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/styles.ts
Labels: enhancement

#2282 PSP-4585: BVT: Update Research File list view labels to be consistent…
  source/frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.tsx
  source/frontend/src/features/research/list/ResearchSearchResults/__snapshots__/ResearchSearchResults.test.tsx.snap
  source/frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
Labels: frontend

#2296 Uat tag fix
  .github/workflows/ci-cd-pims-master.yml
  openshift/4.0/scripts/oc-tag.sh
Labels: bug

#2298 Update navigation link name
  source/frontend/src/components/layout/SideNavBar/AdminTools.tsx
Labels: bug

#2300 psp-4624 ensure that province is displayed when selecting lease tenants.
  source/frontend/src/features/leases/detail/LeasePages/tenant/Tenant.tsx
Labels: bug

#2299 psp-4672 correct POI legend label.
  source/frontend/src/components/maps/leaflet/Legend/Legend.tsx
  source/frontend/src/components/maps/leaflet/Legend/__snapshots__/Legend.test.tsx.snap
  source/frontend/src/components/maps/leaflet/mapUtils.tsx
  source/frontend/src/hooks/pims-api/useWfsLayer.test.tsx
Labels: bug

#2289 Moved database lingering folder
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S36_02/HotFix/00_DML_PIMS_ACTIVITY_TEMPLATE_Insert.sql
Labels: tech-debt, db-migration

#2313 Updated area and volume calculators
  source/frontend/config-overrides.js
  source/frontend/package-lock.json
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/components/measurements/AreaContainer.tsx
  source/frontend/src/components/measurements/AreaForm.test.tsx
  source/frontend/src/components/measurements/AreaForm.tsx
  source/frontend/src/components/measurements/AreaView.tsx
  source/frontend/src/components/measurements/VolumeContainer.tsx
  source/frontend/src/components/measurements/VolumeForm.test.tsx
  source/frontend/src/components/measurements/VolumeForm.tsx
  source/frontend/src/components/measurements/VolumeView.tsx
  source/frontend/src/components/measurements/__snapshots__/AreaForm.test.tsx.snap
  source/frontend/src/components/measurements/__snapshots__/VolumeForm.test.tsx.snap
  source/frontend/src/components/measurements/styles.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.helpers.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/components/LandMeasurementTable.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/components/VolumetricMeasurementTable.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/__snapshots__/LandMeasurementTable.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/components/__snapshots__/VolumetricMeasurementTable.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/common/ResearchFileNameGuide.tsx
  source/frontend/src/features/properties/map/research/common/__snapshots__/ResearchFileNameGuide.test.tsx.snap
  source/frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
Labels: enhancement

#2315 Automation Test refactoring
  .gitignore
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseSurplus.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFile.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#2316 Lease Historical fields update
  source/backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  source/backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  source/backend/api/Areas/Leases/Models/Search/LeaseFilterModel.cs
  source/backend/dal/Helpers/Extensions/LeaseExtensions.cs
  source/backend/dal/Models/LeaseFilter.cs
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseForm.tsx
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/NoteSubForm.test.tsx
  source/frontend/src/features/leases/add/NoteSubForm.tsx
  source/frontend/src/features/leases/add/PropertyInformationSubForm.tsx
  source/frontend/src/features/leases/add/ReferenceSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/NoteSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/PropertyInformationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/interfaces.ts
  source/frontend/src/features/leases/leaseUtils.ts
  source/frontend/src/features/leases/list/LeaseFilter/LeaseFilter.tsx
  source/frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  source/frontend/src/interfaces/ILease.ts
Labels: enhancement

#2318 PSP-4411: FRONTEND - Log keycloak errors properly
  source/frontend/src/utils/getKeycloakEventHandler.ts
Labels: tech-debt

#2326 Fix map markers in dev
  source/frontend/src/components/maps/leaflet/Legend/Legend.tsx
  source/frontend/src/components/maps/leaflet/Legend/__snapshots__/Legend.test.tsx.snap
  source/frontend/src/components/maps/leaflet/mapUtils.tsx
Labels: bug

#2311 clamav auto update template, instructions.
  openshift/4.0/templates/clamav/README.md
  openshift/4.0/templates/clamav/clamav-cron.conf
Labels: enhancement

#2297 Psp 4495 fix property summary display of address.
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/ResearchFileRepository.cs
  source/frontend/src/features/properties/map/MapView.test.tsx
  source/frontend/src/features/properties/map/research/add/ResearchProperties.test.tsx
  source/frontend/src/utils/propertyUtils.ts
Labels: bug

#2333 Backmerge master to test
  .github/workflows/ci-cd-pims-master.yml
  openshift/4.0/scripts/oc-tag.sh
  tools/keycloak/sync/appsettings.uat.json
  tools/keycloak/sync/realm.uat.json
Labels: devops

#2314 PSP-4408: Deprecate "useApi" hook
  source/frontend/src/components/maps/leaflet/Map.test.tsx
  source/frontend/src/features/properties/components/GeocoderAutoComplete.test.tsx
  source/frontend/src/features/properties/components/GeocoderAutoComplete.tsx
  source/frontend/src/features/properties/selector/search/LayerFilter.tsx
  source/frontend/src/features/properties/selector/search/PropertySearchSelectorFormView.tsx
  source/frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/hooks/pims-api/interfaces/IGeocoder.ts
  source/frontend/src/hooks/pims-api/useApiGeocoder.ts
  source/frontend/src/hooks/useApi.test.tsx
  source/frontend/src/hooks/useApi.ts
  source/frontend/src/hooks/useGeocoderRepository.ts
  source/frontend/src/mocks/mockGeocoderResponses.ts
Labels: tech-debt

#2317 Psp 4695
  source/frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  source/frontend/src/features/properties/map/acquisition/ViewSelector.tsx
  source/frontend/src/features/properties/map/propertyInformation/PropertyViewSelector.tsx
  source/frontend/src/features/properties/map/research/ResearchContainer.tsx
  source/frontend/src/features/properties/map/research/ViewSelector.tsx
  source/frontend/src/features/properties/map/research/update/property/UpdatePropertyView.tsx
  source/frontend/src/features/properties/map/research/update/summary/UpdateSummaryView.tsx
  source/frontend/src/features/properties/map/shared/detail/PropertyFileContainer.tsx
Labels: enhancement

#2338 Backmerge TEST to DEV
  .github/workflows/ci-cd-pims-master.yml
  openshift/4.0/scripts/oc-tag.sh
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/ResearchFileRepository.cs
  source/frontend/src/components/layout/SideNavBar/AdminTools.tsx
  source/frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  source/frontend/src/features/properties/map/acquisition/ViewSelector.tsx
  source/frontend/src/features/properties/map/propertyInformation/PropertyViewSelector.tsx
  source/frontend/src/features/properties/map/research/ResearchContainer.tsx
  source/frontend/src/features/properties/map/research/ViewSelector.tsx
  source/frontend/src/features/properties/map/research/update/property/UpdatePropertyView.tsx
  source/frontend/src/features/properties/map/research/update/summary/UpdateSummaryView.tsx
  source/frontend/src/features/properties/map/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/utils/propertyUtils.ts
  tools/keycloak/sync/appsettings.uat.json
  tools/keycloak/sync/realm.uat.json
Labels: alignment

#2346 Increment DEV version - IS40
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2349 Updated styles
  source/frontend/src/components/common/TabView.tsx
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionProperties.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/ActivityTray/styles.ts
  source/frontend/src/features/properties/map/activity/detail/ActivityControlsBar.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityForm.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityHeader.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityView.tsx
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityControlsBar.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityHeader.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  source/frontend/src/features/properties/map/activity/list/ActivityFilter/ActivityFilterForm.tsx
  source/frontend/src/features/properties/map/activity/list/ActivityFilter/__snapshots__/ActivityFilterForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/list/ActivityListView.tsx
  source/frontend/src/features/properties/map/activity/list/ActivityResults/__snapshots__/ActivityResults.test.tsx.snap
  source/frontend/src/features/properties/map/activity/list/ActivityResults/columns.tsx
  source/frontend/src/features/properties/map/activity/list/__snapshots__/ActivityListView.test.tsx.snap
  source/frontend/src/features/properties/map/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/properties/selector/__snapshots__/MapSelectorContainer.test.tsx.snap
Labels: enhancement, tech-debt

#2342 add an idp hint to keycloak configuration, so that the users don't ne…
  source/frontend/src/features/account/Login.tsx
Labels: enhancement

#2312 PSP-3685: Reusable Component - Close Activity (General)
  source/frontend/src/features/properties/map/activity/ActivityTray/ActivityTray.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityControlsBar.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityControlsBar.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityDescription.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityDescription.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityForm.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityForm.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityView.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityView.tsx
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityControlsBar.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  source/frontend/src/features/properties/map/shared/SidebarFooter.tsx
Labels: enhancement

#2360 Schema s40 scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsActivityInstance.cs
  source/backend/entities/ef/PimsLease.cs
  source/backend/entities/ef/PimsLeaseActivityInstance.cs
  source/backend/entities/ef/PimsLeaseActivityInstanceHist.cs
Labels: db-scaffold
