Repository bcgov/PSP, pull requests merged in 2022-09, with the labels that each got.

#1986 desired tag is latest-uat not latest-master
  .github/workflows/ci-cd-pims-master.yml
Labels: devops

#1985 PSP-4066: Add test coverage for document upload, list, get document
  frontend/src/components/common/form/Multiselect.test.tsx
  frontend/src/features/documents/DocumentMetadataView.tsx
  frontend/src/features/documents/DownloadDocumentButton.tsx
  frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  frontend/src/features/documents/documentDetail/DocumentDetailView.test.tsx
  frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
  frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailView.test.tsx.snap
  frontend/src/features/documents/documentUpload/DocumentUploadModal.tsx
  frontend/src/features/documents/documentUpload/DocumentUploadView.test.tsx
  frontend/src/features/documents/documentUpload/DocumentUploadView.tsx
  frontend/src/features/documents/documentUpload/__snapshots__/DocumentUploadView.test.tsx.snap
  frontend/src/features/documents/list/DocumentListView.test.tsx
  frontend/src/features/documents/list/DocumentListView.tsx
  frontend/src/features/documents/list/DocumentResults/DocumentResults.test.tsx
  frontend/src/features/documents/list/DocumentResults/DocumentResultsColumns.tsx
  frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
Labels: tech-debt

#2009 Backend stylecop fixes
  backend/api/Areas/Activities/Controllers/ActivityController.cs
  backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  backend/api/Services/DocumentService.cs
  backend/dal/Repositories/ActivityRepository.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  backend/tests/unit/dal/Repositories/ResearchRepositoryTest.cs
  backend/tests/unit/dal/Services/ResearchServiceTest.cs
Labels: bug

#2015 make sonarqube action on push only.
  .github/workflows/api-dotnetcore.yml
Labels: devops

#2022 Increment DEV to IS36
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#2014 Feature/psp 4066
  frontend/src/features/documents/documentDetail/DocumentDetailView.test.tsx
  frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailView.test.tsx.snap
  frontend/src/features/documents/documentUpload/DocumentUploadView.test.tsx
  frontend/src/features/documents/documentUpload/__snapshots__/DocumentUploadView.test.tsx.snap
  frontend/src/mocks/mockDocuments.ts
Labels: tech-debt

#2029 Add missing mappings from last sprint
  backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePropertyMap.cs
Labels: tech-debt

#2034 PSP-4320 Improve LTSA logging
  backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
  backend/ltsa/LtsaService.cs
Labels: enhancement

#2035 Added new search filter and result column | psp-3904
  backend/api/Areas/Acquisition/Models/AcquisitionFilterModel.cs
  backend/dal/Helpers/Extensions/AcquisitionExtensions.cs
  backend/dal/Models/AcquisitionFilter.cs
  frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.tsx
  frontend/src/features/acquisition/list/AcquisitionFilter/__snapshots__/AcquisitionFilter.test.tsx.snap
  frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionProperties.tsx
  frontend/src/features/acquisition/list/AcquisitionSearchResults/__snapshots__/AcquisitionSearchResults.test.tsx.snap
  frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  frontend/src/features/acquisition/list/interfaces.ts
  frontend/src/features/properties/map/MapRouter.tsx
  frontend/src/utils/propertyUtils.ts
Labels: enhancement

#2045 npm package fixes, tested manually.
  frontend/package-lock.json
  frontend/package.json
Labels: devops

#2047 Psp 4234 fix mapping issue preventing any surplus declaration data from displaying.
  backend/api/Areas/Leases/Mapping/Lease/PropertyMap.cs
Labels: bug

#2057 Feature/psp 4272
  frontend/src/features/documents/documentUpload/DocumentUploadYupSchema.tsx
Labels: bug

#2053 Bugs/psp 4038
  frontend/src/features/documents/list/DocumentFilter/DocumentFilterForm.test.tsx
  frontend/src/features/documents/list/DocumentFilter/DocumentFilterForm.tsx
  frontend/src/features/documents/list/DocumentFilter/__snapshots__/DocumentFilterForm.test.tsx.snap
  frontend/src/features/documents/list/DocumentListView.test.tsx
  frontend/src/features/documents/list/DocumentListView.tsx
  frontend/src/features/documents/list/DocumentResults/DocumentResults.test.tsx
  frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  frontend/src/interfaces/IDocumentResults.ts
  frontend/src/mocks/mockDocuments.ts
Labels: bug

#2055 BUGFIX: PSP-4241 When notes are extensive, the Property Information Slide-out resizes
  frontend/src/features/properties/map/MapSideBar.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: bug

#2033 psp-3965 display plan number when saved/loaded on a research file.
  backend/api/Models/Concepts/Property/PropertyMap.cs
  backend/api/Models/Concepts/Property/PropertyModel.cs
  frontend/src/features/properties/map/research/ResearchContainer.test.tsx
  frontend/src/features/properties/map/research/__snapshots__/ResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/models.ts
  frontend/src/features/properties/selector/utils.ts
  frontend/src/mocks/mockResearchFile.ts
Labels: bug

#2046 Psp 4237 ensure the help desk arrow is on the same line as the dependent element.
  frontend/src/features/help/components/HelpBox.scss
  frontend/src/features/help/components/HelpBox.tsx
  frontend/src/features/help/components/__snapshots__/HelpBox.test.tsx.snap
Labels: bug

#2054 psp-3827 ensure that adding a property to a file from the map populat…
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.tsx
  frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
  frontend/src/components/maps/providers/SelectedPropertyContext.tsx
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  frontend/src/features/properties/map/acquisition/add/models.ts
  frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.ts
  frontend/src/features/properties/map/research/add/AddResearchContainer.test.tsx
  frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
  frontend/src/features/properties/map/research/add/models.ts
  frontend/src/features/properties/selector/MapSelectorContainer.test.tsx
  frontend/src/features/properties/selector/MapSelectorContainer.tsx
  frontend/src/features/properties/selector/components/MapClickMonitor.tsx
  frontend/src/features/properties/selector/map/PropertyMapSelectorFormView.tsx
  frontend/src/features/properties/selector/search/PropertySearchSelectorFormView.test.tsx
Labels: bug

#2032 psp-4182 allow clicking on a properties boundary in addition to its m…
  frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
  frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopup.tsx
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.test.tsx
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.tsx
  frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
  frontend/src/features/properties/map/MapView.tsx
  geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_BOUNDARY_VW/featuretype.xml
  geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_BOUNDARY_VW/layer.xml
Labels: bug

#2076 Rfile fix
  frontend/src/features/research/list/ResearchListView.test.tsx
  frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.tsx
  frontend/src/interfaces/IResearchSearchResult.ts
Labels: bug

#2072 PSP-4074 Review todos on backend and frontend
  backend/api/Areas/Admin/Controllers/RoleController.cs
  backend/api/Controllers/UserController.cs
  backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
  backend/api/Helpers/Swagger/ConfigureSwaggerOptions.cs
  backend/api/Models/CodeModel.cs
  backend/api/Startup.cs
  backend/core/Converters/GeometryJsonConverter.cs
  backend/core/Exceptions/HttpClientRequestException.cs
  backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  backend/dal/Models/PageFilter.cs
  backend/dal/Repositories/ContactRepository.cs
  backend/dal/Repositories/OrganizationRepository.cs
  backend/dal/Repositories/PropertyRepository.cs
  backend/keycloak/KeycloakService.cs
  backend/ltsa/Models/TitleOrder.cs
  backend/tests/core/TestHelper.cs
  frontend/src/App.test.tsx
  frontend/src/components/Table/Table.tsx
  frontend/src/components/Table/TablePagination.tsx
  frontend/src/components/common/TooltipWrapper.tsx
  frontend/src/components/maps/BasemapToggle.tsx
  frontend/src/components/maps/hooks/useMapSearch.tsx
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/constants/API.ts
  frontend/src/customAxios.ts
  frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  frontend/src/features/contacts/contact/create/styles.ts
  frontend/src/features/help/components/HelpModal.tsx
  frontend/src/features/leases/detail/LeasePages/payment/styles.tsx
  frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  frontend/src/features/properties/map/activity/list/ActivityFilter/ActivityFilterForm.tsx
  frontend/src/features/properties/map/propertyInformation/PropertyContainer.tsx
  frontend/src/features/properties/selector/components/MapClickMonitor.tsx
  frontend/src/hooks/useApi.ts
  frontend/src/hooks/useFavicon.test.ts
  frontend/src/hooks/useRouterFilter.test.tsx
  frontend/src/mocks/filterDataMock.ts
  frontend/src/utils/getKeycloakEventHandler.ts
Labels: documentation, tech-debt

#2075 Psp 3946
  backend/api/Models/Concepts/ActivityInstance/ActivityInstancePropertyFile.cs
  backend/api/Services/DocumentService.cs
  backend/api/Services/IDocumentService.cs
  backend/dal/Repositories/DocumentActivityRepository.cs
  backend/dal/Repositories/DocumentRepository.cs
  backend/dal/Repositories/ResearchFilePropertyRepository.cs
  frontend/src/features/properties/map/activity/ActivityTray/ActivityTray.tsx
  frontend/src/features/properties/map/activity/detail/ActivityContainer.tsx
  frontend/src/features/properties/map/activity/detail/ActivityDescription.tsx
  frontend/src/features/properties/map/activity/detail/ActivityForm.test.tsx
  frontend/src/features/properties/map/activity/detail/ActivityForm.tsx
  frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.test.tsx
  frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.tsx
  frontend/src/features/properties/map/activity/detail/ActivityView.test.tsx
  frontend/src/features/properties/map/activity/detail/ActivityView.tsx
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/content/formContent.tsx
  frontend/src/features/properties/map/activity/detail/content/models.ts
  frontend/src/features/properties/map/activity/detail/models.ts
  frontend/src/mocks/mockActivities.ts
Labels: enhancement

#2051 PSP-3620: ACQ - Adding Acquisition staff
  backend/api/Controllers/LookupController.cs
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePersonMap.cs
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePersonModel.cs
  backend/dal/Repositories/AcquisitionFileRepository.cs
  backend/dal/Repositories/Interfaces/ILookupService.cs
  backend/dal/Repositories/LookupService.cs
  backend/entities/Partials/AcqFilePersonProfileType.cs
  backend/entities/Partials/AcquisitionFilePerson.cs
  backend/entities/ef/PimsAcqFlPersonProfileType.cs
  frontend/src/components/common/form/ContactInput.tsx
  frontend/src/components/contact/ContactManagerModal.tsx
  frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  frontend/src/constants/API.ts
  frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/__snapshots__/ReceivedDepositForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionFileYupSchema.ts
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionTeamForm.test.tsx
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionTeamForm.tsx
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionTeamForm.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/models.ts
  frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#2077 PSP-4135:Activity Status Changes (Matrix)
  backend/api/Models/Concepts/ActivityInstance/ActivityInstanceMap.cs
  backend/api/Models/Concepts/ActivityInstance/ActivityInstanceModel.cs
  frontend/src/constants/API.ts
  frontend/src/features/properties/map/activity/detail/ActivityControlsBar.test.tsx
  frontend/src/features/properties/map/activity/detail/ActivityControlsBar.tsx
  frontend/src/features/properties/map/activity/detail/ActivityForm.tsx
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityControlsBar.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/models.ts
  frontend/src/features/properties/map/activity/list/ActivityFilter/ActivityFilterForm.tsx
  frontend/src/features/properties/map/activity/list/ActivityListView.tsx
  frontend/src/mocks/mockActivities.ts
  frontend/src/models/api/Activity.ts
Labels: enhancement

#2056 Feature/psp 4243
  frontend/src/components/Table/Table.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionProperties.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/selector/__snapshots__/MapSelectorContainer.test.tsx.snap
  frontend/src/features/properties/selector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap
Labels: bug

#2097 correct issue with not being able to click map properties in test/dev
  frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
Labels: bug

#2106 Scaffold for S37
  backend/entities/PimsBaseContext.cs
  backend/entities/ef/PimsAcqFlPersonProfileType.cs
  backend/entities/ef/PimsAcquisitionFile.cs
  backend/entities/ef/PimsAcquisitionFileHist.cs
  backend/entities/ef/PimsNoteHist.cs
Labels: db-scaffold

#2080 Automation - Contacts
  testing/PIMS.Tests.Automation/.gitignore
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/ImplicitUsings.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.sln
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/Login.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/Tenants.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/GenericSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LoginSteps.cs
Labels: test-scripts

#2114 PSP-4231:UI/UX corrections for contact and user screens
  frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  frontend/src/components/contact/ContactManagerView/ContactFilterComponent/__snapshots__/ContactFilterComponent.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  frontend/src/features/admin/access/ManageAccessRequestsPage.tsx
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  frontend/src/features/admin/users/ManageUsersPage.tsx
  frontend/src/features/admin/users/components/UsersFilterBar.tsx
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
Labels: frontend

#2115 Document generation integration
  backend/api/Areas/DocumentGeneration/DocumentGenerationController.cs
  backend/api/Areas/Documents/DocumentController.cs
  backend/api/Models/Cdogs/FileTypes.cs
  backend/api/Models/Cdogs/JwtResponse.cs
  backend/api/Models/Cdogs/UploadTemplateCachedError.cs
  backend/api/Models/Configuration/CdogsConfig.cs
  backend/api/Repositories/Cdogs/CdogsAuthRepository.cs
  backend/api/Repositories/Cdogs/CdogsBaseRepository.cs
  backend/api/Repositories/Cdogs/CdogsRepository.cs
  backend/api/Repositories/Cdogs/IDocumentGenerationAuthRepository.cs
  backend/api/Repositories/Cdogs/IDocumentGenerationRepository.cs
  backend/api/Repositories/Mayan/MayanBaseRepository.cs
  backend/api/Repositories/RestCommon/BaseRestRespository.cs
  backend/api/Repositories/RestCommon/IRestRespository.cs
  backend/api/Services/DocumentGenerationService.cs
  backend/api/Services/IDocumentGenerationService.cs
  backend/api/Startup.cs
  backend/api/appsettings.json
Labels: enhancement

#2124 Updated env generation for the api file
  scripts/gen-env-files.sh
Labels: enhancement, tech-debt

#2129 Psp 4494
  frontend/src/components/Table/ColumnSort.tsx
  frontend/src/components/Table/Table.test.tsx
  frontend/src/components/Table/Table.tsx
  frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/ContactManagerView.test.tsx
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/ContactResultComponent.test.tsx
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  frontend/src/features/acquisition/list/AcquisitionSearchResults/__snapshots__/AcquisitionSearchResults.test.tsx.snap
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  frontend/src/features/properties/map/activity/list/ActivityResults/__snapshots__/ActivityResults.test.tsx.snap
  frontend/src/features/properties/map/activity/list/__snapshots__/ActivityListView.test.tsx.snap
  frontend/src/features/properties/selector/search/PropertySearchSelectorFormView.tsx
  frontend/src/features/research/list/ResearchSearchResults/__snapshots__/ResearchSearchResults.test.tsx.snap
  frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
Labels: bug

#2131 PSP-4489:FT: Acquisition Files - Adding Staff: UI allows to choose or…
  frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
Labels: bug

#2132 psp-4242
  backend/api/Services/AcquisitionFileService.cs
  backend/api/Services/ResearchFileService.cs
  backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  backend/dal/Repositories/PropertyRepository.cs
  backend/tests/unit/api/Services/ResearchServiceTest.cs
  backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
Labels: bug

#2113 PSP-3889:Field label suggestions for Property Information tab
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/update/validation.ts
  frontend/src/mocks/mockLookups.ts
Labels: frontend

#2136 Psp 4490
  frontend/src/features/acquisition/list/AcquisitionFilter/__snapshots__/AcquisitionFilter.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/ActivityControlsBar.test.tsx
  frontend/src/features/properties/map/activity/detail/ActivityControlsBar.tsx
  frontend/src/features/properties/map/activity/detail/ActivityForm.tsx
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityControlsBar.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  frontend/src/features/properties/map/activity/list/ActivityFilter/__snapshots__/ActivityFilterForm.test.tsx.snap
  frontend/src/features/properties/map/activity/list/ActivityListView.test.tsx
  frontend/src/features/properties/map/activity/list/__snapshots__/ActivityListView.test.tsx.snap
  frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  frontend/src/features/research/list/ResearchFilter/__snapshots__/ResearchFilter.test.tsx.snap
  frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  frontend/src/mocks/mockActivities.ts
  frontend/src/mocks/mockLookups.ts
Labels: bug

#2130 PSP-3271 Acquisition File details view
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePersonMap.cs
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePersonModel.cs
  backend/dal/Repositories/AcquisitionFileRepository.cs
  frontend/src/constants/index.ts
  frontend/src/features/mapSideBar/layout/FileLayout.tsx
  frontend/src/features/mapSideBar/tabs/FileTabs.tsx
  frontend/src/features/mapSideBar/tabs/SectionField.tsx
  frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx
  frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  frontend/src/features/properties/map/acquisition/EditFormNames.ts
  frontend/src/features/properties/map/acquisition/ViewSelector.tsx
  frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  frontend/src/features/properties/map/acquisition/common/AcquisitionMenu.test.tsx
  frontend/src/features/properties/map/acquisition/common/AcquisitionMenu.tsx
  frontend/src/features/properties/map/acquisition/common/__snapshots__/AcquisitionMenu.test.tsx.snap
  frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.tsx
  frontend/src/features/properties/map/acquisition/detail/AcquisitionSummaryView.test.tsx
  frontend/src/features/properties/map/acquisition/detail/AcquisitionSummaryView.tsx
  frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  frontend/src/features/properties/map/acquisition/detail/models.ts
  frontend/src/features/properties/map/research/ResearchContainer.tsx
  frontend/src/features/properties/map/research/ResearchTabsContainer.tsx
  frontend/src/features/properties/map/research/__snapshots__/ResearchContainer.test.tsx.snap
  frontend/src/features/properties/selector/utils.ts
  frontend/src/mocks/mockAcquisitionFiles.ts
  frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#2133 BIGFIX: PSP-4500 HTTP 400 error thrown when notes are updated
  backend/api/Models/Concepts/Note/NoteMap.cs
  backend/api/Models/Concepts/Note/NoteModel.cs
  frontend/src/models/api/Note.ts
Labels: bug

#2137 Psp 4498
  frontend/src/components/Table/Table.test.tsx
  frontend/src/components/Table/Table.tsx
  frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  frontend/src/components/menu/Menu.tsx
  frontend/src/components/menu/__snapshots__/Menu.test.tsx.snap
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
Labels: bug

#2135 PSP-4450: Acquisition team alignment issues
  frontend/src/assets/scss/_variables.module.scss
  frontend/src/components/common/buttons/RemoveButton.tsx
  frontend/src/components/common/form/ContactInput.tsx
  frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/__snapshots__/ReceivedDepositForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionTeamForm.test.tsx
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionTeamForm.tsx
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionProperties.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  frontend/src/features/properties/selector/components/__snapshots__/SelectedPropertyRow.test.tsx.snap
Labels: bug

#2152 File activity list header alignment fix
  frontend/src/components/common/buttons/IconButton.tsx
  frontend/src/components/common/buttons/RemoveButton.tsx
  frontend/src/components/common/form/NotesModal.tsx
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  frontend/src/features/admin/users/ManageUsersPage.tsx
  frontend/src/features/contacts/contact/detail/Container.tsx
  frontend/src/features/leases/list/LeaseListView.tsx
  frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  frontend/src/features/notes/list/NoteResults/columns.tsx
  frontend/src/features/properties/list/PropertyListView.tsx
  frontend/src/features/properties/map/activity/list/ActivityResults/__snapshots__/ActivityResults.test.tsx.snap
  frontend/src/features/properties/map/activity/list/ActivityResults/columns.tsx
  frontend/src/features/properties/map/activity/list/__snapshots__/ActivityListView.test.tsx.snap
Labels: bug

#2149 Added comment section validation for Contact form
  frontend/src/features/contacts/contact/create/validation.ts
Labels: bug

#2143 Updated search of properties and improved aggregation of the data
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
  frontend/src/features/documents/hooks/useDocumentProvider.ts
  frontend/src/features/properties/selector/models.ts
  frontend/src/features/properties/selector/search/LayerFilter.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.test.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.tsx
  frontend/src/hooks/pims-api/useApiGeocoder.test.ts
  frontend/src/hooks/pims-api/useApiGeocoder.ts
  frontend/src/hooks/pims-api/useApiRequestWrapper.ts
  frontend/src/hooks/useGeocoderRepository.ts
Labels: bug

#2144 PSP-4376: Create ACQ - Default region and give message when removing …
  frontend/src/features/properties/map/acquisition/add/AcquisitionProperties.test.tsx
  frontend/src/features/properties/map/acquisition/add/AcquisitionProperties.tsx
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  frontend/src/features/properties/map/acquisition/modals/AcquisitionFormModal.tsx
Labels: enhancement

#2160 Psp 4492
  frontend/src/features/properties/map/activity/detail/ActivityForm.tsx
Labels: bug

#2112 PSP-3740:Verb usage in the left nav bar sub-menu labels
  frontend/src/components/layout/SideNavBar/AcquisitionTray.test.tsx
  frontend/src/components/layout/SideNavBar/AcquisitionTray.tsx
  frontend/src/components/layout/SideNavBar/ContactTray.tsx
  frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  frontend/src/components/layout/SideNavBar/ResearchTray.tsx
  frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  frontend/src/components/layout/SideNavBar/__snapshots__/AcquisitionTray.test.tsx.snap
  frontend/src/features/leases/list/LeaseListView.tsx
Labels: frontend

#2138 psp-4510 correct display of property name on activity property selector.
  frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.test.tsx
  frontend/src/features/properties/map/activity/properties/PropertyActivityTable.tsx
  frontend/src/features/properties/map/research/ResearchContainer.tsx
  frontend/src/features/properties/selector/utils.ts
  frontend/src/mocks/mockProperties.ts
Labels: bug

#2167 PSP-3740:CR fixes
  frontend/src/components/layout/SideNavBar/AcquisitionTray.test.tsx
  frontend/src/components/layout/SideNavBar/AcquisitionTray.tsx
  frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  frontend/src/components/layout/SideNavBar/ResearchTray.tsx
  frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  frontend/src/components/layout/SideNavBar/__snapshots__/AcquisitionTray.test.tsx.snap
Labels: frontend

#2173 Backmerge master to test
  .github/workflows/ci-cd-pims-master.yml
Labels: devops

#2174 Backmerge test to dev
  .github/workflows/ci-cd-pims-master.yml
  backend/api/Models/Concepts/Note/NoteMap.cs
  backend/api/Models/Concepts/Note/NoteModel.cs
  backend/api/Services/AcquisitionFileService.cs
  backend/api/Services/ResearchFileService.cs
  backend/core/Properties/launchSettings.json
  backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  backend/dal/Repositories/PropertyRepository.cs
  backend/tests/unit/api/Services/ResearchServiceTest.cs
  backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  frontend/src/components/Table/ColumnSort.tsx
  frontend/src/components/Table/Table.test.tsx
  frontend/src/components/Table/Table.tsx
  frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  frontend/src/components/contact/ContactManagerView/ContactManagerView.test.tsx
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/ContactResultComponent.test.tsx
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  frontend/src/components/menu/Menu.tsx
  frontend/src/components/menu/__snapshots__/Menu.test.tsx.snap
  frontend/src/features/acquisition/list/AcquisitionFilter/__snapshots__/AcquisitionFilter.test.tsx.snap
  frontend/src/features/acquisition/list/AcquisitionSearchResults/__snapshots__/AcquisitionSearchResults.test.tsx.snap
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  frontend/src/features/contacts/contact/create/validation.ts
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  frontend/src/features/properties/map/activity/detail/ActivityControlsBar.test.tsx
  frontend/src/features/properties/map/activity/detail/ActivityControlsBar.tsx
  frontend/src/features/properties/map/activity/detail/ActivityForm.tsx
  frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.test.tsx
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityControlsBar.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  frontend/src/features/properties/map/activity/list/ActivityFilter/__snapshots__/ActivityFilterForm.test.tsx.snap
  frontend/src/features/properties/map/activity/list/ActivityListView.test.tsx
  frontend/src/features/properties/map/activity/list/ActivityResults/__snapshots__/ActivityResults.test.tsx.snap
  frontend/src/features/properties/map/activity/list/__snapshots__/ActivityListView.test.tsx.snap
  frontend/src/features/properties/map/activity/properties/PropertyActivityTable.tsx
  frontend/src/features/properties/map/research/ResearchContainer.tsx
  frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  frontend/src/features/properties/selector/search/PropertySearchSelectorFormView.tsx
  frontend/src/features/properties/selector/utils.ts
  frontend/src/features/research/list/ResearchFilter/__snapshots__/ResearchFilter.test.tsx.snap
  frontend/src/features/research/list/ResearchSearchResults/__snapshots__/ResearchSearchResults.test.tsx.snap
  frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  frontend/src/mocks/mockActivities.ts
  frontend/src/mocks/mockLookups.ts
  frontend/src/mocks/mockProperties.ts
  frontend/src/models/api/Note.ts
Labels: devops

#2161 Psp 4256
  backend/api/Services/AcquisitionFileService.cs
  backend/dal/Repositories/ActivityRepository.cs
  frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  frontend/src/features/properties/map/activity/list/ActivityListView.tsx
  frontend/src/features/properties/map/activity/list/ActivityResults/ActivityResults.test.tsx
  frontend/src/features/properties/map/activity/list/ActivityResults/ActivityResults.tsx
  frontend/src/features/properties/map/activity/list/ActivityResults/__snapshots__/ActivityResults.test.tsx.snap
  frontend/src/features/properties/map/activity/list/ActivityResults/columns.tsx
  frontend/src/features/properties/map/activity/list/__snapshots__/ActivityListView.test.tsx.snap
  frontend/src/features/properties/map/context/sidebarContext.tsx
  frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
Labels: enhancement

#2170 Psp 3913
  backend/api/Areas/Property/Mapping/Property/PropertyMap.cs
  backend/api/Areas/Property/Models/Property/PropertyModel.cs
  backend/api/Areas/Research/Controllers/ResearchFileController.cs
  frontend/src/components/maps/leaflet/mapUtils.tsx
  frontend/src/features/mapSideBar/tabs/InventoryTabs.tsx
  frontend/src/features/mapSideBar/tabs/propertyResearch/PropertyResearchTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyResearch/PropertyResearchTabView.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/acquisition/ViewSelector.tsx
  frontend/src/features/properties/map/activity/detail/ActivityContainer.tsx
  frontend/src/features/properties/map/activity/list/ActivityResults/columns.tsx
  frontend/src/features/properties/map/propertyInformation/PropertyContainer.tsx
  frontend/src/features/properties/map/research/ViewSelector.tsx
  frontend/src/features/properties/map/research/__snapshots__/ResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.test.tsx
  frontend/src/features/properties/map/research/update/property/models.ts
  frontend/src/features/properties/map/shared/detail/PropertyFileContainer.test.tsx
  frontend/src/features/properties/map/shared/detail/PropertyFileContainer.tsx
  frontend/src/features/properties/map/shared/detail/__snapshots__/PropertyFileContainer.test.tsx.snap
  frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  frontend/src/features/properties/selector/utils.ts
  frontend/src/features/research/list/ResearchListView.test.tsx
  frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.tsx
  frontend/src/features/research/list/ResearchSearchResults/__snapshots__/ResearchSearchResults.test.tsx.snap
  frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  frontend/src/hooks/pims-api/useApiResearchFile.ts
  frontend/src/hooks/usePropertyAssociations.ts
  frontend/src/interfaces/IResearchSearchResult.ts
  frontend/src/mocks/mockResearchFile.ts
  frontend/src/models/api/AcquisitionFile.ts
  frontend/src/models/api/PropertyResearchFile.ts
  frontend/src/models/api/ResearchFile.ts
Labels: enhancement

#2186 Automation Leases and Licenses
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseSurplus.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/Tenants.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
Labels: test-scripts

#2191 Increment DEV version to IS38
  backend/api/Pims.Api.csproj
  frontend/package-lock.json
  frontend/package.json
Labels: devops

#2202 PSP-4552: Fix input field width in Acquisition File update form
  frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
Labels: bug

#2211 Fix npm install
  source/backend/dal/Properties/launchSettings.json
  source/frontend/.husky/pre-commit
  source/frontend/.husky/pre-push
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: bug

#2192 psp-4485 fix mapview scroll bar
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: bug
