Repository bcgov/PSP, pull requests merged in 2022-02, with the labels that each got.

#823 psp-2830 remove physical security tab.
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeaseContainer.tsx
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseIndex.test.tsx.snap
Labels: enhancement

#816 psp-2693 display the other text values on the view screen.
  frontend/src/features/leases/add/AdministrationSubForm.test.tsx
  frontend/src/features/leases/add/AdministrationSubForm.tsx
  frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.test.tsx
  frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
Labels: enhancement

#815 Psp 2616
  frontend/src/features/leases/detail/LeasePages/surplus/Surplus.tsx
  frontend/src/interfaces/IProperty.ts
Labels: bug

#843 Fix Contact list email | Bugs/psp 2722
  backend/api/Areas/Contacts/Mapping/Search/ContactSummaryMap.cs
Labels: bug

#833 psp-2662 remove organizations from users and access requests.
  frontend/src/features/leases/detail/LeasePages/payment/hooks/useCalculateActualGst.tsx
  frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentForm.test.tsx
Labels: enhancement

#829 documentation updates on recent technical decisions.
  adr/api-architecture.md
  adr/child-entities.md
  adr/database-first.md
Labels: documentation, tech-debt

#846 Fixed overlapping contact info
  frontend/src/features/contacts/contact/detail/Organization.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
  frontend/src/features/contacts/contact/detail/__snapshots__/Organization.test.tsx.snap
  frontend/src/features/contacts/contact/detail/__snapshots__/Person.test.tsx.snap
Labels: bug

#841 PSP-2819: Contact Method Validation Bug Fix
  frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.tsx
  frontend/src/features/contacts/contact/create/Person/CreatePersonForm.tsx
Labels: bug

#840 Psp reconfiguration for is19 execution
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_Load.dtsx
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_PIMS.dtproj
  etl/LISOS_PIMS/LISOS_PIMS/Project.params
  etl/PAIMS_PIMS/PAIMS_PIMS/MOTI_LEGACY_PAIMS_PIMS_DATA_MIGRATION.dtproj
  etl/PAIMS_PIMS/PAIMS_PIMS/PAIMS.conmgr
  etl/PAIMS_PIMS/PAIMS_PIMS/PAM_LOAD_PAIMS_TO_PIMS_DATASET_2.dtsx
Labels: etl

#876 Backmerge TEST into DEV
  frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.tsx
  frontend/src/features/contacts/contact/create/Person/CreatePersonForm.tsx
Labels: release-management

#879 Fix CI build action
  .github/workflows/ci-cd-pims-dev.yml
Labels: bug, devops

#885 Update gen env files.
  scripts/gen-env-files.sh
Labels: enhancement

#884 Psp 2758
  frontend/src/components/common/OverflowTip.tsx
  frontend/src/components/common/form/Form.scss
  frontend/src/components/common/form/Input.tsx
  frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.test.tsx.snap
  frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
  frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/contacts/list/filter/__snapshots__/ContactFilter.test.tsx.snap
  frontend/src/features/help/components/__snapshots__/HelpSubmitBox.test.tsx.snap
  frontend/src/features/help/containers/__snapshots__/HelpModalContentContainer.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/PropertyInformationSubForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/__snapshots__/AddressSubForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/__snapshots__/DepositNotes.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/__snapshots__/ReceivedDepositForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/insurance/edit/__snapshots__/EditContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermModal.tsx
  frontend/src/features/leases/detail/LeasePages/payment/modal/term/__snapshots__/TermForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/TenantNotes.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/TenantOrganizationContactInfo.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/TenantPersonContactInfo.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap
  frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/interfaces/IPerson.ts
Labels: enhancement

#890 Bump version to IS21
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#893 Psp 2529
  frontend/src/features/leases/detail/LeaseContainer.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/InsuranceContainer.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/details/Insurance.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/details/Policy.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/insurance/details/styles.ts
  frontend/src/features/leases/detail/LeasePages/insurance/edit/EditContainer.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/edit/__snapshots__/EditContainer.test.tsx.snap
  frontend/src/features/leases/hooks/useLeaseDetail.ts
Labels: enhancement

#894 PSP-2844 Require proper claims to edit contacts
  frontend/src/features/contacts/contact/detail/Container.test.tsx
  frontend/src/features/contacts/contact/detail/Container.tsx
  frontend/src/features/contacts/contact/detail/__snapshots__/Container.test.tsx.snap
  frontend/src/features/contacts/list/ContactSearchResults/ContactSearchResults.test.tsx
  frontend/src/features/contacts/list/ContactSearchResults/__snapshots__/ContactSearchResults.test.tsx.snap
  frontend/src/features/contacts/list/ContactSearchResults/columns.tsx
Labels: bug

#899 Backmerge test into dev
  frontend/src/components/common/ErrorTabs.tsx
  frontend/src/components/common/GenericModal.tsx
  frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.tsx
  frontend/src/features/contacts/contact/create/Person/CreatePersonForm.tsx
  frontend/src/features/contacts/contact/detail/Container.test.tsx
  frontend/src/features/contacts/contact/detail/Container.tsx
  frontend/src/features/contacts/contact/detail/__snapshots__/Container.test.tsx.snap
  frontend/src/features/contacts/list/ContactSearchResults/ContactSearchResults.test.tsx
  frontend/src/features/contacts/list/ContactSearchResults/__snapshots__/ContactSearchResults.test.tsx.snap
  frontend/src/features/contacts/list/ContactSearchResults/columns.tsx
Labels: release-management

#895 PSP-2823: Changing tooltip for Terms Header
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
Labels: bug

#898 psp-2827 correct issues with LISOS etl.
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_Load.dtsx
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_PIMS.dtproj
Labels: bug

#902 PSP-2846 - GitHub action "CI-CD PIMS Test"
  .github/workflows/ci-cd-pims-test.yml
  openshift/4.0/scripts/oc-tag.sh
Labels: devops

#908 psp-2821 fix lease terms with same start date.
  backend/dal/Repositories/LeaseRepository.cs
  backend/dal/Services/LeaseTermService.cs
  backend/tests/unit/dal/Services/LeaseTermServiceTest.cs
Labels: bug

#913 Backmerge test to dev
  backend/dal/Repositories/LeaseRepository.cs
  backend/dal/Services/LeaseTermService.cs
  backend/tests/unit/dal/Services/LeaseTermServiceTest.cs
  frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx
  frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
Labels: devops

#914 PSP-2300 update organization - BACKEND
  backend/api/Areas/Organizations/Controllers/OrganizationController.cs
  backend/api/Areas/Organizations/Mapping/Organization/AddressMap.cs
  backend/api/Areas/Organizations/Mapping/Organization/ContactMethodMap.cs
  backend/api/Areas/Organizations/Mapping/Organization/OrganizationMap.cs
  backend/api/Areas/Organizations/Mapping/Organization/PersonMap.cs
  backend/api/Areas/Organizations/Models/Organization/OrganizationAddressModel.cs
  backend/api/Areas/Organizations/Models/Organization/OrganizationModel.cs
  backend/api/Areas/Organizations/Models/Organization/PersonSummaryModel.cs
  backend/api/Areas/Persons/Controllers/PersonController.cs
  backend/api/Areas/Persons/Mapping/Person/ContactMethodMap.cs
  backend/api/Models/Contact/AddressModel.cs
  backend/api/Models/Contact/ContactMethodModel.cs
  backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  backend/dal/IPimsRepository.cs
  backend/dal/IPimsService.cs
  backend/dal/PimsRepository.cs
  backend/dal/PimsService.cs
  backend/dal/Repositories/Interfaces/IOrganizationRepository.cs
  backend/dal/Repositories/OrganizationRepository.cs
  backend/dal/Services/Interfaces/IOrganizationService.cs
  backend/dal/Services/OrganizationService.cs
  backend/entities/Organization.cs
  backend/tests/unit/api/Controllers/Organization/OrganizationControllerTest.cs
Labels: enhancement

#923 update execute permissions on file.
  openshift/4.0/scripts/oc-tag.sh
Labels: devops

#925 Added 2 environment variables required to ci-cd-pims-test.yml
  .github/workflows/ci-cd-pims-test.yml
Labels: devops

#934 Refactored backend and front end to align with DB changes
  backend/api/Areas/Leases/Controllers/SecurityDepositReturnController.cs
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Mapping/Lease/SecurityDepositMap.cs
  backend/api/Areas/Leases/Mapping/Lease/SecurityDepositReturnMap.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  backend/api/Areas/Leases/Models/Lease/SecurityDepositModel.cs
  backend/api/Areas/Leases/Models/Lease/SecurityDepositReturnModel.cs
  backend/dal/PIMSContext.cs
  backend/dal/Repositories/Interfaces/ISecurityDepositReturnRepository.cs
  backend/dal/Repositories/LeaseRepository.cs
  backend/dal/Repositories/SecurityDepositReturnRepository.cs
  backend/entities/ef/PimsLease.cs
  backend/entities/ef/PimsOrganization.cs
  backend/entities/ef/PimsOrganizationHist.cs
  backend/entities/ef/PimsSecurityDepositReturn.cs
  backend/entities/ef/PimsSecurityDepositReturnHist.cs
  backend/entities/ef/PimsSecurityDepositType.cs
  frontend/src/features/contacts/contact/detail/Organization.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/DepositsReceivedContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/DepositsReceivedContainer.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/DepositsReturnedContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/__snapshots__/DepositsReturnedContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnedDepositModal.test.tsx
  frontend/src/hooks/pims-api/useApiLeaseDepositsReturn.ts
  frontend/src/interfaces/ILeaseSecurityDeposit.ts
  frontend/src/interfaces/ILeaseSecurityDepositReturn.ts
Labels: enhancement

#933 psp-2913 fix missing organization being sent as "" instead of null.
  frontend/src/features/contacts/contact/create/Person/CreatePersonForm.test.tsx
  frontend/src/features/contacts/contactUtils.ts
Labels: bug

#944 Updated sizing of property filter
  frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  frontend/src/components/contact/ContactManagerView/ContactFilterComponent/__snapshots__/ContactFilterComponent.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  frontend/src/features/contacts/contact/detail/Organization.tsx
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  frontend/src/features/properties/filter/PropertyFilter.tsx
  frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: enhancement

#945 Lookup performance
  backend/api/Areas/Admin/Mapping/AccessRequest/AccessRequestMap.cs
  backend/api/Areas/Keycloak/Mapping/AccessRequest/AccessRequestMap.cs
  backend/api/Controllers/AccessRequestController.cs
  backend/api/Controllers/LookupController.cs
  backend/api/Mapping/AccessRequest/AccessRequestMap.cs
  backend/dal/Repositories/AccessRequest.cs
  backend/tests/unit/api/Controllers/AccessControllerTest.cs
  backend/tests/unit/api/Controllers/LookupControllerTest.cs
  frontend/src/components/layout/Header/Header.test.tsx
  frontend/src/components/layout/Header/UserProfile.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.test.tsx
  frontend/src/features/admin/access-request/AccessRequestPage.tsx
  frontend/src/features/admin/access/ManageAccessRequests.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.test.tsx
  frontend/src/features/admin/edit-user/EditUserPage.tsx
  frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  frontend/src/features/admin/users/ManageUsers.test.tsx
  frontend/src/features/admin/users/ManageUsers.tsx
  frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
  frontend/src/features/admin/users/components/UsersFilterBar.tsx
  frontend/src/features/admin/users/constants/index.tsx
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeaseStatusSummary.tsx
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseStatusSummary.test.tsx.snap
  frontend/src/features/properties/filter/PropertyFilter.test.tsx
Labels: enhancement

#949 Backmerge test to dev
  .github/workflows/ci-cd-pims-test.yml
  frontend/src/features/admin/users/ManageUsers.tsx
  frontend/src/features/leases/detail/LeasePages/payment/styles.tsx
Labels: devops

#930 psp-2829
  backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  backend/core/Extensions/DateExtensions.cs
Labels: bug

#960 Psp 1795
  backend/api/Areas/Reports/Controllers/LeaseController.cs
  backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Reports/Models/Lease/AggregatedLeaseModel.cs
  backend/api/Areas/Reports/Models/Lease/AggregatedLeasesModel.cs
  backend/api/Pims.Api.csproj
  backend/api/Resources/AggregatedLeasesTemplate.xlsx
  backend/core/Extensions/DateExtensions.cs
  backend/core/Pims.Core.csproj
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  backend/dal/IPimsService.cs
  backend/dal/Pims.Dal.csproj
  backend/dal/PimsService.cs
  backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  backend/dal/Repositories/LeaseRepository.cs
  backend/dal/Services/Interfaces/ILeaseReportsService.cs
  backend/dal/Services/LeasePaymentService.cs
  backend/dal/Services/LeaseReportsService.cs
  backend/entities/LeasePaymentStatusType.cs
  backend/entities/LeaseStatusType.cs
  backend/entities/Models/LeaseFilter.cs
  backend/tests/core/Entities/LeaseHelper.cs
  backend/tests/unit/api/Controllers/Reports/LeaseControllerTest.cs
  backend/tests/unit/api/Helpers/SolutionProvider.cs
  backend/tests/unit/dal/Core/Extensions/DateExtensionsTest.cs
  backend/tests/unit/dal/Services/LeaseReportsServiceTest.cs
  backend/tests/unit/dal/Services/LeaseServiceTest.cs
  backend/tests/unit/dal/Services/PaymentServiceTest.cs
  frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  frontend/src/components/layout/SideNavBar/styles.ts
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/hooks/useLeaseExport.ts
  frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.test.tsx
  frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.tsx
  frontend/src/features/leases/reports/aggregated/__snapshots__/ExportAggregatedLeasesContainer.test.tsx.snap
  frontend/src/hooks/pims-api/useApiLeases.ts
Labels: enhancement

#964 Use the incoming id to determine the contact type to retrieve.
  backend/api/Areas/Contacts/Controllers/ContactController.cs
Labels: enhancement

#968 Count on table pagination | Features/psp 2691
  frontend/src/components/Table/PageSizeSelector.tsx
  frontend/src/components/Table/Table.scss
  frontend/src/components/Table/Table.tsx
  frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/ContactResultComponent.tsx
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
  frontend/src/features/admin/users/ManageUsers.tsx
  frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
  frontend/src/features/contacts/list/ContactListPage.tsx
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  frontend/src/features/leases/list/LeaseListView.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/properties/list/PropertyListView.tsx
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
Labels: enhancement

#963 Access request organizations
  frontend/src/features/admin/access/ManageAccessRequests.tsx
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
  frontend/src/features/admin/access/components/Details.test.tsx
  frontend/src/features/admin/access/components/Details.tsx
  frontend/src/features/admin/access/components/Filter.tsx
  frontend/src/features/admin/access/constants/constants.tsx
  frontend/src/features/admin/access/interfaces/index.ts
Labels: enhancement

#974 Added missing pagination fields
  backend/api/Areas/Leases/Models/Search/LeaseFilterModel.cs
Labels: bug

#977 Enforce proper claims on Contact List view
  frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
Labels: enhancement

#982 scaffold for IS21.
  backend/api/Areas/Leases/Mapping/Lease/SecurityDepositMap.cs
  backend/api/Areas/Leases/Mapping/Lease/SecurityDepositReturnMap.cs
  backend/dal/PIMSContext.cs
  backend/entities/ef/PimsPerson.cs
  backend/entities/ef/PimsPersonHist.cs
  backend/entities/ef/PimsSecurityDeposit.cs
  backend/entities/ef/PimsSecurityDepositHolder.cs
  backend/entities/ef/PimsSecurityDepositReturn.cs
  backend/entities/ef/PimsSecurityDepositReturnHolder.cs
Labels: db-migration

#985 Fix issues with DB passwords preventing scaffolding
  scripts/gen-env-files.sh
Labels: devops

#993 Build fix
  backend/api/Pims.Api.csproj
  frontend/package.json
  openshift/4.0/scripts/oc-tag.sh
Labels: devops

#998 IS21 to TEST - fix build
  backend/api/Pims.Api.csproj
  frontend/package.json
  openshift/4.0/scripts/oc-tag.sh
Labels: release-management

#999 Increase DEV version to IS22
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#1002 version bumps.
  frontend/package-lock.json
  frontend/package.json
Labels: tech-debt

#1007 Psp 2960
  frontend/src/components/Table/PidCell.tsx
  frontend/src/features/leases/detail/LeasePages/surplus/Surplus.test.tsx
  frontend/src/features/leases/detail/LeasePages/surplus/Surplus.tsx
Labels: bug

#1003 Psp 2956
  frontend/src/components/Table/PropertyTypeCell.tsx
  frontend/src/components/common/Icons.ts
  frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.scss
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.test.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/LeaseAttributes.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/ParcelAttributes.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/ThreeColumnItem.tsx
  frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/HeaderActions.test.tsx.snap
  frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/InfoContent.test.tsx.snap
  frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/InfoSlideOut.test.tsx.snap
  frontend/src/components/maps/leaflet/Map.test.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/leaflet/__snapshots__/Map.test.tsx.snap
  frontend/src/constants/trueFalse.ts
  frontend/src/features/admin/users/interfaces/IUserRecord.ts
  frontend/src/features/properties/common/slices/propertyNameSlice.ts
  frontend/src/features/properties/common/slices/usePropertyNames.ts
  frontend/src/features/properties/filter/PropertyFilter.test.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/hooks/useCallbackAppSelector.ts
  frontend/src/store/rootReducer.ts
  frontend/src/utils/YupSchema.ts
  frontend/src/utils/storageUtils.ts
Labels: enhancement

#1006 Fix contact mgr full name search.
  database/mssql/scripts/dbscripts/PSP_PIMS_S21_00/Alter Up/01_PSP_PIMS_S20_00_Alter_Up.sql
Labels: db-migration

#1005 Psp 2949
  frontend/src/components/common/form/NotesModal.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/columns.tsx
Labels: bug

#1016 psp-2802 update configuration with updated urls, tests.
  backend/api/Program.cs
  backend/api/ltsa.Development.json
  backend/api/ltsa.Local.json
  backend/api/ltsa.Test.json
  backend/api/ltsa.json
  backend/ltsa/Configuration/LtsaOptions.cs
  test/Postman/pims-api-collection.json
Labels: enhancement

#1015 psp-3002 Add indent to report line.
  frontend/src/features/leases/detail/LeasePages/payment/styles.tsx
  frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.tsx
  frontend/src/features/leases/reports/aggregated/__snapshots__/ExportAggregatedLeasesContainer.test.tsx.snap
Labels: bug

#1014 Psp 2474
  frontend/src/App.scss
  frontend/src/assets/images/icon-lot.svg
  frontend/src/components/common/TabView.tsx
  frontend/src/components/common/TooltipWrapper.tsx
  frontend/src/components/common/styles.ts
  frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  frontend/src/components/layout/SideNavBar/styles.ts
  frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
  frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  frontend/src/components/maps/leaflet/InventoryLayer.tsx
  frontend/src/components/maps/leaflet/LayerPopup/PidLink.tsx
  frontend/src/components/maps/leaflet/LayerPopup/index.ts
  frontend/src/components/maps/leaflet/Map.scss
  frontend/src/components/maps/leaflet/Map.test.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/leaflet/PointClusterer.tsx
  frontend/src/components/maps/leaflet/__snapshots__/Map.test.tsx.snap
  frontend/src/components/maps/leaflet/styles.ts
  frontend/src/components/maps/providers/PropertyPopUpProvider.tsx
  frontend/src/features/mapSideBar/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.ts
  frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  frontend/src/features/mapSideBar/tabs/InventoryTabs.tsx
  frontend/src/features/properties/hooks/useDraftMarkerSynchronizer.tsx
  frontend/src/features/properties/list/PropertyListView.tsx
  frontend/src/features/properties/map/MapView.scss
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/hooks/index.ts
  frontend/src/hooks/useProperties.test.tsx
  frontend/src/hooks/useProperties.ts
  frontend/src/mocks/filterDataMock.ts
  frontend/src/store/rootReducer.ts
  frontend/src/store/slices/properties/index.ts
  frontend/src/store/slices/properties/interfaces/IPropertyDetail.ts
  frontend/src/store/slices/properties/interfaces/IPropertyState.ts
  frontend/src/store/slices/properties/interfaces/IStorePropertyDetail.ts
  frontend/src/store/slices/properties/interfaces/index.ts
  frontend/src/store/slices/properties/propertiesReducer.test.tsx
  frontend/src/store/slices/properties/propertiesSlice.ts
  frontend/src/styles.scss
  frontend/src/tabs.scss
  frontend/src/utils/propertyUtils.ts
Labels: enhancement

#1032 Made PID and PIN displaying optional
  frontend/src/features/leases/list/LeaseSearchResults/LeaseProperties.tsx
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
Labels: bug
