Repository bcgov/PSP, pull requests merged in 2022-12, with the labels that each got.

#2487 Lease Creation refactor | psp 4806
  source/backend/api/Services/LeaseService.cs
  source/frontend/package-lock.json
  source/frontend/src/AppRouter.tsx
  source/frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/AddLeaseForm.tsx
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/AdministrationSubForm.test.tsx
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/LeaseDatesSubForm.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.test.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/add/NoteSubForm.test.tsx
  source/frontend/src/features/leases/add/NoteSubForm.tsx
  source/frontend/src/features/leases/add/PropertyInformationSubForm.test.tsx
  source/frontend/src/features/leases/add/ReferenceSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDatesSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/NoteSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/PropertyInformationSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/styles.ts
  source/frontend/src/features/leases/detail/LeaseContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseListView.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/properties/map/MapRouter.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/shared/SidebarFooter.tsx
  source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
Labels: enhancement

#2492 Test backmerge
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/01_PSP_PIMS_S41_01_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/100_DML_PIMS_ACTIVITY_TEMPLATE_Delete.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/Schema Compare.zip
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/02_PSP_PIMS_S41_00_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/Schema Compare.zip
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Drop/01_PSP_PIMS_Drop.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/PIMS S41.00 Change Log.txt
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S41_00/Alter Down/01_PSP_PIMS_S41_01_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S41_00/Alter Down/100_DML_PIMS_ACTIVITY_TEMPLATE_Delete.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S41_00/Alter Up/02_PSP_PIMS_S41_00_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S41_00/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S41_00/Drop/01_PSP_PIMS_Drop.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S41_00/PIMS S41.00 Change Log.txt
Labels: alignment

#2498 S42 Scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsLeaseTenant.cs
  source/backend/entities/ef/PimsLeaseTenantHist.cs
  source/backend/entities/ef/PimsProperty.cs
  source/backend/entities/ef/PimsTenantType.cs
Labels: db-scaffold

#2501 HOTFIX: Psp-4937
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts
Labels: bug, hotfix

#2512 Backmerge master to test
  source/frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts
  source/frontend/src/hooks/useBcAssessmentLayer.ts
Labels: devops

#2520 Backmerge test to dev
  source/frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts
  source/frontend/src/hooks/useBcAssessmentLayer.ts
Labels: devops

#2522 Increment DEV version to IS43
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2526 Scaffold for s43
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsPropertyBoundaryVw.cs
  source/backend/entities/ef/PimsPropertyLease.cs
  source/backend/entities/ef/PimsPropertyLeaseHist.cs
  source/backend/entities/ef/PimsPropertyLocationVw.cs
Labels: db-scaffold

#2533 PSP-5033: Cancel warning pop-up should only appear when user made changes to the form
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
Labels: bug

#2535 PSP-5027 View property attribute - address
  source/frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/tabs/bcAssessment/BcAssessmentTabView.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/mocks/mockAddress.ts
  source/frontend/src/utils/propertyUtils.ts
Labels: enhancement

#2531 IS-43.00 Views Updated
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S43_00/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S43_00/Build/002_PSP_PIMS_Build.sql
Labels: db-migration

#2539 HOTFIX: psp-5105, psp-5123
  source/backend/api/Pims.Api.csproj
  source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  source/frontend/package.json
  source/frontend/src/features/properties/map/activity/detail/ActivityForm.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityView.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityView.tsx
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
Labels: hotfix

#2530 Automation - Activities, notes and digital documents
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/Activities.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFile.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ActivitiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#2545 Updated scaffold
  source/backend/entities/ef/PimsPropertyBoundaryVw.cs
  source/backend/entities/ef/PimsPropertyLocationVw.cs
Labels: db-scaffold

#2542 Added warning mesage when removing properties from leases
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
Labels: enhancement

#2536 Added marker logic for payable leases
  source/backend/api/Areas/Leases/Controllers/LeaseController.cs
  source/frontend/src/assets/images/pins/land-lease-selected.svg
  source/frontend/src/assets/images/pins/land-lease.svg
  source/frontend/src/assets/images/pins/land_lease-highlight.png
  source/frontend/src/assets/images/pins/land_lease.png
  source/frontend/src/components/maps/leaflet/Legend/Legend.tsx
  source/frontend/src/components/maps/leaflet/Legend/__snapshots__/Legend.test.tsx.snap
  source/frontend/src/components/maps/leaflet/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/mapUtils.tsx
  source/frontend/src/interfaces/IProperty.ts
  source/frontend/src/mocks/dataMocks.ts
Labels: enhancement

#2555 PSP-5066 Fix sort by status in activity list view
  source/frontend/src/features/properties/map/activity/list/ActivityListView.tsx
Labels: bug

#2561 Backmerge master to test
  source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  source/frontend/src/features/properties/map/activity/detail/ActivityForm.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityView.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityView.tsx
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
Labels: devops

#2560 Added lease create logic to the popup
  source/frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
  source/frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/AddLeaseForm.tsx
Labels: enhancement

#2556 PSP-5113: FT-REG: Property Inventory - List View: When an inserted ad…
  source/frontend/src/components/maps/leaflet/Map.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/list/PropertyListView.tsx
Labels: bug

#2554 PSP-4926: FT: Activities - When changing the activity to Complete or …
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.tsx
  source/frontend/src/features/properties/map/activity/properties/PropertyActivityTable.tsx
Labels: bug

#2562 add mayan sync endpoints to postman collection.
  test/Postman/pims-api-collection.json
Labels: enhancement

#2570 PSP-4407 Edit property address
  Makefile
  source/backend/api/Models/Concepts/Address/AddressMap.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
Labels: enhancement

#2569 psp-4929 correct delete behaviour when file is related to another fil…
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
Labels: bug

#2580 PSP-4844: Update version to 3.1
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2583 regenerate package-lock
  source/backend/api/Services/DocumentSyncService.cs
  source/frontend/package-lock.json
Labels: devops
