Repository bcgov/PSP, pull requests merged in 2022-11, with the labels that each got.

#2368 bump release version.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
Labels: devops

#2369 psp-4829 The FA parcel map layer does not require the Siteminder cookie anymor…
  source/frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
  source/frontend/src/hooks/pims-api/useFullyAttributedParcelMapLayer.ts
Labels: bug

#2374 PSP-4702 Hide last updated info for system-generated notes
  source/frontend/src/features/notes/detail/NoteDetailsFormModal.test.tsx
  source/frontend/src/features/notes/detail/NoteDetailsFormModal.tsx
Labels: bug

#2377 PSP-4800: Property Details Tab and Research Property Tab - Updates cannot be saved
  source/frontend/src/features/properties/map/research/ViewSelector.tsx
Labels: bug

#2376 PSP-4700: FT: CDOGS Document Template - Sortable List by Status doesn…
  source/frontend/src/features/documents/list/DocumentListView.tsx
Labels: bug

#2382 IS-40 Database Patch
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/02_PSP_PIMS_S39_00_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S40_00/Alter Up/02_PSP_PIMS_S39_00_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S40_00/Build/002_PSP_PIMS_Build.sql
Labels: db-migration

#2386 S40 Scaffold fix
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsLeaseActivityInstance.cs
  source/backend/entities/ef/PimsLeaseActivityInstanceHist.cs
Labels: db-scaffold

#2381 Psp 3410
  source/frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  source/frontend/src/components/maps/leaflet/InventoryLayer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.tsx
  source/frontend/src/components/maps/leaflet/Map.test.tsx
  source/frontend/src/components/maps/leaflet/Map.tsx
  source/frontend/src/components/maps/leaflet/PointClusterer.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
  source/frontend/src/components/maps/providers/SelectedPropertyContext.tsx
  source/frontend/src/features/properties/map/MapRouter.tsx
  source/frontend/src/features/properties/map/MapView.test.tsx
  source/frontend/src/features/properties/map/MapView.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/AcquisitionProperties.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
  source/frontend/src/features/properties/map/research/add/ResearchProperties.test.tsx
  source/frontend/src/features/properties/selector/MapSelectorContainer.tsx
  source/frontend/src/features/properties/selector/components/MapClickMonitor.tsx
  source/frontend/src/features/properties/selector/map/PropertyMapSelectorFormView.tsx
  source/frontend/src/hooks/useDraftMarkerSynchronizer.ts
Labels: bug

#2361 psp-4095 properly support properties with no address in L&L screens.
  source/frontend/src/features/leases/detail/LeaseHeaderAddresses.test.tsx
  source/frontend/src/features/leases/detail/LeaseHeaderAddresses.tsx
  source/frontend/src/features/leases/detail/LeasePages/AddressSubForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/AddressSubForm.tsx
  source/frontend/src/features/leases/detail/styles.ts
Labels: enhancement

#2395 PIMS_LEASE_ACTIVITY_INSTANCE Fix
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/02_PSP_PIMS_S39_00_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S40_00/Alter Up/02_PSP_PIMS_S39_00_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S40_00/Build/002_PSP_PIMS_Build.sql
Labels: db-migration

#2400 PSP-4185 Satellite imagery with labels
  source/frontend/public/basemaps.json
  source/frontend/src/components/maps/BasemapToggle.test.tsx
  source/frontend/src/components/maps/BasemapToggle.tsx
  source/frontend/src/components/maps/__snapshots__/BasemapToggle.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Map.tsx
Labels: enhancement

#2383 Lease Documents | psp 4712
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/DocumentRelationType.cs
  source/backend/api/Services/ActivityService.cs
  source/backend/api/Services/DocumentLeaseService.cs
  source/backend/api/Services/IActivityService.cs
  source/backend/api/Services/IDocumentLeaseService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Constants/ActivityTemplateType.cs
  source/backend/dal/Repositories/ActivityRepository.cs
  source/backend/dal/Repositories/ActivityTemplateRepository.cs
  source/backend/dal/Repositories/Interfaces/IActivityRepository.cs
  source/backend/dal/Repositories/Interfaces/IActivityTemplateRepository.cs
  source/frontend/src/constants/documentRelationshipType.ts
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeaseContainer.tsx
  source/frontend/src/features/leases/detail/LeaseIndex.test.tsx
  source/frontend/src/features/leases/detail/LeaseIndex.tsx
  source/frontend/src/features/leases/detail/LeasePages/documents/DocumentsPage.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/documents/DocumentsPage.tsx
  source/frontend/src/features/leases/detail/LeasePages/documents/__snapshots__/DocumentsPage.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/Insurance.test.tsx
  source/frontend/src/features/leases/detail/LeaseRouter.tsx
  source/frontend/src/features/leases/detail/__snapshots__/LeaseIndex.test.tsx.snap
Labels: enhancement

#2380 psp-4803 ensure address displays in view and edit mode of property se…
  source/frontend/src/components/maps/leaflet/SvgMarkers/DraftMarker.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionProperties.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/properties/map/shared/models.ts
  source/frontend/src/features/properties/map/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/properties/selector/components/__snapshots__/SelectedPropertyRow.test.tsx.snap
Labels: bug

#2367 PSP-4183: BVT: From the Property List view, should be able to select …
  source/frontend/src/features/properties/list/PropertyListView.test.tsx
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  source/frontend/src/features/properties/list/columns.tsx
Labels: enhancement

#2399 Psp 2378 bc assessment tab(s)
  source/backend/geocoder/Extensions/ServiceCollectionExtensions.cs
  source/backend/ltsa/Exceptions/LtsaException.cs
  source/backend/ltsa/LtsaService.cs
  source/backend/tests/unit/dal/Libraries/Ltsa/LtsaExceptionTest.cs
  source/backend/tests/unit/dal/Libraries/Ltsa/LtsaServiceTest.cs
  source/frontend/src/components/Table/MoneyCell.tsx
  source/frontend/src/components/maps/leaflet/mapUtils.tsx
  source/frontend/src/features/account/Login.tsx
  source/frontend/src/features/mapSideBar/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/tabs/bcAssessment/AssessedValuesTable.tsx
  source/frontend/src/features/mapSideBar/tabs/bcAssessment/BcAssessmentTabView.test.tsx
  source/frontend/src/features/mapSideBar/tabs/bcAssessment/BcAssessmentTabView.tsx
  source/frontend/src/features/mapSideBar/tabs/bcAssessment/SalesTable.tsx
  source/frontend/src/features/mapSideBar/tabs/bcAssessment/__snapshots__/BcAssessmentTabView.test.tsx.snap
  source/frontend/src/features/properties/map/propertyInformation/ComposedProperty.ts
  source/frontend/src/features/properties/map/propertyInformation/PropertyContainer.tsx
  source/frontend/src/features/properties/map/shared/detail/PropertyFileContainer.test.tsx
  source/frontend/src/features/properties/map/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/hooks/pims-api/useWfsLayer.ts
  source/frontend/src/hooks/pims-api/wfsAxios.ts
  source/frontend/src/hooks/useBcAssessmentLayer.ts
  source/frontend/src/hooks/useComposedProperties.ts
  source/frontend/src/mocks/bcAssessmentMock.ts
  source/frontend/src/tenants/ITenantConfig.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: enhancement

#2388 PSP-4763: Plan # in pop-up doesn't match plan # in Property Info pane
  source/frontend/src/features/mapSideBar/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  source/frontend/src/hooks/pims-api/useFullyAttributedParcelMapLayer.ts
  source/frontend/src/hooks/useComposedProperties.ts
Labels: bug

#2427 Increment DEV version to IS41
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops, release-management

#2434 HOTFIX: psp-4851 Correct issue with geocoder key not being present in…
  source/backend/api/Pims.Api.csproj
  source/backend/geocoder/Extensions/ServiceCollectionExtensions.cs
  source/frontend/package.json
Labels: bug, hotfix

#2438 Psp 4883-fix white screen when siteminder id invalid.
  source/backend/ltsa/LtsaService.cs
  source/frontend/src/components/layout/Header/ErrorModal.tsx
  source/frontend/src/utils/utils.ts
Labels: bug

#2440 PSP-4855 Property Research - Research Summary section has a different subtitle when in Edit mode
  source/frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.tsx
  source/frontend/src/features/properties/map/research/update/property/__snapshots__/UpdatePropertyForm.test.tsx.snap
Labels: bug

#2443 Psp 4708 - ensure region is populated when creating acq file from the map.
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
Labels: bug

#2441 Psp 4827
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/account/Login.tsx
  source/frontend/src/hooks/usePimsIdleTimer.tsx
  source/frontend/src/layouts/AuthLayout.tsx
  source/frontend/src/tenants/ITenantConfig.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: bug

#2445 Fixed button label | psp-4502
  source/frontend/src/features/admin/document-template/DocumentTemplateManagementView.tsx
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
Labels: bug

#2444 Added documents to the file tabs | psp-4766
  source/backend/api/Areas/Documents/DocumentController.cs
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/DocumentRelationType.cs
  source/backend/api/Services/DocumentActivityService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/Services/IDocumentActivityService.cs
  source/backend/dal/Repositories/DocumentActivityRepository.cs
  source/backend/dal/Repositories/Interfaces/IDocumentActivityRepository.cs
  source/frontend/src/constants/documentRelationshipType.ts
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  source/frontend/src/features/documents/hooks/useDocumentProvider.ts
  source/frontend/src/features/documents/hooks/useDocumentRelationshipProvider.ts
  source/frontend/src/features/documents/list/DocumentFilter/DocumentFilterForm.tsx
  source/frontend/src/features/documents/list/DocumentFilter/__snapshots__/DocumentFilterForm.test.tsx.snap
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/documents/list/DocumentResults/DocumentResultsColumns.tsx
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/documents/__snapshots__/DocumentsPage.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/FileTabs.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.tsx
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  source/frontend/src/features/properties/map/activity/list/ActivityListView.tsx
  source/frontend/src/features/properties/map/research/ResearchTabsContainer.tsx
  source/frontend/src/hooks/pims-api/useApiDocuments.ts
Labels: enhancement

#2453 psp-4929 do not attempt to delete a property if it is in a separate r…
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
  source/frontend/src/hooks/usePimsIdleTimer.tsx
Labels: bug

#2457 PSP-4725 Add highway research layers
  openshift/4.0/templates/app/deploy.yaml
  source/frontend/src/components/maps/leaflet/LayersControl/__snapshots__/LayersControl.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayersControl/data.ts
Labels: enhancement

#2454 Fix automatic pagination not working when the page size is changed an…
  source/frontend/src/components/Table/Table.test.tsx
  source/frontend/src/components/Table/Table.tsx
Labels: bug

#2456 psp-4949 correct display of non-inventory properties.
  source/frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  source/frontend/src/hooks/pims-api/useApiRequestWrapper.ts
  source/frontend/src/hooks/useComposedProperties.ts
Labels: bug

#2455 prevent formik submit from refreshing the page.
  source/frontend/src/features/documents/list/DocumentFilter/DocumentFilterForm.tsx
  source/frontend/src/features/documents/list/DocumentFilter/__snapshots__/DocumentFilterForm.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/documents/__snapshots__/DocumentsPage.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
Labels: bug

#2464 Test to master
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/features/documents/list/DocumentFilter/DocumentFilterForm.tsx
  source/frontend/src/features/documents/list/DocumentFilter/__snapshots__/DocumentFilterForm.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/documents/__snapshots__/DocumentsPage.test.tsx.snap
  source/frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiRequestWrapper.ts
  source/frontend/src/hooks/useComposedProperties.ts
Labels: devops

#2463 Backmerge test to dev
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/geocoder/Extensions/ServiceCollectionExtensions.cs
  source/backend/ltsa/LtsaService.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/Table/Table.test.tsx
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/layout/Header/ErrorModal.tsx
  source/frontend/src/features/account/Login.tsx
  source/frontend/src/features/documents/list/DocumentFilter/DocumentFilterForm.tsx
  source/frontend/src/features/documents/list/DocumentFilter/__snapshots__/DocumentFilterForm.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/documents/__snapshots__/DocumentsPage.test.tsx.snap
  source/frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  source/frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.tsx
  source/frontend/src/features/properties/map/research/update/property/__snapshots__/UpdatePropertyForm.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiRequestWrapper.ts
  source/frontend/src/hooks/useComposedProperties.ts
  source/frontend/src/hooks/usePimsIdleTimer.tsx
  source/frontend/src/layouts/AuthLayout.tsx
  source/frontend/src/tenants/ITenantConfig.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
  source/frontend/src/utils/utils.ts
Labels: devops

#2459 Automation - Research Files, Acquisition, Contacts, Login update
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/PageObjects/Activities.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/Login.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFile.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedNotes.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LoginSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#2477 Increment DEV version to IS42
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2485 HOTFIX: Psp-4999
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  source/frontend/src/hooks/useBcAssessmentLayer.ts
Labels: bug, hotfix
