Repository bcgov/PSP, pull requests merged in 2022-04, with the labels that each got.

#1170 Increment DEV version to IS25
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#1153 Psp 2907
  database/mssql/scripts/dbscripts/PSP_PIMS_S23_01/Test Data/05_DML_LEASE_PROPERTY.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S23_01/Test Data/12_SECURITY_DEPOSIT_RETURN_TEST_DATA.sql
  frontend/src/assets/images/draft-building-icon.svg
  frontend/src/assets/images/draft-parcel-icon.svg
  frontend/src/assets/images/pins/icon-draft.svg
  frontend/src/components/common/GenericModal.tsx
  frontend/src/components/common/RemoveButton.tsx
  frontend/src/components/common/mapping/SelectProperty.tsx
  frontend/src/components/common/styles.ts
  frontend/src/components/contact/ContactManagerModal.tsx
  frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
  frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  frontend/src/components/maps/leaflet/InventoryLayer.tsx
  frontend/src/components/maps/leaflet/Map.test.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/leaflet/PointClusterer.tsx
  frontend/src/components/maps/leaflet/SvgMarkers/DraftMarker.tsx
  frontend/src/components/maps/leaflet/mapUtils.tsx
  frontend/src/components/maps/leaflet/styles.ts
  frontend/src/components/maps/providers/PropertyPopUpProvider.tsx
  frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  frontend/src/features/contacts/contact/create/components/contactInfo/ContactPhone.tsx
  frontend/src/features/contacts/contact/create/styles.ts
  frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  frontend/src/features/mapSideBar/MapPropertySideBarContainer.tsx
  frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.ts
  frontend/src/features/mapSideBar/layout/PropertyInfoLayout.tsx
  frontend/src/features/mapSideBar/tabs/PropertySelectorTabsView.tsx
  frontend/src/features/mapSideBar/tabs/Section.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeOwnerSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaDuplicateTitleSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTransferSubForm.tsx
  frontend/src/features/properties/map/MapView.scss
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/features/properties/selector/MapSelectorContainer.tsx
  frontend/src/features/properties/selector/MapSelectorModalContainer.tsx
  frontend/src/features/properties/selector/components/DraftCircleNumber.tsx
  frontend/src/features/properties/selector/components/MapClickMonitor.tsx
  frontend/src/features/properties/selector/components/SelectedPropertyHeaderRow.tsx
  frontend/src/features/properties/selector/components/SelectedPropertyRow.tsx
  frontend/src/features/properties/selector/layout/PropertySelectorLayout.tsx
  frontend/src/features/properties/selector/tabs/PropertySelectorFormView.tsx
  frontend/src/features/properties/selector/tabs/PropertySelectorSubForm.tsx
  frontend/src/hooks/useDraftMarkerSynchronizer.ts
  frontend/src/interfaces/IProperty.ts
  frontend/src/store/rootReducer.ts
  frontend/src/store/slices/parcelLayerData/parcelLayerDataSlice.ts
  frontend/src/store/slices/properties/index.ts
  frontend/src/store/slices/properties/interfaces/IPropertyState.ts
  frontend/src/store/slices/properties/interfaces/index.ts
  frontend/src/store/slices/properties/propertiesReducer.test.tsx
  frontend/src/store/slices/properties/propertiesSlice.ts
Labels: enhancement

#1182 Unit tests for PSP-2376
  frontend/src/components/maps/leaflet/mapUtils.test.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/propertyAdjacentLandTypes.ts
  frontend/src/constants/propertyTenureTypes.ts
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/mocks/filterDataMock.ts
Labels: unit-tests

#1187 Psp 3151
  frontend/src/components/common/RemoveButton.tsx
  frontend/src/components/common/mapping/SelectProperty.tsx
  frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  frontend/src/features/properties/selector/MapSelectorContainer.test.tsx
  frontend/src/features/properties/selector/MapSelectorContainer.tsx
  frontend/src/features/properties/selector/MapSelectorModalContainer.test.tsx
  frontend/src/features/properties/selector/MapSelectorModalContainer.tsx
  frontend/src/features/properties/selector/PropertySelectorFormView.test.tsx
  frontend/src/features/properties/selector/PropertySelectorFormView.tsx
  frontend/src/features/properties/selector/PropertySelectorSubForm.tsx
  frontend/src/features/properties/selector/__snapshots__/MapSelectorContainer.test.tsx.snap
  frontend/src/features/properties/selector/__snapshots__/MapSelectorModalContainer.test.tsx.snap
  frontend/src/features/properties/selector/__snapshots__/PropertySelectorFormView.test.tsx.snap
  frontend/src/features/properties/selector/components/DraftCircleNumber.tsx
  frontend/src/features/properties/selector/components/MapClickMonitor.tsx
  frontend/src/features/properties/selector/components/SelectedPropertyRow.test.tsx
  frontend/src/features/properties/selector/components/SelectedPropertyRow.tsx
  frontend/src/features/properties/selector/components/__snapshots__/SelectedPropertyRow.test.tsx.snap
Labels: unit-tests

#1174 update lease clear functionality - remove lease subtables before atte…
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj
Labels: etl

#1196 PSP-3188 Fix property information slide-out
  frontend/src/features/mapSideBar/MapSideBarContainer.test.tsx
  frontend/src/features/mapSideBar/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/MapSideBarHeader.test.tsx
  frontend/src/features/mapSideBar/MapSlideBarHeader.tsx
  frontend/src/features/mapSideBar/__snapshots__/MapSideBarHeader.test.tsx.snap
  frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts
  frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.helpers.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: bug

#1201 Map popup fixes
  frontend/src/assets/scss/_variables.module.scss
  frontend/src/assets/scss/colors.scss
  frontend/src/components/common/form/Button.scss
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopup.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/__snapshots__/LayerPopupLinks.test.tsx.snap
  frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
Labels: bug

#1204 Backmerge test to dev
  frontend/src/assets/scss/_variables.module.scss
  frontend/src/assets/scss/colors.scss
  frontend/src/components/common/form/Button.scss
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopup.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.tsx
  frontend/src/components/maps/leaflet/LayerPopup/components/__snapshots__/LayerPopupLinks.test.tsx.snap
  frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
  frontend/src/features/mapSideBar/MapSideBarContainer.test.tsx
  frontend/src/features/mapSideBar/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/MapSideBarHeader.test.tsx
  frontend/src/features/mapSideBar/MapSlideBarHeader.tsx
  frontend/src/features/mapSideBar/__snapshots__/MapSideBarHeader.test.tsx.snap
  frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts
  frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.helpers.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: release-management

#1208 Feature/psp 3119
  frontend/src/features/mapSideBar/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/__snapshots__/MapSideBarHeader.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/SectionStyles.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeOwnerSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaDuplicateTitleSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLandSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLegalNotationsSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTransferSubForm.test.tsx.snap
Labels: bug

#1211 PSP-2910: BVT: Back To Search remove this option
  frontend/src/features/leases/detail/BackToSearchButton.test.tsx
  frontend/src/features/leases/detail/BackToSearchButton.tsx
  frontend/src/features/leases/detail/LeaseContainer.tsx
  frontend/src/features/leases/detail/__snapshots__/BackToSearchButton.test.tsx.snap
  frontend/src/features/leases/detail/__snapshots__/LeaseContainer.test.tsx.snap
  frontend/src/features/leases/index.ts
Labels: frontend

#1215 PSP-2961:BVT: Swap the First Name and Last Name columns for better re…
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
Labels: frontend

#1225 is 25.1 scaffold.
  backend/dal/PIMSContext.cs
  backend/entities/ef/PimsProperty.cs
  backend/entities/ef/PimsPropertyBoundaryVw.cs
  backend/entities/ef/PimsPropertyHist.cs
  backend/entities/ef/PimsPropertyLocationVw.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/05_DML_LEASE_PROPERTY.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_01/Test Data/05_DML_LEASE_PROPERTY.sql
Labels: db-scaffold

#1227 PSP-3114:Remove Excel converter tool
  tools/converters/excel/.editorconfig
  tools/converters/excel/.gitignore
  tools/converters/excel/Configuration/ActionArgumentOptions.cs
  tools/converters/excel/Configuration/ActionOptions.cs
  tools/converters/excel/Configuration/ColumnOptions.cs
  tools/converters/excel/Configuration/ConvertWhenOption.cs
  tools/converters/excel/Configuration/ConverterOptions.cs
  tools/converters/excel/Configuration/GeocoderOptions.cs
  tools/converters/excel/Configuration/RowOptions.cs
  tools/converters/excel/Configuration/SkipOption.cs
  tools/converters/excel/Configuration/SourceOptions.cs
  tools/converters/excel/Configuration/ValueSwitchOptions.cs
  tools/converters/excel/Converter.cs
  tools/converters/excel/Converters/GeoLocationConverter.cs
  tools/converters/excel/Converters/IGeoLocationConverter.cs
  tools/converters/excel/Converters/StringConverters.cs
  tools/converters/excel/Extensions/TypeExtensions.cs
  tools/converters/excel/IConverter.cs
  tools/converters/excel/Makefile
  tools/converters/excel/Models/AddressModel.cs
  tools/converters/excel/Models/AddressModelMap.cs
  tools/converters/excel/Pims.Tools.Converters.ExcelConverter.csproj
  tools/converters/excel/Pims.Tools.Converters.ExcelConverter.sln
  tools/converters/excel/Program.cs
  tools/converters/excel/README.md
  tools/converters/excel/Startup.cs
  tools/converters/excel/appsettings.Development.json
  tools/converters/excel/appsettings.Local.json
  tools/converters/excel/appsettings.Production.json
  tools/converters/excel/appsettings.Test.json
  tools/converters/excel/appsettings.json
Labels: tech-debt

#1218 psp-3194 add zoom button to property info sidebar header.
  frontend/src/components/common/form/__snapshots__/NotesModal.test.tsx.snap
  frontend/src/components/common/styles.ts
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  frontend/src/features/mapSideBar/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/MapSideBarHeader.test.tsx
  frontend/src/features/mapSideBar/MapSlideBarHeader.tsx
  frontend/src/features/mapSideBar/__snapshots__/MapSideBarHeader.test.tsx.snap
  frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: bug

#1231 PSP-2919 Property Details - NON-INVENTORY
  backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopup.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/features/mapSideBar/MapSideBarContainer.test.tsx
  frontend/src/features/mapSideBar/MapSideBarContainer.tsx
  frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.ts
  frontend/src/features/mapSideBar/tabs/InventoryTabs.tsx
Labels: enhancement

#1226 PSP-3086: Contact modal default to 5 items
  frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
Labels: bug

#1246 Backmerge test to dev
  frontend/src/components/common/form/__snapshots__/NotesModal.test.tsx.snap
  frontend/src/components/common/styles.ts
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  frontend/src/features/mapSideBar/MotiInventoryContainer.test.tsx
  frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  frontend/src/features/mapSideBar/MotiInventoryHeader.test.tsx
  frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  frontend/src/features/mapSideBar/__snapshots__/MotiInventoryHeader.test.tsx.snap
  frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.tsx
  frontend/src/features/properties/map/MapView.tsx
Labels: db-migration

#1250 update npm dependencies based on production audit, dependabot
  frontend/package-lock.json
  frontend/package.json
Labels: db-migration

#1256 Test
  database/mssql/scripts/dbscripts/PSP_PIMS_S24_00/Alter Up/01_PSP_PIMS_S23_01_Alter_Up.sql
Labels: bug, db-migration

#1258 Remove duplicate test data files, likely added inadvertently.
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/07_DML_PROPERTY_LEASE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/08_CONTACTS_ORGANIZATION_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/09_CONTACTS_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/10_INSURANCE_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/11_LEASE_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/12_SECURITY_DEPOSIT_RETURN_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/12_SECURITY_DEPOSIT_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/13_SURPLUS_DECLARATION_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/15_SURPLUS_DECLERATION_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/16_TENANT_TEST_DATA.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/17_DML_LEASE_PROPERTY_TENURE_TYPE.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Test Data/18_SECURITY_DEPOSIT_RETURN_HOLDER_TEST_DATA.sql
Labels: bug, db-migration

#1266 Db backmerge test
  backend/api/Pims.Api.csproj
  database/mssql/scripts/dbscripts/PSP_PIMS_S24_00/Alter Up/01_PSP_PIMS_S23_01_Alter_Up.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_00/Alter Up/01_PSP_PIMS_S24_00_Alter_Up.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_01/Alter Down/20_PIMS_PROPERTY_BOUNDARY_VW.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_01/Alter Down/21_PIMS_PROPERTY_LOCATION_VW.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_01/Alter Up/20_PIMS_PROPERTY_BOUNDARY_VW.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_01/Alter Up/21_PIMS_PROPERTY_LOCATION_VW.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_01/Build/02_PSP_PIMS_S25_01_Build.sql
  frontend/package.json
Labels: db-migration, alignment

#1269 Increment DEV version to IS26
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#1263 PSP-3176: PRD: User Access Request screen opens external links in a n…
  frontend/src/features/admin/access-request/AccessRequestPage.tsx
  frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.test.tsx.snap
Labels: frontend

#1281 PSP-3225:Make ltsa charges collapseable
  frontend/src/features/mapSideBar/__snapshots__/MotiInventoryHeader.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/SectionStyles.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeOwnerSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaDuplicateTitleSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLandSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLegalNotationsSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTransferSubForm.test.tsx.snap
Labels: frontend

#1288 psp-3227 fix satellite basemap swap behaviour.
  frontend/src/components/maps/leaflet/Map.tsx
Labels: bug

#1289 psp-3254 allow other unit types besides hectares to be selected.
  backend/api/Areas/Leases/Mapping/Lease/PropertyMap.cs
  backend/api/Areas/Leases/Models/Lease/PropertyModel.cs
  backend/dal/Repositories/LeaseRepository.cs
  backend/tests/unit/api/Controllers/Leases/LeaseControllerTest.cs
  frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  frontend/src/features/leases/add/PropertyRow.tsx
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/PropertyInformationSubForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.test.tsx
  frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.test.tsx
  frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
  frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.tsx
  frontend/src/features/leases/leaseUtils.ts
  frontend/src/interfaces/ILease.ts
  frontend/src/interfaces/IProperty.ts
  frontend/src/pages/TestFileManagement.tsx
Labels: bug

#1301 psp-3164 correct unhandled pid(s) within ltsa.
  backend/ltsa/LtsaService.cs
  backend/ltsa/Models/AssociatedPlan.cs
  backend/ltsa/Models/BillingInfo.cs
  backend/ltsa/Models/CanadianProvince.cs
  backend/ltsa/Models/ChargeOnTitle.cs
  backend/ltsa/Models/ChargeOwnershipGroup.cs
  backend/ltsa/Models/ChargesOnStrataCommonProperty.cs
  backend/ltsa/Models/DescriptionOfLand.cs
  backend/ltsa/Models/DocOrPlanSummary.cs
  backend/ltsa/Models/LandTitleDistrict.cs
  backend/ltsa/Models/LandTitleDistrictCode.cs
  backend/ltsa/Models/LegalNotationsOnStrataCommonProperty.cs
  backend/ltsa/Models/OrderParent.cs
  backend/ltsa/Models/OrderStatus.cs
  backend/ltsa/Models/OwnerAddress.cs
  backend/ltsa/Models/ParcelInfo.cs
  backend/ltsa/Models/Title.cs
  backend/ltsa/Models/TitleSummary.cs
  backend/ltsa/Pims.Ltsa.csproj
Labels: bug

#1299 psp-3288 do not allow duplicate draft map markers.
  frontend/src/features/properties/map/research/add/ResearchProperties.tsx
Labels: bug

#1298 correct issue with pims_property sequence not being set by paims etl.
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_01/Alter Up/89_DML_PIMS_PROPERTY_ID_SEQ.sql
  frontend/src/features/properties/map/research/add/AddResearchFileYupSchema.ts
Labels: bug

#1297 psp-3280 enforce order of address fields on contact view screens.
  frontend/src/features/contacts/contact/detail/Organization.test.tsx
  frontend/src/features/contacts/contact/detail/Organization.tsx
  frontend/src/features/contacts/contact/detail/Person.test.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
  frontend/src/features/contacts/contact/detail/utils.ts
Labels: bug

#1310 Psp 3253 prevent lease tenants from being created with org and person information
  backend/api/Areas/Leases/Mapping/Lease/TenantMap.cs
  backend/entities/Lease.cs
  frontend/src/features/leases/context/LeaseContext.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  frontend/src/features/leases/leaseUtils.ts
  frontend/src/hooks/pims-api/useApiRequestWrapper.ts
  frontend/src/interfaces/ITenant.ts
Labels: bug

#1317 Backmerge test to dev
  backend/api/Areas/Research/Models/ResearchFilterModel.cs
  backend/ltsa/LtsaService.cs
  backend/ltsa/Models/AssociatedPlan.cs
  backend/ltsa/Models/BillingInfo.cs
  backend/ltsa/Models/CanadianProvince.cs
  backend/ltsa/Models/ChargeOnTitle.cs
  backend/ltsa/Models/ChargeOwnershipGroup.cs
  backend/ltsa/Models/ChargesOnStrataCommonProperty.cs
  backend/ltsa/Models/DescriptionOfLand.cs
  backend/ltsa/Models/DocOrPlanSummary.cs
  backend/ltsa/Models/LandTitleDistrict.cs
  backend/ltsa/Models/LandTitleDistrictCode.cs
  backend/ltsa/Models/LegalNotationsOnStrataCommonProperty.cs
  backend/ltsa/Models/OrderParent.cs
  backend/ltsa/Models/OrderStatus.cs
  backend/ltsa/Models/OwnerAddress.cs
  backend/ltsa/Models/ParcelInfo.cs
  backend/ltsa/Models/Title.cs
  backend/ltsa/Models/TitleSummary.cs
  backend/ltsa/Pims.Ltsa.csproj
  database/mssql/scripts/dbscripts/PSP_PIMS_S25_01/Alter Up/89_DML_PIMS_PROPERTY_ID_SEQ.sql
  frontend/src/features/properties/map/research/add/AddResearchFileYupSchema.ts
  frontend/src/features/properties/map/research/add/ResearchProperties.tsx
Labels: release-management

#1314 prevent NPE when property address is null.
  frontend/src/features/contacts/contactUtils.ts
  frontend/src/features/properties/list/columns.tsx
Labels: enhancement

#1265 Psp-3229 create a research file via link
  frontend/src/AppRouter.tsx
  frontend/src/assets/images/chooser-marker.svg
  frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  frontend/src/components/maps/leaflet/InventoryLayer.tsx
  frontend/src/components/maps/leaflet/LayerPopup/LayerPopup.tsx
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.test.tsx
  frontend/src/components/maps/leaflet/Map.test.tsx
  frontend/src/components/maps/leaflet/Map.tsx
  frontend/src/components/maps/providers/SelectedPropertyContext.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/projectStatusTypes.ts
  frontend/src/features/properties/list/index.ts
  frontend/src/features/properties/list/interfaces/IFlatProperty.ts
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/features/properties/map/research/add/AddResearchContainer.test.tsx
  frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
  frontend/src/features/properties/map/research/add/ResearchProperties.test.tsx
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/list/ResearchListView.tsx
  frontend/src/features/properties/selector/PropertySelectorSubForm.test.tsx
  frontend/src/features/properties/selector/components/MapClickMonitor.tsx
  frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.tsx
  frontend/src/hooks/useDraftMarkerSynchronizer.ts
  frontend/src/interfaces/IParentParcel.ts
  frontend/src/interfaces/IProject.ts
  frontend/src/interfaces/IProjectActivity.ts
  frontend/src/interfaces/IProperty.ts
  frontend/src/interfaces/IPropertyEvaluation.ts
  frontend/src/interfaces/IPropertyServiceFile.ts
  frontend/src/interfaces/index.ts
  frontend/src/mocks/filterDataMock.ts
  frontend/src/router.test.tsx
  frontend/src/store/rootReducer.ts
  frontend/src/store/slices/parcelLayerData/parcelLayerDataSlice.ts
  frontend/src/store/slices/properties/index.ts
  frontend/src/store/slices/properties/interfaces/IPropertyState.ts
  frontend/src/store/slices/properties/interfaces/index.ts
  frontend/src/store/slices/properties/propertiesReducer.test.tsx
  frontend/src/store/slices/properties/propertiesSlice.ts
  frontend/src/utils/getCurrentFiscal.ts
  frontend/src/utils/getCurrentYearEvaluation.ts
  frontend/src/utils/getMostRecentAppraisal.ts
  frontend/src/utils/getMostRecentEvaluation.ts
  frontend/src/utils/index.ts
  frontend/src/utils/propertyUtils.test.ts
  frontend/src/utils/utils.test.ts
Labels: enhancement

#1329 Backmerge master into test
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj
Labels: release-management

#1337 Increment DEV to IS27
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#1343 Scaffold for s27
  backend/dal/PIMSContext.cs
  backend/entities/ef/PimsLease.cs
  backend/entities/ef/PimsLeaseHist.cs
  backend/entities/ef/PimsLeaseTenant.cs
  backend/entities/ef/PimsLeaseTenantHist.cs
  backend/entities/ef/PimsPerson.cs
  backend/entities/ef/PimsResearchFilePurpose.cs
  backend/entities/ef/PimsResearchFilePurposeHist.cs
  backend/entities/ef/PimsSecurityDepositReturn.cs
  backend/entities/ef/PimsSecurityDepositReturnHist.cs
Labels: db-scaffold

#1331 update the "area" label on the edit/view lease screens to display "Le…
  frontend/src/features/leases/add/PropertyInformationSubForm.test.tsx
  frontend/src/features/leases/add/PropertyRow.tsx
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/add/__snapshots__/PropertyInformationSubForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
Labels: enhancement
