Repository bcgov/PSP, pull requests merged in 2022-05, with the labels that each got.

#1346 psp-3302 address duplicate code warnings from sonarqube on frontend.
  frontend/src/components/maps/leaflet/SvgMarkers/DraftMarker.tsx
  frontend/src/features/contacts/contact/Organization/OrganizationSubForm.tsx
  frontend/src/features/contacts/contact/Person/PersonSubForm.tsx
  frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.tsx
  frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/Person/CreatePersonForm.tsx
  frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  frontend/src/features/contacts/contact/detail/ContactInfoSubForm.tsx
  frontend/src/features/contacts/contact/detail/Organization.test.tsx
  frontend/src/features/contacts/contact/detail/Organization.tsx
  frontend/src/features/contacts/contact/detail/Person.tsx
  frontend/src/features/contacts/contact/detail/utils.ts
  frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.tsx
  frontend/src/features/contacts/contact/utils/contactUtils.ts
  frontend/src/features/contacts/hooks/usePersonOrganizationTypeahead.ts
  frontend/src/features/contacts/hooks/useUpdateContact.ts
  frontend/src/features/contacts/interfaces.ts
  frontend/src/features/leases/detail/LeasePages/deposits/hooks/useDeposits.tsx
  frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.test.tsx
  frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.tsx
  frontend/src/features/leases/reports/aggregated/__snapshots__/ExportAggregatedLeasesContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/SelectedPropertyRow.test.tsx.snap
  frontend/src/features/properties/map/research/detail/DetailResearchContainer.tsx
  frontend/src/features/properties/map/research/hooks/useAddResearch.ts
  frontend/src/features/properties/map/research/hooks/useGetResearch.ts
  frontend/src/features/properties/map/research/hooks/useUpdateResearch.ts
  frontend/src/features/properties/selector/components/DraftCircleNumber.tsx
  frontend/src/hooks/pims-api/useApiRequestWrapper.ts
  frontend/src/interfaces/IContact.ts
  frontend/src/store/slices/users/useUsers.ts
  frontend/src/utils/utils.ts
Labels: tech-debt

#1349 PSP-3296: Fix UI to show 0 at the 1/100th place
  frontend/src/components/common/form/FastCurrencyInput.tsx
  frontend/src/features/leases/detail/LeasePages/details/DetailTerms.test.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/edit/EditContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/edit/__snapshots__/EditContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentForm.test.tsx
Labels: bug

#1356 feat(PSP-3157): Changes
  frontend/src/features/mapSideBar/MotiInventoryContainer.test.tsx
  frontend/src/features/mapSideBar/__snapshots__/MotiInventoryHeader.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaLandSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaLegalNotationsSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeOwnerSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaDuplicateTitleSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLandSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLegalNotationsSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaOwnershipInformationForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaOwnershipInformationTitleOwnerForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTransferSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/__snapshots__/PropertyDetailsTabView.test.tsx.snap
Labels: frontend

#1354 Feature/3072
  backend/api/Models/Concepts/Deposit/SecurityDepositReturnMap.cs
  backend/api/Models/Concepts/Deposit/SecurityDepositReturnModel.cs
  frontend/src/components/common/form/FastCurrencyInput.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/__snapshots__/DepositsReceivedContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/DepositsReturnedContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/__snapshots__/DepositsReturnedContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositYupSchema.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnedDepositModal.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/models/FormLeaseDepositReturn.ts
  frontend/src/models/api/SecurityDeposit.ts
Labels: enhancement

#1361 Psp 3296
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__mocks__/react-text-mask.tsx
  frontend/src/components/common/form/FastCurrencyInput.tsx
  frontend/src/components/common/form/__snapshots__/FastCurrencyInput.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/__snapshots__/DepositsReceivedContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/__snapshots__/DepositsReturnedContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/__snapshots__/ReceivedDepositForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/DetailTerms.test.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/insurance/edit/EditContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/edit/__snapshots__/EditContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/hooks/useCalculateActualGst.tsx
  frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentModal.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/modal/payment/__snapshots__/PaymentForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/modal/term/__snapshots__/TermForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/table/payments/PaymentsForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/__snapshots__/TermsForm.test.tsx.snap
  frontend/src/features/properties/map/research/detail/DetailResearchContainer.tsx
  frontend/src/utils/numberFormatUtils.ts
  frontend/src/utils/test-utils.tsx
Labels: bug

#1366 use the guid instead of the business identifier to id users.
  tools/keycloak/sync/SyncFactory.cs
Labels: bug

#1369 prevent circular references in the research file.
  backend/api/Models/Concepts/ResearchFile/ResearchFileMap.cs
  frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.test.tsx
  frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.tsx
  frontend/src/features/leases/reports/aggregated/__snapshots__/ExportAggregatedLeasesContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
Labels: bug

#1370 remove duplicated code.
  frontend/src/components/maps/leaflet/SvgMarkers/DraftMarker.tsx
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/SelectedPropertyRow.test.tsx.snap
Labels: bug

#1362 ensure that the cursor is reset when no longer selecting properties.
  frontend/src/features/properties/selector/MapSelectorContainer.tsx
Labels: bug

#1380 Update Research property | Features/psp 2941
  backend/api/Areas/Research/Controllers/ResearchFileController.cs
  backend/api/Controllers/LookupController.cs
  backend/dal/Helpers/Extensions/EntityExtensions.cs
  backend/dal/Repositories/Interfaces/ILookupService.cs
  backend/dal/Repositories/Interfaces/IResearchFileRepository.cs
  backend/dal/Repositories/LookupService.cs
  backend/dal/Repositories/ResearchFileRepository.cs
  backend/dal/Services/Interfaces/IResearchFileService.cs
  backend/dal/Services/LeaseService.cs
  backend/dal/Services/ResearchFileService.cs
  backend/entities/PropertyResearchPurposeType.cs
  backend/entities/ResearchFile.cs
  backend/entities/ResearchFilePropertyPurpose.cs
  backend/entities/ResearchPurposeType.cs
  frontend/package-lock.json
  frontend/src/constants/API.ts
  frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.tsx
  frontend/src/features/mapSideBar/tabs/propertyResearch/PropertyResearchTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyResearch/PropertyResearchTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyResearch/__snapshots__/PropertyResearchTabView.test.tsx.snap
  frontend/src/features/properties/map/research/ResearchContainer.tsx
  frontend/src/features/properties/map/research/ViewSelector.tsx
  frontend/src/features/properties/map/research/common/ResearchMenu.test.tsx
  frontend/src/features/properties/map/research/common/ResearchMenu.tsx
  frontend/src/features/properties/map/research/detail/DetailViewSelector.tsx
  frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
  frontend/src/features/properties/map/research/detail/ResearchSummaryView.test.tsx
  frontend/src/features/properties/map/research/detail/ResearchSummaryView.tsx
  frontend/src/features/properties/map/research/detail/__snapshots__/ResearchSummaryView.test.tsx.snap
  frontend/src/features/properties/map/research/hooks/useUpdatePropertyResearch.ts
  frontend/src/features/properties/map/research/update/UpdateResearchContainer.tsx
  frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.test.tsx
  frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.tsx
  frontend/src/features/properties/map/research/update/property/UpdatePropertyView.tsx
  frontend/src/features/properties/map/research/update/property/__snapshots__/UpdatePropertyForm.test.tsx.snap
  frontend/src/features/properties/map/research/update/property/models.ts
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.test.tsx
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.tsx
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryView.tsx
  frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  frontend/src/features/properties/map/research/update/summary/models.ts
  frontend/src/hooks/pims-api/useApiResearchFile.ts
  frontend/src/models/api/PropertyResearchFile.ts
  frontend/src/models/api/ResearchFile.ts
Labels: enhancement

#1382 Psp 3119 - correct spelling error.
  frontend/src/features/mapSideBar/__snapshots__/MotiInventoryHeader.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeOwnerSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaDuplicateTitleSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLandSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLegalNotationsSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaOwnershipInformationForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaOwnershipInformationTitleOwnerForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTransferSubForm.test.tsx.snap
Labels: bug

#1390 BackMerge test to dev
  backend/api/Models/Concepts/ResearchFile/ResearchFileMap.cs
  frontend/src/features/mapSideBar/__snapshots__/MotiInventoryHeader.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeOwnerSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaDuplicateTitleSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLandSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLegalNotationsSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaOwnershipInformationForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaOwnershipInformationTitleOwnerForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTransferSubForm.test.tsx.snap
  frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
  frontend/src/features/properties/selector/MapSelectorContainer.tsx
Labels: devops

#1379 Psp 3274 - fix need for unsafe hashes for draft markers.
  frontend/src/components/maps/leaflet/SvgMarkers/DraftMarker.tsx
  frontend/src/components/maps/leaflet/mapUtils.tsx
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/SelectedPropertyRow.test.tsx.snap
Labels: enhancement

#1364 add notification to general channel to add visibility to build failures.
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
Labels: enhancement, devops

#1398 Fixed R-file number generation and wired purpose
  backend/dal/Repositories/ResearchFileRepository.cs
  frontend/src/features/properties/map/research/update/summary/models.ts
Labels: bug

#1355 Psp 3222 organization tenant primary contact
  backend/api/Areas/Contacts/Mapping/Search/ContactSummaryMap.cs
  backend/api/Areas/Contacts/Models/Search/ContactSummaryModel.cs
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Mapping/Lease/OrganizationMap.cs
  backend/api/Areas/Leases/Mapping/Lease/TenantMap.cs
  backend/api/Areas/Leases/Models/Lease/OrganizationModel.cs
  backend/api/Areas/Leases/Models/Lease/TenantModel.cs
  backend/api/Models/Concepts/Organization/OrganizationPersonMap.cs
  backend/api/Models/Concepts/Organization/OrganizationPersonModel.cs
  backend/dal/Helpers/Extensions/ContactExtensions.cs
  backend/dal/Repositories/ContactRepository.cs
  backend/dal/Repositories/ContactService.cs
  backend/dal/Repositories/Interfaces/IContactRepository.cs
  backend/dal/Repositories/LeaseRepository.cs
  backend/dal/Services/ContactService.cs
  backend/dal/Services/Interfaces/IContactService.cs
  backend/entities/Contact.cs
  frontend/src/components/Table/Table.tsx
  frontend/src/components/common/GenericModal.tsx
  frontend/src/components/common/form/Select.tsx
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/summaryColumns.tsx
  frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  frontend/src/components/maps/leaflet/PointClusterer.tsx
  frontend/src/components/maps/leaflet/mapUtils.test.tsx
  frontend/src/features/contacts/contactUtils.ts
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/PrimaryContactWarningModal.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/TenantOrganizationContactInfo.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/TenantPersonContactInfo.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/columns.tsx
  frontend/src/features/leases/leaseUtils.ts
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/interfaces/IAddress.ts
  frontend/src/interfaces/IContactSearchResult.ts
  frontend/src/interfaces/ILease.ts
  frontend/src/interfaces/ILeasePayment.ts
  frontend/src/interfaces/ILeaseTerm.ts
  frontend/src/interfaces/ISelectedTenant.ts
  frontend/src/mocks/filterDataMock.ts
  frontend/src/models/api/ContactMethod.ts
  frontend/src/models/api/LeaseTenant.ts
  frontend/src/models/api/Organization.ts
  frontend/src/utils/contactMethodUtil.ts
Labels: enhancement

#1371 psp-3415
  frontend/src/features/mapSideBar/MotiInventoryContainer.test.tsx
  frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  frontend/src/features/mapSideBar/MotiInventoryHeader.test.tsx
  frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  frontend/src/features/mapSideBar/__snapshots__/MotiInventoryHeader.test.tsx.snap
  frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  frontend/src/features/mapSideBar/tabs/InventoryTabs.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeOwnerSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaDuplicateTitleSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaLandSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaLegalNotationsSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaOwnershipInformationForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaOwnershipInformationTitleOwnerForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaOwnershipInformationTitleOwnerForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTransferSubForm.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeOwnerSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaDuplicateTitleSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLandSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLegalNotationsSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaOwnershipInformationForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaOwnershipInformationTitleOwnerForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTransferSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/PropertyDetailsTabView.tsx
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
  frontend/src/hooks/pims-api/useApiRequestWrapper.ts
  frontend/src/hooks/useLtsa.ts
  frontend/src/hooks/useProperties.test.tsx
  frontend/src/hooks/useProperties.ts
  frontend/src/mocks/filterDataMock.ts
  frontend/src/utils/utils.ts
Labels: bug

#1412 Increment DEV version to IS28
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#1421 Correct LISDB etl.
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
Labels: etl

#1428 Property associations | Features/psp 3217
  backend/api/Areas/Property/Controllers/PropertyController.cs
  backend/api/Areas/Property/Mapping/Property/AssociationMap.cs
  backend/api/Areas/Property/Models/Property/AssociationModel.cs
  backend/api/Areas/Property/Models/Property/PropertyAssociationModel.cs
  backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  backend/dal/Repositories/PropertyRepository.cs
  frontend/package-lock.json
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.tsx
  frontend/src/features/mapSideBar/MotiInventoryContainer.tsx
  frontend/src/features/mapSideBar/MotiInventoryHeader.tsx
  frontend/src/features/mapSideBar/__snapshots__/MotiInventoryHeader.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/InventoryTabs.tsx
  frontend/src/features/mapSideBar/tabs/Section.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaDuplicateTitleSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaLandSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaOwnershipInformationForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTransferSubForm.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaChargeSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaDuplicateTitleSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLandSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaOwnershipInformationForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTransferSubForm.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyAssociations/AssociationContent.tsx
  frontend/src/features/mapSideBar/tabs/propertyAssociations/AssociationHeader.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyAssociations/AssociationHeader.tsx
  frontend/src/features/mapSideBar/tabs/propertyAssociations/PropertyAssociationTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyAssociations/__snapshots__/AssociationHeader.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyDetails/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  frontend/src/features/mapSideBar/tabs/propertyResearch/PropertyResearchTabView.tsx
  frontend/src/features/mapSideBar/tabs/propertyResearch/__snapshots__/PropertyResearchTabView.test.tsx.snap
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
  frontend/src/features/properties/map/research/add/ResearchProperties.tsx
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
  frontend/src/features/properties/map/research/detail/ResearchSummaryView.tsx
  frontend/src/features/properties/map/research/detail/__snapshots__/ResearchSummaryView.test.tsx.snap
  frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.tsx
  frontend/src/features/properties/map/research/update/property/__snapshots__/UpdatePropertyForm.test.tsx.snap
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.tsx
  frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  frontend/src/hooks/pims-api/useApiProperties.ts
  frontend/src/hooks/usePropertyAssociations.ts
  frontend/src/models/api/Property.ts
Labels: enhancement

#1425 feat(PSP-3133): Changes to add the Physical lease/license exists, Dig…
  backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  frontend/src/features/leases/add/AddLeaseYupSchema.ts
  frontend/src/features/leases/add/ReferenceSubForm.tsx
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.test.tsx
  frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
  frontend/src/features/leases/leaseUtils.ts
  frontend/src/interfaces/ILease.ts
  frontend/src/utils/formUtils.ts
Labels: enhancement

#1437 feat(PSP-3379):Update Research File - Header Behaviour
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.test.tsx
  frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.tsx
  frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
Labels: frontend

#1444 Fix Property Research not updating | psp 3474
  backend/dal/Repositories/ResearchFileRepository.cs
  frontend/src/features/properties/map/research/ViewSelector.tsx
Labels: bug

#1446 PSP-3383 Add Region and District to properties in research file
  backend/dal/Repositories/ResearchFileRepository.cs
  backend/dal/Services/ResearchFileService.cs
  frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
  frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
  frontend/src/constants/districtCodes.ts
  frontend/src/constants/index.ts
  frontend/src/constants/regionCodes.ts
  frontend/src/features/properties/map/MapView.test.tsx
  frontend/src/features/properties/map/research/add/AddResearchContainer.test.tsx
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/research/add/models.ts
  frontend/src/features/properties/selector/PropertySelectorSubForm.test.tsx
  frontend/src/features/properties/selector/PropertySelectorSubForm.tsx
  frontend/src/features/properties/selector/__snapshots__/PropertySelectorSubForm.test.tsx.snap
  frontend/src/features/properties/selector/components/MapClickMonitor.tsx
  frontend/src/features/properties/selector/models.ts
Labels: enhancement

#1431 Psp 3422
  frontend/src/assets/images/pins/icon-draft.svg
  frontend/src/components/maps/leaflet/SvgMarkers/DraftMarker.tsx
  frontend/src/components/maps/leaflet/mapUtils.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/SelectedPropertyRow.test.tsx.snap
Labels: bug

#1438 limit sonarqube scan, failure notification to runs within bcgov repo …
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
Labels: devops

#1452 Bugs/psp 3511
  frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.tsx
  frontend/src/features/properties/map/research/update/property/__snapshots__/UpdatePropertyForm.test.tsx.snap
Labels: bug

#1453 Updated research filename showing on PIMS files
  backend/api/Areas/Property/Mapping/Property/AssociationMap.cs
Labels: bug

#1449 Ensure that psp-3510 correct error message is displayed if non-exista…
  backend/dal/Repositories/LeaseRepository.cs
  backend/tests/unit/dal/Repositories/LeaseServiceTest.cs
Labels: bug

#1454 feat(PSP-3230): Changes to enable sorting on the Lease Result table
  backend/dal/Helpers/Extensions/LeaseExtensions.cs
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.test.tsx
  frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
Labels: enhancement

#1430 psp-3067 allow users to search for properties in the property selecto…
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SearchBar/__snapshots__/FilterBar.test.tsx.snap
  frontend/src/components/Table/Table.tsx
  frontend/src/components/common/TabView.tsx
  frontend/src/components/common/buttons/ResetButton.tsx
  frontend/src/components/common/buttons/SearchButton.tsx
  frontend/src/components/contact/ContactManagerView/ContactFilterComponent/__snapshots__/ContactFilterComponent.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
  frontend/src/components/maps/leaflet/PointClusterer.tsx
  frontend/src/components/maps/leaflet/mapUtils.tsx
  frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
  frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
  frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/features/properties/map/research/add/ResearchProperties.tsx
  frontend/src/features/properties/map/research/add/SelectedPropertyRow.test.tsx
  frontend/src/features/properties/map/research/add/SelectedPropertyRow.tsx
  frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  frontend/src/features/properties/selector/MapSelectorContainer.test.tsx
  frontend/src/features/properties/selector/MapSelectorContainer.tsx
  frontend/src/features/properties/selector/PropertySelectorTabsView.tsx
  frontend/src/features/properties/selector/__snapshots__/MapSelectorContainer.test.tsx.snap
  frontend/src/features/properties/selector/map/PropertyMapSelectorFormView.tsx
  frontend/src/features/properties/selector/map/PropertyMapSelectorSubForm.test.tsx
  frontend/src/features/properties/selector/map/PropertyMapSelectorSubForm.tsx
  frontend/src/features/properties/selector/map/__snapshots__/PropertyMapSelectorSubForm.test.tsx.snap
  frontend/src/features/properties/selector/models.ts
  frontend/src/features/properties/selector/search/LayerFilter.tsx
  frontend/src/features/properties/selector/search/PropertySearchSelectorFormView.test.tsx
  frontend/src/features/properties/selector/search/PropertySearchSelectorFormView.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.test.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.tsx
  frontend/src/features/properties/selector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap
  frontend/src/features/properties/selector/search/mapPropertyColumns.ts
  frontend/src/features/properties/selector/utils.ts
  frontend/src/features/research/list/ResearchFilter/__snapshots__/ResearchFilter.test.tsx.snap
  frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  frontend/src/mocks/filterDataMock.ts
Labels: enhancement

#1471 Increment DEV version - IS29
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: devops, release-management
