Repository bcgov/PSP, pull requests merged in 2022-08, with the labels that each got.

#1815 Psp 3974 - correct tenants being removed. Add unmerged unit tests for primary contact.
  backend/dal/Repositories/ContactRepository.cs
  frontend/src/components/common/GenericModal.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/PrimaryContactWarningModal.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/PrimaryContactWarningModal.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/TenantOrganizationContactInfo.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/PrimaryContactWarningModal.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/columns.tsx
  frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap
  frontend/src/features/notes/list/NoteResults/NoteResults.test.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.test.tsx
  frontend/src/interfaces/IOrganization.ts
  frontend/src/interfaces/IProperty.ts
  frontend/src/mocks/mockLease.ts
  frontend/src/mocks/mockOrganization.ts
  frontend/src/models/api/LeaseTenant.ts
Labels: bug

#1816 Psp 3964 unable to delete a property on a research file
  backend/dal/Repositories/ResearchFilePropertyRepository.cs
  backend/tests/unit/dal/Repositories/ResearchFilePropertyRepositoryTest.cs
  backend/tests/unit/dal/Services/ResearchServiceTest.cs
Labels: bug

#1819 PSP-3659 BUGFIX - pagination details not updating after filtering
  frontend/src/components/Table/Table.tsx
  frontend/src/components/common/form/TableSelect.tsx
Labels: bug

#1827 PSP-4034 BUGFIX - Show confirmation on cancel for Add Notes
  frontend/src/features/notes/add/AddNotesContainer.test.tsx
  frontend/src/features/notes/add/AddNotesContainer.tsx
  frontend/src/features/notes/add/AddNotesFormModal.test.tsx
  frontend/src/features/notes/add/AddNotesFormModal.tsx
  frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  frontend/src/features/notes/update/UpdateNoteContainer.tsx
  frontend/src/features/notes/update/UpdateNoteFormModal.tsx
Labels: bug

#1833 fix overwritten build scripts.
  database/mssql/scripts/dbscripts/PSP_PIMS_S33_00/Build/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S33_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
Labels: db-migration

#1836 Add Pryanka to codeowners
  .github/CODEOWNERS
Labels: alignment

#1832 Backmerge TEST into DEV
  backend/dal/Repositories/ContactRepository.cs
  backend/dal/Repositories/ResearchFilePropertyRepository.cs
  backend/tests/unit/dal/Repositories/ResearchFilePropertyRepositoryTest.cs
  backend/tests/unit/dal/Services/ResearchServiceTest.cs
  frontend/src/components/Table/Table.tsx
  frontend/src/components/common/GenericModal.tsx
  frontend/src/components/common/form/TableSelect.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/PrimaryContactWarningModal.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/PrimaryContactWarningModal.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/TenantOrganizationContactInfo.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/PrimaryContactWarningModal.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/tenant/columns.tsx
  frontend/src/features/notes/NoteContainer.test.tsx
  frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  frontend/src/features/notes/add/AddNotesContainer.test.tsx
  frontend/src/features/notes/add/AddNotesContainer.tsx
  frontend/src/features/notes/add/AddNotesFormModal.test.tsx
  frontend/src/features/notes/add/AddNotesFormModal.tsx
  frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap
  frontend/src/features/notes/detail/NoteDetailsFormModal.test.tsx
  frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap
  frontend/src/features/notes/list/NoteResults/NoteResults.test.tsx
  frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  frontend/src/features/notes/update/UpdateNoteContainer.tsx
  frontend/src/features/notes/update/UpdateNoteFormModal.tsx
  frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap
  frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap
  frontend/src/interfaces/IOrganization.ts
  frontend/src/interfaces/IProperty.ts
  frontend/src/mocks/mockLease.ts
  frontend/src/mocks/mockOrganization.ts
  frontend/src/models/api/LeaseTenant.ts
Labels: alignment

#1828 psp-3980 add property tables to lisdb etl.
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj
Labels: etl

#1826 psp-3929 create etl to import PAIMS lease data into PIMS.
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE.sln
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE.sql
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE.dtproj
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE.dtproj.user
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE/PAIMS_PIMS_LOAD.dtsx
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE/Project.params
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE_PAYMENTS.sql
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE_PYBL_PAYMENTS.sql
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE_RCVBL_PAYMENTS.sql
  etl/PAIMS_PIMS_LEASE/Project.params
  etl/PAIMS_PIMS_LEASE/VALID_PIDS.sql
Labels: etl

#1858 Increment DEV version to IS34
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: release-management

#1848 correct hardcoded query.
  backend/api/Pims.Api.csproj
  etl/LISDB_PIMS/LISDB_PIMS/LIS_DB_to_PIMS_DATASET_1.dtsx
  etl/LISDB_PIMS/LISDB_PIMS/MOTI_LEGACY_LISDB_PIMS_DATA_MIGRATION.dtproj
  frontend/package.json
Labels: bug, etl, hotfix

#1864 Fix issue with github action logic, should run either on a bcgov pr o…
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
Labels: bug

#1861 HOTFIX psp-4084 control deposit, terms, payments via LEASE_EDIT permission.
  backend/api/Areas/Leases/Controllers/LeasePaymentController.cs
  backend/api/Areas/Leases/Controllers/LeaseTermController.cs
  backend/api/Pims.Api.csproj
  backend/dal/Services/SecurityDepositReturnService.cs
  backend/dal/Services/SecurityDepositService.cs
  backend/tests/unit/dal/Repositories/PaymentServiceTest.cs
  backend/tests/unit/dal/Services/LeaseTermServiceTest.cs
  frontend/package.json
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/DepositsReceivedContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/table/payments/PaymentsForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/payments/paymentsColumns.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
Labels: bug, hotfix

#1867 HOTFIX: Fix keycloak sync
  backend/api/Pims.Api.csproj
  frontend/package.json
  tools/keycloak/sync/Program.cs
  tools/keycloak/sync/RealmFactory.cs
  tools/keycloak/sync/SyncFactory.cs
Labels: bug, hotfix

#1868 HOTFIX: add missing commit to previous hotfix
  backend/api/Pims.Api.csproj
  frontend/package.json
  tools/keycloak/sync/Program.cs
Labels: bug, hotfix

#1869 HOTFIX: PSP-4092 Page-to-page function missing
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/src/components/Table/Table.tsx
  frontend/src/components/common/form/TableSelect.tsx
Labels: bug, hotfix

#1870 Backmerge master to test
  backend/api/Areas/Leases/Controllers/LeasePaymentController.cs
  backend/api/Areas/Leases/Controllers/LeaseTermController.cs
  backend/dal/Services/SecurityDepositReturnService.cs
  backend/dal/Services/SecurityDepositService.cs
  backend/tests/unit/dal/Repositories/PaymentServiceTest.cs
  backend/tests/unit/dal/Services/LeaseTermServiceTest.cs
  frontend/src/components/Table/Table.tsx
  frontend/src/components/common/form/TableSelect.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/DepositsReceivedContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/table/payments/PaymentsForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/payments/paymentsColumns.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
  tools/keycloak/sync/Program.cs
  tools/keycloak/sync/RealmFactory.cs
  tools/keycloak/sync/SyncFactory.cs
Labels: devops

#1871 Updated initial gen files and makefile
  .vscode/launch.json
  Makefile
  frontend/README.md
  frontend/src/setupProxy.js
  scripts/gen-env-files.sh
Labels: tech-debt

#1875 BUGFIX: PSP-4036 Edit notes: pop-up has an "x" button at the top right that doesn't work
  frontend/src/features/notes/detail/NoteDetailsFormModal.tsx
Labels: bug

#1879 PSP-3253 List View - Acquisition Files
  .vscode/launch.json
  backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  backend/api/Areas/Acquisition/Controllers/SearchController.cs
  backend/api/Areas/Acquisition/Models/AcquisitionFilterModel.cs
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  backend/api/Services/AcquisitionFileService.cs
  backend/api/Services/IAcquisitionFileService.cs
  backend/dal/Helpers/Extensions/AcquisitionExtensions.cs
  backend/dal/Models/AcquisitionFilter.cs
  backend/dal/Repositories/AcquisitionFileRepository.cs
  backend/dal/Repositories/Interfaces/IAcquisitionFileRepository.cs
  backend/dal/Repositories/UserRepository.cs
  backend/tests/unit/api/Controllers/Acquisition/AcquisitionControllerTest.cs
  backend/tests/unit/api/Routes/Acquisition/AcquisitionControllerTest.cs
  frontend/src/AppRouter.tsx
  frontend/src/components/layout/SideNavBar/AcquisitionTray.test.tsx
  frontend/src/components/layout/SideNavBar/AcquisitionTray.tsx
  frontend/src/components/layout/SideNavBar/__snapshots__/AcquisitionTray.test.tsx.snap
  frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.test.tsx
  frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.tsx
  frontend/src/features/acquisition/list/AcquisitionFilter/__snapshots__/AcquisitionFilter.test.tsx.snap
  frontend/src/features/acquisition/list/AcquisitionListView.tsx
  frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.test.tsx
  frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.tsx
  frontend/src/features/acquisition/list/AcquisitionSearchResults/__snapshots__/AcquisitionSearchResults.test.tsx.snap
  frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  frontend/src/features/acquisition/list/interfaces.ts
  frontend/src/features/acquisition/list/styles.ts
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.test.tsx
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionFileYupSchema.ts
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.test.tsx
  frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  frontend/src/features/properties/map/acquisition/add/models.ts
  frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.test.tsx
  frontend/src/features/research/list/ResearchFilter/ResearchFilter.test.tsx
  frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  frontend/src/hooks/useSearch.ts
  frontend/src/mocks/mockAcquisitionFiles.ts
  frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#1882 Backmerge test into dev
  backend/api/Areas/Leases/Controllers/LeasePaymentController.cs
  backend/api/Areas/Leases/Controllers/LeaseTermController.cs
  backend/dal/Services/SecurityDepositReturnService.cs
  backend/dal/Services/SecurityDepositService.cs
  backend/tests/unit/dal/Repositories/PaymentServiceTest.cs
  backend/tests/unit/dal/Services/LeaseTermServiceTest.cs
  frontend/src/components/Table/Table.tsx
  frontend/src/components/common/form/TableSelect.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/DepositsReceivedContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/columns.tsx
  frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/table/payments/PaymentsForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/payments/paymentsColumns.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
  frontend/src/features/notes/detail/NoteDetailsFormModal.tsx
  tools/keycloak/sync/Program.cs
  tools/keycloak/sync/RealmFactory.cs
  tools/keycloak/sync/SyncFactory.cs
Labels: alignment

#1892 Standarized the display of map properties
  frontend/src/features/properties/map/research/ResearchContainer.tsx
  frontend/src/features/properties/map/research/add/SelectedPropertyRow.test.tsx
  frontend/src/features/properties/map/research/add/SelectedPropertyRow.tsx
  frontend/src/features/properties/map/research/add/models.ts
  frontend/src/features/properties/selector/MapSelectorContainer.test.tsx
  frontend/src/features/properties/selector/MapSelectorContainer.tsx
  frontend/src/features/properties/selector/components/MapClickMonitor.tsx
  frontend/src/features/properties/selector/models.ts
  frontend/src/features/properties/selector/search/PropertySearchSelectorFormView.test.tsx
  frontend/src/features/properties/selector/search/PropertySearchSelectorFormView.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.tsx
  frontend/src/features/properties/selector/utils.ts
Labels: bug

#1893 PSP-4069: JSONSerializerOptions.IgnoreNullValues
  backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  backend/api/Repositories/Mayan/MayanMetadataRepository.cs
  backend/core/Extensions/JsonSerializerExtensions.cs
  backend/core/Http/HttpRequestClient.cs
  backend/dal/PIMSContextFactory.cs
Labels: tech-debt

#1831 PSP-3942: Add the container for activities - that will display activi…
  frontend/src/features/mapSideBar/hooks/useMapSideBarQueryParams.tsx
  frontend/src/features/properties/map/MapActionWindow.tsx
  frontend/src/features/properties/map/MapSideBar.tsx
  frontend/src/features/properties/map/MapView.tsx
  frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
  frontend/src/features/research/activities/ActivityTray/ActivityTray.tsx
  frontend/src/features/research/activities/ActivityTray/styles.ts
  frontend/src/features/research/activities/list/ActivityListView.tsx
  frontend/src/models/api/Activity.ts
Labels: enhancement

#1897 HOTFIX: Psp 3983
  .github/workflows/ci-cd-pims-master.yml
  .github/workflows/deploy-prod-end.yml
  .github/workflows/depoy-prod-start.yml
  backend/api/Pims.Api.csproj
  frontend/package.json
  maintenance/maintenance.sh
Labels: hotfix

#1889 psp-4079 activity permissions.
  backend/api/Areas/Research/Controllers/ResearchFileController.cs
  backend/dal/Security/Permissions.cs
  backend/dal/Services/ActivityService.cs
  database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/77_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/76_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/77_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S33_00/Build/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S33_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S34_00/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S34_00/Alter Down/77_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S34_00/Alter Up/76_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S34_00/Alter Up/77_DML_PIMS_ROLE_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S34_00/Build/74_DML_PIMS_CLAIM.sql
  database/mssql/scripts/dbscripts/PSP_PIMS_S34_00/Build/75_DML_PIMS_ROLE_CLAIM.sql
Labels: db-migration

#1904 backmerge master into test
  .github/workflows/ci-cd-pims-master.yml
  .github/workflows/deploy-prod-end.yml
  .github/workflows/depoy-prod-start.yml
  maintenance/maintenance.sh
Labels: db-migration

#1906 Backmerge test to dev
  .github/workflows/ci-cd-pims-master.yml
  .github/workflows/deploy-prod-end.yml
  .github/workflows/depoy-prod-start.yml
  frontend/src/features/properties/map/research/ResearchContainer.tsx
  frontend/src/features/properties/map/research/add/SelectedPropertyRow.test.tsx
  frontend/src/features/properties/map/research/add/SelectedPropertyRow.tsx
  frontend/src/features/properties/map/research/add/models.ts
  frontend/src/features/properties/selector/MapSelectorContainer.test.tsx
  frontend/src/features/properties/selector/MapSelectorContainer.tsx
  frontend/src/features/properties/selector/components/MapClickMonitor.tsx
  frontend/src/features/properties/selector/models.ts
  frontend/src/features/properties/selector/search/PropertySearchSelectorFormView.test.tsx
  frontend/src/features/properties/selector/search/PropertySearchSelectorFormView.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.tsx
  frontend/src/features/properties/selector/utils.ts
  maintenance/maintenance.sh
Labels: devops, db-migration

#1885 psp-4065 prevent requests to LTSA when no valid pid is associated.
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTabView.test.tsx.snap
  frontend/src/features/properties/map/propertyInformation/PropertyContainer.tsx
  frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
Labels: bug

#1884 PSP-3792:Reusable component - metadata for document upload
  backend/api/Areas/Documents/DocumentController.cs
  backend/api/Models/Concepts/Document/DocumentMetadataUpdateModel.cs
  backend/api/Models/Concepts/Document/Upload/DocumentUploadRequest.cs
  backend/api/Repositories/Mayan/IEdmsDocumentRepository.cs
  backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  backend/api/Services/DocumentService.cs
  backend/api/Services/DocumentSyncService.cs
  backend/api/Services/IDocumentService.cs
  frontend/src/features/documents/documentUpload/DocumentUploadContainer.tsx
  frontend/src/features/documents/documentUpload/DocumentUploadView.tsx
  frontend/src/features/documents/documentUpload/DocumentUploadYupSchema.tsx
  frontend/src/hooks/pims-api/useApiDocuments.ts
  frontend/src/models/api/Document.ts
Labels: enhancement

#1914 reorder git jobs.
  .github/workflows/depoy-prod-start.yml
Labels: devops

#1905 psp-3982 modify fa url, update timeouts.
  frontend/public/tenants/tenant.json
  frontend/src/features/properties/selector/MapSelectorContainer.test.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.test.tsx
  frontend/src/features/properties/selector/search/PropertySelectorSearchContainer.tsx
  frontend/src/hooks/pims-api/useFullyAttributedParcelMapLayer.ts
  frontend/src/hooks/pims-api/useWfsLayer.ts
  frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  frontend/src/tenants/config/default.ts
Labels: bug, gis

#1925 Bump the version of dev to new IS.
  backend/api/Pims.Api.csproj
  frontend/package.json
Labels: devops

#1931 setExternalRows duplicate condition in conditional statement.
  frontend/src/components/Table/Table.tsx
Labels: bug

#1888 psp-4144, psp-4149 remove pid restriction, correct mapping issues.
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE.dtproj
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE/PAIMS_PIMS_LOAD.dtsx
Labels: bug, etl

#1934 Features/psp 3908
  frontend/src/features/mapSideBar/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  frontend/src/features/properties/map/research/common/ResearchHeader.tsx
  frontend/src/features/properties/map/research/common/__snapshots__/ResearchHeader.test.tsx.snap
Labels: enhancement

#1942 PSP-3541 Logging reference implementation
  backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  backend/api/Areas/Acquisition/Controllers/SearchController.cs
  backend/dal/Helpers/Extensions/LoggingExtensions.cs
  backend/dal/Repositories/AcquisitionFileRepository.cs
Labels: enhancement

#1941 HOTFIX: Psp 4198
  backend/api/Pims.Api.csproj
  frontend/package.json
  tools/keycloak/sync/SyncFactory.cs
Labels: bug, hotfix

#1938 HOTFIX: Psp 4179
  backend/api/Areas/Persons/Controllers/PersonController.cs
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.tsx
  frontend/src/hooks/pims-api/useApiContacts.ts
  frontend/src/mocks/mockContacts.ts
Labels: bug, hotfix

#1949 HOTFIX: psp-4210, psp-4214, psp-4215, psp-4218, psp-4220, psp-4224
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/src/components/common/form/NotesModal.tsx
  frontend/src/features/contacts/contact/create/validation.ts
  frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.tsx
  frontend/src/features/leases/add/AddLeaseYupSchema.ts
  frontend/src/features/leases/add/ReferenceSubForm.tsx
  frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeaseContainer.tsx
  frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/insurance/InsuranceContainer.tsx
  frontend/src/features/leases/detail/LeasePages/insurance/edit/EditContainer.tsx
  frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsYupSchema.ts
  frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/__snapshots__/TermsForm.test.tsx.snap
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantYupSchema.ts
  frontend/src/features/leases/detail/LeasePages/tenant/Tenant.tsx
Labels: bug, hotfix

#1955 scaffold for 35.01
  Makefile
  backend/entities/PimsBaseContext.cs
  backend/entities/ef/PimsActivityInstance.cs
  backend/entities/ef/PimsActivityInstanceHist.cs
Labels: db-migration

#1958 PSP-3362 Acquisition file header
  frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx
  frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.test.tsx
  frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.tsx
  frontend/src/features/properties/map/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
  frontend/src/mocks/mockAcquisitionFiles.ts
Labels: enhancement

#1962 HOTFIX: 2.2 fixes
  backend/api/Areas/Tools/Controllers/LtsaController.cs
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/DepositsReceivedContainer.tsx
  frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/DepositsReturnedContainer.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/payments/PaymentsForm.tsx
  frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.tsx
  frontend/src/features/leases/detail/LeasePages/surplus/Surplus.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
Labels: bug, hotfix

#1967 PSP-4043 fix
  frontend/src/features/mapSideBar/tabs/propertyResearch/PropertyResearchTabView.test.tsx
  frontend/src/features/mapSideBar/tabs/propertyResearch/PropertyResearchTabView.tsx
  frontend/src/features/properties/map/research/FormKeys.ts
  frontend/src/features/properties/map/research/ResearchContainer.tsx
  frontend/src/features/properties/map/research/ResearchTabsContainer.tsx
  frontend/src/features/properties/map/research/ViewSelector.tsx
  frontend/src/features/properties/map/research/detail/PropertyResearchContainer.tsx
Labels: bug

#1969 HOTFIX: Psp-4179
  backend/api/Pims.Api.csproj
  frontend/package.json
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
Labels: bug, etl

#1971 correct issue with realm admin group being removed from kc.
  backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
  backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
Labels: bug, devops

#1975 Elevated empty string to error
  backend/.editorconfig
Labels: tech-debt

#1961 PSP-4067:Tests for research file backend
  backend/dal/Repositories/ResearchFileRepository.cs
  backend/tests/unit/dal/Repositories/ResearchRepositoryTest.cs
  backend/tests/unit/dal/Services/ResearchServiceTest.cs
Labels: tech-debt

#1950 PSP-3642:Reusable component - edit document details
  backend/api/Areas/Documents/DocumentController.cs
  backend/api/Models/Concepts/Document/DocumentMetadataUpdateModel.cs
  backend/api/Models/Concepts/Document/UpdateMetadata/DocumentUpdateMetadataRequest.cs
  backend/api/Repositories/Mayan/IEdmsDocumentRepository.cs
  backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  backend/api/Services/DocumentService.cs
  backend/api/Services/IDocumentService.cs
  backend/dal/Repositories/DocumentRepository.cs
  backend/dal/Repositories/Interfaces/IDocumentRepository.cs
  frontend/src/components/common/form/Input.tsx
  frontend/src/features/admin/users/ManageUsersPage.test.tsx
  frontend/src/features/documents/ComposedDocument.ts
  frontend/src/features/documents/DocumentMetadataView.tsx
  frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  frontend/src/features/documents/documentDetail/DocumentDetailModal.tsx
  frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
  frontend/src/features/documents/documentUpload/ComposedDocument.ts
  frontend/src/features/documents/documentUpload/DocumentUploadView.tsx
  frontend/src/features/documents/hooks/useDocumentRelationshipProvider.ts
  frontend/src/features/documents/list/DocumentListView.tsx
  frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaTransferSubForm.test.tsx.snap
  frontend/src/hooks/pims-api/useApiDocuments.ts
  frontend/src/models/api/Document.ts
  frontend/src/models/api/DocumentStorage.ts
Labels: enhancement
