Repository bcgov/PSP, pull requests merged in 2023-05, with the labels that each got.

#3117 update agreements form to use new isDraft, and use yes/no instead of …
  source/frontend/src/features/properties/map/agreement/detail/AgreementView.tsx
  source/frontend/src/features/properties/map/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
  source/frontend/src/features/properties/map/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/properties/map/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
Labels: enhancement

#3120 psp-5753 update map attribution to call out parcelmap bc.
  source/frontend/public/basemaps.json
Labels: enhancement

#3126 PSP-5887 Manage users - Identify a user as a staff/contractor
  source/backend/api/Areas/Reports/Mapping/User/UserMap.cs
  source/backend/api/Areas/Reports/Models/User/UserModel.cs
  source/backend/api/Models/Concepts/User/UserMap.cs
  source/backend/api/Models/Concepts/User/UserModel.cs
  source/backend/dal.keycloak/PimsKeycloakService.cs
  source/backend/dal/Repositories/AccessRequestRepository.cs
  source/backend/dal/Repositories/UserRepository.cs
  source/frontend/src/constants/index.ts
  source/frontend/src/constants/userTypes.ts
  source/frontend/src/features/admin/access-request/models.ts
  source/frontend/src/features/admin/edit-user/EditUserContainer.tsx
  source/frontend/src/features/admin/edit-user/EditUserForm.test.tsx
  source/frontend/src/features/admin/edit-user/EditUserForm.tsx
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserContainer.test.tsx.snap
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserForm.test.tsx.snap
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  source/frontend/src/features/admin/users/constants/index.tsx
  source/frontend/src/features/admin/users/models.ts
  source/frontend/src/mocks/accessRequestMock.ts
  source/frontend/src/mocks/userMock.ts
  source/frontend/src/models/api/AccessRequest.ts
  source/frontend/src/models/api/User.ts
  source/frontend/src/utils/YupSchema.ts
Labels: enhancement

#3124 psp-3346 add support for generating H0074
  source/backend/api/Constants/FormDocumentType.cs
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
  source/frontend/src/features/properties/map/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
  source/frontend/src/features/properties/map/shared/content/models.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/mocks/mockAgreements.ts
  source/frontend/src/models/generate/GenerateAgreement.test.ts
  source/frontend/src/models/generate/GenerateAgreement.ts
  source/frontend/src/models/generate/GenerateFile.test.ts
  source/frontend/src/models/generate/GenerateFile.ts
  source/frontend/src/models/generate/GenerateOwner.test.ts
  source/frontend/src/models/generate/GenerateOwner.ts
  source/frontend/src/models/generate/GeneratePerson.test.ts
  source/frontend/src/models/generate/GeneratePerson.ts
Labels: enhancement

#3132 add Aman to the code owners.
  .github/CODEOWNERS
Labels: enhancement

#3135 add aman to user seed script.
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S53_00/Build/051_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S53_00/Test Data/38_PIMS_USER.sql
Labels: enhancement

#3109 Automation - Research File refactoring and adding test data to excel sheet
  source/frontend/package-lock.json
  testing/PIMS.Tests.Automation/Classes/FinancialCode.cs
  testing/PIMS.Tests.Automation/Classes/Project.cs
  testing/PIMS.Tests.Automation/Classes/Property.cs
  testing/PIMS.Tests.Automation/Classes/ResearchFile.cs
  testing/PIMS.Tests.Automation/Data/ExcelDataContext.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/AdminTools.feature
  testing/PIMS.Tests.Automation/Features/AdminTools.feature.cs
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/PageObjects/Activities.cs
  testing/PIMS.Tests.Automation/PageObjects/CDOGSTemplates.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/Login.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFile.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedNotesTab.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ActivitiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/GenericSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/NotesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3128 prevent possible NPE if grandchild reference is null or references a …
  source/backend/dal/Helpers/Extensions/EntityExtensions.cs
Labels: bug

#3138 HOTFIX: psp-6136 - replace map property selector clickaway with manual…
  source/frontend/src/components/common/mapping/SelectProperty.tsx
  source/frontend/src/components/common/styles.ts
  source/frontend/src/components/maps/leaflet/LoadingBackdrop/LoadingBackdrop.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorFormView.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.test.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.tsx
  source/frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  source/frontend/src/features/admin/document-template/__snapshots__/DocumentTemplateManagementContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/properties/map/MapSideBar.tsx
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
Labels: bug

#3136 PSP-6029 : acquisition_file_person (acq team) id increments every sav…
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePersonMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePersonModel.cs
  source/frontend/src/features/properties/map/acquisition/common/models.ts
  source/frontend/src/models/api/AcquisitionFile.ts
Labels: bug

#3142 Limit documents extensions | psp-5855
  source/backend/api/Services/DocumentService.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  source/frontend/src/constants/ValidDocumentExtensions.ts
  source/frontend/src/features/documents/documentUpload/DocumentUploadForm.tsx
  source/frontend/src/features/documents/documentUpload/__snapshots__/DocumentUploadForm.test.tsx.snap
Labels: enhancement

#3134 Fixed Products not being de-selectable | psp-5980
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/api/Models/Concepts/Product/ProductMap.cs
  source/backend/api/Models/Concepts/Product/ProductModel.cs
  source/backend/api/Models/Concepts/ResearchFile/ResearchFileProjectMap.cs
  source/backend/api/Models/Concepts/ResearchFile/ResearchFileProjectModel.cs
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/add/models.ts
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/checklist/models.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/features/properties/map/project/ProjectContainer.tsx
  source/frontend/src/features/properties/map/project/models.ts
  source/frontend/src/features/properties/map/research/add/models.ts
  source/frontend/src/features/properties/map/research/common/models.ts
  source/frontend/src/features/properties/map/research/update/summary/models.ts
  source/frontend/src/interfaces/IProject.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/mocks/mockProjects.ts
  source/frontend/src/mocks/mockResearchFile.ts
  source/frontend/src/models/api/AcquisitionFile.ts
  source/frontend/src/models/api/Project.ts
  source/frontend/src/models/api/ResearchFile.ts
Labels: bug

#3146 PROD HOTFIX: Psp 6146 ensure selected properties match map draft marker numbering
  source/frontend/src/components/maps/leaflet/PointClusterer.tsx
  source/frontend/src/features/properties/map/acquisition/add/AcquisitionPropertiesSubForm.test.tsx
  source/frontend/src/features/properties/map/research/add/ResearchProperties.test.tsx
  source/frontend/src/hooks/useDraftMarkerSynchronizer.ts
  source/frontend/src/mocks/mockDraftProperties.ts
Labels: bug, hotfix

#3145 Fixed leases not being created with new property
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
Labels: bug

#3131 psp-5131 changed region field to MoTI region in access form
  source/frontend/src/features/admin/access-request/AccessRequestForm.tsx
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestContainer.test.tsx.snap
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestForm.test.tsx.snap
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.test.tsx.snap
Labels: bug

#3155 standardized h0043 generation and fixed acq team update
  source/frontend/src/features/properties/map/acquisition/add/models.ts
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateAgreement.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH0443.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH0443.ts
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateLetter.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/models.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/models/api/AcquisitionFile.ts
  source/frontend/src/models/generate/GenerateOwner.ts
  source/frontend/src/models/generate/GenerateProperty.ts
Labels: bug

#3149 Codeowners | Reverted linebreaks
  .github/CODEOWNERS
Labels: enhancement

#3148 PSP-5909 Add financial codes to projects
  source/backend/api/Areas/FinancialCodes/FinancialCodeController.cs
  source/backend/api/Models/Concepts/Project/ProjectModel.cs
  source/backend/api/Services/FinancialCodeService.cs
  source/backend/api/Services/IFinancialCodeService.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/tests/unit/api/Controllers/Admin/FinancialCodeControllerTest.cs
  source/backend/tests/unit/api/Controllers/FinancialCodes/FinancialCodeControllerTest.cs
  source/backend/tests/unit/api/Services/FinancialCodeServiceTest.cs
  source/frontend/src/features/admin/financial-codes/add/AddFinancialCodeContainer.test.tsx
  source/frontend/src/features/admin/financial-codes/add/AddFinancialCodeContainer.tsx
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeListView.tsx
  source/frontend/src/features/admin/financial-codes/update/UpdateFinancialCodeContainer.test.tsx
  source/frontend/src/features/admin/financial-codes/update/UpdateFinancialCodeContainer.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectForm.tsx
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/properties/map/project/detail/ProjectSummaryView.tsx
  source/frontend/src/features/properties/map/project/detail/__snapshots__/ProjectSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/project/models.ts
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.tsx
  source/frontend/src/hooks/pims-api/useApiFinancialCodes.ts
  source/frontend/src/hooks/repositories/useFinancialCodeRepository.ts
  source/frontend/src/models/api/Project.ts
  source/frontend/src/utils/financialCodeUtils.ts
Labels: enhancement

#3161 correct user migration when a user has multiple overlapping roles.
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S53_00/Alter Up/013_DML_MIGRATE_USER_ROLES.sql
Labels: bug

#3162 add distinct (missing from test script).
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S53_00/Alter Up/013_DML_MIGRATE_USER_ROLES.sql
Labels: bug

#3163 Bump dev version
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3164 Backmerge
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S53_00/Alter Up/013_DML_MIGRATE_USER_ROLES.sql
Labels: alignment

#3125 PSP-4288 : Create/Edit H120 (Compensation Requisition) - Capturing Information Only (no payees)
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Areas/Compensation/CompensationController.cs
  source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationFinancialMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationFinancialModel.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationDocumentService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/IAcquisitionFileService.cs
  source/backend/api/Services/ICompensationRequisitionService.cs
  source/backend/api/Services/ICompensationService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/CompensationRepository.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs
  source/backend/entities/Partials/CompensationRequisition.cs
  source/backend/tests/core/Entities/CompensationRequisitionHelper.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/frontend/src/components/common/SectionListHeader.tsx
  source/frontend/src/features/properties/map/CompensationRequisitionRouter.tsx
  source/frontend/src/features/properties/map/MapView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityForm.tsx
  source/frontend/src/features/properties/map/compensation/CompensationRequisitionTrayContainer.tsx
  source/frontend/src/features/properties/map/compensation/CompensationRequisitionTrayView.tsx
  source/frontend/src/features/properties/map/compensation/CompensationRequisitionYupSchema.ts
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailContainer.test.tsx
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/properties/map/compensation/detail/__snapshots__/CompensationRequisitionDetailContainer.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationListView.test.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationListView.tsx
  source/frontend/src/features/properties/map/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/list/columns.tsx
  source/frontend/src/features/properties/map/compensation/models.ts
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/properties/map/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/context/sidebarContext.tsx
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/pims-api/useApiRequisitionCompensations.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/mocks/mockCompensations.ts
  source/frontend/src/models/api/Compensation.ts
  source/frontend/src/store/slices/systemConstants/useSystemConstants.ts
Labels: enhancement

#3158 correct calculated terms not displaying correctly.
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
Labels: bug

#3147 Automation - Digital Documents refactoring
  testing/PIMS.Tests.Automation/Classes/Contact.cs
  testing/PIMS.Tests.Automation/Classes/DigitalDocument.cs
  testing/PIMS.Tests.Automation/Classes/Project.cs
  testing/PIMS.Tests.Automation/Data/ExcelDataContext.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/AdminTools.feature
  testing/PIMS.Tests.Automation/Features/AdminTools.feature.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProjects.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedDocumentsTab.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ActivitiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3169 Scaffold for s54
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcqPayeeCheque.cs
  source/backend/entities/ef/PimsAcqPayeeChequeHist.cs
  source/backend/entities/ef/PimsChartOfAccountsCode.cs
  source/backend/entities/ef/PimsCompReqH120.cs
  source/backend/entities/ef/PimsCompReqH120Hist.cs
  source/backend/entities/ef/PimsCompensationRequisition.cs
  source/backend/entities/ef/PimsCompensationRequisitionHist.cs
  source/backend/entities/ef/PimsDocumentFormatType.cs
  source/backend/entities/ef/PimsFinancialActivityCode.cs
  source/backend/entities/ef/PimsH120Category.cs
  source/backend/entities/ef/PimsProperty.cs
  source/backend/entities/ef/PimsPropertyHist.cs
  source/backend/entities/ef/PimsResponsibilityCode.cs
  source/backend/entities/ef/PimsYearlyFinancialCode.cs
Labels: db-scaffold

#3160 Automation - Changing Check element values
  source/frontend/src/components/common/form/Check.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/__snapshots__/TermForm.test.tsx.snap
Labels: frontend, test-scripts

#3170 Added Property General Location
  source/backend/api/Models/Concepts/Property/PropertyMap.cs
  source/backend/api/Models/Concepts/Property/PropertyModel.cs
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/validation.ts
  source/frontend/src/models/api/Property.ts
Labels: enhancement

#3180 psp-6201 remove project edit access from acquistion functional role
  source/frontend/src/features/properties/map/project/detail/ProjectSummaryView.tsx
Labels: bug

#3179 PSP-6149 Fix claim mismatch popup for new users
  source/backend/api/Controllers/AuthController.cs
Labels: bug

#3177 PSP-6164 : FT-Reg: Acquisition File: In the update mode if user deselects the Ministry Project that has been already selected and try to save the form, system is generating error and form is not saving
  source/frontend/src/components/common/form/AsyncTypeahead.tsx
  source/frontend/src/components/common/form/ProjectSelector/__snapshots__/ProjectSelector.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/features/properties/map/research/common/updateProjects/__snapshots__/UpdateProjectsSubForm.test.tsx.snap
Labels: bug

#3181 All Project pages appear within the sidebar-which requires property-v…
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S53_00/Alter Up/012_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S53_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
Labels: bug

#3178 PSP-6159 : BVT: Field label is missing the 'days' tag prior to Save
  source/frontend/src/features/properties/map/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/properties/map/agreement/update/UpdateAgreementsYupSchema.ts
  source/frontend/src/features/properties/map/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
Labels: bug

#3173 psp-6147 fix alignment of payments table
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/__snapshots__/TermsForm.test.tsx.snap
Labels: bug

#3172 psp-6119 display error message when required fields missing
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/shared/SidebarFooter.tsx
  source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
Labels: frontend

#3150 psp-5863 remove popup when expand arrow clicked on layer controls
  source/frontend/src/components/maps/leaflet/LayersControl/LayersMenu.tsx
Labels: bug

#3176 Added Map Layers | psp-5720
  source/frontend/src/components/maps/leaflet/LayersControl/__snapshots__/LayersControl.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayersControl/data.ts
Labels: enhancement

#3182 add escapes to keycloak sync to avoid special characters being treate…
  tools/keycloak/sync/SyncFactory.cs
Labels: bug

#3175 PSP-6111 Transfer properties of interest to core inventory when Acquisition File is complete
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
  source/backend/api/Models/Concepts/Property/PropertyMap.cs
  source/backend/api/Models/Concepts/Property/PropertyModel.cs
  source/backend/api/Models/ErrorResponseModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/IAcquisitionFileService.cs
  source/backend/dal/Exceptions/UserOverrideException.cs
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Controllers/Acquisition/AcquisitionControllerTest.cs
  source/backend/tests/unit/api/Routes/Acquisition/AcquisitionControllerTest.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
  source/frontend/src/features/properties/map/acquisition/ViewSelector.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/interfaces/IApiError.ts
  source/frontend/src/mocks/index.mock.ts
Labels: enhancement

#3188 Automation - Lease Licenses refactoring
  testing/PIMS.Tests.Automation/Classes/Lease.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
Labels: test-scripts

#3183 PSP-4631 takes
  etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION/PAIMS_ACQUISITION_TO_PIMS_DATASET.dtsx
  etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION.dtproj
Labels: etl

#3189 psp-6121 UI/UX enhancements to improvements tab
  source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/ImprovementsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
Labels: enhancement, frontend

#3193 PSP-6103 Update map layers to improve their visibility
  source/frontend/src/components/maps/leaflet/LayersControl/LayersMenu.tsx
  source/frontend/src/components/maps/leaflet/LayersControl/__snapshots__/LayersControl.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayersControl/data.ts
Labels: enhancement

#3187 psp-6229 fix document tab subtitle under lease & licenses
  source/frontend/src/features/properties/map/lease/detail/LeaseTabsContainer.tsx
Labels: bug

#3195 Doc updates
  README.md
Labels: documentation

#3192 psp-6069 allow checklist items to display for ETL'd acquisition files.
  source/backend/api/Helpers/Extensions/PrincipalExtensions.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/AcquisitionFileChecklistRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileChecklistRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#3197 Updated scaffold for s54
  source/backend/api/Models/Concepts/Take/TakeMap.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcqPayeeCheque.cs
  source/backend/entities/ef/PimsAcqPayeeChequeHist.cs
  source/backend/entities/ef/PimsAddress.cs
  source/backend/entities/ef/PimsCompReqH120.cs
  source/backend/entities/ef/PimsCompReqH120Hist.cs
  source/backend/entities/ef/PimsCompensationRequisition.cs
  source/backend/entities/ef/PimsCompensationRequisitionHist.cs
  source/backend/entities/ef/PimsDocumentCategorySubtype.cs
  source/backend/entities/ef/PimsDocumentCategoryType.cs
  source/backend/entities/ef/PimsDocumentTyp.cs
  source/backend/entities/ef/PimsLandActType.cs
  source/backend/entities/ef/PimsProperty.cs
  source/backend/entities/ef/PimsPropertyHist.cs
  source/backend/entities/ef/PimsTake.cs
  source/backend/entities/ef/PimsTakeHist.cs
Labels: db-scaffold

#3196 Document categories | psp-5720
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/DocumentRelationType.cs
  source/backend/api/Models/Mayan/PimsSync/DocumentTypeModel.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/Services/DocumentSyncService.cs
  source/backend/api/Services/IDocumentService.cs
  source/backend/dal/Repositories/DocumentTypeRepository.cs
  source/backend/dal/Repositories/Interfaces/IDocumentTypeRepository.cs
  source/backend/entities/Partials/DocumentCategorySubtype.cs
  source/backend/tests/unit/api/Services/DocumentSyncServiceTest.cs
  source/frontend/package.json
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  source/frontend/src/features/documents/documentUpload/DocumentUploadContainer.tsx
  source/frontend/src/features/documents/hooks/useDocumentProvider.ts
  source/frontend/src/features/documents/hooks/useDocumentRelationshipProvider.ts
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/hooks/pims-api/useApiDocuments.ts
Labels: enhancement

#3199 Backmerge test to dev
  source/backend/api/Controllers/AuthController.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S53_00/Alter Up/012_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S53_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/frontend/src/components/common/form/AsyncTypeahead.tsx
  source/frontend/src/components/common/form/ProjectSelector/__snapshots__/ProjectSelector.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/features/properties/map/research/common/updateProjects/__snapshots__/UpdateProjectsSubForm.test.tsx.snap
  tools/keycloak/sync/SyncFactory.cs
Labels: devops

#3204 Bump dev version to IS55
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3202 psp-6219 add tooltip for deposit due days button in agreements
  source/frontend/src/features/properties/map/agreement/detail/AgreementView.tsx
  source/frontend/src/features/properties/map/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
  source/frontend/src/features/properties/map/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/properties/map/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
Labels: frontend
