Repository bcgov/PSP, pull requests merged in 2023-01, with the labels that each got.

#2591 add eduardo to codeowners.
  .github/CODEOWNERS
Labels: devops

#2590 psp-5153 re-add missing activation logic.
  source/frontend/src/App.tsx
Labels: bug

#2589 psp-5106 correct poi delete behaviour.
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
Labels: bug

#2603 PSP-4878 Add Property Picker to Lease and License update form
  source/backend/api/Models/Concepts/Lease/PropertyLeaseMap.cs
  source/backend/api/Models/Concepts/Lease/PropertyLeaseModel.cs
  source/frontend/src/components/propertySelector/MapSelectorContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/SelectedPropertyRow.tsx
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap
  source/frontend/src/models/api/PropertyLease.ts
Labels: enhancement

#2613 Increment DEV version to IS45
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2619 scaffold of IS44
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcquisitionFile.cs
  source/backend/entities/ef/PimsAcquisitionFileHist.cs
  source/backend/entities/ef/PimsPropertyLease.cs
  source/backend/entities/ef/PimsPropertyLeaseHist.cs
Labels: devops, db-migration

#2636 Added Project info to Acq | psp-3859
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/api/Models/Concepts/Product/ProductMap.cs
  source/backend/api/Models/Concepts/Product/ProductModel.cs
  source/backend/api/Models/Concepts/Project/ProjectMap.cs
  source/backend/api/Models/Concepts/Project/ProjectModel.cs
  source/backend/api/Services/IProjectService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/Interfaces/IProjectRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/entities/Partials/AcquisitionFundingType.cs
  source/backend/entities/Partials/Product.cs
  source/backend/entities/Partials/Project.cs
  source/backend/entities/Partials/ProjectStatusType.cs
  source/backend/tests/core/Entities/ProjectHelper.cs
  source/backend/tests/unit/api/Controllers/Projects/ProjectControllerTest.cs
  source/backend/tests/unit/api/Services/ActivityServiceTest.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/package-lock.json
  source/frontend/src/constants/API.ts
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/models.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionTeam/UpdateAcquisitionTeamYupSchema.ts
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/hooks/useProjectTypeahead.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/features/properties/map/activity/list/ActivityFilter/__snapshots__/ActivityFilterForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/list/__snapshots__/ActivityListView.test.tsx.snap
  source/frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  source/frontend/src/features/research/list/ResearchFilter/__snapshots__/ResearchFilter.test.tsx.snap
  source/frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiProjects.ts
  source/frontend/src/mocks/mockLookups.ts
  source/frontend/src/mocks/mockProjects.ts
  source/frontend/src/models/api/AcquisitionFile.ts
  source/frontend/src/models/api/Project.ts
Labels: enhancement

#2640 Bump version in TEST to IS44
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2633 psp-3784 add notes to acq file.
  source/backend/api/Constants/NoteType.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileNoteMap.cs
  source/backend/api/Services/NoteService.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/IEntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/INoteRepository.cs
  source/backend/dal/Repositories/NoteRepository.cs
  source/backend/entities/Partials/AcquisitionFileNote.cs
  source/backend/tests/core/Entities/NoteHelper.cs
  source/backend/tests/unit/api/Services/NoteServiceTest.cs
  source/backend/tests/unit/dal/Repositories/NoteRepositoryTest.cs
  source/frontend/src/constants/noteTypes.ts
  source/frontend/src/features/mapSideBar/tabs/FileTabs.tsx
  source/frontend/src/features/notes/add/AddNotesContainer.test.tsx
  source/frontend/src/features/notes/list/NoteListView.test.tsx
  source/frontend/src/features/notes/update/UpdateNoteContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.tsx
  source/frontend/src/hooks/pims-api/useApiNotes.test.ts
Labels: enhancement

#2639 psp-5235 replace confusing error on map load when user is not SITEMIN…
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
Labels: bug

#2646 PSP-5025 Prevent warning during submission
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.test.tsx
  source/frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.ts
Labels: bug

#2649 Fixed selected feature file property
  source/frontend/src/components/layout/SideNavBar/SideTray.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/properties/map/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
Labels: bug

#2653 45_01 scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcquisitionFile.cs
  source/backend/entities/ef/PimsAcquisitionFileHist.cs
  source/backend/entities/ef/PimsAcquisitionFileNote.cs
  source/backend/entities/ef/PimsActivityTemplate.cs
  source/backend/entities/ef/PimsActivityTemplateHist.cs
  source/backend/entities/ef/PimsBusinessFunctionCode.cs
  source/backend/entities/ef/PimsChartOfAccountsCode.cs
  source/backend/entities/ef/PimsChartOfAccountsCodeHist.cs
  source/backend/entities/ef/PimsFinancialActivityCode.cs
  source/backend/entities/ef/PimsFinancialActivityCodeHist.cs
  source/backend/entities/ef/PimsProduct.cs
  source/backend/entities/ef/PimsProject.cs
  source/backend/entities/ef/PimsRegion.cs
  source/backend/entities/ef/PimsResponsibilityCode.cs
  source/backend/entities/ef/PimsResponsibilityCodeHist.cs
Labels: db-scaffold

#2637 PSP-4459 Financial Codes list view
  source/backend/api/Areas/Admin/Controllers/FinancialCodeController.cs
  source/backend/api/Models/Concepts/FinancialCode/FinancialCodeMap.cs
  source/backend/api/Models/Concepts/FinancialCode/FinancialCodeModel.cs
  source/backend/api/Models/Concepts/FinancialCode/FinancialCodeTypes.cs
  source/backend/api/Services/FinancialCodeService.cs
  source/backend/api/Services/IFinancialCodeService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/BusinessFunctionCodeRepository.cs
  source/backend/dal/Repositories/ChartOfAccountsCodeRepository.cs
  source/backend/dal/Repositories/CostTypeCodeRepository.cs
  source/backend/dal/Repositories/FinancialActivityCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/IBusinessFunctionCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/IChartOfAccountsCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/ICostTypeCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/IFinancialActivityCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/IResponsibilityCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/IWorkActivityCodeRepository..cs
  source/backend/dal/Repositories/Interfaces/IYearlyFinancialCodeRepository.cs
  source/backend/dal/Repositories/ResponsibilityCodeRepository.cs
  source/backend/dal/Repositories/WorkActivityCodeRepository.cs
  source/backend/dal/Repositories/YearlyFinancialCodeRepository.cs
  source/backend/entities/Partials/BusinessFunctionCode.cs
  source/backend/entities/Partials/ChartOfAccountsCode.cs
  source/backend/entities/Partials/CostTypeCode.cs
  source/backend/entities/Partials/FinancialActivityCode.cs
  source/backend/entities/Partials/IFinancialCodeEntity.cs
  source/backend/entities/Partials/ResponsibilityCode.cs
  source/backend/entities/Partials/WorkActivityCode.cs
  source/backend/entities/Partials/YearlyFinancialCode.cs
  source/frontend/src/AppRouter.tsx
  source/frontend/src/components/layout/SideNavBar/AdminTools.tsx
  source/frontend/src/constants/claims.ts
  source/frontend/src/constants/financialCodeTypes.ts
  source/frontend/src/features/admin/financial-codes/hooks/useFinancialCodeRepository.ts
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeFilter/FinancialCodeFilter.test.tsx
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeFilter/FinancialCodeFilter.tsx
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeFilter/__snapshots__/FinancialCodeFilter.test.tsx.snap
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeListView.tsx
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeResults/FinancialCodeResults.test.tsx
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeResults/FinancialCodeResults.tsx
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeResults/__snapshots__/FinancialCodeResults.test.tsx.snap
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeResults/columns.tsx
  source/frontend/src/features/admin/financial-codes/list/styles.ts
  source/frontend/src/hooks/pims-api/useApiFinancialCodes.ts
  source/frontend/src/models/api/FinancialCode.ts
Labels: enhancement

#2651 Updated text displays | psp-5142
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeSubForm.test.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaChargeSubForm.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaDuplicateTitleSubForm.test.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaDuplicateTitleSubForm.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaLandSubForm.test.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaLandSubForm.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaLegalNotationsSubForm.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaOwnershipInformationForm.test.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaOwnershipInformationForm.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaTransferSubForm.test.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaTransferSubForm.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLandSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/ltsa/__snapshots__/LtsaLegalNotationsSubForm.test.tsx.snap
Labels: enhancement

#2659 Added permisions for search projects
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
Labels: enhancement

#2667 PROD HOTFIX - make all ltsa options configurable via environment variables.
  source/backend/ltsa/Configuration/LtsaOptions.cs
Labels: hotfix

#2662 psp-3986 cache list of lookups.
  source/backend/api/Constants/CacheKeys.cs
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Startup.cs
  source/backend/tests/unit/api/Controllers/LookupControllerTest.cs
  source/frontend/src/customAxios.ts
Labels: enhancement, tech-debt

#2673 version bump.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
Labels: hotfix

#2638 Psp 4741 - split file and properties requests.
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Areas/Research/Controllers/ResearchFileController.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/IAcquisitionFileService.cs
  source/backend/api/Services/IResearchFileService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/ResearchFilePropertyRepository.cs
  source/backend/dal/Repositories/ResearchFileRepository.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionFilePropertyRepositoryTest.cs
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/documents/list/DocumentResults/DocumentResults.test.tsx
  source/frontend/src/features/documents/list/DocumentResults/DocumentResults.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/hooks/useAcquisitionProvider.ts
  source/frontend/src/features/properties/map/research/ResearchContainer.test.tsx
  source/frontend/src/features/properties/map/research/ResearchContainer.tsx
  source/frontend/src/features/properties/map/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/hooks/useGetResearch.ts
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/pims-api/useApiResearchFile.ts
  source/frontend/src/utils/utils.ts
Labels: tech-debt

#2650 PSP-4709 : Project Search and List view (Manage projects)
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Areas/Projects/Controllers/SearchController.cs
  source/backend/api/Areas/Projects/Models/ProjectFilterModel.cs
  source/backend/api/Mapping/RegionMap.cs
  source/backend/api/Models/Concepts/Address/AddressMap.cs
  source/backend/api/Models/Concepts/Project/ProjectMap.cs
  source/backend/api/Models/Concepts/Project/ProjectModel.cs
  source/backend/api/Models/RegionModel.cs
  source/backend/api/Services/IProjectService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Models/ProjectFilter.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/Interfaces/IProjectRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/entities/Partials/ProjectStatusType.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/src/AppRouter.tsx
  source/frontend/src/components/layout/SideNavBar/ProjectTray.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/SideTray.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/constants/API.ts
  source/frontend/src/constants/projectStatusTypes.ts
  source/frontend/src/features/projects/index.ts
  source/frontend/src/features/projects/interfaces.ts
  source/frontend/src/features/projects/list/ProjectFilter/ProjectFilter.test.tsx
  source/frontend/src/features/projects/list/ProjectFilter/ProjectFilter.tsx
  source/frontend/src/features/projects/list/ProjectFilter/__snapshots__/ProjectFilter.test.tsx.snap
  source/frontend/src/features/projects/list/ProjectListView.test.tsx
  source/frontend/src/features/projects/list/ProjectListView.tsx
  source/frontend/src/features/projects/list/ProjectSearchResults/ProjectSearchResults.test.tsx
  source/frontend/src/features/projects/list/ProjectSearchResults/ProjectSearchResults.tsx
  source/frontend/src/features/projects/list/ProjectSearchResults/__snapshots__/ProjectSearchResults.test.tsx.snap
  source/frontend/src/features/projects/list/ProjectSearchResults/columns.tsx
  source/frontend/src/features/projects/list/ProjectSearchResults/models.ts
  source/frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
  source/frontend/src/features/projects/list/styles.ts
  source/frontend/src/features/projects/styles.ts
  source/frontend/src/hooks/pims-api/useApiProjects.ts
  source/frontend/src/mocks/mockLookups.ts
  source/frontend/src/mocks/mockProjects.ts
  source/frontend/src/models/api/Project.ts
Labels: enhancement

#2681 PSP-4709 : Project Search and List view (Manage projects)
  source/backend/api/Controllers/LookupController.cs
Labels: bug

#2671 add missing cancel edit changes modal to lease edit screens
  source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
Labels: bug

#2684 make all ltsa options configurable via environment variables. (#2667)
  source/backend/api/Pims.Api.csproj
  source/backend/ltsa/Configuration/LtsaOptions.cs
  source/frontend/package.json
Labels: devops

#2685 Backmerge master to test
  source/backend/ltsa/Configuration/LtsaOptions.cs
Labels: devops

#2672 psp-5241 correct lease property details.
  source/backend/api/Areas/Leases/Mapping/Lease/PropertyMap.cs
  source/backend/api/Areas/Leases/Models/Lease/PropertyModel.cs
  source/backend/api/Controllers/UserController.cs
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/add/ReferenceSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailDocumentation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailDocumentation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailDocumentation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/properties/map/shared/models.ts
Labels: bug

#2689 Merge test to master
  source/backend/api/Areas/Leases/Mapping/Lease/PropertyMap.cs
  source/backend/api/Areas/Leases/Models/Lease/PropertyModel.cs
  source/backend/api/Controllers/UserController.cs
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/add/ReferenceSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailDocumentation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailDocumentation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailDocumentation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/properties/map/shared/models.ts
Labels: bug

#2690 Backmerge test to dev
  source/backend/api/Areas/Leases/Mapping/Lease/PropertyMap.cs
  source/backend/api/Areas/Leases/Models/Lease/PropertyModel.cs
  source/backend/api/Controllers/UserController.cs
  source/backend/ltsa/Configuration/LtsaOptions.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/PIMS S44.00 Change Log.txt
  source/frontend/src/components/layout/SideNavBar/SideTray.tsx
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/add/ReferenceSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailDocumentation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailDocumentation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailDocumentation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.test.tsx
  source/frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.ts
  source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
  source/frontend/src/features/properties/map/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
  source/frontend/src/features/properties/map/shared/models.ts
Labels: alignment

#2694 Bump DEV version to IS46
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2696 Producs & Acqisition files | PSP-5213
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Services/IProjectService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IProductRepository.cs
  source/backend/dal/Repositories/ProductRepository.cs
  source/frontend/src/components/common/form/AsyncTypeahead.tsx
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/models.ts
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/hooks/pims-api/useApiProjects.ts
  source/frontend/src/hooks/providers/useProjectProvider.ts
Labels: enhancement

#2706 Scaffols for s46
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsProject.cs
  source/backend/entities/ef/PimsProjectHist.cs
  source/backend/tests/core/Entities/ProjectHelper.cs
  source/backend/tests/unit/api/Controllers/Projects/ProjectControllerTest.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
Labels: db-scaffold

#2704 PSP-4514 : Create Project
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Models/Concepts/Project/ProjectMap.cs
  source/backend/api/Models/Concepts/Project/ProjectModel.cs
  source/backend/api/Services/IProjectService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Repositories/Interfaces/IProjectRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/tests/unit/api/Controllers/Projects/SearchControllerTest.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/src/components/layout/SideNavBar/ProjectTray.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
  source/frontend/src/features/projects/list/ProjectListView.test.tsx
  source/frontend/src/features/projects/list/ProjectListView.tsx
  source/frontend/src/features/projects/list/ProjectSearchResults/models.ts
  source/frontend/src/features/properties/map/MapRouter.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectFileYupSchema.ts
  source/frontend/src/features/properties/map/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectForm.tsx
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/models.ts
  source/frontend/src/features/properties/map/project/hooks/useAddProjectFormManagement.tsx
  source/frontend/src/hooks/pims-api/useApiProjects.ts
  source/frontend/src/hooks/providers/useProjectProvider.ts
  source/frontend/src/mocks/mockProjects.ts
  source/frontend/src/models/api/Project.ts
Labels: enhancement

#2697 PSP-5206 ETL: correction after Code Review
  etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION/PAIMS_ACQUISITION_TO_PIMS_DATASET.dtsx
  etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION.dtproj
Labels: etl

#2678 json5 bump.
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
Labels: dependencies

#2699 PSP-4460 create financial code
  source/backend/api/Areas/Admin/Controllers/FinancialCodeController.cs
  source/backend/api/Models/Concepts/FinancialCode/FinancialCodeMap.cs
  source/backend/api/Models/Concepts/FinancialCode/FinancialCodeTypes.cs
  source/backend/api/Services/FinancialCodeService.cs
  source/backend/api/Services/IFinancialCodeService.cs
  source/backend/dal/Repositories/BusinessFunctionCodeRepository.cs
  source/backend/dal/Repositories/ChartOfAccountsCodeRepository.cs
  source/backend/dal/Repositories/CostTypeCodeRepository.cs
  source/backend/dal/Repositories/FinancialActivityCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/IBusinessFunctionCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/IChartOfAccountsCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/ICostTypeCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/IFinancialActivityCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/IResponsibilityCodeRepository.cs
  source/backend/dal/Repositories/Interfaces/IWorkActivityCodeRepository..cs
  source/backend/dal/Repositories/Interfaces/IYearlyFinancialCodeRepository.cs
  source/backend/dal/Repositories/ResponsibilityCodeRepository.cs
  source/backend/dal/Repositories/WorkActivityCodeRepository.cs
  source/backend/dal/Repositories/YearlyFinancialCodeRepository.cs
  source/backend/tests/unit/api/Controllers/Admin/FinancialCodeControllerTest.cs
  source/backend/tests/unit/api/Services/FinancialCodeServiceTest.cs
  source/backend/tests/unit/dal/Repositories/BusinessFunctionCodeRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ChartOfAccountsCodeRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/CostTypeCodeRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/FinancialActivityCodeRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ResponsibilityCodeRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/WorkActivityCodeRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/YearlyFinancialCodeRepositoryTest.cs
  source/frontend/src/AppRouter.tsx
  source/frontend/src/constants/financialCodeTypes.ts
  source/frontend/src/constants/index.ts
  source/frontend/src/features/admin/financial-codes/add/AddFinancialCodeContainer.test.tsx
  source/frontend/src/features/admin/financial-codes/add/AddFinancialCodeContainer.tsx
  source/frontend/src/features/admin/financial-codes/add/AddFinancialCodeForm.test.tsx
  source/frontend/src/features/admin/financial-codes/add/AddFinancialCodeForm.tsx
  source/frontend/src/features/admin/financial-codes/add/AddFinancialCodeYupSchema.ts
  source/frontend/src/features/admin/financial-codes/add/__snapshots__/AddFinancialCodeForm.test.tsx.snap
  source/frontend/src/features/admin/financial-codes/add/models.ts
  source/frontend/src/features/admin/financial-codes/financialCodeUtils.ts
  source/frontend/src/features/admin/financial-codes/hooks/useFinancialCodeRepository.ts
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeFilter/FinancialCodeFilter.tsx
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeFilter/__snapshots__/FinancialCodeFilter.test.tsx.snap
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeResults/columns.tsx
  source/frontend/src/hooks/pims-api/useApiFinancialCodes.ts
  source/frontend/src/mocks/index.ts
  source/frontend/src/mocks/mockFinancialCode.ts
  source/frontend/src/utils/test-utils.tsx
Labels: enhancement

#2719 psp-5258 reduce toast messages.
  source/frontend/src/constants/toasts.ts
  source/frontend/src/features/documents/hooks/useDocumentProvider.ts
  source/frontend/src/features/mapSideBar/tabs/bcAssessment/BcAssessmentTabView.tsx
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaTabView.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/hooks/useGetProperty.ts
  source/frontend/src/features/properties/map/acquisition/hooks/useAcquisitionProvider.ts
  source/frontend/src/features/properties/map/research/hooks/useGetResearch.ts
  source/frontend/src/hooks/pims-api/useGeoServer.ts
  source/frontend/src/hooks/pims-api/wfsAxios.ts
  source/frontend/src/hooks/useBcAssessmentLayer.ts
  source/frontend/src/hooks/useLtsa.ts
Labels: enhancement

#2728 HOTFIX: Psp-5235 unable to view map after timing out/logging out of application
  openshift/s2i/nginx-runtime/nginx.conf.template
Labels: bug, hotfix

#2733 ETL: PSP-5273, 5274, 5275, 5276, 5277, 5278, 5279 Codes commit
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.sln
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtproj
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtproj.user
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtsx
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/Project.params
Labels: etl

#2731 HOTFIX: PSP-5358 Fix 400 server error by validating property names
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
Labels: bug, hotfix

#2736 Fixed mesage
  source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
Labels: bug

#2727 correct note delete behaviour.
  source/backend/api/Areas/Notes/Controllers/NoteController.cs
  source/backend/api/Services/INoteService.cs
  source/backend/api/Services/NoteService.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/tests/unit/api/Controllers/Note/NoteControllerTest.cs
  source/backend/tests/unit/dal/Repositories/NoteRepositoryTest.cs
Labels: bug

#2726 psp-5284 make all layer urls configurable.
  source/frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts
  source/frontend/src/hooks/useQueryMapLayersByLocation.ts
  source/frontend/src/tenants/ITenantConfig.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
  source/frontend/src/tenants/useTenant.test.tsx
  source/frontend/src/tenants/useTenant.ts
Labels: enhancement

#2737 Psp 5353 - Lease tenant fixes for uat hotfix (RELEASE 3.1)
  source/frontend/src/components/Table/PageSizeSelector.tsx
  source/frontend/src/components/Table/Table.test.tsx
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  source/frontend/src/components/Table/types.ts
  source/frontend/src/components/common/form/TableSelect.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeastTenantListView.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/PrimaryContactWarningModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantOrganizationContactInfo.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantPersonContactInfo.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/ViewTenantForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
  source/frontend/src/mocks/mockContacts.ts
Labels: bug

#2725 psp-4848 add acq file name to header.
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/properties/map/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
Labels: enhancement

#2746 HOTFIX: Psp 5353 - Lease tenant fixes for uat hotfix (RELEASE 3.1) (#2737)
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/components/Table/PageSizeSelector.tsx
  source/frontend/src/components/Table/Table.test.tsx
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  source/frontend/src/components/Table/types.ts
  source/frontend/src/components/common/form/TableSelect.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeastTenantListView.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/PrimaryContactWarningModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantOrganizationContactInfo.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantPersonContactInfo.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/ViewTenantForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
  source/frontend/src/mocks/mockContacts.ts
Labels: bug, hotfix

#2749 PSP-4514 : Create Project
  source/frontend/src/features/properties/map/project/add/AddProjectFileYupSchema.ts
  source/frontend/src/features/properties/map/project/add/AddProjectForm.tsx
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
Labels: bug

#2729 PSP-5037 : View / Read Project Details
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Services/IProjectService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Repositories/Interfaces/IProjectRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
  source/frontend/src/features/projects/context/ProjectContext.tsx
  source/frontend/src/features/projects/detail/ProjectEditButton.tsx
  source/frontend/src/features/properties/map/MapRouter.tsx
  source/frontend/src/features/properties/map/context/sidebarContext.tsx
  source/frontend/src/features/properties/map/project/EditFormNames.ts
  source/frontend/src/features/properties/map/project/ProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/ProjectContainer.tsx
  source/frontend/src/features/properties/map/project/ProjectContainerView.tsx
  source/frontend/src/features/properties/map/project/ProjectTabs.tsx
  source/frontend/src/features/properties/map/project/ViewSelector.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/add/models.ts
  source/frontend/src/features/properties/map/project/common/ProjectHeader.tsx
  source/frontend/src/features/properties/map/project/detail/ProjectPages/ProjectPageForm.tsx
  source/frontend/src/features/properties/map/project/detail/ProjectSummaryView.test.tsx
  source/frontend/src/features/properties/map/project/detail/ProjectSummaryView.tsx
  source/frontend/src/features/properties/map/project/detail/ProjectTab.tsx
  source/frontend/src/features/properties/map/project/detail/ProjectTabsContainer.tsx
  source/frontend/src/features/properties/map/project/detail/__snapshots__/ProjectSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.tsx
  source/frontend/src/hooks/providers/useProjectProvider.ts
  source/frontend/src/interfaces/IProject.ts
  source/frontend/src/mocks/mockProjects.ts
  source/frontend/src/models/api/Address.ts
  source/frontend/src/models/api/CodeType.ts
  source/frontend/src/models/api/Project.ts
Labels: enhancement
