Repository bcgov/PSP, pull requests merged in 2023-06, with the labels that each got.

#3214 Re-generated scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcqPayeeCheque.cs
  source/backend/entities/ef/PimsAcqPayeeChequeHist.cs
  source/backend/entities/ef/PimsInterestHolder.cs
  source/backend/entities/ef/PimsInterestHolderHist.cs
  source/backend/entities/ef/PimsInthldrPropInterest.cs
  source/backend/entities/ef/PimsInthldrPropInterestHist.cs
Labels: db-migration

#3213 psp-6106 modify land act description field in takes to be select
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Models/Concepts/Take/TakeMap.cs
  source/backend/api/Models/Concepts/Take/TakeModel.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/dal/Repositories/TakeRepository.cs
  source/backend/entities/Partials/LandActType.cs
  source/backend/entities/PimsBaseContext.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/features/mapSideBar/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/update/TakesUpdateForm.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/takes/update/models.ts
  source/frontend/src/mocks/takes.mock.ts
  source/frontend/src/models/api/Take.ts
Labels: enhancement, frontend

#3185 psp-6220 fix the order of improvements view form
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/Improvements.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
Labels: bug

#3218 PSP-6276-Changes on Term forms - GST Radio buttons labels
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/__snapshots__/TermForm.test.tsx.snap
Labels: frontend

#3205 Automation - Acquisition File refactoring - adapt data reading from spreadsheet
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Classes/Contact.cs
  testing/PIMS.Tests.Automation/Classes/DigitalDocument.cs
  testing/PIMS.Tests.Automation/Classes/FinancialCode.cs
  testing/PIMS.Tests.Automation/Classes/Project.cs
  testing/PIMS.Tests.Automation/Classes/Property.cs
  testing/PIMS.Tests.Automation/Classes/ResearchFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/NotesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3220 PSP-6017 Ability to read "Electoral District" and "Highway District" from layers for Generated H120
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/models/generate/GenerateProperty.ts
  source/frontend/src/utils/mapPropertyUtils.ts
  tools/mayan-edms/docker-compose.yml
Labels: enhancement

#3222 Regenerated scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcquisitionOwnerSolicitor.cs
  source/backend/entities/ef/PimsAcquisitionOwnerSolicitorHist.cs
  source/backend/entities/ef/PimsAcquisitionPayee.cs
  source/backend/entities/ef/PimsConsultationStatusType.cs
  source/backend/entities/ef/PimsConsultationType.cs
  source/backend/entities/ef/PimsInterestHolder.cs
  source/backend/entities/ef/PimsLeaseConsultation.cs
  source/backend/entities/ef/PimsLeaseConsultationHist.cs
  source/backend/entities/ef/PimsOrganization.cs
Labels: db-scaffold

#3223 IS54 fix for lease/research functional project access, as well as removing activity claim…
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S54_00/Alter Down/012_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S54_00/Alter Up/012_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S54_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
Labels: bug, db-migration

#3225 re-enable mapview snapshot.
  source/frontend/src/features/properties/map/MapView.test.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapView.test.tsx.snap
Labels: unit-tests

#3224 psp-6284 force refresh comp req list on save.
  source/frontend/src/features/properties/map/compensation/CompensationRequisitionTrayContainer.tsx
Labels: bug

#3217 PSP-6023 : Add/Edit OWNER Payee to Create/Edit H120 (Compensation Requisition Input)
  source/backend/api/Areas/FinancialCodes/FinancialCodeController.cs
  source/backend/api/Mapping/Lookup/LookupMap.cs
  source/backend/api/Models/Concepts/AcquisitionPayeeCheque/AcquisitionPayeeChequeMap.cs
  source/backend/api/Models/Concepts/AcquisitionPayeeCheque/AcquisitionPayeeChequeModel.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationFinancialMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationFinancialModel.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationPayeeMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationPayeeModel.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/dal/Helpers/Extensions/EntityExtensions.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs
  source/backend/entities/Partials/AcquisitionPayee.cs
  source/backend/entities/Partials/AcquistionPayeeCheque.cs
  source/backend/entities/Partials/ChartOfAccountsCode.cs
  source/backend/entities/Partials/CompensationRequisition.cs
  source/backend/entities/Partials/FinancialActivityCode.cs
  source/backend/entities/Partials/ResponsibilityCode.cs
  source/backend/entities/Partials/YearlyFinancialCode.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/frontend/src/components/common/form/FastCurrencyInput.tsx
  source/frontend/src/components/common/form/Select.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/features/properties/map/compensation/CompensationRequisitionTrayContainer.tsx
  source/frontend/src/features/properties/map/compensation/CompensationRequisitionTrayView.tsx
  source/frontend/src/features/properties/map/compensation/CompensationRequisitionYupSchema.ts
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationListView.test.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationListView.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationResults.tsx
  source/frontend/src/features/properties/map/compensation/list/columns.tsx
  source/frontend/src/features/properties/map/compensation/models.ts
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/properties/map/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/update/financials/FinancialActivitiesSubForm.tsx
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/pims-api/useApiFinancialCodes.ts
  source/frontend/src/hooks/pims-api/useApiRequisitionCompensations.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/hooks/repositories/useFinancialCodeRepository.ts
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/mocks/mockCompReqH120s.ts
  source/frontend/src/models/api/Compensation.ts
  source/frontend/src/models/api/CompensationFinancial.ts
  source/frontend/src/models/api/CompensationPayee.ts
  source/frontend/src/models/api/CompensationRequisition.ts
  source/frontend/src/models/api/PayeeCheque.ts
  source/frontend/src/models/generate/GenerateCompensation.ts
  source/frontend/src/models/generate/GenerateCompensationFinancial.ts
  source/frontend/src/models/generate/GenerateCompensationFinancialSummary.ts
Labels: enhancement

#3228 update pims user script, add all regions to devs by default, also mak…
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Test Data/38_PIMS_USER.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S55_00/Test Data/38_PIMS_USER.sql
Labels: test-scripts, test-data

#3230 Backmerge test to dev
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S54_00/Alter Down/012_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S54_00/Alter Up/012_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S54_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/frontend/src/features/properties/map/compensation/CompensationRequisitionTrayContainer.tsx
Labels: devops

#3229 PSP-6279 Add a tooltip to the Compensation tab for "Total Payment"
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/__snapshots__/DepositsReceivedContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/__snapshots__/DepositsReturnedContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/__snapshots__/TermsForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/Section.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/propertyResearch/__snapshots__/PropertyResearchTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/checklist/__snapshots__/UpdateAcquisitionChecklistForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/stakeholders/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityControlsBar.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityPropertyModal.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  source/frontend/src/features/properties/map/activity/list/__snapshots__/ActivityListView.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/list/CompensationListView.tsx
  source/frontend/src/features/properties/map/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/properties/map/research/detail/__snapshots__/ResearchSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/research/update/property/__snapshots__/UpdatePropertyForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
Labels: enhancement

#3231 Added interest holders to the payee options
  source/frontend/src/features/properties/map/compensation/models.ts
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionContainer.tsx
Labels: enhancement

#3232 PSP-5952 : View H120 Details (Compensation Requisition)
  source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/ICompensationRequisitionService.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/properties/map/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiRequisitionCompensations.ts
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/models/api/CompensationPayee.ts
Labels: enhancement

#3226 Psp 5908 - generation for interest holders
  source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationPayeeMap.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/ICompensationRequisitionService.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/AcquisitionPayeeRepository.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/dal/Repositories/InterestHolderRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionPayeeRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs
  source/frontend/src/components/common/form/ContactInput/ContactInputContainer.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputView.tsx
  source/frontend/src/components/contact/ContactManagerModal.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/features/properties/map/acquisition/common/models.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionTeam/UpdateAcquisitionTeamSubForm.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/update/stakeholders/UpdateStakeHolderForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/interfaces/IContactSearchResult.ts
  source/frontend/src/models/generate/GenerateAgreement.ts
  source/frontend/src/models/generate/GenerateFile.test.ts
  source/frontend/src/models/generate/GenerateFile.ts
  source/frontend/src/models/generate/GenerateLetter.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.test.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationFinancial.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationFinancialSummary.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
  source/frontend/src/models/generate/acquisition/GenerateH120Property.ts
  source/frontend/src/models/generate/acquisition/GenerateInterestHolder.ts
  source/frontend/src/models/generate/compensation/GenerateCompensation.test.ts
Labels: enhancement

#3235 psp-6259 make 'days' tag bold next to due no later than field
  source/frontend/src/features/properties/map/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/properties/map/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
Labels: bug, frontend

#3239 Bump DEV version - IS56
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3240 HOTFIX: PSP-6343 Update GitHub Actions to run Node16 instead of Node12
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/ci-cd-pims-master.yml
  .github/workflows/ci-cd-pims-test.yml
  .github/workflows/credentials-comment-pr.yml
  .github/workflows/credentials-scan.yml
  .github/workflows/deploy-prod-end.yml
  .github/workflows/depoy-prod-start.yml
  .github/workflows/image-scan-analysis.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .github/workflows/version.yml
Labels: devops

#3242 Regenerated scaffold and fixed compiling issues.
  source/backend/api/Models/Concepts/AcquisitionPayeeCheque/AcquisitionPayeeChequeMap.cs
  source/backend/api/Models/Concepts/AcquisitionPayeeCheque/AcquisitionPayeeChequeModel.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationPayeeMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationPayeeModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/dal/Repositories/AcquisitionPayeeRepository.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs
  source/backend/entities/Partials/AcquistionPayeeCheque.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcqPayeeCheque.cs
  source/backend/entities/ef/PimsAcqPayeeChequeHist.cs
  source/backend/entities/ef/PimsAcquisitionPayee.cs
  source/backend/entities/ef/PimsAcquisitionPayeeHist.cs
Labels: db-scaffold

#3243 Backmerge master to test
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/ci-cd-pims-master.yml
  .github/workflows/ci-cd-pims-test.yml
  .github/workflows/credentials-comment-pr.yml
  .github/workflows/credentials-scan.yml
  .github/workflows/deploy-prod-end.yml
  .github/workflows/depoy-prod-start.yml
  .github/workflows/image-scan-analysis.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .github/workflows/version.yml
Labels: devops

#3244 Fix github-actions bot email
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .github/workflows/version.yml
Labels: devops

#3245 PSP-6342 : Update acquisition file to remove PIMS_PAYEE_CHEQUE
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationPayeeMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationPayeeModel.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/entities/Partials/AcquisitionPayee.cs
  source/frontend/src/features/properties/map/compensation/CompensationRequisitionYupSchema.ts
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/properties/map/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/models.ts
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/properties/map/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/models/api/CompensationPayee.ts
  source/frontend/src/models/api/PayeeCheque.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
Labels: enhancement

#3254 psp-6312 correct typings of string values in report.
  source/backend/api/Models/Concepts/Lease/LeasePaymentReportModel.cs
Labels: bug, release 4.0

#3257 PSP-6393 Add missing mapping for comments
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileOwnerRepresentativeMap.cs
Labels: bug, release 4.0

#3255 h120 development-only option removed from sidebar.
  source/frontend/src/components/Table/Table.test.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputContainer.test.tsx
  source/frontend/src/components/common/form/ProjectSelector/ProjectSelector.test.tsx
  source/frontend/src/features/admin/access-request/AccessRequestContainer.test.tsx
  source/frontend/src/features/admin/edit-user/EditUserContainer.test.tsx
  source/frontend/src/features/admin/financial-codes/add/AddFinancialCodeForm.test.tsx
  source/frontend/src/features/admin/financial-codes/update/UpdateFinancialCodeForm.test.tsx
  source/frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.test.tsx
  source/frontend/src/features/contacts/contact/create/Person/CreatePersonForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.test.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.test.tsx
  source/frontend/src/features/leases/detail/LeaseHeaderAddresses.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx
  source/frontend/src/features/notes/NoteContainer.test.tsx
  source/frontend/src/features/notes/add/AddNotesContainer.test.tsx
  source/frontend/src/features/notes/add/AddNotesFormModal.test.tsx
  source/frontend/src/features/notes/hooks/useAddNotesFormManagement.test.tsx
  source/frontend/src/features/notes/hooks/useUpdateNotesFormManagement.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/map/MapView.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/formDocumentEntry.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityForm.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityPropertyModal.test.tsx
  source/frontend/src/features/properties/map/activity/list/ActivityListView.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/properties/map/research/detail/ResearchSummaryView.test.tsx
  source/frontend/src/utils/AppRoute.test.tsx
Labels: bug, release 4.0

#3258 Psp 6404, psp-6152
  source/frontend/src/components/common/List/SelectInput.tsx
  source/frontend/src/components/common/form/Input.tsx
  source/frontend/src/components/common/form/InputGroup.tsx
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
  source/frontend/src/components/maps/leaflet/Map.tsx
  source/frontend/src/components/maps/leaflet/mapUtils.test.tsx
  source/frontend/src/components/maps/leaflet/mapUtils.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/components/propertySelector/search/LayerFilter.tsx
  source/frontend/src/components/propertySelector/search/__snapshots__/LayerFilter.test.tsx.snap
  source/frontend/src/components/propertySelector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/hooks/useMapProperties.tsx
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/hooks/pims-api/useFullyAttributedParcelMapLayer.ts
  source/frontend/src/hooks/pims-api/useGeoServer.ts
  source/frontend/src/hooks/pims-api/useWfsLayer.ts
  source/frontend/src/hooks/useBcAssessmentLayer.ts
Labels: bug, release 4.0

#3261 psp-6365 fix display issues with organization based solicitors.
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/frontend/src/features/properties/map/acquisition/common/models.ts
Labels: bug, release 4.0

#3263 psp-6367 truncate payee names for dropdown in H120
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/models.ts
Labels: enhancement, frontend, release 4.0

#3264 Psp 6410
  source/frontend/src/features/leases/hooks/useLeaseExport.ts
Labels: bug, release 4.0

#3262 psp-6386 allow interest holders to be deleted.
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/InterestHolderRepository.cs
  source/backend/tests/unit/dal/Repositories/InterestHolderRepositoryTest.cs
  source/frontend/src/components/common/form/FastCurrencyInput.tsx
  source/frontend/src/components/common/form/Select.tsx
  source/frontend/src/features/properties/map/acquisition/update/stakeholders/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/stakeholders/models.test.ts
  source/frontend/src/features/properties/map/acquisition/update/stakeholders/models.ts
  source/frontend/src/features/properties/map/compensation/CompensationRequisitionYupSchema.ts
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/properties/map/compensation/models.ts
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/properties/map/compensation/update/financials/FinancialActivitiesSubForm.tsx
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
Labels: bug, release 4.0

#3266 PSP-6364 : FT: H120 Payee List - Owner Solicitor, when selected as a payee and then deleted, PIMS throws a 400 error
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Areas/Acquisition/Controllers/InterestHolderController.cs
  source/backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/core/Exceptions/ForeignKeyDependencyException.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/entities/Partials/AcquisitionPayee.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/features/properties/map/acquisition/update/stakeholders/UpdateStakeHolderContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/stakeholders/UpdateStakeHolderContainer.tsx
  source/frontend/src/features/properties/map/acquisition/update/stakeholders/UpdateStakeHolderForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionContainer.tsx
  source/frontend/src/hooks/repositories/useInterestHolderRepository.ts
  source/frontend/src/utils/axiosUtils.ts
Labels: bug, release 4.0

#3274 PSP-6422 : Not possible to save compensation requisition that has a p…
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationPayeeMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationPayeeModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/frontend/src/features/properties/map/compensation/models.ts
Labels: bug, release 4.0

#3203 psp-2175 fix frontend tests console output
  .vscode/settings.json
  source/frontend/src/components/common/ModalContainer.test.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputView.test.tsx
  source/frontend/src/components/common/form/FastDatePicker.test.tsx
  source/frontend/src/components/common/form/Multiselect.test.tsx
  source/frontend/src/components/common/form/NotesModal.test.tsx
  source/frontend/src/components/common/form/ParentSelect.test.tsx
  source/frontend/src/components/common/form/ProjectSelector/ProjectSelector.test.tsx
  source/frontend/src/components/propertySelector/search/LayerFilter.test.tsx
  source/frontend/src/hooks/layer-api/useLayerQuery.test.tsx
Labels: unit-tests

#3275 ensure that interest holder organizations display correctly in payee …
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.tsx
Labels: bug, release 4.0

#3276 PSP-6428 : FT: Compensation requisition - Typo when user wants to era…
  source/backend/api/Services/AcquisitionFileService.cs
Labels: bug, release 4.0

#3279 PSP-6422 : Not possible to save compensation requisition that has a p…
  source/backend/api/Services/CompensationRequisitionService.cs
Labels: bug, release 4.0

#3272 psp-6227: fix leases filtering for tenant names
  source/backend/dal/Helpers/Extensions/LeaseExtensions.cs
Labels: bug

#3277 psp-6263 display 'missing fields required' message in edit mode
  source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
Labels: bug

#3278 remove 0 padding trim on property search
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
Labels: bug, release 4.0

#3280 Psp 6429 agreement commencement date hide on non-h0074 on view screen.
  source/frontend/src/features/properties/map/agreement/detail/AgreementView.tsx
  source/frontend/src/features/properties/map/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
Labels: bug, release 4.0

#3252 PSP-6288 : User Warning and System Note when changing compensation status
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/frontend/package-lock.json
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/financials/FinancialActivitiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/financials/FinancialActivitiesSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/financials/__snapshots__/FinancialActivitiesSubForm.test.tsx.snap
  source/frontend/src/mocks/compensations.mock.ts
Labels: enhancement

#3271 Techdebt/refactor map split
  source/frontend/src/components/common/List/SelectInput.test.tsx
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/MapView.test.tsx
  source/frontend/src/components/maps/MapView.tsx
  source/frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/features/mapSideBar/hooks/usePropertyDetails.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  source/frontend/src/features/properties/map/MapContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
  source/frontend/src/hooks/repositories/mapLayer/useAdminBoundaryMapLayer.ts
  source/frontend/src/hooks/repositories/mapLayer/useFullyAttributedParcelMapLayer.ts
  source/frontend/src/hooks/repositories/mapLayer/useIndianReserveBandMapLayer.ts
  source/frontend/src/hooks/repositories/mapLayer/useLegalAdminBoundariesMapLayer.ts
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/hooks/repositories/useBcAssessmentLayer.ts
  source/frontend/src/hooks/repositories/useFullyAttributedParcelMapLayer.test_old.tsx
  source/frontend/src/hooks/repositories/useFullyAttributedParcelMapLayer_old.ts
  source/frontend/src/hooks/repositories/usePimsPropertyRepository.ts
  source/frontend/src/hooks/repositories/useQueryMapLayersByLocation.ts
  source/frontend/src/hooks/useRouterFilter.test.tsx
Labels: tech-debt

#3250 psp-6255: keycloak sync github action
  .github/workflows/keycloak-sync.yml
  tools/keycloak/sync/appsettings.development.json
  tools/keycloak/sync/appsettings.json
Labels: devops

#3285 Automation test - Stabilization of some automated features
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Classes/Contact.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/ManageUsers.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3289 PSP-5111
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_Load.dtsx
  etl/LISOS_PIMS/LISOS_PIMS/LISOS_PIMS.dtproj
Labels: etl

#3281 PSP-6286 : Restrict changing final compensation requisition status back to draft
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/CompensationRequisitionTrayView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/mocks/compensations.mock.ts
Labels: enhancement

#3292 PSP-5715 : Sec3/Sec6 add forms to acquisition file
  source/frontend/src/components/common/TabView.tsx
  source/frontend/src/components/common/styles.ts
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainerView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainerView.tsx
  source/frontend/src/features/mapSideBar/project/tabs/__snapshots__/ProjectTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/detail/FileTabs.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#3287 Drop Payee Check Constraint
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/003_DML_Drop_ACQPAY_COMP_REQ_PAYEE_TCC.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/004_DML_Migrate_Chq_Data_From_TMP.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_DML_SET_ALL_USERS_TO_MINISTRY.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_DML_SET_LEASE_PAYMENT_STATUS_TYPE_CODE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/003_DML_Drop_ACQPAY_COMP_REQ_PAYEE_TCC.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Alter Up/003_DML_Drop_ACQPAY_COMP_REQ_PAYEE_TCC.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Alter Up/004_DML_Migrate_Chq_Data_From_TMP.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Build/003_DML_Drop_ACQPAY_COMP_REQ_PAYEE_TCC.sql
Labels: bug, db-migration

#3291 psp-5361: fix link name for financial codes in admin tools
  source/frontend/src/components/layout/SideNavBar/AdminTools.tsx
Labels: bug

#3295 Bump DEV version - IS57
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3296 HOTFIX: psp-6425 ensure that a new property added to a lease shows up on the …
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
Labels: bug, hotfix

#3300 HOTFIX: Psp 6442
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/properties/map/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/properties/map/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/properties/map/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/models/api/CompensationFinancial.ts
Labels: bug, hotfix

#3290 psp-5791: add assignee to tenant types
  source/frontend/src/features/leases/detail/LeasePages/tenant/ViewTenantForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/ViewTenantForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/ViewTenantForm.test.tsx.snap
Labels: enhancement, frontend

#3302 PSP-6493 Generate H120 button is not matching UXPin mockup
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/CompensationRequisitionTrayContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/CompensationRequisitionTrayView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
Labels: bug
