Repository bcgov/PSP, pull requests merged in 2023-11, with the labels that each got.

#3551 psp-7045 add lease advanced filter.
  source/backend/dal/Models/PropertyFilterCriteria.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.test.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.test.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/models.ts
  source/frontend/src/models/api/ProjectFilterCriteria.ts
Labels: enhancement

#3561 Psp 7100 hide management tab based on claims
  source/frontend/src/features/mapSideBar/property/PropertyContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
Labels: bug

#3565 PSP-7039 Take SRW Expiry Date
  source/backend/api/Models/Concepts/Take/TakeMap.cs
  source/backend/api/Models/Concepts/Take/TakeModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.ts
  source/frontend/src/mocks/takes.mock.ts
  source/frontend/src/models/api/Take.ts
Labels: enhancement

#3556 psp-7082 ensure that primary contact logic for org teams works when t…
  source/frontend/src/features/mapSideBar/acquisition/common/models.test.ts
  source/frontend/src/features/mapSideBar/acquisition/common/models.ts
Labels: bug

#3563 Automation test - Nuget packages update, Refactoring Acquisition File Checklist, Help Desk, Contacts
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFilesDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/HelpDesk.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
Labels: test-scripts

#3567 Automation - Updating nuget packages for github action to work properly
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
Labels: test-scripts

#3566 PSP-7069 : Show ACQ team (organization) in filter by ACQ team in Acqu…
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Areas/Acquisition/Models/AcquisitionFilterModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Models/AcquisitionFilter.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.test.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  source/frontend/src/features/acquisition/list/interfaces.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/InvoiceForm.tsx
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
Labels: enhancement

#3568 PSP-7075 : Show ACQ team (organization) in project exports
  source/backend/api/Areas/Reports/Models/Acquisition/AgreementReportModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Models/AcquisitionReportFilterModel.cs
  source/backend/dal/Repositories/AgreementRepository.cs
  source/backend/dal/Repositories/CompReqFinancialRepository.cs
  source/backend/tests/unit/api/Models/AgreementReportModelTest.cs
  source/backend/tests/unit/dal/Repositories/AgreementRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/CompReqFinancialRepositoryTest.cs
  source/frontend/src/features/projects/reports/ProjectExportForm.test.tsx
  source/frontend/src/features/projects/reports/ProjectExportForm.tsx
  source/frontend/src/features/projects/reports/ProjectExportFormContent.tsx
  source/frontend/src/features/projects/reports/models.ts
  source/frontend/src/models/api/ProjectFilter.ts
Labels: enhancement

#3570 psp-7170 correct view property contact permissions.
  source/backend/api/Services/PropertyService.cs
Labels: bug

#3571 PSP-7013 Enhance Management Summary >> Lease / License Details
  source/backend/api/Models/Concepts/Property/PropertyManagementModel.cs
  source/backend/api/Services/PropertyService.cs
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/PropertyManagementUpdateContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/PropertyManagementUpdateForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/models.test.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/models.ts
  source/frontend/src/mocks/propertyManagement.mock.ts
  source/frontend/src/models/api/Property.ts
  source/frontend/src/utils/propertyUtils.ts
Labels: enhancement

#3562 psp-7162 avoid lease details race condition after updating lease.
  source/frontend/src/features/leases/hooks/useLeaseDetail.ts
Labels: bug

#3560 psp-7096 hook list view into stale last update event.
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesListContainer.tsx
Labels: bug

#3564 Psp 6988 - update property sidebar to use router instead of state.
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/features/mapSideBar/acquisition/router/FilePropertyRouter.tsx
  source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
  source/frontend/src/features/mapSideBar/property/PropertyRouter.tsx
  source/frontend/src/features/mapSideBar/property/PropertyViewSelector.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/PropertyActivityDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesListContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactListContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactListView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactListView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyManagementTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailView.tsx
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/features/mapSideBar/router/PropertyActivityRouter.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
Labels: enhancement

#3559 Psp 7128 fix table pagination when table size prop is supplied.
  source/frontend/src/components/Table/PageSizeSelector.tsx
  source/frontend/src/components/Table/Table.test.tsx
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/features/documents/list/DocumentResults/DocumentResults.tsx
Labels: bug

#3558 psp-7095 add default status to new management activities, display sta…
  source/backend/api/Services/PropertyService.cs
  source/backend/tests/unit/api/Services/PropertyServiceTest.cs
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.tsx
Labels: bug

#3575 psp-6988 File tabs fix
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/router/FilePropertyRouter.tsx
  source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/ResearchRouter.tsx
  source/frontend/src/features/mapSideBar/research/ResearchView.tsx
  source/frontend/src/features/mapSideBar/research/ViewSelector.tsx
  source/frontend/src/features/mapSideBar/research/tabs/ResearchTabsContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/tabs/ResearchTabsContainer.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.test.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
Labels: bug

#3572 PSP-7057 : FT:HelpDesk: map icon is not close PIMS naming on the Header
  source/frontend/src/components/layout/Header/HeaderStyled.tsx
  source/frontend/src/components/layout/Header/__snapshots__/EmptyHeader.test.tsx.snap
  source/frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
Labels: bug

#3576 Update unit tests for PSP-7039
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/__snapshots__/TakesDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.tsx
Labels: unit-tests

#3573 add automatic db deployment to test, uat. add keycloak sync to uat. update action definitions to allow for env specific secrets for keycloak sync.
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION.dtproj
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION.dtproj.user
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/Package.dtsx
  openshift/4.0/templates/jobs/db-deploy.yaml
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/features/mapSideBar/acquisition/common/models.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.tsx
Labels: devops

#3577 PSP-7197 : FT-Management tab: Activities List: Multiple Activities ar…
  source/frontend/src/features/mapSideBar/context/sidebarContext.tsx
Labels: bug

#3574 Takes - Acquire property toggle
  source/backend/api/Models/Concepts/Take/TakeMap.cs
  source/backend/api/Models/Concepts/Take/TakeModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/dal/Repositories/TakeRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.ts
  source/frontend/src/mocks/takes.mock.ts
  source/frontend/src/models/api/Take.ts
  source/frontend/src/utils/formUtils.ts
Labels: enhancement

#3578 Allow Products with multiple projects
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Models/Concepts/Product/ProductMap.cs
  source/backend/api/Models/Concepts/Product/ProductModel.cs
  source/backend/api/Models/Concepts/Project/ProjectMap.cs
  source/backend/api/Models/Concepts/Project/ProjectModel.cs
  source/backend/api/Models/Concepts/Project/ProjectProductMap.cs
  source/backend/api/Models/Concepts/Project/ProjectProductModel.cs
  source/backend/api/Services/IProjectService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Exceptions/OverrideExceptions.cs
  source/backend/dal/Repositories/Interfaces/IProductRepository.cs
  source/backend/dal/Repositories/ProductRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/tests/unit/api/Controllers/Projects/ProjectControllerTest.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.test.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.tsx
  source/frontend/src/features/mapSideBar/project/add/ProductSubForm.tsx
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/hooks/useAddProjectFormManagement.tsx
  source/frontend/src/features/mapSideBar/project/models.ts
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/ProjectProductView.tsx
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/ProjectSummaryView.tsx
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/update/UpdateProjectContainer.test.tsx
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/update/UpdateProjectContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/InvoiceForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiProjects.ts
  source/frontend/src/hooks/repositories/useProjectProvider.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/mocks/projects.mock.ts
  source/frontend/src/mocks/researchFile.mock.ts
  source/frontend/src/models/api/AcquisitionFile.ts
  source/frontend/src/models/api/Project.ts
  source/frontend/src/models/api/UserOverrideCode.ts
Labels: enhancement

#3580 psp-7209 do not display acquisition file until all loading state is c…
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
Labels: bug

#3581 PSP-7209 Fix research container race condition
  source/frontend/src/features/mapSideBar/research/ResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/details/ResearchSummaryView.tsx
Labels: bug

#3585 Bump DEV version - IS67
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3586 PSP-7103 : Change main menu "Management" to "Leases & Licenses"
  source/frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  source/frontend/src/components/layout/SideNavBar/NavIcon.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
Labels: enhancement

#3588 PSP-7228 Management summary lease information - text change
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/__snapshots__/PropertyManagementDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/__snapshots__/PropertyManagementUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/models.test.ts
  source/frontend/src/utils/propertyUtils.ts
Labels: bug

#3584 PSP-7204 : FT: Logic for Completing Takes - When a property belongs to different files, the pin colour doesn't obey the established priority
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
Labels: bug

#3587 PSP-6942 and PSP-6943
  etl/LISDB_PIMS_MANAGEMENT/Integration Services Project1/Integration Services Project1.dtproj
  etl/LISDB_PIMS_MANAGEMENT/Integration Services Project1/Integration Services Project1.dtproj.user
  etl/LISDB_PIMS_MANAGEMENT/Integration Services Project1/LIS_DB_to_PIMS_ACTIVITY_PSP_6942.dtsx
  etl/LISDB_PIMS_MANAGEMENT/Integration Services Project1/LIS_DB_to_PIMS_ACTIVITY_PSP_6943.dtsx
  etl/LISDB_PIMS_MANAGEMENT/Integration Services Project1/Package.dtsx
Labels: etl

#3592 remove keycloak sync as firewall protections make this impossible, al…
  .github/workflows/retag-test-to-uat.yml
Labels: devops

#3593 Scaffold 67
  source/backend/api/Areas/Reports/Models/Acquisition/AgreementReportModel.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AgreementMap.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAgreement.cs
  source/backend/entities/ef/PimsAgreementHist.cs
  source/backend/entities/ef/PimsAgreementStatusType.cs
  source/backend/entities/ef/PimsPropertyBoundaryVw.cs
  source/backend/entities/ef/PimsPropertyLocationVw.cs
Labels: db-scaffold

#3591 psp-7085 update acknowledgement dialog box.
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/appsettings.Test.json
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
Labels: enhancement

#3595 PSP-6778 : Update dialog boxes
  source/frontend/src/assets/scss/App.scss
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/components/common/GenericModal.tsx
  source/frontend/src/components/common/form/NotesModal.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/contact/ContactManagerModal.tsx
  source/frontend/src/components/modals/roleMismatch.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailModal.tsx
  source/frontend/src/features/documents/documentUpload/DocumentUploadModal.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/help/components/HelpModal.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/GenerateLetterRecipientsModal.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/__snapshots__/GenerateLetterRecipientsModal.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/modals/AcquisitionFormModal.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap
  source/frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap
  source/frontend/src/hooks/useApiUserOverride.ts
  source/frontend/src/hooks/usePimsIdleTimer.tsx
Labels: enhancement

#3594 PSP-7157 Project dropdowns
  source/frontend/src/components/common/form/TypeaheadSelect.test.tsx
  source/frontend/src/components/common/form/TypeaheadSelect.tsx
  source/frontend/src/components/common/form/__snapshots__/TypeaheadSelect.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectForm.tsx
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/models.ts
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/ProjectSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/update/UpdateProjectContainer.tsx
  source/frontend/src/utils/financialCodeUtils.ts
Labels: enhancement

#3598 Automation Refactoring
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/AdminTools.feature
  testing/PIMS.Tests.Automation/Features/AdminTools.feature.cs
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFilesDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/Activities.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProjects.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedPagination.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ActivitiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/NotesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3597 Hotfixes
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/maps/MapSearch.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/utils/YupSchema.ts
Labels: release-management

#3596 Psp 7081 cancellation status and note.
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AgreementMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AgreementModel.cs
  source/backend/dal/Repositories/AgreementRepository.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/entities/Partials/AgreementStatusType.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/models.ts
  source/frontend/src/mocks/agreements.mock.ts
  source/frontend/src/mocks/lookups.mock.ts
  source/frontend/src/models/api/Agreement.ts
  source/frontend/src/models/generate/GenerateAgreement.ts
Labels: enhancement

#3600 PSP-7177 h120 dropdowns typeahead
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/CompensationRequisitionYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/financials/FinancialActivitiesSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/models.ts
  source/frontend/src/models/api/CompensationFinancial.ts
Labels: enhancement

#3599 Backmerge test to dev
  source/backend/api/Pims.Api.csproj
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/maps/MapSearch.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/utils/YupSchema.ts
Labels: release-management

#3590 Agreements statuscompletition | psp-7079
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx
  source/frontend/src/hooks/useApiUserOverride.ts
  source/frontend/src/utils/axiosUtils.ts
Labels: enhancement

#3607 PSP-7237 Remove duplicate confirmation prompt
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/UpdateSummaryContainer.tsx
Labels: bug

#3604 use polylabel to calculate a point within the first polygon.
  source/frontend/src/components/maps/constants.ts
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.test.tsx
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: bug

#3603 correct performance issue in project search.
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
Labels: bug

#3610 PSP-7226: Automation Refactoring
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedPagination.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/NotesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3608 Fixed date display on lease header
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
Labels: bug

#3609 V4.1.2 66.43 hotfix
  source/backend/api/Pims.Api.csproj
  source/backend/dal/Repositories/OrganizationRepository.cs
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/models.test.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/models.ts
  source/frontend/src/interfaces/IContactSearchResult.ts
Labels: bug, hotfix

#3613 Backmerge test into dev
  source/backend/dal/Repositories/OrganizationRepository.cs
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/models.test.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/models.ts
  source/frontend/src/interfaces/IContactSearchResult.ts
Labels: devops, release-management

#3612 PSP-4389, PSP-4409 Tech debt fixes
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/common/OverflowTip.tsx
  source/frontend/src/components/common/TooltipWrapper.tsx
  source/frontend/src/components/common/buttons/PlusButton.tsx
  source/frontend/src/components/common/buttons/ResetButton.tsx
  source/frontend/src/components/common/buttons/SearchButton.tsx
  source/frontend/src/components/common/form/AsyncTypeahead.tsx
  source/frontend/src/components/common/form/ContactInput.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputView.tsx
  source/frontend/src/components/common/form/Input.tsx
  source/frontend/src/components/common/form/Multiselect.tsx
  source/frontend/src/components/common/form/Typeahead.tsx
  source/frontend/src/components/common/form/TypeaheadSelect.tsx
  source/frontend/src/components/common/form/YesNoSelect.tsx
  source/frontend/src/components/layout/SideNavBar/NavIcon.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/AdvancedFilterButton.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersControl.tsx
  source/frontend/src/components/maps/leaflet/Control/Legend/LegendControl.tsx
  source/frontend/src/components/maps/leaflet/Control/ZoomOut/ZoomOutButton.tsx
  source/frontend/src/features/acquisition/list/AcquisitionListView.tsx
  source/frontend/src/features/admin/access-request/AccessRequestForm.tsx
  source/frontend/src/features/admin/access/components/Filter.tsx
  source/frontend/src/features/admin/edit-user/EditUserForm.tsx
  source/frontend/src/features/admin/users/ManageUsersPage.tsx
  source/frontend/src/features/admin/users/components/UsersFilterBar.tsx
  source/frontend/src/features/advancedFilterBar/AdvancedFilterBar.tsx
  source/frontend/src/features/help/containers/HelpContainer.tsx
  source/frontend/src/features/leases/list/LeaseListView.tsx
  source/frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.tsx
  source/frontend/src/features/leases/reports/payments/ExportLeasePaymentsContainer.tsx
  source/frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/properties/components/GeocoderAutoComplete.tsx
  source/frontend/src/features/properties/filter/PropertySearchToggle.tsx
  source/frontend/src/features/properties/list/PropertyListView.tsx
  source/frontend/src/hooks/useFavicon.test.ts
  source/frontend/src/hooks/useFavicon.ts
Labels: tech-debt

#3615 Scaffold/disposition
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsDispositionFile.cs
  source/backend/entities/ef/PimsDispositionFileHist.cs
  source/backend/entities/ef/PimsDispositionFileStatusType.cs
  source/backend/entities/ef/PimsDispositionFileTeam.cs
  source/backend/entities/ef/PimsDispositionFileTeamHist.cs
  source/backend/entities/ef/PimsDispositionFundingType.cs
  source/backend/entities/ef/PimsDispositionInitiatingDocType.cs
  source/backend/entities/ef/PimsDispositionStatusType.cs
  source/backend/entities/ef/PimsDispositionType.cs
  source/backend/entities/ef/PimsDspFlTeamProfileType.cs
  source/backend/entities/ef/PimsDspInitiatingBranchType.cs
  source/backend/entities/ef/PimsDspPhysFileStatusType.cs
  source/backend/entities/ef/PimsOrganization.cs
  source/backend/entities/ef/PimsPerson.cs
  source/backend/entities/ef/PimsProperty.cs
  source/backend/entities/ef/PimsPropertyDispositionFile.cs
  source/backend/entities/ef/PimsPropertyDispositionFileHist.cs
  source/backend/entities/ef/PimsRegion.cs
Labels: db-scaffold

#3602 Added check status logic when updating acq and related entities | psp-7006
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/AcquisitionStatusTypes.cs
  source/backend/api/Constants/AgreementStatusTypes.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/TakeService.cs
  source/backend/api/Solvers/AcquisitionStatusSolver.cs
  source/backend/api/Solvers/IAcquisitionStatusSolver.cs
  source/backend/api/Startup.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/AgreementRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IAgreementRepository.cs
  source/backend/entities/Partials/Agreement.cs
  source/backend/tests/core/TestHelper.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/backend/tests/unit/api/Services/TakeServiceTest.cs
  source/backend/tests/unit/api/Solvers/AcquisitionStatusSolverTests.cs
  source/frontend/src/constants/acquisitionFileStatus.ts
  source/frontend/src/features/acquisition/hooks/useAcquisitionFileExport.ts
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.test.tsx
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.tsx
  source/frontend/src/features/acquisition/list/AcquisitionListView.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.test.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/checklist/detail/AcquisitionChecklistView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationResults.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/columns.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/update/UpdateForm8Container.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/statusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/stakeholderOrganizer.test.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/stakeholderOrganizer.ts
Labels: enhancement

#3616 PSP-7330 : Create disposition Claims
  source/backend/dal/Security/Permissions.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/77_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/78_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/075_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/76_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/77_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/051_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/074_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S68_00 - Disposition/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S68_00 - Disposition/Alter Down/77_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S68_00 - Disposition/Alter Down/78_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S68_00 - Disposition/Alter Up/075_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S68_00 - Disposition/Alter Up/76_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S68_00 - Disposition/Alter Up/77_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S68_00 - Disposition/Build/051_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S68_00 - Disposition/Build/074_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S68_00 - Disposition/Build/075_DML_PIMS_ROLE_CLAIM.sql
Labels: enhancement

#3620 Updated placeholder display
  source/frontend/src/components/common/form/FastDatePicker.tsx
  source/frontend/src/features/admin/financial-codes/add/__snapshots__/AddFinancialCodeForm.test.tsx.snap
  source/frontend/src/features/admin/financial-codes/update/__snapshots__/UpdateFinancialCodeForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/__snapshots__/ReceivedDepositForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/__snapshots__/EditInsuranceContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/__snapshots__/PaymentForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/__snapshots__/TermForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/__snapshots__/UpdateSummaryForm.test.tsx.snap
Labels: enhancement

#3623 Disposition alignment
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/AcquisitionStatusTypes.cs
  source/backend/api/Constants/AgreementStatusTypes.cs
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/TakeService.cs
  source/backend/api/Solvers/AcquisitionStatusSolver.cs
  source/backend/api/Solvers/IAcquisitionStatusSolver.cs
  source/backend/api/Startup.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/AgreementRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IAgreementRepository.cs
  source/backend/entities/Partials/Agreement.cs
  source/backend/tests/core/TestHelper.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/backend/tests/unit/api/Services/TakeServiceTest.cs
  source/backend/tests/unit/api/Solvers/AcquisitionStatusSolverTests.cs
  source/frontend/package.json
  source/frontend/src/constants/acquisitionFileStatus.ts
  source/frontend/src/features/acquisition/hooks/useAcquisitionFileExport.ts
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.test.tsx
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.tsx
  source/frontend/src/features/acquisition/list/AcquisitionListView.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.test.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/checklist/detail/AcquisitionChecklistView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationResults.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/columns.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/update/UpdateForm8Container.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/statusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/stakeholderOrganizer.test.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/stakeholderOrganizer.ts
Labels: alignment

#3625 Disposition menu
  source/frontend/src/components/layout/SideNavBar/DispositionTray.tsx
Labels: enhancement
