Repository bcgov/PSP, pull requests merged in 2023-04, with the labels that each got.

#3054 swap boundaries layer for parcels layer to reduce cpu load.
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
  source/frontend/src/tenants/ITenantConfig.ts
Labels: enhancement

#3062 bump hotfix version.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
Labels: bug, hotfix

#3055 Automation - Projects and products
  testing/PIMS.Tests.Automation/Classes/Project.cs
  testing/PIMS.Tests.Automation/Data/ExcelDataContext.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProjects.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
Labels: test-scripts

#3069 psp-5861 modifying documents should not refresh file.
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.tsx
Labels: bug

#3057 PSP-5750 : Add "Product number and name" to acquisition file header
  source/frontend/src/features/mapSideBar/tabs/HeaderField.tsx
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/properties/map/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/mocks/mockAcquisitionFiles.ts
Labels: enhancement

#3073 Re-ran scaffold | S51.00
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAgreement.cs
  source/backend/entities/ef/PimsAgreementHist.cs
  source/backend/entities/ef/PimsConsultationStatusType.cs
  source/backend/entities/ef/PimsConsultationType.cs
  source/backend/entities/ef/PimsLeaseConsultation.cs
  source/backend/entities/ef/PimsLeaseConsultationHist.cs
Labels: db-scaffold

#3065 Psp-5800 replace project region filter.
  source/frontend/src/components/common/form/UserRegionSelect/UserRegionSelectContainer.tsx
  source/frontend/src/components/common/form/UserRegionSelect/__snapshots__/UserRegionSelectContainer.test.tsx.snap
  source/frontend/src/features/projects/list/ProjectFilter/ProjectFilter.test.tsx
  source/frontend/src/features/projects/list/ProjectFilter/ProjectFilter.tsx
  source/frontend/src/features/projects/list/ProjectFilter/__snapshots__/ProjectFilter.test.tsx.snap
  source/frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
Labels: bug

#3064 psp-5920, do not select default initiator.
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/interfaces/ILease.ts
Labels: bug

#3063 psp-5910 fix consultation logic running after form reset, causing tou…
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
Labels: bug

#3066 PSP-5390_fix acquisition_linkage to proj/prod
  etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION/PAIMS_ACQUISITION_TO_PIMS_DATASET.dtsx
  etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION.dtproj
Labels: etl

#3068 make project id, rowversion fields nullable on backend.
  source/backend/api/Models/BaseModel.cs
  source/backend/api/Models/Concepts/Project/ProjectModel.cs
  source/backend/api/Services/FinancialCodeService.cs
  source/backend/api/Services/IOrganizationService.cs
  source/backend/api/Services/IPersonService.cs
  source/backend/api/Services/IResearchFileService.cs
  source/backend/api/Services/NoteService.cs
  source/backend/api/Services/OrganizationService.cs
  source/backend/api/Services/PersonService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
Labels: bug

#3072 PSP-5878 : FT: Acquisition File-Takes: Site contamination default val…
  source/frontend/src/features/mapSideBar/tabs/takes/update/models.ts
Labels: bug

#3071 PSP-5864 : FT-REG: Project's Product - Start Date is a mandatory field.
  source/frontend/src/features/properties/map/project/add/AddProjectFileYupSchema.ts
Labels: bug

#3077 PSP-5699 : FT- Reg: Actions text is not displaying for Notes table under Notes tab
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/columns.tsx
  source/frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
Labels: bug

#3056 PSP-5643 : Enhancements - acquisition file take areas
  source/backend/api/Areas/Takes/Controllers/TakeController.cs
  source/backend/api/Models/Concepts/Take/TakeMap.cs
  source/backend/api/Models/Concepts/Take/TakeModel.cs
  source/backend/api/Services/ITakeService.cs
  source/backend/api/Services/TakeService.cs
  source/backend/dal/Repositories/Interfaces/ITakeRepository.cs
  source/backend/dal/Repositories/TakeRepository.cs
  source/backend/tests/unit/api/Controllers/Takes/TakesControllerTest.cs
  source/backend/tests/unit/api/Services/TakeServiceTest.cs
  source/frontend/src/constants/takesStatusTypes.ts
  source/frontend/src/features/mapSideBar/tabs/takes/detail/TakesDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/detail/TakesDetailContainer.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/detail/__snapshots__/TakesDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/takes/repositories/useTakesRepository.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/update/TakesUpdateForm.test.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/update/TakesUpdateForm.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/takes/update/models.ts
  source/frontend/src/hooks/pims-api/useApiTakes.ts
  source/frontend/src/mocks/mockTakes.ts
  source/frontend/src/models/api/Take.ts
Labels: enhancement

#3079 fix error when submitting product with no date values.
  source/frontend/src/features/properties/map/project/models.ts
Labels: bug

#3076 PSP-5698 : FT: Acquisition File - If any name field is missing under Owner info then by default "<empty>"
  source/frontend/src/features/properties/map/acquisition/add/models.ts
  source/frontend/src/features/properties/map/acquisition/common/models.ts
Labels: bug

#3060 PSP-5759 : Enhancement - Identify "Primary Contact" on acquisition de…
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileOwnerMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileOwnerModel.cs
  source/frontend/src/components/common/buttons/RemoveButton.tsx
  source/frontend/src/features/mapSideBar/tabs/SectionField.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/models.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryView.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/models.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#3082 Backmerge test to dev
  etl/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT.dtproj
  etl/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT.dtsx
  source/backend/api/Models/BaseModel.cs
  source/backend/api/Models/Concepts/Project/ProjectModel.cs
  source/backend/api/Services/FinancialCodeService.cs
  source/backend/api/Services/IOrganizationService.cs
  source/backend/api/Services/IPersonService.cs
  source/backend/api/Services/IResearchFileService.cs
  source/backend/api/Services/NoteService.cs
  source/backend/api/Services/OrganizationService.cs
  source/backend/api/Services/PersonService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
  source/frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  source/frontend/src/features/contacts/contact/create/components/address/Address.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.test.tsx
  source/frontend/src/features/contacts/contactUtils.test.ts
  source/frontend/src/features/contacts/contactUtils.ts
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/tabs/takes/update/models.ts
  source/frontend/src/features/properties/map/acquisition/common/models.ts
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/AddProjectFileYupSchema.ts
  source/frontend/src/features/properties/map/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectForm.tsx
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/properties/map/project/hooks/useAddProjectFormManagement.tsx
  source/frontend/src/features/properties/map/project/models.ts
  source/frontend/src/hooks/useCounter.ts
Labels: release-management

#3085 bump is version in dev.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
Labels: release-management

#3090 Generated scaffold s52
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAccessRequest.cs
  source/backend/entities/ef/PimsAccessRequestHist.cs
  source/backend/entities/ef/PimsAcquisitionFile.cs
  source/backend/entities/ef/PimsAcquisitionFileHist.cs
  source/backend/entities/ef/PimsDocumentTyp.cs
  source/backend/entities/ef/PimsDocumentTypHist.cs
  source/backend/entities/ef/PimsLeaseConsultation.cs
  source/backend/entities/ef/PimsLeaseConsultationHist.cs
  source/backend/entities/ef/PimsUser.cs
  source/backend/entities/ef/PimsUserHist.cs
  source/backend/entities/ef/PimsUserType.cs
Labels: db-scaffold

#3091 psp-4632 Update description of property picker.
  source/frontend/src/components/common/mapping/SelectProperty.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/components/propertySelector/map/__snapshots__/PropertyMapSelectorSubForm.test.tsx.snap
  source/frontend/src/features/help/components/HelpModal.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
Labels: enhancement

#3088 PSP-5760 : Enhancement - Limit acquisition team to single resources
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionTeam/UpdateAcquisitionTeamSubForm.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionTeam/UpdateAcquisitionTeamYupSchema.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/mocks/mockAcquisitionFiles.ts
Labels: enhancement

#3097 Added note logic when updating research status | PSP-5874
  source/backend/api/Services/ResearchFileService.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
Labels: bug

#3096 Added text to match mockup | psp-5992
  source/frontend/src/features/properties/map/agreement/detail/AgreementView.tsx
Labels: bug

#3094 PSP-5937 : FT: Acquisition File - Registration number in the brackets next to the Corporation name is not displayed after saving the Owner Information
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryContainer.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryView.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/models.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
Labels: bug

#3099 PSP-5955 : FT-REG: Projects - User is not able to able to add/update …
  source/backend/api/Models/Concepts/Product/ProductModel.cs
Labels: bug

#3102 PSP-4090 external links
  source/frontend/src/components/layout/Footer/Footer.tsx
  source/frontend/src/components/layout/Footer/__snapshots__/Footer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
Labels: enhancement

#3103 Psp 5743 - add address to initial property when adding via map popup flyout.
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.test.tsx
  source/frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.ts
  source/frontend/src/features/properties/map/hooks/useBcaAddress.tsx
  source/frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
  source/frontend/src/hooks/useInitialMapSelectorProperties.ts
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: bug

#3105 PSP-2499 Change variable name for better readability
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Areas/Reports/Controllers/PropertyController.cs
  source/backend/api/Areas/Reports/Controllers/UserController.cs
Labels: tech-debt

#3092 Generate H0443 | psp-5711
  source/backend/api/Areas/DocumentGeneration/DocumentGenerationRequest.cs
  source/backend/api/Areas/Property/Controllers/PropertyController.cs
  source/backend/api/Constants/FormDocumentType.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePropertyMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePropertyModel.cs
  source/backend/api/Services/DocumentGenerationService.cs
  source/backend/api/Services/IDocumentGenerationService.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/dal/Constants/FormTypeCode.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/src/constants/formDocumentTypes.ts
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/hooks/useGetProperty.ts
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/hooks/useUpdateProperty.ts
  source/frontend/src/features/mapSideBar/tabs/propertyResearch/PropertyResearchTabView.test.tsx
  source/frontend/src/features/properties/list/PropertyListView.test.tsx
  source/frontend/src/features/properties/list/PropertyListView.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionView.tsx
  source/frontend/src/features/properties/map/acquisition/add/models.ts
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionMenu.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionMenu.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/GenerateFormContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/GenerateFormContainer.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/GenerateFormView.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/__snapshots__/GenerateFormContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/formDocumentEntry.ts
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH0443.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH0443.ts
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateLetter.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateLetter.ts
  source/frontend/src/features/properties/map/activity/list/ActivityResults/ActivityResults.test.tsx
  source/frontend/src/features/properties/map/research/add/models.ts
  source/frontend/src/features/properties/map/research/update/property/UpdatePropertyForm.test.tsx
  source/frontend/src/features/properties/map/research/update/property/models.ts
  source/frontend/src/features/properties/map/shared/models.ts
  source/frontend/src/features/properties/map/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/research/list/ResearchListView.test.tsx
  source/frontend/src/hooks/index.ts
  source/frontend/src/hooks/pims-api/useApiProperties.test.tsx
  source/frontend/src/hooks/pims-api/useApiProperties.ts
  source/frontend/src/hooks/repositories/useProperties.test.tsx
  source/frontend/src/hooks/repositories/useProperties.ts
  source/frontend/src/hooks/useGenerateLetter.test.tsx
  source/frontend/src/hooks/useGenerateLetter.ts
  source/frontend/src/hooks/usePropertyAssociations.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/mocks/mockProperties.ts
  source/frontend/src/mocks/mockResearchFile.ts
  source/frontend/src/models/api/PropertyFile.ts
Labels: enhancement

#3111 correction to is51 alter up, required to run alter up in test.
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S51_00/Alter Up/002_PSP_PIMS_Alter_Up.sql
Labels: bug

#3115 Backmerge test to dev
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Models/Concepts/Product/ProductModel.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Repositories/Interfaces/IProjectRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S51_00/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/frontend/src/components/common/form/UserRegionSelect/UserRegionSelectContainer.test.tsx
  source/frontend/src/components/common/form/UserRegionSelect/UserRegionSelectContainer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  source/frontend/src/components/maps/providers/MapStateContext.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/projects/list/ProjectFilter/ProjectFilter.tsx
  source/frontend/src/features/projects/list/ProjectFilter/__snapshots__/ProjectFilter.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryContainer.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryView.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/models.ts
  source/frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.test.tsx
  source/frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.ts
  source/frontend/src/features/properties/map/agreement/detail/AgreementView.tsx
  source/frontend/src/features/properties/map/hooks/useBcaAddress.tsx
  source/frontend/src/features/properties/map/research/add/AddResearchContainer.tsx
  source/frontend/src/hooks/useInitialMapSelectorProperties.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: devops

#3106 Psp 5768 add owner solicitor, also add reusable component for selecting contacts.
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileOwnerSolicitorMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileOwnerSolicitorModel.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/entities/Partials/AcquisitionFileOwnerSolicitor.cs
  source/frontend/src/components/common/form/ContactInput/ContactInputContainer.test.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputContainer.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputView.test.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputView.tsx
  source/frontend/src/components/common/form/ContactInput/__snapshots__/ContactInputContainer.test.tsx.snap
  source/frontend/src/components/common/form/ContactInput/__snapshots__/ContactInputView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/models.ts
  source/frontend/src/features/properties/map/acquisition/common/models.ts
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/AcquisitionSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/fileDetails/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/models.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#3113 Added compensation list view and related backend | psp-5953
  source/backend/api/Areas/Compensation/CompensationController.cs
  source/backend/api/Models/Concepts/Compensation/CompensationFinancialMap.cs
  source/backend/api/Models/Concepts/Compensation/CompensationFinancialModel.cs
  source/backend/api/Models/Concepts/Compensation/CompensationMap.cs
  source/backend/api/Models/Concepts/Compensation/CompensationModel.cs
  source/backend/api/Services/CompensationDocumentService.cs
  source/backend/api/Services/ICompensationService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/AcquisitionFileFormRepository.cs
  source/backend/dal/Repositories/CompensationRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRepository.cs
  source/backend/entities/Partials/CompReqH120.cs
  source/backend/entities/Partials/CompensationRequisition.cs
  source/frontend/src/features/mapSideBar/tabs/FileTabs.tsx
  source/frontend/src/features/properties/list/PropertyListView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationListView.test.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationListView.tsx
  source/frontend/src/features/properties/map/compensation/list/CompensationResults.tsx
  source/frontend/src/features/properties/map/compensation/list/__snapshots__/CompensationListContainer.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/properties/map/compensation/list/columns.tsx
  source/frontend/src/hooks/pims-api/useApiRequisitionCompensations.ts
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/mocks/mockCompensations.ts
  source/frontend/src/models/api/Compensation.ts
Labels: enhancement

#3110 Psp 5707 - agreements
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateAgreement.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/properties/map/agreement/detail/AgreementContainer.tsx
  source/frontend/src/features/properties/map/agreement/detail/AgreementView.test.tsx
  source/frontend/src/features/properties/map/agreement/detail/AgreementView.tsx
  source/frontend/src/features/properties/map/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
  source/frontend/src/features/properties/map/shared/content/models.ts
  source/frontend/src/mocks/mockAgreements.ts
  source/frontend/src/models/api/AcquisitionFile.ts
  source/frontend/src/models/api/Agreement.ts
  source/frontend/src/models/generate/GenerateAgreement.ts
  source/frontend/src/models/generate/GenerateFile.ts
  source/frontend/src/models/generate/GenerateOwner.ts
  source/frontend/src/models/generate/GeneratePerson.ts
Labels: enhancement

#3121 Bump dev version
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops
