Repository bcgov/PSP, pull requests merged in 2023-12, with the labels that each got.

#3629 psp-7336 dialog correction.
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
Labels: bug

#3624 Keycloak Refactor
  source/backend/dal.keycloak/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal.keycloak/PimsKeycloakService.cs
  source/backend/keycloak/Extensions/ServiceCollectionExtensions.cs
  source/backend/keycloak/IKeycloakRepository.cs
  source/backend/keycloak/IKeycloakService.cs
  source/backend/keycloak/KeycloakRepository.cs
  source/backend/keycloak/KeycloakService.cs
  source/backend/keycloak/Models/RoleModel.cs
  source/backend/keycloak/Partials/KeycloakServiceUsers.cs
  source/backend/tests/unit/dal/Libraries/Keycloak/KeycloakServiceTest.cs
  source/backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  source/backend/tests/unit/dal/Libraries/Keycloak/ServiceCollectionExtensionsTest.cs
  tools/core/Keycloak/Configuration/KeycloakAdminOptions.cs
  tools/core/Keycloak/Configuration/KeycloakOptions.cs
  tools/core/Keycloak/IKeycloakRequestClient.cs
  tools/core/Keycloak/KeycloakRequestClient.cs
  tools/core/Keycloak/Models/ClientModel.cs
  tools/core/Keycloak/Models/GroupModel.cs
  tools/core/Keycloak/Models/ProtocolMapperModel.cs
  tools/core/Keycloak/Models/ResponseWrapperModel.cs
  tools/core/Keycloak/Models/RoleModel.cs
  tools/core/Keycloak/Models/UserModel.cs
  tools/core/Keycloak/Models/UserRoleModel.cs
  tools/core/Keycloak/Models/UserRoleOperation.cs
  tools/core/Pims.Tools.Core.csproj
  tools/keycloak/sync/Client/IRequestClient.cs
  tools/keycloak/sync/Client/PimsRequestClient.cs
  tools/keycloak/sync/Client/RequestClient.cs
  tools/keycloak/sync/Configuration/AuthOptions.cs
  tools/keycloak/sync/Configuration/RequestOptions.cs
  tools/keycloak/sync/Configuration/ToolOptions.cs
  tools/keycloak/sync/Models/Keycloak/ClientModel.cs
  tools/keycloak/sync/Models/Keycloak/GroupModel.cs
  tools/keycloak/sync/Models/Keycloak/ProtocolMapperModel.cs
  tools/keycloak/sync/Models/Keycloak/RealmModel.cs
  tools/keycloak/sync/Models/Keycloak/RoleModel.cs
  tools/keycloak/sync/Pims.Tools.Keycloak.Sync.csproj
  tools/keycloak/sync/Pims.Tools.Keycloak.Sync.sln
  tools/keycloak/sync/Program.cs
  tools/keycloak/sync/Syncronizer/ISyncFactory.cs
  tools/keycloak/sync/Syncronizer/SyncFactory.cs
Labels: tech-debt

#3628 System error modal | psp-7304
  source/frontend/src/assets/scss/App.scss
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/components/common/CancelConfirmationModal.tsx
  source/frontend/src/components/common/ErrorModal.tsx
  source/frontend/src/components/common/ErrorTabs.tsx
  source/frontend/src/components/common/GenericModal.test.tsx
  source/frontend/src/components/common/GenericModal.tsx
  source/frontend/src/components/common/ModalContainer.test.tsx
  source/frontend/src/components/common/form/NotesModal.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/contact/ContactManagerModal.tsx
  source/frontend/src/components/layout/Header/ErrorModal.tsx
  source/frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/components/modals/roleMismatch.tsx
  source/frontend/src/contexts/modalContext.tsx
  source/frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/create/Person/CreatePersonForm.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailModal.tsx
  source/frontend/src/features/documents/documentUpload/DocumentUploadModal.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/PrimaryContactWarningModal.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/GenerateLetterRecipientsModal.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/__snapshots__/GenerateLetterRecipientsModal.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/modals/AcquisitionFormModal.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/financials/FinancialActivitiesSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/project/ProjectContainerView.tsx
  source/frontend/src/features/mapSideBar/project/add/ProductsArrayForm.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactList.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  source/frontend/src/features/notes/add/AddNotesContainer.tsx
  source/frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap
  source/frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap
  source/frontend/src/features/notes/list/NoteListView.tsx
  source/frontend/src/features/notes/update/UpdateNoteContainer.tsx
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap
  source/frontend/src/features/projects/reports/ProjectExportContainer.tsx
  source/frontend/src/hooks/useApiUserOverride.ts
  source/frontend/src/hooks/useModalContext.ts
  source/frontend/src/hooks/usePimsIdleTimer.tsx
  source/frontend/src/utils/TestCommonWrapper.tsx
Labels: enhancement

#3626 Psp 6951 - view disposition file details.
  source/backend/api/Models/Concepts/DispositionFile/DispositionFileMap.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/145_DML_PIMS_DISPOSITION_FUNDING_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S68_00 - Disposition/Build/145_DML_PIMS_DISPOSITION_FUNDING_TYPE.sql
  source/frontend/src/components/maps/leaflet/LayerPopup/styles.ts
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionSummaryView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/__snapshots__/DispositionSummaryView.test.tsx.snap
  tools/keycloak/sync/appsettings.test.json
Labels: enhancement

#3630 psp-7371 requested source marked as nullable for validation. (management activity)
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/validation.ts
Labels: bug

#3632 psp-7369 allow showing the edit screen for management activity while the popou…
  source/frontend/src/features/mapSideBar/property/PropertyRouter.tsx
Labels: bug

#3636 Bump DEV version - IS68
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3639 Disposition/menu entry
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/SideTray.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
Labels: enhancement

#3631 PSP-6948 : Create a disposition file
  source/backend/api/Areas/Disposition/Controllers/DispositionFileController.cs
  source/backend/api/Constants/EnumDispositionFileStatusTypeCode.cs
  source/backend/api/Constants/EnumDispositionStatusTypeCode.cs
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/IDispositionFileService.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileMap.cs
  source/backend/dal/Exceptions/OverrideExceptions.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IDispositionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileRepositoryTest.cs
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/constants/API.ts
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainerView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainerView.tsx
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/DispositionForm.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionTeamSubForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionTeamSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionTeamSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/hooks/useAddDispositionFormManagement.ts
  source/frontend/src/features/mapSideBar/disposition/models/AddDispositionFormYupSchema.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionFormModel.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionTeamSubFormModel.ts
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/hooks/pims-api/useApiDispositionFile.ts
  source/frontend/src/hooks/repositories/useDispositionProvider.ts
  source/frontend/src/mocks/lookups.mock.ts
  source/frontend/src/models/api/DispositionFile.ts
  source/frontend/src/models/api/UserOverrideCode.ts
Labels: enhancement

#3645 Bump DEV version - IS69
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3647 V4.1.3 66.43 hotfix
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT.sln
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT.dtproj
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT.dtproj.user
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/Package.dtsx
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/Project.params
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/public/tenants/tenant.json
  source/frontend/src/components/common/mapFSM/models.ts
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.test.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.tsx
  source/frontend/src/components/propertySelector/map/__snapshots__/PropertyMapSelectorSubForm.test.tsx.snap
  source/frontend/src/components/propertySelector/models.ts
  source/frontend/src/components/propertySelector/search/LayerFilter.test.tsx
  source/frontend/src/components/propertySelector/search/LayerFilter.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/components/propertySelector/search/__snapshots__/LayerFilter.test.tsx.snap
  source/frontend/src/components/propertySelector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap
  source/frontend/src/components/propertySelector/search/mapPropertyColumns.ts
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/repositories/mapLayer/useParcelMapLayer.ts
  source/frontend/src/hooks/repositories/useComposedProperties.ts
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/layers/parcelMapBC.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: release-management

#3649 Backmerge master to test
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT.sln
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT.dtproj
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT.dtproj.user
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/Package.dtsx
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/Project.params
  source/backend/api/Controllers/PimsGeoserverController.cs
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/public/tenants/tenant.json
  source/frontend/src/components/common/mapFSM/models.ts
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.test.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.tsx
  source/frontend/src/components/propertySelector/map/__snapshots__/PropertyMapSelectorSubForm.test.tsx.snap
  source/frontend/src/components/propertySelector/models.ts
  source/frontend/src/components/propertySelector/search/LayerFilter.test.tsx
  source/frontend/src/components/propertySelector/search/LayerFilter.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/components/propertySelector/search/__snapshots__/LayerFilter.test.tsx.snap
  source/frontend/src/components/propertySelector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap
  source/frontend/src/components/propertySelector/search/mapPropertyColumns.ts
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/repositories/mapLayer/useParcelMapLayer.ts
  source/frontend/src/hooks/repositories/useComposedProperties.ts
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/layers/parcelMapBC.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: release-management

#3650 backmerge test to dev
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT.sln
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT.dtproj
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT.dtproj.user
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/Package.dtsx
  etl/PAIMS_PIMS_ACQUISITION_PROJECT/PAIMS_PIMS_ACQUISITION_PROJECT/Project.params
  source/backend/api/Controllers/PimsGeoserverController.cs
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/public/tenants/tenant.json
  source/frontend/src/components/common/mapFSM/models.ts
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.test.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.tsx
  source/frontend/src/components/propertySelector/map/__snapshots__/PropertyMapSelectorSubForm.test.tsx.snap
  source/frontend/src/components/propertySelector/models.ts
  source/frontend/src/components/propertySelector/search/LayerFilter.test.tsx
  source/frontend/src/components/propertySelector/search/LayerFilter.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/components/propertySelector/search/__snapshots__/LayerFilter.test.tsx.snap
  source/frontend/src/components/propertySelector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap
  source/frontend/src/components/propertySelector/search/mapPropertyColumns.ts
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/repositories/mapLayer/useParcelMapLayer.ts
  source/frontend/src/hooks/repositories/useComposedProperties.ts
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/layers/parcelMapBC.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: release-management

#3651 PSP-7419 Use pre-tax amounts on H120 financial summary table
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationFinancialSummary.ts
Labels: enhancement

#3634 PSP-6952 tests
  source/backend/api/Areas/Disposition/Controllers/DispositionFileController.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/dal/Models/DispositionFilter.cs
  source/backend/tests/unit/api/Controllers/Disposition/DispositionControllerTest.cs
  source/backend/tests/unit/api/Controllers/Disposition/SearchControllerTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileRepositoryTest.cs
  source/frontend/src/features/disposition/list/DispositionFilter/DispositionFilter.test.tsx
  source/frontend/src/features/disposition/list/DispositionFilter/__snapshots__/DispositionFilter.test.tsx.snap
  source/frontend/src/features/disposition/list/DispositionListView.test.tsx
  source/frontend/src/features/disposition/list/DispositionSearchResults/DispositionSearchResults.test.tsx
  source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/mocks/lookups.mock.ts
Labels: unit-tests

#3653 psp-7280 throw error when duplicate project is created.
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Repositories/Interfaces/IProjectRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
Labels: bug

#3638 PSP-7310: Automation for Property Management Tab, new test cases for Smoke Test
  testing/PIMS.Tests.Automation/Classes/Lease.cs
  testing/PIMS.Tests.Automation/Classes/Property.cs
  testing/PIMS.Tests.Automation/Classes/ResearchFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionExpropriation.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFilesDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/ManageUsers.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3654 PSP-7438 : FT:Reg: Contacts- Primary contact is displaying " No conta…
  source/backend/api/Areas/Organizations/Controllers/OrganizationController.cs
Labels: bug

#3655 psp-7297 fix incorrect model references.
  source/backend/api/Areas/Leases/Controllers/InsuranceController.cs
  source/backend/api/Areas/Leases/Controllers/PropertyImprovementController.cs
  source/backend/api/Areas/Leases/Models/Lease/AddressModel.cs
  source/backend/api/Areas/Leases/Models/Lease/InsuranceModel.cs
  source/backend/api/Areas/Leases/Models/Lease/PropertyImprovementModel.cs
  source/backend/api/Areas/Leases/Models/Lease/PropertyModel.cs
  source/backend/api/Areas/Leases/Models/Lease/RegionModel.cs
  source/backend/api/Areas/Leases/Models/Lease/SurplusDeclarationModel.cs
  source/backend/api/Areas/Persons/Controllers/PersonController.cs
  source/backend/tests/unit/api/Controllers/Leases/LeaseControllerTest.cs
  source/backend/tests/unit/api/Controllers/Leases/LeaseImprovementControllerTest.cs
  source/backend/tests/unit/api/Controllers/Leases/LeasePaymentControllerTest.cs
  source/backend/tests/unit/api/Controllers/Leases/LeaseTenantControllerTest.cs
  source/backend/tests/unit/api/Controllers/Leases/LeaseTermControllerTest.cs
Labels: bug

#3656 psp-7431 correct schema warning.
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/CompensationRequisitionYupSchema.ts
Labels: bug

#3657 PSP-7412 : FT-REG: Property Management Tab - ETL only: When a user updates an activity, a 400 error is displayed
  source/backend/api/Areas/Property/Controllers/PropertyActivityController.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/tests/unit/api/Services/PropertyServiceTest.cs
Labels: bug

#3643 Updated Document Upload and details
  source/frontend/src/components/common/GenericModal.tsx
  source/frontend/src/components/common/Section/Section.tsx
  source/frontend/src/components/common/form/FileDragAndDrop.tsx
  source/frontend/src/features/documents/ComposedDocument.ts
  source/frontend/src/features/documents/DocumentMetadataYupSchema.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailHeader.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailForm.test.tsx.snap
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailView.test.tsx.snap
  source/frontend/src/features/documents/documentUpload/DocumentUploadContainer.tsx
  source/frontend/src/features/documents/documentUpload/DocumentUploadForm.test.tsx
  source/frontend/src/features/documents/documentUpload/DocumentUploadForm.tsx
  source/frontend/src/features/documents/documentUpload/DocumentUploadModal.tsx
  source/frontend/src/features/documents/documentUpload/__snapshots__/DocumentUploadForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/__snapshots__/GenerateLetterRecipientsModal.test.tsx.snap
  source/frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap
  source/frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap
Labels: enhancement

#3658 PSP-7441: FT-REG: Lease & License - Unable to create new licenses
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/tests/unit/api/Controllers/Leases/LeaseControllerTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/dal/Repositories/LeaseRepositoryTest.cs
Labels: bug

#3641 PSP-7305 : Update deposit modal styling (lease/license)
  source/frontend/src/components/common/GenericModal.tsx
  source/frontend/src/components/common/styles.ts
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositModal.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/__snapshots__/ReceivedDepositForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnedDepositModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermModal.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/__snapshots__/GenerateLetterRecipientsModal.test.tsx.snap
  source/frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap
  source/frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap
Labels: enhancement

#3665 Fixed comp reqs delete not working | psp-7428
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/TakeService.cs
  source/frontend/src/features/properties/map/form/list/FormResults.tsx
  source/frontend/src/features/properties/map/form/list/__snapshots__/FormListView.test.tsx.snap
Labels: bug

#3661 PSP-7393 : FT:Reg:Lease/License Files:Map Filter: Lease file with lease expiry date or lease term expiry date is Blank and the property associated with this file should pop up on the lease filter
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
Labels: bug

#3667 Parcelmap error handling | psp-7416
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/hooks/layer-api/useWfsLayer.ts
  source/frontend/src/hooks/repositories/mapLayer/useParcelMapLayer.ts
Labels: enhancement

#3672 PSP-6954 disposition documents
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/FileType.cs
  source/backend/api/Services/DocumentFileService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/Services/IDocumentFileService.cs
  source/backend/apimodels/CodeType/DocumentRelationType.cs
  source/backend/apimodels/Models/Concepts/Document/DocumentRelationshipMap.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/DispositionFileDocumentRepository.cs
  source/backend/dal/Repositories/DocumentRepository.cs
  source/backend/dal/Repositories/Interfaces/IDispositionFileDocumentRepository.cs
  source/backend/entities/Partials/DispositionFileDocument.cs
  source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileDocumentRepositoryTest.cs
  source/frontend/src/constants/documentRelationshipType.ts
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/tabs/DocumentsTab.tsx
Labels: enhancement

#3673 Psp 6955 disposition notes.
  source/backend/api/Constants/NoteType.cs
  source/backend/api/Services/NoteService.cs
  source/backend/apimodels/Models/Concepts/Note/EntityNoteModelMap.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/IEntityNoteRepository.cs
  source/backend/entities/Partials/DispositionFileNote.cs
  source/backend/tests/core/Entities/NoteHelper.cs
  source/backend/tests/unit/api/Services/NoteServiceTest.cs
  source/backend/tests/unit/dal/Repositories/NoteRepositoryTest.cs
  source/frontend/src/constants/noteTypes.ts
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.tsx
  source/frontend/src/features/notes/list/NoteListView.tsx
Labels: enhancement

#3674 version bump for release.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
Labels: release-management

#3680 Bump DEV version - IS70
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: release-management

#3675 PSP-7269 create disposition from map popup
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.test.tsx
Labels: enhancement

#3669 PSP-7247 : View disposition file (offers and sale)
  source/backend/api/Areas/Disposition/Controllers/DispositionFileController.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/IDispositionFileService.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileModel.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileOfferMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileOfferModel.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileSaleMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileSaleModel.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserAgentMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserAgentModel.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserModel.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserSolicitorMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserSolicitorModel.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IDispositionFileRepository.cs
  source/backend/entities/Partials/DispositionFileOffer.cs
  source/backend/entities/Partials/DispositionFileOfferStatusTypeCode.cs
  source/backend/entities/Partials/DispositionFileSale.cs
  source/backend/entities/Partials/DispositionSalePurchaser.cs
  source/backend/entities/Partials/DispositionSalePurchaserAgent.cs
  source/backend/entities/Partials/DispositionSalePurchaserSolicitor.cs
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/models/DispositionFormModel.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionOfferFormModel.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionSaleFormModel.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionSalePurchaserModel.ts
  source/frontend/src/features/mapSideBar/disposition/router/DispositionRouter.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainerView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainerView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/__snapshots__/OffersAndSaleContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/add/AddDispositionOfferContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/__snapshots__/DispositionOfferDetails.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionSaleContactDetails/DispositionSaleContactDetails.tsx
  source/frontend/src/hooks/pims-api/useApiDispositionFile.ts
  source/frontend/src/hooks/repositories/useDispositionProvider.ts
  source/frontend/src/mocks/dispositionFiles.mock.ts
  source/frontend/src/models/api/DispositionFile.ts
  source/frontend/src/utils/formUtils.ts
Labels: enhancement
