Repository bcgov/PSP, pull requests merged in 2023-03, with the labels that each got.

#2944 Fixed issue with no pin or pid warning
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
Labels: bug

#2907 psp-5194 download document does not show download progress.
  source/frontend/src/features/documents/DownloadDocumentButton.tsx
Labels: bug

#2945 PSP-5050 Lease file - add/update/view project details
  source/backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  source/backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  source/backend/api/Models/Concepts/Lease/LeaseMap.cs
  source/backend/api/Models/Concepts/Lease/LeaseModel.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/frontend/src/features/leases/add/LeaseDetailSubForm.test.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/LeasePageForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailTermInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailTermInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/Improvements.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/ImprovementsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/styles.ts
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/Insurance.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/ViewTenantForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/Tenant.test.tsx.snap
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/interfaces/ILease.ts
  source/frontend/src/models/api/Lease.ts
Labels: enhancement

#2953 Backmerge test to dev
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DocumentGenerationService.cs
  source/backend/dal/Repositories/DocumentRepository.cs
  source/backend/dal/Repositories/Interfaces/IDocumentRepository.cs
  source/backend/tests/core/Entities/AcquisitionFileHelper.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionFileYupSchema.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionFileYupSchema.ts
  source/frontend/src/hooks/pims-api/useApiDocumentGeneration.ts
  source/frontend/src/mocks/mockDocuments.ts
Labels: devops

#2933 Psp 5503 display warning when removing a property from an acq file that has takes/activities associated.
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePropertyMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePropertyModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/backend/tests/unit/api/Controllers/Acquisition/AcquisitionControllerTest.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
  source/frontend/src/components/common/GenericModal.tsx
  source/frontend/src/features/properties/map/MapRouter.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionView.tsx
  source/frontend/src/features/properties/map/acquisition/ViewSelector.tsx
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/AcquisitionPropertiesSubForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AcquisitionPropertiesSubForm.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/hooks/useAcquisitionProvider.ts
  source/frontend/src/features/properties/map/research/ResearchContainer.tsx
  source/frontend/src/features/properties/map/shared/detail/AgreementForm.tsx
  source/frontend/src/features/properties/map/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/properties/map/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/properties/map/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/models/api/PropertyFile.ts
Labels: enhancement

#2943 Fixes to the Lease view screen
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertiesInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/shared/detail/AgreementForm.tsx
  source/frontend/src/interfaces/ILease.ts
Labels: bug

#2966 Bump DEV version to IS49
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2930 Psp 5577 - display error for duplicate acquisition staff.
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/hooks/useAddAcquisitionFormManagement.ts
Labels: bug

#2978 Added modal warning if there is a missmatch between claims
  source/backend/api/Controllers/AuthController.cs
  source/backend/api/Models/Auth/UserModel.cs
  source/backend/dal/Repositories/Interfaces/IUserRepository.cs
  source/backend/dal/Repositories/UserRepository.cs
  source/frontend/src/App.tsx
  source/frontend/src/components/modals/roleMismatch.tsx
  source/frontend/src/interfaces/IUser.ts
  source/frontend/src/mocks/filterDataMock.ts
Labels: enhancement

#2982 fix missing include for projects when getting lease.
  source/backend/dal/Repositories/LeaseRepository.cs
Labels: bug

#2986 Psp 5626 create geoserver map proxy within the PIMS api
  source/backend/api/Configuration/GeoserverProxyOptions.cs
  source/backend/api/Controllers/PimsGeoserverController.cs
  source/backend/api/Pims.Api.csproj
  source/backend/api/Startup.cs
  source/backend/api/appsettings.Local.json
  source/backend/api/appsettings.json
  source/frontend/src/features/mapSideBar/tabs/bcAssessment/BcAssessmentTabView.test.tsx
  source/frontend/src/features/mapSideBar/tabs/bcAssessment/BcAssessmentTabView.tsx
  source/frontend/src/hooks/useBcAssessmentLayer.ts
  source/frontend/src/setupProxy.js
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_VW/layer.xml
Labels: enhancement

#2980 PSP-5633 : FT: Acquisition File - Informative text is not populating under Owners header
  source/frontend/src/components/common/styles.ts
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
Labels: bug

#2990 Fixed products loading recursive references
  source/backend/api/Models/Concepts/Product/ProductMap.cs
Labels: bug

#2991 S49_01 scaffold generation
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcqChklstItemType.cs
  source/backend/entities/ef/PimsAcqChklstSectionType.cs
Labels: db-scaffold

#2989 PSP-5583 : Project selection lookahead - they need to search in both project number and name
  source/backend/dal/Repositories/ProjectRepository.cs
  source/frontend/src/hooks/useProjectTypeahead.ts
Labels: enhancement

#2987 Fixed acq creation with properties | PSP-5685
  source/backend/api/Services/AcquisitionFileService.cs
Labels: bug

#2994 S49_02 scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsDocumentTyp.cs
  source/backend/entities/ef/PimsDocumentTypHist.cs
  source/backend/entities/ef/PimsLease.cs
  source/backend/entities/ef/PimsLeaseHist.cs
Labels: db-scaffold

#2992 PSP-5509 Contacts - Mailing Address not saved when 'Other' Country Selected
  source/backend/api/Areas/Contacts/Mapping/Contact/AddressMap.cs
  source/backend/api/Models/Contact/AddressModel.cs
  source/frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.test.tsx
  source/frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/create/Person/CreatePersonForm.test.tsx
  source/frontend/src/features/contacts/contact/detail/Organization.test.tsx
  source/frontend/src/features/contacts/contact/detail/Organization.tsx
  source/frontend/src/features/contacts/contact/detail/Person.test.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.tsx
  source/frontend/src/features/contacts/contact/utils/contactUtils.ts
  source/frontend/src/features/contacts/contactUtils.ts
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/models.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersYupSchema.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/__snapshots__/UpdateAcquisitionOwnersSubForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionFileYupSchema.ts
  source/frontend/src/interfaces/IContact.ts
Labels: bug

#2977 PSP-5431 : Project: Documents
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/DocumentRelationType.cs
  source/backend/api/Constants/FileType.cs
  source/backend/api/Models/Concepts/Document/DocumentRelationshipMap.cs
  source/backend/api/Services/DocumentFileService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/Services/IDocumentFileService.cs
  source/backend/dal/Repositories/DocumentRepository.cs
  source/backend/dal/Repositories/Interfaces/IDocumentRepository.cs
  source/backend/dal/Repositories/Interfaces/IProjectRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/entities/Partials/ProjectDocument.cs
  source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
  source/frontend/src/constants/documentRelationshipType.ts
  source/frontend/src/features/properties/map/project/ProjectTabs.tsx
  source/frontend/src/features/properties/map/project/ViewSelector.tsx
  source/frontend/src/features/properties/map/project/detail/ProjectTabsContainer.test.tsx
  source/frontend/src/features/properties/map/project/detail/ProjectTabsContainer.tsx
  source/frontend/src/features/properties/map/project/detail/__snapshots__/ProjectTabsContainer.test.tsx.snap
Labels: enhancement

#2993 Psp 5626 - fix to geoserver proxy based on testing in dev.
  source/backend/api/Controllers/PimsGeoserverController.cs
Labels: bug

#2984 Psp 3761 admin access request screen corrections.
  source/frontend/src/features/admin/access-request/AccessRequestContainer.tsx
  source/frontend/src/features/admin/access-request/AdminAccessRequestPage.tsx
Labels: bug

#2983 psp-5679 product duplication fix.
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Repositories/Interfaces/IProductRepository.cs
  source/backend/dal/Repositories/ProductRepository.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/backend/tests/unit/dal/Repositories/ProductRepositoryTest.cs
Labels: bug

#3004 Backmerge test to dev
  source/backend/api/Models/Concepts/Product/ProductMap.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Repositories/Interfaces/IProductRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/ProductRepository.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/backend/tests/unit/dal/Repositories/ProductRepositoryTest.cs
  source/frontend/src/components/common/styles.ts
  source/frontend/src/features/admin/access-request/AccessRequestContainer.tsx
  source/frontend/src/features/admin/access-request/AdminAccessRequestPage.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
Labels: devops

#3003 Lease and Licenses automation - new cases
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseSurplus.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
Labels: test-scripts

#3012 PSP-5209 Project and Product Change
  etl/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT.sln
  etl/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT.dtproj
  etl/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT.dtproj.user
  etl/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT.dtsx
  etl/PAIMS_PIMS_PROJECT_PRODUCT/PAIMS_PIMS_PROJECT_PRODUCT/Project.params
Labels: etl

#3016 add claims for forms.
  source/backend/dal/Security/Permissions.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/074_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S50_00/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S50_00/Alter Down/77_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S50_00/Alter Up/76_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S50_00/Alter Up/77_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S50_00/Build/074_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S50_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/frontend/src/constants/claims.ts
Labels: enhancement

#3019 PSP-5690 : Enhancement - Owner information on acquisition details
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileOwnerMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileOwnerModel.cs
  source/frontend/src/features/properties/map/acquisition/common/models.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersYupSchema.ts
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/models.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#3023 Automation - Suppress Activities feature, Acquisition Files - Documents Tab
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/AdminTools.feature
  testing/PIMS.Tests.Automation/Features/AdminTools.feature.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/PageObjects/Activities.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedDocumentsTab.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ActivitiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/NotesSteps.cs
Labels: test-scripts

#3010 Testing DB Scripts
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
  testing/Testing DB Scripts/MANUAL TESTING SCRIPTS.sql
Labels: test-scripts

#3026 bump version to 3.2 for release.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
Labels: devops

#3029 PSP-5778 : Lease/License document upload using new data model and not…
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/FileType.cs
  source/backend/api/Models/Concepts/Document/DocumentRelationshipMap.cs
  source/backend/api/Services/DocumentFileService.cs
  source/backend/api/Services/DocumentLeaseService.cs
  source/backend/api/Services/IDocumentFileService.cs
  source/backend/api/Services/IDocumentLeaseService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Repositories/DocumentRepository.cs
  source/backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/entities/Partials/LeaseDocument.cs
  source/backend/entities/Partials/ProjectDocument.cs
  source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
Labels: enhancement

#3021 Lease Consultations | features/psp 4715
  source/backend/api/Areas/Leases/Mapping/Lease/LeaseMap.cs
  source/backend/api/Areas/Leases/Models/Lease/LeaseModel.cs
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Models/Concepts/Lease/ConsultationLeaseMap.cs
  source/backend/api/Models/Concepts/Lease/ConsultationLeaseModel.cs
  source/backend/api/Models/Concepts/Lease/LeaseMap.cs
  source/backend/api/Models/Concepts/Lease/LeaseModel.cs
  source/backend/api/Models/ExternalResult.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/dal/Repositories/ResearchFilePropertyRepository.cs
  source/backend/dal/Repositories/ResearchFileRepository.cs
  source/backend/entities/Partials/ConsultationStatusType.cs
  source/backend/entities/Partials/ConsultationType.cs
  source/backend/entities/Partials/LeaseConsultation.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/AddLeaseForm.tsx
  source/frontend/src/features/leases/add/ConsultationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailConsultation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/tabs/ltsa/LtsaDuplicateTitleSubForm.tsx
  source/frontend/src/interfaces/ILease.ts
  source/frontend/src/mocks/mockLease.ts
  source/frontend/src/mocks/mockLookups.ts
  source/frontend/src/models/api/Lease.ts
  source/frontend/src/utils/formUtils.ts
Labels: enhancement

#3031 correct inaccurate duplicate property warning.
  source/frontend/src/components/propertySelector/MapSelectorContainer.tsx
Labels: bug

#3028 Enable/Disable 'Duplicate' Lease Status Type
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/073_DML_PIMS_LEASE_STATUS_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/073_DML_PIMS_LEASE_STATUS_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S49_02/Alter Down/073_DML_PIMS_LEASE_STATUS_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S49_02/Alter Up/073_DML_PIMS_LEASE_STATUS_TYPE_Alter_Up.sql
Labels: db-migration

#3032 psp-4813 research file notes.
  source/backend/api/Constants/NoteType.cs
  source/backend/api/Models/Concepts/Note/EntityNoteModelMap.cs
  source/backend/api/Services/NoteService.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/IEntityNoteRepository.cs
  source/backend/entities/Partials/ResearchFileNote.cs
  source/backend/tests/core/Entities/NoteHelper.cs
  source/backend/tests/unit/api/Services/NoteServiceTest.cs
  source/frontend/src/constants/noteTypes.ts
  source/frontend/src/features/properties/map/research/ResearchTabsContainer.test.tsx
  source/frontend/src/features/properties/map/research/ResearchTabsContainer.tsx
  source/frontend/src/features/properties/map/research/__snapshots__/ResearchTabsContainer.test.tsx.snap
Labels: enhancement

#3033 IS49 bug fixes: PSP-5787, PSP-4486
  source/frontend/src/features/notes/list/NoteListView.test.tsx
  source/frontend/src/features/notes/list/NoteListView.tsx
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  source/frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/mocks/mockNoteResponses.ts
Labels: bug

#3027 Checklist Items Type Changes
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/121_DML_PIMS_ACQ_CHKLST_ITEM_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/121_DML_PIMS_ACQ_CHKLST_ITEM_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/121_DML_PIMS_ACQ_CHKLST_ITEM_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S50_00/Alter Down/121_DML_PIMS_ACQ_CHKLST_ITEM_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S50_00/Alter Up/121_DML_PIMS_ACQ_CHKLST_ITEM_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S50_00/Build/121_DML_PIMS_ACQ_CHKLST_ITEM_TYPE.sql
Labels: db-migration

#3018 psp-5749 ensure that document list view updates file, document list w…
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/properties/map/activity/list/ActivityListView.tsx
  source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
  source/frontend/src/features/properties/map/research/ResearchContainer.tsx
Labels: bug

#3035 Fixed bad casting or region filter | psp-5757
  source/backend/dal/Repositories/ProjectRepository.cs
Labels: bug

#3037 psp-4429 clear todo, replace with documentation.
  source/backend/keycloak/KeycloakService.cs
  source/backend/ltsa/Models/TitleOrder.cs
  source/backend/tests/core/TestHelper.cs
  source/frontend/src/components/common/TooltipWrapper.tsx
  source/frontend/src/components/maps/BasemapToggle.tsx
Labels: documentation

#3039 PSP-5788 BVT: Not able to delete a note
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/76_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S49_02/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S49_02/Alter Up/76_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S49_02/Build/075_DML_PIMS_ROLE_CLAIM.sql
Labels: bug

#2917 psp-4629 migrate projects api/frontend to return nullable fields from…
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/core/Json/NullJsonResultFilter.cs
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailTermInformation.test.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/projects/list/ProjectSearchResults/models.ts
  source/frontend/src/features/properties/map/acquisition/add/models.ts
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/features/properties/map/project/ProjectContainer.tsx
  source/frontend/src/features/properties/map/project/add/ProductsArrayForm.tsx
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/properties/map/project/detail/ProjectProductView.tsx
  source/frontend/src/features/properties/map/project/models.ts
  source/frontend/src/features/properties/map/research/common/models.ts
  source/frontend/src/interfaces/IProject.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/mocks/mockProjects.ts
  source/frontend/src/mocks/mockResearchFile.ts
  source/frontend/src/models/api/ConcurrentVersion.ts
  source/frontend/src/models/api/Project.ts
  source/frontend/src/utils/formUtils.ts
  source/frontend/src/utils/numberFormatUtils.ts
  source/frontend/src/utils/projectUtils.ts
  source/frontend/src/utils/utils.ts
Labels: enhancement

#2997 psp-5476 allow document type to be specified in Mayan sync JSON.
  source/backend/api/Controllers/SyncMayanController.cs
  source/backend/api/Models/Concepts/Document/DocumentTypeSyncResponse.cs
  source/backend/api/Models/Mayan/PimsSync/DocumentTypeModel.cs
  source/backend/api/Services/DocumentSyncService.cs
  source/backend/api/Services/IDocumentSyncService.cs
  source/backend/dal/Repositories/DocumentTypeRepository.cs
  source/backend/dal/Repositories/Interfaces/IDocumentTypeRepository.cs
Labels: enhancement

#3025 Psp 5584 form tab on acq file, ability to add a form based on type to acq file
  source/backend/api/Areas/Forms/Controllers/FormController.cs
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Models/Concepts/Form/FileFormModel.cs
  source/backend/api/Models/Concepts/Form/FormFileMap.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/Services/FormService.cs
  source/backend/api/Services/IFormService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/AcquisitionFileFormRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileFormRepository.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/entities/AcquisitionFileForm.cs
  source/backend/entities/Partials/FormType.cs
  source/backend/tests/unit/api/Controllers/Forms/FormControllerTest.cs
  source/backend/tests/unit/api/Services/FormServiceTest.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.test.tsx
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/form/list/AddForm.tsx
  source/frontend/src/features/properties/map/form/list/FormListView.test.tsx
  source/frontend/src/features/properties/map/form/list/FormListView.tsx
  source/frontend/src/features/properties/map/form/list/FormListViewContainer.test.tsx
  source/frontend/src/features/properties/map/form/list/FormListViewContainer.tsx
  source/frontend/src/features/properties/map/form/list/__snapshots__/FormListView.test.tsx.snap
  source/frontend/src/features/properties/map/form/list/__snapshots__/FormListViewContainer.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiForm.ts
  source/frontend/src/hooks/repositories/useFormRepository.tsx
  source/frontend/src/mocks/mockLookups.ts
  source/frontend/src/models/api/Form.ts
Labels: enhancement

#3036 Fixed upgrade script
  source/database/mssql/scripts/dbscripts/db-upgrade.sh
  source/database/mssql/scripts/dbscripts/deploy.sh
Labels: tech-debt

#3040 PSP-5742 : FT: CDOGS Templates - 403 error thrown when navigating to CDOGs Template feature
  source/frontend/src/AppRouter.tsx
  source/frontend/src/components/layout/SideNavBar/AdminTools.tsx
  source/frontend/src/features/admin/document-template/DocumentTemplateManagementContainer.tsx
  source/frontend/src/features/admin/document-template/__snapshots__/DocumentTemplateManagementContainer.test.tsx.snap
Labels: bug

#3042 Automation - Contacts refactoring and Implementing ExcelSheetData reader
  testing/PIMS.Tests.Automation/Classes/Contact.cs
  testing/PIMS.Tests.Automation/Data/ExcelDataContext.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
Labels: test-scripts

#3043 bump webpack version.
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: dependencies

#3051 Bump DEV to IS51
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3044 psp-5585 add form list view, popup display of form data.
  source/backend/api/Areas/FormDocument/FormDocumentController.cs
  source/backend/api/Models/Concepts/FormDocument/FormDocumentFileModel.cs
  source/backend/api/Services/FormDocumentService.cs
  source/backend/api/Services/IFormDocumentService.cs
  source/backend/dal/Repositories/AcquisitionFileFormRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileFormRepository.cs
  source/backend/tests/unit/api/Controllers/Forms/FormDocumentControllerTest.cs
  source/backend/tests/unit/api/Services/FormDocumentServiceTest.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionFileFormRepositoryTest.cs
  source/frontend/package.json
  source/frontend/src/components/common/styles.ts
  source/frontend/src/features/properties/map/MapView.tsx
  source/frontend/src/features/properties/map/PopupRouter.tsx
  source/frontend/src/features/properties/map/activity/ActivityTray/ActivityTray.tsx
  source/frontend/src/features/properties/map/activity/ActivityTray/styles.ts
  source/frontend/src/features/properties/map/activity/detail/ActivityContainer.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityForm.tsx
  source/frontend/src/features/properties/map/form/detail/FormContainer.tsx
  source/frontend/src/features/properties/map/form/detail/FormView.tsx
  source/frontend/src/features/properties/map/form/list/FormFilter.tsx
  source/frontend/src/features/properties/map/form/list/FormListView.test.tsx
  source/frontend/src/features/properties/map/form/list/FormListView.tsx
  source/frontend/src/features/properties/map/form/list/FormListViewContainer.test.tsx
  source/frontend/src/features/properties/map/form/list/FormListViewContainer.tsx
  source/frontend/src/features/properties/map/form/list/FormResults.tsx
  source/frontend/src/features/properties/map/form/list/__snapshots__/FormListView.test.tsx.snap
  source/frontend/src/features/properties/map/form/list/__snapshots__/FormListViewContainer.test.tsx.snap
  source/frontend/src/features/properties/map/form/list/columns.tsx
  source/frontend/src/features/properties/map/shared/content/formContent.tsx
  source/frontend/src/features/properties/map/shared/content/models.ts
  source/frontend/src/hooks/pims-api/useApiFormDocument.ts
  source/frontend/src/hooks/repositories/useFormDocumentRepository.ts
  source/frontend/src/interfaces/IFormResults.ts
  source/frontend/src/mocks/mockForm.ts
  source/frontend/src/mocks/mockLookups.ts
  source/frontend/src/models/api/FormDocument.ts
  source/frontend/src/utils/propertyUtils.ts
Labels: enhancement

#3052 psp-5722 set global mapster default to prevent recursion.
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileChecklistItemMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileChecklistItemTypeMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePersonMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFilePropertyMap.cs
  source/backend/api/Models/Concepts/ActivityInstance/ActivityInstanceMap.cs
  source/backend/api/Models/Concepts/ActivityInstance/ActivityTemplateMap.cs
  source/backend/api/Models/Concepts/Document/DocumentMap.cs
  source/backend/api/Models/Concepts/Document/DocumentRelationshipMap.cs
  source/backend/api/Models/Concepts/Document/DocumentTypeMap.cs
  source/backend/api/Models/Concepts/Lease/ConsultationLeaseMap.cs
  source/backend/api/Models/Concepts/Lease/LeaseMap.cs
  source/backend/api/Models/Concepts/Lease/PropertyLeaseMap.cs
  source/backend/api/Models/Concepts/Note/EntityNoteModelMap.cs
  source/backend/api/Models/Concepts/Note/NoteMap.cs
  source/backend/api/Models/Concepts/Organization/OrganizationMap.cs
  source/backend/api/Models/Concepts/Organization/OrganizationPersonMap.cs
  source/backend/api/Models/Concepts/Person/PersonMap.cs
  source/backend/api/Models/Concepts/Person/PersonOrganizationMap.cs
  source/backend/api/Models/Concepts/Product/ProductMap.cs
  source/backend/api/Models/Concepts/Project/ProjectMap.cs
  source/backend/api/Models/Concepts/Property/PropertyAdjacentLandMap.cs
  source/backend/api/Models/Concepts/Property/PropertyAnomalyMap.cs
  source/backend/api/Models/Concepts/Property/PropertyRoadMap.cs
  source/backend/api/Models/Concepts/Property/PropertyTenureMap.cs
  source/backend/api/Models/Concepts/ResearchFile/PropertyPurposeMap.cs
  source/backend/api/Models/Concepts/ResearchFile/ResearchFileMap.cs
  source/backend/api/Models/Concepts/ResearchFile/ResearchFileProjectMap.cs
  source/backend/api/Models/Concepts/ResearchFile/ResearchFilePropertyMap.cs
  source/backend/api/Models/Concepts/ResearchFile/ResearchFilePurposeMap.cs
  source/backend/api/Models/Concepts/Role/RoleClaimMap.cs
  source/backend/api/Models/Concepts/User/RegionUserMap.cs
  source/backend/api/Models/Concepts/User/UserMap.cs
  source/backend/api/Models/Concepts/User/UserRoleMap.cs
  source/backend/api/Startup.cs
Labels: enhancement

#3053 PSP-5807 Move delete product button to the top of each section
  source/frontend/src/features/properties/map/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/properties/map/project/add/ProductsArrayForm.tsx
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
Labels: enhancement
