Repository bcgov/PSP, pull requests merged in 2023-02, with the labels that each got.

#2758 HOTFIX: Psp 5385 fix bc assessment data load when no props given.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/hooks/useBcAssessmentLayer.ts
Labels: bug, hotfix

#2763 Digital Documents automation
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/PageObjects/Activities.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFile.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ActivitiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#2762 Psp 3914 documents for research and acquisition files.
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/DocumentRelationType.cs
  source/backend/api/Models/Concepts/Document/DocumentRelationshipMap.cs
  source/backend/api/Services/DocumentActivityService.cs
  source/backend/api/Services/DocumentFileService.cs
  source/backend/api/Services/IDocumentActivityService.cs
  source/backend/api/Services/IDocumentFileService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/AcquisitionFileDocumentRepository.cs
  source/backend/dal/Repositories/DocumentActivityRepository.cs
  source/backend/dal/Repositories/DocumentRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileDocumentRepository.cs
  source/backend/dal/Repositories/Interfaces/IDocumentActivityRepository.cs
  source/backend/dal/Repositories/Interfaces/IResearchFileDocumentRepository.cs
  source/backend/dal/Repositories/ResearchFileDocumentRepository.cs
  source/backend/entities/Partials/AcquisitionFileDocument.cs
  source/backend/entities/Partials/FileDocument.cs
  source/backend/entities/Partials/ResearchFileDocument.cs
  source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionFileDocumentRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ResearchFileRepositoryTest.cs
  source/frontend/src/components/common/SectionListHeader.tsx
  source/frontend/src/constants/documentRelationshipType.ts
  source/frontend/src/features/documents/ComposedDocument.ts
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/documents/__snapshots__/DocumentsPage.test.tsx.snap
  source/frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionDocumentsTab.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/ResearchTabsContainer.test.tsx
  source/frontend/src/features/properties/map/research/ResearchTabsContainer.tsx
  source/frontend/src/features/properties/map/research/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/detail/ResearchDocumentsTab.tsx
Labels: enhancement

#2751 PSP:5333 - Lease Term exercised in PAIMS_PIMS_LEASE
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE.dtproj
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE.dtproj.user
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE/PAIMS_PIMS_LOAD.dtsx
Labels: etl

#2757 PSP-4514 : Create Project
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/add/models.ts
  source/frontend/src/mocks/mockProjects.ts
Labels: bug

#2769 Backmerge master to test
  openshift/s2i/nginx-runtime/nginx.conf.template
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
  source/frontend/src/hooks/useBcAssessmentLayer.ts
Labels: devops

#2770 PSP-4086, PSP-5236: UI tweaks to left nav in Research, Acquisition File
  source/frontend/src/assets/images/edit-map-marker.svg
  source/frontend/src/components/common/EditButton.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionMenu.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionMenu.tsx
  source/frontend/src/features/properties/map/acquisition/common/__snapshots__/AcquisitionMenu.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/research/ResearchContainer.tsx
  source/frontend/src/features/properties/map/research/ResearchTabsContainer.tsx
  source/frontend/src/features/properties/map/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/common/ResearchMenu.test.tsx
  source/frontend/src/features/properties/map/research/common/ResearchMenu.tsx
  source/frontend/src/features/properties/map/research/common/__snapshots__/ResearchMenu.test.tsx.snap
Labels: enhancement

#2778 Backmerge test to dev
  openshift/s2i/nginx-runtime/nginx.conf.template
  source/backend/api/Areas/Notes/Controllers/NoteController.cs
  source/backend/api/Services/INoteService.cs
  source/backend/api/Services/NoteService.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/tests/unit/dal/Repositories/NoteRepositoryTest.cs
  source/frontend/src/components/Table/PageSizeSelector.tsx
  source/frontend/src/components/Table/Table.test.tsx
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  source/frontend/src/components/Table/types.ts
  source/frontend/src/components/common/form/TableSelect.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeastTenantListView.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/PrimaryContactWarningModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantOrganizationContactInfo.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantPersonContactInfo.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/ViewTenantForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
  source/frontend/src/hooks/useBcAssessmentLayer.ts
  source/frontend/src/mocks/mockContacts.ts
Labels: devops

#2789 Fix DB migration scripts
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S46_00/Alter Up/002_PSP_PIMS_Alter_Up.sql
Labels: bug, db-migration

#2790 Backmerge test to dev
  source/backend/api/Pims.Api.csproj
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S46_00/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/frontend/package.json
Labels: alignment

#2794 Bump DEV version
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2780 fix uat appsettings
  tools/keycloak/sync/appsettings.uat.json
Labels: bug

#2793 psp-5448 re-add missing loading flag to properties load.
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
  source/frontend/src/features/documents/ComposedDocument.ts
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
Labels: bug

#2786 psp-5391 (git action performance) jest update, github action processor usage improvement.
  .github/workflows/app-react.yml
  source/backend/tests/unit/dal/Repositories/AcquisitionFileDocumentRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ResearchFileDocumentRepositoryTest.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: tech-debt

#2771 PSP-5038 : Edit Project Details
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Models/Concepts/Project/ProjectModel.cs
  source/backend/api/Services/IProjectService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Repositories/Interfaces/IProjectRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/src/features/properties/map/project/ProjectContainer.tsx
  source/frontend/src/features/properties/map/project/ProjectContainerView.test.tsx
  source/frontend/src/features/properties/map/project/ProjectContainerView.tsx
  source/frontend/src/features/properties/map/project/ViewSelector.tsx
  source/frontend/src/features/properties/map/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectForm.tsx
  source/frontend/src/features/properties/map/project/add/ProductSubForm.tsx
  source/frontend/src/features/properties/map/project/add/ProductsArrayForm.tsx
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/properties/map/project/common/ProjectHeader.test.tsx
  source/frontend/src/features/properties/map/project/common/__snapshots__/ProjectHeader.test.tsx.snap
  source/frontend/src/features/properties/map/project/detail/ProjectSummaryView.tsx
  source/frontend/src/features/properties/map/project/detail/__snapshots__/ProjectSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/project/hooks/useAddProjectFormManagement.tsx
  source/frontend/src/features/properties/map/project/models.ts
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.tsx
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainerView.test.tsx
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainerView.tsx
  source/frontend/src/features/properties/map/project/update/__snapshots__/UpdateProjectContainerView.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiProjects.ts
  source/frontend/src/hooks/providers/useProjectProvider.ts
  source/frontend/src/mocks/mockLookups.ts
  source/frontend/src/mocks/mockProjects.ts
Labels: enhancement

#2816 Bug fixes: PSP-5354, PSP-5370
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Repositories/Interfaces/IProjectRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeResults/FinancialCodeResults.tsx
Labels: bug

#2812 psp-5478 prod appsettings corrections - for next release.
  source/backend/api/Startup.cs
  source/backend/api/appsettings.json
Labels: bug

#2819 psp-5487 correct lease expiry behaviour on list view, detail view.
  source/backend/api/Areas/Leases/Mapping/Search/LeaseMap.cs
  source/backend/dal/Helpers/Extensions/LeaseExtensions.cs
  source/backend/tests/unit/dal/Core/Extensions/LeaseExtensionsTest.cs
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsForm.tsx
Labels: bug

#2820 psp-5482 address field character limit corrections.
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/validation.ts
Labels: bug

#2821 psp-5485 correct empty primary contact being sent as ''
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/leaseUtils.ts
Labels: bug

#2826 psp-5460 correct document pagination.
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/utils/utils.ts
Labels: bug

#2823 psp-5371 ensure that changing file id reloads file data.
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/properties/map/research/ResearchContainer.tsx
Labels: bug

#2829 PSP-5049 Research file - add/update/view project details
  source/backend/api/Areas/Research/Controllers/ResearchFileController.cs
  source/backend/api/Models/Concepts/ResearchFile/ResearchFileMap.cs
  source/backend/api/Models/Concepts/ResearchFile/ResearchFileModel.cs
  source/backend/api/Models/Concepts/ResearchFile/ResearchFileProjectMap.cs
  source/backend/api/Models/Concepts/ResearchFile/ResearchFileProjectModel.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Repositories/ResearchFileRepository.cs
  source/backend/entities/Partials/ResearchFileProject.cs
  source/backend/tests/unit/api/Controllers/Research/ResearchControllerTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/ResearchRepositoryTest.cs
  source/frontend/src/components/common/form/ProjectSelector/ProjectSelector.test.tsx
  source/frontend/src/components/common/form/ProjectSelector/ProjectSelector.tsx
  source/frontend/src/components/common/form/ProjectSelector/__snapshots__/ProjectSelector.test.tsx.snap
  source/frontend/src/components/common/form/index.ts
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/AddResearchForm.tsx
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/models.ts
  source/frontend/src/features/properties/map/research/common/models.ts
  source/frontend/src/features/properties/map/research/common/updateProjects/UpdateProjectsSubForm.test.tsx
  source/frontend/src/features/properties/map/research/common/updateProjects/UpdateProjectsSubForm.tsx
  source/frontend/src/features/properties/map/research/common/updateProjects/__snapshots__/UpdateProjectsSubForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/detail/ResearchSummaryView.test.tsx
  source/frontend/src/features/properties/map/research/detail/ResearchSummaryView.tsx
  source/frontend/src/features/properties/map/research/detail/__snapshots__/ResearchSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.test.tsx
  source/frontend/src/features/properties/map/research/update/summary/UpdateSummaryForm.tsx
  source/frontend/src/features/properties/map/research/update/summary/__snapshots__/UpdateSummaryForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/update/summary/models.ts
  source/frontend/src/hooks/useProjectTypeahead.ts
  source/frontend/src/mocks/mockResearchFile.ts
  source/frontend/src/models/api/ResearchFile.ts
  source/frontend/src/utils/index.ts
  source/frontend/src/utils/projectUtils.ts
  source/frontend/src/utils/utils.ts
Labels: enhancement

#2822 psp-5462 Update acq header to use new acq project fk.
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/mocks/mockAcquisitionFiles.ts
Labels: bug

#2828 Document generation backend | psp-5249
  source/backend/api/Areas/DocumentGeneration/DocumentGenerationController.cs
  source/backend/api/Areas/DocumentGeneration/DocumentGenerationRequest.cs
  source/backend/api/Areas/Documents/DocumentController.cs
  source/backend/api/Models/Cdogs/JwtResponse.cs
  source/backend/api/Models/Cdogs/RenderOptions.cs
  source/backend/api/Models/Cdogs/RenderRequest.cs
  source/backend/api/Models/Cdogs/RenderTemplate.cs
  source/backend/api/Models/Download/FileDownload.cs
  source/backend/api/Models/Mayan/Document/FileDownload.cs
  source/backend/api/Repositories/Cdogs/CdogsRepository.cs
  source/backend/api/Repositories/Cdogs/IDocumentGenerationRepository.cs
  source/backend/api/Repositories/Mayan/IEdmsDocumentRepository.cs
  source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  source/backend/api/Repositories/RestCommon/BaseRestRespository.cs
  source/backend/api/Services/DocumentGenerationService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/Services/IDocumentGenerationService.cs
  source/backend/api/Services/IDocumentService.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  source/frontend/src/constants/documentType.ts
  source/frontend/src/features/admin/document-template/DocumentTemplateManagementView.tsx
  source/frontend/src/features/documents/ComposedDocument.ts
  source/frontend/src/features/documents/DownloadDocumentButton.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailHeader.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
  source/frontend/src/features/documents/hooks/useDocumentProvider.ts
  source/frontend/src/hooks/pims-api/useApiDocuments.ts
  source/frontend/src/models/api/DocumentStorage.ts
  tools/mayan-edms/docker-compose.yml
Labels: enhancement

#2847 PSP-5210: Update acquisition list view to use new project data model FK
  source/backend/dal/Helpers/Extensions/AcquisitionExtensions.cs
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/models.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#2848 Test console output
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/common/form/Input.test.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.test.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.test.tsx
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayersControl/LayersControl.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.test.tsx
  source/frontend/src/features/contacts/contact/create/CreateContactContainer.test.tsx
  source/frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.test.tsx
  source/frontend/src/features/contacts/contact/create/Person/CreatePersonForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/UpdateContactContainer.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/help/components/HelpSubmitBox.test.tsx
  source/frontend/src/features/help/components/__snapshots__/HelpSubmitBox.test.tsx.snap
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/payments/PaymentsForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  source/frontend/src/features/leases/list/LeaseListView.test.tsx
  source/frontend/src/features/mapSideBar/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx
  source/frontend/src/features/notes/add/AddNotesContainer.test.tsx
  source/frontend/src/features/notes/list/NoteListView.test.tsx
  source/frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  source/frontend/src/features/notes/update/UpdateNoteContainer.test.tsx
  source/frontend/src/features/notes/update/UpdateNoteFormModal.test.tsx
  source/frontend/src/features/projects/list/ProjectListView.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.test.tsx
  source/frontend/src/features/properties/map/activity/list/ActivityListView.test.tsx
  source/frontend/src/features/properties/map/project/ProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/properties/map/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/research/list/ResearchListView.test.tsx
  source/frontend/src/hooks/useProperties.test.tsx
Labels: unit-tests

#2814 psp-5457 psp-5388 fix edit action on documents. Update interfaces to …
  source/frontend/src/features/documents/ComposedDocument.ts
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/documents/list/DocumentResults/DocumentResults.test.tsx
  source/frontend/src/features/documents/list/DocumentResults/DocumentResults.tsx
  source/frontend/src/features/documents/list/DocumentResults/DocumentResultsColumns.tsx
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/mocks/mockDocuments.ts
  source/frontend/src/models/api/Document.ts
Labels: bug

#2858 PSP-5370 ignore cannot determine region
  source/backend/api/Services/ProjectService.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
Labels: bug

#2855 psp-5249 document generation POC frontend.
  source/frontend/src/constants/documentType.ts
  source/frontend/src/features/documents/DownloadDocumentButton.tsx
  source/frontend/src/features/documents/hooks/useDocumentGenerationRepository.ts
  source/frontend/src/features/mapSideBar/tabs/FileTabs.tsx
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionFileTabs.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/shared/detail/AgreementForm.tsx
  source/frontend/src/features/properties/map/shared/detail/AgreementFormContainer.tsx
  source/frontend/src/features/properties/map/shared/detail/models.ts
  source/frontend/src/hooks/pims-api/useApiDocumentGeneration.ts
  source/frontend/src/models/api/DocumentGenerationRequest.ts
Labels: enhancement

#2809 Psp 5054 - historical file number to acq files.
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/dal/Helpers/Extensions/AcquisitionExtensions.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionRepositoryTest.cs
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.tsx
  source/frontend/src/features/acquisition/list/AcquisitionFilter/__snapshots__/AcquisitionFilter.test.tsx.snap
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.test.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/__snapshots__/AcquisitionSearchResults.test.tsx.snap
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/models.ts
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/models.ts
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/models.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#2875 PSP-4049: Create research file - style fixes
  source/frontend/src/features/properties/map/research/add/AddResearchForm.tsx
  source/frontend/src/features/properties/map/research/add/ResearchProperties.tsx
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/properties/map/research/add/__snapshots__/ResearchProperties.test.tsx.snap
Labels: enhancement

#2878 Backmerge master to test
  etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION/PAIMS_ACQUISITION_TO_PIMS_DATASET.dtsx
  etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION.dtproj
Labels: devops

#2854 PSP-3858 : Acquisition - property owners - create and view
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileOwnerMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileOwnerModel.cs
  source/backend/api/Models/Concepts/Address/AddressMap.cs
  source/backend/api/Models/Concepts/Address/AddressModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/IAcquisitionFileService.cs
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFilePropertyRepository.cs
  source/backend/entities/Partials/AcquisitionFileOwner.cs
  source/backend/entities/ef/PimsAcquisitionOwner.cs
  source/backend/tests/unit/api/Controllers/Projects/ProjectControllerTest.cs
  source/frontend/src/components/common/buttons/RemoveButton.tsx
  source/frontend/src/features/properties/map/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/__snapshots__/AcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionFileYupSchema.ts
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/add/models.ts
  source/frontend/src/features/properties/map/acquisition/common/models.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquistionOwners/UpdateAcquisitionOwnersSubForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquistionOwners/UpdateAcquisitionOwnersSubForm.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquistionOwners/UpdateAcquisitionOwnersYupSchema.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquistionOwners/__snapshots__/UpdateAcquisitionOwnersSubForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionOwnersSummaryContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionOwnersSummaryContainer.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionOwnersSummaryView.test.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/models.ts
  source/frontend/src/features/properties/map/acquisition/hooks/useAcquisitionProvider.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
  source/frontend/src/models/api/AcquisitionFile.ts
  source/frontend/src/models/api/Address.ts
Labels: enhancement

#2889 Bump DEV version - IS48
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#2851 mock bc assessment with msw instead of an inline response.
  .github/.trufflehog3.yml
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/public/mockServiceWorker.js
  source/frontend/src/hooks/useBcAssessmentLayer.ts
  source/frontend/src/index.tsx
  source/frontend/src/mocks/bcAssessmentMock.ts
  source/frontend/src/mocks/msw.ts
Labels: enhancement

#2887 PSP-4629 : Acquisition - property owners - update
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileOwnerMap.cs
  source/backend/api/Models/Concepts/Address/AddressModel.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/frontend/src/features/contacts/contact/create/components/address/Address.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionFileYupSchema.ts
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/common/models.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.tsx
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersYupSchema.ts
  source/frontend/src/features/properties/map/acquisition/common/update/acquisitionOwners/__snapshots__/UpdateAcquisitionOwnersSubForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/detail/AcquisitionOwnersSummaryContainer.tsx
  source/frontend/src/features/properties/map/acquisition/detail/models.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionForm.tsx
  source/frontend/src/features/properties/map/acquisition/update/summary/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/properties/map/acquisition/update/summary/models.ts
  source/frontend/src/mocks/mockAcquisitionFiles.ts
Labels: enhancement

#2888 Psp 5389 - duplicate products
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Repositories/Interfaces/IProductRepository.cs
  source/backend/dal/Repositories/ProductRepository.cs
  source/backend/tests/unit/api/Controllers/Projects/ProjectControllerTest.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.tsx
Labels: enhancement

#2897 PSP-5500 Limit project regions to those the user has access to
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectContainer.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/properties/map/project/add/AddProjectForm.tsx
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/properties/map/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.test.tsx
  source/frontend/src/features/properties/map/project/update/UpdateProjectContainer.tsx
  source/frontend/src/mocks/mockLookups.ts
  source/frontend/src/mocks/userMock.ts
  source/frontend/src/models/api/RegionUser.ts
  source/frontend/src/models/api/Role.ts
  source/frontend/src/models/api/User.ts
  source/frontend/src/models/api/UserRole.ts
Labels: enhancement

#2909 Document generation fix | psp-5575
  source/backend/api/Services/DocumentGenerationService.cs
  source/backend/dal/Repositories/DocumentRepository.cs
  source/backend/dal/Repositories/Interfaces/IDocumentRepository.cs
  source/frontend/src/hooks/pims-api/useApiDocumentGeneration.ts
Labels: bug

#2903 PSP-5504 : FT: Acquisition Files - Notes Tab: Changes on File status …
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/tests/core/Entities/AcquisitionFileHelper.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
Labels: bug

#2905 change the title when in edit mode psp-5203
  source/frontend/src/features/properties/map/lease/LeaseContainer.tsx
Labels: bug

#2908 psp-5508 do not allow cannot determine region for acquisition files.
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/tests/unit/api/Services/AcquisitionServiceTest.cs
  source/frontend/src/features/properties/map/acquisition/add/AcquisitionProperties.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionContainer.tsx
Labels: enhancement

#2896 Wava Scan Improvements | PSP-5118
  openshift/s2i/nginx-runtime/nginx.conf.template
  source/backend/api/Models/Configuration/ContentSecurityPolicyConfig.cs
  source/backend/api/Startup.cs
  source/backend/api/appsettings.json
  source/frontend/config-overrides.js
  source/frontend/public/index.html
  source/frontend/public/manifest.json
Labels: enhancement, tech-debt

#2901 TEST: Psp 5557 historical file number max char length
  source/frontend/src/features/properties/map/acquisition/add/AddAcquisitionFileYupSchema.ts
  source/frontend/src/features/properties/map/acquisition/update/summary/UpdateAcquisitionFileYupSchema.ts
Labels: bug

#2910 psp-5349 lease improvements text added for when there are no improvem…
  source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/ImprovementsContainer.test.tsx.snap
Labels: enhancement

#2898 TEST: psp-5563 correct document delete comparing relationship id to documen…
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/mocks/mockDocuments.ts
Labels: bug

#2902 Psp 5501 - always display the layer popup information on click even if there is no layer data at that location
  source/frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
  source/frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/__snapshots__/LayerPopupContainer.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupContent.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/__snapshots__/LayerPopupContent.test.tsx.snap
Labels: bug

#2904 Lease Notes | psp-4807
  source/backend/api/Areas/Notes/Controllers/NoteController.cs
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Constants/NoteType.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileNoteMap.cs
  source/backend/api/Models/Concepts/Note/ActivityNoteMap.cs
  source/backend/api/Models/Concepts/Note/EntityNoteModelMap.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/NoteService.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/IEntityNoteRepository.cs
  source/backend/entities/Partials/LeaseNote.cs
  source/backend/tests/unit/api/Controllers/Note/NoteControllerTest.cs
  source/backend/tests/unit/api/Controllers/Projects/ProjectControllerTest.cs
  source/backend/tests/unit/api/Routes/Notes/NoteControllerTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/dal/Repositories/LeaseRepositoryTest.cs
  source/frontend/src/constants/noteTypes.ts
  source/frontend/src/features/mapSideBar/tabs/LeaseFileTabs.tsx
  source/frontend/src/features/notes/NoteContainer.tsx
  source/frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  source/frontend/src/features/notes/hooks/useAddNotesFormManagement.ts
  source/frontend/src/features/notes/hooks/useUpdateNotesFormManagement.test.tsx
  source/frontend/src/features/notes/hooks/useUpdateNotesFormManagement.ts
  source/frontend/src/features/notes/list/NoteListView.test.tsx
  source/frontend/src/features/notes/update/UpdateNoteContainer.test.tsx
  source/frontend/src/features/properties/map/lease/detail/LeaseTabsContainer.tsx
  source/frontend/src/hooks/pims-api/useApiNotes.test.ts
  source/frontend/src/hooks/pims-api/useApiNotes.ts
  source/frontend/src/hooks/repositories/useNoteRepository.test.tsx
  source/frontend/src/hooks/repositories/useNoteRepository.ts
Labels: enhancement

#2927 Fixed csp for local dev
  source/frontend/config-overrides.js
Labels: tech-debt

#2938 PSP-5433 : Project: Notes
  source/backend/api/Constants/NoteType.cs
  source/backend/api/Models/Concepts/Note/EntityNoteModelMap.cs
  source/backend/api/Services/NoteService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/IEntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/IProjectRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/entities/Partials/ProjectNote.cs
  source/backend/tests/core/Entities/NoteHelper.cs
  source/backend/tests/core/Entities/ProjectHelper.cs
  source/backend/tests/unit/api/Services/NoteServiceTest.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/src/constants/noteTypes.ts
  source/frontend/src/features/properties/map/project/ProjectTabs.tsx
  source/frontend/src/features/properties/map/project/detail/ProjectTabsContainer.tsx
Labels: enhancement
