Repository bcgov/PSP, pull requests merged in 2023-09, with the labels that each got.

#3458 Bump DEV version - IS62
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops, release-management

#3460 Made types immutable | psp-6860
  source/frontend/src/components/common/mapFSM/models.ts
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
Labels: bug, release 4.0

#3462 PSP-6542
  source/frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx
Labels: bug, release 4.0

#3463 Fixed form8 navigation | psp-6866
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/update/UpdateForm8Container.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/update/UpdateForm8Container.tsx
Labels: bug, release 4.0

#3450 add gha to retag test to uat.
  .github/workflows/retag-test-to-uat.yml
Labels: devops

#3464 PSP-6732 Add tooltip for alternate project
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
Labels: enhancement

#3461 PIMS Automation - Acquisition File refactoring and Adding Checklists, Agreements and Stakeholders
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFilesDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
Labels: test-scripts

#3455 PSP-6517 Compensation Requisition Export
  source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
  source/backend/api/Areas/Reports/Controllers/AcquisitionController.cs
  source/backend/api/Areas/Reports/Models/Acquisition/AgreementReportModel.cs
  source/backend/api/Areas/Reports/Models/Acquisition/CompensationFinancialReportModel.cs
  source/backend/api/Areas/Reports/Models/Acquisition/CompensationFinancialReportTotalsModel.cs
  source/backend/api/Services/CompReqFinancialService.cs
  source/backend/api/Services/ICompReqFinancialService.cs
  source/backend/dal/Repositories/AgreementRepository.cs
  source/backend/dal/Repositories/CompReqFinancialRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompReqFinancialRepository.cs
  source/backend/tests/unit/api/Models/AgreementReportModelTest.cs
  source/backend/tests/unit/api/Models/CompensationFinancialReportModelTest.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/CompReqFinancialServiceTest.cs
  source/backend/tests/unit/dal/Repositories/CompReqFinancialRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/H120CategoryRepositoryTest.cs
  source/frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/surplus/Surplus.test.tsx
  source/frontend/src/features/projects/reports/ProjectExportContainer.test.tsx
  source/frontend/src/features/projects/reports/ProjectExportContainer.tsx
  source/frontend/src/features/projects/reports/ProjectExportForm.test.tsx
  source/frontend/src/features/projects/reports/ProjectExportForm.tsx
  source/frontend/src/features/projects/reports/models.ts
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/hooks/util/useApiRequestWrapper.ts
  source/frontend/src/models/api/ProjectFilter.ts
  source/frontend/src/utils/utils.ts
Labels: enhancement

#3441 PSP-6494 : Acquisition List View Export (Excel)
  source/backend/api/Areas/Contacts/Mapping/Contact/PersonMap.cs
  source/backend/api/Areas/Keycloak/Mapping/AccessRequest/AccessRequestUserMap.cs
  source/backend/api/Areas/Keycloak/Mapping/User/UserMap.cs
  source/backend/api/Areas/Reports/Controllers/AcquisitionController.cs
  source/backend/api/Areas/Reports/Mapping/User/UserMap.cs
  source/backend/api/Areas/Reports/Models/Acquisition/AgreementReportModel.cs
  source/backend/api/Mapping/User/UserMap.cs
  source/backend/api/Models/Concepts/Lease/LeasePaymentReportMap.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/IAcquisitionFileService.cs
  source/backend/dal/Helpers/Extensions/AcquisitionExtensions.cs
  source/backend/dal/Helpers/Extensions/AcquisitionOwnerExtensions.cs
  source/backend/dal/Helpers/Extensions/AddressExtensions.cs
  source/backend/dal/Helpers/Extensions/PersonExtensions.cs
  source/backend/dal/Models/AcquisitionFileExportModel.cs
  source/backend/dal/Pims.Dal.csproj
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileRepository.cs
  source/backend/tests/core/Entities/ContactHelper.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionRepositoryTest.cs
  source/frontend/src/features/acquisition/hooks/useAcquisitionFileExport.ts
  source/frontend/src/features/acquisition/list/AcquisitionListView.tsx
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
Labels: enhancement

#3439 psp-6610: add alternate project field for comp reqs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/models.ts
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/models/api/CompensationRequisition.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
Labels: enhancement, frontend

#3467 add support for '55' RC codes.
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtproj
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtsx
Labels: etl

#3478 Bump version to IS63
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops, release-management

#3473 psp-6844 agreement corrections.
  source/backend/api/Areas/Reports/Controllers/AcquisitionController.cs
  source/backend/dal/Repositories/AgreementRepository.cs
  source/backend/tests/unit/dal/Repositories/AgreementRepositoryTest.cs
  source/frontend/src/features/projects/reports/ProjectExportContainer.test.tsx
  source/frontend/src/features/projects/reports/ProjectExportContainer.tsx
Labels: bug

#3471 psp-6856 correct display of address country - other field.
  source/frontend/src/components/propertySelector/search/LayerFilter.test.tsx
  source/frontend/src/components/propertySelector/search/LayerFilter.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/models/DetailAcquisitionFileOwner.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/InterestHolderSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: bug

#3477 Automation FT Testing - Acquisition Files - Compensations, changes on Digital documents, contacts
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Classes/Contact.cs
  testing/PIMS.Tests.Automation/Data/ExcelDataContext.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFilesDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3476 PSP-6043 Fix frontend tests making web requests
  source/frontend/src/features/leases/add/AdministrationSubForm.test.tsx
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/documents/DocumentsPage.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/documents/__snapshots__/DocumentsPage.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  source/frontend/src/features/leases/list/LeaseFilter/LeaseFilter.test.tsx
  source/frontend/src/features/leases/list/LeaseListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/hooks/useAddAcquisitionFormManagement.test.tsx
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/update/UpdateProjectContainer.test.tsx
  source/frontend/src/features/notes/hooks/useAddNotesFormManagement.test.tsx
  source/frontend/src/features/notes/hooks/useUpdateNotesFormManagement.test.tsx
  source/frontend/src/features/projects/list/ProjectListView.test.tsx
  source/frontend/src/setupTests.ts
Labels: tech-debt

#3475 Psp 6898 correct document list view paging, use built in table paging.
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/documents/list/DocumentResults/DocumentResults.test.tsx
  source/frontend/src/features/documents/list/DocumentResults/DocumentResults.tsx
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
Labels: bug

#3480 FT Automation - Leases refactoring
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/AdminTools.feature
  testing/PIMS.Tests.Automation/Features/AdminTools.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFilesDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseSurplus.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3474 Added filter for team members and updated list view | psp-6151
  source/backend/api/Areas/Acquisition/Models/AcquisitionFilterModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Models/AcquisitionFilter.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.test.tsx
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.tsx
  source/frontend/src/features/acquisition/list/AcquisitionFilter/__snapshots__/AcquisitionFilter.test.tsx.snap
  source/frontend/src/features/acquisition/list/AcquisitionListView.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/__snapshots__/AcquisitionSearchResults.test.tsx.snap
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/models.ts
  source/frontend/src/features/acquisition/list/interfaces.ts
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
Labels: enhancement

#3479 PSP-6775 : Disallow Contractor to Remove Themself From File
  source/backend/api/Helpers/Extensions/AcquisitionFileExtensions.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Exceptions/OverrideExceptions.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx
  source/frontend/src/hooks/useApiUserOverride.ts
  source/frontend/src/models/api/UserOverrideCode.ts
Labels: enhancement

#3485 psp-6906 management claims
  source/backend/dal/Security/Permissions.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/77_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/78_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/075_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/76_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/77_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/051_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/074_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S63_00/Alter Down/76_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S63_00/Alter Down/77_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S63_00/Alter Down/78_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S63_00/Alter Up/075_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S63_00/Alter Up/76_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S63_00/Alter Up/77_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S63_00/Build/051_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S63_00/Build/074_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S63_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
Labels: enhancement

#3489 PSP-6905 Fix section headers
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
Labels: bug

#3486 PSP-6861 : Add "Advanced Payment Served Date"
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/models.ts
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/models/api/CompensationRequisition.ts
Labels: enhancement

#3488 PSP-6865 property management models
  source/backend/api/Areas/Property/Controllers/PropertyController.cs
  source/backend/api/Models/Concepts/Lease/PropertyLeaseMap.cs
  source/backend/api/Models/Concepts/Property/PropertyManagementPurposeMap.cs
  source/backend/api/Models/Concepts/Property/PropertyManagementPurposeModel.cs
  source/backend/api/Models/Concepts/Property/PropertyMap.cs
  source/backend/api/Models/Concepts/Property/PropertyModel.cs
  source/backend/dal/Repositories/PropertyLeaseRepository.cs
  source/backend/entities/Partials/PropPropPurpose.cs
  source/backend/entities/Partials/PropertyPurposeType.cs
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/ManagementSummaryContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/ManagementSummaryView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyManagementTabView.tsx
  source/frontend/src/hooks/pims-api/useApiProperties.ts
  source/frontend/src/hooks/repositories/usePimsPropertyRepository.ts
  source/frontend/src/models/api/Property.ts
Labels: enhancement

#3490 psp-6891 generate h1005a
  source/backend/api/Areas/DocumentGeneration/DocumentGenerationController.cs
  source/backend/api/Constants/FormDocumentType.cs
  source/frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/__snapshots__/TermsForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH1005a.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH1005a.ts
  source/frontend/src/features/mapSideBar/shared/content/models.ts
  source/frontend/src/models/generate/lease/GenerateLease.test.ts
  source/frontend/src/models/generate/lease/GenerateLease.ts
  source/frontend/src/models/generate/lease/GenerateLeaseProperty.ts
  source/frontend/src/models/generate/lease/GenerateSecurityDeposit.ts
  source/frontend/src/models/generate/lease/GenerateTenant.ts
Labels: enhancement

#3487 Property Contacts | psp-6825 & PSP-5745
  source/backend/api/Areas/Property/Controllers/PropertyContactController.cs
  source/backend/api/Models/Concepts/Property/PropertyContactMap.cs
  source/backend/api/Models/Concepts/Property/PropertyContactModel.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/AcquisitionFileFormRepository.cs
  source/backend/dal/Repositories/Interfaces/IPropertyContactRepository.cs
  source/backend/dal/Repositories/PropertyContactRepository.cs
  source/backend/entities/Partials/PropertyContact.cs
  source/frontend/src/components/common/SectionListHeader.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputContainer.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputView.tsx
  source/frontend/src/features/contacts/contactUtils.ts
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
  source/frontend/src/features/mapSideBar/property/PropertyViewSelector.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/ManagementSummaryContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/ManagementSummaryView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactList.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactListContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactListView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactListView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyManagementTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/__snapshots__/PropertyContactListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/PropertyContactEditContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/PropertyContactEditForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/PropertyContactEditForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/__snapshots__/PropertyContactEditForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/models.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/validation.ts
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/hooks/pims-api/useApiPropertyContacts.ts
  source/frontend/src/hooks/repositories/usePropertyContactRepository.ts
  source/frontend/src/models/api/Property.ts
Labels: enhancement

#3492 psp-6864 missing fields required message.
  .github/workflows/retag-test-to-uat.yml
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/UpdateForm8Form.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/project/ProjectContainer.tsx
  source/frontend/src/features/mapSideBar/project/ProjectContainerView.test.tsx
  source/frontend/src/features/mapSideBar/project/ProjectContainerView.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectForm.tsx
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/SidebarFooter.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
Labels: bug

#3496 Bump dev version - IS64
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops, release-management
