Repository bcgov/PSP, pull requests merged in 2023-08, with the labels that each got.

#3362 Added filter backend and frontend logic | psp-5048
  source/backend/api/Areas/Property/Controllers/SearchController.cs
  source/backend/dal/Models/PropertyFilterCriteria.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/package-lock.json
  source/frontend/src/components/common/Section/Section.tsx
  source/frontend/src/components/common/form/ProjectSelector/ProjectSelector.tsx
  source/frontend/src/components/common/form/ProjectSelector/__snapshots__/ProjectSelector.test.tsx.snap
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/MapSearch.tsx
  source/frontend/src/components/maps/MapView.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/AdvancedFilterButton.test.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/AdvancedFilterButton.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/__snapshots__/AdvancedFilterButton.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/models.ts
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersControl.test.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersControl.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/styles.ts
  source/frontend/src/features/advancedFilterBar/AdvancedFilterBar.test.tsx
  source/frontend/src/features/advancedFilterBar/AdvancedFilterBar.tsx
  source/frontend/src/features/advancedFilterBar/__snapshots__/AdvancedFilterBar.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/updateProjects/__snapshots__/UpdateProjectsSubForm.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/features/properties/map/MapContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiProperties.ts
  source/frontend/src/hooks/repositories/usePimsPropertyRepository.ts
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/api/ProjectFilterCriteria.ts
Labels: enhancement

#3376 Psp 6542 ensure lease payments/terms changes are synchronized with the ui.
  source/frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/hooks/useDeleteTermsPayments.tsx
Labels: bug

#3377 psp-6549 fix display of coordinates only property when null vs undefined.
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: bug

#3372 psp-6438-refix: add missing colors and new label
  source/frontend/src/components/maps/leaflet/Control/LayersControl/data.ts
Labels: bug, frontend

#3367 fix address search issue, when searching for lat/lng within bounds ne…
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
Labels: bug

#3381 PSP-6540 primary contacts for owner solicitor and interest holders
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm1.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.ts
  source/frontend/src/models/generate/acquisition/GenerateExpropriationFormBase.ts
  source/frontend/src/models/generate/acquisition/GenerateExpropriationInterestHolder.ts
  source/frontend/src/models/generate/acquisition/GenerateH120InterestHolder.ts
  source/frontend/src/models/generate/acquisition/GenerateH120Property.ts
  source/frontend/src/models/generate/acquisition/GenerateInterestHolder.ts
Labels: enhancement

#3364 psp-6616 correct grouping logic/display of interest holders.
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/PropertyInterestHoldersViewTable.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/models.test.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/models.ts
Labels: bug

#3375 remove redundant tag step, ensure that tag targets correct source tag.
  .github/workflows/retag-dev-to-test.yml
Labels: devops

#3374 create github action to run integration tests (currently manually).
  .github/workflows/integration-test.yml
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
Labels: test-scripts

#3344 psp-3242: add plan number search for map and list views
  source/backend/api/Areas/Property/Models/Search/PropertyFilterModel.cs
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/dal/Models/PropertyFilter.cs
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/constants/API.ts
  source/frontend/src/features/properties/filter/IPropertyFilter.ts
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  source/frontend/src/hooks/repositories/mapLayer/useFullyAttributedParcelMapLayer.ts
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/hooks/useRouterFilter.test.tsx
  source/frontend/src/models/layers/pimsPropertyLocationView.ts
Labels: enhancement, frontend

#3378 ensure contact address/email populated in tenant screen.
  source/backend/api/Areas/Contacts/Controllers/ContactController.cs
  source/backend/api/Areas/Contacts/Controllers/SearchController.cs
  source/backend/api/Startup.cs
  source/backend/dal/Repositories/LeaseTenantRepository.cs
  source/backend/tests/unit/api/Controllers/Contacts/SearchControllerTest.cs
Labels: bug

#3384 Fix dependency override for deprecated library
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: dependencies

#3386 Bump DEV version - IS60
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3391 PSP-6659 When creating a file or project after certain time, the created stamp date is a day after
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/__snapshots__/DepositsReceivedContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/__snapshots__/DepositsReturnedContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailTermInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailTerms.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/GenerateLetterRecipientsModal.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/__snapshots__/GenerateLetterRecipientsModal.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/common/__snapshots__/ProjectHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/__snapshots__/ProjectSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/bcAssessment/SalesTable.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/details/__snapshots__/ResearchSummaryView.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityForm.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityHeader.test.tsx.snap
  source/frontend/src/features/properties/map/activity/detail/__snapshots__/ActivityView.test.tsx.snap
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/setupTests.ts
  source/frontend/src/utils/dateUtils.test.ts
  source/frontend/src/utils/dateUtils.ts
  source/frontend/src/utils/index.ts
  source/frontend/src/utils/utils.test.ts
  source/frontend/src/utils/utils.ts
Labels: bug

#3394 PSP-6561 : Add "Final Date" to Compensation Requisition Input
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/models.ts
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/models/api/CompensationRequisition.ts
Labels: enhancement

#3396 Payee updates | psp-6686
  source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/api/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/CompensationRequisitionYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/models.ts
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/hooks/pims-api/useApiRequisitionCompensations.ts
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/mocks/mockAcquisitionPayee.mock.ts
  source/frontend/src/models/api/CompensationPayee.ts
  source/frontend/src/models/api/CompensationRequisition.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
Labels: enhancement, tech-debt

#3388 Automation branch
  testing/PIMS.Tests.Automation/Classes/Project.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/CDOGSTemplates.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/HelpDesk.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseSurplus.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/Login.cs
  testing/PIMS.Tests.Automation/PageObjects/ManageUsers.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProjects.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/PageObjects/Tenants.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LoginSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
  testing/PIMS.Tests.Automation/TestDocuments/High-def-image.jpg
  testing/PIMS.Tests.Automation/TestDocuments/PSP-4719 ETL Validation.xlsx
  testing/PIMS.Tests.Automation/TestDocuments/RemoteAccessUserGuide2022.pdf
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3380 psp-6577: remove second modal upon cancel changes for acquisition file
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
Labels: bug, frontend

#3400 psp-6685: fix default country selection logic
  source/frontend/src/features/mapSideBar/acquisition/common/models.ts
Labels: bug, frontend

#3401 More payee fixes | psp-6683
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
Labels: tech-debt

#3399 Regenerated scaffold s_60
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/TmpPimsPropPropAdjacentLandType.cs
Labels: db-scaffold

#3398 psp 6602: replace agreement date with final on comp req list view
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/columns.tsx
Labels: frontend

#3397 Added Lease filters and anomalies to advanced property | psp-4845 & psp-6230
  source/backend/dal/Models/PropertyFilterCriteria.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/models.ts
  source/frontend/src/models/api/ProjectFilterCriteria.ts
Labels: enhancement, release 4.0

#3409 PSP-6665 legacy payees
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/GenerateFormContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/models.ts
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
Labels: enhancement

#3407 PSP-6738 : Allow Contractor to Create Files
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Helpers/Extensions/AcquisitionFileExtensions.cs
  source/backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/core/Exceptions/ContractorNotInTeamException.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/hooks/useAddAcquisitionFormManagement.ts
Labels: release 4.0

#3379 psp-6233: enhance tenure status dropdowns
  source/frontend/src/constants/propertyTenureTypes.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
Labels: enhancement, frontend, release 4.0

#3405 psp-6664: remove primary contact column from non-interest payees view
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/PropertyInterestHoldersViewTable.tsx
Labels: bug, frontend, release 4.0

#3404 psp-6661: add primary contact for owner solictor on create acquisitio…
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
Labels: bug, frontend, release 4.0

#3392 psp-6543: add missing fields error for acquisition file screens
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/shared/SidebarFooter.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
Labels: enhancement, frontend, release 4.0

#3411 PSP-6742 : FT:Acquisition File: Compensation: User is not able to del…
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
Labels: bug, release 4.0

#3414 PSP-6741 FT:Acquisition File: Compensation: Wrong date is displayed for the Final date and Agreement Date if the status of the requisition is final
  source/frontend/src/features/documents/list/DocumentResults/DocumentResultsColumns.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/__snapshots__/DepositsReceivedContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/__snapshots__/DepositsReturnedContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/checklist/detail/AcquisitionChecklistView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/checklist/update/UpdateAcquisitionChecklistForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.test.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.test.tsx
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.tsx
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/__snapshots__/ProjectSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.test.tsx
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/research/tabs/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/details/__snapshots__/ResearchSummaryView.test.tsx.snap
  source/frontend/src/features/notes/detail/NoteDetailsFormModal.tsx
  source/frontend/src/features/notes/update/UpdateNoteFormModal.tsx
  source/frontend/src/features/projects/list/ProjectSearchResults/columns.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityHeader.test.tsx
  source/frontend/src/features/properties/map/activity/detail/ActivityHeader.tsx
  source/frontend/src/utils/dateUtils.test.ts
  source/frontend/src/utils/dateUtils.ts
Labels: bug, release 4.0

#3413 Fixed interest holder being updated on the front end | psp-6606
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/entities/Partials/InterestHolderPropertyInterestType.cs
Labels: bug

#3415 psp-6749: fix description display for form 8
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/models/Form8FormModel.ts
Labels: bug, frontend

#3417 Fixed null referencing on orgn & deposits
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/columns.tsx
Labels: bug

#3418 PSP-6762 : FT:Acquisition File: Compensation: In the Edit screen comp…
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
Labels: bug

#3416 psp-6746: force exact match for calls to BC assessment
  source/frontend/src/hooks/repositories/useBcAssessmentLayer.ts
Labels: bug

#3410 PSP-6475 : Generate Expropriation Form - Form 8
  source/backend/dal/Repositories/ExpropriationPaymentRepository.cs
  source/frontend/src/components/common/EditButton.tsx
  source/frontend/src/components/common/Section/SectionField.tsx
  source/frontend/src/components/common/form/ToggleSaveInput/__snapshots__/ToggleSaveInputView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm8.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm8.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainerView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/UpdateForm8Form.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/add/AddForm8Container.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/ExpropriationForm8Details.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/ExpropriationForm8Details.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/__snapshots__/ExpropriationForm8Details.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/update/UpdateForm8Container.test.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchMenu.test.tsx.snap
  source/frontend/src/mocks/ExpropriationPayment.mock.ts
  source/frontend/src/mocks/form8.mock.ts
  source/frontend/src/models/generate/GenerateAddress.ts
  source/frontend/src/models/generate/GenerateExpropriationPaymentItem.ts
  source/frontend/src/models/generate/acquisition/GenerateExpropriationForm8.ts
Labels: enhancement

#3420 PSP-6630: ACQ files: Legacy Interest Holders section
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/dal/Helpers/Extensions/AcquisitionExtensions.cs
  source/backend/tests/unit/dal/Core/Extensions/AcquisitionFileExtensionsTests.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/InterestHolderSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/models/api/AcquisitionFile.ts
  source/frontend/src/models/generate/GenerateOwner.ts
Labels: enhancement

#3422 psp-6748: fix app error when deleting a term
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.tsx
Labels: bug

#3421 psp-6773: remove second confirmation modal for cancelling changes
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
Labels: bug

#3423 Fixed map interactions on edit property | psp-6760 & psp-6761
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/context/sidebarContext.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
Labels: bug

#3427 s60 Fix | Updated Seed Scripts
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_DML_Migrate_ADJACENT_LAND_Data_From_TMP.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_DML_XL8_TENURE_TYPE_Data.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/032_DML_PIMS_PROPERTY_TENURE_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Alter Down/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Alter Up/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Alter Up/999_DML_Migrate_ADJACENT_LAND_Data_From_TMP.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Alter Up/999_DML_XL8_TENURE_TYPE_Data.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Build/032_DML_PIMS_PROPERTY_TENURE_TYPE.sql
Labels: bug, db-migration

#3428 Test backmerge
  source/backend/api/Pims.Api.csproj
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_DML_Migrate_ADJACENT_LAND_Data_From_TMP.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_DML_XL8_TENURE_TYPE_Data.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/032_DML_PIMS_PROPERTY_TENURE_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Alter Down/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Alter Up/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Alter Up/999_DML_Migrate_ADJACENT_LAND_Data_From_TMP.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Alter Up/999_DML_XL8_TENURE_TYPE_Data.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Build/032_DML_PIMS_PROPERTY_TENURE_TYPE.sql
  source/frontend/package.json
Labels: alignment

#3431 Test alter down fix
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Alter Down/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Down.sql
Labels: bug, db-migration

#3419 Automation: Calibrating Implicit waits and adding explicit waits where necessary
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/ManageUsers.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProjects.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/NotesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3435 Backmerge test
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S60_00/Alter Down/032_DML_PIMS_PROPERTY_TENURE_TYPE_Alter_Down.sql
Labels: alignment

#3432 Psp 6580 initiate filter screen for project exports
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/IAcquisitionFileService.cs
  source/backend/api/Services/IProjectService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/core/Extensions/EnumerableExtensions.cs
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/src/components/common/form/Multiselect.tsx
  source/frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  source/frontend/src/components/layout/SideNavBar/ProjectTray.tsx
  source/frontend/src/components/layout/SideNavBar/styles.ts
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserForm.test.tsx.snap
  source/frontend/src/features/leases/reports/payments/ExportLeasePaymentsContainer.tsx
  source/frontend/src/features/leases/reports/payments/__snapshots__/ExportLeasePaymentsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/projects/reports/ProjectExportContainer.test.tsx
  source/frontend/src/features/projects/reports/ProjectExportContainer.tsx
  source/frontend/src/features/projects/reports/ProjectExportForm.test.tsx
  source/frontend/src/features/projects/reports/ProjectExportForm.tsx
  source/frontend/src/features/projects/reports/ProjectExportFormContent.tsx
  source/frontend/src/features/projects/reports/__snapshots__/ProjectExportForm.test.tsx.snap
  source/frontend/src/features/projects/reports/models.ts
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/pims-api/useApiProjects.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/hooks/repositories/useProjectProvider.ts
  source/frontend/src/models/api/ProjectFilter.ts
Labels: enhancement

#3437 PSP-6737 : FT-REG: Lease & Licenses - new date field looks misaligned…
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
Labels: bug, release 4.0

#3430 Added tenure filters | psp-4804
  source/backend/dal/Models/PropertyFilterCriteria.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH0443.ts
  source/frontend/src/models/api/ProjectFilterCriteria.ts
Labels: enhancement

#3440 Psp-6518 agreements export.
  source/backend/api/Areas/Reports/Controllers/AcquisitionController.cs
  source/backend/api/Areas/Reports/Models/Acquisition/AgreementReportModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/IAcquisitionFileService.cs
  source/backend/dal/Models/AcquisitionReportFilterModel.cs
  source/backend/dal/Repositories/AgreementRepository.cs
  source/backend/dal/Repositories/Interfaces/IAgreementRepository.cs
  source/backend/tests/unit/api/Models/AgreementReportModelTest.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/AgreementRepositoryTest.cs
  source/frontend/src/features/projects/reports/ProjectExportContainer.test.tsx
  source/frontend/src/features/projects/reports/ProjectExportContainer.tsx
  source/frontend/src/features/projects/reports/ProjectExportFormContent.tsx
  source/frontend/src/features/projects/reports/models.ts
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/models/api/ProjectFilter.ts
Labels: enhancement

#3444 psp-6820 make take area optional
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.ts
Labels: enhancement, release 4.0

#3446 restoring updated version of PIMS_USER seed script, overriden in IS60.
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Test Data/038_PIMS_USER.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S61_00/Test Data/038_PIMS_USER.sql
Labels: test-data

#3445 psp-6803 ensure that nip/ip interests are separated correctly.
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/columns.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderContainer.tsx
Labels: bug, release 4.0

#3424 psp-6784: fix missing fields required message displays
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/SidebarFooter.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
Labels: bug, frontend, release 4.0

#3447 Fix agriculture flag not workling | psp-6759
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm8.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.test.tsx
  source/frontend/src/hooks/repositories/mapLayer/useLegalAdminBoundariesMapLayer.ts
  source/frontend/src/models/layers/alcAgriculturalReserve.ts
  source/frontend/src/models/layers/alcAgriculturalReserveLines.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: bug

#3452 Fixed property not displaying correctly on the map
  source/frontend/src/components/common/mapFSM/models.ts
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.test.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/layers/pimsPropertyLocationView.ts
Labels: bug
