Repository bcgov/PSP, pull requests merged in 2023-10, with the labels that each got.

#3500 Scaffold/s64
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsPropertyContact.cs
  source/backend/entities/ef/PimsPropertyContactHist.cs
Labels: db-scaffold

#3497 update list of bctfa pids.
  etl/PMBC_PIMS_BCTFA/BCTFA_QUERY.sql
  etl/PMBC_PIMS_BCTFA/PMBC_PIMS_BCTFA/PMBC_PIMS_BCTFA.dtproj
  etl/PMBC_PIMS_BCTFA/PMBC_PIMS_BCTFA/PMBC_PIMS_BCTFA.dtsx
Labels: etl

#3493 Psp 6649 alternate project on list view.
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionRepositoryTest.cs
  source/frontend/src/components/common/ExpandableTextList.tsx
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.tsx
  source/frontend/src/features/acquisition/list/AcquisitionFilter/__snapshots__/AcquisitionFilter.test.tsx.snap
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/AcquisitionSearchResults.test.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/__snapshots__/AcquisitionSearchResults.test.tsx.snap
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/models.ts
  source/frontend/src/models/api/AcquisitionFile.ts
Labels: enhancement

#3499 PSP-6865 Property Management summary
  source/backend/api/Areas/Property/Controllers/PropertyController.cs
  source/backend/api/Areas/Property/Controllers/PropertyManagementController.cs
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Models/Concepts/Property/PropertyManagementMap.cs
  source/backend/api/Models/Concepts/Property/PropertyManagementModel.cs
  source/backend/api/Models/Concepts/Property/PropertyManagementPurposeMap.cs
  source/backend/api/Models/Concepts/Property/PropertyManagementPurposeModel.cs
  source/backend/api/Models/Concepts/Property/PropertyMap.cs
  source/backend/api/Models/Concepts/Property/PropertyModel.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Services/PropertyServiceTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/constants/claims.ts
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestContainer.test.tsx.snap
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestForm.test.tsx.snap
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserContainer.test.tsx.snap
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserForm.test.tsx.snap
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/checklist/detail/__snapshots__/AcquisitionChecklistView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/checklist/update/__snapshots__/UpdateAcquisitionChecklistForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/PropertyViewSelector.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/ManagementSummaryContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyManagementTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/PropertyManagementUpdateContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/PropertyManagementUpdateContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/PropertyManagementUpdateForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/PropertyManagementUpdateForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/__snapshots__/PropertyManagementUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/models.test.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/models.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/validation.ts
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/properties/map/form/list/__snapshots__/FormListView.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiProperties.ts
  source/frontend/src/hooks/pims-api/useApiPropertyManagement.ts
  source/frontend/src/hooks/repositories/usePimsPropertyRepository.ts
  source/frontend/src/hooks/repositories/usePropertyManagementRepository.ts
  source/frontend/src/mocks/lookups.mock.ts
  source/frontend/src/mocks/propertyManagement.mock.ts
  source/frontend/src/models/api/Property.ts
  source/frontend/src/utils/test-utils.tsx
Labels: enhancement

#3502 psp-6021 add possession date to agreements form.
  source/backend/api/Models/Concepts/AcquisitionFile/AgreementMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AgreementModel.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/models.ts
  source/frontend/src/mocks/agreements.mock.ts
  source/frontend/src/models/api/Agreement.ts
Labels: enhancement

#3491 introduce keycloak to dev test ci/cd pipelines as the action appears …
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/integration-test.yml
  .github/workflows/keycloak-sync.yml
  .github/workflows/retag-dev-to-test.yml
  testing/PIMS.Tests.Automation/Data/ExcelDataContext.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
Labels: enhancement

#3503 Research header last-updated-by | PSP-6930
  source/backend/api/Areas/Research/Controllers/ResearchFileController.cs
  source/backend/api/Services/IResearchFileService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Models/LastUpdateBy.cs
  source/backend/dal/Repositories/Interfaces/IResearchFileRepository.cs
  source/backend/dal/Repositories/ResearchFileRepository.cs
  source/frontend/src/components/common/UserNameTooltip.tsx
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/mapSideBar/context/sidebarContext.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.test.tsx
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/research/tabs/ResearchTabsContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/tabs/ResearchTabsContainer.tsx
  source/frontend/src/features/mapSideBar/shared/tabs/DocumentsTab.tsx
  source/frontend/src/features/notes/list/NoteListView.tsx
  source/frontend/src/hooks/pims-api/useApiResearchFile.ts
  source/frontend/src/hooks/repositories/useResearchRepository.ts
  source/frontend/src/models/api/File.ts
Labels: enhancement

#3501 PSP-6945 : Access to PIMS Overview (Help File) - Header
  source/frontend/src/components/common/VerticalBar.tsx
  source/frontend/src/components/layout/Header/Header.tsx
  source/frontend/src/components/layout/Header/UserProfile.tsx
  source/frontend/src/components/layout/Header/__snapshots__/EmptyHeader.test.tsx.snap
  source/frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
  source/frontend/src/features/help/components/HelpBox.scss
  source/frontend/src/features/help/components/HelpBox.test.tsx
  source/frontend/src/features/help/components/HelpBox.tsx
  source/frontend/src/features/help/components/HelpModal.tsx
  source/frontend/src/features/help/components/HelpSubmitBox.test.tsx
  source/frontend/src/features/help/components/HelpSubmitBox.tsx
  source/frontend/src/features/help/components/__snapshots__/HelpBox.test.tsx.snap
  source/frontend/src/features/help/components/text/DetailNavigationHelpText.tsx
  source/frontend/src/features/help/components/text/DetailViewHelpText.tsx
  source/frontend/src/features/help/components/text/InventoryFilterHelpText.tsx
  source/frontend/src/features/help/components/text/InventoryListHelpText.tsx
  source/frontend/src/features/help/components/text/InventoryNavigationHelpText.tsx
  source/frontend/src/features/help/components/text/LandingFilterHelpText.tsx
  source/frontend/src/features/help/components/text/LandingMapHelpText.tsx
  source/frontend/src/features/help/components/text/LandingNavigationHelpText.tsx
  source/frontend/src/features/help/constants/HelpText.tsx
  source/frontend/src/features/help/containers/HelpContainer.tsx
  source/frontend/src/features/help/containers/HelpModalContentContainer.tsx
  source/frontend/src/features/help/containers/__snapshots__/HelpContainer.test.tsx.snap
  source/frontend/src/features/help/containers/__snapshots__/HelpModalContentContainer.test.tsx.snap
  source/frontend/src/features/help/forms/BugForm.tsx
  source/frontend/src/features/help/forms/FeatureRequestForm.tsx
  source/frontend/src/features/help/forms/HelpRequestForm.tsx
  source/frontend/src/features/help/forms/QuestionForm.tsx
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: enhancement

#3505 add missing db-deploy yaml file.
  openshift/4.0/templates/jobs/db-deploy.yaml
Labels: bug, db-migration

#3504 PSP-6824 Property management view
  source/frontend/src/components/common/MultiselectTextList.test.tsx
  source/frontend/src/components/common/MultiselectTextList.tsx
  source/frontend/src/components/common/TabView.tsx
  source/frontend/src/components/common/__snapshots__/MultiselectTextList.test.tsx.snap
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/tabs/__snapshots__/ProjectTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyManagementTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/__snapshots__/PropertyManagementDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/utils/formUtils.ts
  source/frontend/src/utils/propertyUtils.ts
  source/frontend/src/utils/test-utils.tsx
Labels: enhancement

#3507 Acquisition File Header | psp-6936
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/IAcquisitionFileService.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileRepository.cs
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/acquisition/router/AcquisitionRouter.tsx
  source/frontend/src/features/mapSideBar/acquisition/router/FilePropertyRouter.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/CompensationRequisitionTrayContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/add/AddForm8Container.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/add/AddForm8Container.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/update/UpdateForm8Container.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/update/UpdateForm8Container.tsx
  source/frontend/src/features/mapSideBar/context/sidebarContext.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.ts
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/mocks/lastUpdatedBy.mock.ts
Labels: enhancement

#3508 PSP-6895 Digital Documents - Default number of entries on the List View should be 10 instead of 1
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  source/frontend/src/features/documents/list/DocumentResults/DocumentResults.test.tsx
  source/frontend/src/features/documents/list/DocumentResults/DocumentResults.tsx
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  source/frontend/src/mocks/documents.mock.ts
Labels: bug

#3509 Automation Refactoring - Verify View Forms and Research Files
  testing/PIMS.Tests.Automation/Classes/ResearchFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFilesDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3510 Psp-6836 ensure address search matches properties consistently
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/constants/API.ts
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/list/PropertyListView.test.tsx
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
Labels: bug

#3514 Fix keycloak sync in github actions
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/retag-dev-to-test.yml
Labels: devops

#3526 PSP-6829 : Management activity - list view
  source/backend/api/Areas/Property/Controllers/PropertyManagementController.cs
  source/backend/api/Constants/PropertyActivityStatusTypeCodeEnum.cs
  source/backend/api/Models/Concepts/Property/PropertyActivityMap.cs
  source/backend/api/Models/Concepts/Property/PropertyActivityModel.cs
  source/backend/api/Models/Concepts/Property/PropertyManagementActivityMap.cs
  source/backend/api/Models/Concepts/Property/PropertyManagementActivityModel.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/entities/Partials/PropPropActivity.cs
  source/backend/entities/Partials/PropertyActivity.cs
  source/backend/entities/Partials/PropertyMgmtActivityStatusType.cs
  source/backend/entities/Partials/PropertyMgmtActivitySubType.cs
  source/backend/entities/Partials/PropertyMgmtActivityType.cs
  source/backend/tests/core/Entities/PropertyManagementActivityHelper.cs
  source/backend/tests/unit/api/Services/PropertyServiceTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/constants/propertyMgmtActivityStatusTypes.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyManagementTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/activitiesList/ManagementActivitiesList.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/activitiesList/ManagementActivitiesListContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/activitiesList/ManagementActivitiesListContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/activitiesList/ManagementActivitiesListView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/activitiesList/ManagementActivitiesListView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/activitiesList/__snapshots__/ManagementActivitiesListContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/activitiesList/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/activitiesList/models/PropertyActivityRow.ts
  source/frontend/src/hooks/pims-api/useApiPropertyManagement.ts
  source/frontend/src/hooks/repositories/usePropertyManagementRepository.ts
  source/frontend/src/mocks/PropertyManagementActivity.mock.ts
  source/frontend/src/models/api/Property.ts
Labels: enhancement

#3523 psp-6982 correct issue with lease object not containing some sub-enti…
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH1005a.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH1005a.ts
  source/frontend/src/models/generate/lease/GenerateLease.test.ts
  source/frontend/src/models/generate/lease/GenerateLease.ts
Labels: bug

#3521 make display of generation button conditional on type of lease.
  source/frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/__snapshots__/TermsForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/columns.tsx
Labels: bug

#3531 PSP-6960 Acquisition Team Organizations
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileTeamMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileTeamModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/frontend/src/components/common/form/ContactInput/ContactInputContainer.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputView.tsx
  source/frontend/src/components/common/form/ContactInput/__snapshots__/ContactInputView.test.tsx.snap
  source/frontend/src/components/common/form/PrimaryContactSelector/PrimaryContactSelector.test.tsx
  source/frontend/src/components/common/form/PrimaryContactSelector/PrimaryContactSelector.tsx
  source/frontend/src/components/common/form/PrimaryContactSelector/__snapshots__/PrimaryContactSelector.test.tsx.snap
  source/frontend/src/constants/API.ts
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/update/acquisitionTeam/UpdateAcquisitionTeamSubForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/update/acquisitionTeam/UpdateAcquisitionTeamSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/update/acquisitionTeam/UpdateAcquisitionTeamYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/common/update/acquisitionTeam/__snapshots__/UpdateAcquisitionTeamSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/__snapshots__/ExpropriationForm1.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/__snapshots__/ExpropriationForm5.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/__snapshots__/ExpropriationForm9.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/mocks/lookups.mock.ts
  source/frontend/src/models/api/AcquisitionFile.ts
  source/frontend/src/setupTests.ts
  source/frontend/src/utils/test-utils.tsx
Labels: enhancement

#3534 PSP-6989 H120: Show MoTI solicitor organization as a payee
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
Labels: enhancement

#3528 Provide Missing Seed Scripts for Alter Up in IS-65.00
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/134_DML_PIMS_PROP_MGMT_ACTIVITY_STATUS_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/135_DML_PIMS_PROP_MGMT_ACTIVITY_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/136_DML_PIMS_PROP_MGMT_ACTIVITY_SUBTYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S65_00/Alter Up/134_DML_PIMS_PROP_MGMT_ACTIVITY_STATUS_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S65_00/Alter Up/135_DML_PIMS_PROP_MGMT_ACTIVITY_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S65_00/Alter Up/136_DML_PIMS_PROP_MGMT_ACTIVITY_SUBTYPE.sql
Labels: db-migration

#3524 Db upgrade correction
  openshift/4.0/templates/jobs/db-deploy.yaml
  openshift/4.0/templates/jobs/sqlcmd-mssql.yaml
Labels: bug

#3525 allow markers with no pids to be opened/viewed.
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/models/layers/pimsPropertyLocationView.ts
Labels: bug

#3536 FT-REG: Takes - Site contamination label should follow the sentence c…
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
Labels: bug

#3545 Bump DEV version IS65
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3547 Bump DEV version to IS66
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3541 psp-7014 create etl that centers marker based on pole of inaccessibil…
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION.sln
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION.dtproj
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION.dtproj.user
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/Package.dtsx
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/PriorityQueue.dll
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/Project.params
Labels: etl

#3546 psp-7097 restore claims, rolecontroller used by kc.
  source/backend/api/Areas/Admin/Controllers/ClaimController.cs
  source/backend/api/Areas/Admin/Controllers/RoleController.cs
Labels: bug

#3512 Lease Last Updated By | PSP-6933
  source/backend/api/Areas/Leases/Controllers/LeaseController.cs
  source/backend/api/Services/ILeaseService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/InsuranceContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/hooks/useDeleteTermsPayments.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantContainer.tsx
  source/frontend/src/features/leases/hooks/useLeaseDetail.ts
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/lease/ViewSelector.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.test.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/detail/LeaseTab.tsx
  source/frontend/src/features/mapSideBar/lease/detail/LeaseTabsContainer.tsx
  source/frontend/src/hooks/pims-api/useApiLeases.ts
  source/frontend/src/hooks/repositories/useLeaseRepository.ts
Labels: enhancement

#3530 psp-7063 lease property corrections, ensure view screen displays area unit and…
  source/frontend/src/features/leases/detail/LeasePages/details/PropertiesInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
Labels: bug

#3539 PSP-7032 : FT:HelpDesk:Header UI(Font and Icon size) is not displaying accurately for Help and User text
  source/frontend/src/components/layout/Header/Header.tsx
  source/frontend/src/components/layout/Header/HeaderStyled.tsx
  source/frontend/src/components/layout/Header/UserProfile.tsx
  source/frontend/src/components/layout/Header/__snapshots__/EmptyHeader.test.tsx.snap
  source/frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
  source/frontend/src/features/help/containers/HelpContainer.tsx
  source/frontend/src/features/help/containers/__snapshots__/HelpContainer.test.tsx.snap
Labels: bug

#3540 psp-7064 split up legal description and pid.
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
Labels: bug

#3533 PSP-7002 : H0443: Show Acq team (organization) on document
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH0443.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH0443.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
Labels: enhancement

#3544 PSP-3323 rewrite enzyme tests
  .github/workflows/app-react.yml
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/components/common/form/LimitedSelect.test.tsx
  source/frontend/src/components/common/form/PrimaryContactSelector/PrimaryContactSelector.tsx
  source/frontend/src/components/common/form/Select.test.tsx
  source/frontend/src/components/common/form/__snapshots__/Select.test.tsx.snap
  source/frontend/src/mocks/accessRequest.mock.ts
  source/frontend/src/mocks/user.mock.ts
  source/frontend/src/router.test.tsx
Labels: tech-debt

#3550 psp-7034 add warning when interest holders attached to acquisition pr…
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
Labels: bug

#3548 psp-7099 prevent infinite refresh loop of acq files when user is not …
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/utils/axiosUtils.ts
Labels: bug

#3549 Automation Test - Adding automation for Acquisition Expropriation Files and Property Takes
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionExpropriation.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFilesDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
Labels: test-scripts

#3555 PSP-6847 Name changes for Take Areas
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
Labels: enhancement

#3554 psp-6984 add support for activity documents
  source/backend/api/Areas/Admin/Controllers/RoleController.cs
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/DocumentRelationType.cs
  source/backend/api/Constants/FileType.cs
  source/backend/api/Models/Concepts/Document/DocumentRelationshipMap.cs
  source/backend/api/Services/DocumentFileService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/Services/IDocumentFileService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/DocumentRepository.cs
  source/backend/dal/Repositories/Interfaces/IPropertyActivityFileDocumentRepository.cs
  source/backend/dal/Repositories/PropertyActivityFileDocumentRepository.cs
  source/backend/entities/Partials/PropertyActivityDocument.cs
  source/backend/tests/unit/api/Controllers/Document/DocumentControllerTest.cs
  source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyActivityDocumentRepositoryTest.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/129_DML_PIMS_DOCUMENT_CATEGORY_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S66_00/Alter Down/129_DML_PIMS_DOCUMENT_CATEGORY_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S66_00/Alter Up/129_DML_PIMS_DOCUMENT_CATEGORY_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S66_00/Build/129_DML_PIMS_DOCUMENT_CATEGORY_TYPE.sql
  source/frontend/src/AppRouter.tsx
  source/frontend/src/constants/documentRelationshipType.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/PropertyActivityDetailView.tsx
  source/frontend/src/pages/TestFileManagement.tsx
Labels: enhancement

#3553 Psp 6991 - organization team support for h0074 and agreements
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateLetter.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateLetter.ts
  source/frontend/src/models/generate/GenerateLetter.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.test.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.ts
Labels: enhancement
