Repository bcgov/PSP, pull requests merged in 2023-07, with the labels that each got.

#3301 HOTFIX: psp-6499 ensure access request region is being populated when accepti…
  source/backend/dal.keycloak/PimsKeycloakService.cs
  source/backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
Labels: bug, release 4.0

#3306 HOTFIX: bump version number for 4.0
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
Labels: release 4.0

#3303 PSP-5716, PSP-5717, PSP-5719: Expropriation forms 1, 5 and 9
  source/frontend/src/components/common/form/ContactInput/ContactInputContainer.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputView.tsx
  source/frontend/src/components/common/form/ContactInput/__snapshots__/ContactInputView.test.tsx.snap
  source/frontend/src/components/common/form/FormItem.test.tsx
  source/frontend/src/components/common/form/FormItem.tsx
  source/frontend/src/components/common/form/index.ts
  source/frontend/src/components/filePropertiesTable/FilePropertiesTable.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainerView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainerView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1YupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/__snapshots__/ExpropriationForm1.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/ExpropriationForm5.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/ExpropriationForm5.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/ExpropriationForm5YupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/__snapshots__/ExpropriationForm5.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9YupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/__snapshots__/ExpropriationForm9.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/mocks/acquisitionFiles.mock.ts
Labels: enhancement

#3298 psp-5860 limit lease and license access by region.
  source/backend/api/Areas/Leases/Controllers/LeaseController.cs
  source/backend/api/Areas/Leases/Controllers/SearchController.cs
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Models/Concepts/Lease/PropertyLeaseMap.cs
  source/backend/api/Models/Concepts/Lease/PropertyLeaseModel.cs
  source/backend/api/Services/ILeaseService.cs
  source/backend/api/Services/LeaseReportsService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Helpers/Extensions/LeaseExtensions.cs
  source/backend/dal/Helpers/Extensions/UserExtensions.cs
  source/backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/UserRepository.cs
  source/backend/tests/core/Entities/UserHelper.cs
  source/backend/tests/unit/api/Controllers/Leases/SearchControllerTest.cs
  source/backend/tests/unit/api/Controllers/Reports/LeaseControllerTest.cs
  source/backend/tests/unit/api/Helpers/PrincipalExtensionsTest.cs
  source/backend/tests/unit/api/Services/LeaseReportsServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/dal/Repositories/LeaseRepositoryTest.cs
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AdministrationSubForm.test.tsx
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailConsultation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailTermInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/leases/hooks/useLeaseDetail.ts
  source/frontend/src/features/leases/list/LeaseFilter/LeaseFilter.test.tsx
  source/frontend/src/features/leases/list/LeaseFilter/LeaseFilter.tsx
  source/frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
Labels: enhancement

#3311 Backmerge test to dev
  etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION.sln
  etl/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION/PAIMS_PIMS_ACQUISITION.dtproj
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtproj
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtsx
  etl/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE/PAIMS_PIMS_LEASE.dtproj
  source/backend/api/Pims.Api.csproj
  source/backend/dal.keycloak/PimsKeycloakService.cs
  source/backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/003_DML_Drop_ACQPAY_COMP_REQ_PAYEE_TCC.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/003_DML_Migrate_Chq_Data_From_TMP.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/004_DML_Migrate_Chq_Data_From_TMP.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_DML_SET_ALL_USERS_TO_MINISTRY.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_DML_SET_LEASE_PAYMENT_STATUS_TYPE_CODE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/003_DML_Drop_ACQPAY_COMP_REQ_PAYEE_TCC.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Alter Up/003_DML_Drop_ACQPAY_COMP_REQ_PAYEE_TCC.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Alter Up/003_DML_Migrate_Chq_Data_From_TMP.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Alter Up/004_DML_Migrate_Chq_Data_From_TMP.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S56_00/Build/003_DML_Drop_ACQPAY_COMP_REQ_PAYEE_TCC.sql
  source/frontend/package.json
  source/frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/CompensationRequisitionTrayContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/CompensationRequisitionTrayView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/hooks/repositories/useMapProperties.tsx
  source/frontend/src/models/api/CompensationFinancial.ts
Labels: devops

#3309 HOTFIX: Fix issue where bad tenant data can cause an NPE.
  source/backend/api/Models/Concepts/Lease/LeasePaymentReportMap.cs
Labels: bug, release 4.0

#3310 HOTFIX: psp-6495 Correct issue with object matching not working as expected.
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.tsx
Labels: bug, release 4.0

#3313 Increment DEV version - IS58
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3315 HOTFIX: h0074 standardize agreement owner string other name.
  source/frontend/src/models/generate/GenerateOwner.test.ts
  source/frontend/src/models/generate/GenerateOwner.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.test.ts
Labels: bug, release 4.0

#3316 HOTFIX: use financial code instead of id in generated h120.
  source/frontend/src/models/generate/acquisition/GenerateCompensationFinancial.ts
Labels: bug, release 4.0

#3321 Increment hotfix version in UAT
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3323 PSP-6522 : Display user friendly error when compensation req does not…
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
Labels: bug

#3322 IS-58 Re-Add_Adjacent_Property
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/999_Restore_Metadata.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S58_00/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S58_00/Alter Down/999_Restore_Metadata.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S58_00/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S58_00/Build/002_PSP_PIMS_Build.sql
Labels: db-scaffold

#3335 fix trufflehog install from failing (#3333)
  .github/workflows/credentials-scan.yml
Labels: devops

#3332 Fix for takes not showing properly on the update screen | psp-6572
  source/frontend/src/features/mapSideBar/tabs/takes/update/TakesUpdateContainer.tsx
Labels: bug, release 4.0

#3325 PSP-6563 : HOTFIX: in trust is missing on H120
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
Labels: bug, release 4.0

#3326 PSP-6557 : HOTFIX - Missing values on Template H120
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/dal/Repositories/CompReqH120Repository.cs
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/mocks/mockCompReqH120s.mock.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationFinancialSummary.ts
  source/frontend/src/models/generate/compensation/GenerateCompensation.test.ts
Labels: bug, release 4.0

#3330 Fixed business function not being displayed | psp-6550
  source/frontend/src/features/properties/map/compensation/detail/CompensationRequisitionDetailView.tsx
Labels: bug, release 4.0

#3334 bump tough-cookie dep
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: dependencies

#3338 Psp 6566 map search corrections
  source/frontend/src/components/maps/hooks/useMapSearch.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
  source/frontend/src/components/maps/leaflet/mapUtils.tsx
  source/frontend/src/features/properties/map/hooks/useMapProperties.tsx
  source/frontend/src/hooks/pims-api/useFullyAttributedParcelMapLayer.ts
Labels: bug, hotfix, release 4.0

#3340 Psp 6585 - allow yearly financial code expiry date to be updated via etl
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtproj
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtsx
Labels: etl, release 4.0

#3341 bump release hotfix version.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
Labels: hotfix, release 4.0

#3336 PSP-6527 : FT-REG: Lease & License - When a new license is created, t…
  source/backend/api/Models/Concepts/Lease/LeaseModel.cs
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.test.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/mocks/lease.mock.ts
Labels: bug

#3343 Backmerge master to test
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtproj
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtsx
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Models/Concepts/Lease/LeasePaymentReportMap.cs
  source/backend/api/Pims.Api.csproj
  source/backend/dal/Repositories/CompReqH120Repository.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateContainer.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/hooks/layer-api/layerUtils.ts
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
  source/frontend/src/hooks/repositories/mapLayer/useFullyAttributedParcelMapLayer.ts
  source/frontend/src/hooks/repositories/useMapProperties.tsx
  source/frontend/src/mocks/mockCompReqH120s.mock.ts
  source/frontend/src/models/generate/GenerateOwner.test.ts
  source/frontend/src/models/generate/GenerateOwner.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationFinancial.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationFinancialSummary.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
  source/frontend/src/models/generate/compensation/GenerateCompensation.test.ts
Labels: release-management

#3342 remove trufflehog workaround - library maintainer incremented version as requested.
  .github/workflows/credentials-scan.yml
Labels: devops

#3337 Frontend alignment with interest holder updates
  source/backend/api/Models/Concepts/InterestHolder/InterestHolderPropertyMap.cs
  source/backend/dal/Repositories/AcquisitionPayeeRepository.cs
  source/backend/dal/Repositories/InterestHolderRepository.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/constants/interestHolderTypes.ts
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/PropertyInterestHoldersViewTable.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/models.test.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/models.ts
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/mocks/interestHolder.mock.ts
  source/frontend/src/mocks/interestHolders.mock.ts
  source/frontend/src/mocks/mockAcquisitionPayee.mock.ts
  source/frontend/src/models/api/AcquisitionFile.ts
  source/frontend/src/models/api/CompensationPayee.ts
  source/frontend/src/models/api/InterestHolder.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.test.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
  source/frontend/src/models/generate/acquisition/GenerateExpropriationForm1.ts
  source/frontend/src/models/generate/acquisition/GenerateInterestHolder.ts
Labels: tech-debt

#3347 Backmerge test to dev
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtproj
  etl/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES/PAIMS_PIMS_CODES.dtsx
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Models/Concepts/Lease/LeaseModel.cs
  source/backend/api/Models/Concepts/Lease/LeasePaymentReportMap.cs
  source/backend/api/Pims.Api.csproj
  source/backend/dal/Repositories/CompReqH120Repository.cs
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/TermsForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.test.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateContainer.tsx
  source/frontend/src/features/properties/map/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/hooks/layer-api/layerUtils.ts
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
  source/frontend/src/hooks/repositories/mapLayer/useFullyAttributedParcelMapLayer.ts
  source/frontend/src/hooks/repositories/useMapProperties.tsx
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/mocks/mockCompReqH120s.mock.ts
  source/frontend/src/models/generate/GenerateOwner.test.ts
  source/frontend/src/models/generate/GenerateOwner.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationFinancial.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationFinancialSummary.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
  source/frontend/src/models/generate/compensation/GenerateCompensation.test.ts
Labels: devops

#3353 Bump DEV version - IS59
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3354 Backmerge test to dev
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S58_00/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S58_00/Build/002_PSP_PIMS_Build.sql
Labels: alignment

#3273 psp-6222 make canada as default selection for address component
  source/frontend/src/features/mapSideBar/acquisition/common/models.ts
Labels: enhancement, frontend

#3351 Automation Testing - Update of automation based on UI changes
  testing/PIMS.Tests.Automation/Classes/Project.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3359 Fixed loading of properties. Added sidebar of properties info from fullscreen
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/hooks/useRouterFilter.ts
Labels: tech-debt

#3358 Psp 6539 - datepicker styling update
  source/backend/api/Models/Concepts/Lease/PropertyImprovementModel.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Repositories/LeaseTenantRepository.cs
  source/backend/dal/Repositories/UserRepository.cs
  source/backend/tests/unit/dal/Repositories/UserRepositoryTest.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/common/form/FastDatePicker.test.tsx
  source/frontend/src/components/common/form/FastDatePicker.tsx
  source/frontend/src/features/admin/financial-codes/add/AddFinancialCodeForm.tsx
  source/frontend/src/features/admin/financial-codes/add/__snapshots__/AddFinancialCodeForm.test.tsx.snap
  source/frontend/src/features/admin/financial-codes/update/UpdateFinancialCodeForm.tsx
  source/frontend/src/features/admin/financial-codes/update/__snapshots__/UpdateFinancialCodeForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/__snapshots__/ReceivedDepositForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/__snapshots__/EditInsuranceContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/hooks/useCalculateActualGst.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentFormContent.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentModal.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/__snapshots__/PaymentForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/__snapshots__/TermForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/styles.tsx
  source/frontend/src/features/leases/hooks/useLeaseDetail.ts
  source/frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/__snapshots__/UpdateSummaryForm.test.tsx.snap
  source/frontend/src/features/research/list/ResearchFilter/__snapshots__/ResearchFilter.test.tsx.snap
  source/frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  source/frontend/src/hooks/repositories/useLeaseTenantRepository.ts
Labels: enhancement

#3350 psp-6306: add primary contact selector for owner solicitor
  source/frontend/src/features/contacts/hooks/usePersonDetail.ts
  source/frontend/src/features/contacts/repositories/useOrganizationRepository.ts
  source/frontend/src/features/contacts/repositories/usePersonRepository.ts
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/models.test.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/models.ts
Labels: enhancement, frontend

#3355 psp-6470 - action to tag dev to test
  .github/workflows/retag-dev-to-test.yml
Labels: devops

#3361 PSP-6608 Advanced Filter Bar
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/MapView.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilterButton/AdvancedFilterButton.test.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilterButton/AdvancedFilterButton.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilterButton/__snapshots__/AdvancedFilterButton.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersControl.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersControl.test.tsx.snap
  source/frontend/src/features/advancedFilterBar/AdvancedFilterBar.test.tsx
  source/frontend/src/features/advancedFilterBar/AdvancedFilterBar.tsx
  source/frontend/src/features/advancedFilterBar/__snapshots__/AdvancedFilterBar.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/features/properties/map/MapContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/mocks/mapFSM.mock.ts
Labels: enhancement

#3366 PSP-6578 Fix section header text
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainerView.tsx
Labels: bug

#3365 GHA corrections.
  .github/workflows/retag-dev-to-test.yml
Labels: bug

#3363 psp-6651 ensure that searches for pids with leading 0s are supported.
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/dal/Repositories/PropertyRepository.cs
Labels: bug

#3369 Backmerge test to dev
  source/frontend/src/features/mapSideBar/acquisition/common/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainerView.tsx
Labels: alignment

#3357 psp-6384: primary contact selector for interest holders
  source/backend/api/Models/Concepts/InterestHolder/InterestHolderModel.cs
  source/backend/dal/Repositories/InterestHolderRepository.cs
  source/frontend/package-lock.json
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/PropertyInterestHoldersViewTable.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/__snapshots__/StakeHolderView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/InterestHolderSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/models.ts
Labels: enhancement, frontend

#3370 PSP-6635 Fix generate forms file format and name
  source/frontend/src/features/documents/DownloadDocumentButton.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm5.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm9.tsx
Labels: bug

#3368 psp-6652 pagination of list view correction.
  source/frontend/src/features/properties/list/PropertyListView.tsx
  source/frontend/src/utils/CommonFunctions.ts
Labels: bug

#3293 psp-5977: update layers json logic to allow overwriting
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.test.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersMenu.test.tsx.snap
Labels: tech-debt

#3360 Psp 6112 add/enforce total allowable compensation
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/api/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/frontend/src/components/common/Section/SectionField.tsx
  source/frontend/src/components/common/form/ToggleSaveInput/ToggleSaveInputContainer.test.tsx
  source/frontend/src/components/common/form/ToggleSaveInput/ToggleSaveInputContainer.tsx
  source/frontend/src/components/common/form/ToggleSaveInput/ToggleSaveInputView.test.tsx
  source/frontend/src/components/common/form/ToggleSaveInput/ToggleSaveInputView.tsx
  source/frontend/src/components/common/form/ToggleSaveInput/__snapshots__/ToggleSaveInputView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/columns.tsx
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/models/api/AcquisitionFile.ts
  source/frontend/src/utils/axiosUtils.ts
Labels: enhancement
