Repository bcgov/PSP, pull requests merged in 2024-11, with the labels that each got.

#4423 PSP-9341 : Sub-file interest type
  source/backend/api/Controllers/LookupController.cs
  source/backend/apimodels/CodeTypes/SubfileInterestTypes.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/entities/Partials/SubfileInterestType.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionFileYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionFileYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/mocks/lookups.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_SubfileInterestTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_AcquisitionFile.ts
  source/frontend/src/models/defaultInitializers.ts
Labels: enhancement

#4429 PSP-9331: UI UX Clean Up - Replace notes field
  source/frontend/src/components/common/form/NotesModal.test.tsx
  source/frontend/src/components/common/form/NotesModal.tsx
  source/frontend/src/components/common/form/__snapshots__/NotesModal.test.tsx.snap
  source/frontend/src/features/admin/access-request/AccessRequestForm.tsx
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestContainer.test.tsx.snap
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestForm.test.tsx.snap
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.test.tsx.snap
  source/frontend/src/features/admin/edit-user/EditUserForm.tsx
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserContainer.test.tsx.snap
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserForm.test.tsx.snap
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/FeeDeterminationSubForm.tsx
  source/frontend/src/features/leases/add/RenewalSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/FeeDeterminationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/__snapshots__/DepositNotes.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailFeeDetermination.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseRenewalsView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailFeeDetermination.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/payments/PaymentsView.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/payments/paymentsColumns.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/__snapshots__/DispositionOfferDetails.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/form/DispositionOfferForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/models/DispositionOfferFormYupSchema.ts
  source/frontend/src/features/mapSideBar/property/tabs/ltsa/LtsaTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/validation.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/detail/PropertyResearchTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/detail/__snapshots__/PropertyResearchTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyYupSchema.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/__snapshots__/UpdatePropertyForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/details/ResearchSummaryView.tsx
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/details/__snapshots__/ResearchSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/UpdateResearchFileYupSchema.ts
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/UpdateSummaryForm.tsx
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/__snapshots__/UpdateSummaryForm.test.tsx.snap
  tools/mayan_sync_helper/json_output/mayan_sync.json
Labels: enhancement, 5.6

#4426 PSP-9205 : UI UX Clean Up - tab menu - color replacement
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/components/common/TabView.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/__snapshots__/LeasePropertySelector.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/tabs/__snapshots__/ProjectTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: enhancement

#4431 PSP-9406: Clean Up - Map Icons color and interaction
  source/frontend/src/components/maps/leaflet/Control/Legend/LegendControl.tsx
  source/frontend/src/components/maps/leaflet/Control/ZoomOut/ZoomOutButton.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
Labels: bug, 5.6

#4435 PSP-9412: Lease/Licence - Add Approval/Consultation: Outcome field has incorrect default option
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/models.ts
Labels: bug, 5.6

#4438 PSP-9465 Sub interest section is missing on the view screen of Sub-interest file
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionOwnersSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
Labels: bug, 5.6

#4441 PSP-9205 : UI UX Clean Up - tab menu - color replacement
  source/frontend/src/components/common/TabView.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/__snapshots__/LeasePropertySelector.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/tabs/__snapshots__/ProjectTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: enhancement

#4445 psp-9466 ensure that the full pims location data is included in the m…
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
Labels: bug, 5.6

#4442 PSP-9474 : FT: Acquisition File: Sub-interest File: For Other file in…
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
Labels: bug, 5.6

#4447 Adding tooltip of Acquisition File Create form
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
Labels: bug, 5.6

#4444 PSP-9287 | Document Type updates
  tools/mayan_sync_helper/json_output/mayan_sync.json
  tools/mayan_sync_helper/mayan_sync_transformer.py
  tools/mayan_sync_helper/xml_definitions/doc_metadata.xlsx
  tools/mayan_sync_helper/xml_definitions/doctype_definitions.xlsx
  tools/mayan_sync_helper/xml_definitions/metadata_definitions.xlsx
Labels: enhancement

#4449 PSP-9302 Leases Compensation: 500 error should throw a friendlier message when a user attempts to delete a stakeholder that is associated to a compensation
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/PrimaryContactWarningModal.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderContainer.tsx
  source/frontend/src/hooks/pims-api/useApiLeaseStakeholders.ts
  source/frontend/src/hooks/repositories/useLeaseStakeholderRepository.ts
Labels: bug, 5.6

#4443 Psp 9318 - document queue base etl
  etl/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT/DOCUMENT_IMPORT.dtsx
  etl/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT.dtproj
  etl/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT.dtproj.user
  etl/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT.sln
  etl/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT/Project.params
Labels: etl

#4433 PSP-8759 : Creating and Editing Property Records – Property Address F…
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
Labels: enhancement

#4437 PSP-8569 : UI UX Clean Up - Properties Menu (Acquisition, Disposition…
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/components/common/buttons/EditPropertiesButton.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionMenu.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchMenu.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchMenu.test.tsx.snap
Labels: enhancement

#4452 psp-9446 allow leases with large numbers of historical file numbers t…
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberFieldView.tsx
Labels: bug, 5.7

#4439 Psp 9405 allow layers to be refreshed programatically.
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/maps/leaflet/Control/LayersControl/data.ts
  source/frontend/src/components/maps/leaflet/Layers/LeafletLayerListener.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
Labels: bug, 5.6

#4456 PSP-9488 Titles are missing on Properties links and File Summary
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionMenu.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/GenerateFormView.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchMenu.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchMenu.test.tsx.snap
Labels: bug, 5.6

#4454 PSP-9489 : FT: Property Details: The default option for the Province …
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
Labels: bug, 5.6

#4455 correct inconsistent reset of advanced filter.
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.test.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
Labels: bug, 5.6

#4457 PSP-9173 | Fix lease payment reports
  source/backend/dal/Repositories/LeasePaymentRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
Labels: bug

#4459 Bump dev version - Release 5.7
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4460 update 5.7 with latest dev
  source/backend/api/Pims.Api.csproj
  source/backend/dal/Repositories/LeasePaymentRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.test.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.test.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/data.ts
  source/frontend/src/components/maps/leaflet/Layers/LeafletLayerListener.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionMenu.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/GenerateFormView.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchMenu.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchMenu.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/features/properties/map/MapContainer.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
Labels: alignment

#4453 psp-9457 update layer popup flyout to display research/other files co…
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
Labels: bug, 5.7

#4463 test corrections.
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
Labels: bug

#4461 Merge 5.7 branch into dev
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberFieldView.tsx
Labels: devops, alignment

#4458 PSP-9493 | Added purpose on edit and view for document pages
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailForm.test.tsx.snap
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailView.test.tsx.snap
Labels: bug

#4466 Test backmerge
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailForm.test.tsx.snap
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailView.test.tsx.snap
Labels: alignment

#4465 PSP-9475 UI UX cleanup - sub-table expander arrow alignment
  source/frontend/src/components/Table/Table.scss
Labels: enhancement, ui/ux

#4476 HOTFIX: Psp 9649 ensure property marker pin displays after file add.
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/features/properties/map/MapContainer.tsx
Labels: bug, hotfix, 5.6

#4478 PSP-9476: UI UX Clean Up - Documents and Notes - Buttons - add "+"
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/notes/list/NoteListView.tsx
Labels: enhancement, 5.7

#4474 HOTFIX: psp-9436 - remove restriction on take date such that db layer logic c…
  source/backend/dal/Repositories/PropertyRepository.cs
Labels: bug, hotfix, 5.6

#4475 PSP-9450: UI UX Clean Up - Reduce space (top/bottom) on the Cancel/Save buttons area (Tracy)
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/common/__snapshots__/UpdateAcquisitionAgreementForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/__snapshots__/UpdateDispositionSaleView.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/__snapshots__/ConsultationEditForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/SidebarFooter.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: enhancement, 5.7

#4477 HOTFIX: Psp 9505 - ensure document metadata reset when document type changed.
  source/frontend/src/features/documents/ComposedDocument.ts
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.tsx
Labels: bug, hotfix, 5.6

#4471 IS 93.00 Database Schema
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/003_SET_HIST_CONCURRENCY_NOT_NULL.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/Schema Compare.zip
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/Schema Compare.zip
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Drop/01_PSP_PIMS_Drop.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/PIMS S93.00 Change Log.txt
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S93_00/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S93_00/Alter Down/003_SET_HIST_CONCURRENCY_NOT_NULL.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S93_00/Alter Down/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S93_00/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S93_00/Alter Up/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S93_00/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S93_00/Drop/01_PSP_PIMS_Drop.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S93_00/PIMS S93.00 Change Log.txt
Labels: db-migration

#4486 PSP-9503: Automation test set IS93 - Additional data changes
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
Labels: test-scripts

#4480 PSP-9452: Split map search for PID PIN
  Makefile
  source/backend/api/Areas/Property/Models/PropertyFilterModel.cs
  source/backend/dal/Helpers/Extensions/PropertyViewExtensions.cs
  source/backend/dal/Models/PropertyFilter.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/core/DatabaseHelper.cs
  source/backend/tests/core/Entities/PropertyHelper.cs
  source/backend/tests/core/PimsTestContext.cs
  source/backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
  source/backend/tests/unit/api/Controllers/Reports/PropertyControllerTest.cs
  source/backend/tests/unit/dal/Entities/PropertyFilterTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyActivityRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/components/common/List/SelectInput.test.tsx
  source/frontend/src/components/common/List/__snapshots__/SelectInput.test.tsx.snap
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/properties/filter/IPropertyFilter.ts
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/filter/PropertySearchToggle.tsx
  source/frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  source/frontend/src/features/properties/list/PropertyListView.test.tsx
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
Labels: enhancement

#4488 remove disabled OCR app.
  tools/mayan-edms/.mayan-env
Labels: bug

#4482 IS93 Scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcquisitionFileDocument.cs
  source/backend/entities/ef/PimsDispositionFileDocument.cs
  source/backend/entities/ef/PimsDocumentQueue.cs
  source/backend/entities/ef/PimsDocumentQueueHist.cs
  source/backend/entities/ef/PimsLeaseDocument.cs
  source/backend/entities/ef/PimsPropertyActivityDocument.cs
  source/backend/entities/ef/PimsResearchFileDocument.cs
Labels: db-scaffold

#4487 Update keycloak-js version to latest.
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/utils/TestCommonWrapper.tsx
  source/frontend/src/utils/getKeycloakEventHandler.test.ts
  source/frontend/tsconfig.json
Labels: dependencies

#4491 Retag proxy microservice when deploying to TEST
  .github/workflows/retag-dev-to-test.yml
Labels: devops, release-management

#4493 Fix TEST deployment.
  .github/workflows/retag-dev-to-test.yml
Labels: devops

#4495 Fix CICD failing due to proxy using a kubernetes deployment instead of a deployment-config
  .github/workflows/ci-cd-pims-dev.yml
Labels: devops

#4499 PSP-9354: UI UX Clean Up - Lease/Licence - Approvals/Consultation - all tabs closed
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/ConsultationListView.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/__snapshots__/ConsultationListView.test.tsx.snap
Labels: enhancement, 5.7

#4494 psp-9446 allow historical numbers to be collapsed in two dimensions.
  source/frontend/src/components/common/ExpandableTextList.tsx
  source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberContainer.test.tsx
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberFieldView.test.tsx
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberFieldView.tsx
Labels: bug, 5.7

#4497 PSP-9133 : Implement check/warning on frontend that backend and datab…
  source/backend/api/Controllers/HealthController.cs
  source/backend/api/Models/Health/EnvModel.cs
  source/backend/api/Services/EnvironmentService.cs
  source/backend/api/Services/IEnvironmentService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Repositories/Interfaces/ISystemConstantRepository.cs
  source/backend/dal/Repositories/SystemConstantRepository.cs
  source/frontend/src/components/common/ApiVersionInfo.test.tsx
  source/frontend/src/components/common/ApiVersionInfo.tsx
  source/frontend/src/components/common/__snapshots__/ApiVersionInfo.test.tsx.snap
  source/frontend/src/components/layout/Footer/Footer.test.tsx
  source/frontend/src/components/layout/Footer/__snapshots__/Footer.test.tsx.snap
  source/frontend/src/hooks/pims-api/interfaces/IApiVersion.ts
  source/frontend/tsconfig.json
  source/frontend/vite.config.ts
Labels: enhancement

#4492 PSP-9529: Fix faulty logic with retired property filter
  source/frontend/src/components/common/ApiVersionInfo.test.tsx
  source/frontend/src/components/layout/Footer/Footer.test.tsx
  source/frontend/src/components/layout/Footer/__snapshots__/Footer.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
Labels: bug

#4506 S94 Scaffold
  source/backend/api/Services/DocumentGenerationService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcquisitionFile.cs
  source/backend/entities/ef/PimsAcquisitionFileHist.cs
  source/backend/entities/ef/PimsDispositionFileDocument.cs
  source/backend/entities/ef/PimsDispositionFileDocumentHist.cs
  source/backend/entities/ef/PimsDocument.cs
  source/backend/entities/ef/PimsDocumentHist.cs
  source/backend/entities/ef/PimsDocumentQueue.cs
  source/backend/entities/ef/PimsDocumentQueueHist.cs
  source/backend/entities/ef/PimsProjectProduct.cs
  source/backend/entities/ef/PimsProjectProductHist.cs
  source/backend/entities/ef/PimsPropPropAnomalyType.cs
Labels: db-scaffold

#4502 psp-9485 zoom map to individual results, or zoom out to multiple.
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
Labels: enhancement

#4507 keycloak-sync dependency corrections.
  tools/keycloak/sync/Pims.Tools.Keycloak.Sync.csproj
  tools/keycloak/sync/Pims.Tools.Keycloak.Sync.sln
Labels: bug

#4500 PSP-9486 UI UX Property Information - moving PIN information to the left
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/property/__snapshots__/MotiInventoryHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.test.tsx
  source/frontend/src/mocks/data.mock.ts
Labels: enhancement, ui/ux

#4509 PSP-9565: Automation test set update IS94 and Changes on Github action
  .github/workflows/integration-test.yml
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionExpropriation.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionConsolidationProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts
