Repository bcgov/PSP, pull requests merged in 2024-04, with the labels that each got.

#3908 Psp 8156 ensure consolidation order is consistent with the map display
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationMarkerSynchronizer.tsx
Labels: bug, hotfix

#3911 PSP-8119 Hotfix: user is not able to add properties(green/blue/pink) pins from the map on the disposition file
  source/backend/dal/Repositories/DispositionFileRepository.cs
Labels: bug, hotfix

#3915 Backmerge test to dev
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Layers/InventoryLayer.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationMarkerSynchronizer.tsx
  source/frontend/src/features/properties/map/MapContainer.test.tsx
Labels: release-management

#3919 PIMS PROPERTY ETL Merge files commit
  etl/PIMS_PROPERTY_MERGE_UPD/PIMS_PROPERTY_MERGE.dtproj
  etl/PIMS_PROPERTY_MERGE_UPD/PIMS_PROPERTY_MERGE.dtproj.user
  etl/PIMS_PROPERTY_MERGE_UPD/PIMS_PROPERTY_MERGE.dtsx
  etl/PIMS_PROPERTY_MERGE_UPD/PIMS_PROPERTY_MERGE.sln
  etl/PIMS_PROPERTY_MERGE_UPD/PIMS_PROPERTY_MERGE_UPD.dtproj.user
  etl/PIMS_PROPERTY_MERGE_UPD/Project.params
Labels: etl

#3922 HOTFIX - correct multipolygon spatial correction logic.
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION.dtproj
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/SPATIAL_CORRECTION.dtsx
Labels: etl, hotfix, 5.1

#3925 Scaffold/s77
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyMap.cs
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsProperty.cs
  source/backend/entities/ef/PimsPropertyBoundaryVw.cs
  source/backend/entities/ef/PimsPropertyHist.cs
  source/backend/entities/ef/PimsPropertyLocationVw.cs
  source/backend/entities/ef/PimsTake.cs
  source/backend/entities/ef/PimsTakeHist.cs
  source/backend/tests/core/Entities/PropertyHelper.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
Labels: db-scaffold

#3912 PSP-8092 : Prevent completion of acquisition file that has no take
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
Labels: enhancement

#3926 Hotfix 5.1.2
  source/backend/api/Pims.Api.csproj
  source/backend/apimodels/Models/Concepts/Property/PolygonMap.cs
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/utils/mapPropertyUtils.ts
  source/frontend/src/utils/utils.ts
Labels: hotfix

#3928 psp-8116 Update frontend layer configuration.
  source/frontend/src/components/maps/leaflet/Layers/util.test.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.test.tsx
  source/frontend/src/mocks/data.mock.ts
  source/frontend/src/models/layers/pimsPropertyLocationView.ts
Labels: enhancement

#3930 Do not return non-polygon boundaries as the mapping is not idempotent.
  source/backend/apimodels/Models/Concepts/Property/PolygonMap.cs
Labels: bug, hotfix

#3932 Backmerge test into dev (and 5.2 version fix)
  source/backend/api/Pims.Api.csproj
  source/backend/apimodels/Models/Concepts/Property/PolygonMap.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/utils/mapPropertyUtils.ts
  source/frontend/src/utils/utils.ts
Labels: alignment

#3935 Update to IS-77.00 Database Schema
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/Schema Compare.zip
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/Schema Compare.zip
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Drop/01_PSP_PIMS_Drop.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S77_00/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S77_00/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S77_00/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S77_00/Drop/01_PSP_PIMS_Drop.sql
Labels: db-migration

#3939 allow codecov updates to fail.
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
Labels: devops

#3938 PSP-8198 tenant json loading bug
  source/frontend/.gitignore
  source/frontend/public/tenants/tenant.json
  source/frontend/src/serviceWorker.ignore.ts
  source/frontend/src/tenants/tenant.tsx
  source/frontend/vite.config.ts
Labels: bug

#3918 psp-8166 hide toolbar on associated property operations.
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationFileAssocationsContainer.tsx
Labels: bug

#3917 psp-8158 ensure that all subdivisions/consolidations only allow for owned sour…
  source/backend/api/Services/PropertyOperationService.cs
  source/backend/tests/core/Entities/PropertyOperationHelper.cs
  source/backend/tests/unit/api/Services/PropertyOperationServiceTest.cs
Labels: bug

#3940 IS-77.00 Updated Alters
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/128_DML_PIMS_LAND_ACT_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/128_DML_PIMS_LAND_ACT_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S77_00/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S77_00/Alter Down/128_DML_PIMS_LAND_ACT_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S77_00/Alter Up/128_DML_PIMS_LAND_ACT_TYPE_Alter_Up.sql
Labels: db-migration

#3942 codecov fix
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
Labels: devops

#3943 codecov attempted fix.
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
Labels: devops

#3927 PSP-7884 add take completion date.
  source/backend/api/Services/TakeService.cs
  source/backend/apimodels/Models/Concepts/Take/TakeMap.cs
  source/backend/apimodels/Models/Concepts/Take/TakeModel.cs
  source/frontend/src/components/common/form/FastDatePicker.tsx
  source/frontend/src/constants/takesStatusTypes.ts
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/repositories/useTakesRepository.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.ts
  source/frontend/src/mocks/takes.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Take.ts
Labels: enhancement

#3936 PSP-8182: Consolidation and subdivisions test cases
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Classes/Property.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SubdivisionConsolidation.feature
  testing/PIMS.Tests.Automation/Features/SubdivisionConsolidation.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionOfferSale.cs
  testing/PIMS.Tests.Automation/PageObjects/HelpDesk.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyPIMSFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionConsolidationProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/SubdivisionsConsolidationsSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3933 Take property update and cleanup
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/api/Services/TakeService.cs
  source/backend/api/Solvers/ITakeInteractionSolver.cs
  source/backend/api/Solvers/TakeInteractionSolver.cs
  source/backend/api/Startup.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyModel.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/Interfaces/ITakeRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/dal/Repositories/TakeRepository.cs
  source/backend/tests/core/Entities/PropertyHelper.cs
  source/backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
  source/backend/tests/unit/api/Services/TakeInteractionSolverTest.cs
  source/backend/tests/unit/api/Services/TakeServiceTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/components/common/GenericModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/__snapshots__/ReceivedDepositForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/__snapshots__/GenerateLetterRecipientsModal.test.tsx.snap
  source/frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap
  source/frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap
Labels: enhancement

#3945 PSP-8198 Vite fix
  source/frontend/src/tenants/tenant.tsx
  source/frontend/vite.config.ts
Labels: bug

#3947 Bump DEV version - IS78
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops, release-management

#3948 PSP-8203 FT: map icon that hovers when you try to choose property on the map is not displayed
  source/frontend/src/features/properties/map/MapContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
Labels: bug

#3941 Features/psp 7836 filter
  source/backend/Backup/Pims.sln
  source/backend/api/Areas/Property/Controllers/SearchController.cs
  source/backend/api/Areas/Property/Models/PropertyFilterModel.cs
  source/backend/api/Services/PropertyOperationService.cs
  source/backend/api/Services/TakeService.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyViewMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyViewModel.cs
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/core/Entities/PropertyHelper.cs
  source/backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
  source/backend/tests/unit/api/Controllers/Reports/PropertyControllerTest.cs
  source/backend/tests/unit/api/Services/PropertyOperationServiceTest.cs
  source/backend/tests/unit/api/Services/TakeInteractionSolverTest.cs
  source/backend/tests/unit/api/Services/TakeServiceTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
  source/frontend/src/features/mapSideBar/router/FilePropertyRouter.tsx
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionContainer.tsx
  source/frontend/src/features/properties/list/PropertyListView.test.tsx
  source/frontend/src/features/properties/list/PropertyListView.tsx
  source/frontend/src/features/properties/list/columns.tsx
  source/frontend/src/hooks/pims-api/useApiProperties.test.tsx
  source/frontend/src/hooks/pims-api/useApiProperties.ts
  source/frontend/src/hooks/repositories/useProperties.test.tsx
  source/frontend/src/hooks/repositories/useProperties.ts
  source/frontend/src/mocks/filterData.mock.ts
  source/frontend/src/mocks/properties.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Property.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyView.ts
  source/frontend/src/models/defaultInitializers.ts
  source/frontend/src/utils/propertyUtils.ts
Labels: enhancement

#3949 Updated consolidation and subdivisions to only display 3 decimal digits
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.test.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/shared/operations/SelectedOperationProperty.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.test.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
Labels: enhancement

#3944 psp-7739 make map layers use same parent sidebar as map advanced filt…
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/AdvancedFilterButton.test.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/AdvancedFilterButton.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersControl.test.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersControl.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.test.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersControl.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersMenu.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Layers/LeafletLayerListener.tsx
  source/frontend/src/features/advancedFilterBar/__snapshots__/AdvancedFilterBar.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/features/properties/map/MapContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/features/rightSideLayout/AdvancedFilterBar.test.tsx
  source/frontend/src/features/rightSideLayout/RightSideLayout.tsx
  source/frontend/src/features/rightSideLayout/__snapshots__/AdvancedFilterBar.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiProperties.test.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
Labels: ui/ux

#3952 Psp 8102 - new take types
  source/backend/apimodels/Models/Concepts/Take/TakeMap.cs
  source/backend/apimodels/Models/Concepts/Take/TakeModel.cs
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.ts
  source/frontend/src/mocks/takes.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Take.ts
Labels: enhancement

#3959 psp-8154 show warning when adding lease take type.
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.test.tsx
Labels: enhancement

#3958 PSP-8236 | disposition filter and advance filter not showing properties on first…
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.test.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
Labels: bug

#3956 Add asnotracking, with unrelated bugfix for view documents screen.
  source/backend/dal/Repositories/CompReqFinancialRepository.cs
  source/backend/dal/Repositories/DocumentRepository.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/dal/Repositories/H120CategoryRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/OrganizationRepository.cs
  source/backend/dal/Repositories/PersonRepository.cs
  source/backend/dal/Repositories/PropertyActivityRepository.cs
  source/backend/dal/Repositories/PropertyContactRepository.cs
  source/backend/dal/Repositories/TakeRepository.cs
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
Labels: enhancement

#3960 psp-8025 add warning to disposition file when closing a file not in s…
  source/backend/api/Services/DispositionFileService.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
Labels: enhancement

#3961 psp-8205 hide land act end date for certain types.
  source/backend/api/Services/TakeService.cs
  source/backend/apimodels/CodeTypes/DocumentRelationType.cs
  source/backend/apimodels/CodeTypes/ExternalResultStatus.cs
  source/backend/apimodels/CodeTypes/FormDocumentType.cs
  source/backend/apimodels/CodeTypes/LandActTypes.cs
  source/backend/apimodels/Models/Concepts/FinancialCode/FinancialCodeTypes.cs
  source/backend/tests/unit/api/Services/TakeServiceTest.cs
  source/frontend/src/components/common/form/FastDatePicker.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakesUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.ts
  source/frontend/src/mocks/lookups.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_LandActTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Take.ts
  tools/TsModelGenerator/Converters/EnumValueConverter.cs
Labels: enhancement

#3965 PSP-8094, PSP-8095: Warn user that property is part of an existing file
  source/backend/api/Areas/Property/Controllers/PropertyController.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyService.cs
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/ResearchView.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchForm.test.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchForm.tsx
  source/frontend/src/features/mapSideBar/research/add/ResearchProperties.test.tsx
  source/frontend/src/features/mapSideBar/research/add/ResearchProperties.tsx
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/hooks/pims-api/useApiProperties.ts
  source/frontend/src/hooks/repositories/usePimsPropertyRepository.ts
Labels: enhancement

#3963 Updated generation of models to use IsoDatetime alias
  source/frontend/src/models/api/UtcIsoDateTime.ts
  source/frontend/src/models/api/generated/ApiGen_Base_BaseAudit.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_AcquisitionFile.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Agreement.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Association.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompensationRequisition.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_DispositionFile.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_DispositionFileAppraisal.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_DispositionFileOffer.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_DispositionFileSale.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_FinancialCode.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_H120Category.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Insurance.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Lease.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_LeaseTerm.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Payment.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Person.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Product.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Property.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyActivity.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyActivityInvoice.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyManagement.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyOperation.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyView.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_ResearchFile.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_SecurityDeposit.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_SecurityDepositReturn.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Take.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_User.ts
  source/frontend/src/models/api/generated/ApiGen_Mayan_DocumentDetail.ts
  source/frontend/src/models/api/generated/ApiGen_Mayan_FileLatest.ts
  tools/TsModelGenerator/Specifications/PimsGenerationSpec.cs
Labels: tech-debt

#3967 PSP-8181 : FT-REG: Lease & License - H1005A is not including security deposit amount, properties Legal Description and land area
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/statusUpdateSolver.ts
  source/frontend/src/models/generate/GenerateProperty.ts
  source/frontend/src/models/generate/lease/GenerateLease.test.ts
  source/frontend/src/models/generate/lease/GenerateLease.ts
Labels: bug

#3968 PSP-8103 Warn user that property is part of any disposition file
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainerView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainerView.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionForm.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.tsx
Labels: enhancement

#3964 PSP-8253: Fixed looking for property in the property listview
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
Labels: bug

#3962 Psp 7883 - remove acquisition completion date.
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionFileYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_AcquisitionFile.ts
  source/frontend/src/models/defaultInitializers.ts
Labels: enhancement

#3974 Bump DEV version - IS79
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3973 psp-7999 close button styling
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/CompensationRequisitionTrayView.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/tabs/__snapshots__/ProjectTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/PropertyActivityDetailView.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
Labels: ui/ux

#3976 PSP-8182: Automation update based on last changes on TST Environment
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchDispositionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
  testing/Testing DB Scripts/MANUAL TESTING SCRIPTS.sql
Labels: test-scripts

#3977 snapshot updates.
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/tabs/__snapshots__/ProjectTabsContainer.test.tsx.snap
Labels: bug

#3978 vitest corrections
  .github/workflows/app-react.yml
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/components/common/buttons/Button.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputContainer.tsx
  source/frontend/src/components/common/form/Input.tsx
  source/frontend/src/components/layout/Header/Header.test.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/__snapshots__/AdvancedFilterButton.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersControl.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersMenu.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/__snapshots__/Control.test.tsx.snap
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/features/contacts/list/ContactListView.test.tsx
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.test.tsx
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/layouts/__snapshots__/Header.test.tsx.snap
  source/frontend/src/setupTests.ts
  source/frontend/src/store/slices/tenants/useTenants.test.tsx
  source/frontend/src/store/slices/tenants/useTenants.ts
  source/frontend/src/utils/test-utils.tsx
  source/frontend/vite.config.ts
Labels: bug
