Repository bcgov/PSP, pull requests merged in 2024-03, with the labels that each got.

#3817 PSP-7500 - UI/UX cleanup agreements create /edit
  source/backend/api/Areas/Acquisition/Controllers/AgreementController.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/IAcquisitionFileService.cs
  source/backend/api/Solvers/AcquisitionStatusSolver.cs
  source/backend/apimodels/CodeTypes/AcquisitionStatusTypes.cs
  source/backend/apimodels/CodeTypes/AgreementStatusTypes.cs
  source/backend/apimodels/CodeTypes/AgreementTypes.cs
  source/backend/apimodels/CodeTypes/DocumentRelationType.cs
  source/backend/apimodels/CodeTypes/ExternalResultStatus.cs
  source/backend/apimodels/CodeTypes/FormDocumentType.cs
  source/backend/apimodels/CodeTypes/PropertyOperationTypes.cs
  source/backend/apimodels/CodeTypes/SpatialReference.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AgreementMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AgreementModel.cs
  source/backend/dal/Repositories/AgreementRepository.cs
  source/backend/dal/Repositories/Interfaces/IAgreementRepository.cs
  source/backend/tests/unit/api/Controllers/Acquisition/AgreementControllerTest.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/router/AcquisitionRouter.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/add/AddAcquisitionAgreementContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/add/AddAcquisitionAgreementContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/common/UpdateAcquisitionAgreementForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/common/UpdateAcquisitionAgreementForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/common/__snapshots__/UpdateAcquisitionAgreementForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/form/AcquisitionAgreementForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/form/AcquisitionAgreementFormYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/models/AcquisitionAgreementFormModel.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAcquisitionAgreementContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAcquisitionAgreementContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/__snapshots__/UpdateAgreementsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/statusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/hooks/pims-api/useApiAgreements.ts
  source/frontend/src/hooks/repositories/useAgreementProvider.ts
  source/frontend/src/mocks/agreements.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Agreement.ts
Labels: enhancement

#3832 s75 Regenerated scaffold
  source/backend/entities/ef/PimsProperty.cs
  source/backend/entities/ef/PimsPropertyBoundaryVw.cs
  source/backend/entities/ef/PimsPropertyHist.cs
  source/backend/entities/ef/PimsPropertyLocationVw.cs
Labels: db-scaffold

#3831 PSP-7636 Prometheus/Sysdig alerts
  docker-compose.yml
  openshift/4.0/templates/monitoring/sysdig-team.yaml
  source/backend/api/Helpers/Healthchecks/PimsMetricsHealthCheck.cs
  source/backend/api/Startup.cs
  tools/prometheus/alert-rules.yml
  tools/prometheus/prometheus.yml
Labels: devops

#3833 PSP-7849 : Stop user from completing acquisition file if take is in progress
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/apimodels/CodeTypes/AcquisitionTakeStatusTypes.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx
Labels: enhancement

#3838 psp-7971 correct cancel modal behaviour on add subdivision.
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionContainer.tsx
Labels: bug

#3821 psp-7622 Testing
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/SubdivisionContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/SubdivisionContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/SubdivisionView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/SubdivisionView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/__snapshots__/SubdivisionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/columns.tsx
  source/frontend/src/mocks/propertyOperation.mock.ts
Labels: tech-debt

#3834 psp-7854 property consolidation backend service.
  source/backend/api/Areas/PropertyOperation/Controllers/PropertyOperationController.cs
  source/backend/api/Services/IPropertyOperationService.cs
  source/backend/api/Services/PropertyOperationService.cs
  source/backend/apimodels/Models/Concepts/PropertyOperation/PropertyOperationMap.cs
  source/backend/dal/Repositories/PropertyOperationRepository.cs
  source/backend/tests/unit/api/Controllers/PropertyOperation/PropertyOperationControllerTest.cs
  source/backend/tests/unit/api/Services/PropertyOperationServiceTest.cs
Labels: enhancement

#3836 psp 7616 | Subdivision Consolidation navigation
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/SideTray.tsx
  source/frontend/src/components/layout/SideNavBar/SubdCons.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/common/UpdateAcquisitionAgreementForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAcquisitionAgreementContainer.test.tsx
Labels: enhancement

#3790 PSP-7681 : FT-REG: Browser alerts should be replaced by established modal dialogs
  source/frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/create/Person/CreatePersonForm.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/AddLeaseForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
Labels: bug, 5.1

#3839 psp-7975 ensure disposition file filter by D- is consistent
  source/backend/api/Areas/Reports/Controllers/UserController.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/UserRepository.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileRepositoryTest.cs
Labels: bug

#3840 PSP-7869 Indicate "retired" on property information details
  source/backend/api/Areas/Property/Controllers/PropertyController.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/core/Entities/PropertyHelper.cs
  source/backend/tests/unit/api/Services/PropertyServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateLetter.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
Labels: enhancement

#3847 PSP-7916 : Disposition file GST collected - correct the calculation
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/__snapshots__/OffersAndSaleView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/__snapshots__/DispositionSaleForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/hooks/useCalculateNetProceeds.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/__snapshots__/UpdateDispositionSaleView.test.tsx.snap
Labels: enhancement

#3846 Psp 7984 node 20 update
  .github/workflows/app-react.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .github/workflows/version.yml
  openshift/4.0/templates/app/README.md
  openshift/4.0/templates/app/build.yaml
  openshift/4.0/templates/base-images/nodejs-20-ubi9.yaml
  source/frontend/.eslintrc.json
  source/frontend/.prettierignore
  source/frontend/Dockerfile
  source/frontend/config-overrides.js
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/customAxios.ts
  source/frontend/src/hooks/repositories/useBcAssessmentLayer.ts
  source/frontend/src/utils/test-utils.tsx
Labels: tech-debt

#3844 PSP-7967: Adding Subdivisions to Automation, PSP-7979: Changing Agreements UI
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
Labels: test-scripts

#3843 psp-7993 correct recursive model object.
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/models.ts
Labels: bug

#3850 PSP-7698: Adding or improving list views and pagination
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/ManageUsers.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchDispositionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProjects.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedPagination.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3853 PSP-7907 Add representation of RETIRED properties on the map view and advance filter
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyOperationService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/dal/Models/PropertyFilterCriteria.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Services/PropertyOperationServiceTest.cs
  source/frontend/.eslintignore
  source/frontend/.prettierignore
  source/frontend/src/assets/images/pins/retired.png
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/models.ts
  source/frontend/src/components/maps/leaflet/Control/Legend/Legend.scss
  source/frontend/src/components/maps/leaflet/Control/Legend/Legend.tsx
  source/frontend/src/components/maps/leaflet/Control/Legend/__snapshots__/Legend.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleForm.test.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/api/ProjectFilterCriteria.ts
Labels: enhancement

#3848 PSP-7860, psp-7962, psp-7963, psp-7964 | Added consolidation history view and fixed issues
  source/backend/dal/Repositories/PropertyOperationRepository.cs
  source/backend/entities/Partials/PropertyOperationType.cs
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationSectionView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/__snapshots__/OperationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/columns.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
  source/frontend/src/utils/dateUtils.ts
Labels: enhancement

#3835 psp-7658 display is retired in property list view.
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/components/common/TooltipIcon.scss
  source/frontend/src/components/common/TooltipIcon.tsx
  source/frontend/src/components/common/form/Multiselect.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/common/UpdateAcquisitionAgreementForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionForm.tsx
  source/frontend/src/features/properties/list/PropertyListView.test.tsx
  source/frontend/src/features/properties/list/PropertyListView.tsx
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  source/frontend/src/features/properties/list/columns.tsx
  source/frontend/src/utils/test-utils.tsx
Labels: enhancement

#3852 Psp-7818 display disposition errors with error modal
  source/frontend/src/components/propertySelector/search/PropertySelectorPidSearchContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionContainer.tsx
  source/frontend/src/hooks/repositories/usePimsPropertyRepository.ts
Labels: bug

#3851 psp-7313 change user override styling.
  source/frontend/src/hooks/useApiUserOverride.ts
Labels: bug

#3855 PSP-8002 : FT:UI/UX- Agreements: Agreement #(number) is not aligned a…
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
Labels: bug

#3861 PSP-6920 replace toast with warning modal
  source/frontend/src/features/acquisition/hooks/useAcquisitionFileExport.ts
  source/frontend/src/features/disposition/hooks/useDispositionFileExport.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationView.test.tsx
Labels: bug

#3859 PSP-8047 : FT-REG: Disposition Files - Net proceeds before & After SP…
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleForm.tsx
Labels: bug

#3863 correct issue in gen env script.
  tools/cicd/scripts/gen-env-files.sh
Labels: bug

#3862 Fix PSP-7927
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/research/add/ResearchProperties.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionContainer.tsx
  source/frontend/src/mocks/msw/handlers.ts
Labels: bug

#3864 Fix "retired" label on property information header
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
Labels: bug

#3857 Psp 8009 - login page changes.
  source/frontend/src/features/account/Login.test.tsx
  source/frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  source/frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/MOTI.ts
Labels: enhancement

#3868 Bump dev version - IS76
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops, release-management

#3860 PSP-8023 user management/access request tooltip updates.
  source/frontend/src/features/admin/access-request/RolesToolTip.tsx
Labels: enhancement

#3869 Consolidation fixes
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationContainer.test.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationContainer.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationSectionView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/columns.tsx
  source/frontend/src/features/mapSideBar/shared/operations/SelectedOperationProperty.tsx
  source/frontend/src/features/mapSideBar/shared/operations/SelectedOperationPropertyHeader.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: bug

#3871 Psp 7875 only show error modal or bomb - not both.
  source/frontend/src/features/contacts/hooks/useUpdateContact.ts
  source/frontend/src/features/documents/hooks/useDocumentGenerationRepository.ts
  source/frontend/src/features/documents/hooks/useDocumentProvider.ts
  source/frontend/src/features/documents/hooks/useDocumentRelationshipProvider.ts
  source/frontend/src/features/leases/hooks/useAddLease.ts
  source/frontend/src/features/leases/hooks/useUpdateLease.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/hooks/useUpdatePropertyResearch.ts
  source/frontend/src/features/mapSideBar/research/hooks/useAddResearch.ts
  source/frontend/src/features/mapSideBar/research/hooks/useGetResearch.ts
  source/frontend/src/features/mapSideBar/research/hooks/useUpdateResearch.ts
  source/frontend/src/features/mapSideBar/research/hooks/useUpdateResearchProperties.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.test.tsx
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/hooks/repositories/useAgreementProvider.test.tsx
  source/frontend/src/hooks/repositories/useDispositionProvider.test.tsx
  source/frontend/src/hooks/repositories/useDispositionProvider.ts
  source/frontend/src/hooks/repositories/useFinancialCodeRepository.ts
  source/frontend/src/hooks/repositories/useInterestHolderRepository.ts
  source/frontend/src/hooks/repositories/useNoteRepository.test.tsx
  source/frontend/src/hooks/repositories/usePimsPropertyRepository.ts
  source/frontend/src/hooks/repositories/useProductProvider.ts
  source/frontend/src/hooks/repositories/useProjectProvider.ts
  source/frontend/src/hooks/repositories/useProperties.test.tsx
  source/frontend/src/hooks/repositories/useProperties.ts
  source/frontend/src/hooks/repositories/usePropertyAssociations.ts
  source/frontend/src/hooks/repositories/usePropertyOperationRepository.ts
  source/frontend/src/hooks/repositories/useUserInfoRepository.ts
  source/frontend/src/hooks/useGeocoderRepository.ts
  source/frontend/src/hooks/util/useApiRequestWrapper.ts
  source/frontend/src/utils/axiosUtils.ts
  source/frontend/src/utils/utils.ts
Labels: enhancement

#3875 psp-8079 fix address list view search.
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
Labels: bug

#3874 psp-8077 ensure that bca calls use exact match pid searches.
  source/frontend/src/hooks/layer-api/layerUtils.ts
Labels: bug

#3872 psp-7971 correct cancel modal behaviour. - same as psp-7971
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationContainer.tsx
Labels: bug

#3873 psp-8059 allow properties in pims as consolidation destination if als…
  source/backend/api/Services/PropertyOperationService.cs
  source/backend/tests/unit/api/Services/PropertyOperationServiceTest.cs
Labels: bug

#3880 ensure that object changes do not cause infinite useEffect loop.
  source/frontend/src/features/leases/add/ConsultationSubForm.tsx
Labels: bug

#3876 Added logic to make sure the current status is taken into account
  source/backend/api/Services/AcquisitionFileService.cs
  source/frontend/public/mockServiceWorker.js
Labels: enhancement

#3878 psp-7607 prevent npe when opening non-inventory property.
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
Labels: bug

#3854 PSP-8004 : FT:UI/UX- Agreements: tooltip icon for Deposit due no late…
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
Labels: bug

#3879 correct error when loading research file property.
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/models.ts
Labels: bug

#3882 PSP-8024 helpdesk modal UI/IX refresh
  source/frontend/src/components/common/GenericModal.tsx
  source/frontend/src/features/help/components/HelpModal.tsx
  source/frontend/src/features/help/components/HelpSubmitBox.test.tsx
  source/frontend/src/features/help/components/__snapshots__/HelpSubmitBox.test.tsx.snap
  source/frontend/src/features/help/containers/HelpContainer.test.tsx
  source/frontend/src/features/help/containers/HelpContainer.tsx
  source/frontend/src/features/help/containers/HelpModalContentContainer.test.tsx
  source/frontend/src/features/help/containers/__snapshots__/HelpContainer.test.tsx.snap
  source/frontend/src/features/help/containers/__snapshots__/HelpModalContentContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/__snapshots__/GenerateLetterRecipientsModal.test.tsx.snap
  source/frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap
  source/frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap
Labels: enhancement

#3870 PSP-8075 : FT:Advanced Map Filter: Property info panel is displaying create Acquisition, lease/license, Disposition,subdivision and consolidation options
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
Labels: bug

#3881 Increase timeouts
  source/frontend/src/hooks/useInitialMapSelectorProperties.ts
Labels: bug

#3883 PSP-8093 label change/fix
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/__snapshots__/OffersAndSaleView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/UpdateDispostionSaleView.tsx
Labels: bug

#3884 PSP-7929 : Backend error - For all files do not include a retired property on selection
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/DispositionFilePropertyRepository.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionFilePropertyRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFilePropertyRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/LeaseRepositoryTest.cs
Labels: enhancement

#3885 PSP-7922 Completing disposition file - selected properties and errors
  source/backend/api/Services/DispositionFileService.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/__snapshots__/UpdateDispositionForm.test.tsx.snap
Labels: enhancement

#3886 PSP-7968, PSP-7967, PSP-8087
  testing/PIMS.Tests.Automation/Classes/Property.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/SubdivisionConsolidation.feature
  testing/PIMS.Tests.Automation/Features/SubdivisionConsolidation.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionOfferSale.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedPagination.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionConsolidationProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/SubdivisionsConsolidationsSteps.cs
Labels: test-scripts

#3877 psp-7995 consolidation/subdivision restrictions.
  source/backend/apimodels/Models/Concepts/ResearchFile/ResearchFilePropertyMap.cs
  source/frontend/src/components/propertySelector/search/PropertySelectorPidSearchContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/models.ts
  source/frontend/src/hooks/layer-api/layerUtils.ts
  source/frontend/src/hooks/repositories/usePimsPropertyRepository.ts
Labels: enhancement

#3888 psp-7924 property operation sub-table.
  source/frontend/src/components/Table/Table.scss
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/common/Section/Section.tsx
  source/frontend/src/constants/fileTypes.ts
  source/frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/styles.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/terms/__snapshots__/TermsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationFileAssocationsContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationFileAssociationsContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationSectionView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/__snapshots__/OperationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/propertyOperationAssociationColumns.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/propertyOperationColumns.tsx
Labels: enhancement

#3889 PSP-6765 empty file upload error
  source/backend/api/Services/DocumentFileService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
Labels: bug

#3893 PSP-8051 : FT:User is able to add the retired property record to the …
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFilePropertyModel.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/LeaseRepositoryTest.cs
Labels: bug

#3895 psp-8125 order of file types.
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationFileAssocationsContainer.tsx
Labels: bug

#3894 psp-7962 correct missing no rows message introduced by operation sect…
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/OperationSectionView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/OperationSectionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/OperationSectionView.tsx
Labels: bug

#3899 fix an error introduced in the isRetired conditional logic when getti…
  source/backend/dal/Repositories/PropertyRepository.cs
Labels: bug

#3897 psp-8133 do not show retired properties unless isretired specified.
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
Labels: bug

#3898 Remove router filter from map/list view.
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/list/PropertyListView.tsx
  source/frontend/src/hooks/useRouterFilter.test.tsx
  source/frontend/src/hooks/useRouterFilter.ts
Labels: enhancement

#3900 psp-8126 | Research files also match retired properties now
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
Labels: bug

#3902 Correct typo in file association display.
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/propertyOperationAssociationColumns.tsx
Labels: bug

#3901 IS-76 Fix
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/049_DML_PIMS_DATA_SOURCE_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/049_DML_PIMS_DATA_SOURCE_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/049_DML_PIMS_DATA_SOURCE_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/PIMS S75.00 Change Log.txt
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S75_00/Alter Down/049_DML_PIMS_DATA_SOURCE_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S75_00/Alter Up/049_DML_PIMS_DATA_SOURCE_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S75_00/Build/049_DML_PIMS_DATA_SOURCE_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S75_00/PIMS S75.00 Change Log.txt
Labels: db-migration

#3903 FT-REG: Consolidations - Incorrect instructions for selecting a child…
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
Labels: bug

#3904 Fully fix property getByPid, add unit tests.
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
Labels: bug

#3906 PSP-8144, PSP-8119 Disposition File bug fixes
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/LeaseService.cs
Labels: bug

#3909 Increment DEV version - IS77 5.2
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3892 update docker-compose so primary docker compose refers to mayan.
  Makefile
  docker-compose.yml
  source/backend/Dockerfile
  source/frontend/Dockerfile
  source/frontend/Makefile
  tools/mayan-edms/docker-compose.yml
Labels: enhancement, 5.2

#3856 psp-7986 update ts version - increment packages with vulnerabilities.
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/admin/access/ManageAccessRequestsPage.test.tsx
  source/frontend/src/features/admin/users/ManageUsersPage.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/bcAssessment/SalesTable.tsx
  source/frontend/src/hooks/repositories/useBcAssessmentLayer.ts
  source/frontend/src/hooks/util/useApiRequestWrapper.ts
  source/frontend/src/mocks/bcAssessment.mock.ts
  source/frontend/src/models/generate/acquisition/GenerateH120Property.ts
  source/frontend/src/models/layers/bcAssesment.ts
  source/frontend/src/utils/axiosUtils.ts
  source/frontend/tsconfig.json
Labels: dependencies, 5.2

#3910 ensure that max zoom is used consistently between map and map clusterer.
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Layers/InventoryLayer.tsx
  source/frontend/src/features/properties/map/MapContainer.test.tsx
Labels: bug, hotfix
