Repository bcgov/PSP, pull requests merged in 2024-02, with the labels that each got.

#3763 update uat and prod mayan urls.
  .github/workflows/depoy-prod-start.yml
  .github/workflows/retag-test-to-uat.yml
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_pre_release_hotfix.yml
Labels: bug, devops

#3765 Bump dev version - IS73
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: release-management

#3764 PSP-7638: Automation refactoring
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Classes/Contact.cs
  testing/PIMS.Tests.Automation/Classes/DigitalDocument.cs
  testing/PIMS.Tests.Automation/Classes/DispositionFile.cs
  testing/PIMS.Tests.Automation/Classes/FinancialCode.cs
  testing/PIMS.Tests.Automation/Classes/Lease.cs
  testing/PIMS.Tests.Automation/Classes/Project.cs
  testing/PIMS.Tests.Automation/Classes/Property.cs
  testing/PIMS.Tests.Automation/Classes/ResearchFile.cs
  testing/PIMS.Tests.Automation/Data/ExcelDataContext.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionExpropriation.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchDispositionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LoginSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/NotesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3753 Enhanced retrieval of deleted entries
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/ResearchFileRepository.cs
Labels: bug

#3750 psp-7679 display lease province and country
  source/backend/dal/Repositories/PropertyLeaseRepository.cs
  source/frontend/src/features/leases/detail/LeasePages/AddressSubForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/AddressSubForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/__snapshots__/AddressSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.test.tsx
Labels: bug

#3766 PSP-7661 Update map legend to include "Disposed" property (grey marker)
  source/frontend/src/assets/images/pins/disposed-highlight.png
  source/frontend/src/assets/images/pins/disposed.png
  source/frontend/src/components/maps/leaflet/Control/Legend/Legend.scss
  source/frontend/src/components/maps/leaflet/Control/Legend/Legend.tsx
  source/frontend/src/components/maps/leaflet/Control/Legend/__snapshots__/Legend.test.tsx.snap
Labels: enhancement

#3767 Scaffold/s73
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileSaleMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserAgentMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserSolicitorMap.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsDispositionFile.cs
  source/backend/entities/ef/PimsDispositionFileHist.cs
  source/backend/entities/ef/PimsDispositionFileProperty.cs
  source/backend/entities/ef/PimsDispositionFilePropertyHist.cs
  source/backend/entities/ef/PimsDispositionSale.cs
  source/backend/entities/ef/PimsDispositionSaleHist.cs
  source/backend/entities/ef/PimsDspPurchAgent.cs
  source/backend/entities/ef/PimsDspPurchAgentHist.cs
  source/backend/entities/ef/PimsDspPurchSolicitor.cs
  source/backend/entities/ef/PimsDspPurchSolicitorHist.cs
  source/backend/entities/ef/PimsProduct.cs
  source/backend/entities/ef/PimsProject.cs
  source/backend/entities/ef/PimsProperty.cs
  source/backend/entities/ef/PimsPropertyBoundaryVw.cs
  source/backend/entities/ef/PimsPropertyHist.cs
  source/backend/entities/ef/PimsPropertyLocationVw.cs
Labels: db-scaffold

#3768 PSP-7722 BVT. Disposition File: System is not displaying warning message when the status is moved from non-editable state(Cancelled)
  source/backend/api/Services/DispositionFileService.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
Labels: bug

#3769 psp-7515 allow disposition properties to be added/updated.
  docker-compose.yml
  source/backend/api/Areas/Disposition/Controllers/DispositionFileController.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/IDispositionFileService.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFilePropertyMap.cs
  source/backend/dal/Repositories/DispositionFilePropertyRepository.cs
  source/backend/dal/Repositories/Interfaces/IDispositionFilePropertyRepository.cs
  source/backend/tests/unit/api/Controllers/Disposition/DispositionControllerTest.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionFilePropertyRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFilePropertyRepositoryTest.cs
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
  source/frontend/src/hooks/pims-api/useApiDispositionFile.ts
  source/frontend/src/hooks/repositories/useDispositionProvider.ts
Labels: enhancement

#3708 psp-7323 Contact ambiguous
  source/backend/api/Areas/Contacts/Mapping/Search/ContactMap.cs
  source/backend/api/Areas/Contacts/Models/Search/ContactSummaryModel.cs
  source/backend/entities/Partials/Organization.cs
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.test.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/ContactResultComponent.test.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/summaryColumns.tsx
  source/frontend/src/features/contacts/list/ContactListView.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/models.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/models.test.ts
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/UpdateSummaryForm.tsx
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/models.ts
  source/frontend/src/interfaces/IContactSearchResult.ts
Labels: enhancement, 5.1

#3771 Psp 7736 correct typo in warning message, psp-7700 only 50 users being exported from excel report.
  source/backend/dal/Repositories/UserRepository.cs
  source/backend/tests/unit/dal/Repositories/UserRepositoryTest.cs
  source/frontend/src/features/contacts/contact/create/components/modals/CancelConfirmationModal.tsx
Labels: bug

#3772 psp-7726 re-order takes such that view and update are consistent.
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/models.ts
Labels: bug

#3773 psp-7690 support filtering when user appends D- to start of string.
  source/backend/api/Services/DispositionFileService.cs
Labels: bug

#3774 psp-7727 add missing tooltip to edit sales form.
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/__snapshots__/DispositionSaleForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/__snapshots__/UpdateDispositionSaleView.test.tsx.snap
Labels: bug

#3775 psp-7674 add project name/number to disposition export.
  source/backend/api/Services/DispositionFileService.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
Labels: enhancement

#3776 psp-7746 do not remove the disposition file from props during loading, only if…
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
Labels: bug

#3778 PSP-7731: Automation fixes
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionExpropriation.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/CDOGSTemplates.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionOfferSale.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyPIMSFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3746 PSP-7547 Auto-select region for disposition file
  source/backend/api/Areas/Disposition/Controllers/DispositionFileController.cs
  source/backend/api/Helpers/Extensions/PrincipalExtensions.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFilePropertyModel.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyMap.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/core/Entities/PropertyHelper.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/models/AddDispositionFormYupSchema.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionFormModel.ts
  source/frontend/src/hooks/useApiUserOverride.ts
Labels: enhancement

#3779 set table to not reset page when data changes.
  source/frontend/src/components/Table/Table.tsx
Labels: bug

#3784 PSP-7731: Automation Task
  testing/PIMS.Tests.Automation/Classes/DispositionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionOfferSale.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
Labels: test-scripts

#3744 psp-7548 ensure last update/date time reflects diposition file sub-entities correctly.
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/frontend/public/mockServiceWorker.js
  source/frontend/src/constants/dispositionFileStatus.ts
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.tsx
  source/frontend/src/features/mapSideBar/disposition/router/DispositionRouter.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionAppraisal/update/UpdateDispositionAppraisalContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionAppraisal/update/UpdateDispositionAppraisalContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/add/AddDispositionOfferContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/add/AddDispositionOfferContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/update/UpdateDispositionOfferContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/update/UpdateDispositionOfferContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/UpdateDispositionSaleContainer.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
Labels: enhancement

#3781 psp-7598 | Properties list view filter by ownership
  source/backend/api/Areas/Property/Controllers/SearchController.cs
  source/backend/api/Areas/Property/Mapping/Search/AddressMap.cs
  source/backend/api/Areas/Property/Mapping/Search/PropertyMap.cs
  source/backend/api/Areas/Property/Models/Search/AddressModel.cs
  source/backend/api/Areas/Property/Models/Search/PropertyFilterModel.cs
  source/backend/api/Areas/Property/Models/Search/PropertyModel.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyModel.cs
  source/backend/core/Extensions/QueryableExtensions.cs
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/dal/Helpers/Extensions/ResearchExtensions.cs
  source/backend/dal/Models/PropertyFilter.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/dal/Repositories/UserRepository.cs
  source/backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
  source/backend/tests/unit/api/Helpers/HttpResponseMessageExtensionsTest.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Solvers/AcquisitionStatusSolverTests.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/properties/filter/IPropertyFilter.ts
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/list/PropertyListView.tsx
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  source/frontend/src/features/properties/list/columns.tsx
  source/frontend/src/hooks/pims-api/useApiProperties.ts
  source/frontend/src/hooks/repositories/useProperties.ts
  source/frontend/src/hooks/useRouterFilter.test.tsx
  source/frontend/src/models/api/Property.ts
  source/frontend/src/utils/utils.ts
Labels: enhancement

#3783 psp-7726 guarantee same view/edit order by using id instead of timestamp. Ther…
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.tsx
Labels: bug

#3740 psp-7275 complete a disposition file. psp-7785, psp-7322, psp-7568
  source/backend/api/Constants/DispositionStatusTypes.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Solvers/AcquisitionStatusSolver.cs
  source/backend/api/Solvers/DispositionStatusSolver.cs
  source/backend/api/Solvers/IAcquisitionStatusSolver.cs
  source/backend/api/Solvers/IDispositionStatusSolver.cs
  source/backend/api/Startup.cs
  source/backend/dal/Exceptions/OverrideExceptions.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Solvers/DispositionStatusSolverTests.cs
  source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionMenu.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionMenu.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/columns.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/statusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.tsx
  source/frontend/src/features/mapSideBar/disposition/models/AddDispositionFormYupSchema.ts
  source/frontend/src/features/mapSideBar/disposition/router/DispositionRouter.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionStatusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionSummaryView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/__snapshots__/DispositionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/__snapshots__/UpdateDispositionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/__snapshots__/OffersAndSaleView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/hooks/useApiUserOverride.ts
  source/frontend/src/mocks/dispositionFiles.mock.ts
  source/frontend/src/models/api/UserOverrideCode.ts
  source/frontend/src/utils/axiosUtils.ts
Labels: enhancement

#3785 PSP-7655 advanced map filter for property ownership
  source/backend/dal/Models/PropertyFilterCriteria.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/core/Entities/PropertyHelper.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/models.ts
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/api/ProjectFilterCriteria.ts
  source/frontend/src/models/layers/pimsPropertyLocationView.ts
  source/frontend/src/react-app-env.d.ts
Labels: enhancement

#3789 PSP-7803 refresh the disposition file after updating checklist items
  source/frontend/src/features/mapSideBar/disposition/router/DispositionRouter.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/checklist/update/UpdateDispositionChecklistContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/checklist/update/UpdateDispositionChecklistContainer.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
Labels: bug

#3787 psp-7607 correct creating file from orange marker not working properly.
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/mocks/faParcelLayerResponse.mock.ts
  source/frontend/src/mocks/featureset.mock.ts
  source/frontend/src/utils/mapPropertyUtils.test.tsx
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: bug

#3792 text correction.
  source/backend/api/Services/DispositionFileService.cs
Labels: bug

#3794 psp-7680 correct todo.
  source/backend/api/Areas/Reports/Models/Acquisition/AgreementReportModel.cs
Labels: bug

#3795 Psp 7287 replace confusing boolean parameters with an object.
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/dal/Models/PropertyOwnershipState.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
Labels: bug

#3797 changed alignment of ownership items
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  source/frontend/src/features/properties/list/columns.tsx
Labels: enhancement

#3793 PSP-7819 FT: Disposition File - Grey marker appears as Other Interest when the Advanced Filters for IS_DISPOSED is not selected
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/leaflet/Layers/util.test.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/models/layers/pimsPropertyLocationView.ts
Labels: bug

#3799 Backmerge TEST to DEV
  .github/workflows/depoy-prod-start.yml
  .github/workflows/retag-test-to-uat.yml
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_pre_release_hotfix.yml
Labels: alignment, release-management

#3801 Bump DEV version
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops, release-management

#3802 PSP-7636 Prometheus/Sysdig metrics
  Makefile
  docker-compose.yml
  openshift/4.0/templates/sysdig/sysdig-team.yaml
  source/backend/api/Pims.Api.csproj
  source/backend/api/Startup.cs
  tools/prometheus/prometheus.yml
Labels: enhancement, tech-debt

#3805 Release 5.0 hotfix 1
  source/backend/api/Pims.Api.csproj
  source/backend/dal/Repositories/UserRepository.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
Labels: bug, hotfix

#3811 Backmerge test to dev
  source/backend/api/Pims.Api.csproj
  source/backend/dal/Repositories/UserRepository.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/AgreementSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
Labels: release-management

#3812 PSP-7676 | Updated the calculation of totals for property activity invoices
  source/backend/apimodels/Models/Concepts/Property/PropertyActivityMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyActivityModel.cs
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/PropertyActivityDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/models.ts
  source/frontend/src/mocks/PropertyManagementActivity.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyActivity.ts
Labels: enhancement

#3814 PSP-7832: Automation changes for IS74
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Classes/DispositionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchDispositionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3813 PSP-7868 invalid map pin logic. PSP-7872
  source/frontend/src/components/maps/leaflet/Layers/util.test.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/features/disposition/list/DispositionListView.test.tsx
  source/frontend/src/features/disposition/list/DispositionSearchResults/DispositionSearchResults.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.test.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.test.tsx
  source/frontend/src/features/mapSideBar/shared/tabs/checklist/detail/ChecklistView.test.tsx
  source/frontend/src/utils/mapPropertyUtils.test.tsx
Labels: bug

#3816 PSP-7622 | Added Subdivision view and backend retrieval of property operations
  source/backend/api/Areas/Property/Controllers/PropertyOperationController.cs
  source/backend/api/Services/IPropertyOperationService.cs
  source/backend/api/Services/PropertyOperationService.cs
  source/backend/api/Startup.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyModel.cs
  source/backend/apimodels/Models/Concepts/PropertyOperation/PropertyOperationMap.cs
  source/backend/apimodels/Models/Concepts/PropertyOperation/PropertyOperationModel.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/IPropertyOperationRepository.cs
  source/backend/dal/Repositories/PropertyOperationRepository.cs
  source/backend/entities/Partials/PropertyOperation.cs
  source/frontend/.eslintrc.json
  source/frontend/src/components/common/Section/Section.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/__snapshots__/UpdateDispositionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/SubdivisionContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/SubdivisionView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/columns.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/hooks/pims-api/useApiPropertyOperation.ts
  source/frontend/src/hooks/repositories/usePropertyOperationRepository.ts
  source/frontend/src/mocks/properties.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Property.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyOperation.ts
  source/frontend/src/models/defaultInitializers.ts
  source/frontend/src/utils/utils.ts
Labels: enhancement

#3806 Fix local development issues.
  source/backend/Dockerfile
  tools/mayan-edms/docker-compose.yml
Labels: tech-debt

#3820 ensure pre-release hotfix gha tags images correctly
  .github/workflows/uat_pre_release_hotfix.yml
Labels: bug

#3823 Fixed Lease sorting not working
  source/backend/dal/Repositories/LeaseRepository.cs
  source/frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
Labels: bug

#3822 Psp 7897 do not allow generated letter recipient text to overflow.
  source/frontend/src/components/common/OverflowTip.tsx
  source/frontend/src/components/propertySelector/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap
  source/frontend/src/features/leases/detail/__snapshots__/StackedTenantFields.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/GenerateLetterRecipientsModal.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/__snapshots__/GenerateLetterRecipientsModal.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/__snapshots__/ExpropriationForm1.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/__snapshots__/ExpropriationForm5.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/__snapshots__/ExpropriationForm9.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
Labels: bug

#3825 Fixed property list sort by lot size
  source/backend/api/Areas/Property/Models/PropertyFilterModel.cs
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/frontend/src/features/properties/list/PropertyListView.tsx
  source/frontend/src/features/properties/list/columns.tsx
Labels: bug

#3824 Fixed lease not showing pids on view
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.tsx
Labels: bug

#3827 Bump dev version - IS75
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#3819 psp-7880 disposition file number export display.
  source/backend/api/Services/DispositionFileService.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
Labels: bug

#3828 PSP-7888 fix missed mapping of sale completion date on frontend.
  source/frontend/src/features/mapSideBar/disposition/models/DispositionSaleFormModel.ts
Labels: bug
