Repository bcgov/PSP, pull requests merged in 2024-01, with the labels that each got.

#3686 dev dotnet 8 corrections.
  source/backend/api/Models/Health/EnvModel.cs
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  tools/keycloak/sync/Pims.Tools.Keycloak.Sync.csproj
Labels: bug

#3685 PSP-7363 : Delete Offer (Disposition)
  source/backend/api/Areas/Disposition/Controllers/DispositionFileController.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/IDispositionFileService.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IDispositionFileRepository.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainerView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainerView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.tsx
  source/frontend/src/hooks/pims-api/useApiDispositionFile.ts
  source/frontend/src/hooks/repositories/useDispositionProvider.ts
Labels: enhancement

#3671 Psp 7306 - update term modal ui
  source/frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/TermsPaymentsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermsPaymentsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermModal.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/__snapshots__/TermForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/__snapshots__/TermModal.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
Labels: enhancement

#3697 version bump.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
Labels: enhancement

#3689 Psp 7290 - disposition export.
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/retag-dev-to-test.yml
  source/backend/api/Areas/Reports/Controllers/DispositionController.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/IDispositionFileService.cs
  source/backend/dal/Models/DispositionFileExportModel.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IDispositionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileRepositoryTest.cs
  source/frontend/src/features/disposition/hooks/useDispositionFileExport.ts
  source/frontend/src/features/disposition/list/DispositionListView.test.tsx
  source/frontend/src/features/disposition/list/DispositionListView.tsx
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiDispositionFile.ts
Labels: enhancement

#3698 Test coverage
  source/backend/dal/IRepository.cs
  source/backend/dal/Repositories/BaseRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/OrganizationRepository.cs
  source/backend/dal/Repositories/PersonRepository.cs
  source/backend/dal/Repositories/ResearchFileRepository.cs
  source/backend/tests/core/Entities/DocumentHelper.cs
  source/backend/tests/core/Entities/LeaseHelper.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/DocumentRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ExpropriationPaymentRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/LeaseRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/OrganizationRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/PersonRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ProductRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ProjectRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ResearchRepositoryTest.cs
Labels: unit-tests

#3692 PSP-7427: Automation Refactoring
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Classes/FinancialCode.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionFilesDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/Login.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedPagination.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSearchProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/NotesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3705 psp-7536 ensure that execute function updates refresh index.
  source/frontend/src/hooks/useSearch.ts
Labels: bug

#3704 psp-7532 correct modal buttons.
  source/frontend/src/features/mapSideBar/acquisition/common/modals/AcquisitionFormModal.tsx
Labels: bug

#3703 psp-7530 update cancel modals to new format.
  source/frontend/src/features/contacts/contact/create/components/modals/CancelConfirmationModal.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/project/ProjectContainerView.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
Labels: bug

#3702 psp-7531 correct mapping issue.
  source/backend/apimodels/Models/Concepts/Property/PropertyActivityMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyActivityModel.cs
Labels: bug

#3701 psp-7528 delete document modal updates.
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
Labels: bug

#3700 psp-7516 notes modal corrections.
  source/frontend/src/components/common/form/NotesModal.test.tsx
  source/frontend/src/components/common/form/NotesModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/payments/PaymentsForm.test.tsx
Labels: bug

#3699 psp-7534 ensure dateonly is supported in excel exports.
  source/backend/core/Helpers/CsvHelper.cs
Labels: bug

#3712 PSP-7496, PSP-7497 UI UX Clean Up - Contact - Add and Update
  source/frontend/src/components/common/buttons/RemoveButton.tsx
  source/frontend/src/components/common/form/FormTitleBar.tsx
  source/frontend/src/features/contacts/contact/Organization/OrganizationSubForm.tsx
  source/frontend/src/features/contacts/contact/Person/PersonSubForm.tsx
  source/frontend/src/features/contacts/contact/create/CreateContactContainer.test.tsx
  source/frontend/src/features/contacts/contact/create/CreateContactContainer.tsx
  source/frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/Person/CreatePersonForm.tsx
  source/frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/components/address/Address.tsx
  source/frontend/src/features/contacts/contact/create/components/comments/CommentNotes.tsx
  source/frontend/src/features/contacts/contact/create/components/contactInfo/ContactEmail.tsx
  source/frontend/src/features/contacts/contact/create/components/contactInfo/ContactEmailList.tsx
  source/frontend/src/features/contacts/contact/create/components/contactInfo/ContactPhone.tsx
  source/frontend/src/features/contacts/contact/create/components/contactInfo/ContactPhoneList.tsx
  source/frontend/src/features/contacts/contact/create/components/index.ts
  source/frontend/src/features/contacts/contact/create/styles.ts
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.tsx
  source/frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/UpdateContactContainer.test.tsx
  source/frontend/src/features/contacts/contact/edit/UpdateContactContainer.tsx
  source/frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/typeSelector/ContactTypeSelector.tsx
  source/frontend/src/features/contacts/contact/typeSelector/__snapshots__/ContactTypeSelector.test.tsx.snap
  source/frontend/src/features/contacts/styles.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
Labels: enhancement

#3707 add missing disposition roles/claims to build.
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S69_00/Build/051_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S69_00/Build/074_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S69_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S70_00/Build/051_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S70_00/Build/074_DML_PIMS_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S70_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
Labels: bug, db-migration

#3715 PSP-7519: Automation updates
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyPIMSFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#3714 PSP-7316-7479 changes
  etl/MOTI_LEGACY_LIS_DISPOSITION_PIMS/LIS_DISPOSITION_PIMS_LOAD.dtsx
  etl/MOTI_LEGACY_LIS_DISPOSITION_PIMS/MOTI_LEGACY_LIS_DISPOSITION_PIMS.dtproj
  etl/MOTI_LEGACY_LIS_DISPOSITION_PIMS/MOTI_LEGACY_LIS_DISPOSITION_PIMS.dtproj.user
  etl/MOTI_LEGACY_LIS_DISPOSITION_PIMS/MOTI_LEGACY_LIS_DISPOSITION_PIMS.sln
  etl/MOTI_LEGACY_LIS_DISPOSITION_PIMS/Project.params
  etl/PIMS_HIST_LOAD/PIMS_HIST_LOAD.dtproj
  etl/PIMS_HIST_LOAD/PIMS_HIST_LOAD.dtproj.user
  etl/PIMS_HIST_LOAD/PIMS_HIST_LOAD.sln
  etl/PIMS_HIST_LOAD/PIMS_HIST_TABLES_LOAD.dtsx
  etl/PIMS_HIST_LOAD/Project.params
Labels: etl

#3717 Psp 6333 - mayan sync via oc task/git action
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/mayan-sync.yml
  .github/workflows/retag-dev-to-test.yml
  openshift/4.0/templates/jobs/mayan-sync-task.yaml
  openshift/4.0/templates/jobs/mayan-sync.yaml
Labels: devops

#3718 PSP-7414 Tech debt: Remove obsolete roles from PSP frontend
  source/frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  source/frontend/src/constants/roles.ts
  source/frontend/src/features/account/Login.test.tsx
  source/frontend/src/features/account/Login.tsx
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestContainer.test.tsx.snap
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestForm.test.tsx.snap
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserContainer.test.tsx.snap
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserForm.test.tsx.snap
  source/frontend/src/hooks/useKeycloakWrapper.tsx
  source/frontend/src/mocks/lookups.mock.ts
Labels: tech-debt

#3721 psp-7532 update message text.
  source/backend/api/Services/AcquisitionFileService.cs
Labels: bug

#3722 fixed empty time parsing incorrectly
  source/frontend/src/features/documents/ComposedDocument.ts
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.test.tsx
  source/frontend/src/models/api/UtcIsoDateTime.ts
Labels: bug

#3719 PSP-7480: Digital Documents subtitles
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailForm.test.tsx.snap
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailView.test.tsx.snap
Labels: bug

#3729 Version bump
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: release-management

#3732 PSP-7648- Create Disposition Form
  testing/PIMS.Tests.Automation/Classes/DispositionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
Labels: test-scripts

#3730 Psp 7611 - ensure undefined/null handled correctly by contact parsers.
  source/frontend/src/features/mapSideBar/acquisition/common/models.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionTeamSubFormModel.ts
Labels: bug

#3734 PSP-7578 Remove Project and Product from Header of Disposition File
  source/frontend/src/components/common/UserNameTooltip.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionHeader.test.tsx.snap
Labels: enhancement

#3728 psp-7630 ensure that properties added directly to inventory have the …
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
Labels: bug

#3726 psp-7609 ensure that changing the status of a disposition file generates a note
  source/backend/api/Services/DispositionFileService.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
Labels: bug

#3733 psp-7565 update wording, display logic on edit button tooltips.
  source/frontend/src/features/mapSideBar/acquisition/common/constants.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/UpdateAgreementsForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/update/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/mocks/properties.mock.ts
Labels: enhancement

#3738 generated scaffold and removed lingering files
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsOrganization.cs
  source/backend/entities/ef/PimsPerson.cs
  source/backend/entities/ef/PimsPropPropClassificationHist.cs
  source/backend/entities/ef/PimsProperty.cs
  source/backend/entities/ef/PimsPropertyBoundaryVw.cs
  source/backend/entities/ef/PimsPropertyDispositionFile.cs
  source/backend/entities/ef/PimsPropertyDispositionFileHist.cs
  source/backend/entities/ef/PimsPropertyHist.cs
  source/backend/entities/ef/PimsPropertyLocationVw.cs
Labels: db-scaffold

#3741 PSP 7648-Disposition Checklist Automation
  testing/PIMS.Tests.Automation/Classes/DispositionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionChecklist.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
Labels: test-scripts

#3731 PSP-7296 : Create/Edit Sales Details (Disposition)
  source/backend/api/Areas/Disposition/Controllers/DispositionFileController.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/IDispositionFileService.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileModel.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileSaleMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFileSaleModel.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserAgentMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserMap.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionSalePurchaserSolicitorMap.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IDispositionFileRepository.cs
  source/backend/tests/unit/api/Controllers/Disposition/DispositionControllerTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileRepositoryTest.cs
  source/frontend/src/features/mapSideBar/disposition/form/DispositionTeamSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/models/DispositionSaleContactModel.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionSaleFormModel.test.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionSaleFormModel.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionSalePurchaserModel.ts
  source/frontend/src/features/mapSideBar/disposition/router/DispositionRouter.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainerView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/__snapshots__/OffersAndSaleContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionSaleContactDetails/DispositionSaleContactDetails.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleFormYupSchema.ts
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSalePurchasersSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/__snapshots__/DispositionSaleForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/hooks/useCalculateNetProceeds.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/UpdateDispositionSaleContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/UpdateDispositionSaleContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/UpdateDispositionSaleView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/UpdateDispostionSaleView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/__snapshots__/UpdateDispositionSaleView.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiDispositionFile.ts
  source/frontend/src/hooks/repositories/useDispositionProvider.ts
  source/frontend/src/interfaces/IContactSearchResult.ts
  source/frontend/src/mocks/dispositionFiles.mock.ts
  source/frontend/src/models/api/DispositionFile.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_DispositionFileAppraisal.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_DispositionFileSale.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyActivity.ts
  source/frontend/src/utils/personUtils.ts
Labels: enhancement

#3743 PSP-7639 PIMS HIST Table fix commit
  etl/PIMS_HIST_LOAD/PIMS_HIST_LOAD.dtproj
  etl/PIMS_HIST_LOAD/PIMS_HIST_TABLES_LOAD.dtsx
  etl/PIMS_HIST_LOAD/PIMS_HIST_TABLES_LOAD_LISOS_ETL_USER.dtsx
Labels: etl

#3735 PSP-7509 : Allow Contractor to Create or Edit Disposition File
  source/backend/api/Helpers/Extensions/AcquisitionFileExtensions.cs
  source/backend/api/Helpers/Extensions/DispositionFileExtensions.cs
  source/backend/api/Helpers/Extensions/PrincipalExtensions.cs
  source/backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/dal/Repositories/DispositionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IDispositionFileRepository.cs
  source/backend/tests/unit/api/Controllers/Disposition/DispositionControllerTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileRepositoryTest.cs
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainerView.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionForm.tsx
  source/frontend/src/features/mapSideBar/disposition/hooks/useAddDispositionFormManagement.ts
  source/frontend/src/hooks/useApiUserOverride.ts
Labels: enhancement

#3745 PSP-7510 : Disallow Contractor to Remove Themself from Disposition File
  source/backend/api/Helpers/Extensions/DispositionFileExtensions.cs
  source/backend/api/Helpers/Extensions/PrincipalExtensions.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionContainer.tsx
  source/frontend/src/utils/test-utils.tsx
Labels: enhancement

#3736 psp-7580 correct disposition list view file number.
  source/frontend/src/features/disposition/list/DispositionSearchResults/DispositionSearchResults.test.tsx
  source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap
  source/frontend/src/features/disposition/list/DispositionSearchResults/columns.tsx
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
Labels: bug

#3737 Psp 7614, 7657, 7626, 7610 assorted text corrections.
  source/backend/api/Services/DispositionFileService.cs
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionTeamSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainerView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleContainerView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/__snapshots__/OffersAndSaleContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.tsx
Labels: bug

#3752 PSP-7682, 7683, 7172 Text changes
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionSummaryView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/__snapshots__/DispositionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/PropertyActivityDetailView.tsx
Labels: bug

#3749 correct message text.
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
Labels: bug

#3754 PSP- 7638: Automation Refactoring and Disposition Files
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Classes/DispositionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionExpropriation.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/CDOGSTemplates.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionOfferSale.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchDispositionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3755 PSP-6668 FT: Acquisition File: Compensation: Show error modal instead of toast when total allowable compensation value is less than total compensation value
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
Labels: bug

#3747 PSP-7664 FT-REG: When cancelling, the confirmation modal should be consistent around different types of files
  source/frontend/src/components/common/CancelConfirmationModal.tsx
  source/frontend/src/components/common/GenericModal.test.tsx
  source/frontend/src/components/common/GenericModal.tsx
  source/frontend/src/features/admin/financial-codes/add/AddFinancialCodeForm.test.tsx
  source/frontend/src/features/admin/financial-codes/update/UpdateFinancialCodeForm.test.tsx
  source/frontend/src/features/contacts/contact/create/components/modals/CancelConfirmationModal.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/__snapshots__/GenerateLetterRecipientsModal.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/project/ProjectContainerView.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap
  source/frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap
  source/frontend/src/hooks/useModalContext.tsx
Labels: bug

#3751 psp-7680 add agreement status type to agreement export.
  source/backend/dal/Repositories/AgreementRepository.cs
  source/backend/tests/unit/dal/Repositories/AgreementRepositoryTest.cs
Labels: bug
