Repository bcgov/PSP, pull requests merged in 2024-08, with the labels that each got.

#4237 PSP-8279, PSP-8937 UI fixes
  source/frontend/src/components/common/SimplePagination.scss
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupContent.test.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseRenewalsView.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/models.test.ts
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
Labels: bug, 5.5

#4238 Increment DEV version
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4239 - define a SQL server version to prevent issues
  source/database/mssql/Dockerfile
  source/database/mssql/scripts/dbscripts/Dockerfile
Labels: tech-debt

#4240 PSP-8994 : FT: Lease & Licenses Details - Purpose Other field has an …
  source/backend/apimodels/CodeTypes/LeaseLicenceTypes.cs
  source/backend/apimodels/CodeTypes/LeasePurposeTypes.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/PaymentPeriodsView.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/periodColumns.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateLicenceOfOccupation.ts
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_LeaseLicenceTypes.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_LeasePurposeTypes.ts
Labels: bug

#4242 Lease purpose fixes
  source/backend/dal/Repositories/LeasePaymentRepository.cs
  source/backend/tests/core/Entities/LeaseHelper.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
Labels: bug

#4243 PSP-8986: Automation updates based on IS85 changes.
  testing/PIMS.Tests.Automation/Classes/Lease.cs
  testing/PIMS.Tests.Automation/Classes/Property.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePeriodPayments.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchDispositionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#4245 Fixes Mayan null pointer for Size value
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/DocumentService.cs
  source/backend/apimodels/Models/Mayan/Document/DocumentDetailModel.cs
  source/backend/apimodels/Models/Mayan/Document/DocumentTypeModel.cs
  source/backend/apimodels/Models/Mayan/Document/FileLatestModel.cs
Labels: bug, hotfix

#4247 psp-8983 add pin to property selector screen.
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.test.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.tsx
  source/frontend/src/components/propertySelector/map/__snapshots__/PropertyMapSelectorSubForm.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
Labels: enhancement

#4248 Psp 8983 - correct legal description not displaying when selecting property.
  source/frontend/src/hooks/repositories/mapLayer/useFullyAttributedParcelMapLayer.ts
Labels: bug

#4254 PSP-8937 Fix typo on lease renewal section
  source/frontend/src/components/Table/Table.scss
  source/frontend/src/features/leases/add/RenewalSubForm.tsx
  source/frontend/src/features/leases/leaseUtils.ts
Labels: bug

#4250 psp-9007 ensure automatic gst amount calculations work properly.
  source/frontend/src/components/common/form/FastCurrencyInput.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/VariablePeriodSubForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/__snapshots__/PeriodForm.test.tsx.snap
Labels: bug

#4252 PSP-9008 Fix incorrect naming of form fields.
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.tsx
Labels: bug

#4253 psp-9012 ensure that gst is only calculated based on "live" form value.
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentFormContent.tsx
Labels: bug

#4251 psp-7788 | Crown Layers on popup
  source/frontend/public/tenants/tenant.json
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/constants.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/repositories/mapLayer/useCrownLandLayer.ts
  source/frontend/src/models/layers/crownLand.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: enhancement

#4255 psp-7878 | Improvements to zoom handling
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/features/properties/map/MapContainer.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
Labels: enhancement

#4259 PSP-8704 changes
  etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs.dtproj
  etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs.dtproj.user
  etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs.dtsx
  etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs.sln
  etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/PRE_ETL_CREATE_TEMP_Tables.dtsx
  etl/PIMS_PROPERTY_FIX_DUPLICATE_ADDRESSIDs/Project.params
Labels: etl

#4256 Update frontend to handle desynchronized models.
  source/frontend/package-lock.json
  source/frontend/src/constants/API.ts
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderYupSchema.ts
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/LeaseStakeholderContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/PrimaryContactWarningModal.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/PrimaryContactWarningModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/SelectedTableHeader.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/StakeholderOrganizationContactInfo.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/StakeholderPersonContactInfo.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/ViewStakeholderForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/ViewStakeholderForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/__snapshots__/AddLeaseStakeholderContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/__snapshots__/AddLeaseStakeholderForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/__snapshots__/AddLeaseTenantContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/__snapshots__/PrimaryContactWarningModal.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/__snapshots__/ViewStakeholderForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/__snapshots__/ViewTenantForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/columns.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/models.ts
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/styles.ts
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/ViewTenantForm.tsx
  source/frontend/src/features/leases/detail/StackedStakeholderFields.test.tsx
  source/frontend/src/features/leases/detail/StackedStakeholderFields.tsx
  source/frontend/src/features/leases/detail/__snapshots__/StackedStakeholderFields.test.tsx.snap
  source/frontend/src/features/leases/hooks/useLeaseDetail.ts
  source/frontend/src/features/leases/index.ts
  source/frontend/src/features/leases/list/LeaseListView.test.tsx
  source/frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.test.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateLicenceOfOccupation.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateLicenceOfOccupation.ts
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeaderTenants.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/LeaseAssociationContent.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/hooks/pims-api/useApiLeaseStakeholders.ts
  source/frontend/src/hooks/repositories/useLeaseStakeholderRepository.ts
  source/frontend/src/hooks/repositories/useLeaseTenantRepository.ts
  source/frontend/src/interfaces/IContactSearchResult.ts
  source/frontend/src/interfaces/ISelectedTenant.ts
  source/frontend/src/interfaces/ITenant.ts
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/mocks/lookups.mock.ts
  source/frontend/src/models/generate/lease/GenerateLease.ts
Labels: bug

#4265 psp-8960 correct auth errors with fa layer.
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
  source/frontend/src/hooks/layer-api/wfsAxios.ts
  source/frontend/src/hooks/repositories/mapLayer/useFullyAttributedParcelMapLayer.ts
Labels: bug

#4271 Bump DEV version to IS87
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4260 PSP-8986: Updates on period and payments automated test cases
  testing/PIMS.Tests.Automation/Classes/Lease.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePeriodPayments.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#4270 psp-9039 | Updated payment labels
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentFormContent.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/__snapshots__/PaymentForm.test.tsx.snap
Labels: enhancement

#4268 PSP-8802 | Updated frontend with matching propery attributes. Removed IProperty
  source/frontend/src/components/common/ExpandableTextList.test.tsx
  source/frontend/src/components/maps/MapView.test.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.test.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/models.ts
  source/frontend/src/constants/index.ts
  source/frontend/src/constants/propertyClassificationTypes.ts
  source/frontend/src/features/leases/detail/LeaseHeaderAddresses.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.helpers.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/features/research/list/ResearchListView.test.tsx
  source/frontend/src/hooks/useLookupCodeHelpers.tsx
  source/frontend/src/interfaces/IProperty.ts
  source/frontend/src/interfaces/index.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/mocks/data.mock.ts
  source/frontend/src/mocks/filterData.mock.ts
  source/frontend/src/mocks/properties.mock.ts
  source/frontend/src/mocks/researchFile.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Property.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyView.ts
  source/frontend/src/models/defaultInitializers.ts
  source/frontend/src/models/layers/pimsPropertyLocationView.ts
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: enhancement, tech-debt

#4272 PSP-9014 : Contact Manager: Link Individual Contact to an Existing Or…
  source/backend/api/Areas/Contacts/Mapping/Contact/PersonMap.cs
  source/backend/api/Areas/Contacts/Models/Contact/PersonModel.cs
  source/backend/apimodels/CodeTypes/AddressUsageTypes.cs
  source/frontend/src/constants/addressTypes.ts
  source/frontend/src/constants/index.ts
  source/frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.test.tsx
  source/frontend/src/features/contacts/contact/create/Person/CreatePersonForm.test.tsx
  source/frontend/src/features/contacts/contact/create/Person/CreatePersonForm.tsx
  source/frontend/src/features/contacts/contact/detail/Organization.test.tsx
  source/frontend/src/features/contacts/contact/detail/Person.test.tsx
  source/frontend/src/features/contacts/contact/detail/utils.ts
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.tsx
  source/frontend/src/features/contacts/contactUtils.ts
  source/frontend/src/features/contacts/formModels.test.ts
  source/frontend/src/features/contacts/formModels.ts
  source/frontend/src/features/documents/ComposedDocument.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
  source/frontend/src/interfaces/IContact.ts
  source/frontend/src/mocks/organization.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_AddressUsageTypes.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.test.ts
Labels: bug

#4269 standardize usage of '-' and $0.00
  source/frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/PeriodPaymentsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/PaymentPeriodsView.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/__snapshots__/PaymentPeriodsView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/periodColumns.tsx
Labels: enhancement

#4275 PSP-9021 : Lease / Licence - Remove Documentation section from File D…
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseForm.tsx
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/ReferenceSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailDocumentation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailDocumentation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
Labels: enhancement

#4284 Add the GST number to the compensation detail view.
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
Labels: bug

#4285 psp-9063 correct update lease form from not displaying warning when lease inva…
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
Labels: bug

#4288 psp-9041 fix issues with PIN-only properties.
  source/frontend/src/components/propertySelector/MapSelectorContainer.tsx
Labels: bug

#4283 psp-9058, psp-9059 ensure that the gst calculation does not override current va…
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/VariablePeriodSubForm.tsx
Labels: bug

#4286 psp-9080 add missing LEASE_STAKEHOLDER_TYPE codes.
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S87_00/Alter Down/154_DML_PIMS_LEASE_STAKEHOLDER_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S87_00/Alter Up/154_DML_PIMS_LEASE_STAKEHOLDER_TYPE_Alter_Up.sql
  source/frontend/src/components/common/form/Select.tsx
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/ViewStakeholderForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/columns.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/tabs/checklist/update/__snapshots__/UpdateChecklistForm.test.tsx.snap
Labels: bug, db-hotfix

#4287 PSP-9122 : Lease compensation does not have access to new payees with…
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/mocks/lease.mock.ts
Labels: bug

#4289 PSP-9075 | Fixed lease filter
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/core/Entities/LeaseHelper.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
Labels: bug

#4290 psp-8939 | Added message when changing period flexible type
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.tsx
Labels: bug

#4295 PSP-9083, PSP-9062 Document file upload fixes
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  source/frontend/src/features/documents/documentUpload/DocumentUploadForm.test.tsx
  source/frontend/src/features/documents/documentUpload/DocumentUploadForm.tsx
  source/frontend/src/features/documents/documentUpload/DocumentUploadModal.tsx
  source/frontend/src/features/documents/documentUpload/__snapshots__/DocumentUploadForm.test.tsx.snap
  source/frontend/src/features/documents/list/DocumentListView.test.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/notes/list/NoteListView.tsx
  source/frontend/src/mocks/documents.mock.ts
Labels: bug

#4279 psp-8830 use minimal version of location view in order to populate in…
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/mocks/msw/handlers.ts
  source/frontend/src/tenants/config/defaultTenant.ts
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_MINIMAL_VW/featuretype.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_MINIMAL_VW/layer.xml
Labels: enhancement, 5.6

#4282 psp-8955 add file streaming back to PIMS.
  source/backend/api/Areas/Documents/DocumentController.cs
  source/backend/api/Repositories/Mayan/IEdmsDocumentRepository.cs
  source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  source/backend/api/Repositories/RestCommon/BaseRestRepository.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/Services/IDocumentService.cs
  source/backend/apimodels/Models/Requests/Http/FileStreamResponse.cs
  source/backend/tests/unit/api/Controllers/Document/DocumentControllerTest.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  source/frontend/src/features/documents/DocumentPreviewContainer.test.tsx
  source/frontend/src/features/documents/DownloadDocumentButton.tsx
  source/frontend/src/features/documents/hooks/useDocumentProvider.ts
  source/frontend/src/hooks/pims-api/useApiDocuments.ts
  source/frontend/src/hooks/util/useApiRequestWrapper.ts
Labels: enhancement

#4293 psp-8982 Display pin in header.
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/property/__snapshots__/MotiInventoryHeader.test.tsx.snap
Labels: enhancement

#4292 PSP-8932 | Added checks to create pages so navigating with data shows a warning
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationContainer.test.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationContainer.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainerView.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.test.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionContainer.test.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionContainer.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
Labels: bug

#4297 Psp 9058 - gst calculation fixes.
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/VariablePeriodSubForm.tsx
Labels: bug

#4299 Lease Consultation updates
  source/backend/api/Areas/Leases/Controllers/ConsultationController.cs
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/lease/detail/LeaseTabsContainer.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/LeaseRouter.tsx
Labels: enhancement

#4291 PSP-9053 Update L/L H1005A with additional fields
  source/backend/apimodels/CodeTypes/LeaseInsuranceTypes.cs
  source/backend/apimodels/CodeTypes/LeaseSecurityDepositTypes.cs
  source/frontend/src/features/leases/detail/LeasePages/payment/PeriodPaymentsContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateLicenceOfOccupation.test.tsx
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_LeaseInsuranceTypes.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_LeaseSecurityDepositTypes.ts
  source/frontend/src/models/generate/lease/GenerateLease.test.ts
  source/frontend/src/models/generate/lease/GenerateLease.ts
Labels: enhancement, 5.5

#4280 PSP-8977 : Add Total Allowable Compensation to Compensation Section
  source/backend/api/Services/CompReqFinancialService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/ICompReqFinancialService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseMap.cs
  source/backend/dal/Repositories/CompReqFinancialRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompReqFinancialRepository.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListView.tsx
  source/frontend/src/hooks/repositories/useLeaseRepository.ts
  source/frontend/src/mocks/lease.mock.ts
Labels: enhancement, 5.5
