Repository bcgov/PSP, pull requests merged in 2024-09, with the labels that each got.

#4301 is88 Scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsLease.cs
  source/backend/entities/ef/PimsLeaseConsultation.cs
  source/backend/entities/ef/PimsLeaseHist.cs
  source/backend/entities/ef/PimsProduct.cs
Labels: db-scaffold

#4302 Version bump - IS88
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.test.tsx
Labels: devops, release-management

#4303 PSP-9002 : Generate H120 Lease/Licence
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/ICompensationRequisitionService.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs
  source/backend/tests/unit/api/Controllers/Acquisition/AcquisitionControllerTest.cs
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/pims-api/useApiRequisitionCompensations.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/mocks/organization.mock.ts
  source/frontend/src/models/generate/CompensationRequisition/GenerateCompReqFileLease.ts
  source/frontend/src/models/generate/CompensationRequisition/ICompensationRequisitionFile.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
  source/frontend/src/models/generate/acquisition/GenerateH120InterestHolder.ts
  source/frontend/src/models/generate/acquisition/GenerateH120Property.ts
Labels: enhancement, 5.5

#4304 PSP-9047 : Add product for L/L payable lease and show on h120
  source/backend/apimodels/Models/Concepts/Lease/LeaseMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseModel.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/frontend/src/features/leases/add/LeaseDetailSubForm.test.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailView.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Lease.ts
  source/frontend/src/models/defaultInitializers.ts
  source/frontend/src/models/generate/CompensationRequisition/GenerateCompReqFileLease.ts
  source/frontend/src/models/generate/GenerateProduct.ts
Labels: enhancement, 5.5

#4305 PSP-9065 UI cleanup
  source/frontend/src/features/leases/add/RenewalSubForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailFeeDetermination.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseRenewalsView.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseRenewalsView.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.test.ts
Labels: enhancement

#4308 PSP-8880: Fixes based on last PR comments
  source/backend/apimodels/Models/Concepts/Lease/LeaseStakeholderTypeMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseStakeholderTypeModel.cs
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/columns.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/lease/detail/LeaseTabsContainer.tsx
Labels: enhancement, 5.5

#4306 PSP-9164 : FT:Reg:Lease&Licence File: In the update mode if user deselects the project that has been already selected and try to save the form, system is still displaying associated selected product in the view/edit screen
  source/frontend/src/features/leases/add/LeaseDetailSubForm.test.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/mocks/lease.mock.ts
Labels: bug, 5.5

#4309 PSP-8684 | Updated Lease list report
  source/backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  source/backend/api/Areas/Reports/Models/Lease/LeaseModel.cs
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/dal/Helpers/Extensions/PropertyViewExtensions.cs
  source/backend/dal/Helpers/Extensions/TypeCodeExtensions.cs
  source/backend/tests/unit/api/Controllers/Reports/LeaseControllerTest.cs
Labels: enhancement

#4307 PSP-8988 Add Crown Details tab for any property that has Tantalis record
  source/frontend/src/features/mapSideBar/property/ComposedProperty.ts
  source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/crown/CrownDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.test.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/hooks/repositories/useComposedProperties.ts
  source/frontend/src/mocks/crownTenuresLayerResponse.mock.ts
  source/frontend/src/mocks/ltsa.mock.ts
  source/frontend/src/utils/dateUtils.test.ts
  source/frontend/src/utils/dateUtils.ts
Labels: enhancement

#4311 Update payee options model to correctly handle null/undefined.
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
Labels: bug

#4319 5.6 merge from dev
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/features/leases/hooks/useLeaseDetail.ts
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/context/sidebarContext.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
Labels: alignment

#4318 PIMS devops updates
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-logging.yml
  .github/workflows/app-react.yml
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/ci-cd-pims-master.yml
  .github/workflows/credentials-comment-pr.yml
  .github/workflows/credentials-scan.yml
  .github/workflows/db-schma.yml
  .github/workflows/deploy-prod-end.yml
  .github/workflows/deploy-prod-start.yml
  .github/workflows/image-scan-analysis.yml
  .github/workflows/integration-test.yml
  .github/workflows/keycloak-sync.yml
  .github/workflows/mayan-sync.yml
  .github/workflows/release.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
  .github/workflows/tag.yml
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_pre_release_hotfix.yml
  .github/workflows/version.yml
Labels: devops

#4317 PSP-8713: UI UX Clean Up - First Page Banner + Warning Information + Images
  source/frontend/public/tenants/tenant.json
  source/frontend/src/features/account/Login.test.tsx
  source/frontend/src/features/account/Login.tsx
  source/frontend/src/features/account/LoginLoading.tsx
  source/frontend/src/features/account/LoginStyled.tsx
  source/frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  source/frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/MOTI.ts
Labels: enhancement, 5.6

#4322 psp-9177 | Fixed null pointer when generated lease report
  source/backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
Labels: bug

#4316 PSP-9164 : FT:Reg:Lease&Licence File: In the update mode if user dese…
  source/frontend/src/features/leases/models.ts
Labels: bug, 5.5

#4323 PSP-9144 | Set default to 'No' on response received dropdown
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/ConsultationEditForm.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/models.ts
Labels: bug

#4327 psp-9064 Correct performance issue with getting files associated to p…
  source/backend/dal/Repositories/PropertyRepository.cs
Labels: bug

#4324 psp-9173 fixes to lease payments, project comp req, and lease exports.
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Services/CompReqFinancialService.cs
  source/backend/api/Services/ILeaseService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
Labels: bug

#4328 PSP-8317: Changes on foot note font size and spacing
  source/frontend/package-lock.json
  source/frontend/src/features/account/LoginStyled.tsx
  source/frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  source/frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
Labels: enhancement, 5.6

#4329 5.6 merge from dev
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-logging.yml
  .github/workflows/app-react.yml
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/ci-cd-pims-master.yml
  .github/workflows/credentials-comment-pr.yml
  .github/workflows/credentials-scan.yml
  .github/workflows/db-schma.yml
  .github/workflows/deploy-prod-end.yml
  .github/workflows/deploy-prod-start.yml
  .github/workflows/image-scan-analysis.yml
  .github/workflows/integration-test.yml
  .github/workflows/keycloak-sync.yml
  .github/workflows/mayan-sync.yml
  .github/workflows/release.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
  .github/workflows/tag.yml
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_pre_release_hotfix.yml
  .github/workflows/version.yml
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/CompReqFinancialService.cs
  source/backend/api/Services/ILeaseService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/public/tenants/tenant.json
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/features/account/Login.test.tsx
  source/frontend/src/features/account/Login.tsx
  source/frontend/src/features/account/LoginLoading.tsx
  source/frontend/src/features/account/LoginStyled.tsx
  source/frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  source/frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/ConsultationEditForm.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/models.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/MOTI.ts
Labels: release-management

#4331 Bump version for Release 5.6
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: release-management, 5.6

#4325 Psp 8933 move coordinates to align with other fields
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
Labels: ui/ux, 5.6

#4315 Psp 9140 add support for mayan builds within pims build infrastructure.
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/deploy-prod-start.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
  openshift/4.0/templates/mayan-bcgov/build.yaml
  openshift/4.0/templates/mayan-bcgov/imagestream.yaml
Labels: enhancement, 5.6

#4332 Merge 5.6 features into DEV
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/deploy-prod-start.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
  openshift/4.0/templates/mayan-bcgov/build.yaml
  openshift/4.0/templates/mayan-bcgov/imagestream.yaml
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/Table/Table.scss
  source/frontend/src/components/Table/Table.test.tsx
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationResults.tsx
  source/frontend/src/features/mapSideBar/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/list/columns.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/mocks/msw/handlers.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_MINIMAL_VW/featuretype.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_MINIMAL_VW/layer.xml
Labels: release-management

#4333 correct issue with ci/cd - temporary fix - needs update to rollout de…
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/deploy-prod-start.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
Labels: bug, devops

#4334 Psp 6333 - run keycloak sync in openshift
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/deploy-prod-start.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_pre_release_hotfix.yml
  openshift/4.0/templates/jobs/keycloak-sync-pipeline-run.yaml
  openshift/4.0/templates/jobs/keycloak-sync-pipeline.yaml
  openshift/4.0/templates/jobs/keycloak-sync-pvc.yaml
  openshift/4.0/templates/jobs/keycloak-sync-task.yaml
Labels: devops

#4296 re-enable codecov, and sonarqube on the frontend.
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/codecov-comment-pr.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_pre_release_hotfix.yml
Labels: tech-debt, devops

#4339 Update deprecated dependencies to fix CI/CD
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
Labels: devops

#4343 correct sonar build, use vars for non-secret values.
  .github/workflows/app-react.yml
Labels: devops

#4341 scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsConsultationOutcomeType.cs
  source/backend/entities/ef/PimsLeaseConsultation.cs
  source/backend/entities/ef/PimsLeaseConsultationHist.cs
  source/backend/entities/ef/PimsPropertyBoundaryLiteVw.cs
  source/backend/entities/ef/PimsPropertyLocationLiteVw.cs
  source/backend/entities/ef/PimsResearchFileNote.cs
Labels: db-scaffold

#4344 Just expose the sonarqube variables as plaintext, as they are not sec…
  .github/workflows/app-react.yml
Labels: devops

#4338 PSP-8320 Update Lease button location
  source/frontend/src/components/common/SimpleSectionHeader.test.tsx
  source/frontend/src/components/common/SimpleSectionHeader.tsx
  source/frontend/src/components/common/UserNameTooltip.test.tsx
  source/frontend/src/components/common/__snapshots__/SimpleSectionHeader.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsView.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/LeaseDetailsView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/PeriodPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/PaymentPeriodsView.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/PaymentPeriodsView.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/periodColumns.tsx
Labels: enhancement

#4335 psp-9033 ensure legal description is populated correctly from FA parc…
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.tsx
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: enhancement

#4346 PSP-9153 Copy access request notes to the user's notes on approval
  source/backend/dal.keycloak/PimsKeycloakService.cs
  source/backend/dal/Repositories/AccessRequestRepository.cs
  source/backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
Labels: enhancement

#4347 Update view name for local geoserver
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_LITE_VW/featuretype.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_LITE_VW/layer.xml
Labels: bug

#4313 psp-8120 update project config to use bcgov mayan repo to build mayan…
  tools/mayan-edms/.mayan-env
  tools/mayan-edms/docker-compose.yml
Labels: enhancement, tech-debt

#4340 PSP-9119: UI UX Clean Up - Bomb and Toasts relocation
  source/frontend/src/App.tsx
  source/frontend/src/assets/scss/_variables.scss
  source/frontend/src/components/layout/Footer/EmptyFooter.tsx
  source/frontend/src/components/layout/Footer/Footer.test.tsx
  source/frontend/src/components/layout/Footer/Footer.tsx
  source/frontend/src/components/layout/Footer/FooterStyled.tsx
  source/frontend/src/components/layout/Footer/__snapshots__/Footer.test.tsx.snap
  source/frontend/src/components/layout/Header/Header.tsx
  source/frontend/src/components/layout/Header/HeaderStyled.tsx
  source/frontend/src/components/layout/Header/__snapshots__/EmptyHeader.test.tsx.snap
  source/frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
  source/frontend/src/layouts/EmptyLayout.tsx
Labels: enhancement, 5.6

#4350 keycloak-sync correction.
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_pre_release_hotfix.yml
Labels: devops

#4351 PSP-9151 : Expand notes tab to improve readability
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/project/ProjectContainer.tsx
  source/frontend/src/features/mapSideBar/research/tabs/ResearchTabsContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/tabs/ResearchTabsContainer.tsx
Labels: enhancement

#4345 psp-9148 Add consultation outcomes and business logic.
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/apimodels/CodeTypes/ConsultationOutcomeTypes.cs
  source/backend/apimodels/Models/Concepts/Lease/ConsultationLeaseMap.cs
  source/backend/apimodels/Models/Concepts/Lease/ConsultationLeaseModel.cs
  source/backend/dal/Repositories/ConsultationRepository.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/entities/Partials/ConsultationOutcomeTypeCode.cs
  source/backend/tests/core/Entities/LeaseConsultationHelper.cs
  source/backend/tests/unit/api/Controllers/Leases/ConsultationControllerTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/dal/Repositories/ConsultationRepositoryTest.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderForm.test.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/ConsultationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/ConsultationListContainer.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/ConsultationListView.test.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/ConsultationListView.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/__snapshots__/ConsultationListContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/__snapshots__/ConsultationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/ConsultationAddContainer.test.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/ConsultationEditForm.test.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/ConsultationEditForm.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/ConsultationUpdateContainer.test.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/ConsultationUpdateContainer.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/EditConsultationYupSchema.ts
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/__snapshots__/ConsultationAddContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/__snapshots__/ConsultationEditForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/__snapshots__/ConsultationUpdateContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/models.ts
  source/frontend/src/mocks/consultations.mock.ts
  source/frontend/src/mocks/lookups.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_ConsultationOutcomeTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_ConsultationLease.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_LeaseStakeholderType.ts
Labels: bug

#4356 PSP-9152 : Expand documents tab to improve readability
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/project/ProjectContainer.tsx
  source/frontend/src/features/mapSideBar/research/tabs/ResearchTabsContainer.tsx
Labels: enhancement

#4348 psp-8335 | Pims properties boundary highlayer
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersMenu.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/LayersControl/data.ts
  source/frontend/src/components/maps/leaflet/Control/LayersControl/wmsHeaders.ts
  source/frontend/src/components/maps/leaflet/Layers/LeafletLayerListener.tsx
  source/frontend/src/components/maps/leaflet/Layers/useConfiguredMapLayers.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_BOUNDARY_VW/layer.xml
  tools/geoserver/geoserver_data/psp/styles/pims_custom.sld
  tools/geoserver/geoserver_data/psp/styles/pims_custom.xml
Labels: enhancement

#4352 PSP-8442 : UI UX Clean Up - arrow down - size and position
  source/frontend/src/components/common/Section/SectionStyles.tsx
  source/frontend/src/components/common/form/YesNoSelect.tsx
  source/frontend/src/features/admin/document-template/DocumentTemplateManagementView.tsx
  source/frontend/src/features/admin/document-template/__snapshots__/DocumentTemplateManagementContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/FeeDeterminationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/__snapshots__/DepositNotes.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailFeeDetermination.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/documents/__snapshots__/DocumentsPage.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/__snapshots__/EditInsuranceContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/__snapshots__/StakeHolderView.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/__snapshots__/OffersAndSaleView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/__snapshots__/DispositionSaleForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/__snapshots__/UpdateDispositionSaleView.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/__snapshots__/ConsultationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/__snapshots__/ConsultationEditForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/__snapshots__/ProjectSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/OperationSectionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/__snapshots__/OperationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/__snapshots__/PropertyContactListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/__snapshots__/PropertyManagementDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/__snapshots__/PropertyManagementUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/__snapshots__/TakesDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakeUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/tabs/checklist/detail/__snapshots__/ChecklistView.test.tsx.snap
  source/frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
Labels: enhancement

#4358 ensure that isPims* functions work with new layers
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
Labels: bug

#4359 Local fixes for geoserver boundary layer
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_BOUNDARY_VW/layer.xml
Labels: devops

#4357 Document sync update to allow of re-enabling doc types
  source/backend/api/Services/DocumentSyncService.cs
  source/backend/tests/unit/api/Services/DocumentSyncServiceTest.cs
Labels: bug

#4361 PSP-9237 Force submitting flag to be true in the case of user override.
  source/frontend/src/features/mapSideBar/project/hooks/useAddProjectFormManagement.tsx
Labels: bug

#4362 Bump dev version - IS90
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4364 correct STsrid in sql statement.
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION.dtproj
  etl/PIMS_PROPERTY_SPATIAL_CORRECTION/PIMS_PROPERTY_SPATIAL_CORRECTION/SPATIAL_CORRECTION.dtsx
Labels: bug, etl

#4365 GHA corrections
  .github/workflows/codecov-comment-pr.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
Labels: devops
