Repository bcgov/PSP, pull requests merged in 2024-10, with the labels that each got.

#4367 PSP-9181: Automation Test cases - Lease update
  testing/PIMS.Tests.Automation/Classes/Lease.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseConsultations.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasesChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedPagination.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
Labels: test-scripts

#4366 PSP-9214 - L/L Update payment details export to include payment notes
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Models/Report/LeasePaymentReportMap.cs
  source/backend/api/Models/Report/LeasePaymentReportModel.cs
  source/frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.test.tsx
  source/frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.tsx
  source/frontend/src/features/leases/reports/aggregated/__snapshots__/ExportAggregatedLeasesContainer.test.tsx.snap
  source/frontend/src/features/leases/reports/payments/ExportLeasePaymentsContainer.test.tsx
  source/frontend/src/features/leases/reports/payments/ExportLeasePaymentsContainer.tsx
  source/frontend/src/features/leases/reports/payments/__snapshots__/ExportLeasePaymentsContainer.test.tsx.snap
Labels: enhancement

#4368 psp-9173 fixes to lease payments, project comp req, and lease exports…
  source/backend/api/Pims.Api.csproj
  source/backend/dal/Repositories/LeasePaymentRepository.cs
  source/frontend/package.json
Labels: bug, hotfix

#4374 PSP-6599 | Master script shell integration
  Makefile
  source/database/mssql/scripts/dbscripts/MSSQL_Script_Footer.txt
  source/database/mssql/scripts/dbscripts/MSSQL_Script_Header.txt
  source/database/mssql/scripts/dbscripts/callmaster.sh
  source/database/mssql/scripts/dbscripts/deploy-transaction.sh
  source/database/mssql/scripts/dbscripts/deploy.sh
  source/database/mssql/scripts/dbscripts/generate_master_sql.sh
  source/database/mssql/scripts/dbscripts/master_script_static/MSSQL_Script_Footer.txt
  source/database/mssql/scripts/dbscripts/master_script_static/MSSQL_Script_Header.txt
  source/database/mssql/scripts/dbscripts/run_sql_scripts.sh
Labels: tech-debt

#4377 PSP-9292 : FT: Approval / Consultations: Count is displayed on the se…
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/ConsultationListView.test.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/ConsultationListView.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/__snapshots__/ConsultationListView.test.tsx.snap
Labels: bug

#4375 PSP-9131 : Display boundary for property not in PIMS
  source/frontend/src/components/maps/MapLeafletView.tsx
Labels: enhancement

#4379 PSP-9308 : Drop-down menu underlined
  source/frontend/src/assets/scss/App.scss
Labels: bug

#4371 psp-8420 allow, and display a warning when choosing a payment date outside of pa…
  source/backend/api/Services/LeasePaymentService.cs
  source/backend/tests/unit/api/Services/PaymentServiceTest.cs
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentFormContent.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/__snapshots__/PeriodForm.test.tsx.snap
Labels: enhancement

#4378 PSP-9207 L/L H120 details - need to be added to Compensation Requisition Export
  source/backend/api/Areas/Reports/Controllers/AcquisitionController.cs
  source/backend/api/Areas/Reports/Models/Acquisition/CompensationFinancialReportModel.cs
  source/backend/api/Areas/Reports/Models/Acquisition/CompensationFinancialReportTotalsModel.cs
  source/backend/api/Services/CompReqFinancialService.cs
  source/backend/dal/Repositories/CompReqFinancialRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompReqFinancialRepository.cs
  source/backend/tests/unit/api/Models/CompensationFinancialReportModelTest.cs
  source/backend/tests/unit/api/Services/CompReqFinancialServiceTest.cs
  source/backend/tests/unit/dal/Repositories/CompReqFinancialRepositoryTest.cs
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/ConsultationListView.test.tsx
  source/frontend/src/features/projects/reports/ProjectExportContainer.tsx
Labels: enhancement

#4381 PSP-8561, PSP-8968: UI/UX Clean - Submenus and Icons.
  source/frontend/src/assets/images/icon-lot.svg
  source/frontend/src/components/layout/SideNavBar/AcquisitionTray.tsx
  source/frontend/src/components/layout/SideNavBar/AdminTools.tsx
  source/frontend/src/components/layout/SideNavBar/ContactTray.tsx
  source/frontend/src/components/layout/SideNavBar/DispositionTray.tsx
  source/frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  source/frontend/src/components/layout/SideNavBar/ProjectTray.tsx
  source/frontend/src/components/layout/SideNavBar/ResearchTray.tsx
  source/frontend/src/components/layout/SideNavBar/SideTray.tsx
  source/frontend/src/components/layout/SideNavBar/SubdCons.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/AcquisitionTray.test.tsx.snap
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/components/layout/SideNavBar/styles.ts
  source/frontend/src/features/contacts/contact/create/CreateContactContainer.tsx
  source/frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/detail/Container.tsx
  source/frontend/src/features/contacts/contact/detail/__snapshots__/Container.test.tsx.snap
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/LeaseDetailsView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/DispositionView.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainerView.tsx
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/ProjectContainerView.tsx
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.tsx
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/ResearchView.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
  source/frontend/src/features/projects/reports/ProjectExportForm.tsx
  source/frontend/src/features/projects/reports/__snapshots__/ProjectExportForm.test.tsx.snap
Labels: enhancement, 5.6

#4382 PSP-9181: Leases Consultations and Compensation automated test cases
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Classes/Lease.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/CDOGSTemplates.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionOfferSale.cs
  testing/PIMS.Tests.Automation/PageObjects/HelpDesk.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseConsultations.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePeriodPayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedPagination.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
Labels: test-scripts

#4383 PSP-7786 Parcel Boundary - SRW delineation
  source/frontend/src/components/maps/leaflet/Control/LayersControl/data.ts
Labels: enhancement

#4384 add checkout step to codecov action to ensure action has necessary co…
  .github/workflows/codecov-comment-pr.yml
  codecov.yml
Labels: devops

#4385 PSP-9181: Additional corrections to lease compensation and consultation to automated test cases.
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/PageObjects/LeaseConsultations.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
Labels: test-scripts

#4380 PSP-9238 UI/UX : The green hyperlink button is not aligned for Invoices Total section in the management tab
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/InvoiceListForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/InvoiceTotalsForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/InvoiceTotalsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/__snapshots__/InvoiceTotalsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/models.ts
  source/frontend/src/mocks/PropertyManagementActivity.mock.ts
  source/frontend/src/mocks/propertyActivityInvoice.mock.ts
Labels: bug

#4388 Psp 9316 - hotfix for prod document issues introduced by streaming.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/features/documents/DocumentPreviewContainer.tsx
  source/frontend/src/features/documents/DownloadDocumentButton.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  source/frontend/src/hooks/pims-api/useApiDocuments.ts
Labels: bug, hotfix, 5.5

#4389 Bump DEV version - IS91
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4392 Devops updates
  .github/workflows/deploy-prod-start.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
Labels: devops

#4390 Add missing environment variables expected by mayan 4.7.2
  tools/mayan-edms/.mayan-env
Labels: enhancement

#4387 PSP-9296: Relocating edit button to the header on Property Information Management and Acquisition Files Stakeholders
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/__snapshots__/StakeHolderView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/__snapshots__/PropertyManagementDetailView.test.tsx.snap
Labels: bug, 5.6

#4391 PSP-9344 : FT: Map Features - When a search is done for a property th…
  source/frontend/src/components/maps/MapLeafletView.tsx
Labels: bug

#4393 PSP-9319 UI UX Clean Up - Replacing PIMS Resources with PIMS Training…
  source/frontend/src/features/help/containers/HelpContainer.test.tsx
  source/frontend/src/features/help/containers/HelpContainer.tsx
Labels: enhancement

#4395 PSP-9268 Sub-files tab skeleton view and container
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListView.tsx
  source/frontend/src/features/mapSideBar/shared/detail/FileTabs.tsx
Labels: enhancement

#4396 PSP-6599 | Updated scripts to work in actions
  Makefile
  source/database/mssql/scripts/dbscripts/db-deploy-transaction.sh
  source/database/mssql/scripts/dbscripts/db-deploy.sh
  source/database/mssql/scripts/dbscripts/db-upgrade.sh
  source/database/mssql/scripts/dbscripts/deploy-transaction.sh
  source/database/mssql/scripts/dbscripts/deploy.sh
  source/database/mssql/scripts/dbscripts/generate_master_sql.sh
  source/database/mssql/scripts/dbscripts/master_script_static/MSSQL_Script_Footer.txt
  source/database/mssql/scripts/dbscripts/master_script_static/MSSQL_Script_Header.txt
  source/database/mssql/scripts/dbscripts/upgrade.sh
Labels: tech-debt, devops

#4398 Template fix
  openshift/4.0/templates/jobs/db-deploy.yaml
Labels: tech-debt

#4399 Template permission fix
  openshift/4.0/templates/jobs/db-deploy.yaml
Labels: tech-debt

#4400 IS91 scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcquisitionFile.cs
  source/backend/entities/ef/PimsAcquisitionFileHist.cs
  source/backend/entities/ef/PimsDocumentTyp.cs
  source/backend/entities/ef/PimsDocumentTypHist.cs
  source/backend/entities/ef/PimsPropertyActivity.cs
  source/backend/entities/ef/PimsPropertyActivityHist.cs
Labels: db-scaffold

#4402 PSP-9268 Model updates to support sub-files
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_AcquisitionFile.ts
  source/frontend/src/models/defaultInitializers.ts
Labels: enhancement

#4401 PSP-9350: FT: Projects - Export Project and Team member options are misaligned
  source/frontend/src/features/projects/reports/ProjectExportForm.tsx
  source/frontend/src/features/projects/reports/ProjectExportFormContent.tsx
  source/frontend/src/features/projects/reports/__snapshots__/ProjectExportForm.test.tsx.snap
Labels: bug, 5.6

#4403 PSP-9328 : Update document type
  source/backend/api/Areas/Documents/DocumentController.cs
  source/backend/api/Repositories/Mayan/IEdmsDocumentRepository.cs
  source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/apimodels/Models/Requests/Document/UpdateMetadata/DocumentUpdateRequest.cs
  source/backend/dal/Repositories/DocumentTypeRepository.cs
  source/backend/dal/Repositories/Interfaces/IDocumentTypeRepository.cs
  source/backend/tests/unit/api/Controllers/Document/DocumentControllerTest.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  source/frontend/src/features/documents/ComposedDocument.ts
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailHeader.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
  source/frontend/src/features/documents/documentDetail/DocumentUpdateFormDataYupSchema.tsx
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailForm.test.tsx.snap
  source/frontend/src/features/documents/documentDetail/__snapshots__/DocumentDetailView.test.tsx.snap
  source/frontend/src/features/documents/documentUpload/DocumentUploadContainer.tsx
  source/frontend/src/features/documents/hooks/useDocumentProvider.ts
  source/frontend/src/hooks/pims-api/useApiDocuments.ts
  source/frontend/src/mocks/documents.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Requests_DocumentUpdateRequest.ts
Labels: enhancement

#4406 PSP-9276 : Show file linkage - Inside the file
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/IAcquisitionFileService.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFileRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/__snapshots__/SubFileListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/table/SubFilesResultsTable.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/table/colums.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/hooks/pims-api/useApiAcquisitionFile.ts
  source/frontend/src/hooks/repositories/useAcquisitionProvider.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_AcquisitionFile.ts
  source/frontend/src/models/defaultInitializers.ts
Labels: enhancement

#4411 PSP-9381: Correct tool tip for acquisition takes - Completed date
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
Labels: bug, 5.6

#4409 Psp 9347 PSP-9353 - zoom functionality not working after displaying search results.
  source/frontend/src/components/maps/MapLeafletView.tsx
Labels: bug

#4407 PSP-9312 | Document type purpose / definition
  source/backend/api/Services/DocumentSyncService.cs
  source/backend/apimodels/Models/Concepts/Document/DocumentTypeMap.cs
  source/backend/apimodels/Models/Concepts/Document/DocumentTypeModel.cs
  source/backend/apimodels/Models/PimsSync/DocumentTypeModel.cs
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.test.tsx
  source/frontend/src/features/documents/documentUpload/SelectedDocumentHeader.tsx
  source/frontend/src/mocks/documents.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_DocumentType.ts
  tools/mayan_sync_helper/.gitignore
  tools/mayan_sync_helper/json_output/mayan_sync.json
  tools/mayan_sync_helper/mayan_sync_transformer.py
  tools/mayan_sync_helper/xml_definitions/doc_metadata.xlsx
  tools/mayan_sync_helper/xml_definitions/doctype_definitions.xlsx
  tools/mayan_sync_helper/xml_definitions/metadata_definitions.xlsx
Labels: enhancement

#4410 psp-9301 change to manual handling of setSubmitting function.
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/AddLeaseForm.tsx
Labels: bug

#4394 psp-8905 | Contact summary model standarization
  source/backend/api/Areas/Contacts/Controllers/SearchController.cs
  source/backend/apimodels/Models/Concepts/Contact/ContactMap.cs
  source/backend/apimodels/Models/Concepts/Contact/ContactSummaryModel.cs
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.test.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/ContactResultComponent.test.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/ContactResultComponent.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/summaryColumns.tsx
  source/frontend/src/features/contacts/list/ContactListView.test.tsx
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/models.ts
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm1.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm5.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm9.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/models.test.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/models.ts
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/ConsultationEditForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/models.test.ts
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/UpdateSummaryForm.tsx
  source/frontend/src/hooks/pims-api/useApiContacts.ts
  source/frontend/src/interfaces/IContactSearchResult.ts
  source/frontend/src/mocks/contacts.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_ContactSummary.ts
Labels: enhancement, tech-debt

#4415 PSP-9415 : FT-REG: Lease & Licences - 500 error thrown when user atte…
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Repositories/Interfaces/IPropertyLeaseRepository.cs
  source/backend/dal/Repositories/PropertyLeaseRepository.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
Labels: bug

#4416 psp-9235 | Contact Navigation check
  source/frontend/src/features/contacts/contact/create/ContactRouter.tsx
  source/frontend/src/features/contacts/contact/create/CreateContactContainer.tsx
  source/frontend/src/features/contacts/contact/create/Organization/CreateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/Person/CreatePersonForm.tsx
  source/frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.tsx
  source/frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
Labels: bug

#4418 Version bump IS92
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/ContactResultComponent.test.tsx
  source/frontend/src/features/contacts/list/ContactListView.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.test.tsx
Labels: devops, release-management

#4413 PSP-9268 Add sub-interest files to a main file
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/dal/Exceptions/OverrideExceptions.cs
  source/backend/dal/Helpers/Extensions/AcquisitionFileExtensions.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionRepositoryTest.cs
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/models.test.ts
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/SubFileListView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/subFiles/__snapshots__/SubFileListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/models/api/UserOverrideCode.ts
Labels: enhancement

#4414 PSP-9351 UI/UX: The close button at the top right side of the sub-menu should be integrated within the header
  source/frontend/src/components/common/styles.ts
  source/frontend/src/components/layout/SideNavBar/AcquisitionTray.test.tsx
  source/frontend/src/components/layout/SideNavBar/AcquisitionTray.tsx
  source/frontend/src/components/layout/SideNavBar/AdminTools.tsx
  source/frontend/src/components/layout/SideNavBar/ContactTray.tsx
  source/frontend/src/components/layout/SideNavBar/DispositionTray.tsx
  source/frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  source/frontend/src/components/layout/SideNavBar/ProjectTray.tsx
  source/frontend/src/components/layout/SideNavBar/ResearchTray.tsx
  source/frontend/src/components/layout/SideNavBar/SideTray.tsx
  source/frontend/src/components/layout/SideNavBar/SideTrayLayout.tsx
  source/frontend/src/components/layout/SideNavBar/SubdCons.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/AcquisitionTray.test.tsx.snap
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/components/layout/SideNavBar/styles.ts
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  source/frontend/src/features/mapSideBar/layout/__snapshots__/MapSideBarLayout.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: bug

#4419 PSP-9411 : FT-REG: Lease & Licences: Header still displays "Tenant" w…
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.test.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/detail/LeaseTabsContainer.tsx
Labels: bug

#4420 Fixed repository not updating doc purpose
  source/backend/dal/Repositories/DocumentTypeRepository.cs
Labels: enhancement

#4412 psp-9186 prevent merging of pims and parcel map data - use pims if ex…
  source/frontend/src/components/propertySelector/MapSelectorContainer.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/mocks/researchFile.mock.ts
  source/frontend/src/utils/mapPropertyUtils.test.tsx
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: bug

#4425 PSP-9449: Automation Test Set changes IS92
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/HelpDesk.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseConsultations.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionConsolidationProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
Labels: test-scripts

#4424 PSP-9437 Fix faulty logic when closing property info panel
  source/frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
Labels: bug, 5.6

#4428 PSP-9252 Add date fields to acquisition file (major projects)
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/models.test.ts
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_AcquisitionFile.ts
  source/frontend/src/models/defaultInitializers.ts
  source/frontend/src/utils/test-utils.tsx
Labels: enhancement, 5.6
