Repository bcgov/PSP, pull requests merged in 2024-12, with the labels that each got.

#4512 PSP-9593 Fix map fit to bounds error on load
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
Labels: bug, 5.7

#4514 updated PAT document etl
  etl/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT/DOCUMENT_IMPORT.dtsx
  etl/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT/PAT_PIMS_DOCUMENT_IMPORT.dtproj
Labels: etl

#4515 PSP-9598 App error when a property is searched using PIN, Plan # or Historical File
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
Labels: bug, 5.7

#4513 Fix keycloak-sync call in GitHub actions
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/deploy-prod-start-argo.yml
Labels: bug, devops

#4516 PSP-9565: Changes on automation test set to accomodate GHA
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
Labels: test-scripts

#4518 Bump version to IS95
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4519 PSP-9569 : H 120 document- Generated document shows full names, inste…
  source/frontend/src/features/mapSideBar/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/models/generate/GenerateProject.ts
  source/frontend/src/models/generate/acquisition/GenerateAcquisitionFile.test.ts
Labels: enhancement

#4520 Github action fixes
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/retag-test-to-uat-argo.yml
Labels: bug, devops

#4521 PSP-9433: Lease Historical file alignment fix
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
Labels: enhancement, 5.7

#4522 PSP-9517 Remove "cannot determine" region dropdown from User Management screen under Admin Tools
  source/frontend/src/features/admin/users/ManageUsersPage.test.tsx
  source/frontend/src/features/admin/users/__snapshots__/ManageUsersPage.test.tsx.snap
  source/frontend/src/features/admin/users/components/UsersFilterBar.tsx
Labels: enhancement, 5.7

#4523 PSP-9431: Property Information Pane: Information tooltip in Railway belt/ Dominion patent field
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
Labels: enhancement, 5.7

#4525 IS 95 scaffold
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcquisitionFile.cs
  source/backend/entities/ef/PimsAcquisitionFileHist.cs
  source/backend/entities/ef/PimsCompensationRequisition.cs
  source/backend/entities/ef/PimsCompensationRequisitionHist.cs
  source/backend/entities/ef/PimsExpropriationPayment.cs
  source/backend/entities/ef/PimsExpropriationPaymentHist.cs
  source/backend/tests/core/Entities/AcquisitionFileHelper.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
Labels: db-scaffold

#4524 PSP-9283 : UI UX Clean Up - Acquisition - Stakeholders - edit button
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionMenu.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/StakeHolderView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/__snapshots__/StakeHolderView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchMenu.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchMenu.test.tsx.snap
Labels: enhancement

#4526 PSP-8923: UI UX Clean Up - Left Side Menu - Clicked icon stage
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/components/layout/SideNavBar/NavIcon.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/components/layout/SideNavBar/styles.ts
Labels: enhancement, 5.7

#4527 SetOriginalConcurrencyControlNumber function removal
  source/backend/dal/Helpers/Extensions/DbContextExtensions.cs
  source/backend/dal/Repositories/UserRepository.cs
Labels: bug

#4528 PSP-9279 UI UX - Acquisition - Agreements & Expropriation - UI Button update for consistency
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsView.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/LeaseDetailsView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/GenerateFormView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/__snapshots__/ExpropriationForm1.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/ExpropriationForm5.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/ExpropriationForm5.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/__snapshots__/ExpropriationForm5.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/ExpropriationForm8Details.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/__snapshots__/ExpropriationForm8Details.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/__snapshots__/ExpropriationForm9.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
Labels: enhancement, 5.7

#4533 psp-9632 limit the default bounds when resetting.
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
Labels: bug

#4530 psp-9715 fix issues adding properties with no locations, and also ove…
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Repositories/ResearchFilePropertyRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
Labels: bug

#4537 [CI] Fix build failures after ubuntu-latest upgrade to 24.04
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-logging.yml
  .github/workflows/app-react.yml
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/codecov-comment-pr.yml
  .github/workflows/credentials-comment-pr.yml
  .github/workflows/credentials-scan.yml
  .github/workflows/db-schma.yml
  .github/workflows/deploy-prod-end.yml
  .github/workflows/deploy-prod-start-argo.yml
  .github/workflows/deploy-prod-start.yml
  .github/workflows/image-scan-analysis.yml
  .github/workflows/integration-test.yml
  .github/workflows/keycloak-sync.yml
  .github/workflows/mayan-sync.yml
  .github/workflows/release.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat-argo.yml
  .github/workflows/retag-test-to-uat.yml
  .github/workflows/tag.yml
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_hotfix_argo.yml
  .github/workflows/uat_pre_release_hotfix.yml
  .github/workflows/uat_pre_release_hotfix_argo.yml
  .github/workflows/version.yml
  .github/workflows/zap-scan.yml
Labels: devops

#4532 psp-9457 leases allow disposed properties to be added.
  source/backend/api/Services/LeaseService.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/SelectedPropertyRow.tsx
  source/frontend/src/features/mapSideBar/shared/models.ts
Labels: bug

#4536 disposition override corrections - ensure save redirect functions.
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx
Labels: bug

#4534 psp-9530 allow research files to add retired properties.
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/api/Services/PropertyServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
Labels: bug

#4531 PSP-8573 | Updated list headers
  source/frontend/src/features/acquisition/list/AcquisitionListView.tsx
  source/frontend/src/features/admin/access/ManageAccessRequestsPage.tsx
  source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  source/frontend/src/features/admin/document-template/DocumentTemplateManagementView.tsx
  source/frontend/src/features/admin/document-template/__snapshots__/DocumentTemplateManagementContainer.test.tsx.snap
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeListView.tsx
  source/frontend/src/features/admin/users/ManageUsersPage.tsx
  source/frontend/src/features/admin/users/__snapshots__/ManageUsersPage.test.tsx.snap
  source/frontend/src/features/contacts/list/ContactListPage.tsx
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/disposition/list/DispositionListView.tsx
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseListView.tsx
  source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/projects/list/ProjectListView.tsx
  source/frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
  source/frontend/src/features/research/list/ResearchListView.tsx
  source/frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
Labels: enhancement

#4540 PSP-9655 : FT-REG: When creating a new file approximately after 4pm P…
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
Labels: bug

#4543 Bump version 96
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
Labels: devops, release-management

#4548 PSP-9740 HOTFIX: User is not able to update the Acquisition Files
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
Labels: bug, hotfix, 5.7

#4546 PSP-9211 and PSP-9719: UI/UX Clean up: Map Icons Replacement and PIMS File header colors
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/AssociationHeader.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/__snapshots__/AssociationHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
  source/frontend/src/features/properties/filter/PropertySearchToggle.tsx
  source/frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
Labels: enhancement, 5.7

#4551 Backmerge test into dev
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
Labels: alignment

#4545 Add alter ups to change the name of the PIMS_ROLEs for lease/license
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/011_DML_PIMS_ROLE_NAME.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/164_DML_PIMS_ROLE_NAME.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/051_DML_PIMS_ROLE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S96_00/Alter Down/011_DML_PIMS_ROLE_NAME.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S96_00/Alter Down/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S96_00/Alter Up/164_DML_PIMS_ROLE_NAME.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S96_00/Alter Up/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S96_00/Build/051_DML_PIMS_ROLE.sql
Labels: bug

#4549 PSP-9743 Generate green button in the Expropriation tab for Form 1,5 and 9 are displaying incorrect colour
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/__snapshots__/ExpropriationForm1.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/ExpropriationForm5.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/__snapshots__/ExpropriationForm5.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/__snapshots__/ExpropriationForm9.test.tsx.snap
Labels: bug

#4539 PSP-9570 Property Information leaflet should open up when a property is part of the PIMS Inventory regardless if it has a PID or not
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/constants/API.ts
  source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/hooks/repositories/useComposedProperties.ts
  source/frontend/src/hooks/repositories/useMapProperties.tsx
  source/frontend/src/utils/propertyUtils.ts
Labels: enhancement, 5.7

#4557 correct error when filtering by file #.
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
Labels: bug

#4556 remove retired check from research files.
  source/frontend/src/features/mapSideBar/research/add/AddResearchFileYupSchema.ts
Labels: bug

#4558 PSP-9572 : Acquisition- Aggregating and Displaying Final H-120 CompeNsation Requisition Totals for Linked Files
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListView.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationResults.tsx
  source/frontend/src/features/mapSideBar/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
Labels: enhancement

#4555 psp-9256 allow users added to a project to view an acquisition file.
  source/backend/api/Helpers/Extensions/AcquisitionFileExtensions.cs
  source/backend/api/Helpers/Extensions/PrincipalExtensions.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/apimodels/Models/Concepts/Project/ProjectMap.cs
  source/backend/apimodels/Models/Concepts/Project/ProjectModel.cs
  source/backend/apimodels/Models/Concepts/Project/ProjectPersonMap.cs
  source/backend/apimodels/Models/Concepts/Project/ProjectPersonModel.cs
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/backend/entities/Partials/ProjectPerson.cs
  source/frontend/src/components/common/form/ContactInput/ContactInputContainer.tsx
  source/frontend/src/components/common/form/ContactInput/ContactInputView.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectForm.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectTeamSubForm.tsx
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/models.ts
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/ProjectSummaryView.tsx
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/__snapshots__/ProjectSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/LeaseAssociationContent.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/mocks/dispositionFiles.mock.ts
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/mocks/projects.mock.ts
  source/frontend/src/mocks/researchFile.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Project.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_ProjectPerson.ts
Labels: enhancement

#4559 Address race condition where: (see comment)
  source/backend/api/Services/DocumentQueueService.cs
  source/backend/dal/Repositories/DocumentQueueRepository.cs
  source/backend/tests/unit/api/Services/DocumentQueueServiceTest.cs
Labels: bug, 5.7

#4552 PSP-9471: UI UX Clean Up - Contact – Manage Contacts: Allow to save contacts that are set as Inactive without Contact Methods
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.test.tsx
  source/frontend/src/features/contacts/contact/edit/Person/UpdatePersonForm.tsx
  source/frontend/src/features/contacts/contact/utils/contactUtils.ts
  source/frontend/src/features/contacts/formModels.ts
Labels: enhancement, 5.7

#4561 Psp 9763 - infinite render loop
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListView.test.tsx
  source/frontend/src/hooks/useKeycloakWrapper.tsx
Labels: bug

#4562 Psp 9512 - corrections/enhancements
  source/backend/api/Services/DocumentQueueService.cs
  source/backend/dal/PIMSContextFactory.cs
  source/backend/dal/Repositories/DocumentQueueRepository.cs
  source/backend/dal/Repositories/Interfaces/IDocumentQueueRepository.cs
  source/backend/entities/Models/DocumentQueueSearchResult.cs
  source/backend/scheduler/appsettings.json
  source/backend/tests/unit/api/Services/DocumentQueueServiceTest.cs
Labels: bug

#4563 PSP-9760 : FT:Projects: User is not able to update any of the project…
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/backend/dal/Repositories/ProjectRepository.cs
  source/frontend/src/features/mapSideBar/project/models.ts
Labels: bug, 5.7
