Repository bcgov/PSP, pull requests merged in 2024-05, with the labels that each got.

#3979 PSP-8022 : Disposition file states - Hold
  source/backend/api/Constants/EnumDispositionFileStatusTypeCode.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Solvers/DispositionStatusSolver.cs
  source/backend/api/Solvers/IDispositionStatusSolver.cs
  source/backend/apimodels/CodeTypes/DispositionFileStatusTypes.cs
  source/backend/apimodels/CodeTypes/DispositionStatusTypes.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Solvers/DispositionStatusSolverTests.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/constants/dispositionFileStatus.ts
  source/frontend/src/features/account/Logout.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionStatusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.test.tsx
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_DispositionFileStatusTypes.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_DispositionStatusTypes.ts
Labels: 5.2

#3980 psp-7909 take ui refactor.
  source/backend/api/Areas/Takes/Controllers/TakeController.cs
  source/backend/api/Services/ITakeService.cs
  source/backend/api/Services/TakeService.cs
  source/backend/apimodels/CodeTypes/TakeTypes.cs
  source/backend/dal/Exceptions/OverrideExceptions.cs
  source/backend/dal/Repositories/Interfaces/ITakeRepository.cs
  source/backend/dal/Repositories/TakeRepository.cs
  source/backend/entities/Extensions/ExpiringTypeEntity.cs
  source/backend/tests/core/Entities/TakeHelper.cs
  source/backend/tests/unit/api/Controllers/Takes/TakeControllerTest.cs
  source/backend/tests/unit/api/Controllers/Takes/TakesControllerTest.cs
  source/backend/tests/unit/api/Services/TakeServiceTest.cs
  source/backend/tests/unit/dal/Repositories/TakeRepositoryTest.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/property/tabs/takes/add/TakesAddContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/add/TakesAddContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/__snapshots__/TakesDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/models.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/models.ts
  source/frontend/src/features/mapSideBar/property/tabs/takes/repositories/useTakesRepository.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeUpdateContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeUpdateContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeUpdateForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakesUpdateForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakeUpdateContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakeUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/router/FilePropertyRouter.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/hooks/pims-api/useApiTakes.ts
  source/frontend/src/models/api/UserOverrideCode.ts
Labels: enhancement, 5.2

#3982 unit test stability corrections
  .github/workflows/app-react.yml
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/public/mockServiceWorker.js
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.test.tsx
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.test.tsx
  source/frontend/src/mocks/msw/browser.ts
  source/frontend/src/mocks/msw/handlers.ts
  source/frontend/src/mocks/msw/server.ts
  source/frontend/src/setupTests.ts
Labels: tech-debt, unit-tests

#3984 psp-8252 remove unecessary cast from/to string
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
Labels: bug, 5.2

#3986 psp-8352 properly handle null/empty organization (based on error in test).
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/details/ResearchSummaryView.tsx
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/UpdateSummaryForm.tsx
  source/frontend/src/interfaces/IContactSearchResult.ts
Labels: bug, 5.2

#3985 PSP-8361: Automation updates based on IS79 build on Test Environment
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#3993 PSP-8124 Fix map zoom bug for draft markers
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
Labels: bug, 5.2

#3988 psp-7928 make document upload block - to reduce number of failed uplo…
  source/backend/api/Models/Configuration/MayanConfig.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/appsettings.json
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  tools/mayan-edms/docker-compose.yml
Labels: 5.2

#3994 psp-8353 add missing disposition message.
  source/frontend/src/features/mapSideBar/disposition/DispositionView.tsx
Labels: bug, 5.2

#3995 PSP-8186 : Property File Change Log Update
  source/backend/apimodels/CodeTypes/PropertyPPHStatusTypes.cs
  source/backend/dal/Pims.Dal.csproj
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/core/PrincipalHelper.cs
  source/backend/tests/unit/dal/Repositories/PropertyRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/UserRepositoryTest.cs
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_PropertyPPHStatusTypes.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_TakeTypes.ts
Labels: bug, 5.2

#3998 Added new view that does allows for properties without location data
  source/backend/apimodels/Models/Concepts/Property/PropertyViewMap.cs
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsPropertyVw.cs
  source/backend/tests/core/Entities/PropertyHelper.cs
  source/backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
  source/backend/tests/unit/api/Controllers/Reports/PropertyControllerTest.cs
Labels: bug, 5.2

#4000 psp-7861 Historical file numbers on Acquisition file and Research file
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/PropertyDetailsTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/ResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberSectionView.tsx
Labels: enhancement, 5.3

#4004 PSP - pre-release test feedback.
  source/frontend/src/assets/scss/App.scss
  source/frontend/src/features/documents/list/DocumentResults/DocumentResultsColumns.tsx
Labels: bug, 5.2

#4002 PSP-8241 | Updated take calculation to use incoming take if being updated
  source/backend/api/Services/TakeService.cs
Labels: bug, 5.2

#4007 5.3 test fixes
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.test.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.test.tsx
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.test.tsx
Labels: unit-tests

#4008 Bump DEV version to 5.3
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: release-management

#4011 PSP-8444: Update on Automated Takes
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
Labels: test-scripts

#4017 Scaffold for s80 and compilation fixes
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/apimodels/Models/Concepts/Property/HistoricalNumberMap.cs
  source/backend/dal/Repositories/HistoricNumberRepository.cs
  source/backend/dal/Repositories/Interfaces/IHistoricalNumberRepository.cs
  source/backend/entities/Partials/FileNumber.cs
  source/backend/entities/Partials/HistoricalFileNumber.cs
  source/backend/entities/Partials/HistoricalFileNumberType.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsDataSourceType.cs
  source/backend/entities/ef/PimsHistoricalFileNumber.cs
  source/backend/entities/ef/PimsHistoricalFileNumberHist.cs
  source/backend/entities/ef/PimsHistoricalFileNumberType.cs
  source/backend/entities/ef/PimsHistoricalFileNumberVw.cs
  source/backend/entities/ef/PimsInsurance.cs
  source/backend/entities/ef/PimsLease.cs
  source/backend/entities/ef/PimsLeaseHist.cs
  source/backend/entities/ef/PimsProperty.cs
  source/backend/entities/ef/PimsPropertyBoundaryVw.cs
  source/backend/entities/ef/PimsPropertyLocationVw.cs
  source/backend/entities/ef/PimsPropertyVw.cs
Labels: db-scaffold

#4015 correct modal close icon, text.
  source/frontend/package-lock.json
  source/frontend/src/components/common/form/NotesModal.tsx
  source/frontend/src/features/notes/add/AddNotesFormModal.tsx
  source/frontend/src/features/notes/add/__snapshots__/AddNotesContainer.test.tsx.snap
  source/frontend/src/features/notes/add/__snapshots__/AddNotesFormModal.test.tsx.snap
Labels: bug

#4012 psp-8268 | Added historical file numbers to the disposition header
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionHeader.test.tsx.snap
Labels: enhancement

#4013 PSP-8256 : Remove PS and LIS number from lease/area
  source/frontend/src/features/leases/add/ReferenceSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailDocumentation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailDocumentation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailDocumentation.test.tsx.snap
Labels: enhancement

#4019 correct help href not being set during initial help modal open.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/features/help/containers/HelpContainer.tsx
Labels: bug, hotfix, 5.2

#4016 PSP-5492 Update Historical # and Type on Property Details (Property Attributes)
  source/backend/api/Areas/HistoricalNumber/HistoricalNumberController.cs
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/dal/Repositories/HistoricNumberRepository.cs
  source/backend/dal/Repositories/Interfaces/IHistoricalNumberRepository.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdateHistoricalNumbersSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/validation.ts
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.test.tsx
  source/frontend/src/hooks/pims-api/useApiHistoricalNumbers.ts
  source/frontend/src/hooks/repositories/useHistoricalNumberRepository.ts
Labels: enhancement

#4022 PSP-6900: Enhance L/L insurance options
  source/backend/apimodels/Models/Concepts/Lease/InsuranceModel.cs
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/Policy.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/InsuranceForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/__snapshots__/EditInsuranceContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/models.ts
Labels: enhancement, 5.3

#4024 PSP-7493 lease insurance UI cleanup
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/Insurance.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/Policy.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/__snapshots__/Insurance.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/EditInsuranceContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/EditInsuranceContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/InsuranceForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/__snapshots__/EditInsuranceContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/edit/models.ts
Labels: enhancement, 5.3

#4018 PSP-8412 | Updated lease header files and initial work on other file headers
  source/frontend/src/components/common/HeaderField/AuditSection.tsx
  source/frontend/src/components/common/HeaderField/HeaderField.tsx
  source/frontend/src/components/common/UserNameTooltip.tsx
  source/frontend/src/components/common/styles.ts
  source/frontend/src/components/measurements/styles.tsx
  source/frontend/src/features/acquisition/list/AcquisitionListView.tsx
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeListView.tsx
  source/frontend/src/features/contacts/styles.ts
  source/frontend/src/features/leases/detail/LeasePages/payment/styles.tsx
  source/frontend/src/features/leases/detail/LeaseStatusSummary.tsx
  source/frontend/src/features/leases/list/LeaseListView.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.test.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/common/__snapshots__/ProjectHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/__snapshots__/MotiInventoryHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.test.tsx
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberSectionView.tsx
  source/frontend/src/features/research/list/ResearchListView.tsx
  source/frontend/src/index.tsx
Labels: enhancement

#4025 psp-7417 add health checks for Major pims services.
  source/backend/api/Helpers/Healthchecks/PimsCdogsHealthCheck.cs
  source/backend/api/Helpers/Healthchecks/PimsDatabaseHealthcheck.cs
  source/backend/api/Helpers/Healthchecks/PimsExternalApiHealthcheck.cs
  source/backend/api/Helpers/Healthchecks/PimsGeocoderHealthCheck.cs
  source/backend/api/Helpers/Healthchecks/PimsGeoserverHealthcheck.cs
  source/backend/api/Helpers/Healthchecks/PimsLtsaHealthcheck.cs
  source/backend/api/Helpers/Healthchecks/PimsMayanHealthCheck.cs
  source/backend/api/Helpers/Healthchecks/PimsMetricsHealthCheck.cs
  source/backend/api/Services/DocumentGenerationService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/Startup.cs
  source/backend/api/appsettings.Development.json
  source/backend/api/appsettings.Local.json
  source/backend/api/appsettings.Test.json
  source/backend/api/appsettings.Uat.json
  source/backend/api/appsettings.json
  source/backend/dal/Helpers/Extensions/IdentityExtensions.cs
Labels: enhancement, tech-debt

#4023 PSP-8314 : Record reason for rejecting or terminating a lease
  source/backend/api/Services/LeaseService.cs
  source/backend/apimodels/CodeTypes/LeaseStatusTypes.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseModel.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/LeaseDetailSubForm.test.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/LeasePageForm.tsx
  source/frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/lease/detail/LeaseTab.tsx
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_LeaseStatusTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Lease.ts
  source/frontend/src/models/defaultInitializers.ts
Labels: enhancement

#3966 styled modal that warns the user is leaving a form.
  source/frontend/src/components/common/ConfirmNavigation.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
Labels: enhancement, 5.3

#4020 psp-8438 | Complementary UI for file headers + zoom to property fix
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/property/__snapshots__/MotiInventoryHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchHeader.test.tsx.snap
Labels: enhancement

#4021 PSP-8208 | Updated property header
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/property/__snapshots__/MotiInventoryHeader.test.tsx.snap
Labels: enhancement

#4028 psp-8228 | Updated header status display
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/components/common/HeaderField/AuditSection.tsx
  source/frontend/src/components/common/HeaderField/StatusField.tsx
  source/frontend/src/components/common/HeaderField/styles.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.test.tsx
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.tsx
  source/frontend/src/features/mapSideBar/project/common/__snapshots__/ProjectHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchHeader.test.tsx.snap
  source/frontend/src/index.tsx
Labels: enhancement

#4027 psp-8415 correct permissions on insurance controller.
  source/backend/api/Areas/Leases/Controllers/InsuranceController.cs
Labels: bug

#4026 psp-8185 remove closebutton generic modal prop - show custom pims clo…
  source/frontend/src/components/common/GenericModal.tsx
  source/frontend/src/features/documents/documentUpload/DocumentUploadContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.tsx
  source/frontend/src/features/notes/__snapshots__/NoteContainer.test.tsx.snap
  source/frontend/src/features/notes/detail/NoteDetailsFormModal.tsx
  source/frontend/src/features/notes/detail/__snapshots__/NoteDetailsFormModal.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/columns.tsx
  source/frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  source/frontend/src/features/notes/update/UpdateNoteFormModal.tsx
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteContainer.test.tsx.snap
  source/frontend/src/features/notes/update/__snapshots__/UpdateNoteFormModal.test.tsx.snap
  source/frontend/src/features/projects/reports/ProjectExportContainer.tsx
Labels: bug

#4029 Backmerge test to dev
  source/frontend/src/features/help/containers/HelpContainer.tsx
Labels: release-management

#4032 PSP-4089 FT-REG: Property Info - When getting a Land Parcel Type that is not defined by PIMS, on edit mode, should display the default option as "Unknown"
  source/backend/apimodels/CodeTypes/PropertyTypes.cs
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/features/leases/add/LeaseDetailSubForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_PropertyTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Insurance.ts
  source/frontend/src/models/api/generated/ApiGen_Mayan_FilePage.ts
Labels: bug

#4030 Psp-8424 download animation correction - also unrelated eslint fix.
  source/frontend/src/assets/images/subdivisionconsolidation.svg
  source/frontend/src/assets/scss/App.scss
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: enhancement

#4035 Hotfix - ensure that it is possible to display properties with no own…
  source/backend/api/Pims.Api.csproj
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/package.json
Labels: bug, hotfix, 5.2

#4037 PSP-8474 | Fixed property updates removing is-owned
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
Labels: bug, 5.2

#4038 PSP-8413 | Fixed lease warning not showing
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
Labels: bug

#4040 Backmerge test to dev
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/models/UpdatePropertyDetailsFormModel.ts
Labels: release-management

#4041 Bump DEV version - IS81
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: release-management

#4033 PSP-8227 : Add search for "historical file number" on the property se…
  source/backend/api/Areas/Property/Models/PropertyFilterModel.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyViewMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyViewModel.cs
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/dal/Models/PropertyFilter.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberContainer.tsx
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberSectionView.tsx
  source/frontend/src/features/properties/filter/IPropertyFilter.ts
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/list/PropertyListView.test.tsx
  source/frontend/src/features/properties/list/PropertyListView.tsx
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  source/frontend/src/features/properties/list/columns.tsx
Labels: enhancement

#4044 psp 7495 | Lease tenant UI update
  source/frontend/src/components/common/form/TableSelect.tsx
  source/frontend/src/components/propertySelector/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/columns.tsx
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/__snapshots__/UpdateDispositionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/updateProjects/__snapshots__/UpdateProjectsSubForm.test.tsx.snap
  source/frontend/src/utils/columnUtils.tsx
Labels: enhancement

#4045 PSP-8444: Automation test cases update based on IS80 changes
  testing/PIMS.Tests.Automation/Classes/Lease.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/HelpDesk.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchDispositionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#4049 PSP-8501: L/L - Insurance in Place Field
  source/backend/entities/PimsBaseContext.cs
Labels: bug

#4056 psp-8531 correct the disposition header icon
  source/frontend/src/features/mapSideBar/disposition/DispositionView.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
Labels: bug, 5.3

#4055 PSP-6546: Area component across the application should be displayed with at most 4 decimals
  source/frontend/src/components/common/form/ContactInput/ContactInputView.test.tsx
  source/frontend/src/components/measurements/AreaForm.test.tsx
  source/frontend/src/components/measurements/AreaForm.tsx
  source/frontend/src/components/measurements/AreaView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertyInformation.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/propertyOperationColumns.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeUpdateForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakeUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/operations/SelectedOperationProperty.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.test.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/features/properties/list/PropertyListView.test.tsx
Labels: enhancement, 5.3

#4039 pims document preview - pre-cache.
  source/backend/api/Models/Configuration/MayanConfig.cs
  source/backend/api/Repositories/Mayan/IEdmsDocumentRepository.cs
  source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/appsettings.json
  source/frontend/src/assets/scss/App.scss
  source/frontend/src/features/documents/DocumentPreviewView.tsx
Labels: enhancement, 5.3

#4060 psp-8549 correct property header retired status styling.
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/property/__snapshots__/MotiInventoryHeader.test.tsx.snap
Labels: 5.3

#4058 psp-8470 tooltip for lease statuses.
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
Labels: enhancement, 5.3

#4057 psp-8534 add 'file:' in front of status on file headers.
  source/frontend/src/components/common/HeaderField/AuditSection.tsx
  source/frontend/src/components/common/HeaderField/StatusField.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/common/__snapshots__/ProjectHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
Labels: bug, 5.3

#4043 Psp 8099 - allow special instruction whitespace to display.
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
Labels: enhancement, 5.3

#4054 psp-8545 property ownership filter fixes.
  source/frontend/src/components/maps/MapSearch.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/list/PropertyListView.tsx
Labels: bug, 5.3

#4059 psp-5576 update select all button behaviour, ensure paged selections …
  source/frontend/src/components/Table/Table.tsx
Labels: bug, 5.3

#4046 psp-8477 - use fully attributed parcel map.
  source/frontend/public/tenants/tenant.json
  source/frontend/src/components/common/mapFSM/models.ts
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.test.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.tsx
  source/frontend/src/components/propertySelector/map/__snapshots__/PropertyMapSelectorSubForm.test.tsx.snap
  source/frontend/src/components/propertySelector/models.ts
  source/frontend/src/components/propertySelector/search/LayerFilter.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/components/propertySelector/search/__snapshots__/LayerFilter.test.tsx.snap
  source/frontend/src/components/propertySelector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap
  source/frontend/src/components/propertySelector/search/mapPropertyColumns.ts
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/hooks/layer-api/wfsAxios.ts
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/repositories/mapLayer/useFullyAttributedParcelMapLayer.ts
  source/frontend/src/hooks/repositories/useComposedProperties.ts
  source/frontend/src/hooks/useRefreshSiteminder.ts
  source/frontend/src/index.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/layers/parcelMapBC.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
  source/frontend/src/utils/mapPropertyUtils.test.tsx
  source/frontend/src/utils/mapPropertyUtils.ts
  source/frontend/vite.config.ts
Labels: enhancement, 5.3

#4064 PSP-8555: Update .NET sonarscanner in GitHub actions to support .NET 8
  .github/workflows/api-dotnetcore.yml
  source/frontend/src/features/leases/detail/LeasePages/details/PropertyInformation.test.tsx
Labels: tech-debt, devops

#4066 psp-8108 style changes for improvements page.
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
Labels: enhancement

#4067 make the file pretext on file headers in front of file status bold.
  source/frontend/src/components/common/HeaderField/StatusField.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/common/__snapshots__/ProjectHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
Labels: bug, 5.3

#4061 PSP-8194 Add Complete Support for MultiPolygons
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CoordinateTransformService.TransformationFilter .cs
  source/backend/api/Services/CoordinateTransformService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/ICoordinateTransformService.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/api/Startup.cs
  source/backend/apimodels/CodeTypes/GeoJsonTypes.cs
  source/backend/apimodels/Models/Concepts/Property/GeometryMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyModel.cs
  source/backend/core/Converters/GeometryJsonConverter.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/entities/Partials/DispositionFileProperty.cs
  source/backend/entities/Partials/PropertyAcquisitionFile.cs
  source/backend/entities/Partials/PropertyLease.cs
  source/backend/entities/Partials/PropertyResearchFile.cs
  source/backend/entities/Partials/base/IBaseTypeEntity{T_Id,T_DisplayOrder}.cs
  source/backend/entities/Partials/base/IExpiringTypeEntity.cs
  source/backend/entities/Partials/base/IWithPropertyEntity.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/dal/Core/Converters/GeometryJsonConverterTest.cs
  source/frontend/package.json
  source/frontend/src/components/propertySelector/models.ts
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/mocks/properties.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_GeoJsonTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Property.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyView.ts
  source/frontend/src/utils/mapPropertyUtils.ts
  tools/TsModelGenerator/Specifications/PimsGenerationSpec.cs
Labels: enhancement, 5.4

#4065 PSP-8552 : FT: Map View- Historical file number search is not working…
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/propertySelector/models.ts
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.test.tsx
  source/frontend/src/constants/API.ts
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/hooks/repositories/useMapProperties.tsx
  source/frontend/src/mocks/filterData.mock.ts
  source/frontend/src/models/layers/pimsPropertyLocationView.ts
Labels: bug, 5.3

#4069 modify tooltip render direction to avoid clipping.
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
Labels: bug, 5.3

#4050 psp-8499 | Updated historical number rendering for leases
  source/frontend/src/features/leases/list/LeaseFilter/LeaseFilter.tsx
  source/frontend/src/features/leases/list/LeaseListView.test.tsx
  source/frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberContainer.tsx
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberFieldView.tsx
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberSectionView.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/list/PropertyListView.test.tsx
  source/frontend/src/features/properties/list/columns.tsx
Labels: enhancement

#4068 Features/psp 7494
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/components/common/Section/Section.tsx
  source/frontend/src/components/common/SectionListHeader.tsx
  source/frontend/src/components/common/styles.ts
  source/frontend/src/features/contacts/contact/create/Organization/__snapshots__/CreateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/DepositNotes.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositNotes/__snapshots__/DepositNotes.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/DepositsReceivedContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/__snapshots__/DepositsReceivedContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/columns.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReturnedContainer/columns.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailDocumentation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/documents/__snapshots__/DocumentsPage.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/__snapshots__/StakeHolderView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/__snapshots__/OffersAndSaleView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/__snapshots__/ProjectSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/__snapshots__/OperationSectionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/__snapshots__/OperationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/__snapshots__/PropertyContactListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/__snapshots__/PropertyManagementDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakeUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/tabs/checklist/detail/__snapshots__/ChecklistView.test.tsx.snap
  source/frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
Labels: enhancement, 5.3
