Repository bcgov/PSP, pull requests merged in 2024-07, with the labels that each got.

#4145 psp-8605 do not show the add button when a take's file has been compl…
  source/frontend/src/components/common/SectionListHeader.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
Labels: bug

#4146 psp-8690 Ensure that selected locations
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
Labels: bug

#4148 psp-8718 correct behaviour of address search.
  source/frontend/src/components/propertySelector/search/LayerFilter.scss
  source/frontend/src/features/properties/components/GeocoderAutoComplete.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
Labels: bug

#4149 psp-8545 Correct behaviour when there is no property ownership specif…
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
  source/backend/dal/Repositories/PropertyRepository.cs
Labels: bug

#4156 Version bump - IS84
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: release-management

#4153 psp-8761 swap to using cdogs health endpoint.
  source/backend/api/Helpers/Healthchecks/PimsCdogsHealthCheck.cs
  source/backend/api/Repositories/Cdogs/CdogsRepository.cs
  source/backend/api/Repositories/Cdogs/IDocumentGenerationRepository.cs
Labels: enhancement, tech-debt

#4150 PSP-8599 remove acquisition completed column from excel export
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Models/AcquisitionFileExportModel.cs
Labels: bug

#4158 PSP-8560: enforce consistent styling for add button, update "focus" state to al…
  source/frontend/src/components/common/styles.ts
  source/frontend/src/features/acquisition/list/AcquisitionListView.tsx
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeListView.tsx
  source/frontend/src/features/leases/list/LeaseListView.tsx
  source/frontend/src/features/research/list/ResearchListView.tsx
Labels: enhancement, ui/ux

#4159 PSP-8354 Tool Tip – Lease/License: Exercised Option
  source/frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/PeriodPaymentsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/__snapshots__/PeriodForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/__snapshots__/PaymentPeriodsView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/columns.tsx
Labels: enhancement, 5.4

#4161 PSP-8612 : FT:Lease&License Checklist: Not applicable icon is missing…
  source/backend/apimodels/CodeTypes/ChecklistItemStatusTypes.cs
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_LeaseChecklistItemStatusTypes.ts
Labels: bug

#4163 PSP-8591 : UI UX Clean Up - Left Side Menu
  source/frontend/src/assets/images/acquisition-icon.svg
  source/frontend/src/assets/images/admin-icon.svg
  source/frontend/src/assets/images/admin-panel-settings.svg
  source/frontend/src/assets/images/contact-icon.svg
  source/frontend/src/assets/images/disposition-icon.svg
  source/frontend/src/assets/images/home-icon.svg
  source/frontend/src/assets/images/lease-icon.svg
  source/frontend/src/assets/images/projects-icon.svg
  source/frontend/src/assets/images/real-estate-agent.svg
  source/frontend/src/assets/images/research-icon.svg
  source/frontend/src/assets/images/source.svg
  source/frontend/src/assets/images/subdivision-icon.svg
  source/frontend/src/assets/images/subdivisionconsolidation.svg
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/components/layout/SideNavBar/NavIcon.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: enhancement

#4165 regenerate scaffold.
  source/backend/entities/ef/PimsDispositionFileProperty.cs
  source/backend/entities/ef/PimsLease.cs
  source/backend/entities/ef/PimsLeaseHist.cs
  source/backend/entities/ef/PimsLeasePeriod.cs
  source/backend/entities/ef/PimsLeasePeriodHist.cs
  source/backend/entities/ef/PimsPropertyActivityHist.cs
  source/backend/entities/ef/PimsPropertyLease.cs
  source/backend/entities/ef/PimsPropertyResearchFile.cs
Labels: db-migration

#4167 psp-8522 update lease export to include financial gain fields.
  source/backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  source/backend/api/Areas/Reports/Models/Lease/LeaseModel.cs
  source/backend/core/Extensions/BoolExtensions.cs
  source/backend/tests/unit/api/Controllers/Reports/LeaseControllerTest.cs
Labels: enhancement

#4169 psp-8796 correct generated property report.
  source/backend/api/Areas/Reports/Mapping/Property/PropertyMap.cs
  source/backend/api/Areas/Reports/Models/Property/PropertyModel.cs
Labels: bug

#4172 PSP-8693: Rename Header Dates (Lease and License)
  source/backend/apimodels/Models/Concepts/Lease/LeaseMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseModel.cs
  source/frontend/src/components/common/HeaderField/HeaderField.tsx
  source/frontend/src/components/common/HeaderField/StatusField.tsx
  source/frontend/src/components/common/Section/SectionField.tsx
  source/frontend/src/features/leases/detail/LeasePages/LeasePageForm.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.test.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/common/__snapshots__/ProjectHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/__snapshots__/MotiInventoryHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberContainer.tsx
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberSectionView.tsx
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Lease.ts
  source/frontend/src/models/defaultInitializers.ts
  source/frontend/src/utils/formUtils.tsx
Labels: enhancement, 5.4

#4173 PSP-8826: Automation test case update for IS84
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#4177 add link icon to help modal.
  source/frontend/src/features/help/containers/HelpContainer.tsx
Labels: bug

#4175 PSP-8448 : Ability to track Arbitration Cities for Leases/Licences
  source/backend/api/Areas/Leases/Controllers/LeaseController.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseModel.cs
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/models.ts
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Lease.ts
  source/frontend/src/models/defaultInitializers.ts
Labels: enhancement

#4171 psp-8605 do not show edit admin button if file is non-editable.
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
Labels: bug

#4178 automatically tag uat images so they can be released to prod.
  .github/workflows/retag-test-to-uat.yml
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_pre_release_hotfix.yml
Labels: release-management

#4179 PSP-8511: Headers - lower case on label second word
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.tsx
  source/frontend/src/features/mapSideBar/project/common/__snapshots__/ProjectHeader.test.tsx.snap
Labels: enhancement, 5.4

#4160 PSP-8414 : Select one or multiple properties for H120 Generation
  source/backend/api/Areas/Acquisition/Controllers/AcquisitionFileController.cs
  source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/ICompensationRequisitionService.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionPropertyMap.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionPropertyModel.cs
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/dal/Repositories/Interfaces/IAcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs
  source/backend/entities/Partials/PimsPropAcqFlCompReq.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/features/documents/documentDetail/DocumentDetailForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/models.ts
  source/frontend/src/features/mapSideBar/shared/tabs/checklist/detail/ChecklistView.tsx
  source/frontend/src/features/mapSideBar/shared/tabs/checklist/update/__snapshots__/UpdateChecklistForm.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiRequisitionCompensations.ts
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompensationRequisition.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompensationRequisitionProperty.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
Labels: enhancement

#4170 psp-8772 lease payment export corrections.
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Models/Report/LeasePaymentReportMap.cs
  source/backend/api/Services/LeasePaymentService.cs
  source/backend/dal/Repositories/Interfaces/ILeasePaymentRepository.cs
  source/backend/dal/Repositories/LeasePaymentRepository.cs
  source/backend/tests/unit/api/Mapping/LeasePaymentReportMapTest.cs
  source/frontend/src/features/leases/detail/LeasePages/payment/PeriodPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.tsx
Labels: bug

#4180 psp-8630 | Updated Leases and added renewals
  source/backend/api/Areas/Leases/Controllers/LeaseRenewalController.cs
  source/backend/api/Services/ILeaseService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseModel.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseRenewalMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseRenewalModel.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/Interfaces/ILeaseRenewalRepository.cs
  source/backend/dal/Repositories/Interfaces/ILeaseRepository.cs
  source/backend/dal/Repositories/LeaseRenewalRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/entities/Partials/LeaseRenewal.cs
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/add/RenewalSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailPeriodInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailPeriodInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseRenewalsView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/leases/hooks/useLeaseDetail.ts
  source/frontend/src/features/leases/index.ts
  source/frontend/src/features/leases/models.ts
  source/frontend/src/hooks/pims-api/useApiLeases.ts
  source/frontend/src/hooks/repositories/useLeaseRepository.ts
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Lease.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_LeaseRenewal.ts
  source/frontend/src/models/defaultInitializers.ts
Labels: enhancement

#4185 prevent PIMS translating mayan 202 responses as errors.
  source/backend/api/Repositories/RestCommon/BaseRestRepository.cs
Labels: bug

#4186 Correct double scroll bar issue.
  source/frontend/src/components/common/TabView.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/tabs/__snapshots__/ProjectTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: ui/ux

#4184 correct NPE in address iterator.
  source/backend/api/Areas/Organizations/Controllers/OrganizationController.cs
  source/backend/api/Areas/Persons/Controllers/PersonController.cs
Labels: bug

#4183 psp-8784 do not display cancel modal unless changes have been made to…
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseForm.tsx
  source/frontend/src/features/leases/add/ConsultationSubForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailConsultation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/models/defaultInitializers.ts
Labels: bug

#4176 psp-8708 fix tenant primary contacts.
  source/backend/api/Areas/Contacts/Models/Search/ContactSummaryModel.cs
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/columns.tsx
Labels: bug

#4187 PSP-8317: Lease and Licence Edit/View Fee Denomination forms
  source/backend/apimodels/Models/Concepts/Lease/LeaseMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseModel.cs
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/FeeDeterminationSubForm.test.tsx
  source/frontend/src/features/leases/add/FeeDeterminationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/FeeDeterminationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailFeeDetermination.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailFeeDetermination.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailFeeDetermination.test.tsx.snap
  source/frontend/src/features/leases/leaseUtils.ts
  source/frontend/src/features/leases/models.ts
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Lease.ts
  source/frontend/src/models/defaultInitializers.ts
Labels: enhancement, 5.4

#4189 psp-8771 & psp-8683 | Lease expiry using renewal information
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/PropertyLeaseRepository.cs
  source/backend/entities/Extensions/LeaseExtensions.cs
  source/backend/tests/unit/dal/Core/Extensions/LeaseExtensionsTest.cs
  source/frontend/src/features/leases/leaseUtils.ts
  source/frontend/src/features/leases/list/LeaseFilter/LeaseFilter.tsx
  source/frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateLicenceOfOccupation.ts
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/LeaseAssociationContent.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/models/generate/lease/GenerateLease.test.ts
  source/frontend/src/models/generate/lease/GenerateLease.ts
Labels: enhancement

#4190 PSP-8744 : Management activity - tooltip for Delete
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/PropertyActivityDetailContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesList.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesListContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesListView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/router/PropertyActivityRouter.tsx
Labels: enhancement

#4188 PSP-7980 : Display L/L Status in Property Information Pane - Management (Summary Section)
  source/backend/api/Services/PropertyService.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyManagementModel.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/entities/Extensions/LeaseExtensions.cs
  source/backend/tests/unit/api/Services/PropertyServiceTest.cs
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/__snapshots__/PropertyManagementDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/PropertyManagementUpdateContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/models.test.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/models.ts
  source/frontend/src/mocks/propertyManagement.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyManagement.ts
  source/frontend/src/utils/propertyUtils.ts
Labels: enhancement

#4191 PSP-8732 Add ability to control map marker within file to additional file types
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFilePropertyMap.cs
  source/backend/apimodels/Models/Concepts/Lease/PropertyLeaseMap.cs
  source/backend/apimodels/Models/Concepts/Lease/PropertyLeaseModel.cs
  source/backend/apimodels/Models/Concepts/ResearchFile/ResearchFilePropertyMap.cs
  source/backend/dal/Repositories/PropertyLeaseRepository.cs
  source/backend/entities/Partials/DispositionFileProperty.cs
  source/backend/entities/Partials/PropertyAcquisitionFile.cs
  source/backend/entities/Partials/PropertyLease.cs
  source/backend/entities/Partials/PropertyResearchFile.cs
  source/backend/entities/Partials/base/IFilePropertyEntity.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
  source/frontend/src/features/leases/add/FeeDeterminationSubForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailFeeDetermination.test.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/disposition/models/DispositionFormModel.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/models.ts
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/models.ts
  source/frontend/src/features/mapSideBar/shared/models.ts
Labels: enhancement, 5.4

#4193 PSP-8856: Status tooltip on Details view + Research File MOTI Label fixed
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailView.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchHeader.test.tsx.snap
Labels: bug, 5.4

#4192 psp-8845 ensure that pin of zero not sent, not used for property match.
  source/backend/api/Services/AcquisitionFileService.cs
  source/frontend/src/features/mapSideBar/shared/models.ts
Labels: bug

#4195 psp-8851 | Fixed consultations update
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/ConsultationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
Labels: bug

#4168 psp-8783 ensure that form state is maintained during collapsing of sidebar.
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  source/frontend/src/features/mapSideBar/layout/__snapshots__/MapSideBarLayout.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailView.test.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: bug

#4196 psp=8857 Do not use global lease to check periods - fix start date is…
  source/frontend/src/features/leases/detail/LeasePages/payment/PeriodPaymentsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/PeriodPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/hooks/useDeletePeriodsPayments.tsx
Labels: bug

#4198 psp-8852 | Fixed tenants without primary contact on save
  source/frontend/src/features/contacts/contact/detail/Organization.tsx
  source/frontend/src/features/contacts/contact/detail/__snapshots__/Organization.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/tenant/TenantOrganizationContactInfo.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/columns.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/models.ts
Labels: bug

#4200 PSP-8862 : FT: Missing space on top of map view icon on Left Side Menu
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/components/layout/SideNavBar/styles.ts
Labels: bug

#4199 Psp 8855 fix create file from map property - property attribution display
  source/frontend/src/components/propertySelector/MapSelectorContainer.tsx
Labels: bug

#4201 PSP-8801 Acquisition Files - When default region is changed, the warning header is different between the create form and the edit form
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx
  source/frontend/src/hooks/useApiUserOverride.ts
Labels: bug, 5.4

#4204 PSP-8867 : FT: tooltip is missing for selected properties label in the edit/view compensation requisition screen
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
Labels: bug

#4205 PSP-8896 : FT:AcquisitionFile:Requisition: System generates warning m…
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
Labels: bug

#4207 PSP-8317: Suggested fee mispelling fix
  source/frontend/src/features/leases/add/FeeDeterminationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/FeeDeterminationSubForm.test.tsx.snap
Labels: bug, 5.4

#4206 PSP-8868 Display file marker locations for Lease/Licence
  source/frontend/src/features/leases/detail/LeasePages/details/PropertiesInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertiesInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/PropertiesInformation.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.test.tsx
Labels: bug, 5.4

#4208 PSP-8911 : FT: User is not able to delete the requisition if the user…
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
Labels: bug

#4213 Psp 8914 fix project npe
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/LeaseAssociationContent.tsx
Labels: bug

#4210 Bump dev version to IS85
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops, release-management

#4216 psp-8907 | Fixed lease export for multiple leases
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
Labels: bug

#4215 psp-8898 remove periods at end of tooltips, update Exercised to Exerc…
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/features/contacts/contact/detail/Organization.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  source/frontend/src/features/documents/DownloadDocumentButton.tsx
  source/frontend/src/features/leases/add/FeeDeterminationSubForm.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/add/RenewalSubForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/columns.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailFeeDetermination.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/payment/PaymentFormContent.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/payments/paymentsColumns.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/periodColumns.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/update/acquisitionOwners/UpdateAcquisitionOwnersSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/form/AcquisitionAgreementForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form5/ExpropriationForm5.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/InterestHolderSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderForm.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionSummaryView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/OffersAndSaleView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionOfferDetails/DispositionOfferDetails.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/form/DispositionOfferForm.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/form/DispositionSaleForm.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesList.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/summary/PropertyManagementDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/update/summary/PropertyManagementUpdateForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
Labels: enhancement, ui/ux

#4217 Backmerge test to dev
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/LeaseAssociationContent.tsx
Labels: release-management

#4218 psp-8912 show suggested text for fee determination.
  source/frontend/src/features/leases/add/FeeDeterminationSubForm.test.tsx
  source/frontend/src/features/leases/add/FeeDeterminationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/FeeDeterminationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailFeeDetermination.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailFeeDetermination.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailFeeDetermination.test.tsx.snap
  source/frontend/src/features/leases/leaseUtils.ts
Labels: enhancement

#4219 PSP-8556 | Updated payments export with Historical numbers and new fields
  source/backend/api/Models/Report/LeasePaymentReportMap.cs
  source/backend/api/Models/Report/LeasePaymentReportModel.cs
  source/backend/dal/Repositories/LeasePaymentRepository.cs
Labels: enhancement

#4221 PSP-8794 : Allow payment periods to have default start date
  source/frontend/src/features/leases/detail/LeasePages/payment/PeriodPaymentsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/PeriodPaymentsContainer.tsx
Labels: enhancement

#4223 PSP-8945 : Lease & Licences - Administration Section: Add an expandable tooltip above MOTI Contact field
  source/frontend/src/components/common/form/FormGuide/FormGuideContainer.tsx
  source/frontend/src/components/common/form/FormGuide/FormGuideView.tsx
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchFileNameGuide.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchFileNameGuide.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/__snapshots__/UpdateSummaryForm.test.tsx.snap
Labels: enhancement

#4224 Truncate NVARCHAR(max) Columns Prior to Alter Up
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/000_Truncate_Nvarchar_Max.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S85_00/Alter Up/000_Truncate_Nvarchar_Max.sql
Labels: db-migration

#4225 PSP-6901: Enhance L/L to have a tooltip for Intended Use
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
Labels: enhancement, 5.5

#4226 PSP-8284: UI/UX- Map Layer: Text alignment
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/data.ts
Labels: enhancement, 5.5

#4227 PSP-8746 | GST is modifiable for periods
  source/frontend/src/components/common/form/Check.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/PeriodPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/PeriodForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/period/VariablePeriodSubForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/models.test.ts
  source/frontend/src/features/leases/detail/LeasePages/payment/models.ts
Labels: enhancement

#4228 PSP-8872: Update to layer labels on map and in the panel
  source/frontend/src/components/maps/leaflet/Control/LayersControl/data.ts
  source/frontend/vite.config.ts
Labels: enhancement, 5.5

#4229 PSP-8505 : Update list of lease types
  source/backend/api/Areas/Reports/Mapping/Lease/LeaseMap.cs
  source/backend/api/Controllers/LookupController.cs
  source/backend/api/Models/Report/LeasePaymentReportMap.cs
  source/backend/api/Services/ILeaseService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/apimodels/CodeTypes/LeasePurposeTypes.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseModel.cs
  source/backend/apimodels/Models/Concepts/Lease/LeasePurposeMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeasePurposeModel.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/entities/Partials/PimsLeaseLeasePurpose.cs
  source/backend/tests/unit/dal/Repositories/LookupRepositoryTest.cs
  source/frontend/src/components/common/form/Multiselect.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/AdministrationSubForm.test.tsx
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/leases/models/LeasePurposeModel.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.helpers.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/mocks/lease.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_LeasePurposeTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Lease.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_LeasePurpose.ts
  source/frontend/src/models/defaultInitializers.ts
Labels: enhancement

#4230 Highway layer map popup enhancement
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/common/SimplePagination.scss
  source/frontend/src/components/common/SimplePagination.tsx
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/__snapshots__/LayerPopupView.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupContent.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupContent.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/__snapshots__/LayerPopupContent.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/constants.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/styles.ts
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/repositories/mapLayer/useHighwayLayer.tsx
  source/frontend/src/mocks/featureset.mock.ts
  source/frontend/src/mocks/mockISSResult.ts
  source/frontend/src/models/layers/pimsHighwayLayer.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: enhancement

#4231 PSP-8940 : FT-REG: Termination date - The field is missing its tooltip
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailView.tsx
Labels: bug

#4232 Fixed call parameters
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
Labels: enhancement
