Repository bcgov/PSP, pull requests merged in 2024-06, with the labels that each got.

#4075 psp-8585 display either retired or disposed status in property header…
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/features/leases/detail/LeasePages/checklist/update/UpdateLeaseChecklistContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/hooks/layer-api/useGeoServer.ts
Labels: bug, 5.3

#4076 psp-8568 fix database scripts such that the draft disposition status …
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S80_00/Alter Down/138_DML_PIMS_DISPOSITION_FILE_STATUS_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S80_00/Alter Up/138_DML_PIMS_DISPOSITION_FILE_STATUS_TYPE_Alter_Up.sql
Labels: bug

#4078 PSP-8587 table pagination visual bug
  source/frontend/src/components/Table/PageSizeSelector.test.tsx
  source/frontend/src/components/Table/PageSizeSelector.tsx
  source/frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
Labels: bug

#4081 5.4 alignment
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/LeaseService.cs
  source/frontend/package.json
  source/frontend/src/components/Table/PageSizeSelector.test.tsx
  source/frontend/src/components/Table/PageSizeSelector.tsx
  source/frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
Labels: alignment

#4077 PSP-8586 : FT-REG: Subdivision/ Consolidation - Menu icon enlarges when user clicks on expand the left menu section
  source/frontend/src/assets/images/subdivisionconsolidation.svg
  source/frontend/src/components/layout/SideNavBar/NavIcon.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/components/layout/SideNavBar/styles.ts
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: bug

#4071 PSP-8536: Property Information Details - Historical File, Headers.
  testing/PIMS.Tests.Automation/Classes/Property.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionConsolidationProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
Labels: test-scripts

#4082 psp-8586 auto-format corrections.
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S80_00/Alter Down/138_DML_PIMS_DISPOSITION_FILE_STATUS_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S80_00/Alter Up/138_DML_PIMS_DISPOSITION_FILE_STATUS_TYPE_Alter_Up.sql
Labels: bug, 5.3

#4080 color pallette corrections.
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/components/common/HeaderField/StatusField.tsx
Labels: tech-debt, 5.4

#4083 Backmerge test to dev
  source/frontend/src/assets/images/edit-map-marker.svg
  source/frontend/src/components/common/buttons/EditPropertiesButton.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionMenu.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.tsx
  source/frontend/src/features/mapSideBar/research/common/ResearchMenu.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchMenu.test.tsx.snap
Labels: alignment

#4085 commits for PSP-8524 changes
  etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.dtproj
  etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.dtproj.user
  etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.sln
  etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS_LOAD.dtsx
  etl/LISDB_PIMS_HISTORICAL_NUMBERS/Project.params
Labels: etl

#4086 merge changes from dev into 5.4
  etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.dtproj
  etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.dtproj.user
  etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS.sln
  etl/LISDB_PIMS_HISTORICAL_NUMBERS/LISDB_PIMS_HISTORICAL_NUMBERS_LOAD.dtsx
  etl/LISDB_PIMS_HISTORICAL_NUMBERS/Project.params
  source/backend/api/Pims.Api.csproj
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S80_00/Alter Down/138_DML_PIMS_DISPOSITION_FILE_STATUS_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S80_00/Alter Up/138_DML_PIMS_DISPOSITION_FILE_STATUS_TYPE_Alter_Up.sql
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/assets/images/edit-map-marker.svg
  source/frontend/src/assets/images/subdivisionconsolidation.svg
  source/frontend/src/components/common/buttons/EditPropertiesButton.tsx
  source/frontend/src/components/layout/SideNavBar/NavIcon.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/components/layout/SideNavBar/styles.ts
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionMenu.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.tsx
  source/frontend/src/features/mapSideBar/research/common/ResearchMenu.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchMenu.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
  testing/PIMS.Tests.Automation/Classes/Property.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionConsolidationProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
Labels: alignment

#4087 Merge 5.4 branch into dev
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CoordinateTransformService.TransformationFilter .cs
  source/backend/api/Services/CoordinateTransformService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/ICoordinateTransformService.cs
  source/backend/api/Services/IPropertyService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/api/Startup.cs
  source/backend/apimodels/CodeTypes/GeoJsonTypes.cs
  source/backend/apimodels/Models/Concepts/Property/GeometryMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyModel.cs
  source/backend/core/Converters/GeometryJsonConverter.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/entities/Partials/DispositionFileProperty.cs
  source/backend/entities/Partials/PropertyAcquisitionFile.cs
  source/backend/entities/Partials/PropertyLease.cs
  source/backend/entities/Partials/PropertyResearchFile.cs
  source/backend/entities/Partials/base/IBaseTypeEntity{T_Id,T_DisplayOrder}.cs
  source/backend/entities/Partials/base/IWithPropertyEntity.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/dal/Core/Converters/GeometryJsonConverterTest.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/components/common/HeaderField/StatusField.tsx
  source/frontend/src/components/propertySelector/models.ts
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_GeoJsonTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_Property.ts
  source/frontend/src/utils/mapPropertyUtils.ts
  tools/TsModelGenerator/Specifications/PimsGenerationSpec.cs
Labels: release-management, 5.4

#4093 PSP-7879 Fix label width
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
Labels: enhancement

#4088 reorder lease tabs.
  source/frontend/src/features/mapSideBar/lease/detail/LeaseTabsContainer.tsx
Labels: bug

#4072 psp-7983 update db job to display logs in github.
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/depoy-prod-start.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
Labels: devops, 5.4

#4095 Psp 8624 - allow api startup without external services.
  source/backend/api/Helpers/Healthchecks/PimsCdogsHealthCheck.cs
  source/backend/api/Helpers/Healthchecks/PimsGeocoderHealthCheck.cs
  source/backend/api/Helpers/Healthchecks/PimsLtsaHealthcheck.cs
  source/backend/api/Helpers/Healthchecks/PimsMayanHealthCheck.cs
  source/backend/api/Pims.Api.csproj
  source/backend/api/Startup.cs
  source/frontend/package.json
Labels: bug, hotfix, 5.3

#4098 Backmerge test to dev
  source/backend/api/Helpers/Healthchecks/PimsCdogsHealthCheck.cs
  source/backend/api/Helpers/Healthchecks/PimsGeocoderHealthCheck.cs
  source/backend/api/Helpers/Healthchecks/PimsLtsaHealthcheck.cs
  source/backend/api/Helpers/Healthchecks/PimsMayanHealthCheck.cs
  source/backend/api/Startup.cs
Labels: release-management

#4096 updates to make commands based on dockerfile setup.
  Makefile
Labels: tech-debt

#4094 psp-8132 allow keycloak service to ignore keycloak user if null.
  source/backend/dal.keycloak/PimsKeycloakService.cs
  source/backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
Labels: bug

#4100 PSP-8194 Multipolygon test updates
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/tests/core/Entities/NtsGeometryHelper.cs
  source/backend/tests/unit/api/Controllers/LookupControllerTest.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/CoordinateTransformServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/api/Services/PropertyServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
Labels: unit-tests

#4099 Update pims health checks to support configuration based enable/disab…
  source/backend/api/Helpers/Healthchecks/PimsLtsaHealthcheck.cs
  source/backend/api/Startup.cs
  source/backend/api/appsettings.Development.json
  source/backend/api/appsettings.Local.json
  source/backend/api/appsettings.Test.json
  source/backend/api/appsettings.Uat.json
  source/backend/api/appsettings.json
  source/backend/dal/Options/AllHealthCheckOptions.cs
  source/backend/dal/Options/GeocoderHealthCheckOptions.cs
  source/backend/dal/Options/GeoserverHealthCheckOptions.cs
  source/backend/dal/Options/LtsaHealthCheckOptions.cs
  source/backend/dal/Options/PimsBaseHealthCheckOptions.cs
  source/backend/dal/Options/PmbcExternalApiHealthCheckOptions.cs
  source/backend/ltsa/ILtsaService.cs
Labels: enhancement, tech-debt

#4104 Psp 8635, psp-8636, psp-8638
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/useConfiguredMapLayers.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/mocks/mapFSM.mock.ts
  tools/geoserver/geoserver_data/psp/settings.xml
Labels: bug, hotfix, 5.3

#4105 Backmerge test to dev
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/useConfiguredMapLayers.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/mocks/mapFSM.mock.ts
  tools/geoserver/geoserver_data/psp/settings.xml
Labels: release-management

#4090 PSP-8574 : Ability to view non-PS and non-LIS Historical Number Types…
  source/backend/dal/Helpers/Extensions/PropertyExtensions.cs
Labels: enhancement

#4107 PSP-8183 : UI UX Clean Up - Filter Map - Moving Ownwership Flags to t…
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
Labels: enhancement

#4106 PSP-8575 : Lease/License – Improvements Tab (Other Improvements) Tool…
  source/frontend/src/features/leases/detail/LeasePages/improvements/AddImprovementsForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/AddImprovementsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/improvements/components/Improvement/Improvement.tsx
Labels: enhancement

#4101 PSP-8604: Add Lease checklist, changes on status elements
  testing/PIMS.Tests.Automation/Classes/Lease.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseInsurance.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePayments.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasesChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#4103 PSP-8597 : Subdivisions/Consolidation- Display of warning modal inste…
  source/frontend/src/components/propertySelector/search/PropertySelectorPidSearchContainer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorPidSearchContainer.tsx
Labels: enhancement

#4115 DB Scaffold IS-82
  source/backend/apimodels/Models/Concepts/Lease/LeaseMap.cs
  source/backend/apimodels/Models/Concepts/Lease/LeaseModel.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsLease.cs
  source/backend/entities/ef/PimsLeaseChklstItemType.cs
  source/backend/entities/ef/PimsLeaseHist.cs
  source/frontend/src/components/propertySelector/search/PropertySelectorPidSearchContainer.test.tsx
  source/frontend/src/models/api/generated/ApiGen_Concepts_Lease.ts
Labels: db-scaffold

#4114 PSP-8602: Volume common component area is still displaying 2 decimals
  source/frontend/src/components/measurements/VolumeForm.test.tsx
  source/frontend/src/components/measurements/VolumeForm.tsx
  source/frontend/src/components/measurements/VolumeView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
Labels: bug, 5.4

#4113 PSP-7490 PRD Feedback: Set default for GST on lease terms
  source/backend/apimodels/CodeTypes/LeaseAccountTypes.cs
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/TermPaymentsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/TermPaymentsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/modal/term/TermForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/payment/models.ts
  source/frontend/src/features/leases/models.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_LeaseAccountTypes.ts
Labels: enhancement, 5.4

#4108 PSP-8337 : UI UX Clean Up - Verbiage - Licence
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/AppRouter.tsx
  source/frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/ReferenceSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailTermInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailTermInformation.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/ImprovementsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/improvements/__snapshots__/ImprovementsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/Insurance.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/insurance/details/Insurance.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/AddLeaseTenantForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/SelectedTableHeader.tsx
  source/frontend/src/features/leases/detail/LeasePages/tenant/__snapshots__/AddLeaseTenantForm.test.tsx.snap
  source/frontend/src/features/leases/hooks/useLeaseExport.ts
  source/frontend/src/features/leases/list/LeaseListView.test.tsx
  source/frontend/src/features/leases/list/LeaseListView.tsx
  source/frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.test.tsx
  source/frontend/src/features/leases/list/LeaseSearchResults/LeaseSearchResults.tsx
  source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/propertyOperation/propertyOperationAssociationColumns.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakeUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
Labels: enhancement

#4119 PSP-8672: Disposed Property Label
  source/frontend/src/assets/scss/colors.scss
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
Labels: enhancement, 5.4

#4120 PSP-8603 : FT:Historical Files: System is throwing unknown bomb messa…
  source/backend/api/Areas/HistoricalNumber/HistoricalNumberController.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/tests/unit/api/Services/PropertyServiceTest.cs
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsContainer.tsx
Labels: bug

#4109 PSP-8566 : FT: Lease & Licences - Tenants: Select Tenants button gets…
  source/frontend/src/components/common/GenericModal.tsx
Labels: bug

#4110 Update mayan docker, and backend models to match 4.7 spec.
  source/backend/api/Services/DocumentService.cs
  source/backend/apimodels/Models/Mayan/Document/DocumentDetailModel.cs
  source/backend/apimodels/Models/Mayan/Document/DocumentTypeModel.cs
  source/backend/apimodels/Models/Mayan/Document/FileLatestModel.cs
  tools/mayan-edms/docker-compose.yml
Labels: 5.4

#4111 PSP-7498: UI/UX Clean Up - Contacts - View
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/features/contacts/contact/Person/PersonSubForm.tsx
  source/frontend/src/features/contacts/contact/create/Person/__snapshots__/CreatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/create/__snapshots__/CreateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/contact/detail/ContactInfoSubForm.tsx
  source/frontend/src/features/contacts/contact/detail/Container.tsx
  source/frontend/src/features/contacts/contact/detail/Organization.test.tsx
  source/frontend/src/features/contacts/contact/detail/Organization.tsx
  source/frontend/src/features/contacts/contact/detail/Person.test.tsx
  source/frontend/src/features/contacts/contact/detail/Person.tsx
  source/frontend/src/features/contacts/contact/detail/__snapshots__/Container.test.tsx.snap
  source/frontend/src/features/contacts/contact/detail/__snapshots__/Organization.test.tsx.snap
  source/frontend/src/features/contacts/contact/detail/__snapshots__/Person.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Organization/UpdateOrganizationForm.tsx
  source/frontend/src/features/contacts/contact/edit/Organization/__snapshots__/UpdateOrganizationForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/Person/__snapshots__/UpdatePersonForm.test.tsx.snap
  source/frontend/src/features/contacts/contact/edit/__snapshots__/UpdateContactContainer.test.tsx.snap
  source/frontend/src/features/contacts/styles.ts
Labels: enhancement, frontend, 5.4

#4121 Psp 5563 - correct exceptions bypassing error handling.
  source/backend/api/Pims.Api.csproj
  source/backend/api/Repositories/Mayan/MayanBaseRepository.cs
  source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  source/frontend/package.json
Labels: bug, hotfix, 5.3

#4123 PSP-8312 Start date not mandatory for non-active leases
  source/backend/api/Areas/Leases/Controllers/LeaseController.cs
  source/frontend/src/features/leases/add/AddLeaseForm.tsx
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/LeaseDetailSubForm.test.tsx
  source/frontend/src/features/leases/add/LeaseDetailSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/LeaseDetailSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/mocks/lookups.mock.ts
Labels: enhancement

#4122 Backmerge test to dev
  source/backend/api/Repositories/Mayan/MayanBaseRepository.cs
  source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
Labels: release-management, 5.4

#4118 PSP-7499: UI/UX Clean Up - Contact List
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/__snapshots__/ContactFilterComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
Labels: enhancement, frontend, 5.4

#4124 PSP-8703 Fix database upgrade GitHub action
  .github/workflows/ci-cd-pims-dev.yml
  .github/workflows/deploy-prod-start.yml
  .github/workflows/retag-dev-to-test.yml
  .github/workflows/retag-test-to-uat.yml
Labels: tech-debt, devops

#4125 Bump dev version - IS83
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: release-management

#4117 Psp-8018: For all files do not include a retired property on selection
  source/frontend/src/components/common/form/Input.tsx
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/propertySelector/MapClickMonitor.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorFormView.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.test.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/components/propertySelector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap
  source/frontend/src/components/propertySelector/search/mapPropertyColumns.ts
  source/frontend/src/components/propertySelector/search/mapPropertyColumns.tsx
  source/frontend/src/components/propertySelector/selectedPropertyList/SelectedPropertyRow.tsx
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionFileYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.test.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/models/AddDispositionFormYupSchema.ts
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchFileYupSchema.ts
  source/frontend/src/features/mapSideBar/research/add/ResearchProperties.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdatePropertiesYupSchema.ts
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.test.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/hooks/layer-api/useLayerQuery.test.tsx
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/models/layers/motDistrictBoundary.ts
  source/frontend/src/models/layers/motRegionalBoundary.ts
  source/frontend/src/models/layers/pimsPropertyLocationView.ts
  source/frontend/src/utils/mapPropertyUtils.ts
  source/frontend/vite.config.ts
Labels: enhancement, 5.4

#4126 add pagination to management contacts. Style updates to pagination in…
  source/frontend/src/components/Table/PageSizeSelector.tsx
  source/frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactList.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/__snapshots__/PropertyContactListView.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
Labels: enhancement, ui/ux

#4127 Psp 8584 - footer styling
  source/frontend/src/assets/scss/_variables.scss
  source/frontend/src/components/layout/Footer/Footer.tsx
  source/frontend/src/components/layout/Footer/__snapshots__/Footer.test.tsx.snap
Labels: enhancement, ui/ux

#4128 PSP-8409 Takes UI/UX cleanup
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/__snapshots__/TakesDetailView.test.tsx.snap
  source/frontend/src/mocks/takes.mock.ts
Labels: enhancement, ui/ux, 5.4

#4129 PSP-8686 : Ability to search for non-PS and non-LIS Historical Number…
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/tests/unit/dal/Repositories/LeaseRepositoryTest.cs
Labels: enhancement

#4130 PSP-8707: IS83 Automated test cases changes
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/ManageUsers.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyPIMSFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionConsolidationProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#4116 Psp-7862 collapse map side bar
  source/frontend/src/assets/images/fence.svg
  source/frontend/src/assets/images/subdivisionconsolidation.svg
  source/frontend/src/components/common/buttons/ExpandCollapseButton.tsx
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/common/styles.ts
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/components/layout/SideNavBar/styles.ts
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/styles.ts
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/MapSideBar.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationContainer.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.tsx
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/context/sidebarContext.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainerView.tsx
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/layout/MapSideBarLayout.test.tsx
  source/frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  source/frontend/src/features/mapSideBar/layout/__snapshots__/MapSideBarLayout.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/project/ProjectContainerView.tsx
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.tsx
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/ResearchView.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionContainer.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/mocks/mapFSM.mock.ts
Labels: enhancement, 5.4

#4134 PSP-7499: Minor changes on the responsiveness of the Contacts List Filter to accomodate the Select Contacts view
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/__snapshots__/ContactFilterComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
Labels: enhancement, 5.4

#4139 update github action name based on correction in dev.
  .github/workflows/deploy-prod-start.yml
Labels: release-management

#4143 backmerge test to dev
  source/backend/dal/Repositories/TakeRepository.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsLeasePayment.cs
  source/backend/entities/ef/PimsLeasePaymentHist.cs
  source/backend/entities/ef/PimsLeasePeriod.cs
  source/backend/entities/ef/PimsLeasePeriodHist.cs
  source/backend/entities/ef/PimsPropertyAcquisitionFile.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionTakes.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
Labels: release-management
