Repository bcgov/PSP, pull requests merged in 2025-05, with the labels that each got.

#4777 PSP-10220 Management File Documents
  source/backend/api/Areas/Documents/DocumentRelationshipController.cs
  source/backend/api/Constants/FileType.cs
  source/backend/api/Services/DocumentFileService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/api/Services/IDocumentFileService.cs
  source/backend/apimodels/CodeTypes/DocumentRelationType.cs
  source/backend/apimodels/Models/Concepts/Document/DocumentRelationshipMap.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/Interfaces/IManagementFileDocumentRepository.cs
  source/backend/dal/Repositories/Interfaces/IPropertyActivityDocumentRepository.cs
  source/backend/dal/Repositories/ManagementFileDocumentRepository.cs
  source/backend/dal/Repositories/PropertyActivityDocumentRepository.cs
  source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  source/backend/tests/unit/dal/Repositories/DispositionFileDocumentRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ManagementFileDocumentRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ManagementFilePropertyRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/PropertyActivityDocumentRepositoryTest.cs
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/PropertyActivityDetailView.tsx
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_DocumentRelationType.ts
Labels: enhancement

#4781 PSP-10171 : FT-REG: Lease and Licenses - When user inserts the Admini…
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
Labels: bug

#4778 psp-10042 correct ability to delete documents.
  source/backend/api/Services/DocumentFileService.cs
Labels: bug

#4783 PSP-10056, PSP-10302: Toast UI/UX +Changing green toast for blue toast when BCTFA .CSV is uploaded
  source/frontend/src/App.tsx
  source/frontend/src/assets/scss/App.scss
  source/frontend/src/constants/toasts.ts
  source/frontend/src/features/mapSideBar/shared/detail/__snapshots__/PropertyFileContainer.test.tsx.snap
  source/frontend/src/hooks/repositories/useBctfaOwnershipRepository.ts
Labels: enhancement, 5.10

#4779 Psp 10329 fix
  source/frontend/src/features/properties/map/MapContainer.tsx
Labels: bug

#4785 PSP-10114: Error modal when a payee that is associated to a Comp Req is deleted from the lease.
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderContainer.tsx
Labels: enhancement, 5.10

#4786 HOTFIX: psp-10364 rename strata lot to common property.
  source/frontend/src/components/maps/leaflet/LayerPopup/MultiplePropertyPopupView.tsx
  source/frontend/src/features/mapSideBar/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
Labels: enhancement, hotfix, 5.9

#4787 psp-10349 | common property fixes
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/maps/leaflet/LayerPopup/MultiplePropertyPopupView.tsx
Labels: bug, hotfix

#4791 Backmerge test to dev
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/Interfaces/IPropertyRepository.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/frontend/src/components/maps/leaflet/LayerPopup/MultiplePropertyPopupView.tsx
Labels: alignment

#4766 PSP-10098 Track keycloak events with browser telemetry
  source/frontend/index.html
  source/frontend/public/config.js
  source/frontend/public/tenants/tenant.json
  source/frontend/src/config.ts
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/index.tsx
  source/frontend/src/telemetry/config.ts
  source/frontend/src/telemetry/traces.ts
  source/frontend/src/telemetry/traces/SpanEnrichment.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
  source/frontend/src/utils/getKeycloakEventHandler.test.ts
  source/frontend/src/utils/getKeycloakEventHandler.ts
  tools/cicd/scripts/gen-env-files.sh
Labels: enhancement

#4793 Increment DEV version - IS104
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4794 make management files icon visible.
  source/frontend/src/features/management/list/ManagementListView.tsx
  source/frontend/src/features/management/list/__snapshots__/ManagementListView.test.tsx.snap
Labels: bug

#4797 Backmerge test to dev
  source/frontend/src/components/maps/MapLeafletView.tsx
Labels: release-management

#4795 psp-10456 updates to strata common property calculation.
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/MultiplePropertyPopupView.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.tsx
  source/frontend/src/utils/propertyUtils.test.ts
  source/frontend/src/utils/propertyUtils.ts
Labels: enhancement

#4799 PSP-10468: FT-REG: React error on Manage Contacts
  source/frontend/src/AppRouter.tsx
  source/frontend/src/features/contacts/list/ContactListPage.tsx
Labels: bug, 5.10

#4800 PSP-10160: Contact Modal aesthetic changes.
  source/frontend/src/components/common/form/RadioGroup.tsx
  source/frontend/src/components/contact/ContactManagerModal.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/__snapshots__/ContactFilterComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/AddLeaseStakeholderForm.test.tsx
Labels: enhancement, 5.10

#4801 PSP-10474 : Management File - Migrate Program Type to Purpose Type
  source/backend/api/Controllers/LookupController.cs
  source/backend/apimodels/CodeTypes/ManagementFilePurposeTypes.cs
  source/backend/apimodels/Models/Concepts/ManagementFile/ManagementFileMap.cs
  source/backend/apimodels/Models/Concepts/ManagementFile/ManagementFileModel.cs
  source/backend/dal/Repositories/Interfaces/ILookupRepository.cs
  source/backend/dal/Repositories/LookupRepository.cs
  source/backend/dal/Repositories/ManagementFileRepository.cs
  source/backend/entities/Partials/ManagementFileProgramType.cs
  source/backend/entities/Partials/ManagementFilePurposeType.cs
  source/backend/entities/ef/PimsManagementFileProgramType.cs
  source/backend/tests/core/Entities/ManagementFileHelper.cs
  source/backend/tests/unit/dal/Repositories/ManagementFileRepositoryTest.cs
  source/frontend/src/constants/API.ts
  source/frontend/src/features/management/list/ManagementFilter/ManagementFilter.test.tsx
  source/frontend/src/features/management/list/ManagementFilter/__snapshots__/ManagementFilter.test.tsx.snap
  source/frontend/src/features/management/list/ManagementListView.tsx
  source/frontend/src/features/management/list/ManagementSearchResults/__snapshots__/ManagementSearchResults.test.tsx.snap
  source/frontend/src/features/management/list/ManagementSearchResults/columns.tsx
  source/frontend/src/features/management/list/__snapshots__/ManagementListView.test.tsx.snap
  source/frontend/src/features/management/list/models.ts
  source/frontend/src/features/mapSideBar/management/__snapshots__/ManagementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/add/__snapshots__/AddManagementContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/form/ManagementForm.tsx
  source/frontend/src/features/mapSideBar/management/models/AddManagementFormYupSchema.ts
  source/frontend/src/features/mapSideBar/management/models/ManagementFormModel.ts
  source/frontend/src/features/mapSideBar/management/tabs/__snapshots__/ManagementFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/ManagementSummaryView.tsx
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/__snapshots__/ManagementSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/update/UpdateManagementForm.test.tsx
  source/frontend/src/features/mapSideBar/management/update/UpdateManagementForm.tsx
  source/frontend/src/features/mapSideBar/management/update/__snapshots__/UpdateManagementForm.test.tsx.snap
  source/frontend/src/mocks/lookups.mock.ts
  source/frontend/src/mocks/managementFiles.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_ManagementFilePurposeTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_ManagementFile.ts
Labels: db-migration-correction

#4802 PSP-10287: Clean Up - Date Pop-up - uncover
  source/frontend/src/components/common/form/FastDatePicker.tsx
Labels: enhancement, 5.10

#4810 PSP-103100: Management File automated test cases, Leases Team
  testing/PIMS.Tests.Automation/Classes/Lease.cs
  testing/PIMS.Tests.Automation/Classes/ManagementFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/ManagementFiles.feature
  testing/PIMS.Tests.Automation/Features/ManagementFiles.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/ManagementDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchManagement.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedTeamMembers.cs
  testing/PIMS.Tests.Automation/Reports/ReportUtil.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ManagementFileSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#4812 Psp 10275 update property (name and activity business rule)
  source/backend/api/Services/ManagementFileService.cs
  source/backend/apimodels/Models/Concepts/ManagementFile/ManagementFilePropertyMap.cs
  source/backend/tests/unit/api/Services/ManagementFileServiceTest.cs
Labels: enhancement, 5.10

#4815 fix copy/paste error on add management tab names.
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
Labels: bug

#4818 psp-10356 add missing org tenant include to correct fiscal report.
  source/backend/dal/Repositories/LeaseRepository.cs
Labels: bug

#4817 psp-10465 correct toast close button issues.
  source/frontend/src/App.tsx
  source/frontend/src/assets/scss/App.scss
Labels: bug, 5.10

#4813 PSP-10352 Property Notes
  source/backend/api/Areas/Notes/Controllers/NoteController.cs
  source/backend/api/Constants/NoteType.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/INoteService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/ManagementFileService.cs
  source/backend/api/Services/NoteService.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/apimodels/Models/Concepts/Note/EntityNoteModelMap.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/AcquisitionFileNoteRepository.cs
  source/backend/dal/Repositories/DispositionFileNoteRepository.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/IEntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/INoteRelationshipRepository.cs
  source/backend/dal/Repositories/LeaseNoteRepository.cs
  source/backend/dal/Repositories/ManagementFileNoteRepository.cs
  source/backend/dal/Repositories/ProjectNoteRepository.cs
  source/backend/dal/Repositories/PropertyNoteRepository.cs
  source/backend/dal/Repositories/ResearchFileNoteRepository.cs
  source/backend/entities/Partials/AcquisitionFileNote.cs
  source/backend/entities/Partials/DispositionFileNote.cs
  source/backend/entities/Partials/LeaseNote.cs
  source/backend/entities/Partials/ManagementFileNote.cs
  source/backend/entities/Partials/PimsNoteRelationship.cs
  source/backend/entities/Partials/ProjectNote.cs
  source/backend/entities/Partials/PropertyNote.cs
  source/backend/entities/Partials/ResearchFileNote.cs
  source/backend/tests/core/Entities/NoteHelper.cs
  source/backend/tests/unit/api/Controllers/Note/NoteControllerTest.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/api/Services/ManagementFileServiceTest.cs
  source/backend/tests/unit/api/Services/NoteServiceTest.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/NoteRepositoryTest.cs
  source/frontend/src/constants/noteTypes.ts
  source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.test.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
Labels: enhancement, 5.10

#4820 PSP-8837 : Management Tab - Activities List Table View
  source/backend/dal/Repositories/PropertyActivityRepository.cs
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesList.tsx
Labels: enhancement

#4822 PSP-10478 : FT-REG: Search Property tab - When a user looks for a pro…
  source/frontend/src/components/Table/Table.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.tsx
Labels: bug

#4819 PSP-10370 : Activity Management List View
  source/backend/api/Areas/Management/ActivitySearchController.cs
  source/backend/api/Areas/Management/Models/ManagementActivityFilterModel.cs
  source/backend/api/Areas/Reports/Controllers/ManagementActivityController.cs
  source/backend/api/Areas/Reports/Mapping/Management/ManagementActivityReportMap.cs
  source/backend/api/Areas/Reports/Models/Management/ManagementActivityReportModel.cs
  source/backend/api/Services/IManagementActivityService.cs
  source/backend/api/Services/ManagementActivityService.cs
  source/backend/api/Startup.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyActivityMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyActivityModel.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/Repositories/Interfaces/IManagementActivityRepository.cs
  source/backend/dal/Repositories/ManagementActivityRepository.cs
  source/backend/entities/Models/ManagementActivityFilter.cs
  source/frontend/src/AppRouter.tsx
  source/frontend/src/components/common/List/ExpandableFileProperties.tsx
  source/frontend/src/components/layout/SideNavBar/Management.tsx
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  source/frontend/src/features/disposition/list/DispositionSearchResults/columns.tsx
  source/frontend/src/features/management/activities/list/ManagementActivitiesListView.tsx
  source/frontend/src/features/management/activities/list/filter/ActivitiesFilter.tsx
  source/frontend/src/features/management/activities/list/searchResults/ManagementActivitiesSearchResults.tsx
  source/frontend/src/features/management/activities/list/searchResults/columns.tsx
  source/frontend/src/features/management/activities/models/ManagementActivityFilterModel.ts
  source/frontend/src/features/management/activities/models/ManagementActivitySearchResultModel.ts
  source/frontend/src/features/management/hooks/useManagementActivityExport.ts
  source/frontend/src/features/management/list/ManagementSearchResults/ManagementSearchResults.test.tsx
  source/frontend/src/features/management/list/ManagementSearchResults/__snapshots__/ManagementSearchResults.test.tsx.snap
  source/frontend/src/features/management/list/ManagementSearchResults/columns.tsx
  source/frontend/src/features/management/list/__snapshots__/ManagementListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/models.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/models.ts
  source/frontend/src/hooks/pims-api/useApiManagementActivities.ts
  source/frontend/src/mocks/PropertyManagementActivity.mock.ts
  source/frontend/src/mocks/managementFiles.mock.ts
  source/frontend/src/models/api/ManagementActivityFilter.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyActivity.ts
Labels: enhancement
