Repository bcgov/PSP, pull requests merged in 2025-02, with the labels that each got.

#4633 HOTFIX: PSP-9939 Layer control screen is displaying blank
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.test.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersMenu.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Layers/useConfiguredMapLayers.tsx
Labels: bug, hotfix, 5.8

#4634 Backmerge test to dev
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.test.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersMenu.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Layers/useConfiguredMapLayers.tsx
Labels: alignment

#4631 PSP-9932: PIMS Files Tab - Icons & Header
  source/frontend/src/assets/images/acquisition-grey-icon.svg
  source/frontend/src/assets/images/admin-grey-icon.svg
  source/frontend/src/assets/images/contact-grey-icon.svg
  source/frontend/src/assets/images/disposition-grey-icon.svg
  source/frontend/src/assets/images/home-grey-icon.svg
  source/frontend/src/assets/images/lease-grey-icon.svg
  source/frontend/src/assets/images/projects-grey-icon.svg
  source/frontend/src/assets/images/research-grey-icon.svg
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
Labels: enhancement, 5.8

#4632 PSP-9810: Canceling an Acquisition file with in-progress takes validation
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
Labels: enhancement, 5.8

#4629 psp-9551 remove lease notes (currently called comments) from the frontend.
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailNotes.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/models.ts
Labels: enhancement

#4630 PSP-9937: IS98 Updating automation test cases
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/ManageUsers.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchDispositionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProjects.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedCompensations.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#4636 Updated cache to use version 4
  .github/workflows/credentials-scan.yml
Labels: tech-debt

#4635 V5.7.3-96.22 Hotfix release
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/DocumentQueueService.cs
  source/backend/scheduler/Startup.cs
  source/backend/tests/unit/api/Services/DocumentQueueServiceTest.cs
  source/frontend/package.json
  source/frontend/src/components/maps/leaflet/Layers/util.test.tsx
  source/frontend/src/hooks/layer-api/layerUtils.ts
Labels: release-management

#4639 PSP-9095 User is not able to delete the requisition
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/backend/tests/unit/dal/Repositories/CompensationRequisitionRepositoryTest.cs
Labels: bug, 5.8

#4641 PSP-9890: FT-AUTO Task - Implement automated report and screenshots when test fails
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/Reports/ReportUtil.cs
  testing/PIMS.Tests.Automation/Reports/TestHooks.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/GenericSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LoginSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/NotesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/SubdivisionsConsolidationsSteps.cs
Labels: test-scripts

#4638 PSP-9563 : Lease/Licence- Duplicate Files- Hide them in default
  source/backend/apimodels/Models/Concepts/Property/AssociationMap.cs
  source/backend/apimodels/Models/Concepts/Property/AssociationModel.cs
  source/frontend/src/features/leases/detail/LeaseEditButton.tsx
  source/frontend/src/features/leases/detail/LeasePages/LeasePageForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/LeasePageForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/__snapshots__/LeasePageForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/LeaseAssociationContent.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
  source/frontend/src/models/api/generated/ApiGen_Concepts_Association.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompReqPayee.ts
Labels: enhancement

#4609 Psp 1362
  source/backend/api/Pims.Api.csproj
  source/backend/api/Repositories/Cdogs/CdogsAuthRepository.cs
  source/backend/api/Repositories/Cdogs/CdogsBaseRepository.cs
  source/backend/api/Repositories/Cdogs/CdogsRepository.cs
  source/backend/api/Repositories/Mayan/MayanAuthRepository.cs
  source/backend/api/Repositories/Mayan/MayanBaseRepository.cs
  source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  source/backend/api/Repositories/Mayan/MayanMetadataRepository.cs
  source/backend/api/Startup.cs
  source/backend/api/appsettings.json
  source/backend/core.api/Pims.Core.Api.csproj
  source/backend/core.api/Repositories/RestCommon/BaseRestRepository.cs
  source/backend/core/Http/HttpRequestClient.cs
  source/backend/core/Http/IOpenIdConnectRequestClient.cs
  source/backend/core/Http/OpenIdConnectRequestClient.cs
  source/backend/core/Options/PollyOptions.cs
  source/backend/core/Pims.Core.csproj
  source/backend/dal.keycloak/Pims.Dal.Keycloak.csproj
  source/backend/dal/Pims.Dal.csproj
  source/backend/keycloak/Pims.Keycloak.csproj
  source/backend/ltsa/Pims.Ltsa.csproj
  source/backend/scheduler/Repositories/PimsBaseRepository.cs
  source/backend/scheduler/Repositories/PimsDocumentQueueRepository.cs
  source/backend/scheduler/Startup.cs
  source/backend/scheduler/appsettings.json
  source/backend/tests/unit/api/Repositories/BaseRestRepositoryTest.cs
  source/backend/tests/unit/api/Repositories/MayanAuthRepositoryTest.cs
  source/backend/tests/unit/api/Repositories/MayanDocumentRepositoryTest.cs
  source/backend/tests/unit/api/Repositories/MayanMetadataRepositoryTest.cs
  source/backend/tests/unit/dal/Core/Http/OpenIdConnectRequestClientTest.cs
  source/backend/tests/unit/dal/Libraries/Geocoder/ServiceCollectionExtensionsTest.cs
  source/backend/tests/unit/dal/Libraries/Ltsa/LtsaServiceCollectionTest.cs
  tools/keycloak/sync/Client/PimsRequestClient.cs
  tools/keycloak/sync/Client/RequestClient.cs
  tools/keycloak/sync/Pims.Tools.Keycloak.Sync.csproj
  tools/keycloak/sync/Program.cs
  tools/keycloak/sync/appsettings.json
Labels: enhancement

#4643 PSP-9921 : UI UX Clean Up - Icons - Collapsible
  source/frontend/src/components/layout/SideNavBar/SideTray.tsx
  source/frontend/src/features/disposition/list/DispositionListView.tsx
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainerView.tsx
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/layout/MapSideBarLayout.tsx
  source/frontend/src/features/mapSideBar/layout/__snapshots__/MapSideBarLayout.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.tsx
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/ResearchView.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
  source/frontend/src/features/research/list/ResearchListView.tsx
  source/frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
Labels: enhancement

#4647 psp-9813 ensure error messages from backend display properly.
  source/frontend/src/features/documents/ComposedDocument.ts
Labels: bug

#4646 PSP-9915 : FT-REG: Lease & License - 404 errors are displayed when Co…
  source/frontend/src/features/mapSideBar/acquisition/models/LeaseStakeholderModel.ts
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeTypeModel.ts
  source/frontend/src/features/mapSideBar/compensation/models/CompensationRequisitionFormModel.ts
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.tsx
Labels: bug

#4649 PSP-9997 : FT:Lease&License: The chip number on the lease&license hea…
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.tsx
Labels: bug

#4648 Psp 9940 - correct issue with map display when jumping to boundaries
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
Labels: bug

#4650 PSP-9912 : FT-REG: Compensation requisition - When a stakeholder, owner or acquisition team is deleted while being attached to a compensation requisition as a payee, PIMS displays a vague 400 error and in 2 different ways.
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderContainer.tsx
Labels: bug, 5.8

#4652 PSP-9965: Extent Report on Github actions
  .github/workflows/integration-test.yml
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/DispositionOfferSale.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedCompensations.cs
  testing/PIMS.Tests.Automation/Reports/ReportUtil.cs
  testing/PIMS.Tests.Automation/Reports/TestHooks.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
Labels: test-scripts

#4651 PSP-9923, PSP-9924 Fix UTC dates in Research Files and Notes
  source/backend/api/Areas/Research/Controllers/ResearchFileController.cs
  source/backend/api/Areas/Research/Controllers/SearchController.cs
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/components/Table/DateCell.test.tsx
  source/frontend/src/components/Table/DateCell.tsx
  source/frontend/src/features/notes/NoteContainer.test.tsx
  source/frontend/src/features/notes/detail/NoteDetailsFormModal.test.tsx
  source/frontend/src/features/notes/hooks/useUpdateNotesFormManagement.test.tsx
  source/frontend/src/features/notes/list/NoteResults/NoteResults.test.tsx
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/columns.tsx
  source/frontend/src/features/notes/update/UpdateNoteContainer.test.tsx
  source/frontend/src/features/notes/update/UpdateNoteFormModal.test.tsx
  source/frontend/src/features/projects/list/ProjectSearchResults/ProjectSearchResults.test.tsx
  source/frontend/src/features/projects/list/ProjectSearchResults/__snapshots__/ProjectSearchResults.test.tsx.snap
  source/frontend/src/features/projects/list/ProjectSearchResults/columns.tsx
  source/frontend/src/features/research/list/ResearchListView.test.tsx
  source/frontend/src/features/research/list/ResearchListView.tsx
  source/frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.test.tsx
  source/frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.tsx
  source/frontend/src/features/research/list/ResearchSearchResults/__snapshots__/ResearchSearchResults.test.tsx.snap
  source/frontend/src/features/research/list/models.ts
  source/frontend/src/hooks/pims-api/useApiResearchFile.ts
  source/frontend/src/hooks/repositories/useNoteRepository.test.tsx
  source/frontend/src/mocks/noteResponses.mock.ts
  source/frontend/src/mocks/researchFile.mock.ts
Labels: bug, 5.8

#4645 PSP-9907 Support legacy payee
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompReqPayeeMap.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompReqPayeeModel.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/models/CompensationRequisitionFormModel.ts
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompReqPayee.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompensationRequisition.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
Labels: enhancement, 5.8

#4655 Bump version 100
  source/backend/api/Pims.Api.csproj
  source/backend/scheduler/appsettings.json
  source/frontend/package-lock.json
  source/frontend/package.json
  tools/mayan_sync_helper/json_output/mayan_sync.json
Labels: devops

#4656 PSP-10013 : New wording for the modal and tooltip ( PSP-9563)
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.tsx
Labels: enhancement

#4658 PSP-10014 : FT:Lease&License: Override modal is populated every time …
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/entities/Partials/LeaseRenewal.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
Labels: bug

#4657 PSP-9811: Contacts - Search by Name text box default state descriptor
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/__snapshots__/ContactFilterComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
Labels: enhancement, 5.8

#4662 DB Scripts - Fix alphanumeric sorting for folders S100 and greater
  source/database/mssql/scripts/dbscripts/deploy.sh
  source/database/mssql/scripts/dbscripts/generate_master_sql.sh
  source/database/mssql/scripts/dbscripts/setup.sh
  source/database/mssql/scripts/dbscripts/upgrade.sh
Labels: bug, devops

#4665 PSP-10051 : FT:Lease&License: Acknowledgement modal verbiage is popul…
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.tsx
Labels: bug

#4663 Psp 10042 fix error when trying to delete documents with no document queue.
  source/backend/api/Services/DocumentFileService.cs
  source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
Labels: bug

#4664 Psp 10048 - research final file edit behaviour corrections.
  source/frontend/src/features/mapSideBar/research/tabs/ResearchTabsContainer.tsx
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/details/ResearchSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/details/ResearchSummaryView.tsx
Labels: bug

#4661 psp-10029 use debounce, memo to limit renders of clusters/markers. Update cluster library.
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/maps/hooks/useSupercluster.ts
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/features/properties/map/MapContainer.test.tsx
Labels: bug, enhancement

#4667 Psp 9943 highway layer url display
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersMenu.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/LayersControl/data.ts
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/__snapshots__/LayerPopupContainer.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/constants.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorPidSearchView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
  source/frontend/src/hooks/repositories/mapLayer/useHighwayLayer.tsx
  source/frontend/src/mocks/mockISSResult.ts
  source/frontend/src/mocks/msw/handlers.ts
Labels: enhancement

#4670 PSP-10062: Reqnroll library changes
  testing/PIMS.Tests.Automation/Data/ExcelDataContext.cs
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/AdminTools.feature.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/Features/SubdivisionConsolidation.feature.cs
  testing/PIMS.Tests.Automation/ImplicitUsings.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/Reports/ReportUtil.cs
  testing/PIMS.Tests.Automation/Reports/TestHooks.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/NotesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/SubdivisionsConsolidationsSteps.cs
Labels: test-scripts

#4669 Psp 9916 - multiple payees for lease/license
  source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/ICompensationRequisitionService.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs
  source/backend/tests/unit/dal/Repositories/CompensationRequisitionRepositoryTest.cs
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/features/mapSideBar/acquisition/models/LeaseStakeholderModel.ts
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
  source/frontend/src/features/mapSideBar/compensation/CompensationRequisitionTrayView.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/models/CompensationRequisitionFormModel.ts
  source/frontend/src/features/mapSideBar/compensation/update/CompensationRequisitionYupSchema.ts
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/hooks/pims-api/useApiRequisitionCompensations.ts
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/mocks/msw/handlers.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompReqAcqPayee.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompReqLeasePayee.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompensationRequisition.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: enhancement

#4672 PSP-10035: IS100 Automation Test changes
  testing/PIMS.Tests.Automation/.gitignore
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedCompensations.cs
  testing/PIMS.Tests.Automation/Reports/TestHooks.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts
