Repository bcgov/PSP, pull requests merged in 2025-09, with the labels that each got.

#4992 PSP-10782 Tech Debt: Cleanup property name generation and remove IMapProperty
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.tsx
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.test.tsx
  source/frontend/src/components/propertySelector/map/PropertyMapSelectorSubForm.tsx
  source/frontend/src/components/propertySelector/map/__snapshots__/PropertyMapSelectorSubForm.test.tsx.snap
  source/frontend/src/components/propertySelector/models.ts
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.tsx
  source/frontend/src/components/propertySelector/selectedPropertyList/SelectedPropertyRow.test.tsx
  source/frontend/src/components/propertySelector/selectedPropertyList/SelectedPropertyRow.tsx
  source/frontend/src/features/leases/detail/LeaseHeaderAddresses.tsx
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.test.tsx
  source/frontend/src/features/leases/shared/propertyPicker/__snapshots__/LeasePropertySelector.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/SelectedPropertyRow.test.tsx
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/SelectedPropertyRow.tsx
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationContainer.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/management/form/ManagementPropertiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/ActivitiesTab.test.tsx
  source/frontend/src/features/mapSideBar/property/ComposedProperty.ts
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/research/add/ResearchProperties.test.tsx
  source/frontend/src/features/mapSideBar/shared/models.ts
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionContainer.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.test.tsx
  source/frontend/src/hooks/repositories/useComposedProperties.ts
  source/frontend/src/hooks/useInitialMapSelectorProperties.ts
  source/frontend/src/utils/mapPropertyUtils.test.tsx
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: tech-debt, 5.13

#4999 psp-10818 allow users to add property to an open file (new, existing).
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/management/add/AddManagementContainer.test.tsx
  source/frontend/src/features/mapSideBar/management/add/AddManagementContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/ResearchProperties.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/hooks/useEditPropertiesMode.ts
  source/frontend/src/hooks/useEditPropertiesNotifier.test.ts
  source/frontend/src/hooks/useEditPropertiesNotifier.ts
  source/frontend/src/models/generate/GenerateForm12.ts
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: enhancement, 5.13

#5006 PSP-10814: UI/UX: Maintain right panel width consistency
  source/frontend/src/features/rightSideLayout/RightSideLayout.tsx
Labels: enhancement, 5.13

#5004 PSP-10834 : Finalize "add property to file logic"
  source/frontend/src/components/common/form/FormGuide/FormGuideView.tsx
  source/frontend/src/components/propertySelector/selectedPropertyList/SelectedPropertyHeaderRow.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseForm.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/leases/shared/propertyPicker/__snapshots__/LeasePropertySelector.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/add/__snapshots__/AddManagementContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/form/ManagementPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/management/form/__snapshots__/ManagementPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddPropertiesGuide.tsx
  source/frontend/src/features/mapSideBar/research/add/ResearchProperties.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchFileNameGuide.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/__snapshots__/UpdateSummaryContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/__snapshots__/UpdateSummaryForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/AddPropertiesGuide.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
  source/frontend/src/hooks/useEditPropertiesNotifier.ts
  source/frontend/src/utils/propertyUtils.ts
Labels: enhancement

#5012 psp-10181 & psp-4160 | Added new generation forms
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/AcquisitionGenerateContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/__snapshots__/AcquisitionGenerateContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateNotice.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateResearchNotice.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/modals/GenerateLetterRecipientsModal.tsx
  source/frontend/src/features/mapSideBar/acquisition/models/DetailAcquisitionFileOwner.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryView.tsx
  source/frontend/src/features/mapSideBar/research/ResearchGenerateContainer.tsx
  source/frontend/src/features/mapSideBar/shared/generateForm/NoticeGenerateContainer.tsx
  source/frontend/src/features/mapSideBar/shared/generateForm/NoticeSelectorModal.tsx
  source/frontend/src/models/generate/GenerateNotice.ts
  source/frontend/src/models/generate/GeneratePerson.ts
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_BOUNDARY_LITE_VW/featuretype.xml
Labels: enhancement

#5008 Psp 10637 ensure that file -> property -> activity edits do not redirect to property - activity screens
  source/backend/scheduler/Startup.cs
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.tsx
  source/frontend/src/features/mapSideBar/layer/LayerTabContainer.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseView.tsx
  source/frontend/src/features/mapSideBar/management/ManagementView.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditContainer.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/list/AdHocSummaryActivitiesContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/PropertyActivityDetailContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/PropertyActivityDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesListContainer.tsx
  source/frontend/src/features/mapSideBar/research/ResearchView.tsx
  source/frontend/src/features/mapSideBar/router/FilePropertyRouter.tsx
  source/frontend/src/features/mapSideBar/router/PropertyActivityRouter.tsx
  source/frontend/src/features/mapSideBar/shared/sidebarPathGenerator.ts
  source/frontend/src/features/mapSideBar/shared/usePropertyIndexFromUrl.tsx
  source/frontend/src/hooks/useFilePropertyIdFromUrl.test.tsx
  source/frontend/src/hooks/useFilePropertyIdFromUrl.tsx
  source/frontend/src/hooks/useManagementPropertyIdFromUrl.test.tsx
  source/frontend/src/hooks/useManagementPropertyIdFromUrl.ts
Labels: enhancement, 5.13

#5010 PSP-10860 : FT:AcquisitionFile: New workflow is not populated under "Properties to include in this file" on the create screen of Acq file
  source/frontend/src/components/common/form/FormGuide/FormGuideContainer.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/__snapshots__/LeasePropertySelector.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/add/__snapshots__/AddManagementContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/form/__snapshots__/ManagementPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchFileNameGuide.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/__snapshots__/UpdateSummaryContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/__snapshots__/UpdateSummaryForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/AddPropertiesGuide.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
Labels: bug

#5013 PSP-10831 Activity list view invoice report
  source/backend/api/Areas/Reports/Controllers/ManagementActivityController.cs
  source/backend/api/Areas/Reports/Models/Management/ManagementActivityInvoicesReportModel.cs
  source/backend/api/Areas/Reports/Models/Management/ManagementActivityOverviewReportModel.cs
  source/backend/api/Services/IManagementActivityService.cs
  source/backend/api/Services/ManagementActivityService.cs
  source/backend/apimodels/Models/Concepts/ManagementActivity/ManagementActivityModel.cs
  source/backend/dal/Repositories/Interfaces/IManagementActivityRepository.cs
  source/backend/dal/Repositories/ManagementActivityRepository.cs
  source/backend/dal/Repositories/ManagementFileRepository.cs
  source/backend/tests/api/Models/ManagementActivityInvoicesReportModelTest.cs
  source/backend/tests/api/Models/ManagementActivityOverviewReportModelTest.cs
  source/backend/tests/core/DatabaseHelper.cs
  source/backend/tests/core/Entities/ManagementActivityHelper.cs
  source/backend/tests/dal/Repositories/ManagementActivityRepositoryTest.cs
  source/frontend/src/features/management/activities/list/ManagementActivitiesListView.test.tsx
  source/frontend/src/features/management/activities/list/ManagementActivitiesListView.tsx
  source/frontend/src/features/management/activities/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/management/hooks/useManagementActivityExport.ts
  source/frontend/src/features/management/list/ManagementListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionOwnersSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditContainer.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/InvoiceTotalsForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesListContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesListView.test.tsx
  source/frontend/src/mocks/managementActivity.mock.ts
Labels: enhancement, 5.13
