Repository bcgov/PSP, pull requests merged in 2025-07, with the labels that each got.

#4878 document queue refactor - resiliency update
  source/backend/api/Areas/Documents/DocumentQueueController.cs
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/DocumentQueueService.cs
  source/backend/api/Services/DocumentSyncService.cs
  source/backend/api/Services/IDocumentQueueService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Pims.Dal.csproj
  source/backend/dal/Repositories/DocumentQueueRepository.cs
  source/backend/dal/Repositories/Interfaces/IDocumentQueueRepository.cs
  source/backend/scheduler/Services/DocumentQueueService.cs
  source/backend/tests/api/Services/DocumentQueueServiceTest.cs
  source/backend/tests/dal/Repositories/DocumentQueueRepositoryTest.cs
  source/backend/tests/scheduler/Services/DocumentQueueServiceTests.cs
Labels: enhancement, 5.11

#4879 PSP-9090 Geocoder autocomplete parameter for direct match
  source/backend/api/Areas/Tools/Controllers/GeocoderController.cs
  source/backend/geocoder/Parameters/AddressesParameters.cs
  source/backend/geocoder/Parameters/BaseParameters.cs
  source/backend/tests/dal/Libraries/Geocoder/GeocoderServiceTest.cs
  source/backend/tests/dal/Libraries/Geocoder/ParameterExtensionsTest.cs
Labels: enhancement, 5.12

#4882 PSP-10565: InventoryTab issue
  source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx
Labels: bug, 5.11

#4875 PSP-10338: UI UX Clean Up - Disposition - Documents and Notes tab
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionHeader.test.tsx.snap
Labels: bug, 5.11

#4881 PSP-10194 : Property information without PIN/PID
  source/backend/api/Areas/Tools/Controllers/LtsaController.cs
  source/backend/ltsa/LtsaService.cs
  source/frontend/src/features/mapSideBar/lease/LeaseView.test.tsx
  source/frontend/src/features/mapSideBar/management/ManagementView.test.tsx
  source/frontend/src/features/mapSideBar/property/ComposedProperty.ts
  source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/ltsa/LtsaPlanTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/ltsa/LtsaPlanTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/ltsa/__snapshots__/LtsaPlanTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/hooks/pims-api/useApiLtsa.tsx
  source/frontend/src/hooks/repositories/useComposedProperties.ts
  source/frontend/src/hooks/useLtsa.ts
  source/frontend/src/mocks/ltsa.mock.ts
  source/frontend/src/utils/propertyUtils.ts
Labels: enhancement, 5.11

#4883 psp-10562
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.tsx
  source/frontend/src/components/maps/leaflet/Layers/MarkerLayer.tsx
Labels: bug, 5.11

#4884 Psp 10572 hold acquisition files allow take editing.
  source/backend/api/Solvers/AcquisitionStatusSolver.cs
  source/backend/tests/api/Solvers/AcquisitionStatusSolverTests.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionFileStatusUpdateSolver.ts
Labels: bug, 5.11

#4885 property management view fields.
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/__snapshots__/PropertyActivityEditForm.test.tsx.snap
Labels: bug, 5.11

#4888 PSP-10565: UAT. Adding a Contact in Property via Management tab is not adding a contact - additional fix
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactListView.tsx
Labels: bug, 5.11

#4889 PSP-10572 ensure that the file property is set on the passed fileProp…
  source/frontend/src/features/mapSideBar/router/FilePropertyRouter.tsx
Labels: bug, 5.11

#4890 PSP-10645 : FT:Management : non-admin is still able to see the edit i…
  source/backend/api/Services/ManagementFileService.cs
  source/backend/tests/api/Services/ManagementFileServiceTest.cs
Labels: bug, 5.11

#4893 stop using saveChangesAsync - not supported for now.
  source/backend/dal/Repositories/DocumentQueueRepository.cs
Labels: bug, 5.11

#4897 psp-10647 ensure that draft disabled markers display differently.
  source/frontend/src/components/maps/leaflet/Layers/FilePropertiesLayer.tsx
Labels: bug, 5.11

#4907 PSP-10336: List-view Tables – File Status Field Default Setting
  source/frontend/src/features/acquisition/list/AcquisitionFilter/AcquisitionFilter.test.tsx
  source/frontend/src/features/acquisition/list/interfaces.ts
  source/frontend/src/features/disposition/list/DispositionFilter/DispositionFilter.tsx
  source/frontend/src/features/disposition/list/DispositionFilter/__snapshots__/DispositionFilter.test.tsx.snap
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseFilter/LeaseFilter.test.tsx
  source/frontend/src/features/leases/list/LeaseFilter/LeaseFilter.tsx
  source/frontend/src/features/leases/list/LeaseFilter/__snapshots__/LeaseFilter.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseListView.test.tsx
  source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  source/frontend/src/features/management/list/ManagementFilter/ManagementFilter.tsx
  source/frontend/src/features/management/list/ManagementFilter/__snapshots__/ManagementFilter.test.tsx.snap
  source/frontend/src/features/management/list/__snapshots__/ManagementListView.test.tsx.snap
  source/frontend/src/features/research/list/ResearchFilter/ResearchFilter.test.tsx
  source/frontend/src/features/research/list/ResearchFilter/ResearchFilter.tsx
  source/frontend/src/features/research/list/ResearchListView.test.tsx
Labels: enhancement, 5.12

#4900 psp-10559 | Property Quick information
  source/frontend/src/components/common/ContactLink.tsx
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/styles.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/PropertyQuickInfoContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/SearchView.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/__snapshots__/SearchContainer.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContainer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LocationPopupContainer.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LocationPopupContainer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/MultiplePropertyPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/__snapshots__/LayerPopupContainer.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/__snapshots__/LayerPopupView.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/__snapshots__/LocationPopupContainer.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupContent.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupContent.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/__snapshots__/LayerPopupContent.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/components/__snapshots__/LayerPopupLinks.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/constants.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/styles.ts
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseTeamView.tsx
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/StakeholderPersonContactInfo.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/ExpropriationForm8Details.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/__snapshots__/ExpropriationForm8Details.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/detail/PropertyInterestHoldersViewTable.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/__snapshots__/UpdateStakeHolderForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionSummaryView.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/__snapshots__/OffersAndSaleView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionOffer/dispositionSaleContactDetails/DispositionSaleContactDetails.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/__snapshots__/ConsultationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/__snapshots__/ManagementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/__snapshots__/ManagementFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/ManagementSummaryView.tsx
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/ProjectSummaryView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/PropertyContactList.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/__snapshots__/PropertyContactListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/shared/sidebarPathGenerator.ts
  source/frontend/src/features/notes/list/NoteResults/columns.tsx
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/mocks/featureset.mock.ts
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/layers/parcelMapBC.ts
Labels: enhancement

#4903 HOTFIX - correct boolean draft/disabled marker
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/maps/leaflet/Layers/FilePropertiesLayer.tsx
  source/frontend/src/components/propertySelector/selectedPropertyList/SelectedPropertyRow.tsx
Labels: bug, hotfix, 5.11

#4891 Psp 10591 remove property comments section.
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
Labels: enhancement, 5.12

#4919 PSP-10688 : [HOTFIX] FT-REG: 400 error thrown when activity from Prop…
  source/backend/dal/Repositories/PropertyActivityRepository.cs
Labels: bug, hotfix, 5.11

#4911 Initialize Sequence Generators
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/001_Create_Sequences_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/011_Reset_Sequence_Values_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/011_Reset_Sequence_Values_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/011_Remove_Sequences.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/PIMS S107.00 Change Log.txt
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S107_00/Alter Down/001_Create_Sequences_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S107_00/Alter Down/011_Reset_Sequence_Values_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S107_00/Alter Down/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S107_00/Alter Up/011_Reset_Sequence_Values_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S107_00/Alter Up/master.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S107_00/Build/011_Remove_Sequences.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S107_00/PIMS S107.00 Change Log.txt
Labels: db-migration

#4926 PSP-10707 : Property information edit screen is still displaying comments field
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
Labels: bug

#4923 PSP-10704 [HOTFIX]: FT-REG: Manage Users - Changes on users throws a 422 error
  source/backend/api/Pims.Api.csproj
  source/backend/dal.keycloak/PimsKeycloakService.cs
  source/backend/keycloak/IKeycloakRepository.cs
  source/backend/keycloak/KeycloakRepository.cs
  source/backend/tests/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/ltsa/LtsaPlanTabView.test.tsx
Labels: bug, hotfix

#4925 PSP-10446: Management File contacts
  source/backend/api/Areas/Management/ManagementFileController.cs
  source/backend/api/Services/IManagementFileService.cs
  source/backend/api/Services/ManagementFileService.cs
  source/backend/apimodels/Models/Concepts/ManagementFile/ManagementFileContactMap.cs
  source/backend/apimodels/Models/Concepts/ManagementFile/ManagementFileContactModel.cs
  source/backend/dal/Repositories/Interfaces/IManagementFileRepository.cs
  source/backend/dal/Repositories/ManagementFileRepository.cs
  source/backend/entities/Partials/ManagementFileContact.cs
  source/frontend/src/features/documents/list/DocumentManagementListContainer.tsx
  source/frontend/src/features/management/list/ManagementListView.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/management/ManagementContainer.tsx
  source/frontend/src/features/mapSideBar/management/ManagementView.test.tsx
  source/frontend/src/features/mapSideBar/management/__snapshots__/ManagementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/add/AddManagementContainer.test.tsx
  source/frontend/src/features/mapSideBar/management/add/AddManagementContainer.tsx
  source/frontend/src/features/mapSideBar/management/models/ManagementFileContactFormModel.ts
  source/frontend/src/features/mapSideBar/management/models/ManagementFileContactFormYupSchema.ts
  source/frontend/src/features/mapSideBar/management/router/ManagementRouter.tsx
  source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.tsx
  source/frontend/src/features/mapSideBar/management/tabs/__snapshots__/ManagementFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/ManagementSummaryContainer.tsx
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/ManagementSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/ManagementSummaryView.tsx
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/__snapshots__/ManagementSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/contacts/ManagementFileContactsList.tsx
  source/frontend/src/features/mapSideBar/management/update/UpdateManagementContainer.test.tsx
  source/frontend/src/features/mapSideBar/management/update/UpdateManagementContainer.tsx
  source/frontend/src/features/mapSideBar/management/update/UpdateManagementFileContactContainer.tsx
  source/frontend/src/features/mapSideBar/management/update/forms/ManagementFileContactEditForm.tsx
  source/frontend/src/hooks/pims-api/useApiManagementFileContact.ts
  source/frontend/src/hooks/repositories/useManagementFileRepository.ts
  source/frontend/src/mocks/managementFiles.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_ManagementFileContact.ts
Labels: enhancement

#4930 Backmerge test to dev
  source/backend/dal.keycloak/PimsKeycloakService.cs
  source/backend/keycloak/IKeycloakRepository.cs
  source/backend/keycloak/KeycloakRepository.cs
  source/backend/tests/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
  source/frontend/src/components/maps/leaflet/Layers/FilePropertiesLayer.tsx
  source/frontend/src/components/propertySelector/selectedPropertyList/SelectedPropertyRow.tsx
  source/frontend/src/features/mapSideBar/management/ManagementView.test.tsx
Labels: alignment
