Repository bcgov/PSP, pull requests merged in 2025-01, with the labels that each got.

#4564 PSP-9683 Generated H-120 Compensation Requisition not Populating Electoral District
  source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/dal/Repositories/CompReqFinancialRepository.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/tests/unit/api/Services/CompensationRequisitionServiceTest.cs
  source/backend/tests/unit/dal/Repositories/CompensationRequisitionRepositoryTest.cs
  source/backend/tests/unit/dal/Repositories/ConsultationRepositoryTest.cs
Labels: bug, 5.7

#4566 Bump DEV version - IS97
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4570 PSP-9416 Prevent deletion of properties that have been subdivided or consolidated
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/PropertyOperationService.cs
  source/backend/api/Services/PropertyService.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
Labels: enhancement, 5.8

#4573 PSP-8351: Expand Visible Text Under the Intended Use Field (L/L)
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
Labels: enhancement, 5.7

#4574 PSP-9478: Changing zoom map tooltip and title on the Property Information leaflet
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
Labels: enhancement, 5.7

#4575 PSP-9772: System displays wrong icon for the view document when mouse hovered
  source/frontend/src/features/documents/list/DocumentResults/DocumentResultsColumns.tsx
Labels: bug, 5.7

#4577 PSP-9799 Fix faulty logic when formatting project name and description
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
Labels: bug, 5.7

#4571 PSP-9427 : Acquisition files- Advanced Payment served date field to b…
  source/backend/apimodels/Models/Concepts/ExpropriationPayment/ExpropriationPaymentMap.cs
  source/backend/apimodels/Models/Concepts/ExpropriationPayment/ExpropriationPaymentModel.cs
  source/backend/apimodels/Models/Requests/Document/Upload/DocumentUploadRequest.cs
  source/frontend/src/features/documents/ComposedDocument.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/UpdateForm8Form.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/UpdateForm8Form.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/ExpropriationForm8Details.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/ExpropriationForm8Details.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/__snapshots__/ExpropriationForm8Details.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/models/Form8FormModel.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/models/Form8FormYupSchema.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/compensation/models/CompensationRequisitionFormModel.ts
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/mocks/ExpropriationPayment.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_DocumentStatusTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_DocumentQueue.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_ExpropriationPayment.ts
  source/frontend/src/models/api/generated/ApiGen_Requests_DocumentUploadRequest.ts
Labels: enhancement, 5.7

#4568 Psp 5703 - document repository unit tests.
  source/backend/api/Repositories/Mayan/MayanAuthRepository.cs
  source/backend/api/Services/DocumentQueueService.cs
  source/backend/core.api/Repositories/RestCommon/BaseRestRepository.cs
  source/backend/tests/unit/api/Repositories/BaseRestRepositoryTest.cs
  source/backend/tests/unit/api/Repositories/MayanAuthRepositoryTest.cs
  source/backend/tests/unit/api/Repositories/MayanDocumentRepositoryTest.cs
  source/backend/tests/unit/api/Repositories/MayanMetadataRepositoryTest.cs
Labels: unit-tests

#4560 Psp 9256 tests
  source/backend/tests/unit/api/Helpers/PrincipalExtensionsTest.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/dal/Repositories/AcquisitionRepositoryTest.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/detail/ProjectSummaryView.test.tsx
Labels: unit-tests

#4569 Backmerge test to dev
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S96_00/Alter Down/002_PSP_PIMS_Alter_Down.sql
Labels: alignment

#4580 PSP-9784: IS97 Update automated test suite
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/CDOGSTemplates.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/FinancialCodes.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseConsultations.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeasePeriodPayments.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyPIMSFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchDispositionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchLease.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionConsolidationProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#4581 PSP-9806: Research File: edit icon is displaying incorrect colour for the property research tab
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/detail/PropertyResearchTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/detail/__snapshots__/PropertyResearchTabView.test.tsx.snap
Labels: bug, 5.7

#4579 PSP-9785 Prevent deletion of properties that have been subdivided or consolidated- Acquisition, Research, Disposition
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/ResearchFileService.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/unit/api/Services/ResearchFileServiceTest.cs
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/UpdateForm8Form.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
Labels: enhancement, 5.7

#4578 HOTFIX: psp-9813, psp-9814
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/DocumentFileService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/tests/core/TestHelper.cs
  source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S96_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/frontend/package.json
Labels: bug, hotfix, 5.7

#4585 uat secret GHA name correction
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_hotfix_argo.yml
  .github/workflows/uat_pre_release_hotfix.yml
  .github/workflows/uat_pre_release_hotfix_argo.yml
Labels: bug

#4587 PSP-9520 Acquisition files- Additional fields to be moved from H120 to F forms (Front-end)
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm1.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm9.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm9.tsx
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1YupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/__snapshots__/ExpropriationForm1.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9YupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/__snapshots__/ExpropriationForm9.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/models.ts
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/models/CompensationRequisitionFormModel.ts
  source/frontend/src/features/mapSideBar/compensation/update/CompensationRequisitionYupSchema.ts
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompensationRequisition.ts
  source/frontend/src/models/generate/acquisition/GenerateExpropriationForm1.ts
  source/frontend/src/models/generate/acquisition/GenerateExpropriationForm9.ts
Labels: enhancement, 5.8

#4588 PSP-9825 Table Pagination bug fix
  source/frontend/src/components/Table/PageSizeSelector.test.tsx
  source/frontend/src/components/Table/PageSizeSelector.tsx
  source/frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
  source/frontend/src/components/Table/__snapshots__/Table.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  source/frontend/src/features/admin/users/__snapshots__/ManageUsersPage.test.tsx.snap
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/documents/list/DocumentResults/__snapshots__/DocumentResults.test.tsx.snap
  source/frontend/src/features/documents/list/__snapshots__/DocumentListView.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseSearchResults/__snapshots__/LeaseSearchResults.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/__snapshots__/PropertyContactListView.test.tsx.snap
  source/frontend/src/features/notes/list/NoteResults/__snapshots__/NoteResults.test.tsx.snap
Labels: bug, 5.8

#4590 Backmerge test to dev
  .github/workflows/deploy-prod-start-argo.yml
  .github/workflows/deploy-prod-start.yml
  .github/workflows/retag-test-to-uat-argo.yml
  .github/workflows/retag-test-to-uat.yml
  .github/workflows/uat_hotfix.yml
  .github/workflows/uat_hotfix_argo.yml
  .github/workflows/uat_pre_release_hotfix.yml
  .github/workflows/uat_pre_release_hotfix_argo.yml
  source/backend/api/Services/DocumentFileService.cs
  source/backend/api/Services/DocumentService.cs
  source/backend/tests/core/TestHelper.cs
  source/backend/tests/unit/api/Services/DocumentFileServiceTest.cs
  source/backend/tests/unit/api/Services/DocumentServiceTest.cs
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S96_00/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S96_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S97_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
Labels: release-management

#4592 PSP-9526 | Updated document types
  tools/mayan_sync_helper/json_output/mayan_sync.json
  tools/mayan_sync_helper/xml_definitions/doctype_definitions.xlsx
Labels: enhancement

#4595 PSP-9838: Contact Manager - Add New Contact green button displays incorrect hover effect color
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
Labels: bug, 5.8

#4593 PSP-9630: Historical File on Header - ability to hide Historical File Numbers when headers is expanded
  source/frontend/src/components/common/ExpandableTextList.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/property/__snapshots__/MotiInventoryHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/header/HistoricalNumberFieldView.tsx
Labels: bug, 5.8

#4596 PSP-9803 UI UX: Advanced Filter Map - Reset to Default Button icon
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/FilterContentForm.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/__snapshots__/FilterContentForm.test.tsx.snap
Labels: ui/ux, 5.8

#4598 PSP-9774, PSP-8562: UI UX cleanup
  source/frontend/src/components/common/ActiveIndicator.tsx
  source/frontend/src/components/common/buttons/DownloadButton.tsx
  source/frontend/src/components/common/styles.ts
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/ContactFilterComponent.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactFilterComponent/__snapshots__/ContactFilterComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/__snapshots__/ContactResultComponent.test.tsx.snap
  source/frontend/src/components/contact/ContactManagerView/ContactResultComponent/columns.tsx
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/components/layout/SideNavBar/LeaseAndLicenses.tsx
  source/frontend/src/components/layout/SideNavBar/styles.ts
  source/frontend/src/features/admin/users/__snapshots__/ManageUsersPage.test.tsx.snap
  source/frontend/src/features/admin/users/components/UsersFilterBar.tsx
  source/frontend/src/features/admin/users/constants/index.tsx
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.tsx
  source/frontend/src/features/leases/reports/aggregated/__snapshots__/ExportAggregatedLeasesContainer.test.tsx.snap
  source/frontend/src/features/leases/reports/payments/ExportLeasePaymentsContainer.tsx
  source/frontend/src/features/leases/reports/payments/__snapshots__/ExportLeasePaymentsContainer.test.tsx.snap
  source/frontend/src/features/projects/reports/ProjectExportFormContent.tsx
Labels: ui/ux, 5.8

#4599 Bump version - IS 98
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4601 IS98 Scaffold
  source/backend/entities/ef/PimsAcquisitionFile.cs
  source/backend/entities/ef/PimsAcquisitionFileHist.cs
  source/backend/entities/ef/PimsCompensationRequisitionHist.cs
  source/backend/entities/ef/PimsLease.cs
  source/backend/entities/ef/PimsLeaseHist.cs
  source/backend/entities/ef/PimsPropertyResearchFile.cs
  source/backend/entities/ef/PimsPropertyResearchFileHist.cs
Labels: db-scaffold

#4602 PSP-9815 Property Research Summary comments field doesn't have a limit of character when more than allowed are inserted.
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyResearchContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/UpdatePropertyYupSchema.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/__snapshots__/UpdatePropertyForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyResearch/update/models.ts
  source/frontend/src/features/mapSideBar/router/FilePropertyRouter.tsx
  source/frontend/src/mocks/researchFile.mock.ts
Labels: enhancement, 5.8

#4600 PSP-9762: Major project enhancements - add automated test cases
  testing/PIMS.Tests.Automation/Classes/Project.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/Projects.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProjects.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ProjectSteps.cs
Labels: test-scripts

#4603 PSP-9846 : UI UX Clean Up - map modal - view property info location (…
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LayerPopupView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/__snapshots__/LayerPopupView.test.tsx.snap
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupFlyout.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.test.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/LayerPopupLinks.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/components/__snapshots__/LayerPopupLinks.test.tsx.snap
Labels: enhancement

#4597 Psp 9066 - allow multiple payees on acq comp reqs.
  source/backend/api/Areas/CompensationRequisition/Controllers/CompensationRequisitionController.cs
  source/backend/api/Areas/Leases/Controllers/LeaseStakeholderController.cs
  source/backend/api/Services/AcquisitionFileService.cs
  source/backend/api/Services/CompensationRequisitionService.cs
  source/backend/api/Services/ICompensationRequisitionService.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompReqPayeeMap.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompReqPayeeModel.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionMap.cs
  source/backend/apimodels/Models/Concepts/CompensationRequisition/CompensationRequisitionModel.cs
  source/backend/dal/Repositories/CompensationRequisitionRepository.cs
  source/backend/dal/Repositories/Interfaces/ICompensationRequisitionRepository.cs
  source/backend/entities/Partials/PimsCompReqPayee.cs
  source/backend/tests/unit/api/Services/AcquisitionFileServiceTest.cs
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.test.tsx
  source/frontend/src/features/account/Logout.test.tsx
  source/frontend/src/features/disposition/list/DispositionListView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH120.ts
  source/frontend/src/features/mapSideBar/acquisition/models/LeaseStakeholderModel.ts
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeOptionModel.ts
  source/frontend/src/features/mapSideBar/acquisition/models/PayeeTypeModel.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/add/AddForm8Container.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/update/UpdateForm8Container.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/__snapshots__/CompensationRequisitionDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/list/CompensationListContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/models/AcquisitionPayeeFormModel.ts
  source/frontend/src/features/mapSideBar/compensation/models/CompensationRequisitionFormModel.ts
  source/frontend/src/features/mapSideBar/compensation/update/CompensationRequisitionYupSchema.ts
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/properties/list/PropertyListView.test.tsx
  source/frontend/src/hooks/pims-api/useApiRequisitionCompensations.ts
  source/frontend/src/hooks/repositories/useRequisitionCompensationRepository.ts
  source/frontend/src/mocks/compensations.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompReqPayee.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_CompensationRequisition.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensation.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.test.ts
  source/frontend/src/models/generate/acquisition/GenerateCompensationPayee.ts
  source/frontend/src/utils/test-utils.tsx
  source/frontend/src/utils/utils.ts
  source/frontend/vite.config.ts
Labels: enhancement

#4604 PSP-9837 : UI UX Clean Up - Manage Tables - Create Buttons - move to the top
  source/frontend/src/components/contact/ContactManagerModal.tsx
  source/frontend/src/components/contact/ContactManagerView/ContactManagerView.tsx
  source/frontend/src/components/contact/ContactManagerView/__snapshots__/ContactManagerView.test.tsx.snap
  source/frontend/src/features/acquisition/list/AcquisitionListView.tsx
  source/frontend/src/features/admin/financial-codes/list/FinancialCodeListView.tsx
  source/frontend/src/features/contacts/list/ContactListPage.tsx
  source/frontend/src/features/contacts/list/__snapshots__/ContactListView.test.tsx.snap
  source/frontend/src/features/contacts/styles.ts
  source/frontend/src/features/disposition/list/DispositionListView.tsx
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/leases/list/LeaseListView.tsx
  source/frontend/src/features/leases/list/__snapshots__/LeaseListView.test.tsx.snap
  source/frontend/src/features/projects/list/ProjectListView.tsx
  source/frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
  source/frontend/src/features/research/list/ResearchListView.tsx
  source/frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
Labels: enhancement

#4605 Use named hangfire server and queue - to assist with debugging.
  source/backend/scheduler/Startup.cs
  source/backend/scheduler/appsettings.json
Labels: enhancement

#4606 Fix DB seed - IS 98
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/075_DML_PIMS_ROLE_CLAIM.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S98_00/Build/075_DML_PIMS_ROLE_CLAIM.sql
Labels: bug, db-migration-correction

#4607 HOTFIX psp-9865 - fix map click loading logic.
  source/backend/api/Pims.Api.csproj
  source/frontend/package.json
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
Labels: hotfix

#4614 Revert "R5.7 ETLs"
  source/backend/Dockerfile.scheduler
  source/backend/Pims.Scheduler.Test/Pims.Scheduler.Test.csproj
  source/backend/Pims.Scheduler.Test/Repositories/PimsDocumentQueueRepositoryTests.cs
  source/backend/Pims.Scheduler.Test/Services/DocumentQueueServiceTests.cs
  source/backend/api/Areas/Documents/DocumentQueueController.cs
  source/backend/api/Helpers/Extensions/DocumentUploadRequestExtension.cs
  source/backend/api/Helpers/Extensions/FormFileExtensions.cs
  source/backend/api/README.md
  source/backend/api/Services/IDocumentQueueService.cs
  source/backend/apimodels/CodeTypes/DataSourceTypes.cs
  source/backend/apimodels/CodeTypes/DocumentQueueStatusTypes.cs
  source/backend/apimodels/CodeTypes/DocumentStatusTypes.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileProgressStatusesMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileProgressStatusesModel.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileTakingStatusesMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileTakingStatusesModel.cs
  source/backend/apimodels/Models/Concepts/DocumentQueue/DocumentQueueMap.cs
  source/backend/apimodels/Models/Concepts/DocumentQueue/DocumentQueueModel.cs
  source/backend/apimodels/Models/Concepts/Project/ProjectPersonMap.cs
  source/backend/apimodels/Models/Concepts/Project/ProjectPersonModel.cs
  source/backend/core.api/Repositories/RestCommon/IRestRespository.cs
  source/backend/core.api/Services/BaseService.cs
Labels: bug

#4611 Psp 9893 mayan document queue corrections.
  source/backend/api/Services/DocumentQueueService.cs
  source/backend/scheduler/Startup.cs
  source/backend/tests/unit/api/Services/DocumentQueueServiceTest.cs
Labels: bug

#4610 PSP-9869 Projects - When user inserts duplicate team members, a 400 error is displayed
  source/backend/api/Areas/Projects/Controllers/ProjectController.cs
  source/backend/api/Services/ProjectService.cs
  source/backend/tests/unit/api/Services/ProjectServiceTest.cs
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.test.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectContainer.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectFileYupSchema.ts
  source/frontend/src/features/mapSideBar/project/add/AddProjectForm.test.tsx
  source/frontend/src/features/mapSideBar/project/add/AddProjectForm.tsx
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/models.ts
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/update/UpdateProjectContainer.test.tsx
  source/frontend/src/features/mapSideBar/project/tabs/projectDetails/update/UpdateProjectContainer.tsx
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/mocks/projects.mock.ts
  source/frontend/src/utils/test-utils.tsx
Labels: bug, 5.8

#4615 Backmerge test to dev
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
Labels: release-management

#4616 PSP-9762: Update and creation of new automated test cases
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Drivers/BrowserDriver.cs
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionStakeholders.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DigitalDocumentSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
Labels: test-scripts

#4617 PSP-8975 Map View: Calibrated Zoom Level index Scale
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/BaseMapToggle/BasemapToggle.scss
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
Labels: enhancement, 5.8

#4618 HOTFIX psp-9893 mayan document queue corrections.
  source/backend/api/Pims.Api.csproj
  source/backend/api/Services/DocumentQueueService.cs
  source/backend/scheduler/Startup.cs
  source/backend/tests/unit/api/Services/DocumentQueueServiceTest.cs
  source/frontend/package.json
Labels: hotfix, 5.7

#4620 HOTFIX psp-9666 hotfix: correct loading of partial property ids.
  source/frontend/src/components/maps/leaflet/Layers/util.test.tsx
  source/frontend/src/hooks/layer-api/layerUtils.ts
Labels: bug, hotfix

#4619 PSP-9866 : FT-REG: Digital Documents - system is not allowing the use…
  source/backend/api/Repositories/Mayan/MayanDocumentRepository.cs
  source/backend/core.api/Repositories/RestCommon/BaseRestRepository.cs
Labels: bug

#4622 PSP-9823 prevent L&L files from zooming out too far when toggling ful…
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/MapView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertiesInformation.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/PropertiesInformation.tsx
  source/frontend/src/features/mapSideBar/acquisition/models/LeaseStakeholderModel.ts
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
Labels: bug

#4623 Backmerge test to dev
  source/frontend/src/components/maps/leaflet/Layers/util.test.tsx
  source/frontend/src/hooks/layer-api/layerUtils.ts
Labels: alignment

#4625 Bump IS version
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops
