Repository bcgov/PSP, pull requests merged in 2025-03, with the labels that each got.

#4683 Version bump 5.9
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.test.tsx
Labels: release-management

#4682 HOTFIX: PSP-9491 | Header Layout improvements
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.tsx
  source/frontend/src/features/mapSideBar/project/common/__snapshots__/ProjectHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/header/styles.ts
Labels: enhancement, hotfix, 5.8

#4684 PSP-10137 HOTFIX: Property Management Activity Details - Sub-type is not displayed on the View form
  source/backend/entities/Partials/PropertyMgmtActivitySubtype.cs
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.test.tsx
Labels: bug, hotfix, 5.8

#4687 HOTFIX: psp-10123, psp-10125 ensure comp req displays for view/edit screen.
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
Labels: bug, hotfix

#4686 HOTFIX: Psp 10037 - error modal ignores cancel button click
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderContainer.tsx
  source/frontend/src/hooks/pims-api/useApiInterestHolders.ts
  source/frontend/src/hooks/repositories/useInterestHolderRepository.ts
Labels: bug, hotfix

#4691 IS-101.00 Database Schema - Scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsFormType.cs
Labels: db-scaffold

#4690 HOTFIX: PSP-10147 Lease / License - Export to Excel/CSV returns empty file when the user is in the second page
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/tests/unit/api/Controllers/Reports/LeaseControllerTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
Labels: hotfix, 5.8

#4692 HOTFIX: PSP-10146 Lease & Licenses - Deposits: 404 error thrown when a deposit is deleted
  source/backend/api/Areas/Leases/Controllers/LeaseController.cs
  source/backend/api/Areas/Leases/Controllers/SecurityDepositController.cs
  source/backend/api/Services/SecurityDepositService.cs
  source/backend/apimodels/Models/Concepts/Deposit/SecurityDepositMap.cs
  source/backend/dal/Repositories/SecurityDepositRepository.cs
  source/backend/tests/unit/api/Services/SecurityDepositReturnServiceTest.cs
  source/backend/tests/unit/api/Services/SecurityDepositServiceTest.cs
  source/backend/tests/unit/dal/Repositories/SecurityDepositRepositoryTest.cs
  source/frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.tsx
Labels: hotfix, 5.9

#4693 PSP-10135: IS101 Automation test set changes
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/AdminTools.feature
  testing/PIMS.Tests.Automation/Features/AdminTools.feature.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SubdivisionConsolidation.feature
  testing/PIMS.Tests.Automation/Features/SubdivisionConsolidation.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionOfferSale.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedCompensations.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#4685 PSP-10141: UI/UX - Generate a Form header should be aligned correctly in the Acquisition file screen
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/GenerateFormView.tsx
Labels: ui/ux, 5.9

#4695 HOTFIX: PSP-10138, PSP-10150 Ministry project field is displaying Hyphen("-") prefix if the project doesn't have project number
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
Labels: hotfix, 5.8

#4696 HOTIFX: psp-10149 ensure that user overrides are displayed by L&L property ed…
  source/backend/api/Services/LeaseService.cs
  source/frontend/src/features/leases/shared/propertyPicker/LeaseUpdatePropertySelector.tsx
Labels: bug, hotfix

#4698 Increment UAT hotfix version
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: release-management

#4699 HOTFIX: psp-10149 show user override messages correctly for lease properties.
  source/backend/api/Services/LeaseService.cs
  source/frontend/src/features/leases/shared/propertyPicker/LeaseUpdatePropertySelector.tsx
Labels: bug, hotfix

#4700 Backmerge test to dev
  source/backend/api/Areas/Leases/Controllers/LeaseController.cs
  source/backend/api/Areas/Leases/Controllers/SecurityDepositController.cs
  source/backend/api/Areas/Reports/Controllers/LeaseController.cs
  source/backend/api/Services/LeaseService.cs
  source/backend/api/Services/SecurityDepositService.cs
  source/backend/apimodels/Models/Concepts/Deposit/SecurityDepositMap.cs
  source/backend/apimodels/Models/Concepts/Deposit/SecurityDepositReturnModel.cs
  source/backend/dal/Repositories/LeaseRepository.cs
  source/backend/dal/Repositories/SecurityDepositRepository.cs
  source/backend/entities/Partials/PropertyMgmtActivitySubtype.cs
  source/backend/tests/unit/api/Controllers/Reports/LeaseControllerTest.cs
  source/backend/tests/unit/api/Services/LeaseServiceTest.cs
  source/backend/tests/unit/api/Services/SecurityDepositReturnServiceTest.cs
  source/backend/tests/unit/api/Services/SecurityDepositServiceTest.cs
  source/backend/tests/unit/dal/Repositories/SecurityDepositRepositoryTest.cs
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/DepositsContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/ReceivedDepositModal.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/receivedDepositModal/__snapshots__/ReceivedDepositForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/ReturnDepositForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/deposits/modal/returnedDepositModal/__snapshots__/ReturnDepositForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/models/FormLeaseDepositReturn.ts
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailView.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsView.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionHeader.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/__snapshots__/AcquisitionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/stakeholders/update/UpdateStakeHolderContainer.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.test.tsx
  source/frontend/src/features/mapSideBar/compensation/detail/CompensationRequisitionDetailView.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionHeader.tsx
  source/frontend/src/features/mapSideBar/disposition/common/__snapshots__/DispositionHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/lease/common/LeaseHeader.tsx
  source/frontend/src/features/mapSideBar/lease/common/__snapshots__/LeaseHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/__snapshots__/ProjectContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.tsx
  source/frontend/src/features/mapSideBar/project/common/__snapshots__/ProjectHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/header/styles.ts
  source/frontend/src/features/notes/list/NoteListView.tsx
  source/frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiInterestHolders.ts
  source/frontend/src/hooks/repositories/useInterestHolderRepository.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_SecurityDepositReturn.ts
Labels: alignment

#4701 PSP-8716: Reduce Size of Cancel/Save buttons panel
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/common/__snapshots__/UpdateAcquisitionAgreementForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/consolidation/__snapshots__/AddConsolidationView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/dispositionSale/update/__snapshots__/UpdateDispositionSaleView.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/edit/__snapshots__/ConsultationEditForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/SidebarFooter.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
Labels: enhancement, 5.9

#4703 HOTFIX: psp-10164 ensure that pid/pin validations display.
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/utils/YupSchema.ts
Labels: bug, hotfix

#4705 HOTFIX: psp-10161 syntax error - action at wrong object level.
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
Labels: bug, hotfix

#4704 HOTFIX: psp-10125 swap inclusive routing scheme for exclusive with switch.
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
Labels: bug, hotfix

#4702 PSP-10068 : Research Files List View - Search - By PID and PIN
  source/backend/api/Areas/Research/Controllers/SearchController.cs
  source/backend/api/Areas/Research/Models/ResearchFilterModel.cs
  source/backend/dal/Helpers/Extensions/ResearchExtensions.cs
  source/backend/entities/Models/ResearchFilter.cs
  source/frontend/src/features/research/interfaces.ts
  source/frontend/src/features/research/list/ResearchFilter/ResearchFileSelect.tsx
  source/frontend/src/features/research/list/ResearchFilter/ResearchFilter.test.tsx
  source/frontend/src/features/research/list/ResearchFilter/ResearchFilter.tsx
  source/frontend/src/features/research/list/ResearchFilter/__snapshots__/ResearchFilter.test.tsx.snap
  source/frontend/src/features/research/list/ResearchListView.test.tsx
  source/frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
Labels: enhancement

#4708 PSP-10038 Integrate Vector Tile Layers into PIMS
  .github/.trufflehog3.yml
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/public/basemaps.json
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/BaseMapToggle/BasemapToggle.test.tsx
  source/frontend/src/components/maps/leaflet/Control/BaseMapToggle/BasemapToggle.tsx
  source/frontend/src/components/maps/leaflet/Control/BaseMapToggle/types.ts
  source/frontend/src/components/maps/leaflet/Layers/LeafletLayerListener.tsx
  source/frontend/src/components/maps/leaflet/VectorTileLayer/EsriVectorTileLayer.tsx
  source/frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.test.tsx
  source/frontend/src/features/leases/reports/payments/ExportLeasePaymentsContainer.test.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/setupTests.ts
  source/frontend/vite.config.ts
Labels: enhancement, 5.9

#4709 PSP-10155 : UI UX Clean Up - File Details tab text is showing lower c…
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/__snapshots__/DispositionFileTabs.test.tsx.snap
Labels: bug

#4710 PSP-10168 : FT-REG: Acquisition File - Compensation requisition: Some…
  source/frontend/src/features/mapSideBar/compensation/update/UpdateCompensationRequisitionForm.tsx
  source/frontend/src/features/mapSideBar/compensation/update/__snapshots__/UpdateCompensationRequisitionForm.test.tsx.snap
Labels: bug

#4706 PSP-10001 Search based on latitude and longitude coordinates
  source/frontend/src/components/common/form/Input.test.tsx
  source/frontend/src/components/common/form/NumberInput.test.tsx
  source/frontend/src/components/common/form/NumberInput.tsx
  source/frontend/src/components/common/form/__snapshots__/NumberInput.test.tsx.snap
  source/frontend/src/components/common/form/index.ts
  source/frontend/src/components/maps/MapSearch.test.tsx
  source/frontend/src/components/maps/MapSearch.tsx
  source/frontend/src/components/maps/__snapshots__/MapSearch.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeaseUpdatePropertySelector.tsx
  source/frontend/src/features/properties/filter/CoordinateSearch/CoordinateSearchForm.tsx
  source/frontend/src/features/properties/filter/CoordinateSearch/models.test.ts
  source/frontend/src/features/properties/filter/CoordinateSearch/models.ts
  source/frontend/src/features/properties/filter/IPropertyFilter.ts
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  source/frontend/src/features/properties/filter/validation.ts
  source/frontend/src/utils/YupSchema.ts
Labels: enhancement, 5.9

#4714 PSP-10136: Updating leases automated test set IS101
  testing/PIMS.Tests.Automation/Classes/AcquisitionFile.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDeposits.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseImprovements.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseTenants.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/ResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedCompensations.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedModals.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedSelectContact.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/GenericSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
Labels: test-scripts

#4718 Increment DEV version
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4720 PSP-10196 : Remove on-prem sonarqube, and all git action references.
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
  .github/workflows/zap-scan.yml
Labels: devops

#4721 PSP-10179: Disposition Files, H120, CDOGS new automated test cases
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/AdminTools.feature
  testing/PIMS.Tests.Automation/Features/AdminTools.feature.cs
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/CDOGSTemplates.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionOfferSale.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedCompensations.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AdminToolSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
Labels: test-scripts
