Repository bcgov/PSP, pull requests merged in 2025-04, with the labels that each got.

#4724 Backmerge test to dev
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
Labels: release-management

#4711 Psp 10010 - service/repository implementation.
  Makefile
  source/backend/api/Areas/Tools/Controllers/BctfaOwnershipController.cs
  source/backend/api/Services/BctfaOwnershipService.cs
  source/backend/api/Services/IBctfaOwnershipService.cs
  source/backend/api/Startup.cs
  source/backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
  source/backend/dal/PIMSContextFactory.cs
  source/backend/dal/Repositories/Interfaces/IPmbcBctfaPidRepository.cs
  source/backend/dal/Repositories/PmbcBctfaPidRepository.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PmbcBctfaParcelPolygonFabric.cs
  source/backend/entities/ef/PmbcBctfaPid.cs
  source/backend/entities/ef/PmbcParcelPolygonFabric.cs
Labels: enhancement

#4722 PSP-10097: Deleting constant looping on Property Information header
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
Labels: enhancement, 5.9

#4717 Psp 10144
  source/frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/PropertyContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/AssociationContent.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/LeaseAssociationContent.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/PropertyAssociationTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyAssociations/__snapshots__/PropertyAssociationTabView.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.test.tsx
  source/frontend/vite.config.ts
Labels: bug

#4732 psp-10178 Increase map native zoom to match new basemap implementation.
  source/frontend/src/constants/strings.tsx
Labels: enhancement

#4725 PSP-10208: UI UX Clean Up - Larger header
  source/frontend/src/components/common/styles.ts
  source/frontend/src/features/mapSideBar/compensation/CompensationRequisitionTrayView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/__snapshots__/PropertyActivityEditForm.test.tsx.snap
Labels: enhancement, 5.9

#4728 PSP-10120: Remove the dates from the current forms section- Form 1, 8 and 9
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm1.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm9.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateExpropriationForm9.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/ExpropriationForm1YupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form1/__snapshots__/ExpropriationForm1.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/UpdateForm8Form.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/UpdateForm8Form.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/ExpropriationForm8Details.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/ExpropriationForm8Details.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/details/__snapshots__/ExpropriationForm8Details.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/models/Form8FormModel.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form8/models/Form8FormYupSchema.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/ExpropriationForm9YupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/form9/__snapshots__/ExpropriationForm9.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/models.ts
  source/frontend/src/models/generate/acquisition/GenerateExpropriationForm1.ts
  source/frontend/src/models/generate/acquisition/GenerateExpropriationForm9.ts
Labels: enhancement, 5.9

#4731 psp-10192 show all properties by plan# when searching.
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
Labels: enhancement

#4736 Updated PIMS_EXPROP_OWNER_HISTORY table and processes
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/000_Expropriation_Date_Read_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/999_Expropriation_Date_Write_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/Schema Compare.zip
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/000_Expropriation_Date_Read_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/999_Expropriation_Date_Write_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/Schema Compare.zip
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/002_PSP_PIMS_Build.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S102_00/Alter Down/000_Expropriation_Date_Read_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S102_00/Alter Down/002_PSP_PIMS_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S102_00/Alter Down/999_Expropriation_Date_Write_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S102_00/Alter Up/000_Expropriation_Date_Read_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S102_00/Alter Up/002_PSP_PIMS_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S102_00/Alter Up/999_Expropriation_Date_Write_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S102_00/Build/002_PSP_PIMS_Build.sql
Labels: db-migration-correction

#4737 IS-102.00 Database Schema - Scaffold
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcquisitionOwner.cs
  source/backend/entities/ef/PimsExpropOwnerHistory.cs
  source/backend/entities/ef/PimsExpropOwnerHistoryHist.cs
  source/backend/entities/ef/PimsExpropriationNotice.cs
  source/backend/entities/ef/PimsExpropriationVesting.cs
  source/backend/entities/ef/PimsInterestHolder.cs
  source/backend/entities/ef/PimsOrganization.cs
  source/backend/entities/ef/PimsPerson.cs
Labels: db-scaffold

#4729 PSP-9933 Acquisition - Add a "Physical file details" text field
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileMap.cs
  source/backend/apimodels/Models/Concepts/AcquisitionFile/AcquisitionFileModel.cs
  source/frontend/src/components/layout/Healthcheck/HealthcheckContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionFileYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/__snapshots__/AcquisitionFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionSummaryView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/__snapshots__/AcquisitionSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/models.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionFileYupSchema.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/__snapshots__/UpdateAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/models.ts
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/mocks/acquisitionFiles.mock.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_AcquisitionFile.ts
  source/frontend/src/models/defaultInitializers.ts
Labels: enhancement, 5.9

#4739 PSP-9900 : PIMS service availability notifications
  source/frontend/src/components/layout/Healthcheck/HealthcheckContainer.tsx
Labels: bug

#4727 PSP-10217 : Green toast message appears when property is added/remove…
  source/frontend/src/hooks/repositories/usePropertyLeaseRepository.ts
Labels: bug

#4733 PSP-8758 : Property Information Pane: Property Address - Populate “Pr…
  source/frontend/src/components/layout/Healthcheck/HealthcheckContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: enhancement

#4740 correct production GHA errors.
  .github/workflows/deploy-prod-end.yml
  .github/workflows/deploy-prod-start.yml
Labels: bug, devops

#4738 Psp 10088 geographic search
  source/frontend/IGeographicNames.ts
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/common/TooltipWrapper.tsx
  source/frontend/src/components/maps/MapSearch.test.tsx
  source/frontend/src/components/maps/MapSearch.tsx
  source/frontend/src/components/maps/__snapshots__/MapSearch.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/constants/API.ts
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeaseUpdatePropertySelector.tsx
  source/frontend/src/features/properties/filter/GeographicNameInput.test.tsx
  source/frontend/src/features/properties/filter/GeographicNameInput.tsx
  source/frontend/src/features/properties/filter/IPropertyFilter.ts
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/filter/__snapshots__/GeographicNameInput.test.tsx.snap
  source/frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  source/frontend/src/hooks/pims-api/interfaces/IGeographicNames.ts
  source/frontend/src/hooks/pims-api/interfaces/IGeographicNamesProperties.ts
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/pims-api/useApiGeographicNames.ts
  source/frontend/src/hooks/useGeographicNamesRepository.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: enhancement

#4719 PSP-10085 : UI UX Clean Up - All the files - related to ticket 9824
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.test.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseContainer.tsx
  source/frontend/src/features/leases/models/LeaseStatusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/detail/AcquisitionFileStatusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/DispositionStatusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/ResearchStatusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/UpdateSummaryContainer.tsx
Labels: enhancement

#4743 PSP-10179: Additional automated test cases
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Projects.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/SubdivisionConsolidation.feature
  testing/PIMS.Tests.Automation/Features/SubdivisionConsolidation.feature.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/MapFeatures.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SubdivisionConsolidationProperties.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LoginSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/SubdivisionsConsolidationsSteps.cs
Labels: test-scripts

#4744 PSP-9900 : Notification services
  source/frontend/package-lock.json
  source/frontend/src/components/layout/Healthcheck/HealthcheckContainer.tsx
  source/frontend/src/components/layout/Healthcheck/HealthcheckView.test.tsx
  source/frontend/src/components/layout/Healthcheck/HealthcheckView.tsx
  source/frontend/src/components/layout/Healthcheck/__snapshots__/HealthcheckView.test.tsx.snap
Labels: bug

#4715 PSP-10016 Implement browser telemetry
  Makefile
  docker-compose.yml
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/public/tenants/tenant.json
  source/frontend/src/components/common/form/UserRegionSelect/UserRegionSelectContainer.tsx
  source/frontend/src/customAxios.ts
  source/frontend/src/features/account/Login.tsx
  source/frontend/src/features/admin/access-request/AccessRequestContainer.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/UpdateLeaseForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/fileDetails/update/UpdateAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.test.tsx
  source/frontend/src/features/research/list/ResearchListView.test.tsx
  source/frontend/src/features/research/list/ResearchListView.tsx
  source/frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/useKeycloakWrapper.tsx
  source/frontend/src/index.tsx
  source/frontend/src/setupTests.ts
  source/frontend/src/telemetry/config.ts
  source/frontend/src/telemetry/index.ts
  source/frontend/src/telemetry/metrics.ts
  source/frontend/src/telemetry/traces.ts
  source/frontend/src/telemetry/traces/BrowserAttributesSpanProcessor.ts
  source/frontend/src/telemetry/traces/ReactRouterSpanProcessor.ts
  source/frontend/src/telemetry/traces/SpanEnrichment.ts
  source/frontend/src/telemetry/traces/UserInfoSpanProcessor.ts
  source/frontend/src/telemetry/users/UserAPI.test.ts
  source/frontend/src/telemetry/users/UserAPI.ts
  source/frontend/src/telemetry/utils.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
  source/frontend/src/tenants/tenant.tsx
  source/frontend/src/utils/TestCommonWrapper.tsx
  source/frontend/src/utils/getKeycloakEventHandler.test.ts
  source/frontend/src/utils/getKeycloakEventHandler.ts
  source/frontend/vite.config.ts
  tools/jaeger/jaeger-config.yaml
  tools/otel-collector/otel-config.yaml
  tools/prometheus/prometheus.yml
Labels: enhancement, 5.9

#4745 PSP-10279 : FT:LTSA Service degradation notification is popping up on the screen even after service is looking fine
  source/backend/api/Helpers/Healthchecks/PimsLtsaHealthcheck.cs
  source/frontend/src/components/layout/Healthcheck/HealthcheckContainer.test.tsx
  source/frontend/src/components/layout/Healthcheck/HealthcheckContainer.tsx
  source/frontend/src/hooks/pims-api/interfaces/IHealthcheckResponse.ts
  source/frontend/src/hooks/pims-api/interfaces/ISystemCheck.ts
  source/frontend/src/layouts/models/HealthcheckMessagesTypes.ts
Labels: bug

#4746 Ignore pids that cannot be translated to integers.
  source/backend/api/Areas/Tools/Controllers/LtsaController.cs
  source/backend/tests/unit/api/Controllers/Tools/LtsaControllerTest.cs
Labels: bug

#4752 PSP-8641 | Lease payee/tenant label update
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/StakeholderPersonContactInfo.tsx
Labels: enhancement

#4747 psp-10148 allow updates to leases with pre-existing retired properties.
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
Labels: bug

#4750 psp-10285, psp-10286 ensure that disposition files save correctly.
  source/backend/api/Services/DispositionFileService.cs
  source/backend/tests/unit/api/Services/DispositionFileServiceTest.cs
  source/frontend/src/features/leases/models/LeaseStatusUpdateSolver.ts
  source/frontend/src/features/mapSideBar/disposition/tabs/fileDetails/detail/update/UpdateDispositionContainer.tsx
Labels: bug

#4734 psp-10008 allow lat/lng search on property picker.
  source/frontend/src/components/common/List/SelectInput.tsx
  source/frontend/src/components/maps/MapSearch.tsx
  source/frontend/src/components/maps/__snapshots__/MapSearch.test.tsx.snap
  source/frontend/src/components/propertySelector/__snapshots__/MapSelectorContainer.test.tsx.snap
  source/frontend/src/components/propertySelector/models.ts
  source/frontend/src/components/propertySelector/search/LayerFilter.test.tsx
  source/frontend/src/components/propertySelector/search/LayerFilter.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySearchSelectorFormView.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.tsx
  source/frontend/src/components/propertySelector/search/__snapshots__/LayerFilter.test.tsx.snap
  source/frontend/src/components/propertySelector/search/__snapshots__/PropertySearchSelectorFormView.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/__snapshots__/LeasePropertySelector.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/properties/filter/CoordinateSearch/CoordinateSearchForm.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  source/frontend/src/hooks/repositories/mapLayer/useFullyAttributedParcelMapLayer.ts
  source/frontend/src/setupTests.ts
Labels: enhancement

#4754 Psp 10291 - ensure that 000-000-000 pid is searchable.
  source/backend/dal/Helpers/Extensions/PropertyViewExtensions.cs
  source/backend/dal/Repositories/PropertyRepository.cs
  source/backend/tests/core/Entities/PropertyHelper.cs
Labels: bug

#4755 PSP-10292: Fix Management Activity Header
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/PropertyActivityDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/__snapshots__/PropertyActivityEditForm.test.tsx.snap
Labels: bug, 5.9

#4756 use "sub" instead of idir_user_guid to identify users.
  source/backend/api/Pims.Api.csproj
  source/backend/api/Startup.cs
  source/backend/api/appsettings.Development.json
  source/backend/api/appsettings.Docker.json
  source/backend/api/appsettings.Local.json
  source/backend/api/appsettings.json
  source/backend/core/Extensions/IdentityExtensions.cs
  source/backend/tests/core/PrincipalHelper.cs
  source/backend/tests/unit/dal/Core/Extensions/IdentityExtensionsTest.cs
  source/backend/tests/unit/dal/Repositories/AccessRequestRepositoryTest.cs
  source/frontend/src/AppRouter.test.tsx
  source/frontend/src/components/common/form/UserRegionSelect/UserRegionSelectContainer.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/hooks/useKeycloakWrapper.tsx
  source/frontend/src/utils/test-utils.tsx
Labels: 5.9, security

#4751 Psp 10193 do not allow selecting a property from the map if there are multiple at a location.
  source/frontend/src/components/propertySelector/MapClickMonitor.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.test.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.test.tsx
  source/frontend/src/utils/mapPropertyUtils.test.tsx
Labels: enhancement, 5.9

#4757 psp-10298 styling corrections.
  source/frontend/src/components/common/form/Select.scss
  source/frontend/src/components/maps/__snapshots__/MapSearch.test.tsx.snap
  source/frontend/src/features/leases/reports/aggregated/ExportAggregatedLeasesContainer.tsx
  source/frontend/src/features/leases/reports/aggregated/__snapshots__/ExportAggregatedLeasesContainer.test.tsx.snap
  source/frontend/src/features/leases/reports/payments/ExportLeasePaymentsContainer.tsx
  source/frontend/src/features/leases/reports/payments/__snapshots__/ExportLeasePaymentsContainer.test.tsx.snap
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
Labels: bug

#4758 fix environment variable name - this way we don't need to make a chan…
  source/backend/api/Startup.cs
Labels: bug

#4759 PSP-10301: Fix FA layer auth issue
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
Labels: bug

#4761 Restore geoserver layer configuration
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_BOUNDARY_LITE_VW/featuretype.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_BOUNDARY_LITE_VW/layer.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_BOUNDARY_VW/featuretype.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_BOUNDARY_VW/layer.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_LITE_VW/featuretype.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_LITE_VW/layer.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_VW/featuretype.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_LOCATION_VW/layer.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_VW/featuretype.xml
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_VW/layer.xml
Labels: alignment

#4763 Bump version - 5.10
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops

#4767 Management sidebar, icon, navigation.
  source/frontend/src/assets/images/management-grey-icon.svg
  source/frontend/src/assets/images/management-icon.svg
  source/frontend/src/components/layout/SideNavBar/Management.tsx
  source/frontend/src/components/layout/SideNavBar/NavIcon.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.test.tsx
  source/frontend/src/components/layout/SideNavBar/SideNavbar.tsx
  source/frontend/src/components/layout/SideNavBar/SideTray.tsx
  source/frontend/src/components/layout/SideNavBar/__snapshots__/SideNavbar.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/ManagementView.tsx
  source/frontend/src/features/mapSideBar/management/__snapshots__/ManagementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/hooks/pims-api/useApiManagementFile.ts
  source/frontend/src/hooks/repositories/useManagementProvider.ts
Labels: enhancement

#4768 Test hotfixes
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/leaflet/Layers/LeafletLayerListener.tsx
  source/frontend/src/components/maps/leaflet/VectorTileLayer/EsriVectorTileLayer.tsx
Labels: 5.9

#4771 Backmerge test into dev
  source/frontend/package-lock.json
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/leaflet/Layers/LeafletLayerListener.tsx
  source/frontend/src/components/maps/leaflet/VectorTileLayer/EsriVectorTileLayer.tsx
Labels: alignment

#4774 PSP-10312 Management File Notes
  source/backend/api/Areas/Notes/Controllers/NoteController.cs
  source/backend/api/Services/NoteService.cs
  source/backend/dal/Repositories/EntityNoteRepository.cs
  source/backend/dal/Repositories/Interfaces/IEntityNoteRepository.cs
  source/backend/tests/core/Entities/NoteHelper.cs
  source/backend/tests/unit/api/Services/NoteServiceTest.cs
  source/backend/tests/unit/dal/Repositories/NoteRepositoryTest.cs
  source/frontend/src/features/mapSideBar/acquisition/tabs/AcquisitionFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/expropriation/ExpropriationTabContainerView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/tabs/DispositionFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/management/update/UpdateManagementForm.test.tsx
  source/frontend/src/features/mapSideBar/research/tabs/ResearchTabsContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/tabs/__snapshots__/ResearchTabsContainer.test.tsx.snap
  source/frontend/src/features/notes/list/NoteListView.test.tsx
  source/frontend/src/features/notes/list/NoteListView.tsx
  source/frontend/src/features/notes/list/__snapshots__/NoteListView.test.tsx.snap
  source/frontend/src/hooks/repositories/useNoteRepository.ts
  source/frontend/src/utils/getKeycloakEventHandler.test.ts
Labels: enhancement
