Repository bcgov/PSP, pull requests merged in 2025-08, with the labels that each got.

#4936 psp-10615 | Quick info and right side refactor
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/AdvancedFilterButton.tsx
  source/frontend/src/components/maps/leaflet/Control/AdvancedFilter/__snapshots__/AdvancedFilterButton.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersControl.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersControl.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/Search/PropertyQuickInfoContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/SearchView.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/__snapshots__/SearchContainer.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/SearchControl/SearchControl.tsx
  source/frontend/src/components/maps/leaflet/Control/WorklistControl/WorklistControl.tsx
  source/frontend/src/components/maps/leaflet/styles.ts
  source/frontend/src/features/properties/map/MapContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/features/properties/worklist/WorklistContainer.tsx
  source/frontend/src/features/rightSideLayout/RightSideContainer.tsx
  source/frontend/src/features/rightSideLayout/RightSideLayout.tsx
  source/frontend/src/features/rightSideLayout/__snapshots__/AdvancedFilterBar.test.tsx.snap
  source/frontend/src/mocks/mapFSM.mock.ts
Labels: enhancement

#4939 PSP-8338: UI UX Clean Up - Verbiage - MOTI to MOTT
  source/frontend/public/tenants/tenant.json
  source/frontend/src/features/account/Login.test.tsx
  source/frontend/src/features/account/__snapshots__/Login.test.tsx.snap
  source/frontend/src/features/account/__snapshots__/LoginLoading.test.tsx.snap
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/__snapshots__/AcquisitionSearchResults.test.tsx.snap
  source/frontend/src/features/acquisition/list/AcquisitionSearchResults/columns.tsx
  source/frontend/src/features/admin/access-request/AccessRequestForm.tsx
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestContainer.test.tsx.snap
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestForm.test.tsx.snap
  source/frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.test.tsx.snap
  source/frontend/src/features/admin/access/__snapshots__/ManageAccessRequestsPage.test.tsx.snap
  source/frontend/src/features/admin/access/constants/constants.tsx
  source/frontend/src/features/admin/edit-user/EditUserForm.tsx
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserContainer.test.tsx.snap
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserForm.test.tsx.snap
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  source/frontend/src/features/admin/users/__snapshots__/ManageUsersPage.test.tsx.snap
  source/frontend/src/features/admin/users/constants/index.tsx
  source/frontend/src/features/disposition/list/DispositionSearchResults/__snapshots__/DispositionSearchResults.test.tsx.snap
  source/frontend/src/features/disposition/list/DispositionSearchResults/columns.tsx
  source/frontend/src/features/disposition/list/__snapshots__/DispositionListView.test.tsx.snap
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseYupSchema.ts
  source/frontend/src/features/leases/add/AdministrationSubForm.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AdministrationSubForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/DetailAdministration.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/details/__snapshots__/UpdateLeaseForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/add/AddProjectForm.tsx
  source/frontend/src/features/mapSideBar/project/add/__snapshots__/AddProjectForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/project/common/ProjectHeader.tsx
  source/frontend/src/features/mapSideBar/project/common/__snapshots__/ProjectHeader.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/UpdatePropertyDetailsForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetails/update/__snapshots__/UpdatePropertyDetailsForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/TakesDetailView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/__snapshots__/TakesDetailView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/TakeSubForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/takes/update/__snapshots__/TakeUpdateForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchHeader.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchHeader.test.tsx.snap
  source/frontend/src/features/research/list/ResearchSearchResults/ResearchSearchResults.tsx
  source/frontend/src/features/research/list/ResearchSearchResults/__snapshots__/ResearchSearchResults.test.tsx.snap
  source/frontend/src/features/research/list/__snapshots__/ResearchListView.test.tsx.snap
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/MOTI.ts
Labels: enhancement, 5.12

#4944 PSP-10722 : “Management Contact” section is not displaying in the right location
  source/frontend/src/features/mapSideBar/management/__snapshots__/ManagementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/__snapshots__/ManagementFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/ManagementSummaryView.tsx
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/__snapshots__/ManagementSummaryView.test.tsx.snap
Labels: bug

#4947 PSP-8338: Adding some more changes from MOTI to MOTT
  source/backend/api/Services/DispositionFileService.cs
  source/backend/api/Services/ManagementFileService.cs
  source/backend/tests/api/Services/DispositionFileServiceTest.cs
  source/backend/tests/api/Services/ManagementFileServiceTest.cs
  source/frontend/src/features/leases/add/FeeDeterminationSubForm.tsx
  source/frontend/src/features/leases/detail/LeasePages/details/DetailFeeDetermination.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/common/ResearchFileNameGuide.tsx
  source/frontend/src/features/mapSideBar/research/common/__snapshots__/ResearchFileNameGuide.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/tabs/fileDetails/update/__snapshots__/UpdateSummaryForm.test.tsx.snap
Labels: enhancement, 5.12

#4949 Psp 10681 display layer information based on active property boundary
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/common/mapFSM/useLocationFeatureLoader.tsx
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/PropertyQuickInfoContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/SearchView.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/__snapshots__/SearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/layer/LayerContent.tsx
  source/frontend/src/features/mapSideBar/layer/LayerTabContainer.tsx
  source/frontend/src/features/mapSideBar/layer/LayerTabView.tsx
  source/frontend/src/features/mapSideBar/layer/constants.tsx
  source/frontend/src/features/mapSideBar/property/ComposedProperty.ts
  source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryHeader.tsx
  source/frontend/src/features/mapSideBar/property/PropertyContainer.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.test.tsx
  source/frontend/src/features/mapSideBar/shared/detail/PropertyFileContainer.tsx
  source/frontend/src/features/properties/map/MapContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/hooks/layer-api/useGeoServer.ts
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/repositories/mapLayer/useCrownLandLayer.test.ts
  source/frontend/src/hooks/repositories/mapLayer/useCrownLandLayer.ts
  source/frontend/src/hooks/repositories/mapLayer/useHighwayLayer.tsx
  source/frontend/src/hooks/repositories/mapLayer/useLegalAdminBoundariesMapLayer.ts
  source/frontend/src/hooks/repositories/useComposedProperties.ts
  source/frontend/src/mocks/researchFile.mock.ts
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: enhancement

#4951 PSP-10610 Worklist/search/info property file operations - part 2
  source/frontend/src/assets/images/management-icon.svg
  source/frontend/src/assets/scss/_variables.module.scss
  source/frontend/src/components/common/MoreOptionsMenu.test.tsx
  source/frontend/src/components/common/MoreOptionsMenu.tsx
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/maps/leaflet/Control/Search/PropertyQuickInfoContainer.tsx
  source/frontend/src/components/propertySelector/MapSelectorContainer.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.test.tsx
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeaseUpdatePropertySelector.tsx
  source/frontend/src/features/management/list/__snapshots__/ManagementListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AddAcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/consolidation/AddConsolidationContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/add/AddDispositionContainer.tsx
  source/frontend/src/features/mapSideBar/management/add/AddManagementContainer.test.tsx
  source/frontend/src/features/mapSideBar/management/add/AddManagementContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/features/properties/worklist/MoreOptionsDropdown.test.tsx
  source/frontend/src/features/properties/worklist/MoreOptionsDropdown.tsx
  source/frontend/src/features/properties/worklist/ParcelItem.tsx
  source/frontend/src/features/properties/worklist/WorklistContainer.tsx
  source/frontend/src/features/properties/worklist/WorklistView.test.tsx
  source/frontend/src/features/properties/worklist/WorklistView.tsx
  source/frontend/src/features/properties/worklist/__snapshots__/WorklistView.test.tsx.snap
  source/frontend/src/features/properties/worklist/context/WorklistContext.tsx
  source/frontend/src/features/rightSideLayout/RightSideLayout.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: 5.12

#4956 psp-10680 | Re-added popup for multi-properties
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/PropertyQuickInfoContainer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/LocationPopupContainer.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/MultiplePropertyPopupView.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/features/properties/parcelList/ParcelItem.test.tsx
  source/frontend/src/features/properties/parcelList/ParcelItem.tsx
  source/frontend/src/features/properties/parcelList/ParcelListView.tsx
  source/frontend/src/features/properties/worklist/WorklistMapClickMonitor.tsx
  source/frontend/src/features/properties/worklist/WorklistView.tsx
Labels: enhancement

#4959 psp-10698 correct null pointer error.
  source/frontend/src/hooks/repositories/useComposedProperties.ts
Labels: bug

#4960 psp-10528 | Highway search by plan #
  source/frontend/src/components/common/mapFSM/models.ts
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/HighwayList.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/SearchView.tsx
  source/frontend/src/components/maps/leaflet/LayerPopup/MultiplePropertyPopupView.tsx
  source/frontend/src/components/maps/leaflet/Layers/HighwayParcelsLayer.tsx
  source/frontend/src/components/maps/leaflet/Layers/MapsearchParcelsLayer.tsx
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/features/properties/parcelList/ParcelListView.tsx
  source/frontend/src/features/properties/worklist/WorklistMapClickMonitor.tsx
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
  source/frontend/src/hooks/repositories/mapLayer/useHighwayLayer.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
Labels: enhancement

#4964 This is a stopgap fix that will allow users to view non parcel or pim…
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/features/mapSideBar/property/InventoryTabs.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/MotiInventoryContainer.tsx
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
Labels: enhancement

#4963 POC Improvements
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/PropertyQuickInfoContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/SearchControl/SearchControl.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/features/rightSideLayout/RightSideContainer.tsx
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: bug, enhancement

#4965 temporary workaround for psp-10701
  source/backend/dal/Repositories/AcquisitionFileRepository.cs
Labels: bug

#4966 PSP-10616 remove property selector
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.test.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeaseUpdatePropertySelector.tsx
  source/frontend/src/features/leases/shared/propertyPicker/__snapshots__/LeasePropertySelector.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/SelectedPropertyHeaderRow.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/AcquisitionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AddAcquisitionForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/LeaseView.test.tsx
  source/frontend/src/features/mapSideBar/management/ManagementView.test.tsx
  source/frontend/src/features/mapSideBar/management/add/__snapshots__/AddManagementContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/form/ManagementPropertiesSubForm.test.tsx
  source/frontend/src/features/mapSideBar/management/form/ManagementPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/management/form/__snapshots__/ManagementPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/add/AddResearchForm.test.tsx
  source/frontend/src/features/mapSideBar/research/add/ResearchProperties.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/AddResearchForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.test.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/properties/worklist/WorklistView.test.tsx
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/hooks/useEnrichWithPimsFeatures.ts
  source/frontend/src/hooks/useFeatureDatasetsWithAddresses.ts
  source/frontend/src/utils/mapPropertyUtils.test.tsx
Labels: 5.12

#4970 5.12 hotfix 1: PSP-10784 correct issue with highway layer
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/maps/leaflet/Control/Search/PropertyQuickInfoContainer.tsx
  source/frontend/src/hooks/repositories/mapLayer/useHighwayLayer.tsx
Labels: hotfix, 5.12

#4976 Scaffold s109
  source/backend/apimodels/CodeTypes/FormTypes.cs
  source/backend/apimodels/Models/Concepts/ManagementActivity/ManagementActivityMap.cs
  source/backend/apimodels/Models/Concepts/ManagementActivity/ManagementActivityModel.cs
  source/backend/entities/PimsBaseContext.cs
  source/backend/entities/ef/PimsAcquisitionFile.cs
  source/backend/entities/ef/PimsLease.cs
  source/backend/entities/ef/PimsManagementActivity.cs
  source/backend/entities/ef/PimsManagementActivityHist.cs
  source/backend/entities/ef/PimsManagementFile.cs
  source/backend/entities/ef/PimsPropertyTenureType.cs
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/models.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/models.ts
  source/frontend/src/mocks/PropertyManagementActivity.mock.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_FormTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_ManagementActivity.ts
Labels: db-scaffold

#4978 Added H179PTO code to PIMS_AGREEMENT_TYPE
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Down/124_DML_PIMS_AGREEMENT_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Alter Up/124_DML_PIMS_AGREEMENT_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_LATEST/Build/124_DML_PIMS_AGREEMENT_TYPE.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S109_00/Alter Down/124_DML_PIMS_AGREEMENT_TYPE_Alter_Down.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S109_00/Alter Up/124_DML_PIMS_AGREEMENT_TYPE_Alter_Up.sql
  source/database/mssql/scripts/dbscripts/PSP_PIMS_S109_00/Build/124_DML_PIMS_AGREEMENT_TYPE.sql
Labels: db-migration, db-migration-correction

#4979 PSP-10598 Add legend for layers with multiple colors
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayerDefinitions.ts
  source/frontend/src/components/maps/leaflet/Control/LayersControl/LayersMenu.tsx
  source/frontend/src/components/maps/leaflet/Control/LayersControl/__snapshots__/LayersMenu.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/LayersControl/types.ts
Labels: enhancement, 5.13

#4981 PSP-10755: UI/UX rename "Contact Manager" Field
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditForm.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/__snapshots__/ManagementActivityEditForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/ActivityDetailSubView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/__snapshots__/PropertyActivityEditForm.test.tsx.snap
Labels: enhancement, 5.13

#4980 PSP-10799 HOTFIX: Legal description is not displaying info when user click on the parcel on a map
  source/frontend/public/tenants/tenant.json
  source/frontend/src/components/propertySelector/MapSelectorContainer.test.tsx
  source/frontend/src/components/propertySelector/search/PropertySelectorSearchContainer.test.tsx
  source/frontend/src/tenants/__snapshots__/tenant.test.tsx.snap
  source/frontend/src/tenants/config/defaultTenant.ts
Labels: hotfix, 5.12

#4982 psp-10173 | H-0179 (FS)(P) & H-0179 PTO
  source/backend/apimodels/CodeTypes/AgreementTypes.cs
  source/frontend/src/components/common/SectionListHeader.tsx
  source/frontend/src/constants/formDocumentTypes.ts
  source/frontend/src/features/leases/detail/LeasePages/deposits/__snapshots__/DepositsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/deposits/components/DepositsReceivedContainer/__snapshots__/DepositsReceivedContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/__snapshots__/PeriodPaymentsContainer.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/payments/__snapshots__/PaymentsView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/payment/table/periods/__snapshots__/PaymentPeriodsView.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/__snapshots__/AddLeaseStakeholderForm.test.tsx.snap
  source/frontend/src/features/leases/detail/LeasePages/stakeholders/__snapshots__/ViewStakeholderForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/GenerateFormContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/GenerateFormContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/GenerateFormView.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/formDocumentEntry.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateAgreement.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateH0443.ts
  source/frontend/src/features/mapSideBar/acquisition/common/GenerateForm/hooks/useGenerateLetter.ts
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/AgreementView.tsx
  source/frontend/src/features/mapSideBar/acquisition/tabs/agreement/detail/__snapshots__/AgreementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/compensation/list/__snapshots__/CompensationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/tabs/offersAndSale/__snapshots__/OffersAndSaleView.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/LeaseGenerateFormContainer.tsx
  source/frontend/src/features/mapSideBar/lease/tabs/consultations/detail/__snapshots__/ConsultationListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/__snapshots__/ManagementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/__snapshots__/ManagementFileTabs.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/fileDetails/detail/__snapshots__/ManagementSummaryView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/detail/__snapshots__/PropertyContactListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/takes/detail/__snapshots__/TakesDetailView.test.tsx.snap
  source/frontend/src/features/notes/list/__snapshots__/NoteListContainer.test.tsx.snap
  source/frontend/src/hooks/pims-api/useApiHealth.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_AgreementTypes.ts
  source/frontend/vite.config.ts
Labels: enhancement

#4984 fix dockerfiles. replace explicit imports with importing the entire b…
  source/backend/Dockerfile
  source/backend/Dockerfile.proxy
  source/backend/Dockerfile.scheduler
Labels: bug, 5.13

#4985 HOTFIX: psp-10793, psp-10802, psp-10791
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/maps/leaflet/Layers/MarkerLayer.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/features/properties/filter/GeographicNameInput.tsx
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
Labels: hotfix, 5.12
