Repository bcgov/PSP, pull requests merged in 2025-06, with the labels that each got.

#4832 psp-10544 | Fixes Management File not working
  source/backend/api/Areas/Management/ManagementActivityController.cs
  source/backend/api/Areas/Management/ManagementFileActivityController.cs
  source/frontend/src/features/documents/list/DocumentActivityListContainer.tsx
  source/frontend/src/features/documents/list/DocumentFileListContainer.tsx
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/documents/list/DocumentManagementListContainer.tsx
  source/frontend/src/features/mapSideBar/management/router/ManagementRouter.tsx
  source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.tsx
Labels: bug, hotfix

#4834 Bump UAT hotfix number
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.test.tsx
Labels: alignment, 5.10

#4833 PSP-8964: Fixing inserted bug
  source/frontend/src/assets/scss/App.scss
  source/frontend/src/components/common/form/Multiselect.scss
  source/frontend/src/components/common/form/Select.scss
Labels: enhancement, 5.11

#4835 psp-10561 | Fixed documents being editable even if the list is not editable
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailModal.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
Labels: bug, hotfix

#4848 Backmerge test to dev
  source/backend/api/Areas/Management/ManagementActivityController.cs
  source/backend/api/Areas/Management/ManagementFileActivityController.cs
  source/backend/api/Pims.Api.csproj
  source/backend/core/Http/OpenIdConnectRequestClient.cs
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailContainer.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailModal.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.test.tsx
  source/frontend/src/features/documents/documentDetail/DocumentDetailView.tsx
  source/frontend/src/features/documents/list/DocumentActivityListContainer.tsx
  source/frontend/src/features/documents/list/DocumentFileListContainer.tsx
  source/frontend/src/features/documents/list/DocumentListContainer.tsx
  source/frontend/src/features/documents/list/DocumentListView.tsx
  source/frontend/src/features/documents/list/DocumentManagementListContainer.tsx
  source/frontend/src/features/mapSideBar/management/router/ManagementRouter.tsx
  source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.tsx
Labels: alignment

#4846 PSP-10521 Order for Properties in Files
  source/backend/apimodels/Models/Concepts/DispositionFile/DispositionFilePropertyMap.cs
  source/backend/apimodels/Models/Concepts/Lease/PropertyLeaseMap.cs
  source/backend/apimodels/Models/Concepts/ManagementFile/ManagementFilePropertyMap.cs
  source/backend/dal/Repositories/AcquisitionFilePropertyRepository.cs
  source/backend/dal/Repositories/DispositionFilePropertyRepository.cs
  source/backend/dal/Repositories/ManagementFilePropertyRepository.cs
  source/backend/dal/Repositories/PropertyLeaseRepository.cs
  source/backend/dal/Repositories/ResearchFilePropertyRepository.cs
  source/frontend/src/components/common/HeaderField/StatusField.tsx
  source/frontend/src/components/common/buttons/RestrictedEditControl.tsx
  source/frontend/src/components/common/buttons/index.ts
  source/frontend/src/features/leases/hooks/useLeaseDetail.ts
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionContainer.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/AcquisitionView.tsx
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/models.ts
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionMenu.test.tsx
  source/frontend/src/features/mapSideBar/acquisition/common/AcquisitionMenu.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionContainer.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.test.tsx
  source/frontend/src/features/mapSideBar/disposition/DispositionView.tsx
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.test.tsx
  source/frontend/src/features/mapSideBar/disposition/common/DispositionMenu.tsx
  source/frontend/src/features/mapSideBar/disposition/models/DispositionFormModel.ts
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/management/ManagementContainer.test.tsx
  source/frontend/src/features/mapSideBar/management/ManagementContainer.tsx
  source/frontend/src/features/mapSideBar/management/ManagementView.test.tsx
  source/frontend/src/features/mapSideBar/management/ManagementView.tsx
  source/frontend/src/features/mapSideBar/management/__snapshots__/ManagementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/common/ManagementMenu.test.tsx
  source/frontend/src/features/mapSideBar/management/common/ManagementMenu.tsx
  source/frontend/src/features/mapSideBar/management/models/ManagementFormModel.ts
  source/frontend/src/features/mapSideBar/research/ResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/ResearchContainer.tsx
  source/frontend/src/features/mapSideBar/research/ResearchView.tsx
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/models.ts
  source/frontend/src/features/mapSideBar/research/common/ResearchMenu.test.tsx
  source/frontend/src/features/mapSideBar/research/common/ResearchMenu.tsx
  source/frontend/src/features/mapSideBar/shared/FileMenuView.test.tsx
  source/frontend/src/features/mapSideBar/shared/FileMenuView.tsx
  source/frontend/src/features/mapSideBar/shared/__snapshots__/FileMenuView.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/usePropertyIndexFromUrl.tsx
  source/frontend/src/mocks/propertyAssociations.mock.ts
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: enhancement, 5.11

#4842 PSP-8614 : PIMS Management Tab – Add Activity: Activity Details (Sub-…
  source/backend/api/Areas/Management/ManagementFileActivityController.cs
  source/backend/api/Areas/Management/ManagementFileController.cs
  source/backend/api/Areas/Management/Models/ManagementActivityFilterModel.cs
  source/backend/api/Areas/Property/Controllers/PropertyActivityController.cs
  source/backend/api/Mapping/Lookup/LookupMap.cs
  source/backend/apimodels/CodeTypes/ManagementActivityStatusTypes.cs
  source/backend/apimodels/Models/Concepts/ManagementActivity/ManagementActivitySubTypeMap.cs
  source/backend/apimodels/Models/Concepts/ManagementActivity/ManagementActivitySubTypeModel.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyActivityMap.cs
  source/backend/apimodels/Models/Concepts/Property/PropertyActivityModel.cs
  source/backend/dal/Repositories/ManagementActivityRepository.cs
  source/backend/dal/Repositories/PropertyActivityRepository.cs
  source/backend/entities/Models/ManagementActivityFilter.cs
  source/frontend/src/features/management/activities/list/ManagementActivitiesListView.tsx
  source/frontend/src/features/management/activities/list/filter/ActivitiesFilter.tsx
  source/frontend/src/features/management/activities/list/searchResults/columns.tsx
  source/frontend/src/features/management/activities/models/ManagementActivityFilterModel.ts
  source/frontend/src/features/management/activities/models/ManagementActivitySearchResultModel.ts
  source/frontend/src/features/management/list/ManagementSearchResults/__snapshots__/ManagementSearchResults.test.tsx.snap
  source/frontend/src/features/management/list/__snapshots__/ManagementListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/ManagementFileTabs.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditContainer.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditContainer.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditForm.test.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditForm.tsx
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditFormYupSchema.ts
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/__snapshots__/ManagementActivityEditForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/models.ts
  source/frontend/src/features/mapSideBar/project/ProjectContainerView.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/detail/ActivityDetailSubView.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditContainer.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.test.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditForm.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/__snapshots__/PropertyActivityEditForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/models.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/validation.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/ManagementActivitiesList.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/__snapshots__/ManagementActivitiesListView.test.tsx.snap
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/list/models/PropertyActivityRow.ts
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/models/ManagementActivitySubType.ts
  source/frontend/src/hooks/pims-api/useApiManagementActivities.ts
  source/frontend/src/hooks/repositories/useManagementActivityRepository.ts
  source/frontend/src/mocks/PropertyManagementActivity.mock.ts
  source/frontend/src/mocks/lookups.mock.ts
  source/frontend/src/mocks/managementFiles.mock.ts
  source/frontend/src/models/api/ManagementActivityFilter.ts
  source/frontend/src/models/api/generated/ApiGen_CodeTypes_ManagementActivityStatusTypes.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_ManagementActivitySubType.ts
  source/frontend/src/models/api/generated/ApiGen_Concepts_PropertyActivity.ts
Labels: enhancement

#4839 PSP-10492 | Moved the search bar into the right side bar
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/models.ts
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/MapSearch.tsx
  source/frontend/src/components/maps/MapView.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/SearchContainer.test.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/SearchContainer.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/SearchView.tsx
  source/frontend/src/components/maps/leaflet/Control/Search/__snapshots__/SearchContainer.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Control/SearchControl/SearchControl.tsx
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/components/maps/leaflet/styles.ts
  source/frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
  source/frontend/src/features/properties/filter/CoordinateSearch/CoordinateSearchForm.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.tsx
  source/frontend/src/features/properties/map/__snapshots__/MapContainer.test.tsx.snap
  source/frontend/src/hooks/repositories/mapLayer/usePimsPropertyLayer.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/layers/pimsPropertyLocationView.ts
Labels: enhancement

#4853 PSP-10588 : Property Management Tab - user is not able to create/edit…
  source/frontend/src/features/mapSideBar/management/tabs/activities/edit/ManagementActivityEditContainer.tsx
  source/frontend/src/features/mapSideBar/property/tabs/propertyDetailsManagement/activity/edit/PropertyActivityEditContainer.tsx
Labels: bug

#4849 PSP-10564 Unable to Expose Lease & Licence files by clicking Hyperlinks in PIMS Files Tab
  source/frontend/src/features/leases/models.ts
  source/frontend/src/features/mapSideBar/context/sidebarContext.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.test.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseContainer.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseView.test.tsx
  source/frontend/src/features/mapSideBar/lease/LeaseView.tsx
  source/frontend/src/features/mapSideBar/lease/__snapshots__/LeaseContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/__snapshots__/LeaseView.test.tsx.snap
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/mocks/lease.mock.ts
Labels: bug, 5.11

#4857 PSP-10592 : FT-REG: Error 400 thrown when an Activity from a Manageme…
  source/backend/api/Areas/Management/ManagementFileController.cs
  source/backend/dal/Repositories/PropertyActivityRepository.cs
Labels: bug

#4858 PSP-10580: Updates on test cases IS105
  testing/PIMS.Tests.Automation/Classes/ManagementFile.cs
  testing/PIMS.Tests.Automation/Classes/Property.cs
  testing/PIMS.Tests.Automation/Data/PIMS_Testing_Data.xlsx
  testing/PIMS.Tests.Automation/Features/AcquisitionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/AdminTools.feature.cs
  testing/PIMS.Tests.Automation/Features/Contacts.feature.cs
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature
  testing/PIMS.Tests.Automation/Features/DispositionFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Leases.feature
  testing/PIMS.Tests.Automation/Features/Leases.feature.cs
  testing/PIMS.Tests.Automation/Features/ManagementFiles.feature
  testing/PIMS.Tests.Automation/Features/ManagementFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/Projects.feature.cs
  testing/PIMS.Tests.Automation/Features/Properties.feature.cs
  testing/PIMS.Tests.Automation/Features/ResearchFiles.feature.cs
  testing/PIMS.Tests.Automation/Features/SmokeTest.feature.cs
  testing/PIMS.Tests.Automation/Features/SubdivisionConsolidation.feature.cs
  testing/PIMS.Tests.Automation/PIMS.Tests.Automation.csproj
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionAgreements.cs
  testing/PIMS.Tests.Automation/PageObjects/AcquisitionDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/Contacts.cs
  testing/PIMS.Tests.Automation/PageObjects/DigitalDocuments.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionChecklist.cs
  testing/PIMS.Tests.Automation/PageObjects/DispositionFileDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/LeaseDetails.cs
  testing/PIMS.Tests.Automation/PageObjects/ManagementActivities.cs
  testing/PIMS.Tests.Automation/PageObjects/Notes.cs
  testing/PIMS.Tests.Automation/PageObjects/PageObjectBase.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyInformation.cs
  testing/PIMS.Tests.Automation/PageObjects/PropertyManagementTab.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchAcquisitionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchContacts.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchDispositionFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchProperties.cs
  testing/PIMS.Tests.Automation/PageObjects/SearchResearchFiles.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedActivities.cs
  testing/PIMS.Tests.Automation/PageObjects/SharedFileProperties.cs
  testing/PIMS.Tests.Automation/Reports/TestHooks.cs
  testing/PIMS.Tests.Automation/StepDefinitions/AcquisitionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ContactsSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/DispositionFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/LeaseLicenseSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ManagementFileSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/PropertiesSteps.cs
  testing/PIMS.Tests.Automation/StepDefinitions/ResearchFileSteps.cs
  testing/Testing DB Scripts/DELETE AUTOMATION TEST DATA.sql
Labels: test-scripts

#4855 Psp 10536 survey plan search
  source/frontend/package-lock.json
  source/frontend/package.json
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/models.ts
  source/frontend/src/components/common/mapFSM/useMapSearch.tsx
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/__snapshots__/MapSearch.test.tsx.snap
  source/frontend/src/components/maps/leaflet/Layers/PointClusterer.tsx
  source/frontend/src/components/maps/leaflet/Layers/util.tsx
  source/frontend/src/components/maps/leaflet/Markers/SingleMarker.tsx
  source/frontend/src/constants/API.ts
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeaseUpdatePropertySelector.tsx
  source/frontend/src/features/mapSideBar/MapSideBar.tsx
  source/frontend/src/features/mapSideBar/router/MapRouter.tsx
  source/frontend/src/features/properties/filter/IPropertyFilter.ts
  source/frontend/src/features/properties/filter/PropertyFilter.test.tsx
  source/frontend/src/features/properties/filter/PropertyFilter.tsx
  source/frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
  source/frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
  source/frontend/src/features/properties/map/MapContainer.test.tsx
  source/frontend/src/hooks/layer-api/useLayerQuery.test.tsx
  source/frontend/src/hooks/layer-api/useLayerQuery.tsx
  source/frontend/src/hooks/layer-api/useWfsLayer.ts
  source/frontend/src/hooks/pims-api/interfaces/ITenantConfig.ts
  source/frontend/src/hooks/repositories/mapLayer/useCrownLandLayer.test.ts
  source/frontend/src/hooks/repositories/mapLayer/useCrownLandLayer.ts
  source/frontend/src/mocks/mapFSM.mock.ts
  source/frontend/src/models/layers/crownLand.ts
  source/frontend/src/tenants/config/defaultTenant.ts
  source/frontend/vite.config.ts
Labels: 5.11

#4865 PSP-10458: Padding zeros to PIDs on Tables
  source/frontend/src/features/leases/list/LeaseSearchResults/LeaseProperties.tsx
  source/frontend/src/features/properties/list/columns.tsx
Labels: enhancement, 5.11

#4864 PSP-10568 | Added buttons to zoom into properties from files
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/propertySelector/selectedPropertyList/SelectedPropertyRow.tsx
  source/frontend/src/components/propertySelector/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap
  source/frontend/src/features/leases/add/__snapshots__/AddLeaseContainer.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/LeasePropertySelector.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeaseUpdatePropertySelector.tsx
  source/frontend/src/features/leases/shared/propertyPicker/__snapshots__/LeasePropertySelector.test.tsx.snap
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/SelectedPropertyRow.tsx
  source/frontend/src/features/leases/shared/propertyPicker/selectedPropertyList/__snapshots__/SelectedPropertyRow.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/__snapshots__/AcquisitionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/acquisition/add/__snapshots__/AcquisitionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/__snapshots__/DispositionView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/add/__snapshots__/AddDispositionContainerView.test.tsx.snap
  source/frontend/src/features/mapSideBar/disposition/form/DispositionPropertiesSubForm.tsx
  source/frontend/src/features/mapSideBar/disposition/form/__snapshots__/DispositionPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/lease/__snapshots__/LeaseView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/__snapshots__/ManagementView.test.tsx.snap
  source/frontend/src/features/mapSideBar/management/form/__snapshots__/ManagementPropertiesSubForm.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/__snapshots__/ResearchContainer.test.tsx.snap
  source/frontend/src/features/mapSideBar/research/add/AddResearchContainer.test.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/FileMenuView.test.tsx
  source/frontend/src/features/mapSideBar/shared/FileMenuView.tsx
  source/frontend/src/features/mapSideBar/shared/__snapshots__/FileMenuView.test.tsx.snap
  source/frontend/src/features/mapSideBar/shared/operations/SelectedOperationProperty.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/UpdateProperties.tsx
  source/frontend/src/features/mapSideBar/shared/update/properties/__snapshots__/UpdateProperties.test.tsx.snap
  source/frontend/src/features/mapSideBar/subdivision/AddSubdivisionView.tsx
  source/frontend/src/features/mapSideBar/subdivision/__snapshots__/AddSubdivisionView.test.tsx.snap
  source/frontend/src/utils/mapPropertyUtils.ts
Labels: enhancement, 5.11

#4869 Scaffold update
  source/backend/entities/ef/PimsPropertyBoundaryResearchVw.cs
  tools/geoserver/geoserver_data/psp/mssql/PIMS_PROPERTY_BOUNDARY_RESEARCH_VW/layer.xml
Labels: db-scaffold

#4871 PSP-10454 | Added marker to location related searches
  source/frontend/src/components/common/mapFSM/MapStateMachineContext.tsx
  source/frontend/src/components/common/mapFSM/machineDefinition/mapMachine.ts
  source/frontend/src/components/common/mapFSM/machineDefinition/types.ts
  source/frontend/src/components/maps/MapLeafletView.tsx
  source/frontend/src/components/maps/MapSearch.tsx
  source/frontend/src/components/maps/leaflet/Layers/InventoryLayer.tsx
  source/frontend/src/components/maps/leaflet/Layers/MarkerLayer.tsx
  source/frontend/src/mocks/mapFSM.mock.ts
Labels: enhancement
