Repository bcgov/PSP, pull requests merged in 2025-10, with the labels that each got.

#5022 Increment version - IS-111
  source/backend/api/Pims.Api.csproj
  source/frontend/package-lock.json
  source/frontend/package.json
Labels: devops, 5.14

#5026 PR checks 5.14
  .github/workflows/api-dotnetcore.yml
  .github/workflows/app-react.yml
Labels: devops

#5028 PSP-10884 : FT:Lease&Licence File: New workflow is not populated under "Properties to include in this file" on the Edit screen of Lease file
  source/frontend/src/features/leases/add/AddLeaseContainer.tsx
  source/frontend/src/features/leases/shared/propertyPicker/LeaseUpdatePropertySelector.tsx
  source/frontend/src/features/mapSideBar/research/add/ResearchProperties.tsx
  source/frontend/src/features/mapSideBar/research/add/__snapshots__/ResearchProperties.test.tsx.snap
Labels: bug, 5.13
